package com.insta.hms.mdm.tpas;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.insta.hms.core.patient.registration.PatientInsurancePlansModel;
import com.insta.hms.model.InsuranceSubmissionBatchModel;
import com.insta.hms.util.ViewProfiles;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpaMasterModel generated by hbm2java
 */
@Entity
@Table(name = "tpa_master")
public class TpaMasterModel implements java.io.Serializable {

  @JsonView(ViewProfiles.Public.class)
	private String tpaId;
  @JsonView(ViewProfiles.Public.class)
	private String tpaName;
	private String state;
	private String city;
	private String country;
	private String pincode;
	private String phoneNo;
	private String mobileNo;
	private String emailId;
	private String fax;
	private String contactName;
	private String contactDesignation;
	private String contactPhone;
	private String contactMobile;
	private String contactEmail;
	private String address;
	private Character status;
	private String tpaPdfForm;
	private Date validityEndDate;
	private Integer claimTemplateId;
	private Character defaultClaimTemplate;
	private String tpaCodeObsolete;
	private char sponsorType;
	private BigDecimal perDayRate;
	private char scannedDocRequired;
	private BigDecimal perVisitCopayOp;
	private BigDecimal perVisitCopayIp;
	private Date createdTimestamp;
	private Date updatedTimestamp;
	private char preAuthMode;
	private String claimFormat;
	private Integer sponsorTypeId;
	private String memberIdPattern;
	private Integer maxResubmissionCount;
	private String tinNumber;
	@JsonIgnore
	private Set<PatientInsurancePlansModel> patientInsurancePlans = new HashSet(0);
	@JsonIgnore
	private Set<InsuranceSubmissionBatchModel> insuranceSubmissionBatches = new HashSet(0);

	public TpaMasterModel() {
	}

	public TpaMasterModel(String tpaId) {
	  this.tpaId = tpaId;
	}

	public TpaMasterModel(String tpaId, String tpaName, char sponsorType, char scannedDocRequired, Date createdTimestamp,
			Date updatedTimestamp, char preAuthMode) {
		this.tpaId = tpaId;
		this.tpaName = tpaName;
		this.sponsorType = sponsorType;
		this.scannedDocRequired = scannedDocRequired;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
		this.preAuthMode = preAuthMode;
	}

	public TpaMasterModel(String tpaId, String tpaName, String state, String city, String country, String pincode,
			String phoneNo, String mobileNo, String emailId, String fax, String contactName, String contactDesignation,
			String contactPhone, String contactMobile, String contactEmail, String address, Character status,
			String tpaPdfForm, Date validityEndDate, Integer claimTemplateId, Character defaultClaimTemplate,
			String tpaCodeObsolete, char sponsorType, BigDecimal perDayRate, char scannedDocRequired,
			BigDecimal perVisitCopayOp, BigDecimal perVisitCopayIp, Date createdTimestamp, Date updatedTimestamp,
			char preAuthMode, String claimFormat, Integer sponsorTypeId, String memberIdPattern,
			Integer maxResubmissionCount, String tinNumber) {
		this.tpaId = tpaId;
		this.tpaName = tpaName;
		this.state = state;
		this.city = city;
		this.country = country;
		this.pincode = pincode;
		this.phoneNo = phoneNo;
		this.mobileNo = mobileNo;
		this.emailId = emailId;
		this.fax = fax;
		this.contactName = contactName;
		this.contactDesignation = contactDesignation;
		this.contactPhone = contactPhone;
		this.contactMobile = contactMobile;
		this.contactEmail = contactEmail;
		this.address = address;
		this.status = status;
		this.tpaPdfForm = tpaPdfForm;
		this.validityEndDate = validityEndDate;
		this.claimTemplateId = claimTemplateId;
		this.defaultClaimTemplate = defaultClaimTemplate;
		this.tpaCodeObsolete = tpaCodeObsolete;
		this.sponsorType = sponsorType;
		this.perDayRate = perDayRate;
		this.scannedDocRequired = scannedDocRequired;
		this.perVisitCopayOp = perVisitCopayOp;
		this.perVisitCopayIp = perVisitCopayIp;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
		this.preAuthMode = preAuthMode;
		this.claimFormat = claimFormat;
		this.sponsorTypeId = sponsorTypeId;
		this.memberIdPattern = memberIdPattern;
		this.maxResubmissionCount = maxResubmissionCount;
		this.tinNumber = tinNumber;
	}

	@Id

	@Column(name = "tpa_id", unique = true, nullable = false, length = 15)
	public String getTpaId() {
		return this.tpaId;
	}

	public void setTpaId(String tpaId) {
		this.tpaId = tpaId;
	}

	@Column(name = "tpa_name", nullable = false, length = 200)
	public String getTpaName() {
		return this.tpaName;
	}

	public void setTpaName(String tpaName) {
		this.tpaName = tpaName;
	}

	@Column(name = "state", length = 250)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "city", length = 250)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 250)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "pincode", length = 10)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "phone_no", length = 16)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "mobile_no", length = 16)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "email_id", length = 60)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "fax", length = 30)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "contact_name", length = 50)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_designation", length = 50)
	public String getContactDesignation() {
		return this.contactDesignation;
	}

	public void setContactDesignation(String contactDesignation) {
		this.contactDesignation = contactDesignation;
	}

	@Column(name = "contact_phone", length = 16)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "contact_mobile", length = 16)
	public String getContactMobile() {
		return this.contactMobile;
	}

	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile;
	}

	@Column(name = "contact_email", length = 60)
	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	@Column(name = "address", length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "tpa_pdf_form", length = 3)
	public String getTpaPdfForm() {
		return this.tpaPdfForm;
	}

	public void setTpaPdfForm(String tpaPdfForm) {
		this.tpaPdfForm = tpaPdfForm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "validity_end_date", length = 13)
	public Date getValidityEndDate() {
		return this.validityEndDate;
	}

	public void setValidityEndDate(Date validityEndDate) {
		this.validityEndDate = validityEndDate;
	}

	@Column(name = "claim_template_id")
	public Integer getClaimTemplateId() {
		return this.claimTemplateId;
	}

	public void setClaimTemplateId(Integer claimTemplateId) {
		this.claimTemplateId = claimTemplateId;
	}

	@Column(name = "default_claim_template", length = 1)
	public Character getDefaultClaimTemplate() {
		return this.defaultClaimTemplate;
	}

	public void setDefaultClaimTemplate(Character defaultClaimTemplate) {
		this.defaultClaimTemplate = defaultClaimTemplate;
	}

	@Column(name = "tpa_code_obsolete")
	public String getTpaCodeObsolete() {
		return this.tpaCodeObsolete;
	}

	public void setTpaCodeObsolete(String tpaCodeObsolete) {
		this.tpaCodeObsolete = tpaCodeObsolete;
	}

	@Column(name = "sponsor_type", nullable = false, length = 1)
	public char getSponsorType() {
		return this.sponsorType;
	}

	public void setSponsorType(char sponsorType) {
		this.sponsorType = sponsorType;
	}

	@Column(name = "per_day_rate", precision = 15)
	public BigDecimal getPerDayRate() {
		return this.perDayRate;
	}

	public void setPerDayRate(BigDecimal perDayRate) {
		this.perDayRate = perDayRate;
	}

	@Column(name = "scanned_doc_required", nullable = false, length = 1)
	public char getScannedDocRequired() {
		return this.scannedDocRequired;
	}

	public void setScannedDocRequired(char scannedDocRequired) {
		this.scannedDocRequired = scannedDocRequired;
	}

	@Column(name = "per_visit_copay_op", precision = 10)
	public BigDecimal getPerVisitCopayOp() {
		return this.perVisitCopayOp;
	}

	public void setPerVisitCopayOp(BigDecimal perVisitCopayOp) {
		this.perVisitCopayOp = perVisitCopayOp;
	}

	@Column(name = "per_visit_copay_ip", precision = 10)
	public BigDecimal getPerVisitCopayIp() {
		return this.perVisitCopayIp;
	}

	public void setPerVisitCopayIp(BigDecimal perVisitCopayIp) {
		this.perVisitCopayIp = perVisitCopayIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_timestamp", nullable = false, length = 29)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_timestamp", nullable = false, length = 29)
	public Date getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	@Column(name = "pre_auth_mode", nullable = false, length = 1)
	public char getPreAuthMode() {
		return this.preAuthMode;
	}

	public void setPreAuthMode(char preAuthMode) {
		this.preAuthMode = preAuthMode;
	}

	@Column(name = "claim_format", length = 20)
	public String getClaimFormat() {
		return this.claimFormat;
	}

	public void setClaimFormat(String claimFormat) {
		this.claimFormat = claimFormat;
	}

	@Column(name = "sponsor_type_id")
	public Integer getSponsorTypeId() {
		return this.sponsorTypeId;
	}

	public void setSponsorTypeId(Integer sponsorTypeId) {
		this.sponsorTypeId = sponsorTypeId;
	}

	@Column(name = "member_id_pattern", length = 100)
	public String getMemberIdPattern() {
		return this.memberIdPattern;
	}

	public void setMemberIdPattern(String memberIdPattern) {
		this.memberIdPattern = memberIdPattern;
	}

	@Column(name = "max_resubmission_count")
	public Integer getMaxResubmissionCount() {
		return this.maxResubmissionCount;
	}

	public void setMaxResubmissionCount(Integer maxResubmissionCount) {
		this.maxResubmissionCount = maxResubmissionCount;
	}

	@Column(name = "tin_number", length = 50)
	public String getTinNumber() {
		return this.tinNumber;
	}

	public void setTinNumber(String tinNumber) {
		this.tinNumber = tinNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpaMasterModel")
	public Set<PatientInsurancePlansModel> getPatientInsurancePlans() {
		return this.patientInsurancePlans;
	}

	public void setPatientInsurancePlans(Set<PatientInsurancePlansModel> patientInsurancePlans) {
		this.patientInsurancePlans = patientInsurancePlans;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpaId")
  public Set<InsuranceSubmissionBatchModel> getInsuranceSubmissionBatches() {
    return this.insuranceSubmissionBatches;
  }

  public void setInsuranceSubmissionBatches(Set<InsuranceSubmissionBatchModel> insuranceSubmissionBatches) {
    this.insuranceSubmissionBatches = insuranceSubmissionBatches;
  }

}
