package com.insta.hms.core.clinical.discharge;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientDischargeModel generated by hbm2java
 */
@Entity
@Table(name = "patient_discharge")
public class PatientDischargeModel implements java.io.Serializable {

	private String patientId;
	private Boolean initiateDischargeStatus;
	private String initiateDischargingDoctor;
	private Date initiateDischargingDate;
	private Date initiateDischargingTime;
	private Date expectedDischargeDate;
	private Date expectedDischargeTime;
	private String initiateEnteredBy;
	private String initiateDischargeComments;
	private Boolean clinicalDischargeFlag;
	private Date clinicalDischargingDate;
	private Date clinicalDischargingTime;
	private String clinicalEnteredBy;
	private String clinicalDischargeComments;
	private Boolean financialDischargeStatus;
	private Date financialDischargeDate;
	private Date financialDischargeTime;
	private String financialEnteredBy;

	public PatientDischargeModel() {
	}

	public PatientDischargeModel(String patientId) {
		this.patientId = patientId;
	}

	public PatientDischargeModel(String patientId, Boolean initiateDischargeStatus, String initiateDischargingDoctor,
			Date initiateDischargingDate, Date initiateDischargingTime, Date expectedDischargeDate,
			Date expectedDischargeTime, String initiateEnteredBy, String initiateDischargeComments,
			Boolean clinicalDischargeFlag, Date clinicalDischargingDate, Date clinicalDischargingTime,
			String clinicalEnteredBy, String clinicalDischargeComments, Boolean financialDischargeStatus,
			Date financialDischargeDate, Date financialDischargeTime, String financialEnteredBy) {
		this.patientId = patientId;
		this.initiateDischargeStatus = initiateDischargeStatus;
		this.initiateDischargingDoctor = initiateDischargingDoctor;
		this.initiateDischargingDate = initiateDischargingDate;
		this.initiateDischargingTime = initiateDischargingTime;
		this.expectedDischargeDate = expectedDischargeDate;
		this.expectedDischargeTime = expectedDischargeTime;
		this.initiateEnteredBy = initiateEnteredBy;
		this.initiateDischargeComments = initiateDischargeComments;
		this.clinicalDischargeFlag = clinicalDischargeFlag;
		this.clinicalDischargingDate = clinicalDischargingDate;
		this.clinicalDischargingTime = clinicalDischargingTime;
		this.clinicalEnteredBy = clinicalEnteredBy;
		this.clinicalDischargeComments = clinicalDischargeComments;
		this.financialDischargeStatus = financialDischargeStatus;
		this.financialDischargeDate = financialDischargeDate;
		this.financialDischargeTime = financialDischargeTime;
		this.financialEnteredBy = financialEnteredBy;
	}

	@Id

	@Column(name = "patient_id", unique = true, nullable = false, length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "initiate_discharge_status")
	public Boolean getInitiateDischargeStatus() {
		return this.initiateDischargeStatus;
	}

	public void setInitiateDischargeStatus(Boolean initiateDischargeStatus) {
		this.initiateDischargeStatus = initiateDischargeStatus;
	}

	@Column(name = "initiate_discharging_doctor", length = 100)
	public String getInitiateDischargingDoctor() {
		return this.initiateDischargingDoctor;
	}

	public void setInitiateDischargingDoctor(String initiateDischargingDoctor) {
		this.initiateDischargingDoctor = initiateDischargingDoctor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "initiate_discharging_date", length = 13)
	public Date getInitiateDischargingDate() {
		return this.initiateDischargingDate;
	}

	public void setInitiateDischargingDate(Date initiateDischargingDate) {
		this.initiateDischargingDate = initiateDischargingDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "initiate_discharging_time", length = 15)
	public Date getInitiateDischargingTime() {
		return this.initiateDischargingTime;
	}

	public void setInitiateDischargingTime(Date initiateDischargingTime) {
		this.initiateDischargingTime = initiateDischargingTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expected_discharge_date", length = 13)
	public Date getExpectedDischargeDate() {
		return this.expectedDischargeDate;
	}

	public void setExpectedDischargeDate(Date expectedDischargeDate) {
		this.expectedDischargeDate = expectedDischargeDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "expected_discharge_time", length = 15)
	public Date getExpectedDischargeTime() {
		return this.expectedDischargeTime;
	}

	public void setExpectedDischargeTime(Date expectedDischargeTime) {
		this.expectedDischargeTime = expectedDischargeTime;
	}

	@Column(name = "initiate_entered_by", length = 100)
	public String getInitiateEnteredBy() {
		return this.initiateEnteredBy;
	}

	public void setInitiateEnteredBy(String initiateEnteredBy) {
		this.initiateEnteredBy = initiateEnteredBy;
	}

	@Column(name = "initiate_discharge_comments", length = 1000)
	public String getInitiateDischargeComments() {
		return this.initiateDischargeComments;
	}

	public void setInitiateDischargeComments(String initiateDischargeComments) {
		this.initiateDischargeComments = initiateDischargeComments;
	}

	@Column(name = "clinical_discharge_flag")
	public Boolean getClinicalDischargeFlag() {
		return this.clinicalDischargeFlag;
	}

	public void setClinicalDischargeFlag(Boolean clinicalDischargeFlag) {
		this.clinicalDischargeFlag = clinicalDischargeFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "clinical_discharging_date", length = 13)
	public Date getClinicalDischargingDate() {
		return this.clinicalDischargingDate;
	}

	public void setClinicalDischargingDate(Date clinicalDischargingDate) {
		this.clinicalDischargingDate = clinicalDischargingDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "clinical_discharging_time", length = 15)
	public Date getClinicalDischargingTime() {
		return this.clinicalDischargingTime;
	}

	public void setClinicalDischargingTime(Date clinicalDischargingTime) {
		this.clinicalDischargingTime = clinicalDischargingTime;
	}

	@Column(name = "clinical_entered_by", length = 100)
	public String getClinicalEnteredBy() {
		return this.clinicalEnteredBy;
	}

	public void setClinicalEnteredBy(String clinicalEnteredBy) {
		this.clinicalEnteredBy = clinicalEnteredBy;
	}

	@Column(name = "clinical_discharge_comments", length = 1000)
	public String getClinicalDischargeComments() {
		return this.clinicalDischargeComments;
	}

	public void setClinicalDischargeComments(String clinicalDischargeComments) {
		this.clinicalDischargeComments = clinicalDischargeComments;
	}

	@Column(name = "financial_discharge_status")
	public Boolean getFinancialDischargeStatus() {
		return this.financialDischargeStatus;
	}

	public void setFinancialDischargeStatus(Boolean financialDischargeStatus) {
		this.financialDischargeStatus = financialDischargeStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "financial_discharge_date", length = 13)
	public Date getFinancialDischargeDate() {
		return this.financialDischargeDate;
	}

	public void setFinancialDischargeDate(Date financialDischargeDate) {
		this.financialDischargeDate = financialDischargeDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "financial_discharge_time", length = 15)
	public Date getFinancialDischargeTime() {
		return this.financialDischargeTime;
	}

	public void setFinancialDischargeTime(Date financialDischargeTime) {
		this.financialDischargeTime = financialDischargeTime;
	}

	@Column(name = "financial_entered_by", length = 100)
	public String getFinancialEnteredBy() {
		return this.financialEnteredBy;
	}

	public void setFinancialEnteredBy(String financialEnteredBy) {
		this.financialEnteredBy = financialEnteredBy;
	}

}
