package com.insta.hms.mdm.packages;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PatientPackagesModel generated by hbm2java
 */
@Entity
@Table(name = "patient_packages")
public class PatientPackagesModel implements java.io.Serializable {

	private int patPackageId;
	private String mrNo;
	private int packageId;
	private BigDecimal depositBalance;
	private String status;

	public PatientPackagesModel() {
	}

	public PatientPackagesModel(int patPackageId, int packageId) {
		this.patPackageId = patPackageId;
		this.packageId = packageId;
	}

	public PatientPackagesModel(int patPackageId, String mrNo, int packageId, BigDecimal depositBalance, String status) {
		this.patPackageId = patPackageId;
		this.mrNo = mrNo;
		this.packageId = packageId;
		this.depositBalance = depositBalance;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pat_package_id_generator")
  @SequenceGenerator(name = "pat_package_id_generator", sequenceName = "patient_packages_seq", allocationSize = 1, initialValue = 1)
	@Column(name = "pat_package_id", unique = true, nullable = false)
	public int getPatPackageId() {
		return this.patPackageId;
	}

	public void setPatPackageId(int patPackageId) {
		this.patPackageId = patPackageId;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "package_id", nullable = false)
	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	@Column(name = "deposit_balance", precision = 15)
	public BigDecimal getDepositBalance() {
		return this.depositBalance;
	}

	public void setDepositBalance(BigDecimal depositBalance) {
		this.depositBalance = depositBalance;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
