package com.insta.hms.core.patient.registration;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.insurancecompanies.InsuranceCompanyMasterModel;
import com.insta.hms.mdm.insuranceplans.InsurancePlanMainModel;
import com.insta.hms.mdm.tpas.TpaMasterModel;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientInsurancePlansModel generated by hbm2java
 */
@Entity
@Table(name = "patient_insurance_plans")
public class PatientInsurancePlansModel implements java.io.Serializable {

	private int patientInsurancePlansId;
	private InsuranceCompanyMasterModel InsuranceCompanyMasterModel;
	private TpaMasterModel TpaMasterModel;
	private InsurancePlanMainModel InsurancePlanMainModel;
	private String mrNo;
	private String patientId;
	private Integer planTypeId;
	private BigDecimal insuranceApproval;
	private Character codificationStatus;
	private String priorAuthId;
	private String codifiedBy;
	private Integer patientPolicyId;
	private Integer priorAuthModeId;
	private String codificationRemarks;
	private String useDrg;
	private String drgCode;
	private char usePerdiem;
	private String perDiemCode;
	private Integer priority;
	private BigDecimal planLimit;
	private BigDecimal visitLimit;
	private BigDecimal visitDeductible;
	private BigDecimal visitCopayPercentage;
	private BigDecimal visitMaxCopayPercentage;
	private BigDecimal visitPerDayLimit;
	private BigDecimal episodeLimit;
	private BigDecimal episodeDeductible;
	private BigDecimal episodeCopayPercentage;
	private BigDecimal episodeMaxCopayPercentage;
	private BigDecimal utilizationAmount;

	public PatientInsurancePlansModel() {
	}

	public PatientInsurancePlansModel(int patientInsurancePlansId, String useDrg, char usePerdiem) {
		this.patientInsurancePlansId = patientInsurancePlansId;
		this.useDrg = useDrg;
		this.usePerdiem = usePerdiem;
	}

	public PatientInsurancePlansModel(int patientInsurancePlansId, InsuranceCompanyMasterModel InsuranceCompanyMasterModel,
			TpaMasterModel TpaMasterModel, InsurancePlanMainModel InsurancePlanMainModel, String mrNo, String patientId, Integer planTypeId,
			BigDecimal insuranceApproval, Character codificationStatus, String priorAuthId, String codifiedBy,
			Integer patientPolicyId, Integer priorAuthModeId, String codificationRemarks, String useDrg, String drgCode,
			char usePerdiem, String perDiemCode, Integer priority, BigDecimal planLimit, BigDecimal visitLimit,
			BigDecimal visitDeductible, BigDecimal visitCopayPercentage, BigDecimal visitMaxCopayPercentage,
			BigDecimal visitPerDayLimit, BigDecimal episodeLimit, BigDecimal episodeDeductible,
			BigDecimal episodeCopayPercentage, BigDecimal episodeMaxCopayPercentage, BigDecimal utilizationAmount) {
		this.patientInsurancePlansId = patientInsurancePlansId;
		this.InsuranceCompanyMasterModel = InsuranceCompanyMasterModel;
		this.TpaMasterModel = TpaMasterModel;
		this.InsurancePlanMainModel = InsurancePlanMainModel;
		this.mrNo = mrNo;
		this.patientId = patientId;
		this.planTypeId = planTypeId;
		this.insuranceApproval = insuranceApproval;
		this.codificationStatus = codificationStatus;
		this.priorAuthId = priorAuthId;
		this.codifiedBy = codifiedBy;
		this.patientPolicyId = patientPolicyId;
		this.priorAuthModeId = priorAuthModeId;
		this.codificationRemarks = codificationRemarks;
		this.useDrg = useDrg;
		this.drgCode = drgCode;
		this.usePerdiem = usePerdiem;
		this.perDiemCode = perDiemCode;
		this.priority = priority;
		this.planLimit = planLimit;
		this.visitLimit = visitLimit;
		this.visitDeductible = visitDeductible;
		this.visitCopayPercentage = visitCopayPercentage;
		this.visitMaxCopayPercentage = visitMaxCopayPercentage;
		this.visitPerDayLimit = visitPerDayLimit;
		this.episodeLimit = episodeLimit;
		this.episodeDeductible = episodeDeductible;
		this.episodeCopayPercentage = episodeCopayPercentage;
		this.episodeMaxCopayPercentage = episodeMaxCopayPercentage;
		this.utilizationAmount = utilizationAmount;
	}

	@Id

	@Column(name = "patient_insurance_plans_id", unique = true, nullable = false)
	public int getPatientInsurancePlansIdSequence() {
		return this.patientInsurancePlansId;
	}

	public void setPatientInsurancePlansIdSequence(int patientInsurancePlansId) {
		this.patientInsurancePlansId = patientInsurancePlansId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "insurance_co")
	public InsuranceCompanyMasterModel getInsuranceCompanyMasterModel() {
		return this.InsuranceCompanyMasterModel;
	}

	public void setInsuranceCompanyMasterModel(InsuranceCompanyMasterModel InsuranceCompanyMasterModel) {
		this.InsuranceCompanyMasterModel = InsuranceCompanyMasterModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sponsor_id")
	public TpaMasterModel getTpaMasterModel() {
		return this.TpaMasterModel;
	}

	public void setTpaMasterModel(TpaMasterModel TpaMasterModel) {
		this.TpaMasterModel = TpaMasterModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plan_id")
	public InsurancePlanMainModel getInsurancePlanMainModel() {
		return this.InsurancePlanMainModel;
	}

	public void setInsurancePlanMainModel(InsurancePlanMainModel InsurancePlanMainModel) {
		this.InsurancePlanMainModel = InsurancePlanMainModel;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "patient_id", length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "plan_type_id")
	public Integer getPlanTypeId() {
		return this.planTypeId;
	}

	public void setPlanTypeId(Integer planTypeId) {
		this.planTypeId = planTypeId;
	}

	@Column(name = "insurance_approval", precision = 15)
	public BigDecimal getInsuranceApproval() {
		return this.insuranceApproval;
	}

	public void setInsuranceApproval(BigDecimal insuranceApproval) {
		this.insuranceApproval = insuranceApproval;
	}

	@Column(name = "codification_status", length = 1)
	public Character getCodificationStatus() {
		return this.codificationStatus;
	}

	public void setCodificationStatus(Character codificationStatus) {
		this.codificationStatus = codificationStatus;
	}

	@Column(name = "prior_auth_id", length = 25)
	public String getPriorAuthId() {
		return this.priorAuthId;
	}

	public void setPriorAuthId(String priorAuthId) {
		this.priorAuthId = priorAuthId;
	}

	@Column(name = "codified_by", length = 30)
	public String getCodifiedBy() {
		return this.codifiedBy;
	}

	public void setCodifiedBy(String codifiedBy) {
		this.codifiedBy = codifiedBy;
	}

	@Column(name = "patient_policy_id")
	public Integer getPatientPolicyId() {
		return this.patientPolicyId;
	}

	public void setPatientPolicyId(Integer patientPolicyId) {
		this.patientPolicyId = patientPolicyId;
	}

	@Column(name = "prior_auth_mode_id")
	public Integer getPriorAuthModeId() {
		return this.priorAuthModeId;
	}

	public void setPriorAuthModeId(Integer priorAuthModeId) {
		this.priorAuthModeId = priorAuthModeId;
	}

	@Column(name = "codification_remarks")
	public String getCodificationRemarks() {
		return this.codificationRemarks;
	}

	public void setCodificationRemarks(String codificationRemarks) {
		this.codificationRemarks = codificationRemarks;
	}

	@Column(name = "use_drg", nullable = false, length = 1)
	public String getUseDrg() {
		return this.useDrg;
	}

	public void setUseDrg(String useDrg) {
		this.useDrg = useDrg;
	}

	@Column(name = "drg_code", length = 15)
	public String getDrgCode() {
		return this.drgCode;
	}

	public void setDrgCode(String drgCode) {
		this.drgCode = drgCode;
	}

	@Column(name = "use_perdiem", nullable = false, length = 1)
	public char getUsePerdiem() {
		return this.usePerdiem;
	}

	public void setUsePerdiem(char usePerdiem) {
		this.usePerdiem = usePerdiem;
	}

	@Column(name = "per_diem_code", length = 15)
	public String getPerDiemCode() {
		return this.perDiemCode;
	}

	public void setPerDiemCode(String perDiemCode) {
		this.perDiemCode = perDiemCode;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "plan_limit", precision = 15)
	public BigDecimal getPlanLimit() {
		return this.planLimit;
	}

	public void setPlanLimit(BigDecimal planLimit) {
		this.planLimit = planLimit;
	}

	@Column(name = "visit_limit", precision = 15)
	public BigDecimal getVisitLimit() {
		return this.visitLimit;
	}

	public void setVisitLimit(BigDecimal visitLimit) {
		this.visitLimit = visitLimit;
	}

	@Column(name = "visit_deductible", precision = 15)
	public BigDecimal getVisitDeductible() {
		return this.visitDeductible;
	}

	public void setVisitDeductible(BigDecimal visitDeductible) {
		this.visitDeductible = visitDeductible;
	}

	@Column(name = "visit_copay_percentage", precision = 15)
	public BigDecimal getVisitCopayPercentage() {
		return this.visitCopayPercentage;
	}

	public void setVisitCopayPercentage(BigDecimal visitCopayPercentage) {
		this.visitCopayPercentage = visitCopayPercentage;
	}

	@Column(name = "visit_max_copay_percentage", precision = 15)
	public BigDecimal getVisitMaxCopayPercentage() {
		return this.visitMaxCopayPercentage;
	}

	public void setVisitMaxCopayPercentage(BigDecimal visitMaxCopayPercentage) {
		this.visitMaxCopayPercentage = visitMaxCopayPercentage;
	}

	@Column(name = "visit_per_day_limit", precision = 15)
	public BigDecimal getVisitPerDayLimit() {
		return this.visitPerDayLimit;
	}

	public void setVisitPerDayLimit(BigDecimal visitPerDayLimit) {
		this.visitPerDayLimit = visitPerDayLimit;
	}

	@Column(name = "episode_limit", precision = 15)
	public BigDecimal getEpisodeLimit() {
		return this.episodeLimit;
	}

	public void setEpisodeLimit(BigDecimal episodeLimit) {
		this.episodeLimit = episodeLimit;
	}

	@Column(name = "episode_deductible", precision = 15)
	public BigDecimal getEpisodeDeductible() {
		return this.episodeDeductible;
	}

	public void setEpisodeDeductible(BigDecimal episodeDeductible) {
		this.episodeDeductible = episodeDeductible;
	}

	@Column(name = "episode_copay_percentage", precision = 15)
	public BigDecimal getEpisodeCopayPercentage() {
		return this.episodeCopayPercentage;
	}

	public void setEpisodeCopayPercentage(BigDecimal episodeCopayPercentage) {
		this.episodeCopayPercentage = episodeCopayPercentage;
	}

	@Column(name = "episode_max_copay_percentage", precision = 15)
	public BigDecimal getEpisodeMaxCopayPercentage() {
		return this.episodeMaxCopayPercentage;
	}

	public void setEpisodeMaxCopayPercentage(BigDecimal episodeMaxCopayPercentage) {
		this.episodeMaxCopayPercentage = episodeMaxCopayPercentage;
	}

	@Column(name = "utilization_amount", precision = 15)
	public BigDecimal getUtilizationAmount() {
		return this.utilizationAmount;
	}

	public void setUtilizationAmount(BigDecimal utilizationAmount) {
		this.utilizationAmount = utilizationAmount;
	}

}
