package com.insta.hms.mdm.insaggregatorcenters;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** InsuranceAggregatorCenterConfigModel generated by hbm2java. */
@Entity
@Table(name = "insurance_aggregator_center_config")
public class InsuranceAggregatorCenterConfigModel implements java.io.Serializable {

  /** The ia center id. */
  private int iaCenterId;

  /** The ia id. */
  private String iaId;

  /** The center id. */
  private int centerId;

  /** The ia center conf. */
  private String iaCenterConf;

  /** The status. */
  private String status;

  /** The facility id. */
  private String facilityId;

  /** Instantiates a new insurance aggregator center config model. */
  public InsuranceAggregatorCenterConfigModel() {}

  /**
   * Instantiates a new insurance aggregator center config model.
   *
   * @param iaCenterId the ia center id
   * @param iaId the ia id
   * @param centerId the center id
   */
  public InsuranceAggregatorCenterConfigModel(int iaCenterId, String iaId, int centerId) {
    this.iaCenterId = iaCenterId;
    this.iaId = iaId;
    this.centerId = centerId;
  }

  /**
   * Instantiates a new insurance aggregator center config model.
   *
   * @param iaCenterId the ia center id
   * @param iaId the ia id
   * @param centerId the center id
   * @param iaCenterConf the ia center conf
   * @param status the status
   * @param facilityId the facility id
   */
  public InsuranceAggregatorCenterConfigModel(
      int iaCenterId,
      String iaId,
      int centerId,
      String iaCenterConf,
      String status,
      String facilityId) {
    this.iaCenterId = iaCenterId;
    this.iaId = iaId;
    this.centerId = centerId;
    this.iaCenterConf = iaCenterConf;
    this.status = status;
    this.facilityId = facilityId;
  }

  /**
   * Gets the ia center id.
   *
   * @return the ia center id
   */
  @Id
  @Column(name = "ia_center_id", unique = true, nullable = false)
  public int getIaCenterId() {
    return this.iaCenterId;
  }

  /**
   * Sets the ia center id.
   *
   * @param iaCenterId the new ia center id
   */
  public void setIaCenterId(int iaCenterId) {
    this.iaCenterId = iaCenterId;
  }

  /**
   * Gets the ia id.
   *
   * @return the ia id
   */
  @Column(name = "ia_id", nullable = false, length = 25)
  public String getIaId() {
    return this.iaId;
  }

  /**
   * Sets the ia id.
   *
   * @param iaId the new ia id
   */
  public void setIaId(String iaId) {
    this.iaId = iaId;
  }

  /**
   * Gets the facility id.
   *
   * @return the facility id
   */
  @Column(name = "facility_id", nullable = false, length = 25)
  public String getFacilityId() {
    return this.facilityId;
  }

  /**
   * Sets the facility id.
   *
   * @param facilityId the new facility id
   */
  public void setFacilityId(String facilityId) {
    this.facilityId = facilityId;
  }

  /**
   * Gets the center id.
   *
   * @return the center id
   */
  @Column(name = "center_id", nullable = false)
  public int getCenterId() {
    return this.centerId;
  }

  /**
   * Sets the center id.
   *
   * @param centerId the new center id
   */
  public void setCenterId(int centerId) {
    this.centerId = centerId;
  }

  /**
   * Gets the ia center conf.
   *
   * @return the ia center conf
   */
  @Column(name = "ia_center_conf")
  public String getIaCenterConf() {
    return this.iaCenterConf;
  }

  /**
   * Sets the ia center conf.
   *
   * @param iaCenterConf the new ia center conf
   */
  public void setIaCenterConf(String iaCenterConf) {
    this.iaCenterConf = iaCenterConf;
  }

  /**
   * Gets the status.
   *
   * @return the status
   */
  @Column(name = "status", length = 1)
  public String getStatus() {
    return this.status;
  }

  /**
   * Sets the status.
   *
   * @param status the new status
   */
  public void setStatus(String status) {
    this.status = status;
  }
}
