package com.insta.hms.mdm.centergroup;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CenterGroupDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "center_group_details")
public class CenterGroupDetailsModel implements java.io.Serializable {

	private CenterGroupDetailsIdSequence id;
	private CenterGroupMasterModel CenterGroupMasterModel;

	public CenterGroupDetailsModel() {
	}

	public CenterGroupDetailsModel(CenterGroupDetailsIdSequence id, CenterGroupMasterModel CenterGroupMasterModel) {
		this.id = id;
		this.CenterGroupMasterModel = CenterGroupMasterModel;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "centerGroupId", column = @Column(name = "center_group_id", nullable = false)),
			@AttributeOverride(name = "centerId", column = @Column(name = "center_id")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)) })
	public CenterGroupDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(CenterGroupDetailsIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "center_group_id", nullable = false, insertable = false, updatable = false)
	public CenterGroupMasterModel getCenterGroupMasterModel() {
		return this.CenterGroupMasterModel;
	}

	public void setCenterGroupMasterModel(CenterGroupMasterModel CenterGroupMasterModel) {
		this.CenterGroupMasterModel = CenterGroupMasterModel;
	}

}
