[#setting number_format="#"]
[#include "TextPrintMacros.ftl"]

[#assign name = "${visitdetails.full_name!}"]
[#assign age = "${visitdetails.age?string} ${visitdetails.agein!} ${visitdetails.patient_gender}"]
[#assign location = "${visitdetails.cityname!}, ${visitdetails.statename!}"]
[#assign admitted]
  [#if visitdetails.visit_type == "i"]Admit Date:[#else]Regd. Date:[/#if][#t]
[/#assign]
[#assign regdate = "${visitdetails.reg_date!}"]
[#assign bedtitle]
  [#if visitdetails.visit_type == "i"]Bed Type:  [#else]           [/#if][#t]
[/#assign]
[#assign wardnbed]
  [#if visitdetails.visit_type == "i"]${visitdetails.bill_bed_type!}[#else][/#if][#t]
[/#assign]
[#assign distitle]
  [#if visitdetails.visit_type == "i"]
    [#if (visitdetails.discharge_type!)=="Expiry"]Death Date:[#else]Disch Date:[/#if][#t]
  [/#if]
[/#assign]
[#assign dischdate]
  [#if visitdetails.visit_type == "i"]
    ${visitdetails.discharge_date!}[#t]
  [/#if]
[/#assign]
[#assign label_one][#if (label1!'') != '']${label1}:[/#if][/#assign]
[#assign label_two][#if (label1!'') != '']${label2}:[/#if][/#assign]

Name:      ${lf(name!,                     		46)} ${label_one}    ${lf(labelvalue1!,16)}
Age/Gender:${lf(age,                      		46)} ${label_two}    ${lf(labelvalue2!,16)}
Address:   ${lf(visitdetails.patient_address!,  46)} MR No:         ${lf(visitdetails.mr_no!,16)}
Location:  ${lf(location!,                 		46)} Visit ID:      ${lf(visitdetails.patient_id!,16)}
Doctor:    ${lf(visitdetails.doctor_name!!,     46)} ${admitted!}   ${lf(regdate!,16)}
Dept:      ${lf(visitdetails.dept_name!,        46)} ${distitle!}   ${lf(dischdate!,16)}
Rate Plan: ${lf(visitdetails.org_name!,         46)} ${bedtitle!}   ${lf(wardnbed!,25)}
[#if (visitdetails.tpa_name??) || (visitdetails.refdoctorname??)]
Sponsor:   ${lf(visitdetails.tpa_name!,         46)} Referred To:   ${lf(visitdetails.refdoctorname!,25)}
[/#if]

[#list form.sections?split(",") as sectionid]
[#if sectionid?number == -1 ] 
	[#if visitdetails.complaint?has_content] 
		[#assign cComplaint="${visitdetails.complaint!}"]
		Chief Complaint:${cComplaint?right_pad(15)}
	[/#if] 
	[#if secondary_complaints?has_content]
	[#list secondary_complaints as s_complaint] 
		[#assign oComplaint="${s_complaint.complaint!}"]
		Other Complaint:${oComplaint?right_pad(15)}
	[/#list]
	[/#if]
[#elseif sectionid?number == -2 && allergies?has_content]
[#assign alleryFinalizedUser = '']
Allergies Details:
${lf("Allergy Type", 12)} ${lf("Allergy", 15)} ${lf("Onset Date", 15)} ${lf("Reaction", 15)} ${lf("Severity", 15)} ${lf("Status", 15)} 
[#list allergies as allergy] 
	[#if allergy.finalized == 'Y']
		[#if (allergy.temp_username!'') != '']
			[#assign alleryFinalizedUser = allergy.temp_username]
		[#else]
			[#assign alleryFinalizedUser = allergy.finalized_user!]
		[/#if]
	[/#if]
	
	[#if allergy.allergy_type == 'N']
		[#assign allergyType="No Known Allergies"]
	[#elseif allergy.allergy_type == 'M']
		[#assign allergyType="Medicine"]
	[#elseif allergy.allergy_type == 'F']
		[#assign allergyType="Food"]
	[#else] [#assign allergyType="Other"]
	[/#if]
	[#assign allergi="${allergy.allergy!}"]
	[#assign onsetDate="${allergy.onset_date!}"]
	[#assign reaction="${allergy.reaction!}"]
	[#assign severity="${allergy.severity!}"]
	[#if allergy.status == 'A']
		[#assign status="Active"]
	[#else][#assign status="Inactive"]
	[/#if]
${lf(allergyType, 12)} ${lf(allergi, 15)} ${lf(onsetDate, 15)} ${lf(reaction, 15)} ${lf(status, 15)}
[/#list] 

[#if visitdetails.isSameFinalizedUser == false && (alleryFinalizedUser!'') != '']
	${"Section Finalized By:"?left_pad(70)} ${alleryFinalizedUser}
[/#if]

 [#elseif sectionid?number == -13 && pregnancyhistoriesBean?has_content || sectionid?number=-13 && pregnancyhistories?has_content] 
	[#assign obstetricHistoryFinalizedUser = '']
	[#if pregnancyhistoriesBean?has_content && pregnancyhistories?has_content]
	Obstetric History Details: 
	[/#if]
	
	[#if pregnancyhistoriesBean?has_content]
	[#list pregnancyhistoriesBean as pregnancyhistory] 
			[#assign pregnancyvariable = false] 
		[#if pregnancyhistory.field_g?has_content || pregnancyhistory.field_p?has_content || pregnancyhistory.field_l?has_content || pregnancyhistory.field_a?has_content]
			[#assign pregnancyvariable = true]
		[/#if]
	[#if pregnancyvariable = true && !pregnancyhistories?has_content]
	Obstetric History Details:
	[/#if]
	
		[#if pregnancyvariable = true]
			[#if pregnancyhistory.finalized == 'Y']
				[#if (pregnancyhistory.temp_username!'') != '']
					[#assign obstetricHistoryFinalizedUser = pregnancyhistory.temp_username]
				[#else]
					[#assign obstetricHistoryFinalizedUser = pregnancyhistory.finalized_user!]
				[/#if]
			[/#if]
				G [#if pregnancyhistory.field_g?has_content]${pregnancyhistory.field_g}[/#if]
				P [#if pregnancyhistory.field_p?has_content]${pregnancyhistory.field_p}[/#if]
				L [#if pregnancyhistory.field_l?has_content]${pregnancyhistory.field_l}[/#if]
				A [#if pregnancyhistory.field_a?has_content]${pregnancyhistory.field_a}[/#if]
		[/#if]
	[/#list]
	[/#if]
	[#if pregnancyhistories?has_content]
	${"Date of Delivery"?right_pad(15)} ${"Week"?right_pad(15)}${"Place"?right_pad(15)}${"Method"?right_pad(15)}${"Weight"?right_pad(15)}${"Sex"?right_pad(15)}${"Complications"?right_pad(15)}${"Feeding"?right_pad(15)}${"Outcome"?right_pad(15)}
	[#list pregnancyhistories as pregnancyhistory] 
			[#if pregnancyhistory.finalized == 'Y']
				[#if (pregnancyhistory.temp_username!'') != '']
					[#assign obstetricHistoryFinalizedUser = pregnancyhistory.temp_username]
				[#else]
					[#assign obstetricHistoryFinalizedUser = pregnancyhistory.finalized_user!]
				[/#if]
			[/#if]
			[#assign Date="${pregnancyhistory.date}"]
			[#assign Week="${pregnancyhistory.weeks}"]
			[#assign Place="${pregnancyhistory.place!}"]
			[#assign Method="${pregnancyhistory.method!}"]
			[#assign Weight="${pregnancyhistory.weight}"]
			[#if pregnancyhistory.sex == 'M']
			[#assign Sex="Male"]
			[#elseif pregnancyhistory.sex == 'F']
			[#assign Sex="Female"]
			[#elseif pregnancyhistory.sex == 'O']
			[#assign Sex="Unknown"]
			[#else]
			[#assign Sex = '']
			[/#if]
			[#assign Complications="${pregnancyhistory.complications}"]
			[#assign Feeding="${pregnancyhistory.feeding}"]
			[#assign Outcome="${pregnancyhistory.outcome}"]
	${Date?right_pad(15)} ${Week?right_pad(15)}${Place?right_pad(15)}${Method?right_pad(15)}${Weight?right_pad(15)}${Sex?right_pad(15)}${Complications?right_pad(15)}${Feeding?right_pad(15)}${Outcome?right_pad(15)}	
	[/#list]
	[/#if]
	
	[#if visitdetails.isSameFinalizedUser == false && (obstetricHistoryFinalizedUser!'') != '']
	${"Section Finalized By:"?left_pad(70)} ${obstetricHistoryFinalizedUser}
	[/#if]
				
[#elseif sectionid?number == -14 && antenatalinfo?has_content] 
	[#assign antenatalFinalizedUser = '']
	Antenatal Details:
	${"Visit Date"?right_pad(15)} ${"Gestation Age"?right_pad(15)}${"Height of Fundus(cm)"?right_pad(15)}${"Presentation"?right_pad(15)}${"Relation of PP to Brim"?right_pad(15)}${"Foetal Heart(bpm)"?right_pad(15)}${"Urine"?right_pad(15)}${"BP(mmHg)"?right_pad(15)}${"Weight"?right_pad(15)}${"Prescription Summary"?right_pad(15)}${"Consulting Doctor"?right_pad(15)}${"Next Visit Date"?right_pad(15)}
	[#list antenatalinfo as antenatal] 
		[#if antenatal.finalized == 'Y']
			[#if (antenatal.temp_username!'') != '']
				[#assign antenatalFinalizedUser = antenatal.temp_username]
			[#else]
				[#assign antenatalFinalizedUser = antenatal.finalized_user!]
			[/#if]
		[/#if]
		[#assign visitDate="${antenatal.visit_date}"]
		[#assign gestationAge][#if antenatal.gestation_age?has_content]${antenatal.gestation_age}[/#if][/#assign]
		[#assign heightofFundus][#if antenatal.height_fundus?has_content]${antenatal.height_fundus}[/#if][/#assign]
		[#assign Presentation="${antenatal.presentation}"]
		[#assign relationofPPtoBrim="${antenatal.rel_pp_brim}"]
		[#assign foetalHeart="${antenatal.foetal_heart}"]
		[#assign Urine="${antenatal.urine}"]
		[#assign BP][#if antenatal.systolic_bp?has_content]${antenatal.systolic_bp}[/#if][#if antenatal.diastolic_bp?has_content]/${antenatal.diastolic_bp}[/#if][/#assign]
		[#assign Weight][#if antenatal.weight?has_content]${antenatal.weight}[/#if][/#assign]
		[#assign prescriptionSummary="${antenatal.prescription_summary}"]
		[#assign consultingDoctor][#if antenatal.doctor_name?has_content]${antenatal.doctor_name}[/#if][/#assign]
		[#assign nextvisitdate][#if antenatal.next_visit_date?has_content]${antenatal.next_visit_date}[/#if][/#assign]
	${visitDate?right_pad(15)} ${gestationAge?right_pad(15)}${heightofFundus?right_pad(15)}${Presentation?right_pad(15)}${relationofPPtoBrim?right_pad(15)}${foetalHeart?right_pad(15)}${Urine?right_pad(15)}${BP?right_pad(15)}${Weight?right_pad(15)}${prescriptionSummary?right_pad(15)}${consultingDoctor?right_pad(15)}${nextvisitdate?right_pad(15)}
		[/#list] 
		
		[#if visitdetails.isSameFinalizedUser == false && (antenatalFinalizedUser!'') != '']
	${"Section Finalized By:"?left_pad(70)} ${antenatalFinalizedUser}
	[/#if]
		 		
 [#elseif sectionid?number == -16 && pac_details?has_content] 
	[#assign pacFinalizedUser = '']
	Pre Anesthesthetic Checkup Details:
	[#list pac_details as pac] 
	${"Doctor"?right_pad(15)} ${"Conduction Date"?right_pad(15)}${"Validity Date"?right_pad(15)}${"Outcome"?right_pad(15)}${"Pre-Anaesthetic Evaluation Remarks"?right_pad(15)}
			[#if pac.finalized == 'Y']
				[#if (pac.temp_username!'') != '']
					[#assign pacFinalizedUser = pac.temp_username]
				[#else]
					[#assign pacFinalizedUser = pac.finalized_user!]
				[/#if]
			[/#if]
			[#assign Doctor="${pac.doctor_name}"]
			[#assign ConductionDate="${pac.pac_date}"]
			[#assign ValidityDate="${pac.pac_validity}"]
			[#if pac.status == 'F']
			[#assign Outcome="Fit"]
			[#elseif pac.status == 'U']
			[#assign Outcome="Unfit"]
			[/#if]
			[#assign preAnaestheticEvalutionRemarks="${pac.patient_pac_remarks}"]
	${Doctor?right_pad(15)} ${ConductionDate?right_pad(15)}${ValidityDate?right_pad(15)}${Outcome?right_pad(15)}${preAnaestheticEvalutionRemarks?right_pad(15)}
	[/#list]
	
	[#if visitdetails.isSameFinalizedUser == false && (pacFinalizedUser!'') != '']
	${"Section Finalized By:"?left_pad(70)} ${pacFinalizedUser}
	[/#if]
				
[#elseif sectionid?number == -4 && vitals?has_content] 
	
Vitals:
[#list vitals as vital] 	
${"Date "}${":"?right_pad(1)}${vital['date_time']?string('dd-MM-yyyy HH:mm')}
[#list vital_params as param] 
${param.param_label!?html}[#if  (param.param_uom??) && "${param.param_uom}" != ""](${param.param_uom})[/#if]${":"?right_pad(1)}${vital[param.param_label]!?html}[#if "${vital[param.param_label]!?html}" != ""] ${param.param_uom!}[/#if]
[/#list] 
${"User "}${":"?right_pad(1)}${vital['user_name']!}
			
[/#list] 
				
[#elseif sectionid?number == -6 && diagnosis_details?has_content] 
				
	Diagnosis Details:
	${"Diag Type"?right_pad(15)}${"Diag Code"?right_pad(15)}${"Description"?right_pad(15)}
	[#list diagnosis_details as diagnosis] 
			[#if diagnosis.diag_type == 'P' ]
				[#assign DiagType="Principal"]			
			[#elseif diagnosis.diag_type == 'A']
				[#assign DiagType="Admitting"]	
			[#elseif diagnosis.diag_type == 'V']
				[#assign DiagType="Reason For Visit"]	
			[#else][#assign DiagType="Secondary"]
			[/#if]
			[#assign DiagCode="${diagnosis.icd_code!}"]
			[#assign Description="${diagnosis.description!}"]
	${DiagType?right_pad(15)}${DiagCode?right_pad(15)}${Description?right_pad(15)}
	[/#list] 
				
[#elseif sectionid?number > 0] 
	[#assign instaSectionFinalizedUser = '']
	[#assign dashmark ='']
	[#assign stn_title = '']
	[#assign stn_count = 1]
	[#list insta_sections as record] 
		[#if insta_sections_data['sd_' + record.section_detail_id]?has_content && record.section_id == sectionid?number] 

		${record.section_title}[#t] 
		[#if stn_title == record.section_title]
			${'- ' + stn_count}
			[#assign stn_count = stn_count + 1]
		[/#if]${""}[#t]
		[#if stn_title != record.section_title]
			[#assign stn_count = 1]
			[#assign stn_title = record.section_title]
		[/#if]${""}:
		[#if record.finalized == 'Y']
			[#if (record.temp_username!'') != '']
				[#assign instaSectionFinalizedUser = record.temp_username]
			[#else]
				[#assign instaSectionFinalizedUser = record.finalized_user!]
			[/#if]
		[/#if][#t]
		[#list insta_sections_data['sd_' + record.section_detail_id] as field] 
		   ${field[0].field_name}: [#t]
			[#assign marker_number=1] 
			[#list field as value]
				[#if value.option_remarks?has_content]
					[#assign dashmark = '-'] 
				[/#if]
				[#if value.field_type == 'checkbox']
					[#if value.allow_others == 'Y' && value.option_id ==-1] 
						[#assign fieldValue="Others ${dashmark} ${value.option_remarks!?html},"]
					[#elseif value.allow_normal == 'Y' && value.option_id == 0] 
						[#assign fieldValue="Normal ${dashmark} ${value.option_remarks!?html},"]
					[#else] 
						[#assign fieldValue="${value.option_value!?html} ${dashmark} ${value.option_remarks!?html},"]
					[/#if]
				[#elseif value.field_type == 'dropdown']
					[#if value.allow_others == 'Y' && value.option_id ==-1] 
						[#assign fieldValue="Others ${dashmark} ${(value.option_remarks!)?html},"]
					[#elseif value.allow_normal == 'Y' && value.option_id == 0] 
						[#assign fieldValue="Normal,"]
					[#else] 
						[#assign fieldValue="${value.option_value!?html},"]
				[/#if]						
				[#elseif value.field_type == 'text' || value.field_type == 'wide text'] 
						[#assign fieldValue="${(value.option_remarks!)?html},"]
				[#elseif value.field_type == 'date'] 
						[#assign fieldValue="${(value.date?string('dd-MM-yyyy'))!}"]
				[#elseif value.field_type == 'datetime'] 
						[#assign fieldValue="${(value.date_time?string('dd-MM-yyyy HH:mm'))!}"]
				[/#if]
				${" "} ${fieldValue} [#t]
			[/#list] 					
		[/#list]
		
			[#if visitdetails.isSameFinalizedUser == false && (instaSectionFinalizedUser!'') != '']
				${"Section Finalized By:"?left_pad(70)} ${instaSectionFinalizedUser}
			[/#if]  
		[/#if] 
	[/#list] 
 [/#if]
[/#list]

[#if visitdetails.isSameFinalizedUser == true]
	[#if visitdetails.temp_username != '']
		${"All Section Finalized By:"?left_pad(70)} ${visitdetails.temp_username}
	[#elseif visitdetails.finalized_user != '']
		${"All Section Finalized By:"?left_pad(70)} ${visitdetails.finalized_user}
	[/#if]
[/#if]
