[#macro rfill field num]
  [#if (field!"")?length > num]
    ${(field!"")?string?substring(0,num)}[#t]
  [#else]
    ${(field!"")?string?left_pad(num)}[#t]
  [/#if]
[/#macro]

[#macro lfill field num]
  [#if (field!"")?length > num]
    ${(field!"")?string?substring(0,num)}[#t]
  [#else]
    ${(field!"")?string?right_pad(num)}[#t]
  [/#if]
[/#macro]

[#macro cfill field num]
  [#if (field!"")?length > num]
    ${(field!"")?substring(0,num)}[#t]
  [#else]
    [#assign width = (num/2 + (field!"")?length/2)?int]
    ${(field!"")?left_pad(width)}[#t]
  [/#if][#t]
[/#macro]

[#function rf str width]
	[#if str?length > width]
		[#return str?string?substring(0,width)]
	[#else]
	  [#return str?string?left_pad(width)]
	[/#if]
[/#function]

[#function lf str width]
	[#if str?length > width]
		[#return str?string?substring(0,width)]
	[#else]
	  [#return str?string?right_pad(width)]
	[/#if]
[/#function]

[#function cf str width]
	[#if str?length > width]
		[#return str?string?substring(0,width)]
	[#else]
    [#assign pad = (width/2 + str?length/2)?int]
	  [#return str?string?left_pad(width)]
	[/#if]
[/#function]

