package com.insta.hms.mdm.departments;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DepartmentModel generated by hbm2java
 */
@Entity
@Table(name = "department", uniqueConstraints = @UniqueConstraint(columnNames = "dept_name"))
public class DepartmentModel implements java.io.Serializable {

	private String deptId;
	private String deptName;
	private Character status;
	private String allowedGender;
	private String costCenterCode;
	private String deptTypeId;
	private Character isReferralDocAsOrderingClinician;

	public DepartmentModel() {
	}

	public DepartmentModel(String deptId, String deptName, String allowedGender, String costCenterCode) {
		this.deptId = deptId;
		this.deptName = deptName;
		this.allowedGender = allowedGender;
		this.costCenterCode = costCenterCode;
	}

	public DepartmentModel(String deptId, String deptName, Character status, String allowedGender, String costCenterCode,
			String deptTypeId) {
		this.deptId = deptId;
		this.deptName = deptName;
		this.status = status;
		this.allowedGender = allowedGender;
		this.costCenterCode = costCenterCode;
		this.deptTypeId = deptTypeId;
	}

	@Id

	@Column(name = "dept_id", unique = true, nullable = false, length = 10)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "dept_name", unique = true, nullable = false, length = 100)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "allowed_gender", nullable = false, length = 3)
	public String getAllowedGender() {
		return this.allowedGender;
	}

	public void setAllowedGender(String allowedGender) {
		this.allowedGender = allowedGender;
	}

	@Column(name = "cost_center_code", nullable = false, length = 200)
	public String getCostCenterCode() {
		return this.costCenterCode;
	}

	public void setCostCenterCode(String costCenterCode) {
		this.costCenterCode = costCenterCode;
	}

	@Column(name = "dept_type_id", length = 20)
	public String getDeptTypeId() {
		return this.deptTypeId;
	}

	public void setDeptTypeId(String deptTypeId) {
		this.deptTypeId = deptTypeId;
	}

  @Column(name = "is_referral_doc_as_ordering_clinician", length = 1)
  public Character getIsReferralDocAsOrderingClinician() {
    return isReferralDocAsOrderingClinician;
  }

  public void setIsReferralDocAsOrderingClinician(Character isReferralDocAsOrderingClinician) {
    this.isReferralDocAsOrderingClinician = isReferralDocAsOrderingClinician;
  }

}
