package com.insta.hms.core.clinical.vitalforms;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VisitVitalsModel generated by hbm2java
 */
@Entity
@Table(name = "visit_vitals")
public class VisitVitalsModel implements java.io.Serializable {

	private int vitalReadingId;
	private String patientId;
	private Date dateTime;
	private String userName;
	private Set vitalReadings = new HashSet(0);

	public VisitVitalsModel() {
	}

	public VisitVitalsModel(int vitalReadingId, String patientId, Date dateTime) {
		this.vitalReadingId = vitalReadingId;
		this.patientId = patientId;
		this.dateTime = dateTime;
	}

	public VisitVitalsModel(int vitalReadingId, String patientId, Date dateTime, String userName, Set vitalReadings) {
		this.vitalReadingId = vitalReadingId;
		this.patientId = patientId;
		this.dateTime = dateTime;
		this.userName = userName;
		this.vitalReadings = vitalReadings;
	}

	@Id

	@Column(name = "vital_reading_id", unique = true, nullable = false)
	public int getVitalReadingId() {
		return this.vitalReadingId;
	}

	public void setVitalReadingId(int vitalReadingId) {
		this.vitalReadingId = vitalReadingId;
	}

	@Column(name = "patient_id", nullable = false, length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, length = 29)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "visitVitals")
	public Set getVitalReadings() {
		return this.vitalReadings;
	}

	public void setVitalReadings(Set vitalReadings) {
		this.vitalReadings = vitalReadings;
	}

}
