package com.insta.hms.mdm.diagnosticcharges;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DiagnosticChargesModel generated by hbm2java
 */
@Entity
@Table(name = "diagnostic_charges")
public class DiagnosticChargesModel implements java.io.Serializable {

	private DiagnosticChargesIdSequence id;
	private BigDecimal charge;
	private BigDecimal discount;
	private String username;
	private String isOverride;

	public DiagnosticChargesModel() {
	}

	public DiagnosticChargesModel(DiagnosticChargesIdSequence id, BigDecimal charge, BigDecimal discount) {
		this.id = id;
		this.charge = charge;
		this.discount = discount;
	}

	public DiagnosticChargesModel(DiagnosticChargesIdSequence id, BigDecimal charge, BigDecimal discount, String username,
			String isOverride) {
		this.id = id;
		this.charge = charge;
		this.discount = discount;
		this.username = username;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orgName", column = @Column(name = "org_name", nullable = false, length = 100)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", nullable = false, length = 150)),
			@AttributeOverride(name = "testId", column = @Column(name = "test_id", nullable = false, length = 10)),
			@AttributeOverride(name = "priority", column = @Column(name = "priority", nullable = false, length = 20)) })
	public DiagnosticChargesIdSequence getId() {
		return this.id;
	}

	public void setId(DiagnosticChargesIdSequence id) {
		this.id = id;
	}

	@Column(name = "charge", nullable = false, precision = 20)
	public BigDecimal getCharge() {
		return this.charge;
	}

	public void setCharge(BigDecimal charge) {
		this.charge = charge;
	}

	@Column(name = "discount", nullable = false, precision = 20)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
