package com.insta.hms.mdm.codetypeclassification;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/** CodeTypeClassificationModel generated by hbm2java. */
@Entity
@Table(name = "code_type_classification")
public class CodeTypeClassificationModel implements java.io.Serializable {

  private CodeTypeClassificationIdSequence id;

  public CodeTypeClassificationModel() {}

  public CodeTypeClassificationModel(CodeTypeClassificationIdSequence id) {
    this.id = id;
  }

  @EmbeddedId
  @AttributeOverrides({
      @AttributeOverride(
        name = "codeCategory",
        column = @Column(name = "code_category", nullable = false, length = 50)
      ),
      @AttributeOverride(
        name = "codeTypeClassification",
        column = @Column(name = "code_type_classification", nullable = false, length = 50)
      )
  })
  public CodeTypeClassificationIdSequence getId() {
    return this.id;
  }

  public void setId(CodeTypeClassificationIdSequence id) {
    this.id = id;
  }
}
