package com.insta.hms.mdm.sectionrolerights;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InstaSectionRightsModel generated by hbm2java
 */
@Entity
@Table(name = "insta_section_rights")
public class InstaSectionRightsModel implements java.io.Serializable {

	private int sectionRoleId;
	private Integer sectionId;
	private Integer roleId;

	public InstaSectionRightsModel() {
	}

	public InstaSectionRightsModel(int sectionRoleId) {
		this.sectionRoleId = sectionRoleId;
	}

	public InstaSectionRightsModel(int sectionRoleId, Integer sectionId, Integer roleId) {
		this.sectionRoleId = sectionRoleId;
		this.sectionId = sectionId;
		this.roleId = roleId;
	}

	@Id

	@Column(name = "section_role_id", unique = true, nullable = false)
	public int getSectionRoleId() {
		return this.sectionRoleId;
	}

	public void setSectionRoleId(int sectionRoleId) {
		this.sectionRoleId = sectionRoleId;
	}

	@Column(name = "section_id")
	public Integer getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(Integer sectionId) {
		this.sectionId = sectionId;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
