package com.insta.hms.core.diagnostics.incomingsampleregistration;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.insta.hms.core.patient.PatientDetailsModel;
import com.insta.hms.mdm.centers.HospitalCenterMasterModel;
import com.insta.hms.mdm.doctors.DoctorsModel;
import com.insta.hms.mdm.referraldoctors.ReferralModel;

/**
 * IncomingSampleRegistrationModel generated by hbm2java
 */
@Entity
@Table(name = "incoming_sample_registration")
public class IncomingSampleRegistrationModel implements java.io.Serializable {

	private String incomingVisitId;
	private String origLabName;
	private String patientName;
	private Integer patientAge;
	private Character patientGender;
	private ReferralModel referringDoctor;
	private String address;
	private String billno;
	private Date date;
	private String category;
	private String phoneNo;
	private HospitalCenterMasterModel centerId;
	private String patientOtherInfo;
	private Integer sourceCenterId;
	private PatientDetailsModel mrNo;
	private String incomingSourceType;
	private Character ageUnit;
	private Date isrDateofbirth;
	private String hisVisitId;
	private String phoneNoCountryCode;
	private String governmentIdentifier;
	private Integer identifierId;
	private Set incomingSampleRegistrationDetailses = new HashSet(0);
	private DoctorsModel referralDoctorDoctors;

	public IncomingSampleRegistrationModel() {
	}

	public IncomingSampleRegistrationModel(String incomingVisitId, String billno, HospitalCenterMasterModel centerId) {
		this.incomingVisitId = incomingVisitId;
		this.billno = billno;
		this.centerId = centerId;
	}

	public IncomingSampleRegistrationModel(String incomingVisitId, String origLabName, String patientName,
			Integer patientAge, Character patientGender, ReferralModel referringDoctor, String address, String billno,
			Date date, String category, String phoneNo, HospitalCenterMasterModel centerId, 
			String patientOtherInfo, Integer sourceCenterId, PatientDetailsModel mrNo, 
			String incomingSourceType, Character ageUnit, Date isrDateofbirth, String hisVisitId,
			String phoneNoCountryCode, String governmentIdentifier, Integer identifierId,
			Set incomingSampleRegistrationDetailses) {
		this.incomingVisitId = incomingVisitId;
		this.origLabName = origLabName;
		this.patientName = patientName;
		this.patientAge = patientAge;
		this.patientGender = patientGender;
		this.referringDoctor = referringDoctor;
		this.address = address;
		this.billno = billno;
		this.date = date;
		this.category = category;
		this.phoneNo = phoneNo;
		this.centerId = centerId;
		this.patientOtherInfo = patientOtherInfo;
		this.sourceCenterId = sourceCenterId;
		this.mrNo = mrNo;
		this.incomingSourceType = incomingSourceType;
		this.ageUnit = ageUnit;
		this.isrDateofbirth = isrDateofbirth;
		this.hisVisitId = hisVisitId;
		this.phoneNoCountryCode = phoneNoCountryCode;
		this.governmentIdentifier = governmentIdentifier;
		this.identifierId = identifierId;
		this.incomingSampleRegistrationDetailses = incomingSampleRegistrationDetailses;
	}

	@Id

	@Column(name = "incoming_visit_id", unique = true, nullable = false, length = 15)
	public String getIncomingVisitId() {
		return this.incomingVisitId;
	}

	public void setIncomingVisitId(String incomingVisitId) {
		this.incomingVisitId = incomingVisitId;
	}

	@Column(name = "orig_lab_name", length = 100)
	public String getOrigLabName() {
		return this.origLabName;
	}

	public void setOrigLabName(String origLabName) {
		this.origLabName = origLabName;
	}

	@Column(name = "patient_name", length = 500)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "patient_age")
	public Integer getPatientAge() {
		return this.patientAge;
	}

	public void setPatientAge(Integer patientAge) {
		this.patientAge = patientAge;
	}

	@Column(name = "patient_gender", length = 1)
	public Character getPatientGender() {
		return this.patientGender;
	}

	public void setPatientGender(Character patientGender) {
		this.patientGender = patientGender;
	}

    @NotFound(action = NotFoundAction.IGNORE)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "referring_doctor", referencedColumnName = "referal_no", insertable = false, updatable = false)
	public ReferralModel getReferringDoctor() {
		return this.referringDoctor;
	}

	public void setReferringDoctor(ReferralModel referringDoctor) {
		this.referringDoctor = referringDoctor;
	}

	@NotFound(action = NotFoundAction.IGNORE)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "referring_doctor", referencedColumnName = "doctor_id", insertable = false, updatable = false)
	public DoctorsModel getReferringDoctorDoctors() {
	  return referralDoctorDoctors;
	}

	public void setReferringDoctorDoctors(DoctorsModel referralDoctorDoctors) {
	  this.referralDoctorDoctors = referralDoctorDoctors;
	}

	@Column(name = "address", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "billno", nullable = false, length = 25)
	public String getBillno() {
		return this.billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 35)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "category", length = 20)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "phone_no", length = 16)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "center_id", nullable = false, insertable = false, updatable = false)
    public HospitalCenterMasterModel getCenterId() {
		return this.centerId;
	}

	public void setCenterId(HospitalCenterMasterModel centerId) {
		this.centerId = centerId;
	}

	@Column(name = "patient_other_info", length = 100)
	public String getPatientOtherInfo() {
		return this.patientOtherInfo;
	}

	public void setPatientOtherInfo(String patientOtherInfo) {
		this.patientOtherInfo = patientOtherInfo;
	}

	@Column(name = "source_center_id")
	public Integer getSourceCenterId() {
		return this.sourceCenterId;
	}

	public void setSourceCenterId(Integer sourceCenterId) {
		this.sourceCenterId = sourceCenterId;
	}

	@NotFound(action = NotFoundAction.IGNORE)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mr_no")
	public PatientDetailsModel getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(PatientDetailsModel mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "incoming_source_type", length = 2)
	public String getIncomingSourceType() {
		return this.incomingSourceType;
	}

	public void setIncomingSourceType(String incomingSourceType) {
		this.incomingSourceType = incomingSourceType;
	}

	@Column(name = "age_unit", length = 1)
	public Character getAgeUnit() {
		return this.ageUnit;
	}

	public void setAgeUnit(Character ageUnit) {
		this.ageUnit = ageUnit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "isr_dateofbirth", length = 13)
	public Date getIsrDateofbirth() {
		return this.isrDateofbirth;
	}

	public void setIsrDateofbirth(Date isrDateofbirth) {
		this.isrDateofbirth = isrDateofbirth;
	}

	@Column(name = "his_visit_id", length = 15)
	public String getHisVisitId() {
		return this.hisVisitId;
	}

	public void setHisVisitId(String hisVisitId) {
		this.hisVisitId = hisVisitId;
	}

	@Column(name = "phone_no_country_code", length = 5)
	public String getPhoneNoCountryCode() {
		return this.phoneNoCountryCode;
	}

	public void setPhoneNoCountryCode(String phoneNoCountryCode) {
		this.phoneNoCountryCode = phoneNoCountryCode;
	}

	@Column(name = "government_identifier", length = 50)
	public String getGovernmentIdentifier() {
		return this.governmentIdentifier;
	}

	public void setGovernmentIdentifier(String governmentIdentifier) {
		this.governmentIdentifier = governmentIdentifier;
	}

	@Column(name = "identifier_id")
	public Integer getIdentifierId() {
		return this.identifierId;
	}

	public void setIdentifierId(Integer identifierId) {
		this.identifierId = identifierId;
	}
}
