package com.insta.hms.mdm.suppliercategories;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SupplierCategoryMasterModel generated by hbm2java
 */
@Entity
@Table(name = "supplier_category_master", uniqueConstraints = @UniqueConstraint(columnNames = "supp_category_name"))
public class SupplierCategoryMasterModel implements java.io.Serializable {

	private int suppCategoryId;
	private String suppCategoryName;
	private Set supplierMasters = new HashSet(0);

	public SupplierCategoryMasterModel() {
	}

	public SupplierCategoryMasterModel(int suppCategoryId, String suppCategoryName) {
		this.suppCategoryId = suppCategoryId;
		this.suppCategoryName = suppCategoryName;
	}

	public SupplierCategoryMasterModel(int suppCategoryId, String suppCategoryName, Set supplierMasters) {
		this.suppCategoryId = suppCategoryId;
		this.suppCategoryName = suppCategoryName;
		this.supplierMasters = supplierMasters;
	}

	@Id

	@Column(name = "supp_category_id", unique = true, nullable = false)
	public int getSuppCategoryId() {
		return this.suppCategoryId;
	}

	public void setSuppCategoryId(int suppCategoryId) {
		this.suppCategoryId = suppCategoryId;
	}

	@Column(name = "supp_category_name", unique = true, nullable = false, length = 100)
	public String getSuppCategoryName() {
		return this.suppCategoryName;
	}

	public void setSuppCategoryName(String suppCategoryName) {
		this.suppCategoryName = suppCategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplierCategoryMaster")
	public Set getSupplierMasters() {
		return this.supplierMasters;
	}

	public void setSupplierMasters(Set supplierMasters) {
		this.supplierMasters = supplierMasters;
	}

}
