package com.insta.hms.mdm.dailyrecurrences;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecurrenceDailyMasterModel generated by hbm2java
 */
@Entity
@Table(name = "recurrence_daily_master")
public class RecurrenceDailyMasterModel implements java.io.Serializable {

	private int recurrenceDailyId;
	private String displayName;
	private String status;
	private String timings;
	private Integer numActivities;
	private Date modTime;
	private String username;
	private Integer displayOrder;

	public RecurrenceDailyMasterModel() {
	}

	public RecurrenceDailyMasterModel(int recurrenceDailyId) {
		this.recurrenceDailyId = recurrenceDailyId;
	}

	public RecurrenceDailyMasterModel(int recurrenceDailyId, String displayName, String status, String timings,
			Integer numActivities, Date modTime, String username, Integer displayOrder) {
		this.recurrenceDailyId = recurrenceDailyId;
		this.displayName = displayName;
		this.status = status;
		this.timings = timings;
		this.numActivities = numActivities;
		this.modTime = modTime;
		this.username = username;
		this.displayOrder = displayOrder;
	}

	@Id

	@Column(name = "recurrence_daily_id", unique = true, nullable = false)
	public int getRecurrenceDailyId() {
		return this.recurrenceDailyId;
	}

	public void setRecurrenceDailyId(int recurrenceDailyId) {
		this.recurrenceDailyId = recurrenceDailyId;
	}

	@Column(name = "display_name", length = 50)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "timings", length = 100)
	public String getTimings() {
		return this.timings;
	}

	public void setTimings(String timings) {
		this.timings = timings;
	}

	@Column(name = "num_activities")
	public Integer getNumActivities() {
		return this.numActivities;
	}

	public void setNumActivities(Integer numActivities) {
		this.numActivities = numActivities;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "display_order")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

}
