package com.insta.hms.mdm.dentalsupplieritemrates;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.dentalsuppliers.DentalSupplierMasterModel;
import com.insta.hms.mdm.dentalsupplies.DentalSuppliesMasterModel;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DentalSupplierItemRateMasterModel generated by hbm2java
 */
@Entity
@Table(name = "dental_supplier_item_rate_master")
public class DentalSupplierItemRateMasterModel implements java.io.Serializable {

	private int itemSupplierRateId;
	private DentalSuppliesMasterModel DentalSuppliesMasterModel;
	private DentalSupplierMasterModel DentalSupplierMasterModel;
	private BigDecimal unitRate;
	private String status;
	private BigDecimal vatPerc;

	public DentalSupplierItemRateMasterModel() {
	}

	public DentalSupplierItemRateMasterModel(int itemSupplierRateId, DentalSuppliesMasterModel DentalSuppliesMasterModel,
			DentalSupplierMasterModel DentalSupplierMasterModel, BigDecimal unitRate, String status) {
		this.itemSupplierRateId = itemSupplierRateId;
		this.DentalSuppliesMasterModel = DentalSuppliesMasterModel;
		this.DentalSupplierMasterModel = DentalSupplierMasterModel;
		this.unitRate = unitRate;
		this.status = status;
	}

	public DentalSupplierItemRateMasterModel(int itemSupplierRateId, DentalSuppliesMasterModel DentalSuppliesMasterModel,
			DentalSupplierMasterModel DentalSupplierMasterModel, BigDecimal unitRate, String status, BigDecimal vatPerc) {
		this.itemSupplierRateId = itemSupplierRateId;
		this.DentalSuppliesMasterModel = DentalSuppliesMasterModel;
		this.DentalSupplierMasterModel = DentalSupplierMasterModel;
		this.unitRate = unitRate;
		this.status = status;
		this.vatPerc = vatPerc;
	}

	@Id

	@Column(name = "item_supplier_rate_id", unique = true, nullable = false)
	public int getItemSupplierRateId() {
		return this.itemSupplierRateId;
	}

	public void setItemSupplierRateId(int itemSupplierRateId) {
		this.itemSupplierRateId = itemSupplierRateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false)
	public DentalSuppliesMasterModel getDentalSuppliesMasterModel() {
		return this.DentalSuppliesMasterModel;
	}

	public void setDentalSuppliesMasterModel(DentalSuppliesMasterModel DentalSuppliesMasterModel) {
		this.DentalSuppliesMasterModel = DentalSuppliesMasterModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id", nullable = false)
	public DentalSupplierMasterModel getDentalSupplierMasterModel() {
		return this.DentalSupplierMasterModel;
	}

	public void setDentalSupplierMasterModel(DentalSupplierMasterModel DentalSupplierMasterModel) {
		this.DentalSupplierMasterModel = DentalSupplierMasterModel;
	}

	@Column(name = "unit_rate", nullable = false, precision = 15)
	public BigDecimal getUnitRate() {
		return this.unitRate;
	}

	public void setUnitRate(BigDecimal unitRate) {
		this.unitRate = unitRate;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "vat_perc", precision = 10)
	public BigDecimal getVatPerc() {
		return this.vatPerc;
	}

	public void setVatPerc(BigDecimal vatPerc) {
		this.vatPerc = vatPerc;
	}

}
