package com.insta.hms.mdm.vitalparameter.referenceranges;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.vitalparameters.VitalParameterMasterModel;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VitalReferenceRangeMasterModel generated by hbm2java
 */
@Entity
@Table(name = "vital_reference_range_master")
public class VitalReferenceRangeMasterModel implements java.io.Serializable {

	private int rangeId;
	private VitalParameterMasterModel VitalParameterMasterModel;
	private Character patientGender;
	private Integer minPatientAge;
	private Integer maxPatientAge;
	private char rangeForAll;
	private Character ageUnit;
	private BigDecimal minNormalValue;
	private BigDecimal maxNormalValue;
	private BigDecimal minCriticalValue;
	private BigDecimal maxCriticalValue;
	private BigDecimal minImprobableValue;
	private BigDecimal maxImprobableValue;
	private Integer priority;
	private String referenceRangeTxt;

	public VitalReferenceRangeMasterModel() {
	}

	public VitalReferenceRangeMasterModel(int rangeId, char rangeForAll) {
		this.rangeId = rangeId;
		this.rangeForAll = rangeForAll;
	}

	public VitalReferenceRangeMasterModel(int rangeId, VitalParameterMasterModel VitalParameterMasterModel, Character patientGender,
			Integer minPatientAge, Integer maxPatientAge, char rangeForAll, Character ageUnit,
			BigDecimal minNormalValue, BigDecimal maxNormalValue, BigDecimal minCriticalValue,
			BigDecimal maxCriticalValue, BigDecimal minImprobableValue, BigDecimal maxImprobableValue, Integer priority,
			String referenceRangeTxt) {
		this.rangeId = rangeId;
		this.VitalParameterMasterModel = VitalParameterMasterModel;
		this.patientGender = patientGender;
		this.minPatientAge = minPatientAge;
		this.maxPatientAge = maxPatientAge;
		this.rangeForAll = rangeForAll;
		this.ageUnit = ageUnit;
		this.minNormalValue = minNormalValue;
		this.maxNormalValue = maxNormalValue;
		this.minCriticalValue = minCriticalValue;
		this.maxCriticalValue = maxCriticalValue;
		this.minImprobableValue = minImprobableValue;
		this.maxImprobableValue = maxImprobableValue;
		this.priority = priority;
		this.referenceRangeTxt = referenceRangeTxt;
	}

	@Id

	@Column(name = "range_id", unique = true, nullable = false)
	public int getRangeId() {
		return this.rangeId;
	}

	public void setRangeId(int rangeId) {
		this.rangeId = rangeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "param_id")
	public VitalParameterMasterModel getVitalParameterMasterModel() {
		return this.VitalParameterMasterModel;
	}

	public void setVitalParameterMasterModel(VitalParameterMasterModel VitalParameterMasterModel) {
		this.VitalParameterMasterModel = VitalParameterMasterModel;
	}

	@Column(name = "patient_gender", length = 1)
	public Character getPatientGender() {
		return this.patientGender;
	}

	public void setPatientGender(Character patientGender) {
		this.patientGender = patientGender;
	}

	@Column(name = "min_patient_age")
	public Integer getMinPatientAge() {
		return this.minPatientAge;
	}

	public void setMinPatientAge(Integer minPatientAge) {
		this.minPatientAge = minPatientAge;
	}

	@Column(name = "max_patient_age")
	public Integer getMaxPatientAge() {
		return this.maxPatientAge;
	}

	public void setMaxPatientAge(Integer maxPatientAge) {
		this.maxPatientAge = maxPatientAge;
	}

	@Column(name = "range_for_all", nullable = false, length = 1)
	public char getRangeForAll() {
		return this.rangeForAll;
	}

	public void setRangeForAll(char rangeForAll) {
		this.rangeForAll = rangeForAll;
	}

	@Column(name = "age_unit", length = 1)
	public Character getAgeUnit() {
		return this.ageUnit;
	}

	public void setAgeUnit(Character ageUnit) {
		this.ageUnit = ageUnit;
	}

	@Column(name = "min_normal_value", precision = 131089, scale = 0)
	public BigDecimal getMinNormalValue() {
		return this.minNormalValue;
	}

	public void setMinNormalValue(BigDecimal minNormalValue) {
		this.minNormalValue = minNormalValue;
	}

	@Column(name = "max_normal_value", precision = 131089, scale = 0)
	public BigDecimal getMaxNormalValue() {
		return this.maxNormalValue;
	}

	public void setMaxNormalValue(BigDecimal maxNormalValue) {
		this.maxNormalValue = maxNormalValue;
	}

	@Column(name = "min_critical_value", precision = 131089, scale = 0)
	public BigDecimal getMinCriticalValue() {
		return this.minCriticalValue;
	}

	public void setMinCriticalValue(BigDecimal minCriticalValue) {
		this.minCriticalValue = minCriticalValue;
	}

	@Column(name = "max_critical_value", precision = 131089, scale = 0)
	public BigDecimal getMaxCriticalValue() {
		return this.maxCriticalValue;
	}

	public void setMaxCriticalValue(BigDecimal maxCriticalValue) {
		this.maxCriticalValue = maxCriticalValue;
	}

	@Column(name = "min_improbable_value", precision = 131089, scale = 0)
	public BigDecimal getMinImprobableValue() {
		return this.minImprobableValue;
	}

	public void setMinImprobableValue(BigDecimal minImprobableValue) {
		this.minImprobableValue = minImprobableValue;
	}

	@Column(name = "max_improbable_value", precision = 131089, scale = 0)
	public BigDecimal getMaxImprobableValue() {
		return this.maxImprobableValue;
	}

	public void setMaxImprobableValue(BigDecimal maxImprobableValue) {
		this.maxImprobableValue = maxImprobableValue;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "reference_range_txt", length = 500)
	public String getReferenceRangeTxt() {
		return this.referenceRangeTxt;
	}

	public void setReferenceRangeTxt(String referenceRangeTxt) {
		this.referenceRangeTxt = referenceRangeTxt;
	}

}
