package com.insta.hms.core.clinical.forms;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AutoSaveJsonDataModel generated by hbm2java
 */
@Entity
@Table(name = "auto_save_json_data")
public class AutoSaveJsonDataModel implements java.io.Serializable {

	private AutoSaveJsonDataIdSequence id;

	public AutoSaveJsonDataModel() {
	}

	public AutoSaveJsonDataModel(AutoSaveJsonDataIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", length = 15)),
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", length = 15)),
			@AttributeOverride(name = "sectionItemId", column = @Column(name = "section_item_id")),
			@AttributeOverride(name = "itemType", column = @Column(name = "item_type")),
			@AttributeOverride(name = "formType", column = @Column(name = "form_type")),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "jsonData", column = @Column(name = "json_data")),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)),
			@AttributeOverride(name = "sectionId", column = @Column(name = "section_id")),
			@AttributeOverride(name = "autoSaveSectionId", column = @Column(name = "auto_save_section_id", nullable = false)) })
	public AutoSaveJsonDataIdSequence getId() {
		return this.id;
	}

	public void setId(AutoSaveJsonDataIdSequence id) {
		this.id = id;
	}

}
