package com.insta.hms.core.clinical.forms;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientSectionDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "patient_section_details")
public class PatientSectionDetailsModel implements java.io.Serializable {

	private int sectionDetailId;
	private Integer sectionItemId;
	private String itemType;
	private String mrNo;
	private String patientId;
	private Integer sectionId;
	private Character obsoleteConsultationForm;
	private Character obsoleteTriageForm;
	private Character obsoleteAssessmentForm;
	private Integer obsoleteConsDisplayOrder;
	private Integer obsoleteTriageDisplayOrder;
	private Integer obsoleteAssessmentDisplayOrder;
	private Integer obsoleteIpRecordDisplayOrder;
	private Character sectionStatus;
	private String userName;
	private Date modTime;
	private Integer obsoleteOperationProcId;
	private Integer obsoleteSurgeryDisplayOrder;
	private Integer obsoleteServiceDisplayOrder;
	private Integer obsoleteServPrescribedId;
	private Integer obsoleteConsultationId;
	private Integer genericFormId;
	private Character finalized;
	private String finalizedUser;

	public PatientSectionDetailsModel() {
	}

	public PatientSectionDetailsModel(int sectionDetailId) {
		this.sectionDetailId = sectionDetailId;
	}

	public PatientSectionDetailsModel(int sectionDetailId, Integer sectionItemId, String itemType, String mrNo,
			String patientId, Integer sectionId, Character obsoleteConsultationForm, Character obsoleteTriageForm,
			Character obsoleteAssessmentForm, Integer obsoleteConsDisplayOrder, Integer obsoleteTriageDisplayOrder,
			Integer obsoleteAssessmentDisplayOrder, Integer obsoleteIpRecordDisplayOrder, Character sectionStatus,
			String userName, Date modTime, Integer obsoleteOperationProcId, Integer obsoleteSurgeryDisplayOrder,
			Integer obsoleteServiceDisplayOrder, Integer obsoleteServPrescribedId, Integer obsoleteConsultationId,
			Integer genericFormId, Character finalized, String finalizedUser) {
		this.sectionDetailId = sectionDetailId;
		this.sectionItemId = sectionItemId;
		this.itemType = itemType;
		this.mrNo = mrNo;
		this.patientId = patientId;
		this.sectionId = sectionId;
		this.obsoleteConsultationForm = obsoleteConsultationForm;
		this.obsoleteTriageForm = obsoleteTriageForm;
		this.obsoleteAssessmentForm = obsoleteAssessmentForm;
		this.obsoleteConsDisplayOrder = obsoleteConsDisplayOrder;
		this.obsoleteTriageDisplayOrder = obsoleteTriageDisplayOrder;
		this.obsoleteAssessmentDisplayOrder = obsoleteAssessmentDisplayOrder;
		this.obsoleteIpRecordDisplayOrder = obsoleteIpRecordDisplayOrder;
		this.sectionStatus = sectionStatus;
		this.userName = userName;
		this.modTime = modTime;
		this.obsoleteOperationProcId = obsoleteOperationProcId;
		this.obsoleteSurgeryDisplayOrder = obsoleteSurgeryDisplayOrder;
		this.obsoleteServiceDisplayOrder = obsoleteServiceDisplayOrder;
		this.obsoleteServPrescribedId = obsoleteServPrescribedId;
		this.obsoleteConsultationId = obsoleteConsultationId;
		this.genericFormId = genericFormId;
		this.finalized = finalized;
		this.finalizedUser = finalizedUser;
	}

	@Id

	@Column(name = "section_detail_id", unique = true, nullable = false)
	public int getSectionDetailId() {
		return this.sectionDetailId;
	}

	public void setSectionDetailId(int sectionDetailId) {
		this.sectionDetailId = sectionDetailId;
	}

	@Column(name = "section_item_id")
	public Integer getSectionItemId() {
		return this.sectionItemId;
	}

	public void setSectionItemId(Integer sectionItemId) {
		this.sectionItemId = sectionItemId;
	}

	@Column(name = "item_type")
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "patient_id", length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "section_id")
	public Integer getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(Integer sectionId) {
		this.sectionId = sectionId;
	}

	@Column(name = "obsolete_consultation_form", length = 1)
	public Character getObsoleteConsultationForm() {
		return this.obsoleteConsultationForm;
	}

	public void setObsoleteConsultationForm(Character obsoleteConsultationForm) {
		this.obsoleteConsultationForm = obsoleteConsultationForm;
	}

	@Column(name = "obsolete_triage_form", length = 1)
	public Character getObsoleteTriageForm() {
		return this.obsoleteTriageForm;
	}

	public void setObsoleteTriageForm(Character obsoleteTriageForm) {
		this.obsoleteTriageForm = obsoleteTriageForm;
	}

	@Column(name = "obsolete_assessment_form", length = 1)
	public Character getObsoleteAssessmentForm() {
		return this.obsoleteAssessmentForm;
	}

	public void setObsoleteAssessmentForm(Character obsoleteAssessmentForm) {
		this.obsoleteAssessmentForm = obsoleteAssessmentForm;
	}

	@Column(name = "obsolete_cons_display_order")
	public Integer getObsoleteConsDisplayOrder() {
		return this.obsoleteConsDisplayOrder;
	}

	public void setObsoleteConsDisplayOrder(Integer obsoleteConsDisplayOrder) {
		this.obsoleteConsDisplayOrder = obsoleteConsDisplayOrder;
	}

	@Column(name = "obsolete_triage_display_order")
	public Integer getObsoleteTriageDisplayOrder() {
		return this.obsoleteTriageDisplayOrder;
	}

	public void setObsoleteTriageDisplayOrder(Integer obsoleteTriageDisplayOrder) {
		this.obsoleteTriageDisplayOrder = obsoleteTriageDisplayOrder;
	}

	@Column(name = "obsolete_assessment_display_order")
	public Integer getObsoleteAssessmentDisplayOrder() {
		return this.obsoleteAssessmentDisplayOrder;
	}

	public void setObsoleteAssessmentDisplayOrder(Integer obsoleteAssessmentDisplayOrder) {
		this.obsoleteAssessmentDisplayOrder = obsoleteAssessmentDisplayOrder;
	}

	@Column(name = "obsolete_ip_record_display_order")
	public Integer getObsoleteIpRecordDisplayOrder() {
		return this.obsoleteIpRecordDisplayOrder;
	}

	public void setObsoleteIpRecordDisplayOrder(Integer obsoleteIpRecordDisplayOrder) {
		this.obsoleteIpRecordDisplayOrder = obsoleteIpRecordDisplayOrder;
	}

	@Column(name = "section_status", length = 1)
	public Character getSectionStatus() {
		return this.sectionStatus;
	}

	public void setSectionStatus(Character sectionStatus) {
		this.sectionStatus = sectionStatus;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "obsolete_operation_proc_id")
	public Integer getObsoleteOperationProcId() {
		return this.obsoleteOperationProcId;
	}

	public void setObsoleteOperationProcId(Integer obsoleteOperationProcId) {
		this.obsoleteOperationProcId = obsoleteOperationProcId;
	}

	@Column(name = "obsolete_surgery_display_order")
	public Integer getObsoleteSurgeryDisplayOrder() {
		return this.obsoleteSurgeryDisplayOrder;
	}

	public void setObsoleteSurgeryDisplayOrder(Integer obsoleteSurgeryDisplayOrder) {
		this.obsoleteSurgeryDisplayOrder = obsoleteSurgeryDisplayOrder;
	}

	@Column(name = "obsolete_service_display_order")
	public Integer getObsoleteServiceDisplayOrder() {
		return this.obsoleteServiceDisplayOrder;
	}

	public void setObsoleteServiceDisplayOrder(Integer obsoleteServiceDisplayOrder) {
		this.obsoleteServiceDisplayOrder = obsoleteServiceDisplayOrder;
	}

	@Column(name = "obsolete_serv_prescribed_id")
	public Integer getObsoleteServPrescribedId() {
		return this.obsoleteServPrescribedId;
	}

	public void setObsoleteServPrescribedId(Integer obsoleteServPrescribedId) {
		this.obsoleteServPrescribedId = obsoleteServPrescribedId;
	}

	@Column(name = "obsolete_consultation_id")
	public Integer getObsoleteConsultationId() {
		return this.obsoleteConsultationId;
	}

	public void setObsoleteConsultationId(Integer obsoleteConsultationId) {
		this.obsoleteConsultationId = obsoleteConsultationId;
	}

	@Column(name = "generic_form_id")
	public Integer getGenericFormId() {
		return this.genericFormId;
	}

	public void setGenericFormId(Integer genericFormId) {
		this.genericFormId = genericFormId;
	}

	@Column(name = "finalized", length = 1)
	public Character getFinalized() {
		return this.finalized;
	}

	public void setFinalized(Character finalized) {
		this.finalized = finalized;
	}

	@Column(name = "finalized_user", length = 15)
	public String getFinalizedUser() {
		return this.finalizedUser;
	}

	public void setFinalizedUser(String finalizedUser) {
		this.finalizedUser = finalizedUser;
	}

}
