package com.insta.hms.core.clinical.forms;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientSectionImageDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "patient_section_image_details")
public class PatientSectionImageDetailsModel implements java.io.Serializable {

	private PatientSectionImageDetailsIdSequence id;

	public PatientSectionImageDetailsModel() {
	}

	public PatientSectionImageDetailsModel(PatientSectionImageDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "obsoleteFormId", column = @Column(name = "obsolete_form_id")),
			@AttributeOverride(name = "fieldId", column = @Column(name = "field_id")),
			@AttributeOverride(name = "obsoleteConsultationId", column = @Column(name = "obsolete_consultation_id")),
			@AttributeOverride(name = "obsoleteMrNo", column = @Column(name = "obsolete_mr_no", length = 50)),
			@AttributeOverride(name = "coordinateX", column = @Column(name = "coordinate_x", precision = 131089, scale = 0)),
			@AttributeOverride(name = "coordinateY", column = @Column(name = "coordinate_y", precision = 131089, scale = 0)),
			@AttributeOverride(name = "markerId", column = @Column(name = "marker_id", nullable = false)),
			@AttributeOverride(name = "notes", column = @Column(name = "notes", nullable = false, length = 2000)),
			@AttributeOverride(name = "obsoletePatientId", column = @Column(name = "obsolete_patient_id", length = 15)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 30)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)),
			@AttributeOverride(name = "sectionDetailId", column = @Column(name = "section_detail_id")),
			@AttributeOverride(name = "obsoleteOperationProcId", column = @Column(name = "obsolete_operation_proc_id")),
			@AttributeOverride(name = "available", column = @Column(name = "available", length = 1)) })
	public PatientSectionImageDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(PatientSectionImageDetailsIdSequence id) {
		this.id = id;
	}

}
