package com.insta.hms.core.scheduler;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SchedulerResourceTypesModel generated by hbm2java
 */
@Entity
@Table(name = "scheduler_resource_types", uniqueConstraints = @UniqueConstraint(columnNames = { "category",
		"resource_type" }))
public class SchedulerResourceTypesModel implements java.io.Serializable {

	private SchedulerResourceTypesIdSequence id;

	public SchedulerResourceTypesModel() {
	}

	public SchedulerResourceTypesModel(SchedulerResourceTypesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "category", column = @Column(name = "category", length = 10)),
			@AttributeOverride(name = "resourceType", column = @Column(name = "resource_type", length = 10)),
			@AttributeOverride(name = "resourceDescription", column = @Column(name = "resource_description", length = 50)),
			@AttributeOverride(name = "primaryResource", column = @Column(name = "primary_resource")),
			@AttributeOverride(name = "resourceGroup", column = @Column(name = "resource_group", length = 10)) })
	public SchedulerResourceTypesIdSequence getId() {
		return this.id;
	}

	public void setId(SchedulerResourceTypesIdSequence id) {
		this.id = id;
	}

}
