package com.insta.hms.core.scheduler;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.resourceavailability.SchedulerMasterModel;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SchedulerAppointmentsModel generated by hbm2java
 */
@Entity
@Table(name = "scheduler_appointments", uniqueConstraints = @UniqueConstraint(columnNames = { "unique_appt_ind",
		"prim_res_id", "appointment_time" }))
public class SchedulerAppointmentsModel implements java.io.Serializable {

	private int appointmentId;
	private SchedulerMasterModel SchedulerMasterModel;
	private String mrNo;
	private String visitId;
	private String patientName;
	private String patientContact;
	private String resSchName;
	private Date appointmentTime;
	private Integer duration;
	private String appointmentStatus;
	private Date arrivalTime;
	private Date completedTime;
	private String bookedBy;
	private Date bookedTime;
	private String changedBy;
	private Date changedTime;
	private Date origApptTime;
	private char rescheduled;
	private String cancelReason;
	private Integer consultationTypeId;
	private String remarks;
	private String schedulerVisitType;
	private String schedulerPriorAuthNo;
	private Integer schedulerPriorAuthModeId;
	private Integer centerId;
	private String complaint;
	private String prescDocId;
	private Integer patPackageId;
	private Integer appSourceId;
	private String billNo;
	private String salutationName;
	private Integer apptToken;
	private Integer uniqueApptInd;
	private String primResId;
	private String patientContactCountryCode;
	private String practoAppointmentId;

	public SchedulerAppointmentsModel() {
	}

	public SchedulerAppointmentsModel(int appointmentId, String patientName, String patientContact, char rescheduled) {
		this.appointmentId = appointmentId;
		this.patientName = patientName;
		this.patientContact = patientContact;
		this.rescheduled = rescheduled;
	}

	public SchedulerAppointmentsModel(int appointmentId, SchedulerMasterModel SchedulerMasterModel, String mrNo, String visitId,
			String patientName, String patientContact, String resSchName, Date appointmentTime, Integer duration,
			String appointmentStatus, Date arrivalTime, Date completedTime, String bookedBy, Date bookedTime,
			String changedBy, Date changedTime, Date origApptTime, char rescheduled, String cancelReason,
			Integer consultationTypeId, String remarks, String schedulerVisitType, String schedulerPriorAuthNo,
			Integer schedulerPriorAuthModeId, Integer centerId, String complaint, String prescDocId,
			Integer patPackageId, Integer appSourceId, String billNo, String salutationName, Integer apptToken,
			Integer uniqueApptInd, String primResId, String patientContactCountryCode, String practoAppointmentId) {
		this.appointmentId = appointmentId;
		this.SchedulerMasterModel = SchedulerMasterModel;
		this.mrNo = mrNo;
		this.visitId = visitId;
		this.patientName = patientName;
		this.patientContact = patientContact;
		this.resSchName = resSchName;
		this.appointmentTime = appointmentTime;
		this.duration = duration;
		this.appointmentStatus = appointmentStatus;
		this.arrivalTime = arrivalTime;
		this.completedTime = completedTime;
		this.bookedBy = bookedBy;
		this.bookedTime = bookedTime;
		this.changedBy = changedBy;
		this.changedTime = changedTime;
		this.origApptTime = origApptTime;
		this.rescheduled = rescheduled;
		this.cancelReason = cancelReason;
		this.consultationTypeId = consultationTypeId;
		this.remarks = remarks;
		this.schedulerVisitType = schedulerVisitType;
		this.schedulerPriorAuthNo = schedulerPriorAuthNo;
		this.schedulerPriorAuthModeId = schedulerPriorAuthModeId;
		this.centerId = centerId;
		this.complaint = complaint;
		this.prescDocId = prescDocId;
		this.patPackageId = patPackageId;
		this.appSourceId = appSourceId;
		this.billNo = billNo;
		this.salutationName = salutationName;
		this.apptToken = apptToken;
		this.uniqueApptInd = uniqueApptInd;
		this.primResId = primResId;
		this.patientContactCountryCode = patientContactCountryCode;
		this.practoAppointmentId = practoAppointmentId;
	}

	@Id

	@Column(name = "appointment_id", unique = true, nullable = false)
	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "res_sch_id")
	public SchedulerMasterModel getSchedulerMasterModel() {
		return this.SchedulerMasterModel;
	}

	public void setSchedulerMasterModel(SchedulerMasterModel SchedulerMasterModel) {
		this.SchedulerMasterModel = SchedulerMasterModel;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "visit_id", length = 15)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Column(name = "patient_name", nullable = false, length = 100)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "patient_contact", nullable = false, length = 16)
	public String getPatientContact() {
		return this.patientContact;
	}

	public void setPatientContact(String patientContact) {
		this.patientContact = patientContact;
	}

	@Column(name = "res_sch_name", length = 100)
	public String getResSchName() {
		return this.resSchName;
	}

	public void setResSchName(String resSchName) {
		this.resSchName = resSchName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appointment_time", length = 29)
	public Date getAppointmentTime() {
		return this.appointmentTime;
	}

	public void setAppointmentTime(Date appointmentTime) {
		this.appointmentTime = appointmentTime;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "appointment_status", length = 30)
	public String getAppointmentStatus() {
		return this.appointmentStatus;
	}

	public void setAppointmentStatus(String appointmentStatus) {
		this.appointmentStatus = appointmentStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrival_time", length = 29)
	public Date getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "completed_time", length = 29)
	public Date getCompletedTime() {
		return this.completedTime;
	}

	public void setCompletedTime(Date completedTime) {
		this.completedTime = completedTime;
	}

	@Column(name = "booked_by", length = 30)
	public String getBookedBy() {
		return this.bookedBy;
	}

	public void setBookedBy(String bookedBy) {
		this.bookedBy = bookedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "booked_time", length = 29)
	public Date getBookedTime() {
		return this.bookedTime;
	}

	public void setBookedTime(Date bookedTime) {
		this.bookedTime = bookedTime;
	}

	@Column(name = "changed_by", length = 30)
	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changed_time", length = 29)
	public Date getChangedTime() {
		return this.changedTime;
	}

	public void setChangedTime(Date changedTime) {
		this.changedTime = changedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "orig_appt_time", length = 29)
	public Date getOrigApptTime() {
		return this.origApptTime;
	}

	public void setOrigApptTime(Date origApptTime) {
		this.origApptTime = origApptTime;
	}

	@Column(name = "rescheduled", nullable = false, length = 1)
	public char getRescheduled() {
		return this.rescheduled;
	}

	public void setRescheduled(char rescheduled) {
		this.rescheduled = rescheduled;
	}

	@Column(name = "cancel_reason", length = 200)
	public String getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	@Column(name = "consultation_type_id")
	public Integer getConsultationTypeId() {
		return this.consultationTypeId;
	}

	public void setConsultationTypeId(Integer consultationTypeId) {
		this.consultationTypeId = consultationTypeId;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "scheduler_visit_type", length = 1)
	public String getSchedulerVisitType() {
		return this.schedulerVisitType;
	}

	public void setSchedulerVisitType(String schedulerVisitType) {
		this.schedulerVisitType = schedulerVisitType;
	}

	@Column(name = "scheduler_prior_auth_no", length = 50)
	public String getSchedulerPriorAuthNo() {
		return this.schedulerPriorAuthNo;
	}

	public void setSchedulerPriorAuthNo(String schedulerPriorAuthNo) {
		this.schedulerPriorAuthNo = schedulerPriorAuthNo;
	}

	@Column(name = "scheduler_prior_auth_mode_id")
	public Integer getSchedulerPriorAuthModeId() {
		return this.schedulerPriorAuthModeId;
	}

	public void setSchedulerPriorAuthModeId(Integer schedulerPriorAuthModeId) {
		this.schedulerPriorAuthModeId = schedulerPriorAuthModeId;
	}

	@Column(name = "center_id")
	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	@Column(name = "complaint")
	public String getComplaint() {
		return this.complaint;
	}

	public void setComplaint(String complaint) {
		this.complaint = complaint;
	}

	@Column(name = "presc_doc_id", length = 30)
	public String getPrescDocId() {
		return this.prescDocId;
	}

	public void setPrescDocId(String prescDocId) {
		this.prescDocId = prescDocId;
	}

	@Column(name = "pat_package_id")
	public Integer getPatPackageId() {
		return this.patPackageId;
	}

	public void setPatPackageId(Integer patPackageId) {
		this.patPackageId = patPackageId;
	}

	@Column(name = "app_source_id")
	public Integer getAppSourceId() {
		return this.appSourceId;
	}

	public void setAppSourceId(Integer appSourceId) {
		this.appSourceId = appSourceId;
	}

	@Column(name = "bill_no", length = 15)
	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	@Column(name = "salutation_name", length = 50)
	public String getSalutationName() {
		return this.salutationName;
	}

	public void setSalutationName(String salutationName) {
		this.salutationName = salutationName;
	}

	@Column(name = "appt_token")
	public Integer getApptToken() {
		return this.apptToken;
	}

	public void setApptToken(Integer apptToken) {
		this.apptToken = apptToken;
	}

	@Column(name = "unique_appt_ind")
	public Integer getUniqueApptInd() {
		return this.uniqueApptInd;
	}

	public void setUniqueApptInd(Integer uniqueApptInd) {
		this.uniqueApptInd = uniqueApptInd;
	}

	@Column(name = "prim_res_id", length = 15)
	public String getPrimResId() {
		return this.primResId;
	}

	public void setPrimResId(String primResId) {
		this.primResId = primResId;
	}

	@Column(name = "patient_contact_country_code", length = 5)
	public String getPatientContactCountryCode() {
		return this.patientContactCountryCode;
	}

	public void setPatientContactCountryCode(String patientContactCountryCode) {
		this.patientContactCountryCode = patientContactCountryCode;
	}

	@Column(name = "practo_appointment_id", length = 100)
	public String getPractoAppointmentId() {
		return this.practoAppointmentId;
	}

	public void setPractoAppointmentId(String practoAppointmentId) {
		this.practoAppointmentId = practoAppointmentId;
	}

}
