package com.insta.hms.mdm.sequences.billsequences;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.centers.HospitalCenterMasterModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HospBillSeqPrefsModel generated by hbm2java
 */
@Entity
@Table(name = "hosp_bill_seq_prefs")
public class HospBillSeqPrefsModel implements java.io.Serializable {

	private int billSeqId;
	private HospitalCenterMasterModel HospitalCenterMasterModel;
	private int priority;
	private char billType;
	private char visitType;
	private String patternId;
	private char restrictionType;
	private Character isTpa;
	private char isCreditNote;

	public HospBillSeqPrefsModel() {
	}

	public HospBillSeqPrefsModel(int billSeqId, HospitalCenterMasterModel HospitalCenterMasterModel, int priority, char billType,
			char visitType, String patternId, char restrictionType, char isCreditNote) {
		this.billSeqId = billSeqId;
		this.HospitalCenterMasterModel = HospitalCenterMasterModel;
		this.priority = priority;
		this.billType = billType;
		this.visitType = visitType;
		this.patternId = patternId;
		this.restrictionType = restrictionType;
		this.isCreditNote = isCreditNote;
	}

	public HospBillSeqPrefsModel(int billSeqId, HospitalCenterMasterModel HospitalCenterMasterModel, int priority, char billType,
			char visitType, String patternId, char restrictionType, Character isTpa, char isCreditNote) {
		this.billSeqId = billSeqId;
		this.HospitalCenterMasterModel = HospitalCenterMasterModel;
		this.priority = priority;
		this.billType = billType;
		this.visitType = visitType;
		this.patternId = patternId;
		this.restrictionType = restrictionType;
		this.isTpa = isTpa;
		this.isCreditNote = isCreditNote;
	}

	@Id

	@Column(name = "bill_seq_id", unique = true, nullable = false)
	public int getBillSeqId() {
		return this.billSeqId;
	}

	public void setBillSeqId(int billSeqId) {
		this.billSeqId = billSeqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "center_id", nullable = false)
	public HospitalCenterMasterModel getHospitalCenterMasterModel() {
		return this.HospitalCenterMasterModel;
	}

	public void setHospitalCenterMasterModel(HospitalCenterMasterModel HospitalCenterMasterModel) {
		this.HospitalCenterMasterModel = HospitalCenterMasterModel;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "bill_type", nullable = false, length = 1)
	public char getBillType() {
		return this.billType;
	}

	public void setBillType(char billType) {
		this.billType = billType;
	}

	@Column(name = "visit_type", nullable = false, length = 1)
	public char getVisitType() {
		return this.visitType;
	}

	public void setVisitType(char visitType) {
		this.visitType = visitType;
	}

	@Column(name = "pattern_id", nullable = false)
	public String getPatternId() {
		return this.patternId;
	}

	public void setPatternId(String patternId) {
		this.patternId = patternId;
	}

	@Column(name = "restriction_type", nullable = false, length = 1)
	public char getRestrictionType() {
		return this.restrictionType;
	}

	public void setRestrictionType(char restrictionType) {
		this.restrictionType = restrictionType;
	}

	@Column(name = "is_tpa", length = 1)
	public Character getIsTpa() {
		return this.isTpa;
	}

	public void setIsTpa(Character isTpa) {
		this.isTpa = isTpa;
	}

	@Column(name = "is_credit_note", nullable = false, length = 1)
	public char getIsCreditNote() {
		return this.isCreditNote;
	}

	public void setIsCreditNote(char isCreditNote) {
		this.isCreditNote = isCreditNote;
	}

}
