package com.insta.hms.mdm.insuranceitemcategories;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemInsuranceCategoriesModel generated by hbm2java
 */
@Entity
@Table(name = "item_insurance_categories")
public class ItemInsuranceCategoriesModel implements java.io.Serializable {

	private int insuranceCategoryId;
	private String insuranceCategoryName;
	private Character insurancePayable;
	private char systemCategory;

	public ItemInsuranceCategoriesModel() {
	}

	public ItemInsuranceCategoriesModel(int insuranceCategoryId, char systemCategory) {
		this.insuranceCategoryId = insuranceCategoryId;
		this.systemCategory = systemCategory;
	}

	public ItemInsuranceCategoriesModel(int insuranceCategoryId, String insuranceCategoryName, Character insurancePayable,
			char systemCategory) {
		this.insuranceCategoryId = insuranceCategoryId;
		this.insuranceCategoryName = insuranceCategoryName;
		this.insurancePayable = insurancePayable;
		this.systemCategory = systemCategory;
	}

	@Id

	@Column(name = "insurance_category_id", unique = true, nullable = false)
	public int getInsuranceCategoryId() {
		return this.insuranceCategoryId;
	}

	public void setInsuranceCategoryId(int insuranceCategoryId) {
		this.insuranceCategoryId = insuranceCategoryId;
	}

	@Column(name = "insurance_category_name", length = 100)
	public String getInsuranceCategoryName() {
		return this.insuranceCategoryName;
	}

	public void setInsuranceCategoryName(String insuranceCategoryName) {
		this.insuranceCategoryName = insuranceCategoryName;
	}

	@Column(name = "insurance_payable", length = 1)
	public Character getInsurancePayable() {
		return this.insurancePayable;
	}

	public void setInsurancePayable(Character insurancePayable) {
		this.insurancePayable = insurancePayable;
	}

	@Column(name = "system_category", nullable = false, length = 1)
	public char getSystemCategory() {
		return this.systemCategory;
	}

	public void setSystemCategory(char systemCategory) {
		this.systemCategory = systemCategory;
	}

}
