package com.insta.hms.jobs;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobLogModel generated by hbm2java
 */
@Entity
@Table(name = "job_log")
public class JobLogModel implements java.io.Serializable {

	private int jobLogId;
	private String jobName;
	private Date jobStartTime;
	private Date jobEndTime;
	private String jobStatus;
	private String jobGroup;
	private String statusDesc;

	public JobLogModel() {
	}

	public JobLogModel(int jobLogId) {
		this.jobLogId = jobLogId;
	}

	public JobLogModel(int jobLogId, String jobName, Date jobStartTime, Date jobEndTime, String jobStatus, String jobGroup,
			String statusDesc) {
		this.jobLogId = jobLogId;
		this.jobName = jobName;
		this.jobStartTime = jobStartTime;
		this.jobEndTime = jobEndTime;
		this.jobStatus = jobStatus;
		this.jobGroup = jobGroup;
		this.statusDesc = statusDesc;
	}

	@Id

	@Column(name = "job_log_id", unique = true, nullable = false)
	public int getJobLogIdSequence() {
		return this.jobLogId;
	}

	public void setJobLogIdSequence(int jobLogId) {
		this.jobLogId = jobLogId;
	}

	@Column(name = "job_name")
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "job_start_time", length = 29)
	public Date getJobStartTime() {
		return this.jobStartTime;
	}

	public void setJobStartTime(Date jobStartTime) {
		this.jobStartTime = jobStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "job_end_time", length = 29)
	public Date getJobEndTime() {
		return this.jobEndTime;
	}

	public void setJobEndTime(Date jobEndTime) {
		this.jobEndTime = jobEndTime;
	}

	@Column(name = "job_status")
	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "job_group")
	public String getJobGroup() {
		return this.jobGroup;
	}

	public void setJobGroup(String jobGroup) {
		this.jobGroup = jobGroup;
	}

	@Column(name = "status_desc")
	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

}
