package com.insta.hms.mdm.diagexportinterfaces;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiagnosticsExportInterfaceIdSequence generated by hbm2java
 */
@Embeddable
public class DiagnosticsExportInterfaceIdSequence implements java.io.Serializable {

	private String testId;
	private String interfaceName;
	private String itemType;

	public DiagnosticsExportInterfaceIdSequence() {
	}

	public DiagnosticsExportInterfaceIdSequence(String testId, String interfaceName, String itemType) {
		this.testId = testId;
		this.interfaceName = interfaceName;
		this.itemType = itemType;
	}

	@Column(name = "test_id", nullable = false, length = 50)
	public String getTestId() {
		return this.testId;
	}

	public void setTestId(String testId) {
		this.testId = testId;
	}

	@Column(name = "interface_name", nullable = false)
	public String getInterfaceName() {
		return this.interfaceName;
	}

	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}

	@Column(name = "item_type", nullable = false)
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiagnosticsExportInterfaceIdSequence))
			return false;
		DiagnosticsExportInterfaceIdSequence castOther = (DiagnosticsExportInterfaceIdSequence) other;

		return ((this.getTestId() == castOther.getTestId()) || (this.getTestId() != null
				&& castOther.getTestId() != null && this.getTestId().equals(castOther.getTestId())))
				&& ((this.getInterfaceName() == castOther.getInterfaceName())
						|| (this.getInterfaceName() != null && castOther.getInterfaceName() != null
								&& this.getInterfaceName().equals(castOther.getInterfaceName())))
				&& ((this.getItemType() == castOther.getItemType()) || (this.getItemType() != null
						&& castOther.getItemType() != null && this.getItemType().equals(castOther.getItemType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTestId() == null ? 0 : this.getTestId().hashCode());
		result = 37 * result + (getInterfaceName() == null ? 0 : this.getInterfaceName().hashCode());
		result = 37 * result + (getItemType() == null ? 0 : this.getItemType().hashCode());
		return result;
	}

}
