package com.insta.hms.mdm.discountplans;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DiscountPlanMainModel generated by hbm2java
 */
@Entity
@Table(name = "discount_plan_main")
public class DiscountPlanMainModel implements java.io.Serializable {

	private int discountPlanId;
	private String discountPlanName;
	private String discountPlanDescription;
	private Date validityStart;
	private Date validityEnd;
	private Character status;
	private Set discountPlanCenterMasters = new HashSet(0);
	private Set discountPlanDetailses = new HashSet(0);

	public DiscountPlanMainModel() {
	}

	public DiscountPlanMainModel(int discountPlanId, String discountPlanName) {
		this.discountPlanId = discountPlanId;
		this.discountPlanName = discountPlanName;
	}

	public DiscountPlanMainModel(int discountPlanId, String discountPlanName, String discountPlanDescription,
			Date validityStart, Date validityEnd, Character status, Set discountPlanCenterMasters,
			Set discountPlanDetailses) {
		this.discountPlanId = discountPlanId;
		this.discountPlanName = discountPlanName;
		this.discountPlanDescription = discountPlanDescription;
		this.validityStart = validityStart;
		this.validityEnd = validityEnd;
		this.status = status;
		this.discountPlanCenterMasters = discountPlanCenterMasters;
		this.discountPlanDetailses = discountPlanDetailses;
	}

	@Id

	@Column(name = "discount_plan_id", unique = true, nullable = false)
	public int getDiscountPlanId() {
		return this.discountPlanId;
	}

	public void setDiscountPlanId(int discountPlanId) {
		this.discountPlanId = discountPlanId;
	}

	@Column(name = "discount_plan_name", nullable = false, length = 100)
	public String getDiscountPlanName() {
		return this.discountPlanName;
	}

	public void setDiscountPlanName(String discountPlanName) {
		this.discountPlanName = discountPlanName;
	}

	@Column(name = "discount_plan_description")
	public String getDiscountPlanDescription() {
		return this.discountPlanDescription;
	}

	public void setDiscountPlanDescription(String discountPlanDescription) {
		this.discountPlanDescription = discountPlanDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "validity_start", length = 13)
	public Date getValidityStart() {
		return this.validityStart;
	}

	public void setValidityStart(Date validityStart) {
		this.validityStart = validityStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "validity_end", length = 13)
	public Date getValidityEnd() {
		return this.validityEnd;
	}

	public void setValidityEnd(Date validityEnd) {
		this.validityEnd = validityEnd;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountPlanMain")
	public Set getDiscountPlanCenterMasters() {
		return this.discountPlanCenterMasters;
	}

	public void setDiscountPlanCenterMasters(Set discountPlanCenterMasters) {
		this.discountPlanCenterMasters = discountPlanCenterMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountPlanMain")
	public Set getDiscountPlanDetailses() {
		return this.discountPlanDetailses;
	}

	public void setDiscountPlanDetailses(Set discountPlanDetailses) {
		this.discountPlanDetailses = discountPlanDetailses;
	}

}
