package com.insta.hms.mdm.samplesources;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SampleSourcesModel generated by hbm2java
 */
@Entity
@Table(name = "sample_sources")
public class SampleSourcesModel implements java.io.Serializable {

	private SampleSourcesIdSequence id;

	public SampleSourcesModel() {
	}

	public SampleSourcesModel(SampleSourcesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "sourceId", column = @Column(name = "source_id")),
			@AttributeOverride(name = "sourceName", column = @Column(name = "source_name", length = 100)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)) })
	public SampleSourcesIdSequence getId() {
		return this.id;
	}

	public void setId(SampleSourcesIdSequence id) {
		this.id = id;
	}

}
