package com.insta.hms.mdm.diagdepartments;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DiagnosticsDepartmentsModel generated by hbm2java
 */
@Entity
@Table(name = "diagnostics_departments", uniqueConstraints = @UniqueConstraint(columnNames = "ddept_name"))
public class DiagnosticsDepartmentsModel implements java.io.Serializable {

	private String ddeptId;
	private String ddeptName;
	private Character status;
	private String designation;
	private String category;
	private BigDecimal displayOrder;

	public DiagnosticsDepartmentsModel() {
	}

	public DiagnosticsDepartmentsModel(String ddeptId, String ddeptName, BigDecimal displayOrder) {
		this.ddeptId = ddeptId;
		this.ddeptName = ddeptName;
		this.displayOrder = displayOrder;
	}

	public DiagnosticsDepartmentsModel(String ddeptId, String ddeptName, Character status, String designation,
			String category, BigDecimal displayOrder) {
		this.ddeptId = ddeptId;
		this.ddeptName = ddeptName;
		this.status = status;
		this.designation = designation;
		this.category = category;
		this.displayOrder = displayOrder;
	}

	@Id

	@Column(name = "ddept_id", unique = true, nullable = false, length = 10)
	public String getDdeptId() {
		return this.ddeptId;
	}

	public void setDdeptId(String ddeptId) {
		this.ddeptId = ddeptId;
	}

	@Column(name = "ddept_name", unique = true, nullable = false, length = 150)
	public String getDdeptName() {
		return this.ddeptName;
	}

	public void setDdeptName(String ddeptName) {
		this.ddeptName = ddeptName;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "designation", length = 100)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "category", length = 10)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "display_order", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(BigDecimal displayOrder) {
		this.displayOrder = displayOrder;
	}

}
