package com.insta.hms.mdm.countries;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CountryMasterModel generated by hbm2java
 */
@Entity
@Table(name = "country_master")
public class CountryMasterModel implements java.io.Serializable {

	private String countryId;
	private String countryName;
	private Character status;
	private String countryCode;
	private String alpha2Code;
	private String alpha3Code;
	private String icaoAlpha3Code;
	private String numericCode;
	private String nationality;
	private Set donorRegistrations = new HashSet(0);

	public CountryMasterModel() {
	}

	public CountryMasterModel(String countryId, String countryName) {
		this.countryId = countryId;
		this.countryName = countryName;
	}

	public CountryMasterModel(String countryId, String countryName, Character status, String countryCode, String alpha2Code,
			String alpha3Code, String icaoAlpha3Code, String numericCode, String nationality, Set donorRegistrations) {
		this.countryId = countryId;
		this.countryName = countryName;
		this.status = status;
		this.countryCode = countryCode;
		this.alpha2Code = alpha2Code;
		this.alpha3Code = alpha3Code;
		this.icaoAlpha3Code = icaoAlpha3Code;
		this.numericCode = numericCode;
		this.nationality = nationality;
		this.donorRegistrations = donorRegistrations;
	}

	@Id

	@Column(name = "country_id", unique = true, nullable = false, length = 10)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "country_name", nullable = false, length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "country_code", length = 30)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "alpha2_code", length = 2)
	public String getAlpha2Code() {
		return this.alpha2Code;
	}

	public void setAlpha2Code(String alpha2Code) {
		this.alpha2Code = alpha2Code;
	}

	@Column(name = "alpha3_code", length = 3)
	public String getAlpha3Code() {
		return this.alpha3Code;
	}

	public void setAlpha3Code(String alpha3Code) {
		this.alpha3Code = alpha3Code;
	}

	@Column(name = "icao_alpha3_code", length = 3)
	public String getIcaoAlpha3Code() {
		return this.icaoAlpha3Code;
	}

	public void setIcaoAlpha3Code(String icaoAlpha3Code) {
		this.icaoAlpha3Code = icaoAlpha3Code;
	}

	@Column(name = "numeric_code", length = 5)
	public String getNumericCode() {
		return this.numericCode;
	}

	public void setNumericCode(String numericCode) {
		this.numericCode = numericCode;
	}

	@Column(name = "nationality", length = 1)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryMaster")
	public Set getDonorRegistrations() {
		return this.donorRegistrations;
	}

	public void setDonorRegistrations(Set donorRegistrations) {
		this.donorRegistrations = donorRegistrations;
	}

}
