package com.insta.hms.core.clinical.consultation.prescriptions;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientMedicinePrescriptionsIdSequence generated by hbm2java
 */
@Embeddable
public class PatientMedicinePrescriptionsIdSequence implements java.io.Serializable {

	private String frequency;
	private Integer medicineQuantity;
	private String medicineRemarks;
	private Date modTime;
	private BigDecimal issuedQty;
	private String initialSaleId;
	private String finalSaleId;
	private Date activityDueDate;
	private Integer medicineId;
	private Integer routeOfAdmin;
	private String strength;
	private String genericCode;
	private Integer itemFormId;
	private String itemStrength;
	private String visitId;
	private Integer duration;
	private Character durationUnits;
	private Integer pbmPrescId;
	private Integer itemStrengthUnits;
	private char erxStatus;
	private String erxDenialCode;
	private String erxDenialRemarks;
	private String consumptionUom;
	private BigDecimal erxApprovedQuantity;
	private Integer opMedicinePresId;
	private String adminStrength;
	private char sendForErx;
	private String username;
	private String refills;

	public PatientMedicinePrescriptionsIdSequence() {
	}

	public PatientMedicinePrescriptionsIdSequence(Date modTime, char erxStatus, char sendForErx) {
		this.modTime = modTime;
		this.erxStatus = erxStatus;
		this.sendForErx = sendForErx;
	}

	public PatientMedicinePrescriptionsIdSequence(String frequency, Integer medicineQuantity, String medicineRemarks,
			Date modTime, BigDecimal issuedQty, String initialSaleId, String finalSaleId, Date activityDueDate,
			Integer medicineId, Integer routeOfAdmin, String strength, String genericCode, Integer itemFormId,
			String itemStrength, String visitId, Integer duration, Character durationUnits, Integer pbmPrescId,
			Integer itemStrengthUnits, char erxStatus, String erxDenialCode, String erxDenialRemarks,
			String consumptionUom, BigDecimal erxApprovedQuantity, Integer opMedicinePresId, String adminStrength,
			char sendForErx, String username, String refills) {
		this.frequency = frequency;
		this.medicineQuantity = medicineQuantity;
		this.medicineRemarks = medicineRemarks;
		this.modTime = modTime;
		this.issuedQty = issuedQty;
		this.initialSaleId = initialSaleId;
		this.finalSaleId = finalSaleId;
		this.activityDueDate = activityDueDate;
		this.medicineId = medicineId;
		this.routeOfAdmin = routeOfAdmin;
		this.strength = strength;
		this.genericCode = genericCode;
		this.itemFormId = itemFormId;
		this.itemStrength = itemStrength;
		this.visitId = visitId;
		this.duration = duration;
		this.durationUnits = durationUnits;
		this.pbmPrescId = pbmPrescId;
		this.itemStrengthUnits = itemStrengthUnits;
		this.erxStatus = erxStatus;
		this.erxDenialCode = erxDenialCode;
		this.erxDenialRemarks = erxDenialRemarks;
		this.consumptionUom = consumptionUom;
		this.erxApprovedQuantity = erxApprovedQuantity;
		this.opMedicinePresId = opMedicinePresId;
		this.adminStrength = adminStrength;
		this.sendForErx = sendForErx;
		this.username = username;
		this.refills = refills;
	}

	@Column(name = "frequency", length = 150)
	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "medicine_quantity")
	public Integer getMedicineQuantity() {
		return this.medicineQuantity;
	}

	public void setMedicineQuantity(Integer medicineQuantity) {
		this.medicineQuantity = medicineQuantity;
	}

	@Column(name = "medicine_remarks", length = 2000)
	public String getMedicineRemarks() {
		return this.medicineRemarks;
	}

	public void setMedicineRemarks(String medicineRemarks) {
		this.medicineRemarks = medicineRemarks;
	}

	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "issued_qty", precision = 131089, scale = 0)
	public BigDecimal getIssuedQty() {
		return this.issuedQty;
	}

	public void setIssuedQty(BigDecimal issuedQty) {
		this.issuedQty = issuedQty;
	}

	@Column(name = "initial_sale_id", length = 15)
	public String getInitialSaleId() {
		return this.initialSaleId;
	}

	public void setInitialSaleId(String initialSaleId) {
		this.initialSaleId = initialSaleId;
	}

	@Column(name = "final_sale_id", length = 15)
	public String getFinalSaleId() {
		return this.finalSaleId;
	}

	public void setFinalSaleId(String finalSaleId) {
		this.finalSaleId = finalSaleId;
	}

	@Column(name = "activity_due_date", length = 29)
	public Date getActivityDueDate() {
		return this.activityDueDate;
	}

	public void setActivityDueDate(Date activityDueDate) {
		this.activityDueDate = activityDueDate;
	}

	@Column(name = "medicine_id")
	public Integer getMedicineId() {
		return this.medicineId;
	}

	public void setMedicineId(Integer medicineId) {
		this.medicineId = medicineId;
	}

	@Column(name = "route_of_admin")
	public Integer getRouteOfAdmin() {
		return this.routeOfAdmin;
	}

	public void setRouteOfAdmin(Integer routeOfAdmin) {
		this.routeOfAdmin = routeOfAdmin;
	}

	@Column(name = "strength", length = 100)
	public String getStrength() {
		return this.strength;
	}

	public void setStrength(String strength) {
		this.strength = strength;
	}

	@Column(name = "generic_code", length = 10)
	public String getGenericCode() {
		return this.genericCode;
	}

	public void setGenericCode(String genericCode) {
		this.genericCode = genericCode;
	}

	@Column(name = "item_form_id")
	public Integer getItemFormId() {
		return this.itemFormId;
	}

	public void setItemFormId(Integer itemFormId) {
		this.itemFormId = itemFormId;
	}

	@Column(name = "item_strength", length = 50)
	public String getItemStrength() {
		return this.itemStrength;
	}

	public void setItemStrength(String itemStrength) {
		this.itemStrength = itemStrength;
	}

	@Column(name = "visit_id", length = 15)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "duration_units", length = 1)
	public Character getDurationUnits() {
		return this.durationUnits;
	}

	public void setDurationUnits(Character durationUnits) {
		this.durationUnits = durationUnits;
	}

	@Column(name = "pbm_presc_id")
	public Integer getPbmPrescId() {
		return this.pbmPrescId;
	}

	public void setPbmPrescId(Integer pbmPrescId) {
		this.pbmPrescId = pbmPrescId;
	}

	@Column(name = "item_strength_units")
	public Integer getItemStrengthUnits() {
		return this.itemStrengthUnits;
	}

	public void setItemStrengthUnits(Integer itemStrengthUnits) {
		this.itemStrengthUnits = itemStrengthUnits;
	}

	@Column(name = "erx_status", nullable = false, length = 1)
	public char getErxStatus() {
		return this.erxStatus;
	}

	public void setErxStatus(char erxStatus) {
		this.erxStatus = erxStatus;
	}

	@Column(name = "erx_denial_code", length = 15)
	public String getErxDenialCode() {
		return this.erxDenialCode;
	}

	public void setErxDenialCode(String erxDenialCode) {
		this.erxDenialCode = erxDenialCode;
	}

	@Column(name = "erx_denial_remarks")
	public String getErxDenialRemarks() {
		return this.erxDenialRemarks;
	}

	public void setErxDenialRemarks(String erxDenialRemarks) {
		this.erxDenialRemarks = erxDenialRemarks;
	}

	@Column(name = "consumption_uom", length = 50)
	public String getConsumptionUom() {
		return this.consumptionUom;
	}

	public void setConsumptionUom(String consumptionUom) {
		this.consumptionUom = consumptionUom;
	}

	@Column(name = "erx_approved_quantity", precision = 131089, scale = 0)
	public BigDecimal getErxApprovedQuantity() {
		return this.erxApprovedQuantity;
	}

	public void setErxApprovedQuantity(BigDecimal erxApprovedQuantity) {
		this.erxApprovedQuantity = erxApprovedQuantity;
	}

	@Column(name = "op_medicine_pres_id")
	public Integer getOpMedicinePresId() {
		return this.opMedicinePresId;
	}

	public void setOpMedicinePresId(Integer opMedicinePresId) {
		this.opMedicinePresId = opMedicinePresId;
	}

	@Column(name = "admin_strength", length = 100)
	public String getAdminStrength() {
		return this.adminStrength;
	}

	public void setAdminStrength(String adminStrength) {
		this.adminStrength = adminStrength;
	}

	@Column(name = "send_for_erx", nullable = false, length = 1)
	public char getSendForErx() {
		return this.sendForErx;
	}

	public void setSendForErx(char sendForErx) {
		this.sendForErx = sendForErx;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "refills", length = 100)
	public String getRefills() {
		return this.refills;
	}

	public void setRefills(String refills) {
		this.refills = refills;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientMedicinePrescriptionsIdSequence))
			return false;
		PatientMedicinePrescriptionsIdSequence castOther = (PatientMedicinePrescriptionsIdSequence) other;

		return ((this.getFrequency() == castOther.getFrequency()) || (this.getFrequency() != null
				&& castOther.getFrequency() != null && this.getFrequency().equals(castOther.getFrequency())))
				&& ((this.getMedicineQuantity() == castOther.getMedicineQuantity())
						|| (this.getMedicineQuantity() != null && castOther.getMedicineQuantity() != null
								&& this.getMedicineQuantity().equals(castOther.getMedicineQuantity())))
				&& ((this.getMedicineRemarks() == castOther.getMedicineRemarks())
						|| (this.getMedicineRemarks() != null && castOther.getMedicineRemarks() != null
								&& this.getMedicineRemarks().equals(castOther.getMedicineRemarks())))
				&& ((this.getModTime() == castOther.getModTime()) || (this.getModTime() != null
						&& castOther.getModTime() != null && this.getModTime().equals(castOther.getModTime())))
				&& ((this.getIssuedQty() == castOther.getIssuedQty()) || (this.getIssuedQty() != null
						&& castOther.getIssuedQty() != null && this.getIssuedQty().equals(castOther.getIssuedQty())))
				&& ((this.getInitialSaleId() == castOther.getInitialSaleId())
						|| (this.getInitialSaleId() != null && castOther.getInitialSaleId() != null
								&& this.getInitialSaleId().equals(castOther.getInitialSaleId())))
				&& ((this.getFinalSaleId() == castOther.getFinalSaleId())
						|| (this.getFinalSaleId() != null && castOther.getFinalSaleId() != null
								&& this.getFinalSaleId().equals(castOther.getFinalSaleId())))
				&& ((this.getActivityDueDate() == castOther.getActivityDueDate())
						|| (this.getActivityDueDate() != null && castOther.getActivityDueDate() != null
								&& this.getActivityDueDate().equals(castOther.getActivityDueDate())))
				&& ((this.getMedicineId() == castOther.getMedicineId()) || (this.getMedicineId() != null
						&& castOther.getMedicineId() != null && this.getMedicineId().equals(castOther.getMedicineId())))
				&& ((this.getRouteOfAdmin() == castOther.getRouteOfAdmin())
						|| (this.getRouteOfAdmin() != null && castOther.getRouteOfAdmin() != null
								&& this.getRouteOfAdmin().equals(castOther.getRouteOfAdmin())))
				&& ((this.getStrength() == castOther.getStrength()) || (this.getStrength() != null
						&& castOther.getStrength() != null && this.getStrength().equals(castOther.getStrength())))
				&& ((this.getGenericCode() == castOther.getGenericCode())
						|| (this.getGenericCode() != null && castOther.getGenericCode() != null
								&& this.getGenericCode().equals(castOther.getGenericCode())))
				&& ((this.getItemFormId() == castOther.getItemFormId()) || (this.getItemFormId() != null
						&& castOther.getItemFormId() != null && this.getItemFormId().equals(castOther.getItemFormId())))
				&& ((this.getItemStrength() == castOther.getItemStrength())
						|| (this.getItemStrength() != null && castOther.getItemStrength() != null
								&& this.getItemStrength().equals(castOther.getItemStrength())))
				&& ((this.getVisitId() == castOther.getVisitId()) || (this.getVisitId() != null
						&& castOther.getVisitId() != null && this.getVisitId().equals(castOther.getVisitId())))
				&& ((this.getDuration() == castOther.getDuration()) || (this.getDuration() != null
						&& castOther.getDuration() != null && this.getDuration().equals(castOther.getDuration())))
				&& ((this.getDurationUnits() == castOther.getDurationUnits())
						|| (this.getDurationUnits() != null && castOther.getDurationUnits() != null
								&& this.getDurationUnits().equals(castOther.getDurationUnits())))
				&& ((this.getPbmPrescId() == castOther.getPbmPrescId()) || (this.getPbmPrescId() != null
						&& castOther.getPbmPrescId() != null && this.getPbmPrescId().equals(castOther.getPbmPrescId())))
				&& ((this.getItemStrengthUnits() == castOther.getItemStrengthUnits())
						|| (this.getItemStrengthUnits() != null && castOther.getItemStrengthUnits() != null
								&& this.getItemStrengthUnits().equals(castOther.getItemStrengthUnits())))
				&& (this.getErxStatus() == castOther.getErxStatus())
				&& ((this.getErxDenialCode() == castOther.getErxDenialCode())
						|| (this.getErxDenialCode() != null && castOther.getErxDenialCode() != null
								&& this.getErxDenialCode().equals(castOther.getErxDenialCode())))
				&& ((this.getErxDenialRemarks() == castOther.getErxDenialRemarks())
						|| (this.getErxDenialRemarks() != null && castOther.getErxDenialRemarks() != null
								&& this.getErxDenialRemarks().equals(castOther.getErxDenialRemarks())))
				&& ((this.getConsumptionUom() == castOther.getConsumptionUom())
						|| (this.getConsumptionUom() != null && castOther.getConsumptionUom() != null
								&& this.getConsumptionUom().equals(castOther.getConsumptionUom())))
				&& ((this.getErxApprovedQuantity() == castOther.getErxApprovedQuantity())
						|| (this.getErxApprovedQuantity() != null && castOther.getErxApprovedQuantity() != null
								&& this.getErxApprovedQuantity().equals(castOther.getErxApprovedQuantity())))
				&& ((this.getOpMedicinePresId() == castOther.getOpMedicinePresId())
						|| (this.getOpMedicinePresId() != null && castOther.getOpMedicinePresId() != null
								&& this.getOpMedicinePresId().equals(castOther.getOpMedicinePresId())))
				&& ((this.getAdminStrength() == castOther.getAdminStrength())
						|| (this.getAdminStrength() != null && castOther.getAdminStrength() != null
								&& this.getAdminStrength().equals(castOther.getAdminStrength())))
				&& (this.getSendForErx() == castOther.getSendForErx())
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getRefills() == castOther.getRefills()) || (this.getRefills() != null
						&& castOther.getRefills() != null && this.getRefills().equals(castOther.getRefills())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFrequency() == null ? 0 : this.getFrequency().hashCode());
		result = 37 * result + (getMedicineQuantity() == null ? 0 : this.getMedicineQuantity().hashCode());
		result = 37 * result + (getMedicineRemarks() == null ? 0 : this.getMedicineRemarks().hashCode());
		result = 37 * result + (getModTime() == null ? 0 : this.getModTime().hashCode());
		result = 37 * result + (getIssuedQty() == null ? 0 : this.getIssuedQty().hashCode());
		result = 37 * result + (getInitialSaleId() == null ? 0 : this.getInitialSaleId().hashCode());
		result = 37 * result + (getFinalSaleId() == null ? 0 : this.getFinalSaleId().hashCode());
		result = 37 * result + (getActivityDueDate() == null ? 0 : this.getActivityDueDate().hashCode());
		result = 37 * result + (getMedicineId() == null ? 0 : this.getMedicineId().hashCode());
		result = 37 * result + (getRouteOfAdmin() == null ? 0 : this.getRouteOfAdmin().hashCode());
		result = 37 * result + (getStrength() == null ? 0 : this.getStrength().hashCode());
		result = 37 * result + (getGenericCode() == null ? 0 : this.getGenericCode().hashCode());
		result = 37 * result + (getItemFormId() == null ? 0 : this.getItemFormId().hashCode());
		result = 37 * result + (getItemStrength() == null ? 0 : this.getItemStrength().hashCode());
		result = 37 * result + (getVisitId() == null ? 0 : this.getVisitId().hashCode());
		result = 37 * result + (getDuration() == null ? 0 : this.getDuration().hashCode());
		result = 37 * result + (getDurationUnits() == null ? 0 : this.getDurationUnits().hashCode());
		result = 37 * result + (getPbmPrescId() == null ? 0 : this.getPbmPrescId().hashCode());
		result = 37 * result + (getItemStrengthUnits() == null ? 0 : this.getItemStrengthUnits().hashCode());
		result = 37 * result + this.getErxStatus();
		result = 37 * result + (getErxDenialCode() == null ? 0 : this.getErxDenialCode().hashCode());
		result = 37 * result + (getErxDenialRemarks() == null ? 0 : this.getErxDenialRemarks().hashCode());
		result = 37 * result + (getConsumptionUom() == null ? 0 : this.getConsumptionUom().hashCode());
		result = 37 * result + (getErxApprovedQuantity() == null ? 0 : this.getErxApprovedQuantity().hashCode());
		result = 37 * result + (getOpMedicinePresId() == null ? 0 : this.getOpMedicinePresId().hashCode());
		result = 37 * result + (getAdminStrength() == null ? 0 : this.getAdminStrength().hashCode());
		result = 37 * result + this.getSendForErx();
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getRefills() == null ? 0 : this.getRefills().hashCode());
		return result;
	}

}
