package com.insta.hms.core.clinical.consultation.prescriptions;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientOtherPrescriptionsModel generated by hbm2java
 */
@Entity
@Table(name = "patient_other_prescriptions")
public class PatientOtherPrescriptionsModel implements java.io.Serializable {

	private PatientOtherPrescriptionsIdSequence id;

	public PatientOtherPrescriptionsModel() {
	}

	public PatientOtherPrescriptionsModel(PatientOtherPrescriptionsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemName", column = @Column(name = "item_name", length = 100)),
			@AttributeOverride(name = "itemRemarks", column = @Column(name = "item_remarks", length = 2000)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)),
			@AttributeOverride(name = "activityDueDate", column = @Column(name = "activity_due_date", length = 29)),
			@AttributeOverride(name = "frequency", column = @Column(name = "frequency", length = 50)),
			@AttributeOverride(name = "medicineQuantity", column = @Column(name = "medicine_quantity")),
			@AttributeOverride(name = "strength", column = @Column(name = "strength", length = 100)),
			@AttributeOverride(name = "itemFormId", column = @Column(name = "item_form_id")),
			@AttributeOverride(name = "itemStrength", column = @Column(name = "item_strength", length = 50)),
			@AttributeOverride(name = "nonHospMedicine", column = @Column(name = "non_hosp_medicine", nullable = false)),
			@AttributeOverride(name = "duration", column = @Column(name = "duration")),
			@AttributeOverride(name = "durationUnits", column = @Column(name = "duration_units", length = 1)),
			@AttributeOverride(name = "itemStrengthUnits", column = @Column(name = "item_strength_units")),
			@AttributeOverride(name = "consumptionUom", column = @Column(name = "consumption_uom", length = 50)),
			@AttributeOverride(name = "prescriptionId", column = @Column(name = "prescription_id")),
			@AttributeOverride(name = "adminStrength", column = @Column(name = "admin_strength", length = 100)),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 30)),
			@AttributeOverride(name = "refills", column = @Column(name = "refills", length = 100)) })
	public PatientOtherPrescriptionsIdSequence getId() {
		return this.id;
	}

	public void setId(PatientOtherPrescriptionsIdSequence id) {
		this.id = id;
	}

}
