insert into insurance_denial_codes values('ELIG-001','Patient is not a covered member','Claim is submitted for Member number “123”. However member number “123” is not found in payers database. Hence, the claim for this member would not be eligible for payment.','A','Eligibility');
insert into insurance_denial_codes values('ELIG-002','Services performed after the last date of coverage are not covered','','I','Eligibility');
insert into insurance_denial_codes values('ELIG-003','Services performed prior to the effective date of coverage are not covered','','I','Eligibility');
insert into insurance_denial_codes values('ELIG-004','Services performed by a non-network provider are not covered','','I','Eligibility');
insert into insurance_denial_codes values('ELIG-005','Services performed after the last date of coverage','The submitted claim for member  has a card expiry date of 01/09/2010; all services provided after 1/09/2010 will not be eligible for payment.','A','Eligibility');
insert into insurance_denial_codes values('ELIG-006','Services performed prior to the effective date of coverage','The card coverage for a member commences   on 15/09/2010. All services before 15/09/2010 will be not be eligible for payment.','A','Eligibility');
insert into insurance_denial_codes values('ELIG-007','Services performed by a non-network provider','If a claim is submitted and the provider is not contracted with a specific plan  or payer on the claimed service dates then such claims would not be eligible for payment on direct billing. ','A','Eligibility');
insert into insurance_denial_codes values('AUTH-001','Prior approval is required and was not obtained','Outpatient MRI claim requires pre-approval. However, if no pre-approval was requested or was requested and denied, then such claims would not be eligible for payment.','A','Authorization');
insert into insurance_denial_codes values('AUTH-002','Services performed are inconsistent with authorized or approved services','','I','Authorization');
insert into insurance_denial_codes values('AUTH-003','PriorAuthorizationNumber is invalid','Claim submitted with authorization number which is invalid for the insurance company would not be eligible for payment.','A','Authorization');
insert into insurance_denial_codes values('AUTH-004','Service(s) is (are) performed outside authorization validity date','Tonsillectomy is authorized to be carried out between 01/01/2010 and 01/02/2010. However, the claim is submitted with service date 03/02/2010. Hence, such claims would not be eligible for payment.','A','Authorization');
insert into insurance_denial_codes values('AUTH-005','Claim information is inconsistent with pre-certified/authorized services','Authorization was obtained for appendectomy while the claim is submitted for inguinal hernia repair using the A authorization number given for the appendectomy.','A','Authorization');
insert into insurance_denial_codes values('BENX-001','Service / Medication is above AED threshold','','I','Benefit expiration');
insert into insurance_denial_codes values('BENX-002','Benefit maximum for this time period or occurrence has been reached','Authorization requested for 6 Physiotherapy sessions but all eligible sessions have been exhausted; hence additional sessions will not be eligible for approval. ','A','Benefit expiration');
insert into insurance_denial_codes values('BENX-003','Lifetime benefit maximum has been reached for this service/benefit category','','I','Benefit expiration');
insert into insurance_denial_codes values('BENX-004','Lifetime benefit maximum has been reached','','I','Benefit expiration');
insert into insurance_denial_codes values('BENX-005','Annual limit/sublimit amount exceeded ','Annual limit for a member is 250,000 AED and the cumulative paid amount exceeds this limit. Hence, all further services will not be not be eligible for payment.','A','Benefit expiration');
insert into insurance_denial_codes values('CLAI-007','Claim is a work-related injury/illness and thus the liability of the employer ','Claim submitted with principal diagnosis "amputation of limb" and secondary diagnosis "adverse effects of work environment". In case work related injuries are not covered for the member, all services on the claim will not be eligible for payment . This code will be I after 22 March 2011.','A','Administrative information');
insert into insurance_denial_codes values('CLAI-008','Claim overlaps inpatient stay. Resubmit only those services rendered outside the inpatient stay','Pre-operative work up is done prior to Inpatient stay. Both the pre-operative work up and Inpatient stay are billed as one Inpatient encounter. The Pre-operative work up should be billed separately as an outpatient encounter to be eligible for payment. ','A','Administrative information');
insert into insurance_denial_codes values('CLAI-009','Date of birth follows the date of service','Members date of birth is  02/01/2007. Claims submitted with services prior to this date will not be eligible for payment','A','Administrative information');
insert into insurance_denial_codes values('CLAI-010','Date of death precedes the date of service','Claims submitted for an ECG with service date 02/01/2010, while date of death was on 01/01/2010 hence not eligible for payment.','A','Administrative information');
insert into insurance_denial_codes values('CLAI-011','Inpatient admission spans multiple rate periods.  Resubmit separate claims','Member was admitted twice to the hospital; First authorized admission spans 01/01/2010 to 06/01/2010 and the second authorized admission from 08/01/201 through 16/01/2010. However the claim is submitted as a single Inpatient encounter for the period of 01/01/2010 and 16/01/2010. Thus the claim will not be eligible for payment unless submitted as two different encounters.','A','Administrative information');
insert into insurance_denial_codes values('CLAI-012','Submission not compliant with contractual agreement between provider & payer','Example to be provided by Daman','A','Administrative information');
insert into insurance_denial_codes values('CLAI-013','Missing an Observation (Dental Tooth #)','','I','Administrative information');
insert into insurance_denial_codes values('CLAI-014','Claim not compliant with Resubmission type (used only for resubmissions)','Claim resubmitted as an  "Internal Complaint" with different diagnosis from that of the original/first claim. Such claims will not be eligible for payment.','A','Administrative information');
insert into insurance_denial_codes values('CODE-001','Missing, incomplete or invalid principal diagnosis','','I','Clinical information');
insert into insurance_denial_codes values('CODE-002','Missing, incomplete or invalid service code','','I','Clinical information');
insert into insurance_denial_codes values('CODE-003','Missing or invalid Clinician','','I','Clinical information');
insert into insurance_denial_codes values('CODE-004','Diagnosis is inconsistent with the patients age','','I','Clinical information');
insert into insurance_denial_codes values('CODE-005','Diagnosis is inconsistent with the patients gender','','I','Clinical information');
insert into insurance_denial_codes values('CODE-006','Diagnosis is inconsistent with the procedure','','I','Clinical information');
insert into insurance_denial_codes values('CODE-007','Diagnosis is inconsistent with the provider type','','I','Clinical information');
insert into insurance_denial_codes values('CODE-008','Service code is inconsistent with the patients age','','I','Clinical information');
insert into insurance_denial_codes values('CODE-009','Service code is inconsistent with the patients gender','','I','Clinical information');
insert into insurance_denial_codes values('CODE-010','Activity/diagnosis inconsistent with clinician specialty','Submitted claim is for a cataract surgery. However the clinician ID submitted belongs to a psychiatrist. Thus the claim would not be eligible for payment.','A','Clinical information');
insert into insurance_denial_codes values('CODE-011','Incorrect DRG calculated','Example to be provided by Daman','A','Clinical information');
insert into insurance_denial_codes values('CODE-012','Encounter type inconsistent with service(s) / diagnosis','Example to be provided by Daman','A','Clinical information');
insert into insurance_denial_codes values('CODE-013','Invalid principal diagnosis (for example E-codes)','Claim  reported with a principal diagnosis "unspecified accident" ( E-code ). Hence the claim will not be eligible for payment. ','A','Clinical information');
insert into insurance_denial_codes values('CODE-014','Activity/diagnosis is inconsistent with the patients age/gender','Antenatal screening tests are billed for a male  member. Diagnosis senile cataract was reported  for a Aborn. Both claims would not be eligible for payment.','A','Clinical information');
insert into insurance_denial_codes values('CODE-015','Activity/diagnosis is inconsistent with the provider type','Claims submitted by an ophthalmology clinic for dental services would not be eligible for payment.','A','Clinical information');
insert into insurance_denial_codes values('DUPL-001','Claim is a duplicate based on service codes and dates','Example to be provided by Daman','A','Duplicate');
insert into insurance_denial_codes values('DUPL-002','Payment already made for A/similar service within set time frame','Example to be provided by Daman','A','Duplicate');
insert into insurance_denial_codes values('MNEC-001','Tests or treatments were not ordered by a Medical doctor','','I','Medical Necessity');
insert into insurance_denial_codes values('MNEC-002','Services performed were not medically necessary','','I','Medical Necessity');
insert into insurance_denial_codes values('MNEC-003','Service is not clinically indicated based on good clinical practice','Example to be provided by Daman','A','Medical Necessity');
insert into insurance_denial_codes values('MNEC-004','Service is not clinically indicated based on good clinical practice, without additional supporting diagnoses/activities','Example to be provided by Daman','A','Medical Necessity');
insert into insurance_denial_codes values('MNEC-005','Service/supply may be appropriate, but too frequent','Claim submitted for 200 boxes of antibiotic for a singular diagnosis of acute tonsillitis would not be eligible for payment.','A','Medical Necessity');
insert into insurance_denial_codes values('MNEC-006','Alternative service should have been utilized','A color ultrasound was performed, however, Payer’s guidelines for patient’s condition suggest that a regular ultrasound would have produced the needed results. In this case, the cost of a regular ultrasound will be reimbursed to the Provider.','A','Medical Necessity');
insert into insurance_denial_codes values('NCOV-001','Diagnosis(es) is (are) not covered','Member plan does not have coverage for fertility treatment and the claim submitted is with a principal diagnosis “assisted fertilization” hence all claimed services will not be eligible for payment.','A','Non-coverage');
insert into insurance_denial_codes values('NCOV-002','Pre-existing conditions are not covered','Example to be provided by Daman','A','Non-coverage');
insert into insurance_denial_codes values('NCOV-003','Service(s) is (are) not covered','Member is eligible for optical benefits excluding LASIK. Hence claims submitted for LASIK would not be eligible for payment. ','A','Non-coverage');
insert into insurance_denial_codes values('NCOV-004','Acupuncture, acupressure, hypnotism, and other forms of alternative treatment are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-005','Air ambulance transportation services are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-006','Allergy services and treatments are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-007','Ambulance transportation for non-emergency situations are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-008','Behavioral and mental health services, treatments and medications are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-009','Dental treatments are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-010','Elective procedure is not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-011','Experimental or investigational services, treatments, devices and medications are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-012','Eye exams and treatments are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-013','Gender manipulation services and associated expenses including voluntary sterilizations or reversal of sterilizations are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-014','Hearing services are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-015','Home Health (Private Nurse) services are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-016','Home Health (Respite) services are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-017','Home Health services are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-018','Immunizations are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-019','Preventative care is not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-020','Services resulting from attempted suicide or self-infliction are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-021','Vaccinations are not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-022','Service(s) is (are) not performed','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-023','Service(s) is (are) performed outside period of hospitalization/admission','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-024','Chronic Condition Service(s) is (are) not covered','','I','Non-coverage');
insert into insurance_denial_codes values('NCOV-025','Service(s) is (are) not performed (used after audit)','Example to be provided by Daman','A','Non-coverage');
insert into insurance_denial_codes values('PRCE-001','Calculation discrepancy ','Claim submitted for a CT Scan with an amount of 1500 AED. However according to the contract the service is chargeable at 1000 AED hence the claim would be processed as per the contract. ','A','Price');
insert into insurance_denial_codes values('PRCE-002','Payment is included in the allowance for another service','Claim submitted for a  normal delivery with/ without episiotomy and delivery of placenta separately. Hence the delivery of placenta would not be eligible for payment','A','Price');
insert into insurance_denial_codes values('PRCE-003','Recovery of Payment','Initial payment made to the incorrect provider Id resulting in a recovery of payments.','A','Price');
insert into insurance_denial_codes values('PRCE-004','Recharge','','I','Price');
insert into insurance_denial_codes values('PRCE-005','Denial reversed because of medical review','','I','Price');
insert into insurance_denial_codes values('PRCE-006','Consultation within free follow up period','Example to be provided by Daman','A','Price');
insert into insurance_denial_codes values('PRCE-007','Service has no contract price','Claims submitted  for a MRI which has  no contracted price hence would not be eligible for payment.','A','Price');
insert into insurance_denial_codes values('PRCE-008','Multiple procedure payment rules incorrectly applied','Example to be provided by Daman','A','Price');
insert into insurance_denial_codes values('PRCE-009','Charges inconsistent with clinician specialty','Claim submitted with service code 10 for specialist consultation billed under a general practitioner clinician ID would be eligible only to the extent of eligible general practitioner charges.','A','Price');
insert into insurance_denial_codes values('PRCE-010','Use bundled code','Claim submitted for CBC and automated differential WBC count .  The claim should be submitted with the correct bundled CPT code  “CBC including automated differential WBC count”.','A','Price');
insert into insurance_denial_codes values('TIME-001','Time limit for submission has expired','Example to be provided by Daman','A','Timely filing');
insert into insurance_denial_codes values('TIME-002','Requested additional information was not received or was not received within time limit','Example to be provided by Daman','A','Timely filing');
insert into insurance_denial_codes values('TIME-003','Appeal procedures not followed or time limits not met','Example to be provided by Daman','A','Timely filing');
insert into insurance_denial_codes values('AUDT-001','Audit','','I','Audit');
insert into insurance_denial_codes values('COPY-001','Deductible/co-pay not collected from member','Claim submitted for radiological services without the collection of 10 AED deductible hence payment will be settled after deducting 10 AED.','A','Copay');

