-- MALAFFI segment template which uses 2.5.1 version messages

-- MSH segment template
UPDATE hl7_segment_template hst SET field_template = '|' FROM interface_config_master icm WHERE segment_field_number = 'MSH_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '^~\&' FROM interface_config_master icm WHERE segment_field_number = 'MSH_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sending_application??>${sending_application}</#if>^<#if sending_application??>${sending_application}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sending_application??>${sending_application}</#if>^<#if sending_application??>${sending_application}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if receving_application??>${receving_application}</#if>^<#if code_system_name??>${code_system_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if receving_facility??>${receving_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if date_time_with_time_zone??>${date_time_with_time_zone}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if message_type??>${message_type?substring(0,3)}^${message_type?substring(4,7)}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if msgCtrlId??>${msgCtrlId}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = 'P' FROM interface_config_master icm WHERE segment_field_number = 'MSH_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if message_version??>${message_version}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- EVN segment template
UPDATE hl7_segment_template hst SET field_template = '<#if message_type??>${message_type?substring(4,7)}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'EVN_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if date_time??>${date_time}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'EVN_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- PID segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_id??>${visit_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if mr_no??>${mr_no}</#if>^^^&<#if sending_facility??>${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if passport_no??>${passport_no}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if last_name??>${last_name?cap_first}</#if>^<#if first_name??>${first_name?cap_first}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if date_of_birth??>${date_of_birth?date?string("yyyyMMdd")}<#elseif expected_date_of_birth??>${expected_date_of_birth?date?string("yyyyMMdd")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if gender??>${gender}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi??><#if code.malaffi.state_master??><#if code.malaffi.state_master[patient_state_id?string]??><#assign pid11_4_1 = code.malaffi.state_master[patient_state_id?string]><#elseif code.malaffi.state_master.default??><#assign pid11_4_1 = code.malaffi.state_master.default></#if></#if><#if code.malaffi.country_master??><#if code.malaffi.country_master[patient_country_id?string]??><#assign pid11_6 = code.malaffi.country_master[patient_country_id?string]><#elseif code.malaffi.country_master.default??><#assign pid11_6 = code.malaffi.country_master.default></#if></#if></#if><#if patient_address??>${patient_address}</#if>^^<#if patient_city_name??>${patient_city_name}</#if>^<#if pid11_4_1??>${pid11_4_1}</#if>^^<#if pid11_6??>${pid11_6}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_phone??>${patient_phone?replace("+","00")}</#if>^^CC^<#if alternate_phone??>${alternate_phone?replace("+","00")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi?? && code.malaffi.marital_status_master??><#if marital_status_id?? && code.malaffi.marital_status_master[marital_status_id?string]??><#assign pid16_1 = code.malaffi.marital_status_master[marital_status_id?string]><#elseif code.malaffi.marital_status_master.default??><#assign pid16_1 = code.malaffi.marital_status_master.default></#if></#if><#if code_desc?? && code_desc.malaffi?? && code_desc.malaffi.marital_status_master??><#if marital_status_id?? && code_desc.malaffi.marital_status_master[marital_status_id?string]??><#assign pid16_2 = code_desc.malaffi.marital_status_master[marital_status_id?string]><#elseif code_desc.malaffi.marital_status_master.default??><#assign pid16_2 = code_desc.malaffi.marital_status_master.default></#if></#if><#if pid16_1??>${pid16_1}</#if>^<#if pid16_2??>${pid16_2}</#if>^<#if code_system_name??>${code_system_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi?? && code.malaffi.religion_master??><#if religion_id?? && code.malaffi.religion_master[religion_id?string]??><#assign pid17_1 = code.malaffi.religion_master[religion_id?string]><#elseif code.malaffi.religion_master.default??><#assign pid17_1 = code.malaffi.religion_master.default></#if></#if><#if code_desc?? && code_desc.malaffi?? && code_desc.malaffi.religion_master??><#if religion_id?? && code_desc.malaffi.religion_master[religion_id?string]??><#assign pid17_2 = code_desc.malaffi.religion_master[religion_id?string]><#elseif code_desc.malaffi.religion_master.default??><#assign pid17_2 = code_desc.malaffi.religion_master.default></#if></#if><#if pid17_1??>${pid17_1}</#if>^<#if pid17_2??>${pid17_2}</#if>^<#if code_system_name??>${code_system_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_17' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if government_identifier??>${government_identifier?replace("-","")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi?? && code.malaffi.nationality??><#if nationality_id?? && code.malaffi.nationality[nationality_id?string]??><#assign pid28_1 = code.malaffi.nationality[nationality_id?string]><#elseif code.malaffi.nationality.default??><#assign pid28_1 = code.malaffi.nationality.default></#if></#if><#if code_desc?? && code_desc.malaffi?? && code_desc.malaffi.nationality??><#if nationality_id?? && code_desc.malaffi.nationality[nationality_id?string]??><#assign pid28_2 = code_desc.malaffi.nationality[nationality_id?string]><#elseif code_desc.malaffi.nationality.default??><#assign pid28_2 = code_desc.malaffi.nationality.default></#if></#if><#if pid28_1??>${pid28_1}</#if>^<#if pid28_2??>${pid28_2}</#if>^<#if code_system_name??>${code_system_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_28' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if death_date?? && death_time??>${death_date?date?string("yyyyMMdd")}${death_time?time?string("HHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_29' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if death_date?? && death_date?string != "">Y</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_30' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- PV1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi?? && code.malaffi.department??><#if department_id?? && code.malaffi.department[department_id?string]??><#assign malaffiDeptCode = code.malaffi.department[department_id?string]><#elseif code.malaffi.department.default??><#assign malaffiDeptCode = code.malaffi.department.default></#if></#if><#if visit_type?? && visit_type = "O"><#if encounter_types_visit_name?? && encounter_types_visit_name = "Homecare">HC<#elseif malaffiDeptCode?? && malaffiDeptCode = 13?string>E<#else>${visit_type}</#if><#else>${visit_type}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_type?? && visit_type = "O" && cons_admit_dept??>${cons_admit_dept}<#elseif visit_type?? && visit_type != "O" && bed_name??>${bed_name}</#if>^^<#if visit_type?? && visit_type != "O" && ward_no??>${ward_no}</#if>^<#if center_service_reg_no?? && sending_facility??>${center_service_reg_no}&${sending_facility}-DOHID</#if>^^C' FROM interface_config_master icm WHERE segment_field_number = 'PV1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_type?? && visit_type != "O" && doc_first_name?? && doc_last_name?? && doctor_license_number?? && sending_facility??>${doctor_license_number}^${doc_last_name}^${doc_first_name}^^^^^^&${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_type?? && visit_type = "O" && doc_first_name?? && doc_last_name?? && doctor_license_number?? && sending_facility??>${doctor_license_number}^${doc_last_name}^${doc_first_name}^^^^^^&${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi?? && code.malaffi.department??><#if department_id?? && code.malaffi.department[department_id?string]??>${code.malaffi.department[department_id?string]}<#elseif code.malaffi.department.default??>${code.malaffi.department.default}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '9' FROM interface_config_master icm WHERE segment_field_number = 'PV1_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_id?? && sending_facility??>${visit_id}^^^&${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_type?? && visit_type = "O"><#if code?? && code.malaffi?? && code.malaffi.department??><#if department_id?? && code.malaffi.department[department_id?string]??><#assign malaffiDeptCode = code.malaffi.department[department_id?string]><#elseif code.malaffi.department.default??><#assign malaffiDeptCode = code.malaffi.department.default></#if></#if><#if malaffiDeptCode?? && malaffiDeptCode = 13?string && emergency_patient_disposition_flag?? && emergency_patient_disposition_flag != "">1</#if><#else><#if code?? && code.malaffi?? && code.malaffi.discharge_type_master??><#if discharge_type_id?? && code.malaffi.discharge_type_master[discharge_type_id?string]??>${code.malaffi.discharge_type_master[discharge_type_id?string]}<#elseif code.malaffi.discharge_type_master.default??>${code.malaffi.discharge_type_master.default}</#if></#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_36' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if transfer_hospital_name??>${transfer_hospital_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_37' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if reg_date?? && reg_time??>${reg_date?date?string("yyyyMMdd")}${reg_time?time?string("HHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_44' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_status?? && visit_status = "I" && discharge_date?? && discharge_time??>${discharge_date?date?string("yyyyMMdd")}${discharge_time?time?string("HHmmss")}<#elseif visit_status?? && visit_status = "I" && discharge_date??>${discharge_date?date?string("yyyyMMdd")}${.now?time?string("HHmmss")}<#elseif visit_status?? && visit_status = "I" && discharge_time??>${.now?date?string("yyyyMMdd")}${discharge_time?time?string("HHmmss")}<#elseif visit_status?? && visit_status = "I">${.now?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_45' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- AL1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if allergy_type?? && allergy_type != "N"><#if allergy_type = "M"><#assign al1_2_1 = "DA"><#assign al1_2_2 = "Drug allergy"><#elseif allergy_type = "F"><#assign al1_2_1 = "FA"><#assign al1_2_2 = "Food allergy"><#elseif allergy_type = "O"><#assign al1_2_1 = "MA"><#assign al1_2_2 = "Miscellaneous allergy"></#if></#if><#if al1_2_1??>${al1_2_1}^<#if al1_2_2??>${al1_2_2}</#if>^<#if code_system_name??>${code_system_name}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '^<#if allergy_type?? && allergy_type != "N"><#if allergy?? && allergy !="">${allergy?replace("\n","<br>")}<#else>Not Available</#if><#else>NKA</#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if allergy_type?? && allergy_type != "N"><#if severity?? && severity = "Moderate"><#assign al1_4_1 = "MO"><#elseif severity?? && severity = "Severe"><#assign al1_4_1 = "SV"><#elseif severity?? && severity = "Mild"><#assign al1_4_1 = "MI"><#elseif severity?? && severity = "Unknown"><#assign al1_4_1 = "U"><#else><#assign al1_4_1 = "NA"></#if><#if severity??><#assign al1_4_2 = severity><#else><#assign al1_4_2 = "Not Available"></#if><#if al1_4_1??>${al1_4_1}</#if>^<#if al1_4_2??>${al1_4_2}</#if>^<#if code_system_name??>${code_system_name}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if allergy_type?? && allergy_type != "N" && reaction??>${reaction}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if created_at??>${created_at?date?string("yyyyMMdd")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- IN1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if ins_co_code?? && (ins_co_code?starts_with("A") || ins_co_code?starts_with("E"))>true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if ins_plan_id??>${ins_plan_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if ins_co_code??>${ins_co_code}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if insurance_co_name??>${insurance_co_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if member_id??>${member_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_49' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- PV2 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if chief_complaint?? && chief_complaint != "">^${chief_complaint}<#elseif diagnosis_code?? && diagnosis_description??>${diagnosis_code}^${diagnosis_description}^ICD10</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV2_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- DG1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if diagnosis_code?? && diagnosis_description??>${diagnosis_code}^${diagnosis_description}^ICD10</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if diagnosis_datetime??>${diagnosis_datetime?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi?? && code.malaffi.diagnosis_statuses??><#if diagnosis_status_id?? && code.malaffi.diagnosis_statuses[diagnosis_status_id?string]??>${code.malaffi.diagnosis_statuses[diagnosis_status_id?string]}<#elseif code.malaffi.diagnosis_statuses.default??>${code.malaffi.diagnosis_statuses.default}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if diag_type?? && diag_type = "P">1<#elseif diag_type?? && diag_type = "S">2<#else>0</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = 'N' FROM interface_config_master icm WHERE segment_field_number = 'DG1_18' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- MRG segment template
UPDATE hl7_segment_template hst SET field_template = '<#if duplicate_mr_no?? && sending_facility??>${duplicate_mr_no}^^^&${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MRG_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- PR1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if operation_conducted_status?? && operation_conducted_status="C">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_code?? && item_code_desc?? && item_code != "">${item_code}^${item_code_desc}^CPT</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_remarks??>${conduction_remarks?trim}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if surgery_start_datetime??>${surgery_start_datetime?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if anaesthetist_license_number?? && anaesthetist_license_number != "">${anaesthetist_license_number}^${anaesthetist_last_name}^${anaesthetist_first_name}^^^^^^&${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if surgeon_license_number?? && surgeon_license_number != "">${surgeon_license_number}^${surgeon_last_name}^${surgeon_first_name}^^^^^^&${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if oper_priority?? && oper_priority = "P">1<#else>2</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if diagnosis_code?? && diagnosis_code != "">${diagnosis_code}^${diagnosis_description}^ICD10</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- PRB segment template
UPDATE hl7_segment_template hst SET field_template = '<#if item_operation?? && item_operation = "insert">AD<#elseif item_operation?? && item_operation = "update">UP<#elseif item_operation?? && item_operation = "delete">DE</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PRB_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if recorded_date??>${recorded_date?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PRB_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_problem_code??>${patient_problem_code}^${patient_problem_desc}^ICD10</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PRB_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if ppl_id??>${ppl_id}^^${sending_application}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PRB_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if problem_status?? && last_status_modified_at?? && problem_status = "R">${last_status_modified_at?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PRB_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = 'F^Final^${code_system_name}' FROM interface_config_master icm WHERE segment_field_number = 'PRB_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if status?? && status = "I">DEL^Delete^${sending_application}<#else><#if problem_status?? && problem_status = "A">ACT^Active^${sending_application}<#elseif problem_status?? && problem_status = "R">RES^Resolved^${sending_application}<#elseif problem_status?? && problem_status = "I">INAV^Inactive^${sending_application}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PRB_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if onset??>${onset?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PRB_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- NTE segment template
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "investigation" && test_code?? && test_code = "87635" && method_name?? && method_name != "">true<#elseif item_type?? && item_type = "investigation" && comments?? && comments != "">true<#elseif item_type?? && item_type = "chronic_problems" && problem_note?? && problem_note != "">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "chronic_problems" && item_operation?? && item_operation = "insert">P</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "chronic_problems" && problem_note??>${problem_note}<#elseif item_type?? && item_type = "investigation" && test_code?? && test_code = "87635" && method_name?? && method_name != "">${method_name}<#elseif item_type?? && item_type = "investigation" && comments??>${comments}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "investigation">RE^Remarks^${code_system_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- ROL segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ROL_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = 'AD^Admitting Provider^${code_system_name}' FROM interface_config_master icm WHERE segment_field_number = 'ROL_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if recorded_by_doctor_license_number??>${recorded_by_doctor_license_number}^${recorded_by_doctor_last_name}^${recorded_by_doctor_first_name}^^^^^^&${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ROL_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- ORC segment template
UPDATE hl7_segment_template hst SET field_template = '<#if (item_type?? && item_type = "investigation") || (item_operation?? && item_operation = "insert")>NW<#elseif item_operation?? && item_operation = "update">XO<#elseif item_operation?? && item_operation = "delete">CA</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if doc_presc_id??>${doc_presc_id}^^<#if sending_facility??>${sending_facility}-DOHID</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && (item_type = "medicine_prescription" || item_type = "medicine_dispense")><#if item_operation?? && item_operation = "delete">entered-in-error<#else>active</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '^^^<#if presc_start_date??>${presc_start_date?string("yyyyMMddHHmmss")}</#if>^<#if presc_end_date??>${presc_end_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if prescribed_date??>${prescribed_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_doc_license_number?? && presc_doc_first_name?? && presc_doc_last_name??><#assign docLicenseNumber = presc_doc_license_number><#assign docFirstName = presc_doc_first_name><#assign docLastName = presc_doc_last_name><#assign sFacility = sending_facility+"-DOHID"><#elseif visit_data?? && visit_data[0]?? && visit_data[0].op_type?? && visit_data[0].op_type = "O"><#assign docLicenseNumber = "SYSTEM"><#assign docFirstName = "SYSTEM"><#assign docLastName = "SYSTEM"><#assign sFacility = sending_facility></#if><#if docLicenseNumber??>${docLicenseNumber}^<#if docLastName??>${docLastName}</#if>^<#if docFirstName??>${docFirstName}</#if>^^^^^^&<#if sFacility??>${sFacility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_start_date??>${presc_start_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- OBR segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if test_code??>${test_code}^${test_name}^${code_type}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sample_date??>${sample_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if is_lab && sample_date??>${sample_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if is_lab && sample_type??>${sample_type}</#if>^^^^^^P&Patient&<#if sending_facility??>${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_doc_license_number?? && presc_doc_first_name?? && presc_doc_last_name??><#assign docLicenseNumber = presc_doc_license_number><#assign docFirstName = presc_doc_first_name><#assign docLastName = presc_doc_last_name><#assign sFacility = sending_facility+"-DOHID"><#elseif visit_data?? && visit_data[0]?? && visit_data[0].op_type?? && visit_data[0].op_type = "O"><#assign docLicenseNumber = "SYSTEM"><#assign docFirstName = "SYSTEM"><#assign docLastName = "SYSTEM"><#assign sFacility = sending_facility></#if><#if docLicenseNumber??>${docLicenseNumber}^<#if docLastName??>${docLastName}</#if>^<#if docFirstName??>${docFirstName}</#if>^^^^^^&<#if sFacility??>${sFacility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_date??>${signoff_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_22' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi?? && code.malaffi.diagnostics_departments??><#if diag_dept_id?? && code.malaffi.diagnostics_departments[diag_dept_id?string]??><#assign obr_24 = code.malaffi.diagnostics_departments[diag_dept_id?string]><#elseif code.malaffi.diagnostics_departments.default??><#assign obr_24 = code.malaffi.diagnostics_departments.default></#if></#if><#if obr_24??>${obr_24}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_24' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_reverted?? && signoff_reverted>C<#else>F</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_25' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if tp_modified_by_doctor_id?? && tp_modified_by_doctor_id !="" && tp_modified_by_doc_last_name?? && tp_modified_by_doc_first_name??><#assign obr32_1 = tp_modified_by_doc_license_number><#assign obr32_2 = tp_modified_by_doc_last_name><#assign obr32_3 = tp_modified_by_doc_first_name><#elseif tp_modified_by_employee_id?? && tp_modified_by_employee_id != "" && tp_modified_by_user_last_name?? && tp_modified_by_user_first_name??><#assign obr32_1 = tp_modified_by_employee_id><#assign obr32_2 = tp_modified_by_user_last_name><#assign obr32_3 = tp_modified_by_user_first_name></#if><#if obr32_1??>${obr32_1}^${obr32_2}^${obr32_3}^^^^^^&<#if sending_facility??>${sending_facility}-DOHID</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_32' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- OBX segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = 'ST' FROM interface_config_master icm WHERE segment_field_number = 'OBX_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if result_code?? && result_code != "">${result_code}<#else>${resultlabel_id}</#if>^<#if result_label_name??>${result_label_name}</#if>^<#if sending_facility??>${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V">${result_value}<#else>${patient_report_file?string?replace("\n","<br>")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V"><#if units?? && units != "">${units}^${units}^${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V" && reference_range??><#assign obx7 =reference_range?string?replace("\n","")?replace("\r","")></#if><#if obx7?? && obx7?length &gt; 100>${obx7?substring(0,100)}<#else>${obx7}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V" && severity??><#if severity = "Normal">N<#elseif severity = "Abnormal Low" || severity = "Abnormal High">A<#elseif severity = "Critical Low" || severity = "Critical High">C<#elseif severity = "Improbable Low">LL<#elseif severity = "Improbable High">HH</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_reverted?? && signoff_reverted>C<#else>F</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_start_date??>${conduction_start_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if tp_modified_by_doctor_id?? && tp_modified_by_doctor_id !="" && tp_modified_by_doc_last_name?? && tp_modified_by_doc_first_name??><#assign obx16_1 = tp_modified_by_doc_license_number><#assign obx16_2 = tp_modified_by_doc_last_name><#assign obx16_3 = tp_modified_by_doc_first_name><#elseif tp_modified_by_employee_id?? && tp_modified_by_employee_id != "" && tp_modified_by_user_last_name?? && tp_modified_by_user_first_name??><#assign obx16_1 = tp_modified_by_employee_id><#assign obx16_2 = tp_modified_by_user_last_name><#assign obx16_3 = tp_modified_by_user_first_name></#if><#if obx16_1??>${obx16_1}^${obx16_2}^${obx16_3}^^^^^^&<#if sending_facility??>${sending_facility}-DOHID</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_date??>${signoff_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if center_name?? && center_service_reg_no??>${center_name}^${center_service_reg_no}^${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_23' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- RXO segment template
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.malaffi??><#if code.malaffi.generic_name??><#if code.malaffi.generic_name[generic_name_id?string]??><#assign rxo1_1 = code.malaffi.generic_name[generic_name_id?string]><#elseif code.malaffi.generic_name.default??><#assign rxo1_1 = code.malaffi.generic_name.default></#if></#if><#if code_desc.malaffi.generic_name??><#if code_desc.malaffi.generic_name[generic_name_id?string]??><#assign rxo1_2 = code_desc.malaffi.generic_name[generic_name_id?string]><#elseif code_desc.malaffi.generic_name.default??><#assign rxo1_2 = code_desc.malaffi.generic_name.default></#if></#if></#if><#if rxo1_1??>${rxo1_1}^<#if rxo1_2??>${rxo1_2}<#if item_strength?? && item_strength != "">,${item_strength}</#if><#if consumption_uom?? && consumption_uom != "">,${consumption_uom}</#if></#if>^DOHDRUG</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if strength??>${strength}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if cons_uom_id??>${cons_uom_id}^${consumption_uom}^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_form_id??>${item_form_id}^${item_form_name}^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = 'Medecine Remarks^Medecine Remarks' FROM interface_config_master icm WHERE segment_field_number = 'RXO_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_qty??>${presc_qty}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if granular_units?? && granular_units = "Y"><#assign rxo12 = issue_units><#else><#assign rxo12 = consumption_uom></#if><#if rxo12??>${rxo12}^${rxo12}^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- RXR segment template
UPDATE hl7_segment_template hst SET field_template = '<#if route_name?? && route_name != "">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXR_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if route_id?? && code?? && code.malaffi??><#if code.malaffi.medicine_route??><#if code.malaffi.medicine_route[route_id?string]??><#assign rxr1_1 = code.malaffi.medicine_route[route_id?string]><#elseif code.malaffi.medicine_route.default??><#assign rxr1_1 = code.malaffi.medicine_route.default></#if></#if><#if code_desc.malaffi.medicine_route??><#if code_desc.malaffi.medicine_route[route_id?string]??><#assign rxr1_2 = code_desc.malaffi.medicine_route[route_id?string]><#elseif code_desc.malaffi.medicine_route.default??><#assign rxr1_2 = code_desc.malaffi.medicine_route.default></#if></#if></#if><#if rxr1_1??>${rxr1_1}^${rxr1_2}^${code_system_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXR_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';

-- RXD segment template
UPDATE hl7_segment_template hst SET field_template = '<#if medicine_ha_code??>${medicine_ha_code}</#if>^<#if medicine_name??>${medicine_name}</#if>^DOHDRUG' FROM interface_config_master icm WHERE segment_field_number = 'RXD_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sale_date??>${sale_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if issued_qty??>${issued_qty}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sale_unit?? && sale_unit = "I"><#assign rxd5_1 = uom_id"U"><#assign rxd5_2 = issue_units><#else><#assign rxd5_1 = uom_id"P"><#assign rxd5_2 = package_uom></#if><#if rxd5_1?? && rxd5_2??>$${rxd5_1}^${rxd5_2}^${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_form_id??>${item_form_id}^${item_form_name}^${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
UPDATE hl7_segment_template hst SET field_template = '<#if ph_user_employee_id?? && ph_user_first_name?? && ph_user_last_name??>${ph_user_employee_id}^${ph_user_last_name}^${ph_user_first_name}^^^^^^&${sending_facility}-DOHID</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Malaffi_%';
