-- Drops temp table if it exists already.
DROP TABLE IF EXISTS religion_mapping_malaffi;
DROP TABLE IF EXISTS marital_status_mapping_malaffi;
DROP TABLE IF EXISTS department_malaffi;
DROP TABLE IF EXISTS discharge_type_malaffi;
DROP TABLE IF EXISTS nationality_master_malaffi;
DROP TABLE IF EXISTS state_master_malaffi;
DROP TABLE IF EXISTS country_master_malaffi;
DROP TABLE IF EXISTS diagnosis_statuses_malaffi;

-- Religion Mapping
CREATE TABLE religion_mapping_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into religion_mapping_malaffi values ('MU','Muslim','Islam',null);
insert into religion_mapping_malaffi values ('MU','Muslim','Muslim',null);
insert into religion_mapping_malaffi values ('CHR','Christianity','Christian',null);
insert into religion_mapping_malaffi values ('AOG','Christian: Assembly of God','',null);
insert into religion_mapping_malaffi values ('BAP','Christian: Baptist','',null);
insert into religion_mapping_malaffi values ('BUD','Buddhist','Buddhist',null);
insert into religion_mapping_malaffi values ('CAT','Christian: Roman Catholic','',null);
insert into religion_mapping_malaffi values ('COC','Christian: Church of Christ','',null);
insert into religion_mapping_malaffi values ('COG','Christian: Church of God','',null);
insert into religion_mapping_malaffi values ('GRE','Christian: Greek Orthodox','',null);
insert into religion_mapping_malaffi values ('HIN','Hindu','Hindu',null);
insert into religion_mapping_malaffi values ('JH','Jewish','Jewish',null);
insert into religion_mapping_malaffi values ('JWN','Christian: Jehovah''s Witness','',null);
insert into religion_mapping_malaffi values ('LUT','Christian: Lutheran','',null);
insert into religion_mapping_malaffi values ('MET','Christian: Methodist','',null);
insert into religion_mapping_malaffi values ('MOM','Christian: Latter-day Saints','',null);
insert into religion_mapping_malaffi values ('NAZ','Christian: Church of the Nazarene','',null);
insert into religion_mapping_malaffi values ('OTH','Other','Agnostic',null);
insert into religion_mapping_malaffi values ('OTH','Other','Atheist',null);
insert into religion_mapping_malaffi values ('OTH','Other','Baha''i',null);
insert into religion_mapping_malaffi values ('OTH','Other','Confucian',null);
insert into religion_mapping_malaffi values ('OTH','Other','Chinese Folk Religionist',null);
insert into religion_mapping_malaffi values ('OTH','Other','Ethnic Religionist',null);
insert into religion_mapping_malaffi values ('OTH','Other','Jain',null);
insert into religion_mapping_malaffi values ('OTH','Other','Other',null);
insert into religion_mapping_malaffi values ('OTH','Other','Others',null);
insert into religion_mapping_malaffi values ('OTH','Other','Parsi',null);
insert into religion_mapping_malaffi values ('OTH','Other','Shintoist',null);
insert into religion_mapping_malaffi values ('OTH','Other','Sikh',null);
insert into religion_mapping_malaffi values ('OTH','Other','Spiritist',null);
insert into religion_mapping_malaffi values ('PEN','Christian: Pentecostal','',null);
insert into religion_mapping_malaffi values ('PRE','Christian: Presbyterian','',null);
insert into religion_mapping_malaffi values ('SEV','Christian: Seventh Day Adventist','',null);
insert into religion_mapping_malaffi values ('VAR','Unknown','Unknown',null);
insert into religion_mapping_malaffi values ('EPI','Christian: Episcopalian','',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'), 2, cs.id, religion_id, malaffi_description, malaffi_code, null 
    FROM religion_mapping_malaffi rmt 
    JOIN religion_master rm ON (lower(rm.religion_name) = lower(rmt.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE rm.religion_id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=2 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS religion_mapping_malaffi;

-- Marital Status Mapping
CREATE TABLE marital_status_mapping_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into marital_status_mapping_malaffi values ('A','Separated','Separated',null);
insert into marital_status_mapping_malaffi values ('A','Separated','Legally Separated',null);
insert into marital_status_mapping_malaffi values ('D','Divorced','Divorced',null);
insert into marital_status_mapping_malaffi values ('M','Married','Married',null);
insert into marital_status_mapping_malaffi values ('P','Domestic Partner','Domestic Partner',null);
insert into marital_status_mapping_malaffi values ('P','Domestic Partner','Registered Domestic Partner',null);
insert into marital_status_mapping_malaffi values ('S','Single','Single',null);
insert into marital_status_mapping_malaffi values ('S','Single','Unmarried',null);
insert into marital_status_mapping_malaffi values ('U','Unknown','Unknown',null);
insert into marital_status_mapping_malaffi values ('U','Unknown','Unreported',null);
insert into marital_status_mapping_malaffi values ('W','Widowed','Widowed',null);
insert into marital_status_mapping_malaffi values ('NA','Not Available','Living Together',null);
insert into marital_status_mapping_malaffi values ('NA','Not Available','Annuled',null);
insert into marital_status_mapping_malaffi values ('NA','Not Available','Common Law',null);
insert into marital_status_mapping_malaffi values ('NA','Not Available','Interlocutory',null);
insert into marital_status_mapping_malaffi values ('NA','Not Available','Other',null);
insert into marital_status_mapping_malaffi values ('NA','Not Available','Others',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'),3, cs.id, msm.marital_status_id, msmt.malaffi_description, msmt.malaffi_code, null 
    FROM marital_status_mapping_malaffi msmt 
    JOIN marital_status_master msm ON (lower(msm.marital_status_name) = lower(msmt.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE msm.marital_status_id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=3 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS marital_status_mapping_malaffi;

-- Department mapping
CREATE TABLE department_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into department_malaffi values ('4','Anesthesia','Anaesthesia',null);
insert into department_malaffi values ('4','Anesthesia','Anaesthesiology',null);
insert into department_malaffi values ('4','Anesthesia','Anaesthetics',null);
insert into department_malaffi values ('4','Anesthesia','Anaesthetist',null);
insert into department_malaffi values ('4','Anesthesia','ANESTHESIA',null);
insert into department_malaffi values ('4','Anesthesia','Anesthesiologist',null);
insert into department_malaffi values ('4','Anesthesia','Anesthesiology',null);
insert into department_malaffi values ('5','Audiology','AUDIOLOGIST',null);
insert into department_malaffi values ('5','Audiology','Audiology',null);
insert into department_malaffi values ('5','Audiology','Auditory System',null);
insert into department_malaffi values ('5','Audiology','OCMC AUDIOLOGY',null);
insert into department_malaffi values ('7','Cardiology','Cardiologist',null);
insert into department_malaffi values ('7','Cardiology','Cardiology',null);
insert into department_malaffi values ('7','Cardiology','CARDIOLOGY - Teleconsultation',null);
insert into department_malaffi values ('7','Cardiology','CARDIOLOGY-Tele Consult',null);
insert into department_malaffi values ('7','Cardiology','CARDIOLOGY-Teleconsultation',null);
insert into department_malaffi values ('7','Cardiology','LLHMC CARDIOLOGY',null);
insert into department_malaffi values ('11','Dermatology','Dermatalogy',null);
insert into department_malaffi values ('11','Dermatology','Dermatolgoy',null);
insert into department_malaffi values ('11','Dermatology','Dermatologist',null);
insert into department_malaffi values ('11','Dermatology','Dermatology',null);
insert into department_malaffi values ('11','Dermatology','DERMATOLOGY - Teleconsultation',null);
insert into department_malaffi values ('11','Dermatology','DERMATOLOGY And WOUND CARE',null);
insert into department_malaffi values ('11','Dermatology','Dermatology Specialty',null);
insert into department_malaffi values ('11','Dermatology','DERMATOLOGY-Tele Consult',null);
insert into department_malaffi values ('11','Dermatology','DERMATOLOGY-Teleconsultation',null);
insert into department_malaffi values ('11','Dermatology','Integumentary System',null);
insert into department_malaffi values ('11','Dermatology','LLHMC DERMATOLOGY',null);
insert into department_malaffi values ('11','Dermatology','Skin Care',null);
insert into department_malaffi values ('12','Diagnostic Radiology','DIAGNOSTICS',null);
insert into department_malaffi values ('13','Emergency Medicine','ACCIDENT & EMERGENCY',null);
insert into department_malaffi values ('13','Emergency Medicine','ACCIDENT AND EMERGENCY',null);
insert into department_malaffi values ('13','Emergency Medicine','E&M',null);
insert into department_malaffi values ('13','Emergency Medicine','Emergency',null);
insert into department_malaffi values ('13','Emergency Medicine','Emergency Department',null);
insert into department_malaffi values ('13','Emergency Medicine','Emergency Medicine',null);
insert into department_malaffi values ('13','Emergency Medicine','Emergency Room',null);
insert into department_malaffi values ('13','Emergency Medicine','ER',null);
insert into department_malaffi values ('13','Emergency Medicine','Urgent Care',null);
insert into department_malaffi values ('13','Emergency Medicine','URGENT CARE (Elective)',null);
insert into department_malaffi values ('13','Emergency Medicine','URGENT CARE (Emergency)',null);
insert into department_malaffi values ('15','Endodontics','Endodontist',null);
insert into department_malaffi values ('16','Family Medicine','Family Medicine',null);
insert into department_malaffi values ('16','Family Medicine','FAMILY MEDICINE - Teleconsultation',null);
insert into department_malaffi values ('16','Family Medicine','FAMILY MEDICINE-Tele Consult',null);
insert into department_malaffi values ('16','Family Medicine','LLHMC FAMILY MEDICINE',null);
insert into department_malaffi values ('16','Family Medicine','SPECIALIST FAMILY MEDICNE',null);
insert into department_malaffi values ('16','Family Medicine','SPECIALIST FAMILY MEDICNE - Teleconsultation',null);
insert into department_malaffi values ('19','General Dentist','GENERAL DENTIST',null);
insert into department_malaffi values ('19','General Dentist','General Dentistry',null);
insert into department_malaffi values ('19','General Dentist','GP Dentist',null);
insert into department_malaffi values ('20','General Practitioner','OCMC GENERAL PRACTITIONER',null);
insert into department_malaffi values ('20','General Practitioner','G.P',null);
insert into department_malaffi values ('20','General Practitioner','G.P.CLINICS',null);
insert into department_malaffi values ('20','General Practitioner','General',null);
insert into department_malaffi values ('20','General Practitioner','General / Aesthetic Medicine',null);
insert into department_malaffi values ('20','General Practitioner','GENERAL MEDICINE',null);
insert into department_malaffi values ('20','General Practitioner','General Physician',null);
insert into department_malaffi values ('20','General Practitioner','General Pra',null);
insert into department_malaffi values ('20','General Practitioner','General Practice',null);
insert into department_malaffi values ('20','General Practitioner','General Practitioner',null);
insert into department_malaffi values ('20','General Practitioner','General Practitioner (GP)',null);
insert into department_malaffi values ('20','General Practitioner','GENERAL PRACTITIONER-Teleconsultation',null);
insert into department_malaffi values ('20','General Practitioner','General Service',null);
insert into department_malaffi values ('20','General Practitioner','GP',null);
insert into department_malaffi values ('20','General Practitioner','GP (Pediatrics)',null);
insert into department_malaffi values ('20','General Practitioner','GP Clinic',null);
insert into department_malaffi values ('20','General Practitioner','GP Medicine',null);
insert into department_malaffi values ('20','General Practitioner','GP Practitioner',null);
insert into department_malaffi values ('20','General Practitioner','GP-MEDICAL',null);
insert into department_malaffi values ('20','General Practitioner','Medical Practitioner',null);
insert into department_malaffi values ('20','General Practitioner','OCMC GP Room 1',null);
insert into department_malaffi values ('20','General Practitioner','OCMC GP Room 2',null);
insert into department_malaffi values ('20','General Practitioner','OCMC GP Room 3',null);
insert into department_malaffi values ('20','General Practitioner','OCMC GP Room 4',null);
insert into department_malaffi values ('20','General Practitioner','Physician',null);
insert into department_malaffi values ('21','Genito Urinary Medicine','Male Genital System',null);
insert into department_malaffi values ('23','Intensive care','ICU',null);
insert into department_malaffi values ('23','Intensive care','Intensivist',null);
insert into department_malaffi values ('24','Internal Medicine','PULMONORY',null);
insert into department_malaffi values ('24','Internal Medicine','Internal Med/Gastro',null);
insert into department_malaffi values ('24','Internal Medicine','Internal Medice',null);
insert into department_malaffi values ('24','Internal Medicine','Internal Medicine',null);
insert into department_malaffi values ('24','Internal Medicine','INTERNAL MEDICINE - Teleconsultation',null);
insert into department_malaffi values ('24','Internal Medicine','Internal Medicine And Pulmonary Diseases',null);
insert into department_malaffi values ('24','Internal Medicine','INTERNAL MEDICINE-Tele Consult',null);
insert into department_malaffi values ('24','Internal Medicine','INTERNAL MEDICINE-Teleconsultation',null);
insert into department_malaffi values ('24','Internal Medicine','LLHMC INTERNAL MEDICINE',null);
insert into department_malaffi values ('25','Medical Genetics','Genetic Lab',null);
insert into department_malaffi values ('25','Medical Genetics','Genetics',null);
insert into department_malaffi values ('27','Neurology','Nervous System',null);
insert into department_malaffi values ('27','Neurology','NEUROLOGIST',null);
insert into department_malaffi values ('27','Neurology','Neurology',null);
insert into department_malaffi values ('27','Neurology','NEUROLOGY- Teleconsultation',null);
insert into department_malaffi values ('27','Neurology','NEUROLOGY-Tele Consult',null);
insert into department_malaffi values ('27','Neurology','Specialist Neurologist',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','LLHMC GYNECOLOGY',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Gynaecology',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Gynaecology And Obstretics',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Gynecologist',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Gynecology',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','GYNECOLOGY AND OBSTERICS',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Gynecology And Obstetrics',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Gynecology Clinic',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Gynecolology',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','GYNEOCOLOGY',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','OB-GYNE',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','OB/Gyn',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','OBSTETRICS',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','OBSTETRICS / GYNAECOLOGY',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Obstetrics & gynaecology',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','OBSTETRICS & GYNAECOLOGY-Tele Consult',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','OBSTETRICS & GYNAECOLOGY-Teleconsultation',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Obstetrics & Gynecology',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Obstetrics And Gynecology',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Obstetrics Gynecology',null);
insert into department_malaffi values ('29','Obstetrics & Gynecology','Specialist OB-GYNE',null);
insert into department_malaffi values ('30','Occupational Medicine','Occupational Health',null);
insert into department_malaffi values ('30','Occupational Medicine','OCCUPATIONAL MEDICINE',null);
insert into department_malaffi values ('30','Occupational Medicine','Occupational Therapist',null);
insert into department_malaffi values ('30','Occupational Medicine','Occupational Therapy',null);
insert into department_malaffi values ('31','Ophthalmology','Eye & Ocular Adnexa',null);
insert into department_malaffi values ('31','Ophthalmology','OCMC OPHTHALMOLOGY',null);
insert into department_malaffi values ('31','Ophthalmology','Ophthalmologist',null);
insert into department_malaffi values ('31','Ophthalmology','Ophthalmology',null);
insert into department_malaffi values ('31','Ophthalmology','Ophthalmology NNMC',null);
insert into department_malaffi values ('31','Ophthalmology','Opthalmology',null);
insert into department_malaffi values ('32','Oral and Maxilofacial Surgery','ORAL & FACIO-MAXILLARY SURGERY',null);
insert into department_malaffi values ('32','Oral and Maxilofacial Surgery','Oral And Maxillofacial Surgery',null);
insert into department_malaffi values ('34','Orthodontics','Orthodontic',null);
insert into department_malaffi values ('34','Orthodontics','Orthodontics',null);
insert into department_malaffi values ('34','Orthodontics','Orthodontist',null);
insert into department_malaffi values ('34','Orthodontics','Specialist Dentist - Orthodontic',null);
insert into department_malaffi values ('34','Orthodontics','SPECIALIST ORTHODONTICS',null);
insert into department_malaffi values ('34','Orthodontics','SPECIALIST ORTHODONTIST',null);
insert into department_malaffi values ('35','Otolaryngology','Otolaryngology',null);
insert into department_malaffi values ('36','Pathology','Clinical Pathologist',null);
insert into department_malaffi values ('36','Pathology','Clinical Pathology',null);
insert into department_malaffi values ('36','Pathology','Laboratory',null);
insert into department_malaffi values ('36','Pathology','LLHMC PHLEBOTOMY',null);
insert into department_malaffi values ('36','Pathology','LLHMC02 PHLEBOTOMY',null);
insert into department_malaffi values ('36','Pathology','OCMC LABORATORY',null);
insert into department_malaffi values ('36','Pathology','PATHOLOGIST',null);
insert into department_malaffi values ('36','Pathology','Pathology',null);
insert into department_malaffi values ('37','Pediatric Dentistry','Specialist Dentist Paediatric',null);
insert into department_malaffi values ('38','Pediatrics','LLHMC PEDIATRIC',null);
insert into department_malaffi values ('38','Pediatrics','PAEDIATRIC',null);
insert into department_malaffi values ('38','Pediatrics','Paediatrician',null);
insert into department_malaffi values ('38','Pediatrics','Paediatrics',null);
insert into department_malaffi values ('38','Pediatrics','PAEDIATRICS-Teleconsultation',null);
insert into department_malaffi values ('38','Pediatrics','PEADIATRICS',null);
insert into department_malaffi values ('38','Pediatrics','Pediatric',null);
insert into department_malaffi values ('38','Pediatrics','Pediatric Nephrology',null);
insert into department_malaffi values ('38','Pediatrics','Pediatric Pulmonology',null);
insert into department_malaffi values ('38','Pediatrics','Pediatrician',null);
insert into department_malaffi values ('38','Pediatrics','Pediatrics',null);
insert into department_malaffi values ('38','Pediatrics','PEDIATRICS-Tele Consult',null);
insert into department_malaffi values ('38','Pediatrics','Specialist Pediatric',null);
insert into department_malaffi values ('38','Pediatrics','Specialist Pediatrician',null);
insert into department_malaffi values ('38','Pediatrics','SPECIALIST PEDIATRICS',null);
insert into department_malaffi values ('39','Periodontics','PEDODONTIST',null);
insert into department_malaffi values ('39','Periodontics','PERIODONTIST',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Physical Medicine & Rehabilitation',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Physical Medicine And Rehabilitation',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Physio_recovery',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Physiotheraphy',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Physiotherapist',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','PhysioTherapy',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Physiotherepy',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Physiotherphy',null);
insert into department_malaffi values ('40','Physical Medicine and Rehabilitation','Rehabilitation',null);
insert into department_malaffi values ('41','Plastic Surgery','Plastic',null);
insert into department_malaffi values ('41','Plastic Surgery','Plastic Surgeon',null);
insert into department_malaffi values ('41','Plastic Surgery','Plastic Surgery',null);
insert into department_malaffi values ('42','Prosthodontics','Specialist - Prosthodontic',null);
insert into department_malaffi values ('42','Prosthodontics','Specialist Prosthodontics',null);
insert into department_malaffi values ('43','Psychiatry','Consultant Psychiatrist',null);
insert into department_malaffi values ('43','Psychiatry','PHYSIATRIST',null);
insert into department_malaffi values ('43','Psychiatry','PSYCHIATRIST',null);
insert into department_malaffi values ('43','Psychiatry','Psychiatry',null);
insert into department_malaffi values ('43','Psychiatry','Specialist Psychiatrist',null);
insert into department_malaffi values ('46','Radiology','LLHMC RADIOLOGY',null);
insert into department_malaffi values ('46','Radiology','OCMC RADIOLOGY',null);
insert into department_malaffi values ('46','Radiology','Radiographer',null);
insert into department_malaffi values ('46','Radiology','Radiologist',null);
insert into department_malaffi values ('46','Radiology','Radiology',null);
insert into department_malaffi values ('50','Urology','Urinary System',null);
insert into department_malaffi values ('50','Urology','Urology',null);
insert into department_malaffi values ('50','Urology','UROLOGY - Teleconsultation',null);
insert into department_malaffi values ('50','Urology','UROLOGY-Tele Consult',null);
insert into department_malaffi values ('50','Urology','UROLOGY-Teleconsultation',null);
insert into department_malaffi values ('50','Urology','Urology1',null);
insert into department_malaffi values ('51','General Surgery','LAPROSCOPIC SURGERY',null);
insert into department_malaffi values ('51','General Surgery','Eneral Surgery',null);
insert into department_malaffi values ('51','General Surgery','General Surgeon',null);
insert into department_malaffi values ('51','General Surgery','General surgery',null);
insert into department_malaffi values ('51','General Surgery','GENERAL SURGERY - Teleconsultation',null);
insert into department_malaffi values ('51','General Surgery','General Surgery Specialist And Osteopath',null);
insert into department_malaffi values ('51','General Surgery','GENERAL SURGERY-Tele Consulatation',null);
insert into department_malaffi values ('51','General Surgery','GENERAL SURGERY-Tele Consult',null);
insert into department_malaffi values ('51','General Surgery','Surgery',null);
insert into department_malaffi values ('52','Gastroenterology','Digestive System',null);
insert into department_malaffi values ('52','Gastroenterology','Endoscopy',null);
insert into department_malaffi values ('52','Gastroenterology','Gastroenterologist',null);
insert into department_malaffi values ('52','Gastroenterology','Gastroenterology',null);
insert into department_malaffi values ('52','Gastroenterology','GASTROENTEROLOGY - Teleconsultation',null);
insert into department_malaffi values ('52','Gastroenterology','GASTROENTEROLOGY-Teleconsultation',null);
insert into department_malaffi values ('52','Gastroenterology','Gastrology',null);
insert into department_malaffi values ('52','Gastroenterology','OPD-GASTROENTEROLOGY',null);
insert into department_malaffi values ('55','Cardiovascular Disease','Cardiovascular System',null);
insert into department_malaffi values ('55','Cardiovascular Disease','CHEST MEDICINE',null);
insert into department_malaffi values ('56','Dermatology & Genito Urinary Medicine','DERMATOLOGY AND VENOROLOGY',null);
insert into department_malaffi values ('57','Endocrinology','Endocrine System',null);
insert into department_malaffi values ('57','Endocrinology','Endocrinology',null);
insert into department_malaffi values ('58','Endocrinology','Diabetes And Endocrinology',null);
insert into department_malaffi values ('58','Endocrinology','DIABETOLOGY',null);
insert into department_malaffi values ('64','Infectious Diseases','Infectious Diseases',null);
insert into department_malaffi values ('67','Medical Oncology','Oncology',null);
insert into department_malaffi values ('68','Neonatology','Neonatology',null);
insert into department_malaffi values ('69','Nephrology','Nephrology',null);
insert into department_malaffi values ('69','Nephrology','Nephrology And Urology',null);
insert into department_malaffi values ('69','Nephrology','Specialist Nephrologist',null);
insert into department_malaffi values ('70','Neurological Surgery','NEURO SURGERY',null);
insert into department_malaffi values ('70','Neurological Surgery','NEURO SURGERY-Tele Consult',null);
insert into department_malaffi values ('70','Neurological Surgery','Neurological Surgery',null);
insert into department_malaffi values ('70','Neurological Surgery','Neurosurgery',null);
insert into department_malaffi values ('71','Obstetrics & Gynecology / Maternal & Fetal Medicine','Maternity',null);
insert into department_malaffi values ('71','Obstetrics & Gynecology / Maternal & Fetal Medicine','Maternity Care & Delivery',null);
insert into department_malaffi values ('72','Obstetrics & Gynecology /Reproductive Endicronology/ Infertility','Gynecology And IVF',null);
insert into department_malaffi values ('72','Obstetrics & Gynecology /Reproductive Endicronology/ Infertility','IVF',null);
insert into department_malaffi values ('72','Obstetrics & Gynecology /Reproductive Endicronology/ Infertility','Ob-Gyn IVF',null);
insert into department_malaffi values ('74','Orthopedic Surgery','LLHMC ORTHOPEDICS',null);
insert into department_malaffi values ('74','Orthopedic Surgery','ORTHO',null);
insert into department_malaffi values ('74','Orthopedic Surgery','Orthopaedic',null);
insert into department_malaffi values ('74','Orthopedic Surgery','Orthopaedics',null);
insert into department_malaffi values ('74','Orthopedic Surgery','ORTHOPAEDICS - Teleconsultation',null);
insert into department_malaffi values ('74','Orthopedic Surgery','ORTHOPAEDICS-Teleconsultation',null);
insert into department_malaffi values ('74','Orthopedic Surgery','ORTHOPEADICSS',null);
insert into department_malaffi values ('74','Orthopedic Surgery','Orthopedic',null);
insert into department_malaffi values ('74','Orthopedic Surgery','Orthopedic Surgeon',null);
insert into department_malaffi values ('74','Orthopedic Surgery','Orthopedic Surgery',null);
insert into department_malaffi values ('74','Orthopedic Surgery','Orthopedics',null);
insert into department_malaffi values ('74','Orthopedic Surgery','ORTHOPEDICS-Tele Consult',null);
insert into department_malaffi values ('74','Orthopedic Surgery','Orthopediste',null);
insert into department_malaffi values ('75','Orthopedic Surgery/ Traumatology','Musculoskeletal System',null);
insert into department_malaffi values ('77','Pediatric Cardiology','Pediatric Cardiology',null);
insert into department_malaffi values ('83','Pediatric Neurology','Pediatric Neurology',null);
insert into department_malaffi values ('84','Pediatric Surgery','PAEDIATRIC SURGERY',null);
insert into department_malaffi values ('84','Pediatric Surgery','PEDIATRIC SURGERY',null);
insert into department_malaffi values ('85','Pain Medicine','Pain Medicine',null);
insert into department_malaffi values ('86','Pediatrics/ Pulmonology','Pulmonology',null);
insert into department_malaffi values ('86','Pediatrics/ Pulmonology','PULMONOLOGY - Teleconsultation',null);
insert into department_malaffi values ('86','Pediatrics/ Pulmonology','PULMONOLOGY-Teleconsultation',null);
insert into department_malaffi values ('86','Pediatrics/ Pulmonology','Pulmonory',null);
insert into department_malaffi values ('86','Pediatrics/ Pulmonology','PULMONORY MEDICINE',null);
insert into department_malaffi values ('87','Reproductive Medicine and Infertility','Reproductive Endocrinology And Infertility',null);
insert into department_malaffi values ('87','Reproductive Medicine and Infertility','Reproductive System & Intersex',null);
insert into department_malaffi values ('88','Respiratory Medicine','RHEUMATOLOGY',null);
insert into department_malaffi values ('88','Respiratory Medicine','Respiratory System',null);
insert into department_malaffi values ('88','Respiratory Medicine','Respiratory Therapist',null);
insert into department_malaffi values ('88','Respiratory Medicine','Respiratory Therapy',null);
insert into department_malaffi values ('88','Respiratory Medicine','Respiratory/Hospital Director',null);
insert into department_malaffi values ('89','Rheumatology','Rheumatology',null);
insert into department_malaffi values ('89','Rheumatology','RHEUMATOLOGY / INTERNAL MEDICINE',null);
insert into department_malaffi values ('91','Dental','Dental',null);
insert into department_malaffi values ('91','Dental','Dental Clinic',null);
insert into department_malaffi values ('91','Dental','Dentist',null);
insert into department_malaffi values ('91','Dental','Dentistry',null);
insert into department_malaffi values ('91','Dental','LLHMC DENTAL',null);
insert into department_malaffi values ('92','Diet','Diet & Nutrition',null);
insert into department_malaffi values ('92','Diet','DIETARY',null);
insert into department_malaffi values ('92','Diet','Dietetics',null);
insert into department_malaffi values ('92','Diet','DieteticsOLD',null);
insert into department_malaffi values ('92','Diet','Dietician',null);
insert into department_malaffi values ('92','Diet','Dietitian',null);
insert into department_malaffi values ('92','Diet','Dietration Clinic',null);
insert into department_malaffi values ('92','Diet','Nutrition',null);
insert into department_malaffi values ('92','Diet','Nutrition And Dietetics',null);
insert into department_malaffi values ('94','Speech Therapy','Hearing & Speech',null);
insert into department_malaffi values ('94','Speech Therapy','Speech Therapist',null);
insert into department_malaffi values ('94','Speech Therapy','Speech Therapy',null);
insert into department_malaffi values ('94','Speech Therapy','Speech Therapy Pathologist',null);
insert into department_malaffi values ('95','Podiatry','Podiatry',null);
insert into department_malaffi values ('96','Pharmacy','Pharmacist',null);
insert into department_malaffi values ('96','Pharmacy','Pharmacy',null);
insert into department_malaffi values ('103','Home Care','Home Care',null);
insert into department_malaffi values ('103','Home Care','HOMECARE',null);
insert into department_malaffi values ('103','Home Care','MidWifery & Homecare',null);
insert into department_malaffi values ('106','Nursing','Nurse',null);
insert into department_malaffi values ('106','Nursing','Nurse Assistant',null);
insert into department_malaffi values ('106','Nursing','Nursing',null);
insert into department_malaffi values ('106','Nursing','Nursing Desk',null);
insert into department_malaffi values ('109','Customer Services','CUSTOMER CARE',null);
insert into department_malaffi values ('109','Customer Services','Customer Services',null);
insert into department_malaffi values ('131','Bariatric Medicine','Bariatric',null);
insert into department_malaffi values ('133','Psychology','CDA PSYCHOLOGIST',null);
insert into department_malaffi values ('133','Psychology','Psychologist',null);
insert into department_malaffi values ('133','Psychology','Psychology',null);
insert into department_malaffi values ('133','Psychology','Psychomotor Therapy',null);
insert into department_malaffi values ('134','Speech and Language Therapy','Speech And Language',null);
insert into department_malaffi values ('135','Geriatric Medicine','GENERAL MEDICINE',null);
insert into department_malaffi values ('136','Cardiothoracic surgery','Cardiothoracic Surgery',null);
insert into department_malaffi values ('136','Cardiothoracic surgery','CARDIOTHORASIC SURGERY',null);
insert into department_malaffi values ('136','Cardiothoracic surgery','Thoracic',null);
insert into department_malaffi values ('137','Behavioral Health','Behavioural Therapy',null);
insert into department_malaffi values ('138','Home Health Services','Home Vist',null);
insert into department_malaffi values ('140','Optometry','Optometry',null);
insert into department_malaffi values ('144','Chiropractic Medicine','Chiropractic',null);
insert into department_malaffi values ('153','Otology/Neuro Otology','Otolarngology',null);
insert into department_malaffi values ('156','Professional Counseling','Counsellor',null);
insert into department_malaffi values ('158','Referral Physician','Referral',null);
insert into department_malaffi values ('160','Sports Medicine','Sports Medicine',null);
insert into department_malaffi values ('160','Sports Medicine','Sports Therapy And Rehabilitaton',null);
insert into department_malaffi values ('162','ENT','LLHMC ENT',null);
insert into department_malaffi values ('162','ENT','ENT',null);
insert into department_malaffi values ('162','ENT','ENT - Teleconsultation',null);
insert into department_malaffi values ('162','ENT','ENT-Tele Consult',null);
insert into department_malaffi values ('162','ENT','ENT-Teleconsultation',null);
insert into department_malaffi values ('162','ENT','ENTT',null);
insert into department_malaffi values ('163','Vascular Surgery','VASCULAR SURGERY',null);
insert into department_malaffi values ('164','Beauty Clinic','Aesthetic',null);
insert into department_malaffi values ('164','Beauty Clinic','Aesthetics',null);
insert into department_malaffi values ('164','Beauty Clinic','Aesthetics & Plastic Surgery',null);
insert into department_malaffi values ('164','Beauty Clinic','Beauticion',null);
insert into department_malaffi values ('164','Beauty Clinic','Beauty',null);
insert into department_malaffi values ('164','Beauty Clinic','Beauty And Laser',null);
insert into department_malaffi values ('164','Beauty Clinic','Beauty Shop',null);
insert into department_malaffi values ('164','Beauty Clinic','Bioaesthetics',null);
insert into department_malaffi values ('164','Beauty Clinic','COSMATOLOGY',null);
insert into department_malaffi values ('164','Beauty Clinic','Cosmesurge',null);
insert into department_malaffi values ('164','Beauty Clinic','COSMETIC',null);
insert into department_malaffi values ('164','Beauty Clinic','COSMETICS',null);
insert into department_malaffi values ('164','Beauty Clinic','COSMETICSsss',null);
insert into department_malaffi values ('164','Beauty Clinic','Cosmetology',null);
insert into department_malaffi values ('164','Beauty Clinic','Cosmotology',null);
insert into department_malaffi values ('164','Beauty Clinic','Facial & Laser',null);
insert into department_malaffi values ('164','Beauty Clinic','Facial & Laser Department',null);
insert into department_malaffi values ('164','Beauty Clinic','Hydra Faical',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser & Hydra Faical',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser 1',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser 2',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser Department',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser Dept',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser Hair Removal',null);
insert into department_malaffi values ('164','Beauty Clinic','Laser Technician',null);
insert into department_malaffi values ('165','Medical/Surgical','Other Surgery',null);
insert into department_malaffi values ('167','Clinical Psychology','Clinical Psychologist',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'), 4, cs.id, d.id, malaffi_description, malaffi_code, null 
    FROM department_malaffi dt 
    JOIN department d ON (lower(d.dept_name) = lower(dt.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE d.id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=4 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS department_malaffi;

-- Discharge type mapping
CREATE TABLE discharge_type_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into discharge_type_malaffi values ('1','Discharged with approval','Normal',null);
insert into discharge_type_malaffi values ('2','Discharged against Medical advice','DAMA',null);
insert into discharge_type_malaffi values ('3','Discharged absent without leave','Absconded',null);
insert into discharge_type_malaffi values ('4','Discharge transfer to acute care','',null);
insert into discharge_type_malaffi values ('5','Deceased','Death',null);
insert into discharge_type_malaffi values ('6','Not discharged','',null);
insert into discharge_type_malaffi values ('7','Discharge transfer to non-acute care','',null);
insert into discharge_type_malaffi values ('8','Discharged to home or self-care (routine discharge)','',null);
insert into discharge_type_malaffi values ('9','Discharged/transferred to another short-term general hospital for inpatient care','Referred To',null);
insert into discharge_type_malaffi values ('10','Discharged/transferred to skilled nursing facility (SNF)','',null);
insert into discharge_type_malaffi values ('11','Discharged/transferred to an intermediate care facility (ICF)','',null);
insert into discharge_type_malaffi values ('12','Discharged/transferred to another type of institution for inpatient care or referred for outpatient services to another institution','',null);
insert into discharge_type_malaffi values ('13','Discharged/transferred to home under care of organized home health service organization','',null);
insert into discharge_type_malaffi values ('14','Left against medical advice or discontinued care','',null);
insert into discharge_type_malaffi values ('15','Discharged/transferred to home under care of Home IV provider','',null);
insert into discharge_type_malaffi values ('16','Admitted as an inpatient to this hospital','',null);
insert into discharge_type_malaffi values ('17','Discharge to be defined at state level, if necessary','',null);
insert into discharge_type_malaffi values ('18','Expired','',null);
insert into discharge_type_malaffi values ('19','Expired to be defined at state level, if necessary','',null);
insert into discharge_type_malaffi values ('20','Still patient or expected to return for outpatient services','',null);
insert into discharge_type_malaffi values ('21','Still patient to be defined at state level, if necessary','',null);
insert into discharge_type_malaffi values ('22','Expired at home','',null);
insert into discharge_type_malaffi values ('23','Expired in a medical facility; e.g., hospital, SNF, ICF, or free-standing hospice','',null);
insert into discharge_type_malaffi values ('24','Expired - place unknown','',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'), 5, cs.id, discharge_type_id, malaffi_description, malaffi_code, null 
    FROM discharge_type_malaffi dtt 
    JOIN discharge_type_master dtm ON (lower(dtm.discharge_type) = lower(dtt.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE dtm.discharge_type_id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=5 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS discharge_type_malaffi;

-- Nationality Mapping
CREATE TABLE nationality_master_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into nationality_master_malaffi values ('AFG','Afghan','Afghanistan',null);
insert into nationality_master_malaffi values ('AGO','Angolan','Angola',null);
insert into nationality_master_malaffi values ('ALB','Albanian','Albania',null);
insert into nationality_master_malaffi values ('AND','Andorran','Andorra',null);
insert into nationality_master_malaffi values ('ARE','Emirati','United Arab Emirates',null);
insert into nationality_master_malaffi values ('ARG','Argentine','Argentina',null);
insert into nationality_master_malaffi values ('ARM','Armenian','Armenia',null);
insert into nationality_master_malaffi values ('ASM','Samoan','American Samoa',null);
insert into nationality_master_malaffi values ('ATG','Antiguan','Antigua and Barbuda',null);
insert into nationality_master_malaffi values ('AUS','Australian','Australia',null);
insert into nationality_master_malaffi values ('AUT','Austrian','Austria',null);
insert into nationality_master_malaffi values ('AZE','Azerbaijani','Azerbaijan',null);
insert into nationality_master_malaffi values ('BDI','Burundian','Burundi',null);
insert into nationality_master_malaffi values ('BEL','Belgian','Belgium',null);
insert into nationality_master_malaffi values ('BEN','Beninese','Benin',null);
insert into nationality_master_malaffi values ('BFA','Burkinabe','Burkina Faso',null);
insert into nationality_master_malaffi values ('BGD','Bangladeshi','Bangladesh',null);
insert into nationality_master_malaffi values ('BGR','Bulgarian','Bulgaria',null);
insert into nationality_master_malaffi values ('BHR','Bahraini','Bahrain',null);
insert into nationality_master_malaffi values ('BHS','Bahamian','Bahamas',null);
insert into nationality_master_malaffi values ('BID','Bidoun','',null);
insert into nationality_master_malaffi values ('BIH','Bosnian','Bosnia and Herzegovina',null);
insert into nationality_master_malaffi values ('BLR','Belarusian','Belarus',null);
insert into nationality_master_malaffi values ('BLZ','Belizean','Belize',null);
insert into nationality_master_malaffi values ('BOL','Bolivian','Bolivia',null);
insert into nationality_master_malaffi values ('BRA','Brazilian','Brazil',null);
insert into nationality_master_malaffi values ('BRB','Barbadian','Barbados',null);
insert into nationality_master_malaffi values ('BRN','Bruneian','Brunei Darussalam',null);
insert into nationality_master_malaffi values ('BTN','Bhutanese','Bhutan',null);
insert into nationality_master_malaffi values ('BWA','Motswana','Botswana',null);
insert into nationality_master_malaffi values ('CAF','Central African','Central African Republic',null);
insert into nationality_master_malaffi values ('CAN','Canadian','Canada',null);
insert into nationality_master_malaffi values ('CHE','Swiss','Switzerland',null);
insert into nationality_master_malaffi values ('CHL','Chilean','Chile',null);
insert into nationality_master_malaffi values ('CHN','Chinese','China',null);
insert into nationality_master_malaffi values ('CIV','Ivorian','Cote d Ivoire',null);
insert into nationality_master_malaffi values ('CMR','Cameroonian','Cameroon',null);
insert into nationality_master_malaffi values ('COG','Congolese','Congo (Democratic Republic of the)',null);
insert into nationality_master_malaffi values ('COG','Congolese','Congo',null);
insert into nationality_master_malaffi values ('COK','Cook Islander','Cook Islands',null);
insert into nationality_master_malaffi values ('COL','Colombian','Colombia',null);
insert into nationality_master_malaffi values ('COM','Comoran','Comoros',null);
insert into nationality_master_malaffi values ('CPV','Cape Verdean','Cabo Verde',null);
insert into nationality_master_malaffi values ('CRI','Costa Rican','Costa Rica',null);
insert into nationality_master_malaffi values ('CUB','Cuban','Cuba',null);
insert into nationality_master_malaffi values ('CYP','Cypriot','Cyprus',null);
insert into nationality_master_malaffi values ('CZE','Czech','Czechia',null);
insert into nationality_master_malaffi values ('DEU','German','Germany',null);
insert into nationality_master_malaffi values ('DJI','Djiboutian','Djibouti',null);
insert into nationality_master_malaffi values ('DMA','Dominica','Dominica',null);
insert into nationality_master_malaffi values ('DNK','Danish','Denmark',null);
insert into nationality_master_malaffi values ('DOM','Dominican Republic','Dominican Republic',null);
insert into nationality_master_malaffi values ('DZA','Algerian','Algeria',null);
insert into nationality_master_malaffi values ('ECU','Ecuadorian','Ecuador',null);
insert into nationality_master_malaffi values ('EGY','Egyptian','Egypt',null);
insert into nationality_master_malaffi values ('ERI','Eritrean','Eritrea',null);
insert into nationality_master_malaffi values ('ESH','Sahrawi','Western Sahara',null);
insert into nationality_master_malaffi values ('ESP','Spanish','Spain',null);
insert into nationality_master_malaffi values ('EST','Estonian','Estonia',null);
insert into nationality_master_malaffi values ('ETH','Ethiopian','Ethiopia',null);
insert into nationality_master_malaffi values ('FIN','Finnish','Finland',null);
insert into nationality_master_malaffi values ('FJI','Fijian','Fiji',null);
insert into nationality_master_malaffi values ('FRA','French','Falkland Islands (Malvinas)',null);
insert into nationality_master_malaffi values ('FSM','Micronesian','Micronesia',null);
insert into nationality_master_malaffi values ('GAB','Gabonese','Gabon',null);
insert into nationality_master_malaffi values ('GBR','British','United Kingdom',null);
insert into nationality_master_malaffi values ('GEO','Georgian','Georgia',null);
insert into nationality_master_malaffi values ('GHA','Ghanaian','Ghana',null);
insert into nationality_master_malaffi values ('GIN','Guinean','Guinea',null);
insert into nationality_master_malaffi values ('GMB','Gambian','Gambia',null);
insert into nationality_master_malaffi values ('GNB','Guinea-Bissau','Guinea-Bissau',null);
insert into nationality_master_malaffi values ('GNQ','Equatoguinean','Equatorial Guinea',null);
insert into nationality_master_malaffi values ('GRC','Greek','Greece',null);
insert into nationality_master_malaffi values ('GRD','Grenadian','Grenada',null);
insert into nationality_master_malaffi values ('GTM','Guatemalan','Guatemala',null);
insert into nationality_master_malaffi values ('GUY','Guyanese','Guyana',null);
insert into nationality_master_malaffi values ('HND','Honduran','Honduras',null);
insert into nationality_master_malaffi values ('HRV','Croatian','Croatia',null);
insert into nationality_master_malaffi values ('HTI','Haitian','Haiti',null);
insert into nationality_master_malaffi values ('HUN','Hungarian','Hungary',null);
insert into nationality_master_malaffi values ('IDN','Indonesian','Indonesia',null);
insert into nationality_master_malaffi values ('IND','Indian','India',null);
insert into nationality_master_malaffi values ('IRL','Irish','Ireland',null);
insert into nationality_master_malaffi values ('IRN','Iranian','Iran',null);
insert into nationality_master_malaffi values ('IRQ','Iraqi','Iraq',null);
insert into nationality_master_malaffi values ('ISL','Icelander','Iceland',null);
insert into nationality_master_malaffi values ('ISR','Israeli','Israel',null);
insert into nationality_master_malaffi values ('ITA','Italian','Italy',null);
insert into nationality_master_malaffi values ('JAM','Jamaican','Jamaica',null);
insert into nationality_master_malaffi values ('JOR','Jordanian','Jordan',null);
insert into nationality_master_malaffi values ('JPN','Japanese','Japan',null);
insert into nationality_master_malaffi values ('KAZ','Kazakhstani','Kazakhstan',null);
insert into nationality_master_malaffi values ('KEN','Kenyan','Kenya',null);
insert into nationality_master_malaffi values ('KGZ','Kyrgyzstani','Kyrgyzstan',null);
insert into nationality_master_malaffi values ('KHM','Cambodian','Cambodia',null);
insert into nationality_master_malaffi values ('KIR','I-Kiribati','Kiribati',null);
insert into nationality_master_malaffi values ('KNA','Kittitian','Saint Kitts and Nevis',null);
insert into nationality_master_malaffi values ('KOR','Korean','South Korea',null);
insert into nationality_master_malaffi values ('KWT','Kuwaiti','Kuwait',null);
insert into nationality_master_malaffi values ('LAO','Laotian','Laos',null);
insert into nationality_master_malaffi values ('LBN','Lebanese','Lebanon',null);
insert into nationality_master_malaffi values ('LBR','Liberian','Liberia',null);
insert into nationality_master_malaffi values ('LBY','Libyan','Libya',null);
insert into nationality_master_malaffi values ('LCA','Saint Lucian','Saint Lucia',null);
insert into nationality_master_malaffi values ('LKA','Sri Lankan','Sri Lanka',null);
insert into nationality_master_malaffi values ('LSO','Basotho','Lesotho',null);
insert into nationality_master_malaffi values ('LTU','Lithuanian','Lithuania',null);
insert into nationality_master_malaffi values ('LUX','Luxembourger','Luxembourg',null);
insert into nationality_master_malaffi values ('LVA','Latvian','Latvia',null);
insert into nationality_master_malaffi values ('MAR','Moroccan','Morocco',null);
insert into nationality_master_malaffi values ('MCO','Monegasque','Monaco',null);
insert into nationality_master_malaffi values ('MDA','Moldovan','Moldova',null);
insert into nationality_master_malaffi values ('MDG','Malagasy','Madagascar',null);
insert into nationality_master_malaffi values ('MDV','Maldivian','Maldives',null);
insert into nationality_master_malaffi values ('MEX','Mexican','Mexico',null);
insert into nationality_master_malaffi values ('MHL','Marshallese','Marshall Islands',null);
insert into nationality_master_malaffi values ('MKD','Macedonian','Macedonia',null);
insert into nationality_master_malaffi values ('MLI','Malian','Mali',null);
insert into nationality_master_malaffi values ('MLT','Maltese','Malta',null);
insert into nationality_master_malaffi values ('MMR','Myanmarese','Myanmar',null);
insert into nationality_master_malaffi values ('MNG','Mongolian','Mongolia',null);
insert into nationality_master_malaffi values ('MON','Montenegrin','',null);
insert into nationality_master_malaffi values ('MOZ','Mozambican','Mozambique',null);
insert into nationality_master_malaffi values ('MRT','Mauritanian','Mauritania',null);
insert into nationality_master_malaffi values ('MUS','Mauritian','Mauritius',null);
insert into nationality_master_malaffi values ('MWI','Malawian','Malawi',null);
insert into nationality_master_malaffi values ('MYS','Malaysian','Malaysia',null);
insert into nationality_master_malaffi values ('NAM','Namibian','Namibia',null);
insert into nationality_master_malaffi values ('NER','Nigerien','Niger',null);
insert into nationality_master_malaffi values ('NGA','Nigerian','Nigeria',null);
insert into nationality_master_malaffi values ('NIC','Nicaraguan','Nicaragua',null);
insert into nationality_master_malaffi values ('NIU','Niuean','Niue',null);
insert into nationality_master_malaffi values ('NLD','Dutch','Netherlands',null);
insert into nationality_master_malaffi values ('NOR','Norwegian','Norway',null);
insert into nationality_master_malaffi values ('NPL','Nepalese','Nepal',null);
insert into nationality_master_malaffi values ('NRU','Nauruan','Nauru',null);
insert into nationality_master_malaffi values ('NZL','New Zealander','New Zealand',null);
insert into nationality_master_malaffi values ('OMN','Omani','Oman',null);
insert into nationality_master_malaffi values ('PAK','Pakistani','Pakistan',null);
insert into nationality_master_malaffi values ('PAN','Panamanian','Panama',null);
insert into nationality_master_malaffi values ('PER','Peruvian','Peru',null);
insert into nationality_master_malaffi values ('PHL','Philippine','Philippines',null);
insert into nationality_master_malaffi values ('PLW','Palauan','Palau',null);
insert into nationality_master_malaffi values ('PNG','Papua New Guinean','Papua New Guinea',null);
insert into nationality_master_malaffi values ('POL','Polish','Poland',null);
insert into nationality_master_malaffi values ('PRT','Portuguese','Portugal',null);
insert into nationality_master_malaffi values ('PRY','Paraguayan','Paraguay',null);
insert into nationality_master_malaffi values ('PSE','Palestinian','Palestine',null);
insert into nationality_master_malaffi values ('QAT','Qatari','Qatar',null);
insert into nationality_master_malaffi values ('ROM','Romanian','',null);
insert into nationality_master_malaffi values ('RUS','Russian','Russian Federation',null);
insert into nationality_master_malaffi values ('RWA','Rwandan','Rwanda',null);
insert into nationality_master_malaffi values ('SAU','Saudi','Saudi Arabia',null);
insert into nationality_master_malaffi values ('SDN','Sudanese','Sudan',null);
insert into nationality_master_malaffi values ('SEN','Senegalese','Senegal',null);
insert into nationality_master_malaffi values ('SGP','Singaporean','Singapore',null);
insert into nationality_master_malaffi values ('SLB','Solomon Islander','Solomon Islands',null);
insert into nationality_master_malaffi values ('SLE','Sierra Leonean','Sierra Leone',null);
insert into nationality_master_malaffi values ('SLV','Salvadoran','El Salvador',null);
insert into nationality_master_malaffi values ('SMR','Sammarinese','San Marino',null);
insert into nationality_master_malaffi values ('SOM','Somali','Somalia',null);
insert into nationality_master_malaffi values ('SRB','Serbian','Serbia',null);
insert into nationality_master_malaffi values ('SSD','South Sudanese','South Sudan',null);
insert into nationality_master_malaffi values ('STP','Sao Tomean','Sao Tome and Principe',null);
insert into nationality_master_malaffi values ('SUR','Surinamese','Suriname',null);
insert into nationality_master_malaffi values ('SVK','Slovak','Slovakia',null);
insert into nationality_master_malaffi values ('SVN','Slovenian','Slovenia',null);
insert into nationality_master_malaffi values ('SWE','Swedish','Sweden',null);
insert into nationality_master_malaffi values ('SWZ','Swazi','Swaziland',null);
insert into nationality_master_malaffi values ('SYC','Seychellois','Seychelles',null);
insert into nationality_master_malaffi values ('SYR','Syrian','Syrian Arab Republic',null);
insert into nationality_master_malaffi values ('TCD','Chadian','Chad',null);
insert into nationality_master_malaffi values ('TGO','Togolese','Togo',null);
insert into nationality_master_malaffi values ('THA','Thai','Thailand',null);
insert into nationality_master_malaffi values ('TJK','Tajikistani','Tajikistan',null);
insert into nationality_master_malaffi values ('TKM','Turkmen','Turkmenistan',null);
insert into nationality_master_malaffi values ('TLS','Timorese','Timor-Leste',null);
insert into nationality_master_malaffi values ('TON','Tongan','Tonga',null);
insert into nationality_master_malaffi values ('TTO','Trinidadian','Trinidad and Tobago',null);
insert into nationality_master_malaffi values ('TUN','Tunisian','Tunisia',null);
insert into nationality_master_malaffi values ('TUR','Turkish','Turkey',null);
insert into nationality_master_malaffi values ('TUV','Tuvaluan','Tuvalu',null);
insert into nationality_master_malaffi values ('TWN','Taiwanese','Taiwan',null);
insert into nationality_master_malaffi values ('TZA','Tanzanian','Tanzania',null);
insert into nationality_master_malaffi values ('UGA','Ugandan','Uganda',null);
insert into nationality_master_malaffi values ('UKR','Ukrainian','Ukraine',null);
insert into nationality_master_malaffi values ('UNA','United Nations','',null);
insert into nationality_master_malaffi values ('URY','Uruguayan','Uruguay',null);
insert into nationality_master_malaffi values ('USA','American','United States of America',null);
insert into nationality_master_malaffi values ('UZB','Uzbek','Uzbekistan',null);
insert into nationality_master_malaffi values ('VAT','Vatican','Vatican City',null);
insert into nationality_master_malaffi values ('VCT','Vincentian','Saint Vincent and the Grenadines',null);
insert into nationality_master_malaffi values ('VEN','Venezuelan','Venezuela',null);
insert into nationality_master_malaffi values ('VNM','Vietnamese','Viet Nam',null);
insert into nationality_master_malaffi values ('VUT','Ni-Vanuatu','Vanuatu',null);
insert into nationality_master_malaffi values ('YEM','Yemeni','Yemen',null);
insert into nationality_master_malaffi values ('ZAF','South African','South Africa',null);
insert into nationality_master_malaffi values ('ZMB','Zambian','Zambia',null);
insert into nationality_master_malaffi values ('ZWE','Zimbabwean','Zimbabwe',null);
insert into nationality_master_malaffi values ('BID','Bidoun','OTHER',null);
insert into nationality_master_malaffi values ('AUS','Australian','Heard Island and McDonald Islands',null);
insert into nationality_master_malaffi values ('ITA','Italian','ITLY',null);
insert into nationality_master_malaffi values ('ARE','Emirati','UAE',null);
insert into nationality_master_malaffi values ('FIN','Finnish','Åland Islands',null);
insert into nationality_master_malaffi values ('GBR','British','Anguilla',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Antarctica',null);
insert into nationality_master_malaffi values ('NLD','Dutch','Aruba',null);
insert into nationality_master_malaffi values ('GBR','British','Bermuda',null);
insert into nationality_master_malaffi values ('NOR','Norwegian','Bouvet Island',null);
insert into nationality_master_malaffi values ('GBR','British','British Indian Ocean Territory',null);
insert into nationality_master_malaffi values ('GBR','British','Cayman Islands',null);
insert into nationality_master_malaffi values ('AUS','Australian','Christmas Island',null);
insert into nationality_master_malaffi values ('AUS','Australian','Cocos (Keeling) Islands',null);
insert into nationality_master_malaffi values ('NLD','Dutch','Curaçao',null);
insert into nationality_master_malaffi values ('DNK','Danish','Faroe Islands',null);
insert into nationality_master_malaffi values ('FRA','French','France',null);
insert into nationality_master_malaffi values ('FRA','French','French Guiana',null);
insert into nationality_master_malaffi values ('FRA','French','French Polynesia',null);
insert into nationality_master_malaffi values ('FRA','French','French Southern Territories',null);
insert into nationality_master_malaffi values ('GBR','British','Gibraltar',null);
insert into nationality_master_malaffi values ('DNK','Danish','Greenland',null);
insert into nationality_master_malaffi values ('FRA','French','Guadeloupe',null);
insert into nationality_master_malaffi values ('USA','American','Guam',null);
insert into nationality_master_malaffi values ('GBR','British','Guernsey',null);
insert into nationality_master_malaffi values ('CHN','Chinese','Hong Kong',null);
insert into nationality_master_malaffi values ('GBR','British','Isle of Man',null);
insert into nationality_master_malaffi values ('GBR','British','Jersey',null);
insert into nationality_master_malaffi values ('KOR','Korean','North Korea',null);
insert into nationality_master_malaffi values ('DEU','German','Liechtenstein',null);
insert into nationality_master_malaffi values ('CHN','Chinese','Macao',null);
insert into nationality_master_malaffi values ('FRA','French','Martinique',null);
insert into nationality_master_malaffi values ('FRA','French','Mayotte',null);
insert into nationality_master_malaffi values ('MON','Montenegrin','Montenegro',null);
insert into nationality_master_malaffi values ('GBR','British','Montserrat',null);
insert into nationality_master_malaffi values ('FRA','French','New Caledonia',null);
insert into nationality_master_malaffi values ('AUS','Australian','Norfolk Island',null);
insert into nationality_master_malaffi values ('USA','American','Northern Mariana Islands',null);
insert into nationality_master_malaffi values ('GBR','British','Pitcairn',null);
insert into nationality_master_malaffi values ('USA','American','Puerto Rico',null);
insert into nationality_master_malaffi values ('FRA','French','Réunion',null);
insert into nationality_master_malaffi values ('ROM','Romanian','Romania',null);
insert into nationality_master_malaffi values ('FRA','French','Saint Barthélemy',null);
insert into nationality_master_malaffi values ('FRA','French','Saint Martin (French)',null);
insert into nationality_master_malaffi values ('FRA','French','Saint Pierre and Miquelon',null);
insert into nationality_master_malaffi values ('NLD','Dutch','Sint Maarten (Dutch)',null);
insert into nationality_master_malaffi values ('GBR','British','South Georgia and the South Sandwich Islands',null);
insert into nationality_master_malaffi values ('NOR','Norwegian','Svalbard and Jan Mayen',null);
insert into nationality_master_malaffi values ('NZL','New Zealander','Tokelau',null);
insert into nationality_master_malaffi values ('GBR','British','Turks and Caicos Islands',null);
insert into nationality_master_malaffi values ('USA','American','US Minor Outlying Islands',null);
insert into nationality_master_malaffi values ('GBR','British','Virgin Islands (British)',null);
insert into nationality_master_malaffi values ('USA','American','Virgin Islands (U.S.)',null);
insert into nationality_master_malaffi values ('FRA','French','Wallis and Futuna',null);
insert into nationality_master_malaffi values ('GBR','British','European Union',null);
insert into nationality_master_malaffi values ('GBR','British','British Overseas Territories Citizen',null);
insert into nationality_master_malaffi values ('GBR','British','British National',null);
insert into nationality_master_malaffi values ('GBR','British','British Overseas Citizen',null);
insert into nationality_master_malaffi values ('BID','Bidoun','British Protected Person',null);
insert into nationality_master_malaffi values ('BID','Bidoun','British Subject',null);
insert into nationality_master_malaffi values ('UNA','United Nations','United Nations Organization',null);
insert into nationality_master_malaffi values ('BID','Bidoun','United Nations Specialized Agency',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Resident of Kosovo',null);
insert into nationality_master_malaffi values ('BID','Bidoun','African Development Bank',null);
insert into nationality_master_malaffi values ('BID','Bidoun','African Export-Import Bank',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Caribbean Community or one of its emissaries',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Common Market for Eastern and Southern Africa',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Economic Community of West African States',null);
insert into nationality_master_malaffi values ('BID','Bidoun','International Criminal Police Organization',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Sovereign Military Order of Malta',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Stateless Person',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Refugee as defined in Article 1 of the 1951',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Refugee',null);
insert into nationality_master_malaffi values ('BID','Bidoun','Person of unspecified nationality',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'), 6, cs.id, cm.id, malaffi_description, malaffi_code, null 
    FROM nationality_master_malaffi cmt 
    JOIN country_master cm ON (lower(cm.country_name) = lower(cmt.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE cm.id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=6 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS nationality_master_malaffi;

-- State Mapping
CREATE TABLE state_master_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into state_master_malaffi values ('1','Abu Dhabi','Abu Dhabi',null);
insert into state_master_malaffi values ('2','Dubai','Dubai',null);
insert into state_master_malaffi values ('3','Sharjah','Sharjah',null);
insert into state_master_malaffi values ('4','Ajman','Ajman',null);
insert into state_master_malaffi values ('5','Ras al Khaimah','Ras al Khaimah',null);
insert into state_master_malaffi values ('6','Fujairah','Fujairah',null);
insert into state_master_malaffi values ('7','Um Al Quwain','Um Al Quwain',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'),7, cs.id, sm.id, malaffi_description, malaffi_code, null 
    FROM state_master_malaffi smt 
    JOIN state_master sm ON (lower(sm.state_name) = lower(smt.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE sm.id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=7 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
INSERT INTO code_sets
(SELECT nextval('code_sets_seq'),7,1,id,'Others','0',null FROM state_master sm
    WHERE sm.id NOT in (SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=7 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS state_master_malaffi;

-- Country Mapping
CREATE TABLE country_master_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into country_master_malaffi values ('AGO','Angola','Angola',null);
insert into country_master_malaffi values ('ALB','Albania','Albania',null);
insert into country_master_malaffi values ('AND','Andorra','Andorra',null);
insert into country_master_malaffi values ('ARE','United Arab Emirates','United Arab Emirates',null);
insert into country_master_malaffi values ('ARG','Argentina','Argentina',null);
insert into country_master_malaffi values ('ARM','Armenia','Armenia',null);
insert into country_master_malaffi values ('ASM','Samoa','Samoa',null);
insert into country_master_malaffi values ('ATG','Antigua and Barbuda','Antigua and Barbuda',null);
insert into country_master_malaffi values ('AUS','Australia','Australia',null);
insert into country_master_malaffi values ('AUT','Austria','Austria',null);
insert into country_master_malaffi values ('AZE','Azerbaijan','Azerbaijan',null);
insert into country_master_malaffi values ('BDI','Burundi','Burundi',null);
insert into country_master_malaffi values ('BEL','Belgium','Belgium',null);
insert into country_master_malaffi values ('BEN','Benin','Benin',null);
insert into country_master_malaffi values ('BFA','Burkina Faso','Burkina Faso',null);
insert into country_master_malaffi values ('BGD','Bangladesh','Bangladesh',null);
insert into country_master_malaffi values ('BGR','Bulgaria','Bulgaria',null);
insert into country_master_malaffi values ('BHR','Bahrain','Bahrain',null);
insert into country_master_malaffi values ('BHS','Bahamas','Bahamas',null);
insert into country_master_malaffi values ('BID','Without Nationality','Without Nationality',null);
insert into country_master_malaffi values ('BIH','Bosnia and Herzegovina','Bosnia and Herzegovina',null);
insert into country_master_malaffi values ('BLR','Belarus','Belarus',null);
insert into country_master_malaffi values ('BLZ','Belize','Belize',null);
insert into country_master_malaffi values ('BOL','Bolivia','Bolivia',null);
insert into country_master_malaffi values ('BRA','Brazil','Brazil',null);
insert into country_master_malaffi values ('BRB','Barbados','Barbados',null);
insert into country_master_malaffi values ('BRN','Brunei Darussalam','Brunei Darussalam',null);
insert into country_master_malaffi values ('BTN','Bhutan','Bhutan',null);
insert into country_master_malaffi values ('BWA','Botswana','Botswana',null);
insert into country_master_malaffi values ('CAF','Central African Republic','Central African Republic',null);
insert into country_master_malaffi values ('CAN','Canada','Canada',null);
insert into country_master_malaffi values ('CHE','Switzerland','Switzerland',null);
insert into country_master_malaffi values ('CHL','Chile','Chile',null);
insert into country_master_malaffi values ('CHN','China','China',null);
insert into country_master_malaffi values ('CIV','Côte d''Ivoire','Côte d''Ivoire',null);
insert into country_master_malaffi values ('CMR','Cameroon','Cameroon',null);
insert into country_master_malaffi values ('COG','Congo; Democratic Republic of the Congo','Congo; Democratic Republic of the Congo',null);
insert into country_master_malaffi values ('COK','Cook Islands','Cook Islands',null);
insert into country_master_malaffi values ('COL','Colombia','Colombia',null);
insert into country_master_malaffi values ('COM','Comoros','Comoros',null);
insert into country_master_malaffi values ('CPV','Cape Verde','Cape Verde',null);
insert into country_master_malaffi values ('CRI','Costa Rica','Costa Rica',null);
insert into country_master_malaffi values ('CUB','Cuba','Cuba',null);
insert into country_master_malaffi values ('CYP','Cyprus','Cyprus',null);
insert into country_master_malaffi values ('CZE','Czech Republic','Czech Republic',null);
insert into country_master_malaffi values ('DEU','Germany','Germany',null);
insert into country_master_malaffi values ('DJI','Djibouti','Djibouti',null);
insert into country_master_malaffi values ('DMA','Dominica','Dominica',null);
insert into country_master_malaffi values ('DNK','Denmark','Denmark',null);
insert into country_master_malaffi values ('DOM','Dominican Republic','Dominican Republic',null);
insert into country_master_malaffi values ('DZA','Algeria','Algeria',null);
insert into country_master_malaffi values ('ECU','Ecuador','Ecuador',null);
insert into country_master_malaffi values ('EGY','Egypt','Egypt',null);
insert into country_master_malaffi values ('ERI','Eritrea','Eritrea',null);
insert into country_master_malaffi values ('ESH','Western Sahara','Western Sahara',null);
insert into country_master_malaffi values ('ESP','Spain','Spain',null);
insert into country_master_malaffi values ('EST','Estonia','Estonia',null);
insert into country_master_malaffi values ('ETH','Ethiopia','Ethiopia',null);
insert into country_master_malaffi values ('FIN','Finland','Finland',null);
insert into country_master_malaffi values ('FJI','Fiji','Fiji',null);
insert into country_master_malaffi values ('FRA','France','France',null);
insert into country_master_malaffi values ('FSM','Micronesia','Micronesia',null);
insert into country_master_malaffi values ('GAB','Gabon','Gabon',null);
insert into country_master_malaffi values ('GBR','United Kingdom','United Kingdom',null);
insert into country_master_malaffi values ('GEO','Georgia','Georgia',null);
insert into country_master_malaffi values ('GHA','Ghana','Ghana',null);
insert into country_master_malaffi values ('GIN','Guinea','Guinea',null);
insert into country_master_malaffi values ('GMB','Gambia','Gambia',null);
insert into country_master_malaffi values ('GNB','Guinea-Bissau','Guinea-Bissau',null);
insert into country_master_malaffi values ('GNQ','Equatorial Guinea','Equatorial Guinea',null);
insert into country_master_malaffi values ('GRC','Greece','Greece',null);
insert into country_master_malaffi values ('GRD','Grenada','Grenada',null);
insert into country_master_malaffi values ('GTM','Guatemala','Guatemala',null);
insert into country_master_malaffi values ('GUY','Guyana','Guyana',null);
insert into country_master_malaffi values ('HND','Honduras','Honduras',null);
insert into country_master_malaffi values ('HRV','Croatia','Croatia',null);
insert into country_master_malaffi values ('HTI','Haiti','Haiti',null);
insert into country_master_malaffi values ('HUN','Hungary','Hungary',null);
insert into country_master_malaffi values ('IDN','Indonesia','Indonesia',null);
insert into country_master_malaffi values ('IRL','Ireland','Ireland',null);
insert into country_master_malaffi values ('IRN','Iran','Iran',null);
insert into country_master_malaffi values ('IND','India','India',null);
insert into country_master_malaffi values ('IRQ','Iraq','Iraq',null);
insert into country_master_malaffi values ('ISL','Iceland','Iceland',null);
insert into country_master_malaffi values ('ISR','Israel','Israel',null);
insert into country_master_malaffi values ('ITA','Italy','Italy',null);
insert into country_master_malaffi values ('JAM','Jamaica','Jamaica',null);
insert into country_master_malaffi values ('JOR','Jordan','Jordan',null);
insert into country_master_malaffi values ('JPN','Japan','Japan',null);
insert into country_master_malaffi values ('KAZ','Kazakhstan','Kazakhstan',null);
insert into country_master_malaffi values ('KEN','Kenya','Kenya',null);
insert into country_master_malaffi values ('KGZ','Kyrgyzstan','Kyrgyzstan',null);
insert into country_master_malaffi values ('KHM','Cambodia','Cambodia',null);
insert into country_master_malaffi values ('KIR','Kiribati','Kiribati',null);
insert into country_master_malaffi values ('KNA','Saint Kitts and Nevis','Saint Kitts and Nevis',null);
insert into country_master_malaffi values ('KOR','Republic of Korea, DPRK','Republic of Korea, DPRK',null);
insert into country_master_malaffi values ('KWT','Kuwait','Kuwait',null);
insert into country_master_malaffi values ('LAO','Lao People''s Democratic Republic','Lao People''s Democratic Republic',null);
insert into country_master_malaffi values ('LBN','Lebanon','Lebanon',null);
insert into country_master_malaffi values ('LBR','Liberia','Liberia',null);
insert into country_master_malaffi values ('LBY','Libyan Arab Jamahiriya','Libyan Arab Jamahiriya',null);
insert into country_master_malaffi values ('LCA','Saint Lucia','Saint Lucia',null);
insert into country_master_malaffi values ('LKA','Sri Lanka','Sri Lanka',null);
insert into country_master_malaffi values ('LSO','Lesotho','Lesotho',null);
insert into country_master_malaffi values ('LTU','Lithuania','Lithuania',null);
insert into country_master_malaffi values ('LUX','Luxembourg','Luxembourg',null);
insert into country_master_malaffi values ('LVA','Latvia','Latvia',null);
insert into country_master_malaffi values ('MAR','Morocco','Morocco',null);
insert into country_master_malaffi values ('MCO','Monaco','Monaco',null);
insert into country_master_malaffi values ('MDA','Republic of Moldova','Republic of Moldova',null);
insert into country_master_malaffi values ('MDG','Madagascar','Madagascar',null);
insert into country_master_malaffi values ('MDV','Maldives','Maldives',null);
insert into country_master_malaffi values ('MEX','Mexico','Mexico',null);
insert into country_master_malaffi values ('MHL','Marshall Islands','Marshall Islands',null);
insert into country_master_malaffi values ('MKD','Republic of Macedonia','Republic of Macedonia',null);
insert into country_master_malaffi values ('MLI','Mali','Mali',null);
insert into country_master_malaffi values ('MLT','Malta','Malta',null);
insert into country_master_malaffi values ('MMR','Myanmar','Myanmar',null);
insert into country_master_malaffi values ('MNG','Mongolia','Mongolia',null);
insert into country_master_malaffi values ('MON','Montenegro','Montenegro',null);
insert into country_master_malaffi values ('MOZ','Mozambique','Mozambique',null);
insert into country_master_malaffi values ('MRT','Mauritania','Mauritania',null);
insert into country_master_malaffi values ('MUS','Mauritius','Mauritius',null);
insert into country_master_malaffi values ('MWI','Malawi','Malawi',null);
insert into country_master_malaffi values ('MYS','Malaysia','Malaysia',null);
insert into country_master_malaffi values ('NAM','Namibia','Namibia',null);
insert into country_master_malaffi values ('NER','Niger','Niger',null);
insert into country_master_malaffi values ('NGA','Nigeria','Nigeria',null);
insert into country_master_malaffi values ('NIC','Nicaragua','Nicaragua',null);
insert into country_master_malaffi values ('NIU','Niue','Niue',null);
insert into country_master_malaffi values ('NLD','Netherlands','Netherlands',null);
insert into country_master_malaffi values ('NOR','Norway','Norway',null);
insert into country_master_malaffi values ('NPL','Nepal','Nepal',null);
insert into country_master_malaffi values ('NRU','Nauru','Nauru',null);
insert into country_master_malaffi values ('NZL','New Zealand','New Zealand',null);
insert into country_master_malaffi values ('OMN','Oman','Oman',null);
insert into country_master_malaffi values ('PAK','Pakistan','Pakistan',null);
insert into country_master_malaffi values ('PAN','Panama','Panama',null);
insert into country_master_malaffi values ('PER','Peru','Peru',null);
insert into country_master_malaffi values ('PHL','Philippines','Philippines',null);
insert into country_master_malaffi values ('PLW','Palau','Palau',null);
insert into country_master_malaffi values ('PNG','Papua New Guinea','Papua New Guinea',null);
insert into country_master_malaffi values ('POL','Poland','Poland',null);
insert into country_master_malaffi values ('PRT','Portugal','Portugal',null);
insert into country_master_malaffi values ('PRY','Paraguay','Paraguay',null);
insert into country_master_malaffi values ('PSE','Palestine','Palestine',null);
insert into country_master_malaffi values ('QAT','Qatar','Qatar',null);
insert into country_master_malaffi values ('ROM','Romania','Romania',null);
insert into country_master_malaffi values ('RUS','Russian Federation','Russian Federation',null);
insert into country_master_malaffi values ('RWA','Rwanda','Rwanda',null);
insert into country_master_malaffi values ('SAU','Saudi Arabia','Saudi Arabia',null);
insert into country_master_malaffi values ('SDN','Sudan','Sudan',null);
insert into country_master_malaffi values ('SEN','Senegal','Senegal',null);
insert into country_master_malaffi values ('SGP','Singapore','Singapore',null);
insert into country_master_malaffi values ('SLB','Solomon Islands','Solomon Islands',null);
insert into country_master_malaffi values ('SLE','Sierra Leone','Sierra Leone',null);
insert into country_master_malaffi values ('SLV','El Salvador','El Salvador',null);
insert into country_master_malaffi values ('SMR','San Marino','San Marino',null);
insert into country_master_malaffi values ('SOM','Somalia','Somalia',null);
insert into country_master_malaffi values ('SRB','Serbia','Serbia',null);
insert into country_master_malaffi values ('SSD','South Sudan','South Sudan',null);
insert into country_master_malaffi values ('STP','Sao Tome and Principe','Sao Tome and Principe',null);
insert into country_master_malaffi values ('SUR','Suriname','Suriname',null);
insert into country_master_malaffi values ('SVK','Slovakia','Slovakia',null);
insert into country_master_malaffi values ('SVN','Slovenia','Slovenia',null);
insert into country_master_malaffi values ('SWE','Sweden','Sweden',null);
insert into country_master_malaffi values ('SWZ','Swaziland','Swaziland',null);
insert into country_master_malaffi values ('SYC','Seychelles','Seychelles',null);
insert into country_master_malaffi values ('SYR','Syrian Arab Republic','Syrian Arab Republic',null);
insert into country_master_malaffi values ('TCD','Chad','Chad',null);
insert into country_master_malaffi values ('TGO','Togo','Togo',null);
insert into country_master_malaffi values ('THA','Thailand','Thailand',null);
insert into country_master_malaffi values ('TJK','Tajikistan','Tajikistan',null);
insert into country_master_malaffi values ('TKM','Turkmenistan','Turkmenistan',null);
insert into country_master_malaffi values ('TLS','Timor-Leste','Timor-Leste',null);
insert into country_master_malaffi values ('TON','Tonga','Tonga',null);
insert into country_master_malaffi values ('TTO','Trinidad and Tobago','Trinidad and Tobago',null);
insert into country_master_malaffi values ('TUN','Tunisia','Tunisia',null);
insert into country_master_malaffi values ('TUR','Turkey','Turkey',null);
insert into country_master_malaffi values ('TUV','Tuvalu','Tuvalu',null);
insert into country_master_malaffi values ('TWN','Republic of China (Taiwan)','Republic of China (Taiwan)',null);
insert into country_master_malaffi values ('TZA','United Republic of Tanzania','United Republic of Tanzania',null);
insert into country_master_malaffi values ('UGA','Uganda','Uganda',null);
insert into country_master_malaffi values ('UKR','Ukraine','Ukraine',null);
insert into country_master_malaffi values ('UNA','United Nations','United Nations',null);
insert into country_master_malaffi values ('URY','Uruguay','Uruguay',null);
insert into country_master_malaffi values ('USA','United States of America','United States of America',null);
insert into country_master_malaffi values ('UZB','Uzbekistan','Uzbekistan',null);
insert into country_master_malaffi values ('VAT','Vatican City','Vatican City',null);
insert into country_master_malaffi values ('VCT','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines',null);
insert into country_master_malaffi values ('VEN','Venezuela','Venezuela',null);
insert into country_master_malaffi values ('VNM','Viet Nam','Viet Nam',null);
insert into country_master_malaffi values ('VUT','Vanuatu','Vanuatu',null);
insert into country_master_malaffi values ('YEM','Yemen','Yemen',null);
insert into country_master_malaffi values ('ZAF','South Africa','South Africa',null);
insert into country_master_malaffi values ('ZMB','Zambia','Zambia',null);
insert into country_master_malaffi values ('ZWE','Zimbabwe','Zimbabwe',null);
insert into country_master_malaffi values ('BID','Without Nationality','OTHER',null);
insert into country_master_malaffi values ('AUS','Australia','Heard Island and McDonald Islands',null);
insert into country_master_malaffi values ('ITA','Italy ','ITLY',null);
insert into country_master_malaffi values ('ARE','United Arab Emirates','UAE',null);
insert into country_master_malaffi values ('FIN','Finland','Åland Islands',null);
insert into country_master_malaffi values ('USA','United States of America','American Samoa',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Anguilla',null);
insert into country_master_malaffi values ('BID','Without Nationality','Antarctica',null);
insert into country_master_malaffi values ('NLD','Netherlands','Aruba',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Bermuda',null);
insert into country_master_malaffi values ('NOR','Norway','Bouvet Island',null);
insert into country_master_malaffi values ('GBR','United Kingdom','British Indian Ocean Territory',null);
insert into country_master_malaffi values ('CAF','Central African Republic','Cabo Verde',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Cayman Islands',null);
insert into country_master_malaffi values ('AUS','Australia','Christmas Island',null);
insert into country_master_malaffi values ('AUS','Australia','Cocos (Keeling) Islands',null);
insert into country_master_malaffi values ('COG','Congo; Democratic Republic of the Congo','Congo',null);
insert into country_master_malaffi values ('COG','Congo; Democratic Republic of the Congo','Congo (Democratic Republic of the)',null);
insert into country_master_malaffi values ('ESH','Western Sahara','Cote d Ivoire',null);
insert into country_master_malaffi values ('NLD','Netherlands','Curaçao',null);
insert into country_master_malaffi values ('CZE','Czech Republic','Czechia',null);
insert into country_master_malaffi values ('MWI','Malawi','Falkland Islands (Malvinas)',null);
insert into country_master_malaffi values ('DNK','Denmark','Faroe Islands',null);
insert into country_master_malaffi values ('FRA','France','French Guiana',null);
insert into country_master_malaffi values ('FRA','France','French Polynesia',null);
insert into country_master_malaffi values ('FRA','France','French Southern Territories',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Gibraltar',null);
insert into country_master_malaffi values ('DNK','Denmark','Greenland',null);
insert into country_master_malaffi values ('FRA','France','Guadeloupe',null);
insert into country_master_malaffi values ('USA','United States of America','Guam',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Guernsey',null);
insert into country_master_malaffi values ('CHN','China','Hong Kong',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Isle of Man',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Jersey',null);
insert into country_master_malaffi values ('KOR','Republic of Korea; DPRK','North Korea',null);
insert into country_master_malaffi values ('KOR','Republic of Korea; DPRK','South Korea',null);
insert into country_master_malaffi values ('LAO','Lao People''s Democratic Republic','Laos',null);
insert into country_master_malaffi values ('LBY','Libyan Arab Jamahiriya','Libya',null);
insert into country_master_malaffi values ('DEU','Germany','Liechtenstein',null);
insert into country_master_malaffi values ('CHN','China','Macao',null);
insert into country_master_malaffi values ('MKD','Republic of Macedonia','Macedonia',null);
insert into country_master_malaffi values ('FRA','France','Martinique',null);
insert into country_master_malaffi values ('FRA','France','Mayotte',null);
insert into country_master_malaffi values ('MDA','Republic of Moldova','Moldova',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Montserrat',null);
insert into country_master_malaffi values ('FRA','France','New Caledonia',null);
insert into country_master_malaffi values ('AUS','Australia','Norfolk Island',null);
insert into country_master_malaffi values ('USA','United States of America','Northern Mariana Islands',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Pitcairn',null);
insert into country_master_malaffi values ('USA','United States of America','Puerto Rico',null);
insert into country_master_malaffi values ('FRA','France','Réunion',null);
insert into country_master_malaffi values ('FRA','France','Saint Barthélemy',null);
insert into country_master_malaffi values ('FRA','France','Saint Martin (French)',null);
insert into country_master_malaffi values ('FRA','France','Saint Pierre and Miquelon',null);
insert into country_master_malaffi values ('NLD','Netherlands','Sint Maarten (Dutch)',null);
insert into country_master_malaffi values ('GBR','United Kingdom','South Georgia and the South Sandwich Islands',null);
insert into country_master_malaffi values ('NOR','Norway','Svalbard and Jan Mayen',null);
insert into country_master_malaffi values ('TWN','Republic of China (Taiwan)','Taiwan',null);
insert into country_master_malaffi values ('TZA','United Republic of Tanzania','Tanzania',null);
insert into country_master_malaffi values ('NZL','New Zealand','Tokelau',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Turks and Caicos Islands',null);
insert into country_master_malaffi values ('USA','United States of America','US Minor Outlying Islands',null);
insert into country_master_malaffi values ('GBR','United Kingdom','Virgin Islands (British)',null);
insert into country_master_malaffi values ('USA','United States of America','Virgin Islands (U.S.)',null);
insert into country_master_malaffi values ('FRA','France','Wallis and Futuna',null);
insert into country_master_malaffi values ('GBR','United Kingdom','European Union',null);
insert into country_master_malaffi values ('GBR','United Kingdom','British Overseas Territories Citizen',null);
insert into country_master_malaffi values ('GBR','United Kingdom','British National',null);
insert into country_master_malaffi values ('GBR','United Kingdom','British Overseas Citizen',null);
insert into country_master_malaffi values ('BID','Without Nationality','British Protected Person',null);
insert into country_master_malaffi values ('BID','Without Nationality','British Subject',null);
insert into country_master_malaffi values ('UNA','United Nations','United Nations Organization',null);
insert into country_master_malaffi values ('BID','Without Nationality','United Nations Specialized Agency',null);
insert into country_master_malaffi values ('BID','Without Nationality','Resident of Kosovo',null);
insert into country_master_malaffi values ('BID','Without Nationality','African Development Bank',null);
insert into country_master_malaffi values ('BID','Without Nationality','African Export-Import Bank',null);
insert into country_master_malaffi values ('BID','Without Nationality','Caribbean Community or one of its emissaries',null);
insert into country_master_malaffi values ('BID','Without Nationality','Common Market for Eastern and Southern Africa',null);
insert into country_master_malaffi values ('BID','Without Nationality','Economic Community of West African States',null);
insert into country_master_malaffi values ('BID','Without Nationality','International Criminal Police Organization',null);
insert into country_master_malaffi values ('BID','Without Nationality','Sovereign Military Order of Malta',null);
insert into country_master_malaffi values ('BID','Without Nationality','Stateless Person',null);
insert into country_master_malaffi values ('BID','Without Nationality','Refugee as defined in Article 1 of the 1951',null);
insert into country_master_malaffi values ('BID','Without Nationality','Refugee',null);
insert into country_master_malaffi values ('BID','Without Nationality','Person of unspecified nationality',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'),8, cs.id, cm.id, malaffi_description, malaffi_code, null 
    FROM country_master_malaffi cmt 
    JOIN country_master cm ON (lower(cm.country_name) = lower(cmt.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE cm.id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=8 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS country_master_malaffi;

-- Diagnosis_ststus
CREATE TABLE diagnosis_statuses_malaffi (
    malaffi_code CHARACTER VARYING,
    malaffi_description CHARACTER VARYING,
    hms_name CHARACTER VARYING,
    is_default CHARACTER VARYING
);
insert into diagnosis_statuses_malaffi values ('A','Admitting','Admitting',null);
insert into diagnosis_statuses_malaffi values ('A','Admitting','Other',null);
insert into diagnosis_statuses_malaffi values ('W','Working','Working',null);
insert into diagnosis_statuses_malaffi values ('W','Working','Probable',null);
insert into diagnosis_statuses_malaffi values ('F','Final','Final',null);
insert into diagnosis_statuses_malaffi values ('F','Final','Confirmed',null);
INSERT INTO code_sets 
(SELECT nextval('code_sets_seq'),9, cs.id, ds.diagnosis_status_id, malaffi_description, malaffi_code, null 
    FROM diagnosis_statuses_malaffi dst 
    JOIN diagnosis_statuses ds ON (lower(ds.diagnosis_status_name) = lower(dst.hms_name))
    JOIN code_systems cs ON (cs.label = 'MALAFFI')
    WHERE ds.diagnosis_status_id NOT IN (
        SELECT cs.entity_id FROM code_sets cs, code_systems css WHERE cs.code_system_category_id=9 AND cs.code_system_id=css.id AND css.label = 'MALAFFI'));
DROP TABLE IF EXISTS diagnosis_statuses_malaffi;

UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 2 AND short_code='OTH' AND label='Other' ORDER BY id ASC LIMIT 1);
UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 3 AND short_code='U' AND label='Unknown' ORDER BY id ASC LIMIT 1);
UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 4 AND short_code='20' AND label= 'General Practitioner' ORDER BY id ASC LIMIT 1);
UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 5 AND short_code='1' AND label= 'Discharged with approval' ORDER BY id ASC LIMIT 1);
UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 6 AND short_code='BID' AND label= 'Bidoun' ORDER BY id ASC LIMIT 1);
UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 7 AND short_code='0' AND label= 'Others' ORDER BY id ASC LIMIT 1);
UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 8 AND short_code='BID' AND label= 'Without Nationality' ORDER BY id ASC LIMIT 1);
UPDATE code_sets set is_default = true WHERE id = (SELECT id FROM code_sets WHERE code_system_category_id = 9 AND short_code='A' AND label= 'Admitting' ORDER BY id ASC LIMIT 1);
