-- NABIDH segment template which uses 2.5 version messages

-- MSH segment template
UPDATE hl7_segment_template hst SET field_template = '|' FROM interface_config_master icm WHERE segment_field_number = 'MSH_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '^~\&' FROM interface_config_master icm WHERE segment_field_number = 'MSH_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sending_application??>${sending_application}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sending_application??>${sending_application}/<#if center_service_reg_no??>${center_service_reg_no}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if receving_application??>${receving_application}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if receving_facility??>${receving_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if date_time??>${date_time}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if message_type??>${message_type?substring(0,3)}^${message_type?substring(4,7)}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if msgCtrlId??>${msgCtrlId}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = 'P' FROM interface_config_master icm WHERE segment_field_number = 'MSH_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if message_version??>${message_version}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MSH_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = 'UTF-8' FROM interface_config_master icm WHERE segment_field_number = 'MSH_18' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- EVN segment template
UPDATE hl7_segment_template hst SET field_template = '<#if message_type??>${message_type?substring(4,7)}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'EVN_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if date_time??>${date_time}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'EVN_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if date_time??>${date_time}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'EVN_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = 'DHCC^<#if center_service_reg_no??>${center_service_reg_no}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'EVN_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- PID segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if mr_no??>${mr_no}</#if>^^^<#if sending_facility??>${sending_facility}</#if>^MRN' FROM interface_config_master icm WHERE segment_field_number = 'PID_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if passport_no??>${passport_no}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_data?? && visit_data[0]?? && visit_data[0].isbaby?? && visit_data[0].isbaby = "Y"><#if last_name??>${last_name?cap_first}</#if><#if middle_name??>${middle_name?cap_first} </#if><#if first_name??>${first_name}^Baby of^^^^^D<#else>Baby</#if><#else><#if last_name??>${last_name?cap_first}</#if>^<#if first_name??>${first_name?cap_first}</#if>^<#if middle_name??>${middle_name?cap_first}^^^^D</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if date_of_birth??>${date_of_birth?date?string("yyyyMMdd")}<#elseif expected_date_of_birth??>${expected_date_of_birth?date?string("yyyyMMdd")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if gender??>${gender}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && race_id??><#if code.nabidh.race_master??><#if code.nabidh.race_master[race_id?string]??><#assign pid10_1 = code.nabidh.race_master[race_id?string]><#elseif code.nabidh.race_master.default??><#assign pid10_1 = code.nabidh.race_master.default></#if></#if><#if code_desc.nabidh.race_master??><#if code_desc.nabidh.race_master[race_id?string]??><#assign pid10_2 = code_desc.nabidh.race_master[race_id?string]><#elseif code_desc.nabidh.race_master.default??><#assign pid10_2 = code_desc.nabidh.race_master.default></#if></#if></#if><#if pid10_1??>${pid10_1}^<#if pid10_2??>${pid10_2}</#if>^NAB004</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh??><#if code.nabidh.state_master??><#if code.nabidh.state_master[patient_state_id?string]??><#assign pid11_4_1 = code.nabidh.state_master[patient_state_id?string]><#elseif code.nabidh.state_master.default??><#assign pid11_4_1 = code.nabidh.state_master.default></#if></#if><#if code.nabidh.country_master??><#if code.nabidh.country_master[patient_country_id?string]??><#assign pid11_6 = code.nabidh.country_master[patient_country_id?string]><#elseif code.nabidh.country_master.default??><#assign pid11_6 = code.nabidh.country_master.default></#if></#if></#if><#if patient_address??>${patient_address}</#if>^^<#if patient_city_name??>${patient_city_name}</#if>^${pid11_4_1?trim}^^<#if pid11_6??>${pid11_6}</#if>^H' FROM interface_config_master icm WHERE segment_field_number = 'PID_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_phone??>${patient_phone}</#if>^PRN^CP<#if email_id??>~^NET^Internet^${email_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_13' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = 'UNK^UNKNOWN^NAB024' FROM interface_config_master icm WHERE segment_field_number = 'PID_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.marital_status_master??><#if marital_status_id?? && code.nabidh.marital_status_master[marital_status_id?string]??><#assign pid16_1 = code.nabidh.marital_status_master[marital_status_id?string]><#elseif code.nabidh.marital_status_master.default??><#assign pid16_1 = code.nabidh.marital_status_master.default></#if></#if><#if code_desc?? && code_desc.nabidh?? && code_desc.nabidh.marital_status_master??><#if marital_status_id?? && code_desc.nabidh.marital_status_master[marital_status_id?string]??><#assign pid16_2 = code_desc.nabidh.marital_status_master[marital_status_id?string]><#elseif code_desc.nabidh.marital_status_master.default??><#assign pid16_2 = code_desc.nabidh.marital_status_master.default></#if></#if><#if pid16_1??>${pid16_1}</#if>^<#if pid16_2??>${pid16_2}</#if>^<#if pid16_1??>NAB002</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.religion_master??><#if religion_id?? && code.nabidh.religion_master[religion_id?string]??><#assign pid17_1 = code.nabidh.religion_master[religion_id?string]><#elseif code.nabidh.religion_master.default??><#assign pid17_1 = code.nabidh.religion_master.default></#if></#if><#if code_desc?? && code_desc.nabidh?? && code_desc.nabidh.religion_master??><#if religion_id?? && code_desc.nabidh.religion_master[religion_id?string]??><#assign pid17_2 = code_desc.nabidh.religion_master[religion_id?string]><#elseif code_desc.nabidh.religion_master.default??><#assign pid17_2 = code_desc.nabidh.religion_master.default></#if></#if><#if pid17_1??>${pid17_1}</#if>^<#if pid17_2??>${pid17_2}</#if>^<#if pid17_2??>NAB003</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_17' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_data?? && visit_data[0]?? && visit_data[0].isbaby?? && visit_data[0].isbaby = "Y">111111111111111<#elseif government_identifier??>${government_identifier?replace("-","")}<#else>999999999999999</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_data?? && visit_data[0]?? && visit_data[0].isbaby?? && visit_data[0].isbaby = "Y" && visit_data[0].parent_government_identifier??>${visit_data[0].parent_government_identifier?string?replace("-","")}<#else><#if date_of_birth??><#assign d=.now?string("yyyy")?number><#assign b=date_of_birth?date?string("yyyy")?number><#assign m=.now?string("MM")?number><#assign t=date_of_birth?date?string("MM")?number><#assign day=.now?string("d")?number><#assign myDate=date_of_birth?date?string("d")?number><#assign dif=day-myDate></#if><#if d=b><#if m=t><#if day-myDate<=2>000000000000000</#if><#elseif m-t=1><#if day=1>000000000000000</#if></#if><#elseif d-b=1><#if m=1><#if day=1>000000000000000</#if></#if></#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_21' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.nationality??><#if nationality_id?? && code.nabidh.nationality[nationality_id?string]??><#assign pid28_1 = code.nabidh.nationality[nationality_id?string]><#elseif code.nabidh.nationality.default??><#assign pid28_1 = code.nabidh.nationality.default></#if></#if><#if code_desc?? && code_desc.nabidh?? && code_desc.nabidh.nationality??><#if nationality_id?? && code_desc.nabidh.nationality[nationality_id?string]??><#assign pid28_2 = code_desc.nabidh.nationality[nationality_id?string]><#elseif code_desc.nabidh.nationality.default??><#assign pid28_2 = code_desc.nabidh.nationality.default></#if></#if><#if pid28_1??>${pid28_1}</#if>^<#if pid28_2??>${pid28_2}</#if>^<#if pid28_2??>NAB038</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_28' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if death_date?? && death_time??>${death_date?date?string("yyyyMMdd")}${death_time?time?string("HHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_29' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if death_date?? && death_date?string != "">Y<#else>N</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_30' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if custom_list9_value?? && custom_list9_value != "" && custom_list9_value="Non-Resident">T<#else>O</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_31' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if last_updated_date_time??>${last_updated_date_time?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_33' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sending_application??>${sending_application}/<#if center_service_reg_no??>${center_service_reg_no}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_34' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- PV1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if message_type?? && message_type="ADT_A28" && op_type?? && op_type="O">false<#else>true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.department??><#if department_id?? && code.nabidh.department[department_id?string]??><#assign nabidhDeptCode = code.nabidh.department[department_id?string]><#elseif code.nabidh.department.default??><#assign nabidhDeptCode = code.nabidh.department.default></#if></#if><#if visit_type?? && visit_type = "O" && nabidhDeptCode?? && nabidhDeptCode = "EMM"?string>E<#else>${visit_type}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.ward_names??><#if ward_name_id?? && code.nabidh.ward_names[ward_name_id?string]??><#assign nabidhWardCode = code.nabidh.ward_names[ward_name_id?string]><#elseif code.nabidh.ward_names.default??><#assign nabidhWardCode = code.nabidh.ward_names.default></#if></#if><#if nabidhWardCode??>${nabidhWardCode}</#if>^<#if visit_type?? && visit_type != "O" && ward_no??>${ward_no}</#if>^<#if visit_type?? && visit_type != "O" && bed_name??>${bed_name}</#if>^<#if center_service_reg_no??>${center_service_reg_no}</#if>^^^^^<#if center_service_reg_no??>${center_service_reg_no}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = 'O' FROM interface_config_master icm WHERE segment_field_number = 'PV1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if op_type?? &&  op_type="O">OSP000-00^UnAssigned^Practitioner^^^^^^DHCC<#else><#if doc_first_name?? && doc_last_name?? && doctor_license_number?? && sending_facility??>${doctor_license_number}^${doc_last_name}^${doc_first_name}^^^^^^DHCC</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if op_type?? && op_type="O">OSP000-00^UnAssigned^Practitioner^^^^^^DHCC<#else><#if doc_first_name?? && doc_last_name?? && doctor_license_number?? && sending_facility??>${doctor_license_number}^${doc_last_name}^${doc_first_name}^^^^^^DHCC</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.department??><#if department_id?? && code.nabidh.department[department_id?string]??>${code.nabidh.department[department_id?string]}<#elseif code.nabidh.department.default??>${code.nabidh.department.default}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '9' FROM interface_config_master icm WHERE segment_field_number = 'PV1_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_id?? && sending_facility??>${visit_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.discharge_type_master??><#if discharge_type_id?? && code.nabidh.discharge_type_master[discharge_type_id?string]??><#assign pid36 = code.nabidh.discharge_type_master[discharge_type_id?string]><#elseif code.nabidh.discharge_type_master.default??><#assign pid36 = code.nabidh.discharge_type_master.default></#if></#if><#if discharge_type_id?? && pid36?? && pid36 != "">${pid36}<#elseif discharge_type_id??>HOM</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_36' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if transfer_hospital_name??>${transfer_hospital_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_37' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if reg_date?? && reg_time??>${reg_date?date?string("yyyyMMdd")}${reg_time?time?string("HHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_44' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if visit_status?? && visit_status = "I" && discharge_date?? && discharge_time??>${discharge_date?date?string("yyyyMMdd")}${discharge_time?time?string("HHmmss")}<#elseif visit_status?? && visit_status = "I" && discharge_date??>${discharge_date?date?string("yyyyMMdd")}${.now?time?string("HHmmss")}<#elseif visit_status?? && visit_status = "I" && discharge_time??>${.now?date?string("yyyyMMdd")}${discharge_time?time?string("HHmmss")}<#elseif visit_status?? && visit_status = "I">${.now?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV1_45' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- AL1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number = 1>true<#elseif allergy_type?? && allergy_type != "N">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number = 1>""""<#else>${sequence?number-1}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if allergy_type?? && allergy_type != "N"><#if allergy_type = "M"><#assign al1_2_1 = "DA"><#assign al1_2_2 = "Drug allergy"><#elseif allergy_type = "F"><#assign al1_2_1 = "FA"><#assign al1_2_2 = "Food allergy"><#elseif allergy_type = "O"><#assign al1_2_1 = "MA"><#assign al1_2_2 = "Miscellaneous allergy"><#else><#assign al1_2_1 = "UNKNOWN"><#assign al1_2_2 = "UNKNOWN"></#if><#else><#assign al1_2_1 = "UNKNOWN"><#assign al1_2_2 = "UNKNOWN"></#if><#if al1_2_1??>${al1_2_1}</#if>^<#if al1_2_2??>${al1_2_2}</#if>^<#if al1_2_2??>NAB042</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if allergy_type?? && allergy_type = "M"><#if code?? && code.nabidh?? && code.nabidh.generic_name??><#if generic_name_id?? && code.nabidh.generic_name[generic_name_id?string]??><#assign al13_1 = code.nabidh.generic_name[generic_name_id?string]><#elseif code.nabidh.generic_name.default??><#assign al13_1 = code.nabidh.generic_name.default></#if></#if><#if code_desc?? && code_desc.nabidh?? && code_desc.nabidh.generic_name??><#if generic_name_id?? && code_desc.nabidh.generic_name[generic_name_id?string]??><#assign al13_2 = code_desc.nabidh.generic_name[generic_name_id?string]><#elseif code_desc.nabidh.generic_name.default??><#assign al13_2 = code_desc.nabidh.generic_name.default></#if></#if><#else><#if code?? && code.nabidh?? && code.nabidh.allergen_master??><#if allergen_code_id?? && code.nabidh.allergen_master[allergen_code_id?string]??><#assign al13_1 = code.nabidh.allergen_master[allergen_code_id?string]></#if></#if><#if code_desc?? && code_desc.nabidh?? && code_desc.nabidh.allergen_master??><#if allergen_code_id?? && code_desc.nabidh.allergen_master[allergen_code_id?string]??><#assign al13_2 = code_desc.nabidh.allergen_master[allergen_code_id?string]></#if></#if></#if><#if al13_1?? && al13_1 != "">${al13_1}<#else>000000000</#if>^<#if al13_2?? && al13_2 != "">${al13_2}<#else><#if allergy_type?? && allergy_type = "M" && generic_name??>${generic_name}<#else>${allergen_description}</#if></#if>^<#if allergy_type?? && allergy_type = "M" && al13_2?? && al13_1??>DDC<#else>NAB043</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%'
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if allergy_type?? && allergy_type != "N"><#if severity?? && severity = "Moderate"><#assign al1_4_1 = "MO"><#elseif severity?? && severity = "Severe"><#assign al1_4_1 = "SV"><#elseif severity?? && severity = "Mild"><#assign al1_4_1 = "MI"><#elseif severity?? && severity = "Unknown"><#assign al1_4_1 = "U"><#else><#assign al1_4_1 = "U"></#if><#if severity?? && severity != ""><#assign al1_4_2 = severity><#else><#assign al1_4_2 = "Unknown"></#if><#if al1_4_1??>${al1_4_1}</#if>^<#if al1_4_2??>${al1_4_2}</#if>^HL7128</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if allergy_type?? && allergy_type != "N" && reaction??>Other</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if created_at??>${created_at?date?string("yyyyMMdd")}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'AL1_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- IN1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if ins_plan_id??>${ins_plan_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if ins_co_code??>${ins_co_code}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if insurance_co_name??>${insurance_co_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if policy_validity_start??>${policy_validity_start?date?string("yyyyMMdd")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if policy_validity_end??>${policy_validity_end?date?string("yyyyMMdd")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_13' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if member_id??>${member_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'IN1_36' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- PV2 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if chief_complaint?? && chief_complaint != "">${chief_complaint}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PV2_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- DG1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number = 1>""""<#else>${sequence?number-1}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1>I10</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if diagnosis_code?? && diagnosis_description??>${diagnosis_code}^${diagnosis_description}^I10</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if diagnosis_description??>${diagnosis_description}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if diagnosis_datetime??>${diagnosis_datetime?date?string("yyyyMMddHHmmss")}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if code?? && code.nabidh?? && code.nabidh.diagnosis_statuses??><#if diagnosis_status_id?? && code.nabidh.diagnosis_statuses[diagnosis_status_id?string]??>${code.nabidh.diagnosis_statuses[diagnosis_status_id?string]}<#elseif code.nabidh.diagnosis_statuses.default??>${code.nabidh.diagnosis_statuses.default}<#else>W</#if></#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1><#if diag_type?? && diag_type = "P">1<#elseif diag_type?? && diag_type = "S">2<#else>0</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1>N</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_18' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence?? && sequence?number != 1>A</#if>' FROM interface_config_master icm WHERE segment_field_number = 'DG1_21' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- MRG segment template
UPDATE hl7_segment_template hst SET field_template = '<#if duplicate_mr_no?? && sending_facility??>${duplicate_mr_no}^^^<#if sending_facility??>${sending_facility}</#if>^MRN</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MRG_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if duplicate_mr_no??>${duplicate_mr_no}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'MRG_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- PR1 segment template
UPDATE hl7_segment_template hst SET field_template = '<#if operation_conducted_status?? && operation_conducted_status="C" && item_code?? && item_code != "" && item_code_desc?? && item_code_desc != "">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_code?? && item_code_desc?? && item_code != "">${item_code}^${item_code_desc}^C4</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_code_desc??>${item_code_desc}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if surgery_start_datetime??>${surgery_start_datetime?date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if anaesthetist_license_number?? && anaesthetist_license_number != "">${anaesthetist_license_number}^${anaesthetist_last_name}^${anaesthetist_first_name}^^^^^^&${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if surgeon_license_number?? && surgeon_license_number != "">${surgeon_license_number?replace("-","")}^${surgeon_last_name}^${surgeon_first_name}^^^^^^DHCC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if oper_priority?? && oper_priority = "P">1<#else>2</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if diagnosis_code?? && diagnosis_code != "">${diagnosis_code}^${diagnosis_description}^I10</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PR1_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- NTE segment template
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "investigation" && test_code?? && test_code = "87635" && method_name?? && method_name != "">true<#elseif item_type?? && item_type = "investigation" && comments?? && comments != "">true<#elseif item_type?? && item_type = "chronic_problems" && problem_note?? && problem_note != "">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "chronic_problems" && item_operation?? && item_operation = "insert">P</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "chronic_problems" && problem_note??>${problem_note}<#elseif item_type?? && item_type = "investigation" && test_code?? && test_code = "87635" && method_name?? && method_name != "">${method_name}<#elseif item_type?? && item_type = "investigation" && comments??>${comments}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "investigation">RE^Remarks^${code_system_name}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'NTE_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- ORC segment template for ORU
UPDATE hl7_segment_template hst SET field_template = '<#if item_operation?? && item_operation = "insert">NW<#elseif item_operation?? && item_operation = "update">XO<#elseif item_operation?? && item_operation = "delete">CA<#elseif item_type?? && item_type = "investigation">RE</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'ORC_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if doc_presc_id??>${doc_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && (item_type = "medicine_prescription" || item_type = "medicine_dispense")><#if item_operation?? && item_operation = "delete">entered-in-error<#else>CM</#if></#if><#if item_type?? && item_type = "investigation">CM</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '^^^<#if presc_start_date??>${presc_start_date?string("yyyyMMddHHmmss")}</#if>^<#if presc_end_date??>${presc_end_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if prescribed_date??>${prescribed_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_doc_license_number??>${presc_doc_license_number?string?replace("-","")}^<#if presc_doc_last_name??>${presc_doc_last_name}</#if>^<#if presc_doc_first_name??>${presc_doc_first_name}</#if>^^^^^^DHCC<#elseif visit_data?? && visit_data[0]?? && visit_data[0].doctor_license_number??>${visit_data[0].doctor_license_number}^<#if visit_data[0].doc_last_name??>${visit_data[0].doc_last_name}</#if>^<#if visit_data[0].doc_first_name??>${visit_data[0].doc_first_name}</#if>^^^^^^DHCC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_start_date??>${presc_start_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = 'U^Usual control^NAB019' FROM interface_config_master icm WHERE segment_field_number = 'ORC_28' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "medicine_prescription">MED<#elseif item_type?? && item_type = "investigation"><#if is_lab>LAB<#else>RAD</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_29' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';

-- ORC segment template for OMP and RDS
UPDATE hl7_segment_template hst SET field_template = '<#if item_operation?? && item_operation = "insert">NW<#elseif item_operation?? && item_operation = "update">XO<#elseif item_operation?? && item_operation = "delete">CA<#elseif item_type?? && item_type = "investigation">RE</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'ORC_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && (item_type = "medicine_prescription" || item_type = "medicine_dispense")><#if item_operation?? && item_operation = "delete">CA<#else>CM</#if></#if><#if item_type?? && item_type = "investigation">CM</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if strength??>${strength}</#if>^<#if frequency??>${frequency}</#if>^<#if duration?? && duration_units??>${duration} <#if duration_units="D">Days<#elseif duration_units="W">Weeks<#elseif duration_units="M">Months</#if></#if>^<#if presc_start_date??>${presc_start_date?string("yyyyMMddHHmmss")}</#if>^<#if
presc_end_date??>${presc_end_date?string("yyyyMMddHHmmss")}</#if>^<#if priority??><#if priority="N">Regular<#elseif priority="P">PRN<#elseif priority="S">STAT<#elseif priority="U">Urgent</#if></#if>^^<#if medicine_remarks??>${medicine_remarks}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if prescribed_date??>${prescribed_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_doc_license_number?? && presc_doc_license_number != "">${presc_doc_license_number?string?replace("-","")}^<#if presc_doc_last_name??>${presc_doc_last_name}</#if>^<#if presc_doc_first_name??>${presc_doc_first_name}</#if>^^^^^^DHCC<#elseif ip_presc_doc_license_number?? && ip_presc_doc_license_number != "">${ip_presc_doc_license_number?string?replace("-","")}^<#if ip_presc_doc_last_name??>${ip_presc_doc_last_name}</#if>^<#if ip_presc_doc_first_name??>${ip_presc_doc_first_name}</#if>^^^^^^DHCC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_start_date??>${presc_start_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = 'U^Usual control^NAB019' FROM interface_config_master icm WHERE segment_field_number = 'ORC_28' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if item_type?? && item_type = "medicine_prescription">MED<#elseif item_type?? && item_type = "investigation"><#if is_lab>LAB<#else>RAD</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_29' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';

-- ORC segment template for VXU
UPDATE hl7_segment_template hst SET field_template = 'RE' FROM interface_config_master icm WHERE segment_field_number = 'ORC_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if pat_vacc_id??>${pat_vacc_id}^^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if pat_vacc_id??>${pat_vacc_id}^^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = 'CM' FROM interface_config_master icm WHERE segment_field_number = 'ORC_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '^^^<#if vaccination_datetime??>${vaccination_datetime?string("yyyyMMddHHmmss")}^<#if vaccination_datetime??>${vaccination_datetime?string("yyyyMMddHHmmss")}</#if>^</#if>^^<#if vaccine_remarks??>${vaccine_remarks}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if vaccination_datetime??>${vaccination_datetime?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'ORC_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if vacc_doc_license_number??>${vacc_doc_license_number?string?replace("-","")}^<#if vacc_doc_last_name??>${vacc_doc_last_name}</#if>^<#if vacc_doc_first_name??>${vacc_doc_first_name}</#if>^^^^^^DHCC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ORC_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = 'U^Usual control^NAB019' FROM interface_config_master icm WHERE segment_field_number = 'ORC_28' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = 'VXU' FROM interface_config_master icm WHERE segment_field_number = 'ORC_29' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';

-- OBR segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_presc_id??>${patient_presc_id}^^<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if test_code??>${test_code}^${test_name}^C4</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if is_lab><#if sample_date??>${sample_date?string("yyyyMMddHHmmss")}</#if><#else><#if signoff_date??>${signoff_date?string("yyyyMMddHHmmss")}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if is_lab && sample_date??>${sample_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if is_lab && sample_type??>${sample_type}</#if>^^^^^^P&Patient&<#if sending_facility??>${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if presc_doc_license_number??>${presc_doc_license_number}^<#if presc_doc_last_name??>${presc_doc_last_name}</#if>^<#if presc_doc_first_name??>${presc_doc_first_name}</#if>^^^^^^&<#if sending_facility??>${sending_facility}-DHCC</#if><#elseif visit_data?? && visit_data[0]?? && visit_data[0].doctor_license_number??>${visit_data[0].doctor_license_number}^<#if visit_data[0].doc_last_name??>${visit_data[0].doc_last_name}</#if>^<#if visit_data[0].doc_first_name??>${visit_data[0].doc_first_name}</#if>^^^^^^&<#if sending_facility??>${sending_facility}-DHCC</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_date??>${signoff_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_22' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.diagnostics_departments??><#if diag_dept_id?? && code.nabidh.diagnostics_departments[diag_dept_id?string]??><#assign obr_24 = code.nabidh.diagnostics_departments[diag_dept_id?string]><#elseif code.nabidh.diagnostics_departments.default??><#assign obr_24 = code.nabidh.diagnostics_departments.default></#if></#if><#if obr_24??>${obr_24}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_24' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_reverted?? && signoff_reverted>C<#else>F</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_25' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if tp_modified_by_doctor_id?? && tp_modified_by_doctor_id !=""><#assign obr32_1 = tp_modified_by_doc_license_number><#assign obr32_2 = tp_modified_by_doc_last_name><#assign obr32_3 = tp_modified_by_doc_first_name><#else><#assign obr32_1 = tp_modified_by_employee_id><#assign obr32_2 = tp_modified_by_user_last_name><#assign obr32_3 = tp_modified_by_user_first_name></#if><#if obr32_1??>${obr32_1}^${obr32_2}^${obr32_3}^^^^^^&<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBR_32' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- OBX segment template for ORU
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = 'ST' FROM interface_config_master icm WHERE segment_field_number = 'OBX_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V"><#if result_code?? && result_code != "">${result_code}<#else>${resultlabel_id}</#if>^<#if result_label_name??>${result_label_name}</#if>^<#if sending_facility??>${sending_facility}</#if><#else><#if test_code??>${test_code}^${test_name}^C4</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V">${result_value}<#else>${patient_report_file?string?replace("\n","<br>")?replace("\r","<br>")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V"><#if units?? && units != "">${units}^${units}^${sending_facility}<#else>.</#if><#else>.</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V" && min_normal_value?? && max_normal_value??>${min_normal_value}-${max_normal_value}<#else>0.00000-0.00000</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_format?? && conduction_format = "V"><#if severity?? && severity = "Normal">N<#elseif severity?? && (severity = "Abnormal Low" || severity = "Abnormal High")>A<#elseif severity?? && (severity = "Critical Low" || severity = "Critical High")>AA<#elseif severity?? && (severity = "Improbable Low")>LL<#elseif severity?? && (severity = "Improbable High")>HH</#if><#else>N</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_reverted?? && signoff_reverted>C<#else>F</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if conduction_start_date??>${conduction_start_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if tp_modified_by_doctor_id?? && tp_modified_by_doctor_id !=""><#assign obx16_1 = tp_modified_by_doc_license_number><#assign obx16_2 = tp_modified_by_doc_last_name><#assign obx16_3 = tp_modified_by_doc_first_name><#else><#assign obx16_1 = tp_modified_by_employee_id><#assign obx16_2 = tp_modified_by_user_last_name><#assign obx16_3 = tp_modified_by_user_first_name></#if><#if obx16_1??>${obx16_1}^${obx16_2}^${obx16_3}^^^^^^&<#if sending_facility??>${sending_facility}</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if signoff_date??>${signoff_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';
UPDATE hl7_segment_template hst SET field_template = '<#if center_name??>${center_name}</#if>^Facility^$<#if center_service_reg_no??>{center_service_reg_no}</#if>^^^DHCC' FROM interface_config_master icm WHERE segment_field_number = 'OBX_23' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ORU';

-- OBX segment template for ADT message
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.vital_parameter_master??><#if param_id?? && code.nabidh.vital_parameter_master[param_id?string]??><#assign obx3_1 = code.nabidh.vital_parameter_master[param_id?string]></#if></#if><#if obx3_1?? && obx3_1 != "">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = 'NM' FROM interface_config_master icm WHERE segment_field_number = 'OBX_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = '<#if code?? && code.nabidh?? && code.nabidh.vital_parameter_master??><#if param_id?? && code.nabidh.vital_parameter_master[param_id?string]??><#assign obx3_1 = code.nabidh.vital_parameter_master[param_id?string]><#elseif code.nabidh.vital_parameter_master.default??><#assign obx3_1 = code.nabidh.vital_parameter_master.default></#if></#if><#if code_desc?? && code_desc.nabidh?? && code_desc.nabidh.vital_parameter_master??><#if param_id?? && code_desc.nabidh.vital_parameter_master[param_id?string]??><#assign obx3_2 = code_desc.nabidh.vital_parameter_master[param_id?string]><#elseif code_desc.nabidh.vital_parameter_master.default??><#assign obx3_2 = code_desc.nabidh.vital_parameter_master.default></#if></#if><#if obx3_1??>${obx3_1}^<#if obx3_2??>${obx3_2}</#if>^^^^N</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = '<#if param_value??>${param_value}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = '<#if reference_range_txt??>${reference_range_txt}<#else>0</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = '<#if param_value?? && max_critical_value?? && min_critical_value?? && (((param_value?number) > (min_critical_value?number)) && ((param_value?number)) < (max_critical_value?number))>C<#elseif param_value?? && max_improbable_value?? && min_improbable_value?? && (((param_value?number) > (min_improbable_value?number)) && ((param_value?number)) < (max_improbable_value?number))>I<#else>N</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = 'O' FROM interface_config_master icm WHERE segment_field_number = 'OBX_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = '<#if vital_date_time??>${vital_date_time?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';
UPDATE hl7_segment_template hst SET field_template = '<#if center_name??>${center_name}</#if>^Facility^$<#if center_service_reg_no??>{center_service_reg_no}</#if>^^^DHCC' FROM interface_config_master icm WHERE segment_field_number = 'OBX_23' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_ADT';

-- OBX segment template for MDM message
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = 'ED' FROM interface_config_master icm WHERE segment_field_number = 'OBX_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if form_type??><#if form_type="Form_CONS">OE^Outpatient Encounter - Summary^NAB035<#elseif form_type="Form_IP">IP<#elseif form_type="Form_DIS">DS^Discharge Summary^NAB035<#elseif form_type="Form_OT">OP^Operative Report^NAB035</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'OBX_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if form_pdf_data??>^^PDF^Base64^${form_pdf_data}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'OBX_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '.' FROM interface_config_master icm WHERE segment_field_number = 'OBX_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = 'Base64' FROM interface_config_master icm WHERE segment_field_number = 'OBX_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = 'N' FROM interface_config_master icm WHERE segment_field_number = 'OBX_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = 'O' FROM interface_config_master icm WHERE segment_field_number = 'OBX_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '${date_time}' FROM interface_config_master icm WHERE segment_field_number = 'OBX_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if center_name??>${center_name}</#if>^Facility^<#if center_service_reg_no??>${center_service_reg_no}</#if>^^^DHCC' FROM interface_config_master icm WHERE segment_field_number = 'OBX_23' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';

-- RXO segment template for OMP and RDS
UPDATE hl7_segment_template hst SET field_template = '<#if medicine_ha_code??>${medicine_ha_code}^<#if medicine_name??>${medicine_name}</#if>^DDC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if strength??>${strength}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if cons_uom_id??>${cons_uom_id}^${consumption_uom}^${sending_facility}<#else>1^One Unit^RAMICENTER</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if item_form_id?? && code?? && code.nabidh??><#if code.nabidh.item_form_master??><#if code.nabidh.item_form_master[item_form_id?string]??><#assign rxo4_1 = code.nabidh.item_form_master[item_form_id?string]><#elseif code.nabidh.item_form_master.default??><#assign rxo4_1 = code.nabidh.item_form_master.default></#if></#if><#if code_desc.nabidh.item_form_master??><#if code_desc.nabidh.item_form_master[item_form_id?string]??><#assign rxo4_2 = code_desc.nabidh.item_form_master[item_form_id?string]><#elseif code_desc.nabidh.item_form_master.default??><#assign rxo4_2 = code_desc.nabidh.item_form_master.default></#if></#if></#if><#if rxo4_1??>${rxo4_1}^<#if rxo4_2??>${rxo4_2}</#if>^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if route_id?? && code?? && code.nabidh??><#if code.nabidh.medicine_route??><#if code.nabidh.medicine_route[route_id?string]??><#assign rxo7_1 = code.nabidh.medicine_route[route_id?string]><#elseif code.nabidh.medicine_route.default??><#assign rxo7_1 = code.nabidh.medicine_route.default></#if></#if><#if code_desc.nabidh.medicine_route??><#if code_desc.nabidh.medicine_route[route_id?string]??><#assign rxo7_2 = code_desc.nabidh.medicine_route[route_id?string]><#elseif code_desc.nabidh.medicine_route.default??><#assign rxo7_2 = code_desc.nabidh.medicine_route.default></#if></#if></#if><#if rxo7_1??>${rxo7_1}^${rxo7_2}^NAB022</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'RXO_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'RXO_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if refills??>${refills}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXO_13' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';

-- RXA segment template for VXU
UPDATE hl7_segment_template hst SET field_template = '1' FROM interface_config_master icm WHERE segment_field_number = 'RXA_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '1' FROM interface_config_master icm WHERE segment_field_number = 'RXA_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if vaccination_datetime??>${vaccination_datetime?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if vaccination_datetime??>${vaccination_datetime?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if medicine_ha_code??>${medicine_ha_code}^<#if medicine_name??>${medicine_name}</#if>^DDC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if medicine_quantity??>${medicine_quantity}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if cons_uom_id??>${cons_uom_id}^${consumption_uom}^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if item_form_id?? && code?? && code.nabidh??><#if code.nabidh.item_form_master??><#if code.nabidh.item_form_master[item_form_id?string]??><#assign rxo4_1 = code.nabidh.item_form_master[item_form_id?string]><#elseif code.nabidh.item_form_master.default??><#assign rxo4_1 = code.nabidh.item_form_master.default></#if></#if><#if code_desc.nabidh.item_form_master??><#if code_desc.nabidh.item_form_master[item_form_id?string]??><#assign rxo4_2 = code_desc.nabidh.item_form_master[item_form_id?string]><#elseif code_desc.nabidh.item_form_master.default??><#assign rxo4_2 = code_desc.nabidh.item_form_master.default></#if></#if></#if><#if rxo4_1??>${rxo4_1}^<#if rxo4_2??>${rxo4_2}</#if>^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_8' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if vaccine_remarks??>${vaccine_remarks}<#else>NA</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if medicine_quantity??>${medicine_quantity}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_13' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if cons_uom_id??>${cons_uom_id}^${consumption_uom}^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_14' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if batch??>${batch}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_15' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if expiry_date??>${expiry_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = 'CP' FROM interface_config_master icm WHERE segment_field_number = 'RXA_20' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if vacc_last_updated_date??>${vacc_last_updated_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXA_22' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';

-- RXR segment template for OMP and RDS
UPDATE hl7_segment_template hst SET field_template = '<#if route_name?? && route_name != "">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXR_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';
UPDATE hl7_segment_template hst SET field_template = '<#if route_id?? && code?? && code.nabidh??><#if code.nabidh.medicine_route??><#if code.nabidh.medicine_route[route_id?string]??><#assign rxr1_1 = code.nabidh.medicine_route[route_id?string]><#elseif code.nabidh.medicine_route.default??><#assign rxr1_1 = code.nabidh.medicine_route.default></#if></#if><#if code_desc.nabidh.medicine_route??><#if code_desc.nabidh.medicine_route[route_id?string]??><#assign rxr1_2 = code_desc.nabidh.medicine_route[route_id?string]><#elseif code_desc.nabidh.medicine_route.default??><#assign rxr1_2 = code_desc.nabidh.medicine_route.default></#if></#if></#if><#if rxr1_1??>${rxr1_1}^${rxr1_2}^NAB022</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXR_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_OMP_RDS';

-- RXR segment template for VXU
UPDATE hl7_segment_template hst SET field_template = '<#if route_name?? && route_name != "">true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXR_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if route_of_admin?? && code?? && code.nabidh??><#if code.nabidh.medicine_route??><#if code.nabidh.medicine_route[route_of_admin?string]??><#assign rxr1_1 = code.nabidh.medicine_route[route_of_admin?string]><#elseif code.nabidh.medicine_route.default??><#assign rxr1_1 = code.nabidh.medicine_route.default></#if></#if><#if code_desc.nabidh.medicine_route??><#if code_desc.nabidh.medicine_route[route_of_admin?string]??><#assign rxr1_2 = code_desc.nabidh.medicine_route[route_of_admin?string]><#elseif code_desc.nabidh.medicine_route.default??><#assign rxr1_2 = code_desc.nabidh.medicine_route.default></#if></#if></#if><#if rxr1_1??>${rxr1_1}^${rxr1_2}^NAB022</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXR_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';
UPDATE hl7_segment_template hst SET field_template = '<#if site_id?? && code?? && code.nabidh??><#if code.nabidh.iv_infusionsites??><#if code.nabidh.iv_infusionsites[site_id?string]??><#assign rxr1_1 = code.nabidh.iv_infusionsites[site_id?string]><#elseif code.nabidh.iv_infusionsites.default??><#assign rxr1_1 = code.nabidh.iv_infusionsites.default></#if></#if><#if code_desc.nabidh.iv_infusionsites??><#if code_desc.nabidh.iv_infusionsites[site_id?string]??><#assign rxr1_2 = code_desc.nabidh.iv_infusionsites[site_id?string]><#elseif code_desc.nabidh.iv_infusionsites.default??><#assign rxr1_2 = code_desc.nabidh.iv_infusionsites.default></#if></#if></#if><#if rxr1_1??>${rxr1_1}^${rxr1_2}^NAB023</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXR_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_VXU';

-- RXD segment template
UPDATE hl7_segment_template hst SET field_template = '<#if medicine_ha_code??>${medicine_ha_code}</#if>^<#if medicine_name??>${medicine_name}</#if>^DOHDRUG' FROM interface_config_master icm WHERE segment_field_number = 'RXD_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sale_date??>${sale_date?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if issued_qty??>${issued_qty}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if sale_unit?? && sale_unit = "I"><#assign rxd5_1 = uom_id"U"><#assign rxd5_2 = issue_units><#else><#assign rxd5_1 = uom_id"P"><#assign rxd5_2 = package_uom></#if><#if rxd5_1?? && rxd5_2??>$${rxd5_1}^${rxd5_2}^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if item_form_id??>${item_form_id}^${item_form_name}^${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_6' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if ph_user_employee_id?? && ph_user_first_name?? && ph_user_last_name??>${ph_user_employee_id}^${ph_user_last_name}^${ph_user_first_name}^^^^^^&${sending_facility}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'RXD_10' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- ZSC segment template
UPDATE hl7_segment_template hst SET field_template = '<#if patient_consent??>true<#elseif patient_data?? && patient_data[0]?? && patient_data[0].patient_group?? && (patient_data[0].patient_group?number=1 || patient_data[0].patient_group?number=2 || patient_data[0].patient_group?number=3 || patient_data[0].patient_group?number=4)>true</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ZSC_0' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_consent?? && patient_data?? && patient_data[0]?? && patient_data[0].vip_status?? && patient_data[0].vip_status = "Y"><#elseif patient_consent??>${patient_consent}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ZSC_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if consent_timestamp?? && patient_data?? && patient_data[0]?? && patient_data[0].vip_status?? && patient_data[0].vip_status = "Y"><#elseif consent_timestamp??>${consent_timestamp?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ZSC_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_data?? && patient_data[0]?? && ((patient_data[0].vip_status?? && patient_data[0].vip_status = "Y") || (patient_data[0].patient_group?? && (patient_data[0].patient_group?number=1 || patient_data[0].patient_group?number=2 || patient_data[0].patient_group?number=3 || patient_data[0].patient_group?number=4)))>1</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ZSC_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
UPDATE hl7_segment_template hst SET field_template = '<#if patient_data?? && patient_data[0]?? && ((patient_data[0].vip_status?? && patient_data[0].vip_status = "Y") || (patient_data[0].patient_group?? && (patient_data[0].patient_group?number=1 || patient_data[0].patient_group?number=2 || patient_data[0].patient_group?number=3 || patient_data[0].patient_group?number=4)))>${patient_data[0].last_updated_date_time?string("yyyyMMddHHmmss")}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'ZSC_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';

-- TXA segment template
UPDATE hl7_segment_template hst SET field_template = '<#if sequence??>${sequence}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_1' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if form_type??><#if form_type="Form_CONS">OE<#elseif form_type="Form_IP">DS<#elseif form_type="Form_DIS">DS<#elseif form_type="Form_OT">OP</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_2' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'TXA_3' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if form_type??><#if form_type="Form_CONS" && consultation_complete_time??>${consultation_complete_time?string("yyyyMMddHHmmss")}<#elseif form_type="Form_IP" && ipemr_complete_time??>${ipemr_complete_time?string("yyyyMMddHHmmss")}<#elseif form_type="Form_DIS" && discharge_finalized_date?? && discharge_finalized_time??>${discharge_finalized_date?string("yyyyMMdd")}${discharge_finalized_time?string("HHmmss")}<#elseif form_type="Form_OT">pending</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_4' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if doctor_license_number?? && doctor_license_number!="">${doctor_license_number?replace("-","")}^<#if doc_first_name??>${doc_first_name}</#if>^<#if doc_last_name??>${doc_last_name}</#if>^<#if doc_middle_name??>${doc_middle_name}</#if>^^Dr.^^^DHCC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if date_time??>${date_time}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if doc_first_name?? && doc_last_name?? && doctor_license_number?? && sending_facility??>${doctor_license_number}^${doc_last_name}^${doc_first_name}^^^^^^DHCC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_9' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'TXA_11' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if form_type??><#if form_type="Form_CONS" && consultation_id??>OE-${consultation_id}<#elseif form_type="Form_IP" && patient_id??>${patient_id}<#elseif form_type="Form_DIS" && patient_id??>DS-${patient_id}<#elseif form_type="Form_OT">wait</#if></#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_12' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'TXA_13' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if form_type?? && form_type="Form_CONS">OE_${consultation_id}<#elseif form_type?? && form_type="Form_IP">DS_${visit_id}<#elseif form_type?? && form_type="Form_DIS">DS_${visit_id}<#elseif form_type?? && form_type="Form_OT">OP_${operation_proc_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_16' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = 'AU' FROM interface_config_master icm WHERE segment_field_number = 'TXA_17' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = 'AV' FROM interface_config_master icm WHERE segment_field_number = 'TXA_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '' FROM interface_config_master icm WHERE segment_field_number = 'TXA_21' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';
UPDATE hl7_segment_template hst SET field_template = '<#if doctor_license_number?? && doctor_license_number!="">${doctor_license_number?replace("-","")}^<#if doc_first_name??>${doc_first_name}</#if>^<#if doc_last_name??>${doc_last_name}</#if>^<#if doc_middle_name??>${doc_middle_name}</#if>^^Dr.^^^DHCC</#if>' FROM interface_config_master icm WHERE segment_field_number = 'TXA_22' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_MDM';


