
--Patient Phone Number and Email Masking-----
UPDATE hl7_segment_template hst SET field_template = '<#if patient_phone??><#assign phone_mask=maskSensitiveData(patient_phone,"default","+999999999999")>${phone_mask}</#if>^PRN^CP<#if email_id??><#assign email_mask=maskSensitiveData(email_id,"default","abcd@sample.com")>~^NET^Internet^${email_mask}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_13' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
---------------------------------------------------------------------------------------------------------------------------
--Patient Name Masking-------------
UPDATE hl7_segment_template hst SET field_template = '<#if first_name?? && first_name!=""><#assign pat_first_name=maskSensitiveData(first_name?cap_first,"#")></#if><#if middle_name?? && middle_name!=""><#assign pat_middle_name=maskSensitiveData(middle_name?cap_first,"#")></#if><#if last_name?? && last_name!=""><#assign pat_last_name=maskSensitiveData(last_name?cap_first,"#")></#if><#if visit_data?? && visit_data[0]?? && visit_data[0].isbaby?? && visit_data[0].isbaby = "Y"><#if pat_first_name??>${pat_first_name}</#if><#if pat_middle_name??>${pat_middle_name}^<#assign baby=maskSensitiveData("Baby of","#")>${baby}^^^^^D<#else><#assign Baby=maskSensitiveData("Baby","#")>${Baby}</#if><#else><#if pat_first_name??>${pat_first_name}</#if>^<#if pat_last_name??>${pat_last_name}</#if>^<#if pat_middle_name??>${pat_middle_name}</#if>^^^^D</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_5' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
----------------------------------------------------------------------------------------------------------------------
--Patient Date of birth masking----
UPDATE hl7_segment_template hst SET field_template = '<#if date_of_birth??><#assign dob=maskSensitiveData(date_of_birth?date?string("yyyyMMdd"),"default","19000101")>${dob}<#elseif expected_date_of_birth??><#assign edob=maskSensitiveData(expected_date_of_birth?date?string("yyyyMMdd"),"default","19000101")>${edob}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_7' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
--------------------------------------------------------------------------------------------------------------------------
--Patient EmaratiID masking--------
UPDATE hl7_segment_template hst SET field_template = '<#if visit_data?? && visit_data[0]?? && visit_data[0].isbaby?? && visit_data[0].isbaby = "Y">111111111111111<#elseif government_identifier??><#assign govt_id=maskSensitiveData(government_identifier?replace("-",""),"1")>${govt_id}<#else>999999999999999</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_19' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
---------------------------------------------------------------------------------------------------------------------
UPDATE hl7_segment_template hst SET field_template = '<#if visit_data?? && visit_data[0]?? && visit_data[0].isbaby?? && visit_data[0].isbaby = "Y" && visit_data[0].parent_government_identifier??><#assign govt_id=maskSensitiveData(visit_data[0].parent_government_identifier?string?replace("-",""),"1")>${govt_id}</#if>' FROM interface_config_master icm WHERE segment_field_number = 'PID_21' AND hst.interface_id = icm.interface_id AND icm.interface_name like 'Nabidh_%';
