package com.insta.hms.mdm.diagtesttemplates;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TestTemplateMasterModel generated by hbm2java
 */
@Entity
@Table(name = "test_template_master")
public class TestTemplateMasterModel implements java.io.Serializable {

	private TestTemplateMasterIdSequence id;

	public TestTemplateMasterModel() {
	}

	public TestTemplateMasterModel(TestTemplateMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "testId", column = @Column(name = "test_id", length = 15)),
			@AttributeOverride(name = "formatName", column = @Column(name = "format_name", length = 20)) })
	public TestTemplateMasterIdSequence getId() {
		return this.id;
	}

	public void setId(TestTemplateMasterIdSequence id) {
		this.id = id;
	}

}
