package com.insta.hms.core.insurance;
// Generated 28 Aug, 2018 12:23:10 PM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.insta.hms.core.billing.BillChargeClaimModel;
import com.insta.hms.core.billing.BillChargeModel;
import com.insta.hms.core.billing.BillModel;
import com.insta.hms.integration.insurance.remittance.InsuranceRemittanceActivityDetailsModel;
import com.insta.hms.model.InsuranceSubmissionBatchModel;

import java.util.Set;

import com.fasterxml.jackson.annotation.JsonView;
import com.insta.hms.mdm.insuranceplans.InsurancePlanMainModel;
import com.insta.hms.util.ViewProfiles;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InsuranceClaim generated by hbm2java
 */
@Entity
@Table(name = "insurance_claim")
public class InsuranceClaimModel implements java.io.Serializable {

  @JsonIgnore
  private Set<InsuranceSubmissionBatchModel> insuranceSubmissionBatches;
  @JsonIgnore
  private Set<BillModel> bills;
  @JsonIgnore
  private Set<BillChargeClaimModel> billChargeClaims;
  @JsonIgnore
  private Set<BillChargeModel> billCharges;
  @JsonView(ViewProfiles.Public.class)
  private String claimId;
  @JsonView(ViewProfiles.Public.class)
  private String lastSubmissionBatchId;
  @JsonView(ViewProfiles.Public.class)
  private String payersReferenceNo;
  @JsonView(ViewProfiles.Public.class)
  private String mainVisitId;
  @JsonView(ViewProfiles.Public.class)
  private char status;
  @JsonView(ViewProfiles.Public.class)
  private int obsoleteResubmissionCount;
  @JsonView(ViewProfiles.Public.class)
  private Character closureType;
  @JsonView(ViewProfiles.Public.class)
  private String actionRemarks;
  @JsonView(ViewProfiles.Public.class)
  private byte[] attachment;
  @JsonView(ViewProfiles.Public.class)
  private String attachmentContentType;
  @JsonView(ViewProfiles.Public.class)
  private String resubmissionType;
  @JsonView(ViewProfiles.Public.class)
  private String comments;
  @JsonView(ViewProfiles.Public.class)
  private int accountGroup;
  @JsonView(ViewProfiles.Public.class)
  private String patientId;
  @JsonView(ViewProfiles.Public.class)
  private String opType;
  @JsonView(ViewProfiles.Public.class)
  private String denialRemarks;
  @JsonView(ViewProfiles.Public.class)
  private InsurancePlanMainModel planId;
  @JsonView(ViewProfiles.Public.class)
  private Integer rejectionReasonCategoryId;
  @JsonIgnore
  private Set<InsuranceRemittanceActivityDetailsModel> icrActivities;



  public InsuranceClaimModel() {
  }

  public InsuranceClaimModel(String claimId) {
    this.claimId = claimId;
  }

  public InsuranceClaimModel(String claimId, char status, int obsoleteResubmissionCount,
      int accountGroup, String patientId, String opType) {
    this.claimId = claimId;
    this.status = status;
    this.obsoleteResubmissionCount = obsoleteResubmissionCount;
    this.accountGroup = accountGroup;
    this.patientId = patientId;
    this.opType = opType;
  }

  @Id
  @Column(name = "claim_id", unique = true, nullable = false, length = 15)
  public String getClaimId() {
    return this.claimId;
  }

  public void setClaimId(String claimId) {
    this.claimId = claimId;
  }

  @Column(name = "last_submission_batch_id", length = 15)
  public String getLastSubmissionBatchId() {
    return this.lastSubmissionBatchId;
  }

  public void setLastSubmissionBatchId(String lastSubmissionBatchId) {
    this.lastSubmissionBatchId = lastSubmissionBatchId;
  }

  @Column(name = "payers_reference_no")
  public String getPayersReferenceNo() {
    return this.payersReferenceNo;
  }

  public void setPayersReferenceNo(String payersReferenceNo) {
    this.payersReferenceNo = payersReferenceNo;
  }

  @Column(name = "main_visit_id", length = 15)
  public String getMainVisitId() {
    return this.mainVisitId;
  }

  public void setMainVisitId(String mainVisitId) {
    this.mainVisitId = mainVisitId;
  }

  @Column(name = "status", nullable = false, length = 1)
  public char getStatus() {
    return this.status;
  }

  public void setStatus(char status) {
    this.status = status;
  }

  @Column(name = "obsolete_resubmission_count", nullable = false)
  public int getObsoleteResubmissionCount() {
    return this.obsoleteResubmissionCount;
  }

  public void setObsoleteResubmissionCount(int obsoleteResubmissionCount) {
    this.obsoleteResubmissionCount = obsoleteResubmissionCount;
  }

  @Column(name = "closure_type", length = 1)
  public Character getClosureType() {
    return this.closureType;
  }

  public void setClosureType(Character closureType) {
    this.closureType = closureType;
  }

  @Column(name = "action_remarks", length = 200)
  public String getActionRemarks() {
    return this.actionRemarks;
  }

  public void setActionRemarks(String actionRemarks) {
    this.actionRemarks = actionRemarks;
  }

  @Column(name = "attachment")
  public byte[] getAttachment() {
    return this.attachment;
  }

  public void setAttachment(byte[] attachment) {
    this.attachment = attachment;
  }

  @Column(name = "attachment_content_type")
  public String getAttachmentContentType() {
    return this.attachmentContentType;
  }

  public void setAttachmentContentType(String attachmentContentType) {
    this.attachmentContentType = attachmentContentType;
  }

  @Column(name = "resubmission_type", length = 50)
  public String getResubmissionType() {
    return this.resubmissionType;
  }

  public void setResubmissionType(String resubmissionType) {
    this.resubmissionType = resubmissionType;
  }

  @Column(name = "comments")
  public String getComments() {
    return this.comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  @Column(name = "account_group", nullable = false)
  public int getAccountGroup() {
    return this.accountGroup;
  }

  public void setAccountGroup(int accountGroup) {
    this.accountGroup = accountGroup;
  }

  @Column(name = "patient_id", nullable = false, length = 15)
  public String getPatientId() {
    return this.patientId;
  }

  public void setPatientId(String patientId) {
    this.patientId = patientId;
  }

  @Column(name = "op_type", nullable = false, length = 1)
  public String getOpType() {
    return this.opType;
  }

  public void setOpType(String opType) {
    this.opType = opType;
  }

  @Column(name = "denial_remarks", length = 200)
  public String getDenialRemarks() {
    return this.denialRemarks;
  }

  public void setDenialRemarks(String denialRemarks) {
    this.denialRemarks = denialRemarks;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "plan_id", nullable = false, insertable = false, updatable = false)
  public InsurancePlanMainModel getPlanId() {
    return this.planId;
  }

  public void setPlanId(InsurancePlanMainModel planId) {
    this.planId = planId;
  }

  @Column(name = "rejection_reason_category_id")
  public Integer getRejectionReasonCategoryId() {
    return this.rejectionReasonCategoryId;
  }

  public void setRejectionReasonCategoryId(Integer rejectionReasonCategoryId) {
    this.rejectionReasonCategoryId = rejectionReasonCategoryId;
  }

  @ManyToMany(fetch = FetchType.LAZY, mappedBy = "insuranceClaims")
  public Set<InsuranceSubmissionBatchModel> getInsuranceSubmissionBatches() {
    return this.insuranceSubmissionBatches;
  }

  public void setInsuranceSubmissionBatches(
      Set<InsuranceSubmissionBatchModel> insuranceSubmissionBatches) {
    this.insuranceSubmissionBatches = insuranceSubmissionBatches;
  }
  
  @ManyToMany(fetch = FetchType.LAZY, mappedBy = "claims")
  public Set<BillModel> getBills() {
    return this.bills;
  }
  
  public void setBills(Set<BillModel> bills) {
    this.bills = bills;
  }
  
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "id.claimId")
  public Set<BillChargeClaimModel> getBillChargeClaims() {
    return this.billChargeClaims;
  }
  
  public void setBillChargeClaims(Set<BillChargeClaimModel> billChargeClaims) {
    this.billChargeClaims = billChargeClaims;
  }

  @ManyToMany(fetch = FetchType.LAZY, mappedBy = "claims")
  public Set<BillChargeModel> getBillCharges() {
    return billCharges;
  }

  public void setBillCharges(Set<BillChargeModel> billCharges) {
    this.billCharges = billCharges;
  }
  
  @OneToMany(fetch = FetchType.LAZY)
  @JoinColumn(name = "claim_id", insertable=false, updatable=false)
  public Set<InsuranceRemittanceActivityDetailsModel> getIcrActivities() {
    return icrActivities;
  }

  public void setIcrActivities(Set<InsuranceRemittanceActivityDetailsModel> icrActivities) {
    this.icrActivities = icrActivities;
  }

}
