package com.insta.hms.mdm.taxsubgroups;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ItemSubGroupsModel generated by hbm2java
 */
@Entity
@Table(name = "item_sub_groups", uniqueConstraints = @UniqueConstraint(columnNames = "subgroup_code"))
public class ItemSubGroupsModel implements java.io.Serializable {

	private int itemSubgroupId;
	private String itemSubgroupName;
	private Integer itemSubgroupDisplayOrder;
	private String subgroupCode;
	private int itemGroupId;
	private String status;

	public ItemSubGroupsModel() {
	}

	public ItemSubGroupsModel(int itemSubgroupId, String itemSubgroupName, String subgroupCode, int itemGroupId) {
		this.itemSubgroupId = itemSubgroupId;
		this.itemSubgroupName = itemSubgroupName;
		this.subgroupCode = subgroupCode;
		this.itemGroupId = itemGroupId;
	}

	public ItemSubGroupsModel(int itemSubgroupId, String itemSubgroupName, Integer itemSubgroupDisplayOrder,
			String subgroupCode, int itemGroupId, String status) {
		this.itemSubgroupId = itemSubgroupId;
		this.itemSubgroupName = itemSubgroupName;
		this.itemSubgroupDisplayOrder = itemSubgroupDisplayOrder;
		this.subgroupCode = subgroupCode;
		this.itemGroupId = itemGroupId;
		this.status = status;
	}

	@Id

	@Column(name = "item_subgroup_id", unique = true, nullable = false)
	public int getItemSubgroupId() {
		return this.itemSubgroupId;
	}

	public void setItemSubgroupId(int itemSubgroupId) {
		this.itemSubgroupId = itemSubgroupId;
	}

	@Column(name = "item_subgroup_name", nullable = false, length = 50)
	public String getItemSubgroupName() {
		return this.itemSubgroupName;
	}

	public void setItemSubgroupName(String itemSubgroupName) {
		this.itemSubgroupName = itemSubgroupName;
	}

	@Column(name = "item_subgroup_display_order")
	public Integer getItemSubgroupDisplayOrder() {
		return this.itemSubgroupDisplayOrder;
	}

	public void setItemSubgroupDisplayOrder(Integer itemSubgroupDisplayOrder) {
		this.itemSubgroupDisplayOrder = itemSubgroupDisplayOrder;
	}

	@Column(name = "subgroup_code", unique = true, nullable = false, length = 6)
	public String getSubgroupCode() {
		return this.subgroupCode;
	}

	public void setSubgroupCode(String subgroupCode) {
		this.subgroupCode = subgroupCode;
	}

	@Column(name = "item_group_id", nullable = false)
	public int getItemGroupId() {
		return this.itemGroupId;
	}

	public void setItemGroupId(int itemGroupId) {
		this.itemGroupId = itemGroupId;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
