package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocHvfTemplatesModel generated by hbm2java
 */
@Entity
@Table(name = "doc_hvf_templates")
public class DocHvfTemplatesModel implements java.io.Serializable {

	private int templateId;
	private String templateName;
	private String title;
	private boolean specialized;
	private char status;
	private String docType;
	private String deptName;
	private String accessRights;
	private String printTemplateName;
	private String docSeqPatternId;

	public DocHvfTemplatesModel() {
	}

	public DocHvfTemplatesModel(int templateId, String templateName, boolean specialized, char status, String docType,
			String deptName) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.specialized = specialized;
		this.status = status;
		this.docType = docType;
		this.deptName = deptName;
	}

	public DocHvfTemplatesModel(int templateId, String templateName, String title, boolean specialized, char status,
			String docType, String deptName, String accessRights, String printTemplateName, String docSeqPatternId) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.title = title;
		this.specialized = specialized;
		this.status = status;
		this.docType = docType;
		this.deptName = deptName;
		this.accessRights = accessRights;
		this.printTemplateName = printTemplateName;
		this.docSeqPatternId = docSeqPatternId;
	}

	@Id

	@Column(name = "template_id", unique = true, nullable = false)
	public int getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(int templateId) {
		this.templateId = templateId;
	}

	@Column(name = "template_name", nullable = false, length = 100)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "specialized", nullable = false)
	public boolean isSpecialized() {
		return this.specialized;
	}

	public void setSpecialized(boolean specialized) {
		this.specialized = specialized;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "doc_type", nullable = false)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "dept_name", nullable = false, length = 15)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "access_rights", length = 1)
	public String getAccessRights() {
		return this.accessRights;
	}

	public void setAccessRights(String accessRights) {
		this.accessRights = accessRights;
	}

	@Column(name = "print_template_name", length = 50)
	public String getPrintTemplateName() {
		return this.printTemplateName;
	}

	public void setPrintTemplateName(String printTemplateName) {
		this.printTemplateName = printTemplateName;
	}

	@Column(name = "doc_seq_pattern_id", length = 50)
	public String getDocSeqPatternId() {
		return this.docSeqPatternId;
	}

	public void setDocSeqPatternId(String docSeqPatternId) {
		this.docSeqPatternId = docSeqPatternId;
	}

}
