package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocPdfFormTemplatesModel generated by hbm2java
 */
@Entity
@Table(name = "doc_pdf_form_templates")
public class DocPdfFormTemplatesModel implements java.io.Serializable {

	private int templateId;
	private String templateName;
	private String docType;
	private boolean specialized;
	private char status;
	private byte[] templateContent;
	private String deptName;
	private String accessRights;
	private Character autoGenOp;
	private Character autoGenIp;
	private byte[] odtFile;
	private String userName;
	private Date modTime;

	public DocPdfFormTemplatesModel() {
	}

	public DocPdfFormTemplatesModel(int templateId, String templateName, String docType, boolean specialized, char status,
			byte[] templateContent, String deptName) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.docType = docType;
		this.specialized = specialized;
		this.status = status;
		this.templateContent = templateContent;
		this.deptName = deptName;
	}

	public DocPdfFormTemplatesModel(int templateId, String templateName, String docType, boolean specialized, char status,
			byte[] templateContent, String deptName, String accessRights, Character autoGenOp, Character autoGenIp,
			byte[] odtFile, String userName, Date modTime) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.docType = docType;
		this.specialized = specialized;
		this.status = status;
		this.templateContent = templateContent;
		this.deptName = deptName;
		this.accessRights = accessRights;
		this.autoGenOp = autoGenOp;
		this.autoGenIp = autoGenIp;
		this.odtFile = odtFile;
		this.userName = userName;
		this.modTime = modTime;
	}

	@Id

	@Column(name = "template_id", unique = true, nullable = false)
	public int getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(int templateId) {
		this.templateId = templateId;
	}

	@Column(name = "template_name", nullable = false, length = 100)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "doc_type", nullable = false)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "specialized", nullable = false)
	public boolean isSpecialized() {
		return this.specialized;
	}

	public void setSpecialized(boolean specialized) {
		this.specialized = specialized;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "template_content", nullable = false)
	public byte[] getTemplateContent() {
		return this.templateContent;
	}

	public void setTemplateContent(byte[] templateContent) {
		this.templateContent = templateContent;
	}

	@Column(name = "dept_name", nullable = false, length = 15)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "access_rights", length = 1)
	public String getAccessRights() {
		return this.accessRights;
	}

	public void setAccessRights(String accessRights) {
		this.accessRights = accessRights;
	}

	@Column(name = "auto_gen_op", length = 1)
	public Character getAutoGenOp() {
		return this.autoGenOp;
	}

	public void setAutoGenOp(Character autoGenOp) {
		this.autoGenOp = autoGenOp;
	}

	@Column(name = "auto_gen_ip", length = 1)
	public Character getAutoGenIp() {
		return this.autoGenIp;
	}

	public void setAutoGenIp(Character autoGenIp) {
		this.autoGenIp = autoGenIp;
	}

	@Column(name = "odt_file")
	public byte[] getOdtFile() {
		return this.odtFile;
	}

	public void setOdtFile(byte[] odtFile) {
		this.odtFile = odtFile;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

}
