package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocPrintConfigurationIdSequence generated by hbm2java
 */
@Embeddable
public class DocPrintConfigurationIdSequence implements java.io.Serializable {

	private String documentType;
	private Integer centerId;
	private Integer printerSettings;
	private String pageSettings;
	private String templateName;

	public DocPrintConfigurationIdSequence() {
	}

	public DocPrintConfigurationIdSequence(String documentType, Integer centerId, Integer printerSettings, String pageSettings,
			String templateName) {
		this.documentType = documentType;
		this.centerId = centerId;
		this.printerSettings = printerSettings;
		this.pageSettings = pageSettings;
		this.templateName = templateName;
	}

	@Column(name = "document_type", length = 100)
	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	@Column(name = "center_id")
	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	@Column(name = "printer_settings")
	public Integer getPrinterSettings() {
		return this.printerSettings;
	}

	public void setPrinterSettings(Integer printerSettings) {
		this.printerSettings = printerSettings;
	}

	@Column(name = "page_settings", length = 15)
	public String getPageSettings() {
		return this.pageSettings;
	}

	public void setPageSettings(String pageSettings) {
		this.pageSettings = pageSettings;
	}

	@Column(name = "template_name", length = 100)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocPrintConfigurationIdSequence))
			return false;
		DocPrintConfigurationIdSequence castOther = (DocPrintConfigurationIdSequence) other;

		return ((this.getDocumentType() == castOther.getDocumentType()) || (this.getDocumentType() != null
				&& castOther.getDocumentType() != null && this.getDocumentType().equals(castOther.getDocumentType())))
				&& ((this.getCenterId() == castOther.getCenterId()) || (this.getCenterId() != null
						&& castOther.getCenterId() != null && this.getCenterId().equals(castOther.getCenterId())))
				&& ((this.getPrinterSettings() == castOther.getPrinterSettings())
						|| (this.getPrinterSettings() != null && castOther.getPrinterSettings() != null
								&& this.getPrinterSettings().equals(castOther.getPrinterSettings())))
				&& ((this.getPageSettings() == castOther.getPageSettings())
						|| (this.getPageSettings() != null && castOther.getPageSettings() != null
								&& this.getPageSettings().equals(castOther.getPageSettings())))
				&& ((this.getTemplateName() == castOther.getTemplateName())
						|| (this.getTemplateName() != null && castOther.getTemplateName() != null
								&& this.getTemplateName().equals(castOther.getTemplateName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDocumentType() == null ? 0 : this.getDocumentType().hashCode());
		result = 37 * result + (getCenterId() == null ? 0 : this.getCenterId().hashCode());
		result = 37 * result + (getPrinterSettings() == null ? 0 : this.getPrinterSettings().hashCode());
		result = 37 * result + (getPageSettings() == null ? 0 : this.getPageSettings().hashCode());
		result = 37 * result + (getTemplateName() == null ? 0 : this.getTemplateName().hashCode());
		return result;
	}

}
