package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HvfPrintTemplateIdSequence generated by hbm2java
 */
@Embeddable
public class HvfPrintTemplateIdSequence implements java.io.Serializable {

	private String templateName;
	private String hvfTemplateContent;
	private String userName;
	private String reason;
	private Character templateMode;

	public HvfPrintTemplateIdSequence() {
	}

	public HvfPrintTemplateIdSequence(String templateName) {
		this.templateName = templateName;
	}

	public HvfPrintTemplateIdSequence(String templateName, String hvfTemplateContent, String userName, String reason,
			Character templateMode) {
		this.templateName = templateName;
		this.hvfTemplateContent = hvfTemplateContent;
		this.userName = userName;
		this.reason = reason;
		this.templateMode = templateMode;
	}

	@Column(name = "template_name", nullable = false, length = 50)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "hvf_template_content")
	public String getHvfTemplateContent() {
		return this.hvfTemplateContent;
	}

	public void setHvfTemplateContent(String hvfTemplateContent) {
		this.hvfTemplateContent = hvfTemplateContent;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "reason", length = 500)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "template_mode", length = 1)
	public Character getTemplateMode() {
		return this.templateMode;
	}

	public void setTemplateMode(Character templateMode) {
		this.templateMode = templateMode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HvfPrintTemplateIdSequence))
			return false;
		HvfPrintTemplateIdSequence castOther = (HvfPrintTemplateIdSequence) other;

		return ((this.getTemplateName() == castOther.getTemplateName()) || (this.getTemplateName() != null
				&& castOther.getTemplateName() != null && this.getTemplateName().equals(castOther.getTemplateName())))
				&& ((this.getHvfTemplateContent() == castOther.getHvfTemplateContent())
						|| (this.getHvfTemplateContent() != null && castOther.getHvfTemplateContent() != null
								&& this.getHvfTemplateContent().equals(castOther.getHvfTemplateContent())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getReason() == castOther.getReason()) || (this.getReason() != null
						&& castOther.getReason() != null && this.getReason().equals(castOther.getReason())))
				&& ((this.getTemplateMode() == castOther.getTemplateMode())
						|| (this.getTemplateMode() != null && castOther.getTemplateMode() != null
								&& this.getTemplateMode().equals(castOther.getTemplateMode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTemplateName() == null ? 0 : this.getTemplateName().hashCode());
		result = 37 * result + (getHvfTemplateContent() == null ? 0 : this.getHvfTemplateContent().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getReason() == null ? 0 : this.getReason().hashCode());
		result = 37 * result + (getTemplateMode() == null ? 0 : this.getTemplateMode().hashCode());
		return result;
	}

}
