package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientRegistrationCardsModel generated by hbm2java
 */
@Entity
@Table(name = "patient_registration_cards")
public class PatientRegistrationCardsModel implements java.io.Serializable {

	private PatientRegistrationCardsIdSequence id;

	public PatientRegistrationCardsModel() {
	}

	public PatientRegistrationCardsModel(PatientRegistrationCardsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "patientId", column = @Column(name = "patient_id", length = 15)),
			@AttributeOverride(name = "docId", column = @Column(name = "doc_id")),
			@AttributeOverride(name = "docDate", column = @Column(name = "doc_date", length = 13)),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 50)),
			@AttributeOverride(name = "docName", column = @Column(name = "doc_name")) })
	public PatientRegistrationCardsIdSequence getId() {
		return this.id;
	}

	public void setId(PatientRegistrationCardsIdSequence id) {
		this.id = id;
	}

}
