package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PatientPdfDocImagesModel generated by hbm2java
 */
@Entity
@Table(name = "patient_pdf_doc_images", uniqueConstraints = @UniqueConstraint(columnNames = { "doc_id", "field_id" }))
public class PatientPdfDocImagesModel implements java.io.Serializable {

	private int docImageId;
	private int docId;
	private int fieldId;
	private byte[] fieldImage;
	private String fieldImageContentType;
	private String deviceIp;
	private String deviceInfo;
	private Date captureTime;
	private String username;

	public PatientPdfDocImagesModel() {
	}

	public PatientPdfDocImagesModel(int docImageId, int docId, int fieldId) {
		this.docImageId = docImageId;
		this.docId = docId;
		this.fieldId = fieldId;
	}

	public PatientPdfDocImagesModel(int docImageId, int docId, int fieldId, byte[] fieldImage, String fieldImageContentType,
			String deviceIp, String deviceInfo, Date captureTime, String username) {
		this.docImageId = docImageId;
		this.docId = docId;
		this.fieldId = fieldId;
		this.fieldImage = fieldImage;
		this.fieldImageContentType = fieldImageContentType;
		this.deviceIp = deviceIp;
		this.deviceInfo = deviceInfo;
		this.captureTime = captureTime;
		this.username = username;
	}

	@Id

	@Column(name = "doc_image_id", unique = true, nullable = false)
	public int getDocImageId() {
		return this.docImageId;
	}

	public void setDocImageId(int docImageId) {
		this.docImageId = docImageId;
	}

	@Column(name = "doc_id", nullable = false)
	public int getDocId() {
		return this.docId;
	}

	public void setDocId(int docId) {
		this.docId = docId;
	}

	@Column(name = "field_id", nullable = false)
	public int getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(int fieldId) {
		this.fieldId = fieldId;
	}

	@Column(name = "field_image")
	public byte[] getFieldImage() {
		return this.fieldImage;
	}

	public void setFieldImage(byte[] fieldImage) {
		this.fieldImage = fieldImage;
	}

	@Column(name = "field_image_content_type", length = 100)
	public String getFieldImageContentType() {
		return this.fieldImageContentType;
	}

	public void setFieldImageContentType(String fieldImageContentType) {
		this.fieldImageContentType = fieldImageContentType;
	}

	@Column(name = "device_ip", length = 50)
	public String getDeviceIp() {
		return this.deviceIp;
	}

	public void setDeviceIp(String deviceIp) {
		this.deviceIp = deviceIp;
	}

	@Column(name = "device_info")
	public String getDeviceInfo() {
		return this.deviceInfo;
	}

	public void setDeviceInfo(String deviceInfo) {
		this.deviceInfo = deviceInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "capture_time", length = 29)
	public Date getCaptureTime() {
		return this.captureTime;
	}

	public void setCaptureTime(Date captureTime) {
		this.captureTime = captureTime;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
