package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientPdfFormDocValuesModel generated by hbm2java
 */
@Entity
@Table(name = "patient_pdf_form_doc_values")
public class PatientPdfFormDocValuesModel implements java.io.Serializable {

	private PatientPdfFormDocValuesIdSequence id;

	public PatientPdfFormDocValuesModel() {
	}

	public PatientPdfFormDocValuesModel(PatientPdfFormDocValuesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "docId", column = @Column(name = "doc_id", nullable = false)),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name", nullable = false, length = 100)),
			@AttributeOverride(name = "fieldValue", column = @Column(name = "field_value")),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 30)) })
	public PatientPdfFormDocValuesIdSequence getId() {
		return this.id;
	}

	public void setId(PatientPdfFormDocValuesIdSequence id) {
		this.id = id;
	}

}
