package com.insta.hms.documents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RegistrationCardsModel generated by hbm2java
 */
@Entity
@Table(name = "registration_cards")
public class RegistrationCardsModel implements java.io.Serializable {

	private RegistrationCardsIdSequence id;

	public RegistrationCardsModel() {
	}

	public RegistrationCardsModel(RegistrationCardsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cardId", column = @Column(name = "card_id", nullable = false)),
			@AttributeOverride(name = "cardName", column = @Column(name = "card_name", nullable = false, length = 50)),
			@AttributeOverride(name = "visitType", column = @Column(name = "visit_type", nullable = false, length = 1)),
			@AttributeOverride(name = "ratePlan", column = @Column(name = "rate_plan", nullable = false, length = 50)),
			@AttributeOverride(name = "customRegCardTemplate", column = @Column(name = "custom_reg_card_template")),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 1)),
			@AttributeOverride(name = "odtFile", column = @Column(name = "odt_file")),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 50)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)) })
	public RegistrationCardsIdSequence getId() {
		return this.id;
	}

	public void setId(RegistrationCardsIdSequence id) {
		this.id = id;
	}

}
