package com.insta.hms.mdm.patientheaderpreferences;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientHeaderPreferencesModel generated by hbm2java
 */
@Entity
@Table(name = "patient_header_preferences")
public class PatientHeaderPreferencesModel implements java.io.Serializable {

	private PatientHeaderPreferencesIdSequence id;

	public PatientHeaderPreferencesModel() {
	}

	public PatientHeaderPreferencesModel(PatientHeaderPreferencesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "fieldName", column = @Column(name = "field_name", length = 100)),
			@AttributeOverride(name = "display", column = @Column(name = "display", length = 1)),
			@AttributeOverride(name = "dataLevel", column = @Column(name = "data_level", length = 1)),
			@AttributeOverride(name = "fieldDesc", column = @Column(name = "field_desc", length = 500)),
			@AttributeOverride(name = "visitType", column = @Column(name = "visit_type", length = 1)),
			@AttributeOverride(name = "dataCategory", column = @Column(name = "data_category", length = 20)),
			@AttributeOverride(name = "displayOrder", column = @Column(name = "display_order", nullable = false)),
			@AttributeOverride(name = "dataType", column = @Column(name = "data_type", length = 200)) })
	public PatientHeaderPreferencesIdSequence getId() {
		return this.id;
	}

	public void setId(PatientHeaderPreferencesIdSequence id) {
		this.id = id;
	}

}
