package com.insta.hms.integration;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.centers.HospitalCenterMasterModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CenterIntegrationDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "center_integration_details", uniqueConstraints = @UniqueConstraint(columnNames = {
    "center_id", "integration_id" }))
public class CenterIntegrationDetailsModel implements java.io.Serializable {

  private int centerIntegrationId;
  private InstaIntegrationModel InstaIntegrationModel;
  private HospitalCenterMasterModel HospitalCenterMasterModel;
  private String establishmentKey;
  private String aeskey;
  private String merchantId;
  private String storeCode;

  public CenterIntegrationDetailsModel() {
  }

  public CenterIntegrationDetailsModel(int centerIntegrationId) {
    this.centerIntegrationId = centerIntegrationId;
  }

  public CenterIntegrationDetailsModel(int centerIntegrationId,
      InstaIntegrationModel InstaIntegrationModel,
      HospitalCenterMasterModel HospitalCenterMasterModel, String establishmentKey, String aeskey,
      String merchantId, String storeCode) {
    this.centerIntegrationId = centerIntegrationId;
    this.InstaIntegrationModel = InstaIntegrationModel;
    this.HospitalCenterMasterModel = HospitalCenterMasterModel;
    this.establishmentKey = establishmentKey;
    this.aeskey = aeskey;
    this.merchantId = merchantId;
    this.storeCode = storeCode;
  }

  @Id

  @Column(name = "center_integration_id", unique = true, nullable = false)
  public int getCenterIntegrationId() {
    return this.centerIntegrationId;
  }

  public void setCenterIntegrationId(int centerIntegrationId) {
    this.centerIntegrationId = centerIntegrationId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "integration_id")
  public InstaIntegrationModel getInstaIntegrationModel() {
    return this.InstaIntegrationModel;
  }

  public void setInstaIntegrationModel(InstaIntegrationModel InstaIntegrationModel) {
    this.InstaIntegrationModel = InstaIntegrationModel;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "center_id")
  public HospitalCenterMasterModel getHospitalCenterMasterModel() {
    return this.HospitalCenterMasterModel;
  }

  public void setHospitalCenterMasterModel(HospitalCenterMasterModel HospitalCenterMasterModel) {
    this.HospitalCenterMasterModel = HospitalCenterMasterModel;
  }

  @Column(name = "establishment_key", length = 100)
  public String getEstablishmentKey() {
    return this.establishmentKey;
  }

  public void setEstablishmentKey(String establishmentKey) {
    this.establishmentKey = establishmentKey;
  }

  @Column(name = "aeskey", length = 50)
  public String getAeskey() {
    return this.aeskey;
  }

  public void setAeskey(String aeskey) {
    this.aeskey = aeskey;
  }

  @Column(name = "merchant_id", length = 50)
  public String getMerchantId() {
    return this.merchantId;
  }

  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }

  @Column(name = "store_code", length = 50)
  public String getStoreCode() {
    return this.storeCode;
  }

  public void setStoreCode(String storeCode) {
    this.storeCode = storeCode;
  }

}
