//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB), v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 10:15:15 PM IST 
//

package com.insta.hms.integration.patientsync;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * 
 * <p>Java class for anonymous complex type.</p>
 * 
 * 
 * <p>The following schema fragment specifies the expected content contained within
 * this class.</p>
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="old_mr_no">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="first_name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="middle_name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="last_name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="gender">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="date_of_birth" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="nationality_id" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="government_identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mobile_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[^@]+@[^\.]+\..+"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="custom_list2_value" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="custom_list3_value">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="custom_field15" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="passport_number" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "oldMrNo", "firstName", "middleName",
    "lastName", "gender", "dateOfBirth", "nationalityId",
    "governmentIdentifier", "mobileNumber", "email", "customList2Value",
    "customList3Value", "customField15", "passportNumber" })
@XmlRootElement(name = "patient_details")
public class PatientDetails {

  @XmlElement(name = "old_mr_no", required = true)
  protected String oldMrNo;
  @XmlElement(name = "first_name", required = true)
  protected String firstName;
  @XmlElement(name = "middle_name")
  protected String middleName;
  @XmlElement(name = "last_name")
  protected String lastName;
  @XmlElement(required = true)
  protected PatientDetails.Gender gender;
  @XmlElement(name = "date_of_birth", required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dateOfBirth;
  @XmlElement(name = "nationality_id")
  protected PatientDetails.NationalityId nationalityId;
  @XmlElement(name = "government_identifier", required = true)
  protected String governmentIdentifier;
  @XmlElement(name = "mobile_number")
  protected String mobileNumber;
  protected String email;
  @XmlElement(name = "custom_list2_value")
  protected PatientDetails.CustomList2Value customList2Value;
  @XmlElement(name = "custom_list3_value", required = true)
  protected PatientDetails.CustomList3Value customList3Value;
  @XmlElement(name = "custom_field15")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar customField15;
  @XmlElement(name = "passport_number")
  protected String passportNumber;

  /**
   * Gets the value of the oldMrNo property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOldMrNo() {
    return oldMrNo;
  }

  /**
   * Sets the value of the oldMrNo property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setOldMrNo(String value) {
    this.oldMrNo = value;
  }

  /**
   * Gets the value of the firstName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the firstName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setFirstName(String value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the middleName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getMiddleName() {
    return middleName;
  }

  /**
   * Sets the value of the middleName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setMiddleName(String value) {
    this.middleName = value;
  }

  /**
   * Gets the value of the lastName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the lastName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setLastName(String value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the gender property.
   * 
   * @return possible object is {@link PatientDetails.Gender }
   * 
   */
  public PatientDetails.Gender getGender() {
    return gender;
  }

  /**
   * Sets the value of the gender property.
   * 
   * @param value
   *          allowed object is {@link PatientDetails.Gender }
   * 
   */
  public void setGender(PatientDetails.Gender value) {
    this.gender = value;
  }

  /**
   * Gets the value of the dateOfBirth property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getDateOfBirth() {
    return dateOfBirth;
  }

  /**
   * Sets the value of the dateOfBirth property.
   * 
   * @param value
   *          allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setDateOfBirth(XMLGregorianCalendar value) {
    this.dateOfBirth = value;
  }

  /**
   * Gets the value of the nationalityId property.
   * 
   * @return possible object is {@link PatientDetails.NationalityId }
   * 
   */
  public PatientDetails.NationalityId getNationalityId() {
    return nationalityId;
  }

  /**
   * Sets the value of the nationalityId property.
   * 
   * @param value
   *          allowed object is {@link PatientDetails.NationalityId }
   * 
   */
  public void setNationalityId(PatientDetails.NationalityId value) {
    this.nationalityId = value;
  }

  /**
   * Gets the value of the governmentIdentifier property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getGovernmentIdentifier() {
    return governmentIdentifier;
  }

  /**
   * Sets the value of the governmentIdentifier property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setGovernmentIdentifier(String value) {
    this.governmentIdentifier = value;
  }

  /**
   * Gets the value of the mobileNumber property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getMobileNumber() {
    return mobileNumber;
  }

  /**
   * Sets the value of the mobileNumber property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setMobileNumber(String value) {
    this.mobileNumber = value;
  }

  /**
   * Gets the value of the email property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEmail() {
    return email;
  }

  /**
   * Sets the value of the email property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setEmail(String value) {
    this.email = value;
  }

  /**
   * Gets the value of the customList2Value property.
   * 
   * @return possible object is {@link PatientDetails.CustomList2Value }
   * 
   */
  public PatientDetails.CustomList2Value getCustomList2Value() {
    return customList2Value;
  }

  /**
   * Sets the value of the customList2Value property.
   * 
   * @param value
   *          allowed object is {@link PatientDetails.CustomList2Value }
   * 
   */
  public void setCustomList2Value(PatientDetails.CustomList2Value value) {
    this.customList2Value = value;
  }

  /**
   * Gets the value of the customList3Value property.
   * 
   * @return possible object is {@link PatientDetails.CustomList3Value }
   * 
   */
  public PatientDetails.CustomList3Value getCustomList3Value() {
    return customList3Value;
  }

  /**
   * Sets the value of the customList3Value property.
   * 
   * @param value
   *          allowed object is {@link PatientDetails.CustomList3Value }
   * 
   */
  public void setCustomList3Value(PatientDetails.CustomList3Value value) {
    this.customList3Value = value;
  }

  /**
   * Gets the value of the customField15 property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getCustomField15() {
    return customField15;
  }

  /**
   * Sets the value of the customField15 property.
   * 
   * @param value
   *          allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setCustomField15(XMLGregorianCalendar value) {
    this.customField15 = value;
  }

  /**
   * Gets the value of the passportNumber property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPassportNumber() {
    return passportNumber;
  }

  /**
   * Sets the value of the passportNumber property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setPassportNumber(String value) {
    this.passportNumber = value;
  }

  /**
   * 
   * <p>Java class for anonymous complex type.</p>
   * 
   * 
   * <p>The following schema fragment specifies the expected content contained
   * within this class.</p>
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "code", "description" })
  public static class CustomList2Value {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the code property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCode() {
      return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCode(String value) {
      this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
      return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
      this.description = value;
    }

  }

  /**
   * 
   * <p>Java class for anonymous complex type.</p>
   * 
   * 
   * <p>The following schema fragment specifies the expected content contained
   * within this class.</p>
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "code", "description" })
  public static class CustomList3Value {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the code property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCode() {
      return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCode(String value) {
      this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
      return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
      this.description = value;
    }

  }

  /**
   * 
   * <p>Java class for anonymous complex type.</p>
   * 
   * 
   * <p>The following schema fragment specifies the expected content contained
   * within this class.</p>
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "code", "description" })
  public static class Gender {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the code property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCode() {
      return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCode(String value) {
      this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
      return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
      this.description = value;
    }

  }

  /**
   * 
   * <p>Java class for anonymous complex type.</p>
   * 
   * 
   * <p>The following schema fragment specifies the expected content contained
   * within this class.</p>
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "code", "description" })
  public static class NationalityId {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the code property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCode() {
      return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCode(String value) {
      this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
      return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
      this.description = value;
    }

  }

}
