package com.insta.hms.mdm.govtidentifiers;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GovtIdentifierMasterModel generated by hbm2java
 */
@Entity
@Table(name = "govt_identifier_master", uniqueConstraints = @UniqueConstraint(columnNames = "identifier_type"))
public class GovtIdentifierMasterModel implements java.io.Serializable {

	private int identifierId;
	private String identifierType;
	private String remarks;
	private String status;
	private Character uniqueId;
	private Character defaultOption;
	private String govtIdPattern;
	private Character valueMandatory;

	public GovtIdentifierMasterModel() {
	}

	public GovtIdentifierMasterModel(int identifierId) {
		this.identifierId = identifierId;
	}

	public GovtIdentifierMasterModel(int identifierId, String identifierType, String remarks, String status,
			Character uniqueId, Character defaultOption, String govtIdPattern, Character valueMandatory) {
		this.identifierId = identifierId;
		this.identifierType = identifierType;
		this.remarks = remarks;
		this.status = status;
		this.uniqueId = uniqueId;
		this.defaultOption = defaultOption;
		this.govtIdPattern = govtIdPattern;
		this.valueMandatory = valueMandatory;
	}

	@Id

	@Column(name = "identifier_id", unique = true, nullable = false)
	public int getIdentifierId() {
		return this.identifierId;
	}

	public void setIdentifierId(int identifierId) {
		this.identifierId = identifierId;
	}

	@Column(name = "identifier_type", unique = true, length = 100)
	public String getIdentifierType() {
		return this.identifierType;
	}

	public void setIdentifierType(String identifierType) {
		this.identifierType = identifierType;
	}

	@Column(name = "remarks", length = 200)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "unique_id", length = 1)
	public Character getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(Character uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Column(name = "default_option", length = 1)
	public Character getDefaultOption() {
		return this.defaultOption;
	}

	public void setDefaultOption(Character defaultOption) {
		this.defaultOption = defaultOption;
	}

	@Column(name = "govt_id_pattern", length = 100)
	public String getGovtIdPattern() {
		return this.govtIdPattern;
	}

	public void setGovtIdPattern(String govtIdPattern) {
		this.govtIdPattern = govtIdPattern;
	}

	@Column(name = "value_mandatory", length = 1)
	public Character getValueMandatory() {
		return this.valueMandatory;
	}

	public void setValueMandatory(Character valueMandatory) {
		this.valueMandatory = valueMandatory;
	}

}
