package com.insta.hms.core.clinical.dischargesummary;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DisDetailIdSequence generated by hbm2java
 */
@Embeddable
public class DisDetailIdSequence implements java.io.Serializable {

  private String docdetailId;
  private Integer docId;
  private String fieldId;
  private String fieldValue;

  public DisDetailIdSequence() {}

  public DisDetailIdSequence(String docdetailId, Integer docId, String fieldId, String fieldValue) {
    this.docdetailId = docdetailId;
    this.docId = docId;
    this.fieldId = fieldId;
    this.fieldValue = fieldValue;
  }

  @Column(name = "docdetail_id", length = 10)
  public String getDocdetailId() {
    return this.docdetailId;
  }

  public void setDocdetailId(String docdetailId) {
    this.docdetailId = docdetailId;
  }

  @Column(name = "doc_id")
  public Integer getDocId() {
    return this.docId;
  }

  public void setDocId(Integer docId) {
    this.docId = docId;
  }

  @Column(name = "field_id", length = 10)
  public String getFieldId() {
    return this.fieldId;
  }

  public void setFieldId(String fieldId) {
    this.fieldId = fieldId;
  }

  @Column(name = "field_value")
  public String getFieldValue() {
    return this.fieldValue;
  }

  public void setFieldValue(String fieldValue) {
    this.fieldValue = fieldValue;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof DisDetailIdSequence))
      return false;
    DisDetailIdSequence castOther = (DisDetailIdSequence) other;

    return ((this.getDocdetailId() == castOther.getDocdetailId())
        || (this.getDocdetailId() != null && castOther.getDocdetailId() != null
            && this.getDocdetailId().equals(castOther.getDocdetailId())))
        && ((this.getDocId() == castOther.getDocId()) || (this.getDocId() != null
            && castOther.getDocId() != null && this.getDocId().equals(castOther.getDocId())))
        && ((this.getFieldId() == castOther.getFieldId()) || (this.getFieldId() != null
            && castOther.getFieldId() != null && this.getFieldId().equals(castOther.getFieldId())))
        && ((this.getFieldValue() == castOther.getFieldValue())
            || (this.getFieldValue() != null && castOther.getFieldValue() != null
                && this.getFieldValue().equals(castOther.getFieldValue())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getDocdetailId() == null ? 0 : this.getDocdetailId().hashCode());
    result = 37 * result + (getDocId() == null ? 0 : this.getDocId().hashCode());
    result = 37 * result + (getFieldId() == null ? 0 : this.getFieldId().hashCode());
    result = 37 * result + (getFieldValue() == null ? 0 : this.getFieldValue().hashCode());
    return result;
  }

}
