package com.insta.hms.core.clinical.dischargesummary;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DisHeaderModel generated by hbm2java
 */
@Entity
@Table(name = "dis_header")
public class DisHeaderModel implements java.io.Serializable {

  private DisHeaderIdSequence id;

  public DisHeaderModel() {}

  public DisHeaderModel(DisHeaderIdSequence id) {
    this.id = id;
  }

  @EmbeddedId

  @AttributeOverrides({@AttributeOverride(name = "docid", column = @Column(name = "docid")),
      @AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", length = 15)),
      @AttributeOverride(name = "patientId", column = @Column(name = "patient_id", length = 15)),
      @AttributeOverride(name = "formId", column = @Column(name = "form_id", length = 10)),
      @AttributeOverride(name = "disDate", column = @Column(name = "dis_date", length = 13)),
      @AttributeOverride(name = "username", column = @Column(name = "username", length = 50))})
  public DisHeaderIdSequence getId() {
    return this.id;
  }

  public void setId(DisHeaderIdSequence id) {
    this.id = id;
  }

}
