package com.insta.hms.core.clinical.order.dietitems;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DietPrescribedModel generated by hbm2java
 */
@Entity
@Table(name = "diet_prescribed")
public class DietPrescribedModel implements java.io.Serializable {

	private int orderedId;
	private BigDecimal dietId;
	private String visitId;
	private String orderedBy;
	private Date orderedTime;
	private String mealTiming;
	private Date mealTime;
	private String specialInstructions;
	private String status;
	private Date statusUpdatedTime;
	private String statusUpdatedBy;
	private Integer dietPresId;
	private Date mealDate;
	private Integer commonOrderId;
	private String userName;
	private Integer packageRef;

	public DietPrescribedModel() {
	}

	public DietPrescribedModel(int orderedId) {
		this.orderedId = orderedId;
	}

	public DietPrescribedModel(int orderedId, BigDecimal dietId, String visitId, String orderedBy, Date orderedTime,
			String mealTiming, Date mealTime, String specialInstructions, String status, Date statusUpdatedTime,
			String statusUpdatedBy, Integer dietPresId, Date mealDate, Integer commonOrderId, String userName,
			Integer packageRef) {
		this.orderedId = orderedId;
		this.dietId = dietId;
		this.visitId = visitId;
		this.orderedBy = orderedBy;
		this.orderedTime = orderedTime;
		this.mealTiming = mealTiming;
		this.mealTime = mealTime;
		this.specialInstructions = specialInstructions;
		this.status = status;
		this.statusUpdatedTime = statusUpdatedTime;
		this.statusUpdatedBy = statusUpdatedBy;
		this.dietPresId = dietPresId;
		this.mealDate = mealDate;
		this.commonOrderId = commonOrderId;
		this.userName = userName;
		this.packageRef = packageRef;
	}

	@Id

	@Column(name = "ordered_id", unique = true, nullable = false)
	public int getOrderedId() {
		return this.orderedId;
	}

	public void setOrderedId(int orderedId) {
		this.orderedId = orderedId;
	}

	@Column(name = "diet_id", precision = 131089, scale = 0)
	public BigDecimal getDietId() {
		return this.dietId;
	}

	public void setDietId(BigDecimal dietId) {
		this.dietId = dietId;
	}

	@Column(name = "visit_id", length = 15)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Column(name = "ordered_by", length = 20)
	public String getOrderedBy() {
		return this.orderedBy;
	}

	public void setOrderedBy(String orderedBy) {
		this.orderedBy = orderedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ordered_time", length = 29)
	public Date getOrderedTime() {
		return this.orderedTime;
	}

	public void setOrderedTime(Date orderedTime) {
		this.orderedTime = orderedTime;
	}

	@Column(name = "meal_timing", length = 20)
	public String getMealTiming() {
		return this.mealTiming;
	}

	public void setMealTiming(String mealTiming) {
		this.mealTiming = mealTiming;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "meal_time", length = 15)
	public Date getMealTime() {
		return this.mealTime;
	}

	public void setMealTime(Date mealTime) {
		this.mealTime = mealTime;
	}

	@Column(name = "special_instructions")
	public String getSpecialInstructions() {
		return this.specialInstructions;
	}

	public void setSpecialInstructions(String specialInstructions) {
		this.specialInstructions = specialInstructions;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "status_updated_time", length = 29)
	public Date getStatusUpdatedTime() {
		return this.statusUpdatedTime;
	}

	public void setStatusUpdatedTime(Date statusUpdatedTime) {
		this.statusUpdatedTime = statusUpdatedTime;
	}

	@Column(name = "status_updated_by", length = 20)
	public String getStatusUpdatedBy() {
		return this.statusUpdatedBy;
	}

	public void setStatusUpdatedBy(String statusUpdatedBy) {
		this.statusUpdatedBy = statusUpdatedBy;
	}

	@Column(name = "diet_pres_id")
	public Integer getDietPresId() {
		return this.dietPresId;
	}

	public void setDietPresId(Integer dietPresId) {
		this.dietPresId = dietPresId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "meal_date", length = 13)
	public Date getMealDate() {
		return this.mealDate;
	}

	public void setMealDate(Date mealDate) {
		this.mealDate = mealDate;
	}

	@Column(name = "common_order_id")
	public Integer getCommonOrderId() {
		return this.commonOrderId;
	}

	public void setCommonOrderId(Integer commonOrderId) {
		this.commonOrderId = commonOrderId;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "package_ref")
	public Integer getPackageRef() {
		return this.packageRef;
	}

	public void setPackageRef(Integer packageRef) {
		this.packageRef = packageRef;
	}

}
