package com.insta.hms.security.usermanager;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * URoleModel generated by hbm2java
 */
@Entity
@Table(name = "u_role")
public class URoleModel implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private Character roleStatus;
	private Date roleSdate;
	private Date roleEdate;
	private String roleFlag;
	private String roleRemk;
	private Character portalId;
	private String statsItem1;
	private String statsItem2;
	private String statsItem3;
	private String statsItem4;
	private String statsItem5;
	private String statsItem6;
	private String statsItem7;
	private String statsItem8;
	private String statsItem9;
	private String statsItem10;
	private String statsItem11;
	private String statsItem12;
	private String modUser;
	private Date modDate;

	public URoleModel() {
	}

	public URoleModel(int roleId) {
		this.roleId = roleId;
	}

	public URoleModel(int roleId, String roleName, Character roleStatus, Date roleSdate, Date roleEdate, String roleFlag,
			String roleRemk, Character portalId, String statsItem1, String statsItem2, String statsItem3,
			String statsItem4, String statsItem5, String statsItem6, String statsItem7, String statsItem8,
			String statsItem9, String statsItem10, String statsItem11, String statsItem12, String modUser,
			Date modDate) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleStatus = roleStatus;
		this.roleSdate = roleSdate;
		this.roleEdate = roleEdate;
		this.roleFlag = roleFlag;
		this.roleRemk = roleRemk;
		this.portalId = portalId;
		this.statsItem1 = statsItem1;
		this.statsItem2 = statsItem2;
		this.statsItem3 = statsItem3;
		this.statsItem4 = statsItem4;
		this.statsItem5 = statsItem5;
		this.statsItem6 = statsItem6;
		this.statsItem7 = statsItem7;
		this.statsItem8 = statsItem8;
		this.statsItem9 = statsItem9;
		this.statsItem10 = statsItem10;
		this.statsItem11 = statsItem11;
		this.statsItem12 = statsItem12;
		this.modUser = modUser;
		this.modDate = modDate;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false, precision = 5, scale = 0)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", length = 25)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_status", length = 1)
	public Character getRoleStatus() {
		return this.roleStatus;
	}

	public void setRoleStatus(Character roleStatus) {
		this.roleStatus = roleStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "role_sdate", length = 13)
	public Date getRoleSdate() {
		return this.roleSdate;
	}

	public void setRoleSdate(Date roleSdate) {
		this.roleSdate = roleSdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "role_edate", length = 13)
	public Date getRoleEdate() {
		return this.roleEdate;
	}

	public void setRoleEdate(Date roleEdate) {
		this.roleEdate = roleEdate;
	}

	@Column(name = "role_flag", length = 10)
	public String getRoleFlag() {
		return this.roleFlag;
	}

	public void setRoleFlag(String roleFlag) {
		this.roleFlag = roleFlag;
	}

	@Column(name = "role_remk", length = 100)
	public String getRoleRemk() {
		return this.roleRemk;
	}

	public void setRoleRemk(String roleRemk) {
		this.roleRemk = roleRemk;
	}

	@Column(name = "portal_id", length = 1)
	public Character getPortalId() {
		return this.portalId;
	}

	public void setPortalId(Character portalId) {
		this.portalId = portalId;
	}

	@Column(name = "stats_item1", length = 80)
	public String getStatsItem1() {
		return this.statsItem1;
	}

	public void setStatsItem1(String statsItem1) {
		this.statsItem1 = statsItem1;
	}

	@Column(name = "stats_item2", length = 80)
	public String getStatsItem2() {
		return this.statsItem2;
	}

	public void setStatsItem2(String statsItem2) {
		this.statsItem2 = statsItem2;
	}

	@Column(name = "stats_item3", length = 80)
	public String getStatsItem3() {
		return this.statsItem3;
	}

	public void setStatsItem3(String statsItem3) {
		this.statsItem3 = statsItem3;
	}

	@Column(name = "stats_item4", length = 80)
	public String getStatsItem4() {
		return this.statsItem4;
	}

	public void setStatsItem4(String statsItem4) {
		this.statsItem4 = statsItem4;
	}

	@Column(name = "stats_item5", length = 80)
	public String getStatsItem5() {
		return this.statsItem5;
	}

	public void setStatsItem5(String statsItem5) {
		this.statsItem5 = statsItem5;
	}

	@Column(name = "stats_item6", length = 80)
	public String getStatsItem6() {
		return this.statsItem6;
	}

	public void setStatsItem6(String statsItem6) {
		this.statsItem6 = statsItem6;
	}

	@Column(name = "stats_item7", length = 80)
	public String getStatsItem7() {
		return this.statsItem7;
	}

	public void setStatsItem7(String statsItem7) {
		this.statsItem7 = statsItem7;
	}

	@Column(name = "stats_item8", length = 80)
	public String getStatsItem8() {
		return this.statsItem8;
	}

	public void setStatsItem8(String statsItem8) {
		this.statsItem8 = statsItem8;
	}

	@Column(name = "stats_item9", length = 80)
	public String getStatsItem9() {
		return this.statsItem9;
	}

	public void setStatsItem9(String statsItem9) {
		this.statsItem9 = statsItem9;
	}

	@Column(name = "stats_item10", length = 80)
	public String getStatsItem10() {
		return this.statsItem10;
	}

	public void setStatsItem10(String statsItem10) {
		this.statsItem10 = statsItem10;
	}

	@Column(name = "stats_item11", length = 80)
	public String getStatsItem11() {
		return this.statsItem11;
	}

	public void setStatsItem11(String statsItem11) {
		this.statsItem11 = statsItem11;
	}

	@Column(name = "stats_item12", length = 80)
	public String getStatsItem12() {
		return this.statsItem12;
	}

	public void setStatsItem12(String statsItem12) {
		this.statsItem12 = statsItem12;
	}

	@Column(name = "mod_user", length = 30)
	public String getModUser() {
		return this.modUser;
	}

	public void setModUser(String modUser) {
		this.modUser = modUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_date", length = 29)
	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

}
