package com.insta.hms.security.usermanager;
//Generated 28 Aug, 2018 12:23:10 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* UUser generated by hbm2java
*/
@Entity
@Table(name = "u_user")
public class UUserModel implements java.io.Serializable {

private String empUsername;
private String empPassword;
private Date empUsrsdate;
private Date empUsredate;
private String empUsrremk;
private String empStatus;
private int roleId;
private String counterId;
private String specializationId;
private String labDeptId;
private String pharmacyCounterId;
private String hospUser;
private String pharmacyStoreId;
private String tempUsername;
private Character type;
private String doctorId;
private String inventoryStoreId;
private Date lastLogin;
private BigDecimal totalLogin;
private String schedulerDeptId;
private char prescriptionNoteTaker;
private String schDefaultDoctor;
private String multiStore;
private String emailId;
private String mobileNo;
private String bedViewDefaultWard;
private String modUser;
private Date modDate;
private Character isSharedLogin;
private Integer sampleCollectionCenter;
private BigDecimal poApprovalUpto;
private int centerId;
private Character allowSigUsageByOthers;
private Date createdTimestamp;
private Date passwordChangeDate;
private Boolean isEncrypted;
private BigDecimal writeoffLimit;
private Integer discAuthId;
private String loginHandle;
private Character centerAssocType;
private Integer reportCenterId;
private String encryptAlgo;
private String nexusToken;

public UUserModel() {
}

public UUserModel(String empUsername) {
  this.empUsername = empUsername;
}

public UUserModel(String empUsername, String empPassword, int roleId, char prescriptionNoteTaker, int centerId,
   Date createdTimestamp) {
 this.empUsername = empUsername;
 this.empPassword = empPassword;
 this.roleId = roleId;
 this.prescriptionNoteTaker = prescriptionNoteTaker;
 this.centerId = centerId;
 this.createdTimestamp = createdTimestamp;
}

public UUserModel(String empUsername, String empPassword, Date empUsrsdate, Date empUsredate, String empUsrremk,
   String empStatus, int roleId, String counterId, String specializationId, String labDeptId,
   String pharmacyCounterId, String hospUser, String pharmacyStoreId, String tempUsername, Character type,
   String doctorId, String inventoryStoreId, Date lastLogin, BigDecimal totalLogin, String schedulerDeptId,
   char prescriptionNoteTaker, String schDefaultDoctor, String multiStore, String emailId, String mobileNo,
   String bedViewDefaultWard, String modUser, Date modDate, Character isSharedLogin,
   Integer sampleCollectionCenter, BigDecimal poApprovalUpto, int centerId, Character allowSigUsageByOthers,
   Date createdTimestamp, Date passwordChangeDate, Boolean isEncrypted, BigDecimal writeoffLimit,
   Integer discAuthId, String loginHandle, Character centerAssocType,
   Integer reportCenterId, String encryptAlgo, String nexusToken) {
 this.empUsername = empUsername;
 this.empPassword = empPassword;
 this.empUsrsdate = empUsrsdate;
 this.empUsredate = empUsredate;
 this.empUsrremk = empUsrremk;
 this.empStatus = empStatus;
 this.roleId = roleId;
 this.counterId = counterId;
 this.specializationId = specializationId;
 this.labDeptId = labDeptId;
 this.pharmacyCounterId = pharmacyCounterId;
 this.hospUser = hospUser;
 this.pharmacyStoreId = pharmacyStoreId;
 this.tempUsername = tempUsername;
 this.type = type;
 this.doctorId = doctorId;
 this.inventoryStoreId = inventoryStoreId;
 this.lastLogin = lastLogin;
 this.totalLogin = totalLogin;
 this.schedulerDeptId = schedulerDeptId;
 this.prescriptionNoteTaker = prescriptionNoteTaker;
 this.schDefaultDoctor = schDefaultDoctor;
 this.multiStore = multiStore;
 this.emailId = emailId;
 this.mobileNo = mobileNo;
 this.bedViewDefaultWard = bedViewDefaultWard;
 this.modUser = modUser;
 this.modDate = modDate;
 this.isSharedLogin = isSharedLogin;
 this.sampleCollectionCenter = sampleCollectionCenter;
 this.poApprovalUpto = poApprovalUpto;
 this.centerId = centerId;
 this.allowSigUsageByOthers = allowSigUsageByOthers;
 this.createdTimestamp = createdTimestamp;
 this.passwordChangeDate = passwordChangeDate;
 this.isEncrypted = isEncrypted;
 this.writeoffLimit = writeoffLimit;
 this.discAuthId = discAuthId;
 this.loginHandle = loginHandle;
 this.centerAssocType = centerAssocType;
 this.reportCenterId = reportCenterId;
 this.encryptAlgo = encryptAlgo;
 this.nexusToken = nexusToken;
}

@Id

@Column(name = "emp_username", unique = true, nullable = false, length = 30)
public String getEmpUsername() {
 return this.empUsername;
}

public void setEmpUsername(String empUsername) {
 this.empUsername = empUsername;
}

@Column(name = "emp_password", nullable = false, length = 100)
public String getEmpPassword() {
 return this.empPassword;
}

public void setEmpPassword(String empPassword) {
 this.empPassword = empPassword;
}

@Temporal(TemporalType.DATE)
@Column(name = "emp_usrsdate", length = 13)
public Date getEmpUsrsdate() {
 return this.empUsrsdate;
}

public void setEmpUsrsdate(Date empUsrsdate) {
 this.empUsrsdate = empUsrsdate;
}

@Temporal(TemporalType.DATE)
@Column(name = "emp_usredate", length = 13)
public Date getEmpUsredate() {
 return this.empUsredate;
}

public void setEmpUsredate(Date empUsredate) {
 this.empUsredate = empUsredate;
}

@Column(name = "emp_usrremk", length = 100)
public String getEmpUsrremk() {
 return this.empUsrremk;
}

public void setEmpUsrremk(String empUsrremk) {
 this.empUsrremk = empUsrremk;
}

@Column(name = "emp_status", length = 1)
public String getEmpStatus() {
 return this.empStatus;
}

public void setEmpStatus(String empStatus) {
 this.empStatus = empStatus;
}

@Column(name = "role_id", nullable = false, precision = 5, scale = 0)
public int getRoleId() {
 return this.roleId;
}

public void setRoleId(int roleId) {
 this.roleId = roleId;
}

@Column(name = "counter_id", length = 20)
public String getCounterId() {
 return this.counterId;
}

public void setCounterId(String counterId) {
 this.counterId = counterId;
}

@Column(name = "specialization_id", length = 20)
public String getSpecializationId() {
 return this.specializationId;
}

public void setSpecializationId(String specializationId) {
 this.specializationId = specializationId;
}

@Column(name = "lab_dept_id", length = 20)
public String getLabDeptId() {
 return this.labDeptId;
}

public void setLabDeptId(String labDeptId) {
 this.labDeptId = labDeptId;
}

@Column(name = "pharmacy_counter_id", length = 20)
public String getPharmacyCounterId() {
 return this.pharmacyCounterId;
}

public void setPharmacyCounterId(String pharmacyCounterId) {
 this.pharmacyCounterId = pharmacyCounterId;
}

@Column(name = "hosp_user", length = 1)
public String getHospUser() {
 return this.hospUser;
}

public void setHospUser(String hospUser) {
 this.hospUser = hospUser;
}

@Column(name = "pharmacy_store_id", length = 20)
public String getPharmacyStoreId() {
 return this.pharmacyStoreId;
}

public void setPharmacyStoreId(String pharmacyStoreId) {
 this.pharmacyStoreId = pharmacyStoreId;
}

@Column(name = "temp_username", length = 50)
public String getTempUsername() {
 return this.tempUsername;
}

public void setTempUsername(String tempUsername) {
 this.tempUsername = tempUsername;
}

@Column(name = "type", length = 1)
public Character getType() {
 return this.type;
}

public void setType(Character type) {
 this.type = type;
}

@Column(name = "doctor_id", length = 20)
public String getDoctorId() {
 return this.doctorId;
}

public void setDoctorId(String doctorId) {
 this.doctorId = doctorId;
}

@Column(name = "inventory_store_id", length = 20)
public String getInventoryStoreId() {
 return this.inventoryStoreId;
}

public void setInventoryStoreId(String inventoryStoreId) {
 this.inventoryStoreId = inventoryStoreId;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "last_login", length = 29)
public Date getLastLogin() {
 return this.lastLogin;
}

public void setLastLogin(Date lastLogin) {
 this.lastLogin = lastLogin;
}

@Column(name = "total_login", precision = 131089, scale = 0)
public BigDecimal getTotalLogin() {
 return this.totalLogin;
}

public void setTotalLogin(BigDecimal totalLogin) {
 this.totalLogin = totalLogin;
}

@Column(name = "scheduler_dept_id", length = 10)
public String getSchedulerDeptId() {
 return this.schedulerDeptId;
}

public void setSchedulerDeptId(String schedulerDeptId) {
 this.schedulerDeptId = schedulerDeptId;
}

@Column(name = "prescription_note_taker", nullable = false, length = 1)
public char getPrescriptionNoteTaker() {
 return this.prescriptionNoteTaker;
}

public void setPrescriptionNoteTaker(char prescriptionNoteTaker) {
 this.prescriptionNoteTaker = prescriptionNoteTaker;
}

@Column(name = "sch_default_doctor", length = 15)
public String getSchDefaultDoctor() {
 return this.schDefaultDoctor;
}

public void setSchDefaultDoctor(String schDefaultDoctor) {
 this.schDefaultDoctor = schDefaultDoctor;
}

@Column(name = "multi_store")
public String getMultiStore() {
 return this.multiStore;
}

public void setMultiStore(String multiStore) {
 this.multiStore = multiStore;
}

@Column(name = "email_id", length = 100)
public String getEmailId() {
 return this.emailId;
}

public void setEmailId(String emailId) {
 this.emailId = emailId;
}

@Column(name = "mobile_no", length = 15)
public String getMobileNo() {
 return this.mobileNo;
}

public void setMobileNo(String mobileNo) {
 this.mobileNo = mobileNo;
}

@Column(name = "bed_view_default_ward", length = 10)
public String getBedViewDefaultWard() {
 return this.bedViewDefaultWard;
}

public void setBedViewDefaultWard(String bedViewDefaultWard) {
 this.bedViewDefaultWard = bedViewDefaultWard;
}

@Column(name = "mod_user", length = 30)
public String getModUser() {
 return this.modUser;
}

public void setModUser(String modUser) {
 this.modUser = modUser;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "mod_date", length = 29)
public Date getModDate() {
 return this.modDate;
}

public void setModDate(Date modDate) {
 this.modDate = modDate;
}

@Column(name = "is_shared_login", length = 1)
public Character getIsSharedLogin() {
 return this.isSharedLogin;
}

public void setIsSharedLogin(Character isSharedLogin) {
 this.isSharedLogin = isSharedLogin;
}

@Column(name = "sample_collection_center")
public Integer getSampleCollectionCenter() {
 return this.sampleCollectionCenter;
}

public void setSampleCollectionCenter(Integer sampleCollectionCenter) {
 this.sampleCollectionCenter = sampleCollectionCenter;
}

@Column(name = "po_approval_upto", precision = 15)
public BigDecimal getPoApprovalUpto() {
 return this.poApprovalUpto;
}

public void setPoApprovalUpto(BigDecimal poApprovalUpto) {
 this.poApprovalUpto = poApprovalUpto;
}

@Column(name = "center_id", nullable = false)
public int getCenterId() {
 return this.centerId;
}

public void setCenterId(int centerId) {
 this.centerId = centerId;
}

@Column(name = "allow_sig_usage_by_others", length = 1)
public Character getAllowSigUsageByOthers() {
 return this.allowSigUsageByOthers;
}

public void setAllowSigUsageByOthers(Character allowSigUsageByOthers) {
 this.allowSigUsageByOthers = allowSigUsageByOthers;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "created_timestamp", nullable = false, length = 29)
public Date getCreatedTimestamp() {
 return this.createdTimestamp;
}

public void setCreatedTimestamp(Date createdTimestamp) {
 this.createdTimestamp = createdTimestamp;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "password_change_date", length = 29)
public Date getPasswordChangeDate() {
 return this.passwordChangeDate;
}

public void setPasswordChangeDate(Date passwordChangeDate) {
 this.passwordChangeDate = passwordChangeDate;
}

@Column(name = "is_encrypted")
public Boolean getIsEncrypted() {
 return this.isEncrypted;
}

public void setIsEncrypted(Boolean isEncrypted) {
 this.isEncrypted = isEncrypted;
}

@Column(name = "writeoff_limit", precision = 15)
public BigDecimal getWriteoffLimit() {
 return this.writeoffLimit;
}

public void setWriteoffLimit(BigDecimal writeoffLimit) {
 this.writeoffLimit = writeoffLimit;
}

@Column(name = "disc_auth_id")
public Integer getDiscAuthId() {
 return this.discAuthId;
}

public void setDiscAuthId(Integer discAuthId) {
 this.discAuthId = discAuthId;
}

@Column(name = "login_handle")
public String getLoginHandle() {
 return this.loginHandle;
}

public void setLoginHandle(String loginHandle) {
 this.loginHandle = loginHandle;
}

@Column(name = "center_assoc_type", length = 1)
public Character getCenterAssocType() {
 return this.centerAssocType;
}

public void setCenterAssocType(Character centerAssocType) {
 this.centerAssocType = centerAssocType;
}

@Column(name = "report_center_id")
public Integer getReportCenterId() {
 return this.reportCenterId;
}

public void setReportCenterId(Integer reportCenterId) {
 this.reportCenterId = reportCenterId;
}

@Column(name = "encrypt_algo", length = 100)
public String getEncryptAlgo() {
 return this.encryptAlgo;
}

public void setEncryptAlgo(String encryptAlgo) {
 this.encryptAlgo = encryptAlgo;
}

@Column(name = "nexus_token", length = 100)
public String getNexusToken() {
 return this.nexusToken;
}

public void setNexusToken(String nexusToken) {
 this.nexusToken = nexusToken;
}

}
