package com.insta.hms.mdm.services;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ServicesModel generated by hbm2java
 */
@Entity
@Table(name = "services", uniqueConstraints = @UniqueConstraint(columnNames = { "service_name", "serv_dept_id" }))
public class ServicesModel implements java.io.Serializable {

	private String serviceId;
	private String serviceName;
	private String units;
	private BigDecimal serviceTax;
	private String serviceCode;
	private Character status;
	private Boolean conductionApplicable;
	private Character specialization;
	private Integer servDeptId;
	private String username;
	private Integer serviceSubGroupId;
	private Character conductingDocMandatory;
	private Integer insuranceCategoryId;
	private Character priorAuthRequired;
	private boolean allowRateIncrease;
	private boolean allowRateDecrease;
	private String remarks;
	private Character toothNumRequired;
	private String docSpecialityId;
	private String conductingRoleId;
	private Character obsoleteConductingDoc;
	private String hl7ExportCode;
	private Set serviceMasterChargeses = new HashSet(0);
	private Set serviceOrgDetailses = new HashSet(0);

	public ServicesModel() {
	}

	public ServicesModel(String serviceId, String serviceName, boolean allowRateIncrease, boolean allowRateDecrease) {
		this.serviceId = serviceId;
		this.serviceName = serviceName;
		this.allowRateIncrease = allowRateIncrease;
		this.allowRateDecrease = allowRateDecrease;
	}

	public ServicesModel(String serviceId, String serviceName, String units, BigDecimal serviceTax, String serviceCode,
			Character status, Boolean conductionApplicable, Character specialization, Integer servDeptId,
			String username, Integer serviceSubGroupId, Character conductingDocMandatory, Integer insuranceCategoryId,
			Character priorAuthRequired, boolean allowRateIncrease, boolean allowRateDecrease, String remarks,
			Character toothNumRequired, String docSpecialityId, String conductingRoleId,
			Character obsoleteConductingDoc, String hl7ExportCode, Set serviceMasterChargeses,
			Set serviceOrgDetailses) {
		this.serviceId = serviceId;
		this.serviceName = serviceName;
		this.units = units;
		this.serviceTax = serviceTax;
		this.serviceCode = serviceCode;
		this.status = status;
		this.conductionApplicable = conductionApplicable;
		this.specialization = specialization;
		this.servDeptId = servDeptId;
		this.username = username;
		this.serviceSubGroupId = serviceSubGroupId;
		this.conductingDocMandatory = conductingDocMandatory;
		this.insuranceCategoryId = insuranceCategoryId;
		this.priorAuthRequired = priorAuthRequired;
		this.allowRateIncrease = allowRateIncrease;
		this.allowRateDecrease = allowRateDecrease;
		this.remarks = remarks;
		this.toothNumRequired = toothNumRequired;
		this.docSpecialityId = docSpecialityId;
		this.conductingRoleId = conductingRoleId;
		this.obsoleteConductingDoc = obsoleteConductingDoc;
		this.hl7ExportCode = hl7ExportCode;
		this.serviceMasterChargeses = serviceMasterChargeses;
		this.serviceOrgDetailses = serviceOrgDetailses;
	}

	@Id

	@Column(name = "service_id", unique = true, nullable = false, length = 10)
	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "service_name", nullable = false, length = 600)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "units", length = 20)
	public String getUnits() {
		return this.units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	@Column(name = "service_tax", precision = 15)
	public BigDecimal getServiceTax() {
		return this.serviceTax;
	}

	public void setServiceTax(BigDecimal serviceTax) {
		this.serviceTax = serviceTax;
	}

	@Column(name = "service_code", length = 50)
	public String getServiceCode() {
		return this.serviceCode;
	}

	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "conduction_applicable")
	public Boolean getConductionApplicable() {
		return this.conductionApplicable;
	}

	public void setConductionApplicable(Boolean conductionApplicable) {
		this.conductionApplicable = conductionApplicable;
	}

	@Column(name = "specialization", length = 1)
	public Character getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Character specialization) {
		this.specialization = specialization;
	}

	@Column(name = "serv_dept_id")
	public Integer getServDeptId() {
		return this.servDeptId;
	}

	public void setServDeptId(Integer servDeptId) {
		this.servDeptId = servDeptId;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "service_sub_group_id")
	public Integer getServiceSubGroupId() {
		return this.serviceSubGroupId;
	}

	public void setServiceSubGroupId(Integer serviceSubGroupId) {
		this.serviceSubGroupId = serviceSubGroupId;
	}

	@Column(name = "conducting_doc_mandatory", length = 1)
	public Character getConductingDocMandatory() {
		return this.conductingDocMandatory;
	}

	public void setConductingDocMandatory(Character conductingDocMandatory) {
		this.conductingDocMandatory = conductingDocMandatory;
	}

	@Column(name = "insurance_category_id")
	public Integer getInsuranceCategoryId() {
		return this.insuranceCategoryId;
	}

	public void setInsuranceCategoryId(Integer insuranceCategoryId) {
		this.insuranceCategoryId = insuranceCategoryId;
	}

	@Column(name = "prior_auth_required", length = 1)
	public Character getPriorAuthRequired() {
		return this.priorAuthRequired;
	}

	public void setPriorAuthRequired(Character priorAuthRequired) {
		this.priorAuthRequired = priorAuthRequired;
	}

	@Column(name = "allow_rate_increase", nullable = false)
	public boolean isAllowRateIncrease() {
		return this.allowRateIncrease;
	}

	public void setAllowRateIncrease(boolean allowRateIncrease) {
		this.allowRateIncrease = allowRateIncrease;
	}

	@Column(name = "allow_rate_decrease", nullable = false)
	public boolean isAllowRateDecrease() {
		return this.allowRateDecrease;
	}

	public void setAllowRateDecrease(boolean allowRateDecrease) {
		this.allowRateDecrease = allowRateDecrease;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "tooth_num_required", length = 1)
	public Character getToothNumRequired() {
		return this.toothNumRequired;
	}

	public void setToothNumRequired(Character toothNumRequired) {
		this.toothNumRequired = toothNumRequired;
	}

	@Column(name = "doc_speciality_id", length = 10)
	public String getDocSpecialityId() {
		return this.docSpecialityId;
	}

	public void setDocSpecialityId(String docSpecialityId) {
		this.docSpecialityId = docSpecialityId;
	}

	@Column(name = "conducting_role_id")
	public String getConductingRoleId() {
		return this.conductingRoleId;
	}

	public void setConductingRoleId(String conductingRoleId) {
		this.conductingRoleId = conductingRoleId;
	}

	@Column(name = "obsolete_conducting_doc", length = 1)
	public Character getObsoleteConductingDoc() {
		return this.obsoleteConductingDoc;
	}

	public void setObsoleteConductingDoc(Character obsoleteConductingDoc) {
		this.obsoleteConductingDoc = obsoleteConductingDoc;
	}

	@Column(name = "hl7_export_code")
	public String getHl7ExportCode() {
		return this.hl7ExportCode;
	}

	public void setHl7ExportCode(String hl7ExportCode) {
		this.hl7ExportCode = hl7ExportCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set getServiceMasterChargeses() {
		return this.serviceMasterChargeses;
	}

	public void setServiceMasterChargeses(Set serviceMasterChargeses) {
		this.serviceMasterChargeses = serviceMasterChargeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set getServiceOrgDetailses() {
		return this.serviceOrgDetailses;
	}

	public void setServiceOrgDetailses(Set serviceOrgDetailses) {
		this.serviceOrgDetailses = serviceOrgDetailses;
	}

}
