package com.insta.hms.mdm.doctors;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.departments.DepartmentModel;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DoctorsModel generated by hbm2java
 */
@Entity
@Table(name = "doctors")
public class DoctorsModel implements java.io.Serializable {

	private String doctorId;
	private String doctorName;
	private String specialization;
	private String doctorType;
	private String doctorAddress;
	private String doctorMobile;
	private String doctorMailId;
	private BigDecimal opConsultationValidity;
	private Character status;
	private DepartmentModel deptId;
	private Character otDoctorFlag;
	private Character consultingDoctorFlag;
	private Boolean schedule;
	private String qualification;
	private String registrationNo;
	private String resPhone;
	private String clinicPhone;
	private BigDecimal paymentCategory;
	private Character paymentEligible;
	private String doctorLicenseNumber;
	private Integer allowedRevisitCount;
	private String customField1Value;
	private String customField2Value;
	private String customField3Value;
	private String customField4Value;
	private String customField5Value;
	private int opTemplateId;
	private Integer serviceSubGroupId;
	private BigDecimal ipDischargeConsultationValidity;
	private Integer ipDischargeConsultationCount;
	private int ipTemplateId;
	private Boolean obsoleteOverbook;
	private String practitionType;
	private char allowSigUsageByOthers;
	private Date createdTimestamp;
	private Date updatedTimestamp;
	private Integer centerIdObsolete;
	private String dhpoClinicianUserId;
	private String dhpoClinicianPassword;
	private String specialityId;
	private String chanelling;
	private Character prescribeByFavourites;
	private String doctorMobileCountryCode;
	private Integer overbookLimit;
	//private Set doctorConsultationCharges = new HashSet(0);

	public DoctorsModel() {
	}

	public DoctorsModel(String doctorId, String doctorName, String doctorType, int opTemplateId, int ipTemplateId,
			char allowSigUsageByOthers, Date createdTimestamp, Date updatedTimestamp) {
		this.doctorId = doctorId;
		this.doctorName = doctorName;
		this.doctorType = doctorType;
		this.opTemplateId = opTemplateId;
		this.ipTemplateId = ipTemplateId;
		this.allowSigUsageByOthers = allowSigUsageByOthers;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
	}

	public DoctorsModel(String doctorId, String doctorName, String specialization, String doctorType, String doctorAddress,
			String doctorMobile, String doctorMailId, BigDecimal opConsultationValidity, Character status,
			DepartmentModel deptId, Character otDoctorFlag, Character consultingDoctorFlag, Boolean schedule,
			String qualification, String registrationNo, String resPhone, String clinicPhone,
			BigDecimal paymentCategory, Character paymentEligible, String doctorLicenseNumber,
			Integer allowedRevisitCount, String customField1Value, String customField2Value, String customField3Value,
			String customField4Value, String customField5Value, int opTemplateId, Integer serviceSubGroupId,
			BigDecimal ipDischargeConsultationValidity, Integer ipDischargeConsultationCount, int ipTemplateId,
			Boolean obsoleteOverbook, String practitionType, char allowSigUsageByOthers, Date createdTimestamp,
			Date updatedTimestamp, Integer centerIdObsolete, String dhpoClinicianUserId, String dhpoClinicianPassword,
			String specialityId, String chanelling, Character prescribeByFavourites, String doctorMobileCountryCode,
			Integer overbookLimit) {
		this.doctorId = doctorId;
		this.doctorName = doctorName;
		this.specialization = specialization;
		this.doctorType = doctorType;
		this.doctorAddress = doctorAddress;
		this.doctorMobile = doctorMobile;
		this.doctorMailId = doctorMailId;
		this.opConsultationValidity = opConsultationValidity;
		this.status = status;
		this.deptId = deptId;
		this.otDoctorFlag = otDoctorFlag;
		this.consultingDoctorFlag = consultingDoctorFlag;
		this.schedule = schedule;
		this.qualification = qualification;
		this.registrationNo = registrationNo;
		this.resPhone = resPhone;
		this.clinicPhone = clinicPhone;
		this.paymentCategory = paymentCategory;
		this.paymentEligible = paymentEligible;
		this.doctorLicenseNumber = doctorLicenseNumber;
		this.allowedRevisitCount = allowedRevisitCount;
		this.customField1Value = customField1Value;
		this.customField2Value = customField2Value;
		this.customField3Value = customField3Value;
		this.customField4Value = customField4Value;
		this.customField5Value = customField5Value;
		this.opTemplateId = opTemplateId;
		this.serviceSubGroupId = serviceSubGroupId;
		this.ipDischargeConsultationValidity = ipDischargeConsultationValidity;
		this.ipDischargeConsultationCount = ipDischargeConsultationCount;
		this.ipTemplateId = ipTemplateId;
		this.obsoleteOverbook = obsoleteOverbook;
		this.practitionType = practitionType;
		this.allowSigUsageByOthers = allowSigUsageByOthers;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
		this.centerIdObsolete = centerIdObsolete;
		this.dhpoClinicianUserId = dhpoClinicianUserId;
		this.dhpoClinicianPassword = dhpoClinicianPassword;
		this.specialityId = specialityId;
		this.chanelling = chanelling;
		this.prescribeByFavourites = prescribeByFavourites;
		this.doctorMobileCountryCode = doctorMobileCountryCode;
		this.overbookLimit = overbookLimit;
	}

	@Id

	@Column(name = "doctor_id", unique = true, nullable = false, length = 20)
	public String getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "doctor_name", nullable = false, length = 100)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "specialization", length = 100)
	public String getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}

	@Column(name = "doctor_type", nullable = false, length = 50)
	public String getDoctorType() {
		return this.doctorType;
	}

	public void setDoctorType(String doctorType) {
		this.doctorType = doctorType;
	}

	@Column(name = "doctor_address")
	public String getDoctorAddress() {
		return this.doctorAddress;
	}

	public void setDoctorAddress(String doctorAddress) {
		this.doctorAddress = doctorAddress;
	}

	@Column(name = "doctor_mobile", length = 16)
	public String getDoctorMobile() {
		return this.doctorMobile;
	}

	public void setDoctorMobile(String doctorMobile) {
		this.doctorMobile = doctorMobile;
	}

	@Column(name = "doctor_mail_id", length = 500)
	public String getDoctorMailId() {
		return this.doctorMailId;
	}

	public void setDoctorMailId(String doctorMailId) {
		this.doctorMailId = doctorMailId;
	}

	@Column(name = "op_consultation_validity", precision = 131089, scale = 0)
	public BigDecimal getOpConsultationValidity() {
		return this.opConsultationValidity;
	}

	public void setOpConsultationValidity(BigDecimal opConsultationValidity) {
		this.opConsultationValidity = opConsultationValidity;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "dept_id", referencedColumnName = "dept_id", nullable = false, insertable = false, updatable = false)
  public DepartmentModel getDeptId() {
    return this.deptId;
  }

  public void setDeptId(DepartmentModel deptId) {
    this.deptId = deptId;
  }

	@Column(name = "ot_doctor_flag", length = 1)
	public Character getOtDoctorFlag() {
		return this.otDoctorFlag;
	}

	public void setOtDoctorFlag(Character otDoctorFlag) {
		this.otDoctorFlag = otDoctorFlag;
	}

	@Column(name = "consulting_doctor_flag", length = 1)
	public Character getConsultingDoctorFlag() {
		return this.consultingDoctorFlag;
	}

	public void setConsultingDoctorFlag(Character consultingDoctorFlag) {
		this.consultingDoctorFlag = consultingDoctorFlag;
	}

	@Column(name = "schedule")
	public Boolean getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Boolean schedule) {
		this.schedule = schedule;
	}

	@Column(name = "qualification", length = 50)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "registration_no", length = 15)
	public String getRegistrationNo() {
		return this.registrationNo;
	}

	public void setRegistrationNo(String registrationNo) {
		this.registrationNo = registrationNo;
	}

	@Column(name = "res_phone", length = 15)
	public String getResPhone() {
		return this.resPhone;
	}

	public void setResPhone(String resPhone) {
		this.resPhone = resPhone;
	}

	@Column(name = "clinic_phone", length = 15)
	public String getClinicPhone() {
		return this.clinicPhone;
	}

	public void setClinicPhone(String clinicPhone) {
		this.clinicPhone = clinicPhone;
	}

	@Column(name = "payment_category", precision = 131089, scale = 0)
	public BigDecimal getPaymentCategory() {
		return this.paymentCategory;
	}

	public void setPaymentCategory(BigDecimal paymentCategory) {
		this.paymentCategory = paymentCategory;
	}

	@Column(name = "payment_eligible", length = 1)
	public Character getPaymentEligible() {
		return this.paymentEligible;
	}

	public void setPaymentEligible(Character paymentEligible) {
		this.paymentEligible = paymentEligible;
	}

	@Column(name = "doctor_license_number", length = 50)
	public String getDoctorLicenseNumber() {
		return this.doctorLicenseNumber;
	}

	public void setDoctorLicenseNumber(String doctorLicenseNumber) {
		this.doctorLicenseNumber = doctorLicenseNumber;
	}

	@Column(name = "allowed_revisit_count")
	public Integer getAllowedRevisitCount() {
		return this.allowedRevisitCount;
	}

	public void setAllowedRevisitCount(Integer allowedRevisitCount) {
		this.allowedRevisitCount = allowedRevisitCount;
	}

	@Column(name = "custom_field1_value", length = 200)
	public String getCustomField1Value() {
		return this.customField1Value;
	}

	public void setCustomField1Value(String customField1Value) {
		this.customField1Value = customField1Value;
	}

	@Column(name = "custom_field2_value", length = 200)
	public String getCustomField2Value() {
		return this.customField2Value;
	}

	public void setCustomField2Value(String customField2Value) {
		this.customField2Value = customField2Value;
	}

	@Column(name = "custom_field3_value", length = 200)
	public String getCustomField3Value() {
		return this.customField3Value;
	}

	public void setCustomField3Value(String customField3Value) {
		this.customField3Value = customField3Value;
	}

	@Column(name = "custom_field4_value", length = 200)
	public String getCustomField4Value() {
		return this.customField4Value;
	}

	public void setCustomField4Value(String customField4Value) {
		this.customField4Value = customField4Value;
	}

	@Column(name = "custom_field5_value", length = 200)
	public String getCustomField5Value() {
		return this.customField5Value;
	}

	public void setCustomField5Value(String customField5Value) {
		this.customField5Value = customField5Value;
	}

	@Column(name = "op_template_id", nullable = false)
	public int getOpTemplateId() {
		return this.opTemplateId;
	}

	public void setOpTemplateId(int opTemplateId) {
		this.opTemplateId = opTemplateId;
	}

	@Column(name = "service_sub_group_id")
	public Integer getServiceSubGroupId() {
		return this.serviceSubGroupId;
	}

	public void setServiceSubGroupId(Integer serviceSubGroupId) {
		this.serviceSubGroupId = serviceSubGroupId;
	}

	@Column(name = "ip_discharge_consultation_validity", precision = 131089, scale = 0)
	public BigDecimal getIpDischargeConsultationValidity() {
		return this.ipDischargeConsultationValidity;
	}

	public void setIpDischargeConsultationValidity(BigDecimal ipDischargeConsultationValidity) {
		this.ipDischargeConsultationValidity = ipDischargeConsultationValidity;
	}

	@Column(name = "ip_discharge_consultation_count")
	public Integer getIpDischargeConsultationCount() {
		return this.ipDischargeConsultationCount;
	}

	public void setIpDischargeConsultationCount(Integer ipDischargeConsultationCount) {
		this.ipDischargeConsultationCount = ipDischargeConsultationCount;
	}

	@Column(name = "ip_template_id", nullable = false)
	public int getIpTemplateId() {
		return this.ipTemplateId;
	}

	public void setIpTemplateId(int ipTemplateId) {
		this.ipTemplateId = ipTemplateId;
	}

	@Column(name = "obsolete_overbook")
	public Boolean getObsoleteOverbook() {
		return this.obsoleteOverbook;
	}

	public void setObsoleteOverbook(Boolean obsoleteOverbook) {
		this.obsoleteOverbook = obsoleteOverbook;
	}

	@Column(name = "practition_type", length = 1)
	public String getPractitionType() {
		return this.practitionType;
	}

	public void setPractitionType(String practitionType) {
		this.practitionType = practitionType;
	}

	@Column(name = "allow_sig_usage_by_others", nullable = false, length = 1)
	public char getAllowSigUsageByOthers() {
		return this.allowSigUsageByOthers;
	}

	public void setAllowSigUsageByOthers(char allowSigUsageByOthers) {
		this.allowSigUsageByOthers = allowSigUsageByOthers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_timestamp", nullable = false, length = 29)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_timestamp", nullable = false, length = 29)
	public Date getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	@Column(name = "center_id_obsolete")
	public Integer getCenterIdObsolete() {
		return this.centerIdObsolete;
	}

	public void setCenterIdObsolete(Integer centerIdObsolete) {
		this.centerIdObsolete = centerIdObsolete;
	}

	@Column(name = "dhpo_clinician_user_id", length = 50)
	public String getDhpoClinicianUserId() {
		return this.dhpoClinicianUserId;
	}

	public void setDhpoClinicianUserId(String dhpoClinicianUserId) {
		this.dhpoClinicianUserId = dhpoClinicianUserId;
	}

	@Column(name = "dhpo_clinician_password", length = 50)
	public String getDhpoClinicianPassword() {
		return this.dhpoClinicianPassword;
	}

	public void setDhpoClinicianPassword(String dhpoClinicianPassword) {
		this.dhpoClinicianPassword = dhpoClinicianPassword;
	}

	@Column(name = "speciality_id", length = 10)
	public String getSpecialityId() {
		return this.specialityId;
	}

	public void setSpecialityId(String specialityId) {
		this.specialityId = specialityId;
	}

	@Column(name = "chanelling", length = 1)
	public String getChanelling() {
		return this.chanelling;
	}

	public void setChanelling(String chanelling) {
		this.chanelling = chanelling;
	}

	@Column(name = "prescribe_by_favourites", length = 1)
	public Character getPrescribeByFavourites() {
		return this.prescribeByFavourites;
	}

	public void setPrescribeByFavourites(Character prescribeByFavourites) {
		this.prescribeByFavourites = prescribeByFavourites;
	}

	@Column(name = "doctor_mobile_country_code", length = 5)
	public String getDoctorMobileCountryCode() {
		return this.doctorMobileCountryCode;
	}

	public void setDoctorMobileCountryCode(String doctorMobileCountryCode) {
		this.doctorMobileCountryCode = doctorMobileCountryCode;
	}

	@Column(name = "overbook_limit")
	public Integer getOverbookLimit() {
		return this.overbookLimit;
	}

	public void setOverbookLimit(Integer overbookLimit) {
		this.overbookLimit = overbookLimit;
	}
}
