package com.insta.hms.mdm.servicesubgroup;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.servicegroup.ServiceGroupsModel;
import com.insta.hms.model.BillAccountHeadsModel;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceSubGroupModel generated by hbm2java
 */
@Entity
@Table(name = "service_sub_groups")
public class ServiceSubGroupModel implements java.io.Serializable {

	private int serviceSubGroupId;
	private char status;
	private ServiceGroupsModel serviceGroupId;
	private String serviceSubGroupName;
	private int displayOrder;
	private String username;
	private Date modTime;
	private String serviceSubGroupCode;
	private BillAccountHeadsModel accountHeadId;
	private char eligibleToEarnPoints;
	private char eligibleToRedeemPoints;
	private BigDecimal redemptionCapPercent;

	public ServiceSubGroupModel() {
	}

	public ServiceSubGroupModel(int serviceSubGroupId, char status, ServiceGroupsModel serviceGroupId, String serviceSubGroupName,
			int displayOrder, String username, Date modTime, char eligibleToEarnPoints, char eligibleToRedeemPoints) {
		this.serviceSubGroupId = serviceSubGroupId;
		this.status = status;
		this.serviceGroupId = serviceGroupId;
		this.serviceSubGroupName = serviceSubGroupName;
		this.displayOrder = displayOrder;
		this.username = username;
		this.modTime = modTime;
		this.eligibleToEarnPoints = eligibleToEarnPoints;
		this.eligibleToRedeemPoints = eligibleToRedeemPoints;
	}

	public ServiceSubGroupModel(int serviceSubGroupId, char status, ServiceGroupsModel serviceGroupId, String serviceSubGroupName,
			int displayOrder, String username, Date modTime, String serviceSubGroupCode, BillAccountHeadsModel accountHeadId,
			char eligibleToEarnPoints, char eligibleToRedeemPoints, BigDecimal redemptionCapPercent) {
		this.serviceSubGroupId = serviceSubGroupId;
		this.status = status;
		this.serviceGroupId = serviceGroupId;
		this.serviceSubGroupName = serviceSubGroupName;
		this.displayOrder = displayOrder;
		this.username = username;
		this.modTime = modTime;
		this.serviceSubGroupCode = serviceSubGroupCode;
		this.accountHeadId = accountHeadId;
		this.eligibleToEarnPoints = eligibleToEarnPoints;
		this.eligibleToRedeemPoints = eligibleToRedeemPoints;
		this.redemptionCapPercent = redemptionCapPercent;
	}

	@Id

	@Column(name = "service_sub_group_id", unique = true, nullable = false)
	public int getServiceSubGroupId() {
		return this.serviceSubGroupId;
	}

	public void setServiceSubGroupId(int serviceSubGroupId) {
		this.serviceSubGroupId = serviceSubGroupId;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "service_group_id", nullable = false, insertable = false, updatable = false)
	public ServiceGroupsModel getServiceGroupId() {
		return this.serviceGroupId;
	}

	public void setServiceGroupId(ServiceGroupsModel serviceGroupId) {
		this.serviceGroupId = serviceGroupId;
	}

	@Column(name = "service_sub_group_name", nullable = false, length = 100)
	public String getServiceSubGroupName() {
		return this.serviceSubGroupName;
	}

	public void setServiceSubGroupName(String serviceSubGroupName) {
		this.serviceSubGroupName = serviceSubGroupName;
	}

	@Column(name = "display_order", nullable = false)
	public int getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "service_sub_group_code", length = 10)
	public String getServiceSubGroupCode() {
		return this.serviceSubGroupCode;
	}

	public void setServiceSubGroupCode(String serviceSubGroupCode) {
		this.serviceSubGroupCode = serviceSubGroupCode;
	}

	@NotFound(action = NotFoundAction.IGNORE)
	@ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "account_head_id", nullable = false, insertable = false, updatable = false)
	public BillAccountHeadsModel getAccountHeadId() {
		return this.accountHeadId;
	}

	public void setAccountHeadId(BillAccountHeadsModel accountHeadId) {
		this.accountHeadId = accountHeadId;
	}

	@Column(name = "eligible_to_earn_points", nullable = false, length = 1)
	public char getEligibleToEarnPoints() {
		return this.eligibleToEarnPoints;
	}

	public void setEligibleToEarnPoints(char eligibleToEarnPoints) {
		this.eligibleToEarnPoints = eligibleToEarnPoints;
	}

	@Column(name = "eligible_to_redeem_points", nullable = false, length = 1)
	public char getEligibleToRedeemPoints() {
		return this.eligibleToRedeemPoints;
	}

	public void setEligibleToRedeemPoints(char eligibleToRedeemPoints) {
		this.eligibleToRedeemPoints = eligibleToRedeemPoints;
	}

	@Column(name = "redemption_cap_percent", precision = 5)
	public BigDecimal getRedemptionCapPercent() {
		return this.redemptionCapPercent;
	}

	public void setRedemptionCapPercent(BigDecimal redemptionCapPercent) {
		this.redemptionCapPercent = redemptionCapPercent;
	}

}
