package com.insta.hms.mdm.ordersets;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Comparator;
import java.util.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * PackageContentsModel generated by hbm2java.
 */
@Entity
@Table(name = "package_contents")
public class PackageContentsModel implements java.io.Serializable {

  /** The package content id. */
  private Integer packageContentId;

  /** The package id. */
  private int packageId;

  /** The activity id. */
  private String activityId;

  /** The activity type. */
  private String activityType;

  /** The activity qty. */
  private Integer activityQty;

  /** The activity qty uom. */
  private String activityQtyUom;

  /** The activity remarks. */
  private String activityRemarks;

  /** The activity description. */
  private String activityDescription;

  /** The doctor id. */
  private String doctorId;

  /** The dept id. */
  private String deptId;

  /** The display order. */
  private Integer displayOrder;

  /** The modified by. */
  private String modifiedBy;

  /** The modified at. */
  @JsonFormat(pattern = "dd-MM-yyyy HH:mm:ss")
  private Date modifiedAt;

  /** The created by. */
  private String createdBy;

  /** The created at. */
  @JsonFormat(pattern = "dd-MM-yyyy HH:mm:ss")
  private Date createdAt;

  /** The consultation type id. */
  private Integer consultationTypeId;

  /** The charge head. */
  private String chargeHead;

  /** The conduction gap. */
  private Integer conductionGap;

  /** The conduction gap unit. */
  private String conductionGapUnit;

  /** The parent pack ob id. */
  private Integer parentPackObId;

  /** The operation id. */
  private String operationId;

  /** The bed id. */
  private Integer bedId;

  /** The panel id. */
  private Integer panelId;

  /** The visit qty limit. */
  private Integer visitQtyLimit;

  /** The content id ref. */
  private Integer contentIdRef;

  /**
   * Instantiates a new package contents model.
   */
  public PackageContentsModel() {}

  /**
   * Instantiates a new package contents model.
   *
   * @param packageContentId the package content id
   * @param packageId the package id
   */
  public PackageContentsModel(int packageContentId, int packageId) {
    this.packageContentId = packageContentId;
    this.packageId = packageId;
  }

  /**
   * Instantiates a new package contents model.
   *
   * @param packageContentId the package content id
   * @param packageId the package id
   * @param activityId the activity id
   * @param activityType the activity type
   * @param activityQty the activity qty
   * @param activityQtyUom the activity qty uom
   * @param activityRemarks the activity remarks
   * @param doctorId the doctor id
   * @param deptId the dept id
   * @param displayOrder the display order
   * @param modifiedBy the modified by
   * @param modifiedAt the modified at
   * @param createdBy the created by
   * @param createdAt the created at
   * @param consultationTypeId the consultation type id
   * @param chargeHead the charge head
   * @param conductionGap the conduction gap
   * @param conductionGapUnit the conduction gap unit
   * @param parentPackObId the parent pack ob id
   * @param operationId the operation id
   * @param bedId the bed id
   * @param panelId the panel id
   */
  public PackageContentsModel(Integer packageContentId, int packageId, String activityId,
      String activityType, Integer activityQty, String activityQtyUom, String activityRemarks,
      String doctorId, String deptId, Integer displayOrder, String modifiedBy, Date modifiedAt,
      String createdBy, Date createdAt, Integer consultationTypeId, String chargeHead,
      Integer conductionGap, String conductionGapUnit, Integer parentPackObId,
      String operationId, Integer bedId, Integer panelId) {
    this.packageContentId = packageContentId;
    this.packageId = packageId;
    this.activityId = activityId;
    this.activityType = activityType;
    this.activityQty = activityQty;
    this.activityQtyUom = activityQtyUom;
    this.activityRemarks = activityRemarks;
    this.doctorId = doctorId;
    this.deptId = deptId;
    this.displayOrder = displayOrder;
    this.modifiedBy = modifiedBy;
    this.modifiedAt = modifiedAt;
    this.createdBy = createdBy;
    this.createdAt = createdAt;
    this.consultationTypeId = consultationTypeId;
    this.chargeHead = chargeHead;
    this.conductionGap = conductionGap;
    this.conductionGapUnit = conductionGapUnit;
    this.parentPackObId = parentPackObId;
    this.operationId = operationId;
    this.bedId = bedId;
    this.panelId = panelId;
  }

  /**
   * Instantiates a new package contents model.
   *
   * @param packageContentId the package content id
   * @param packageId the package id
   * @param activityId the activity id
   * @param activityType the activity type
   * @param activityQty the activity qty
   * @param activityQtyUom the activity qty uom
   * @param activityRemarks the activity remarks
   * @param doctorId the doctor id
   * @param deptId the dept id
   * @param displayOrder the display order
   * @param modifiedBy the modified by
   * @param modifiedAt the modified at
   * @param createdBy the created by
   * @param createdAt the created at
   */
  public PackageContentsModel(Integer packageContentId, int packageId, String activityId,
      String activityType, Integer activityQty, String activityQtyUom, String activityRemarks,
      String doctorId, String deptId, Integer displayOrder, String modifiedBy, Date modifiedAt,
      String createdBy, Date createdAt) {
    this.packageContentId = packageContentId;
    this.packageId = packageId;
    this.activityId = activityId;
    this.activityType = activityType;
    this.activityQty = activityQty;
    this.activityQtyUom = activityQtyUom;
    this.activityRemarks = activityRemarks;
    this.doctorId = doctorId;
    this.deptId = deptId;
    this.displayOrder = displayOrder;
    this.modifiedBy = modifiedBy;
    this.modifiedAt = modifiedAt;
    this.createdBy = createdBy;
    this.createdAt = createdAt;
  }

  /**
   * Gets the package content id.
   *
   * @return the package content id
   */
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE,
      generator = "sequence_generator_for_package_content")
  @SequenceGenerator(name = "sequence_generator_for_package_content",
      sequenceName = "package_contents_seq", allocationSize = 1)
  @Column(name = "package_content_id", unique = true, nullable = false)
  public Integer getPackageContentId() {
    return this.packageContentId;
  }

  /**
   * Sets the package content id.
   *
   * @param packageContentId the new package content id
   */
  public void setPackageContentId(Integer packageContentId) {
    this.packageContentId = packageContentId;
  }

  /**
   * Gets the package id.
   *
   * @return the package id
   */
  @Column(name = "package_id", nullable = false)
  public int getPackageId() {
    return this.packageId;
  }

  /**
   * Sets the package id.
   *
   * @param packageId the new package id
   */
  public void setPackageId(int packageId) {
    this.packageId = packageId;
  }

  /**
   * Gets the activity id.
   *
   * @return the activity id
   */
  @Column(name = "activity_id", length = 200)
  public String getActivityId() {
    return this.activityId;
  }

  /**
   * Sets the activity id.
   *
   * @param activityId the new activity id
   */
  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  /**
   * Gets the activity type.
   *
   * @return the activity type
   */
  @Column(name = "activity_type", length = 50)
  public String getActivityType() {
    return this.activityType;
  }

  /**
   * Sets the activity type.
   *
   * @param activityType the new activity type
   */
  public void setActivityType(String activityType) {
    this.activityType = activityType;
  }

  /**
   * Gets the activity qty.
   *
   * @return the activity qty
   */
  @Column(name = "activity_qty")
  public Integer getActivityQty() {
    return this.activityQty;
  }

  /**
   * Sets the activity qty.
   *
   * @param activityQty the new activity qty
   */
  public void setActivityQty(Integer activityQty) {
    this.activityQty = activityQty;
  }

  /**
   * Gets the activity qty uom.
   *
   * @return the activity qty uom
   */
  @Column(name = "activity_qty_uom")
  public String getActivityQtyUom() {
    return this.activityQtyUom;
  }

  /**
   * Sets the activity qty uom.
   *
   * @param activityQtyUom the new activity qty uom
   */
  public void setActivityQtyUom(String activityQtyUom) {
    this.activityQtyUom = activityQtyUom;
  }

  /**
   * Gets the activity remarks.
   *
   * @return the activity remarks
   */
  @Column(name = "activity_remarks")
  public String getActivityRemarks() {
    return this.activityRemarks;
  }

  /**
   * Sets the activity remarks.
   *
   * @param activityRemarks the new activity remarks
   */
  public void setActivityRemarks(String activityRemarks) {
    this.activityRemarks = activityRemarks;
  }

  /**
   * Gets the doctor id.
   *
   * @return the doctor id
   */
  @Column(name = "doctor_id", length = 20)
  public String getDoctorId() {
    return this.doctorId;
  }

  /**
   * Sets the doctor id.
   *
   * @param doctorId the new doctor id
   */
  public void setDoctorId(String doctorId) {
    this.doctorId = doctorId;
  }

  /**
   * Gets the dept id.
   *
   * @return the dept id
   */
  @Column(name = "dept_id", length = 20)
  public String getDeptId() {
    return this.deptId;
  }

  /**
   * Sets the dept id.
   *
   * @param deptId the new dept id
   */
  public void setDeptId(String deptId) {
    this.deptId = deptId;
  }

  /**
   * Gets the display order.
   *
   * @return the display order
   */
  @Column(name = "display_order")
  public Integer getDisplayOrder() {
    return this.displayOrder;
  }

  /**
   * Sets the display order.
   *
   * @param displayOrder the new display order
   */
  public void setDisplayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
  }

  /**
   * Gets the modified by.
   *
   * @return the modified by
   */
  @Column(name = "modified_by", length = 50)
  public String getModifiedBy() {
    return this.modifiedBy;
  }

  /**
   * Sets the modified by.
   *
   * @param modifiedBy the new modified by
   */
  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  /**
   * Gets the modified at.
   *
   * @return the modified at
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "modified_at", length = 29)
  public Date getModifiedAt() {
    return this.modifiedAt;
  }

  /**
   * Sets the modified at.
   *
   * @param modifiedAt the new modified at
   */
  public void setModifiedAt(Date modifiedAt) {
    this.modifiedAt = modifiedAt;
  }

  /**
   * Gets the created by.
   *
   * @return the created by
   */
  @Column(name = "created_by", length = 50)
  public String getCreatedBy() {
    return this.createdBy;
  }

  /**
   * Sets the created by.
   *
   * @param createdBy the new created by
   */
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  /**
   * Gets the created at.
   *
   * @return the created at
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "created_at", length = 29)
  public Date getCreatedAt() {
    return this.createdAt;
  }

  /**
   * Sets the created at.
   *
   * @param createdAt the new created at
   */
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Gets the consultation type id.
   *
   * @return the consultation type id
   */
  @Column(name = "consultation_type_id")
  public Integer getConsultationTypeId() {
    return consultationTypeId;
  }

  /**
   * Sets the consultation type id.
   *
   * @param consultationTypeId the new consultation type id
   */
  public void setConsultationTypeId(Integer consultationTypeId) {
    this.consultationTypeId = consultationTypeId;
  }

  /**
   * Gets the charge head.
   *
   * @return the charge head
   */
  @Column(name = "charge_head", length = 20)
  public String getChargeHead() {
    return chargeHead;
  }

  /**
   * Sets the charge head.
   *
   * @param chargeHead the new charge head
   */
  public void setChargeHead(String chargeHead) {
    this.chargeHead = chargeHead;
  }

  /**
   * Gets the conduction gap.
   *
   * @return the conduction gap
   */
  @Column(name = "conduction_gap")
  public Integer getConductionGap() {
    return conductionGap;
  }

  /**
   * Sets the conduction gap.
   *
   * @param conductionGap the new conduction gap
   */
  public void setConductionGap(Integer conductionGap) {
    this.conductionGap = conductionGap;
  }

  /**
   * Gets the conduction gap unit.
   *
   * @return the conduction gap unit
   */
  @Column(name = "conduction_gap_unit", length = 20)
  public String getConductionGapUnit() {
    return conductionGapUnit;
  }

  /**
   * Sets the conduction gap unit.
   *
   * @param conductionGapUnit the new conduction gap unit
   */
  public void setConductionGapUnit(String conductionGapUnit) {
    this.conductionGapUnit = conductionGapUnit;
  }

  /**
   * Gets the parent pack ob id.
   *
   * @return the parent pack ob id
   */
  @Column(name = "parent_pack_ob_id")
  public Integer getParentPackObId() {
    return parentPackObId;
  }

  /**
   * Sets the parent pack ob id.
   *
   * @param parentPackObId the new parent pack ob id
   */
  public void setParentPackObId(Integer parentPackObId) {
    this.parentPackObId = parentPackObId;
  }

  /**
   * Gets the operation id.
   *
   * @return the operation id
   */
  @Column(name = "operation_id", length = 10)
  public String getOperationId() {
    return operationId;
  }

  /**
   * Sets the operation id.
   *
   * @param operationId the new operation id
   */
  public void setOperationId(String operationId) {
    this.operationId = operationId;
  }

  /**
   * Gets the bed id.
   *
   * @return the bed id
   */
  @Column(name = "bed_id")
  public Integer getBedId() {
    return bedId;
  }

  /**
   * Sets the bed id.
   *
   * @param bedId the new bed id
   */
  public void setBedId(Integer bedId) {
    this.bedId = bedId;
  }

  /**
   * Gets the panel id.
   *
   * @return the panel id
   */
  @Column(name = "panel_id")
  public Integer getPanelId() {
    return panelId;
  }

  /**
   * Sets the panel id.
   *
   * @param panelId the new panel id
   */
  public void setPanelId(Integer panelId) {
    this.panelId = panelId;
  }

  /**
   * Gets the activity description.
   *
   * @return the activity description
   */
  @Transient
  @JsonProperty
  public String getActivityDescription() {
    return activityDescription;
  }

  /**
   * Sets the activity description.
   *
   * @param activityDescription the new activity description
   */
  public void setActivityDescription(String activityDescription) {
    this.activityDescription = activityDescription;
  }

  /**
   * Gets the visit qty limit.
   *
   * @return the visit qty limit
   */
  @Column(name = "visit_qty_limit")
  public Integer getVisitQtyLimit() {
    return visitQtyLimit;
  }

  /**
   * Sets the visit qty limit.
   *
   * @param visitQtyLimit the new visit qty limit
   */
  public void setVisitQtyLimit(Integer visitQtyLimit) {
    this.visitQtyLimit = visitQtyLimit;
  }

  /**
   * Gets the content id ref.
   *
   * @return the content id ref
   */
  @Column(name = "content_id_ref")
  public Integer getContentIdRef() {
    return contentIdRef;
  }

  /**
   * Sets the content id ref.
   *
   * @param contentIdRef the new content id ref
   */
  public void setContentIdRef(Integer contentIdRef) {
    this.contentIdRef = contentIdRef;
  }



  /**
   * The Class CompareByRef.
   */
  class CompareByRef implements Comparator<PackageContentsModel> {

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Comparator#compare(java.lang.Object, java.lang.Object)
     */
    public int compare(PackageContentsModel p1, PackageContentsModel p2) {
      if (p1.getContentIdRef() != null && p2.getContentIdRef() != null) {
        if (p1.getContentIdRef().compareTo(p2.getContentIdRef()) > 0) {
          return 1;
        }
        if (p1.getContentIdRef().compareTo(p2.getContentIdRef()) < 0) {
          return -1;
        }
        return 0;
      }
      return -1;
    }
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageContentsModel that = (PackageContentsModel) o;
    return Objects.equals(packageContentId, that.packageContentId);
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode() {
    return Objects.hash(packageContentId, activityId, activityType, activityQty,
        activityQtyUom, activityRemarks, activityDescription, doctorId, deptId, displayOrder,
        modifiedBy, modifiedAt, createdBy, createdAt, consultationTypeId, chargeHead,
        conductionGap, conductionGapUnit, parentPackObId, operationId, bedId, panelId,
        visitQtyLimit);
  }

}
