package com.insta.hms.mdm.ordersets;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * PackageChargesModel generated by hbm2java
 */
@Entity
@Table(name = "package_charges")
public class PackageChargesModel implements java.io.Serializable {

	private int packageChargeId;
	private int packageId;
	private String orgId;
	private String bedType;
	private BigDecimal charge;
	private BigDecimal discount;
	private String isOverride;
	private String createdBy;
	@JsonFormat(pattern = "dd-mm-yyyy hh:mm:ss")
	private Date createdAt;
	private String modifiedBy;
	@JsonFormat(pattern = "dd-mm-yyyy hh:mm:ss")
	private Date modifiedAt;

	public PackageChargesModel() {
	}

	public PackageChargesModel(int packageChargeId, BigDecimal discount) {
		this.packageChargeId = packageChargeId;
		this.discount = discount;
	}

	public PackageChargesModel(int packageChargeId, int packageId, BigDecimal charge, BigDecimal discount,
							   String isOverride) {
		this.packageChargeId = packageChargeId;
		this.packageId = packageId;
		this.charge = charge;
		this.discount = discount;
		this.isOverride = isOverride;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator =
			"sequence_generator_for_package_charges")
	@SequenceGenerator(name = "sequence_generator_for_package_charges", sequenceName =
			"package_charges_id_seq", allocationSize = 1)
	@Column(name = "package_charges_id", unique = true, nullable = false)
	public int getPackageChargeId() {
		return this.packageChargeId;
	}

	public void setPackageChargeId(int id) {
		this.packageChargeId = id;
	}

	@Column(name = "charge", precision = 15)
	public BigDecimal getCharge() {
		return this.charge;
	}

	public void setCharge(BigDecimal charge) {
		this.charge = charge;
	}

	@Column(name = "discount", nullable = false, precision = 15)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

	@Column(name = "package_id" , nullable = false)
	public int getPackageId() {
		return packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	@Column(name = "org_id", nullable = false)
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "bed_type", nullable = false)
	public String getBedType() {
		return bedType;
	}

	public void setBedType(String bedType) {
		this.bedType = bedType;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_at")
	public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "modified_by")
	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "modified_at")
	public Date getModifiedAt() {
		return modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}
}
