package com.insta.hms.mdm.tpacenters;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TpaCenterMasterModel generated by hbm2java
 */
@Entity
@Table(name = "tpa_center_master")
public class TpaCenterMasterModel implements java.io.Serializable {

	private int tpaCenterId;
	private String tpaId;
	private Integer centerId;
	private Character status;
	private String claimFormat;

	public TpaCenterMasterModel() {
	}

	public TpaCenterMasterModel(int tpaCenterId) {
		this.tpaCenterId = tpaCenterId;
	}

	public TpaCenterMasterModel(int tpaCenterId, String tpaId, Integer centerId, Character status, String claimFormat) {
		this.tpaCenterId = tpaCenterId;
		this.tpaId = tpaId;
		this.centerId = centerId;
		this.status = status;
		this.claimFormat = claimFormat;
	}

	@Id

	@Column(name = "tpa_center_id", unique = true, nullable = false)
	public int getTpaCenterId() {
		return this.tpaCenterId;
	}

	public void setTpaCenterId(int tpaCenterId) {
		this.tpaCenterId = tpaCenterId;
	}

	@Column(name = "tpa_id", length = 15)
	public String getTpaId() {
		return this.tpaId;
	}

	public void setTpaId(String tpaId) {
		this.tpaId = tpaId;
	}

	@Column(name = "center_id")
	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "claim_format", length = 20)
	public String getClaimFormat() {
		return this.claimFormat;
	}

	public void setClaimFormat(String claimFormat) {
		this.claimFormat = claimFormat;
	}

}
