package com.insta.hms.mdm.paymentmode;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.fasterxml.jackson.annotation.JsonView;
import com.insta.hms.model.PaymentTransactionsModel;
import com.insta.hms.util.ViewProfiles;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PaymentModeMasterModel generated by hbm2java
 */
@Entity
@Table(name = "payment_mode_master", uniqueConstraints = @UniqueConstraint(columnNames = "payment_mode"))
public class PaymentModeMasterModel implements java.io.Serializable {

  @JsonView(ViewProfiles.Public.class)
	private int modeId;
  @JsonView(ViewProfiles.Public.class)
	private String paymentMode;
	private String cardTypeRequired;
	private String bankRequired;
	private String refRequired;
	private String realizationRequired;
	private String status;
	private Integer displayorder;
	private String splAccountName;
	private Character bankBatchRequired;
	private Character cardAuthRequired;
	private Character cardHolderRequired;
	private Character cardNumberRequired;
	private Character cardExpdateRequired;
	private Character totpRequired;
	private Character mobileNumberRequired;
	private BigDecimal transactionLimit;
	private Character allowPaymentsMoreThanTransactionLimit;
	private Set<PaymentTransactionsModel> paymentTransactionses = new HashSet(0);

	public PaymentModeMasterModel() {
	}

	public PaymentModeMasterModel(int modeId) {
		this.modeId = modeId;
	}

	public PaymentModeMasterModel(int modeId, String paymentMode, String cardTypeRequired, String bankRequired,
			String refRequired, String realizationRequired, String status, Integer displayorder, String splAccountName,
			Character bankBatchRequired, Character cardAuthRequired, Character cardHolderRequired,
			Character cardNumberRequired, Character cardExpdateRequired, Character totpRequired,
			Character mobileNumberRequired, BigDecimal transactionLimit,
			Character allowPaymentsMoreThanTransactionLimit, Set<PaymentTransactionsModel> paymentTransactionses) {
		this.modeId = modeId;
		this.paymentMode = paymentMode;
		this.cardTypeRequired = cardTypeRequired;
		this.bankRequired = bankRequired;
		this.refRequired = refRequired;
		this.realizationRequired = realizationRequired;
		this.status = status;
		this.displayorder = displayorder;
		this.splAccountName = splAccountName;
		this.bankBatchRequired = bankBatchRequired;
		this.cardAuthRequired = cardAuthRequired;
		this.cardHolderRequired = cardHolderRequired;
		this.cardNumberRequired = cardNumberRequired;
		this.cardExpdateRequired = cardExpdateRequired;
		this.totpRequired = totpRequired;
		this.mobileNumberRequired = mobileNumberRequired;
		this.transactionLimit = transactionLimit;
		this.allowPaymentsMoreThanTransactionLimit = allowPaymentsMoreThanTransactionLimit;
	}

	@Id

	@Column(name = "mode_id", unique = true, nullable = false)
	public int getModeId() {
		return this.modeId;
	}

	public void setModeId(int modeId) {
		this.modeId = modeId;
	}

	@Column(name = "payment_mode", unique = true, length = 30)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "card_type_required", length = 1)
	public String getCardTypeRequired() {
		return this.cardTypeRequired;
	}

	public void setCardTypeRequired(String cardTypeRequired) {
		this.cardTypeRequired = cardTypeRequired;
	}

	@Column(name = "bank_required", length = 1)
	public String getBankRequired() {
		return this.bankRequired;
	}

	public void setBankRequired(String bankRequired) {
		this.bankRequired = bankRequired;
	}

	@Column(name = "ref_required", length = 1)
	public String getRefRequired() {
		return this.refRequired;
	}

	public void setRefRequired(String refRequired) {
		this.refRequired = refRequired;
	}

	@Column(name = "realization_required", length = 1)
	public String getRealizationRequired() {
		return this.realizationRequired;
	}

	public void setRealizationRequired(String realizationRequired) {
		this.realizationRequired = realizationRequired;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "displayorder")
	public Integer getDisplayorder() {
		return this.displayorder;
	}

	public void setDisplayorder(Integer displayorder) {
		this.displayorder = displayorder;
	}

	@Column(name = "spl_account_name", length = 100)
	public String getSplAccountName() {
		return this.splAccountName;
	}

	public void setSplAccountName(String splAccountName) {
		this.splAccountName = splAccountName;
	}

	@Column(name = "bank_batch_required", length = 1)
	public Character getBankBatchRequired() {
		return this.bankBatchRequired;
	}

	public void setBankBatchRequired(Character bankBatchRequired) {
		this.bankBatchRequired = bankBatchRequired;
	}

	@Column(name = "card_auth_required", length = 1)
	public Character getCardAuthRequired() {
		return this.cardAuthRequired;
	}

	public void setCardAuthRequired(Character cardAuthRequired) {
		this.cardAuthRequired = cardAuthRequired;
	}

	@Column(name = "card_holder_required", length = 1)
	public Character getCardHolderRequired() {
		return this.cardHolderRequired;
	}

	public void setCardHolderRequired(Character cardHolderRequired) {
		this.cardHolderRequired = cardHolderRequired;
	}

	@Column(name = "card_number_required", length = 1)
	public Character getCardNumberRequired() {
		return this.cardNumberRequired;
	}

	public void setCardNumberRequired(Character cardNumberRequired) {
		this.cardNumberRequired = cardNumberRequired;
	}

	@Column(name = "card_expdate_required", length = 1)
	public Character getCardExpdateRequired() {
		return this.cardExpdateRequired;
	}

	public void setCardExpdateRequired(Character cardExpdateRequired) {
		this.cardExpdateRequired = cardExpdateRequired;
	}

	@Column(name = "totp_required", length = 1)
	public Character getTotpRequired() {
		return this.totpRequired;
	}

	public void setTotpRequired(Character totpRequired) {
		this.totpRequired = totpRequired;
	}

	@Column(name = "mobile_number_required", length = 1)
	public Character getMobileNumberRequired() {
		return this.mobileNumberRequired;
	}

	public void setMobileNumberRequired(Character mobileNumberRequired) {
		this.mobileNumberRequired = mobileNumberRequired;
	}

	@Column(name = "transaction_limit", precision = 15)
	public BigDecimal getTransactionLimit() {
		return this.transactionLimit;
	}

	public void setTransactionLimit(BigDecimal transactionLimit) {
		this.transactionLimit = transactionLimit;
	}

	@Column(name = "allow_payments_more_than_transaction_limit", length = 1)
	public Character getAllowPaymentsMoreThanTransactionLimit() {
		return this.allowPaymentsMoreThanTransactionLimit;
	}

	public void setAllowPaymentsMoreThanTransactionLimit(Character allowPaymentsMoreThanTransactionLimit) {
		this.allowPaymentsMoreThanTransactionLimit = allowPaymentsMoreThanTransactionLimit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentModeMasterModel")
	public Set<PaymentTransactionsModel> getPaymentTransactionses() {
		return this.paymentTransactionses;
	}

	public void setPaymentTransactionses(Set<PaymentTransactionsModel> paymentTransactionses) {
		this.paymentTransactionses = paymentTransactionses;
	}

}
