package com.insta.hms.mdm.medicineroute;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MedicineRouteModel generated by hbm2java
 */
@Entity
@Table(name = "medicine_route")
public class MedicineRouteModel implements java.io.Serializable {

	private int routeId;
	private String routeName;
	private Character status;
	private String routeCode;

	public MedicineRouteModel() {
	}

	public MedicineRouteModel(int routeId) {
		this.routeId = routeId;
	}

	public MedicineRouteModel(int routeId, String routeName, Character status, String routeCode) {
		this.routeId = routeId;
		this.routeName = routeName;
		this.status = status;
		this.routeCode = routeCode;
	}

	@Id

	@Column(name = "route_id", unique = true, nullable = false)
	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	@Column(name = "route_name", length = 100)
	public String getRouteName() {
		return this.routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "route_code", length = 50)
	public String getRouteCode() {
		return this.routeCode;
	}

	public void setRouteCode(String routeCode) {
		this.routeCode = routeCode;
	}

}
