<%@ page language="java" contentType="text/html; charset=UTF-8"	pageEncoding="UTF-8"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="insta"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="/WEB-INF/instafn.tld" prefix="ifn" %>
<%@page import="com.insta.hms.master.RegistrationPreferences.RegistrationPreferencesDAO"%>
<%@page import="com.insta.hms.master.GenericPreferences.GenericPreferencesDAO"%>
<c:set var="cpath" value="${pageContext.request.contextPath}" />
<c:set var="max_centers_inc_default" value='<%=com.insta.hms.master.GenericPreferences.GenericPreferencesDAO.getAllPrefs().get("max_centers_inc_default")%>' scope="request"/>
<c:set var="no_of_credit_debit_card_digits" value='<%=com.insta.hms.master.GenericPreferences.GenericPreferencesDAO.getAllPrefs().get("no_of_credit_debit_card_digits") %>'/>
<c:set var="hijricalendar" value="<%= GenericPreferencesDAO.getGenericPreferences().getHijriCalendar()%>" />
<c:set var="allowAgeEntry" value="<%=RegistrationPreferencesDAO.getRegistrationPreferences().getAllow_age_entry()%>" />
<c:set var="actionPath" value="./IncomingRegistraionRadiology.do"/>
<c:if test="${category == 'DEP_LAB'}">
	<c:set var="sampleNeeded" value="y"/>
	<c:set var="actionPath" value="./IncomingRegistraionLaboratory.do"/>
</c:if>
<c:set var="incomeTaxCashLimitApplicability" value='<%=com.insta.hms.master.GenericPreferences.GenericPreferencesDAO.getAllPrefs().get("income_tax_cash_limit_applicability") %>'/>
<c:set var="cashTransactionLimit" value="${cashTransactionLimit}"/>



<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	<title><insta:ltext key="laboratory.incomingsampleregistration.register.title"/></title>
	<insta:link type="js" file="ajax.js" />
	<insta:link type="js" file="hmsvalidation.js" />
	<insta:link type="css" file="widgets.css" />
	<insta:link type="css" file="select2.min.css"/>
	<insta:link type="css" file="select2Override.css"/>
	<insta:link type="js" file="phoneNumberUtil.js"/>
	<insta:link type="script" file="widgets.js" />
	<insta:link type="script" file="sockjs.min.js"/>
	<insta:link type="script" file="stomp.min.js"/>
	<insta:link type="js" file="diagnostics/incomingsamplereg.js" />
	<insta:link type="js" file="billPaymentCommon.js" />
	<insta:link type="js" file="registration/registrationCommon.js"/>
	<insta:link type="js" file="registration/pre-registration.js"/>

	<script src="<%=request.getContextPath()%>/gettests.do?${masterTimeStamp}&${ifn:cleanURL(sesHospitalId)}&module=${ifn:cleanURL(category)}&packages=Y&center_id=${centerId}">

	</script>
	<script>
		 var defaultCountryCode= "+${defaultCountryCode}";
		 var doctors = ${doctors};
		 var centerId = '<%=(Integer) session.getAttribute("centerId") %>';
		 var regPref = ${regPrefJSON};
		 var govtIdentifierTypesJSON = ${govtIdentifierTypesJSON};
		 var govtId_label = regPref.government_identifier_label;
		 var govtId_type_label = regPref.government_identifier_type_label;
		 var no_of_credit_debit_card_digits = ${empty no_of_credit_debit_card_digits ? 0 : no_of_credit_debit_card_digits};
		 var screenid = "";
		 var govtIdentifierMandatory = '';
		 var govtId_pattern = '';
		 var hijriPref = '${hijricalendar}';
		 var agedisable = '${ifn:cleanJavaScript(regPref.allow_age_entry)}';
		 var income_tax_cash_limit_applicability = '${incomeTaxCashLimitApplicability}';
		 var cashTransactionLimitAmt = '${cashTransactionLimit}';

	</script>
	<style type="text/css">
	  .myAutoComplete{
		 width:15em; /* set width here or else widget will expand to fit its container */
	     padding-bottom:2em;
	  }
	  table.infotable td.forminfo { width: 80px; text-align: right }
	  table.infotable td.formlabel { width: 110px; text-align: right }
	</style>
	<insta:js-bundle prefix="laboratory.radiology.billpaymentcommon"/>
	<insta:js-bundle prefix="laboratory.radiology.incomingsampleregistration"/>
	<insta:js-bundle prefix="laboratory.radiology.batchconduction" />
	<insta:js-bundle prefix="order.common"/>
	<insta:js-bundle prefix="billing.salucro"/>
	<insta:js-bundle prefix="registration.patient"/>
</head>

<body class="yui-skin-sam"  onload="init();ajaxForPrintUrls();loadLoyaltyDialog();loadProcessPaymentDialog();hidePaymentModeForRegisterNewSample();" >
<c:set var="title">
 <insta:ltext key="laboratory.incomingsampleregistration.register.title1"/>
</c:set>
<c:set var="select">
 <insta:ltext key="selectdb.dummy.value"/>
</c:set>
<form method="post" name="sampleregform" action="${actionPath}" enctype="multipart/form-data">
<input type="hidden" name="_method" value="savePrescriptions"/>
<input type="hidden" name="referralDocId" />
<input type="hidden" name="labId"/>
<input type="hidden" name="category" value="${category != '' ? category : param.category}">
<input type="hidden" name="sampleAutoGeneratedIdReq" value=""/>
<input type="hidden" name="dateOfBirth" id="dateOfBirth"/>

<h1>${category == 'DEP_LAB' ? 'Incoming Sample Registration' : 'Incoming Radiology Test'}</h1>

<%
	int centerId = (Integer) session.getAttribute("centerId");
	Integer max_centers_inc_default = (Integer)
		com.insta.hms.master.GenericPreferences.GenericPreferencesDAO.getAllPrefs().get("max_centers_inc_default");
	if (max_centers_inc_default>1 && centerId == 0)
		request.setAttribute("error", "Registration allowed only for center users.");
%>
<insta:feedback-panel />

<table class="formtable" >
	<tr>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.incominghospital"/>:</td>
		<td colspan="6">
			<div class="myAutoComplete">
				<input type="text" name="orginalLabName" id="orginalLabName" maxlength="100" />
				<div id="orginalLabContainer" style="width:250px;"></div>
			</div>
		</td>
	</tr>
	<tr>
		<td class="formlabel"><insta:ltext key="ui.label.patient.name"/>:</td>
		<td class="forminfo" colspan="4">
			<insta:selectdb id="salutation" name="salutation" value="" table="salutation_master"
				valuecol="salutation"  displaycol="salutation" usecache="true" style="width: 60px;"
				class="dropdown" onchange="salChange()" dummyvalue="${title}"/>

			 <input type="text" name="patientname" id="patientname" onblur="capWords(patientname)" style="width: 400px"><span class="star"> *</span>
		</td>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.gender"/>:</td>
		<td class="forminfo">
			<select name="gender" style="width:8em;" id="gender" class="dropdown">
				<option value=""><insta:ltext key="laboratory.incomingsampleregistration.register.gender1"/></option>
				<option value="M"><insta:ltext key="laboratory.incomingsampleregistration.register.male"/></option>
				<option value="F"><insta:ltext key="laboratory.incomingsampleregistration.register.female"/></option>
			</select><span class="star"> *</span>
		</td>
	</tr>
	<tr>
        <td class="formlabel"><insta:ltext key="registration.patient.commonlabel.patientdateOfBirth"/>:</td>
		<td style="width: 230px; white-space: nowrap;" colspan=4>
			  <input type="text" class="field" style="width:30px;" size="2"
					 maxlength="2"  name="dobDay" id="dobDay" onkeypress="return enterNumOnly(event)"
				     id="dobDay" value="<insta:ltext key="registration.patient.show.dd.text"/>" onFocus="if (this.value == '<insta:ltext key="registration.patient.show.dd.text"/>') { this.value = ''}"
					 onBlur="if (this.value == '') { this.value = '<insta:ltext key="registration.patient.show.dd.text"/>'} else { if(hijriPref == 'Y') gregorianToHijriISR(); }" value="<%= com.insta.hms.common.Encoder.cleanJavaScript((String)request.getParameter("gregDay")) %>">

					 <input type="text" class="field" style="width:30px;" size="2"
							maxlength="2" name="dobMonth" id="dobMonth" value="<insta:ltext key="registration.patient.show.mm.text"/>"
							onFocus="if (this.value == '<insta:ltext key="registration.patient.show.mm.text"/>') { this.value = ''}"
							onBlur="if (this.value == '') { this.value = '<insta:ltext key="registration.patient.show.mm.text"/>'} else { if(hijriPref == 'Y') gregorianToHijriISR(); }" onkeypress="return enterNumOnly(event)" value="<%= com.insta.hms.common.Encoder.cleanJavaScript((String)request.getParameter("gregMonth")) %>" >

					<input type="text" class="field" size="4" maxlength="4" name="dobYear" id="dobYear"
						   style="width:40px;" onblur="if (this.value == '') { this.value = '<insta:ltext key="registration.patient.show.yy.text"/>' } else { return incomingSampleCalculateAgeAndHijri(); }"
						   value="<insta:ltext key="registration.patient.show.yy.text"/>" onkeypress="return enterNumOnly(event)"
						   onFocus="if (this.value == '<insta:ltext key="registration.patient.show.yy.text"/>') { this.value = ''}" value="<%= com.insta.hms.common.Encoder.cleanJavaScript((String)request.getParameter("gregYear")) %>"><insta:ltext key="registration.patient.commonlabel.or.within.brackets"/>
						   
					<c:choose>
						  <c:when test="${allowAgeEntry eq 'Y'}">
						        <input type="text" class="field" name="age" id="age" size="5"
										style="width:45px;"
										onBlur="if (this.value == '') { this.value = '<insta:ltext key="registration.patient.show.age.text"/>';}else{ wipeOutAddedTests();}"
										value="<insta:ltext key="registration.patient.show.age.text"/>" onFocus="if (this.value == '<insta:ltext key="registration.patient.show.age.text"/>') { this.value = ''}"
										onkeypress="return enterNumOnlyzeroToNine(event)" />
						  </c:when>
						  <c:otherwise>
								<input type="text" class="field" name="age" id="age" size="5"
										style="width:45px;"  readonly
										onBlur="if (this.value == '') { this.value = '<insta:ltext key="registration.patient.show.age.text"/>'}else{ wipeOutAddedTests();}}"
										value="<insta:ltext key="registration.patient.show.age.text"/>" onFocus="if (this.value == '<insta:ltext key="registration.patient.show.age.text"/>') { this.value = ''}"
										onkeypress="return enterNumOnlyzeroToNine(event)" />
						  </c:otherwise>
				    </c:choose>

					<c:choose>
						<c:when test="${allowAgeEntry eq 'Y'}">
								<select name="ageIn" id="ageIn" class="dropdown" style="width:70px;" onchange="wipeOutAddedTests()">
										<option value="Y"><insta:ltext key="registration.patient.commonselectbox.ageIn.years"/></option>
										<option value="M"><insta:ltext key="registration.patient.commonselectbox.ageIn.months"/></option>
										<option value="D"><insta:ltext key="registration.patient.commonselectbox.ageIn.days"/></option>
								</select>
						</c:when>
					<c:otherwise>
						 <select name="ageIn" id="ageIn" class="dropdown" style="width:70px;" disabled>
								<option value="Y"><insta:ltext key="registration.patient.commonselectbox.ageIn.years"/></option>
								<option value="M"><insta:ltext key="registration.patient.commonselectbox.ageIn.months"/></option>
								<option value="D"><insta:ltext key="registration.patient.commonselectbox.ageIn.days"/></option>
						</select>
					</c:otherwise>
				    </c:choose>
				<span class="star">*</span>
		</td>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.phoneno"/>:
		</td>
		<td class="forminfo" colspan="2">
		 	
		 	<div style="margin-top:12px;font-weight:normal">
		 		
				<div>
					<input type="hidden" id="phone_no" name="phone_no"/>
					<input type="hidden" id="phone_no_valid" value="Y"/>
					<select id="phone_no_country_code" class="dropdown" style="width:76px;" name="phone_no_country_code">
						<c:if test="${empty defaultCountryCode}">				
							<option value='+' selected> - Select - </option>
						</c:if>
						<c:forEach items="${countryList}" var="list">
							<c:choose>
								<c:when test="${ list[0] == defaultCountryCode}">				
									<option value='+${list[0]}' selected> +${list[0]}(${ list[1]})  </option>	
								</c:when>	
								<c:otherwise>
									<option value='+${list[0]}'> +${list[0]}(${list[1]})  </option>	
								</c:otherwise>
							</c:choose>
													  
						</c:forEach>
					</select>		
					 <input type="text" class="field" id="phone_no_national" maxlength ="15" onkeypress="return enterNumOnlyzeroToNine(event)"
							 style="width:9.6em;padding-top:1px" />
					
					<img class="imgHelpText" id="phone_no_help" src="${cpath}/images/help.png"/>
								
				</div>
				<div>
					<span style="visibility:hidden;padding-left:10px;color:#f00" id="phone_no_error"></span>	
				</div>

			</div>
		</td>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.patientotherinfo"/></td>
		<td class="forminfo">
			<input type="text" name="patient_other_info" id="patient_other_info" value="" maxlength="100">
		</td>
	</tr>
	<tr>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.billtype"/>:</td>
		<td>
		   <select name="billType" class="dropdown" onchange="onChangeBillType();">
			  <option value="BN" selected="selected"><insta:ltext key="laboratory.incomingsampleregistration.register.billnow"/></option>
			  <c:if test="${actionRightsMap.allow_credit_bill_later eq 'A' || roleId == 1 || roleId ==2}">
			  	<option value="BL" ><insta:ltext key="laboratory.incomingsampleregistration.register.billlater"/></option>
			  </c:if>
		   </select>
		</td>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.rateplan"/>:</td>
		<td >
			<select name='bill_rate_plan_id' id='bill_rate_plan_id' class="dropdown" onchange="return wipeOutAddedTests();" >
			</select>
		</td>
		<td></td>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.referraldoctor"/>:</td>	
		<td>
			<div class="myAutoComplete">
				<input type="text" name="referralDoctorName" id="referralDoctorName" maxlength="100"/>
				<div id="referralDoctorContainer" style="width:250px;"></div>
			</div>
		</td>

	</tr>
	
	<tr>
		<c:if test="${not empty regPref.government_identifier_type_label}">
			<td class="formlabel">${ifn:cleanHtml(regPref.government_identifier_type_label)}</td>
			<td>
				<select name="identifier_id" id="identifier_id" class="dropdown" style="width:137px;" onchange="setGovtPattern();">
					<option value="">--Select--</option>
					<c:forEach items="${govtIdentifierTypes}" var="govtIdTypes">
						<option value="${govtIdTypes.map.identifier_id}" ${govtIdTypes.map.default_option eq 'Y' ? 'selected' : ''}>
							${govtIdTypes.map.remarks}</option>
					</c:forEach>
				</select>
			</td>
			<c:set var="maincolumns" value="${maincolumns+1}"/>
			<c:if test="${(maincolumns % 3) == 0}"></tr><tr></c:if>
		</c:if> 
		<c:if test="${not empty regPref.government_identifier_label}">
			<td class="formlabel">${ifn:cleanHtml(regPref.government_identifier_label)}</td>
			<td>
				<input type="text" name="government_identifier" id="government_identifier" maxlength="50" onchange="onChangeOfGovtIdType();"/>
					<span id="govtidstar" class="star" style="display:none">*</span>
			</td>
			<c:set var="maincolumns" value="${maincolumns+1}"/>
			<c:if test="${(maincolumns % 3) == 0}"></tr><tr></c:if>
		</c:if>	
	</tr>

</table>

<br/>
<br/>

<div class="resultList" style="margin: 10px 0px 5px 0px;">
<table id="testdetails" class="resultList" width="100%" cellspacing="0" cellpadding="0">
	<tr>
		<th><insta:ltext key="laboratory.incomingsampleregistration.register.delete"/></th>
		<c:if test="${category == 'DEP_LAB'}">
			<th><insta:ltext key="laboratory.incomingsampleregistration.register.package"/></th>
		</c:if>
		<th><insta:ltext key="laboratory.incomingsampleregistration.register.testname"/></th>
		<c:if test="${category == 'DEP_LAB'}">
		<th><insta:ltext key="laboratory.incomingsampleregistration.register.sampletype"/></th>
		<th><insta:ltext key="laboratory.incomingsampleregistration.register.origsampleno"/></th>
		<th><insta:ltext key="laboratory.incomingsampleregistration.register.sampleid"/></th>
		<th><insta:ltext key="laboratory.incomingsampleregistration.register.outhouse"/></th>
		</c:if>
		<th style="text-align: right"><insta:ltext key="laboratory.incomingsampleregistration.register.charge"/></th>
		<th style="text-align: right"><insta:ltext key="laboratory.incomingsampleregistration.register.disc"/></th>
		<th style="text-align: right"><insta:ltext key="laboratory.incomingsampleregistration.register.amt"/></th>
		<th></th>
	</tr>
	<tr>
		<c:if test="${category == 'DEP_LAB'}"><td colspan="9"></td></c:if>
		<c:if test="${category == 'DEP_RAD'}"><td colspan="5"></td></c:if>
		<td>
			<button type="button" name="loadDialog" id="loadDialog" title='<insta:ltext key="laboratory.incomingsampleregistration.register.addtest"/>'
				onclick="getAddDialog(this);" style="float: right;"
				accesskey="+" class="imgButton"><img src="${cpath}/icons/Add.png"></button>
		</td>
	</tr>
</table>
</div>

<table align="right" class="infotable" style="margin-bottom: 10px">
	<tr>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.discount"/>:</td>
		<td class="forminfo"><input type="text" name="itemDiscPer" id="itemDiscPer" class="number" onblur="onApplyItemDiscPer();">%</td>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.discountauth"/>:</td>
		<td class="forminfo">
		  <select name="discountAuthName" id="discountAuthName" class="dropdown" >
			<option value="">-- Select --</option>
				<c:forEach var="discAuth" items="${discountAuthorizers}">
					<option value="${discAuth.map.disc_auth_id}">${discAuth.map.disc_auth_name}</option>
				</c:forEach>
			</select>
		</td>
		<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.total"/>:</td>
		<td class="forminfo">
			<label id="totalAmount"></label>
			<input type="hidden" id="totalDiscount1" value="0">
			<input type="hidden" id="totalAmount1" value="0">
		</td>
	</tr>
</table>

<jsp:include page="TestAdditionalDetailsInclude.jsp" />

<table style="margin-top: 10px">
	<tr>
	<td width="100%">
		<div id="paymentDetails">
		<fieldset class="fieldSetBorder">
			<legend class="fieldSetLabel"><insta:ltext key="laboratory.incomingsampleregistration.register.paymentdetails"/>:</legend>
				<table class="formtable" cellpadding="0" cellspacing="0" width="100%">

					<tr>
						<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.totalamountdue"/>:</td>
						<td>
							<input type="text" name="amountdue" id="amountdue"
								maxlength="50" class="number6dig" readonly="readonly">
						</td>
						<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.totalnetamounttopay"/>:</td>
						<td>
							<input type="text" name="amtPay" id="amtPay" maxlength="50"
							onchange="validateAmount();" class="number6dig" size="7" disabled="disabled">
						</td>
						<td></td>
						<td></td>
					</tr>

				</table>

				<insta:billPaymentDetails formName="sampleregform" isBillNowPayment="true"/>

		</fieldset>
		</div>
	</td>
	</tr>
</table>
<table id="innerCondDocForPack"></table>
<table class="formtable" width="100%">
	<tr>
		<td style=" display:none" id="bl">
			<div><button type="button" name="Save" accesskey="S" onclick="return saveDetails()"><b><u><insta:ltext key="laboratory.incomingsampleregistration.register.s"/></u></b><insta:ltext key="laboratory.incomingsampleregistration.register.ave"/></button></div>
		</td>
		<td id="bn">
			<div><button type="button" name="Save" accesskey="P" onclick="return saveDetails()"><b><u><insta:ltext key="laboratory.incomingsampleregistration.register.p"/></u></b><insta:ltext key="laboratory.incomingsampleregistration.register.ay.close"/></button></div>
		</td>
		<td align="right">
			<table>
				<tr>
					<td>
						<insta:selectdb name="sampleBardCodeTemplate" table="sample_bar_code_print_templates" valuecol="template_name"
							displaycol="template_name" filtered="false" value="${template_name}"/>
					</td>
					<td>
						<insta:selectdb name="printer" table="printer_definition"
							valuecol="printer_id"  displaycol="printer_definition_name"
							value="${pref.map.printer_id}"/>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div id="addDialog" style="visibility: hidden">
	<div class="bd">
		<fieldset class="fieldSetBorder" id="mainFieldSet">
		<legend class="fieldSetLabel"><insta:ltext key="laboratory.incomingsampleregistration.register.testdetails"/></legend>
		<table class="formtable">
			<tr>
				<c:choose>
					<c:when test="${category == 'DEP_LAB'}">
						<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.test.labpackage"/>:</td>
					</c:when>
					<c:otherwise>
						<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.test"/>:</td>
					</c:otherwise>
				</c:choose>
				<td class="forminfo" colspan="3">
					<div class="myAutoComplete">
						<input type="text" name="testnameObj" id="testnameObj" style="width:405px;"/>
						<div id="testContainer" style="width:450px;"></div>
					</div>
				</td>
				<c:if test="${category == 'DEP_LAB'}">
					<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.originalsampleno"/>:</td>
					<td class="forminfo">
						<input type="text" name="originalSampleNo" id="originalSampleNo"/>
						<c:if test="${genPrefs.sampleNoBase!='B'}">
							<span class="star"> *</span>
						</c:if>
					</td>
				</c:if>
			</tr>

			<c:choose>
				<c:when test="${category == 'DEP_LAB'}">
				<tr>
					<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.sampletype"/>:</td>
					<td class="forminfo">
						<insta:selectdb name="sampleType"
							id="sampleType" table="sample_type" valuecol="sample_type_id"
							displaycol="sample_type" dummyvalue="${select}" dummyvalueId="" />
					</td>
					<td class="formlabel" id="sampleIdlbl"><insta:ltext key="laboratory.incomingsampleregistration.register.sampleid"/>:</td>
					<td class="forminfo" id="sampleIdField">
						<input type="text" name="insampleId" id="insampleId" size='9' maxlength="50" ${isautogenerateSampleIdReq eq 'Y' ? 'readonly' : ''}>
					</td>
					<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.outhouse"/>:</td>
					<td class="forminfo" >
						<select name="outhouse" class="dropdown"  id="outhouse">
							<option value="">${select}</option>
						</select>
					</td>
				</tr>
				</c:when>
			</c:choose>
			<tr>
				<td class="formlabel"><insta:ltext key="common.addorder.conducting.doctor"/>:</td>
				<td class="yui-skin-sam"  valign="top">
					<div style="width: 138px">
						<input type="text" id="conducting_doctor" name="conducting_doctor" style="width:285px; disabled="disabled"/>
						<div id="conducting_doctorAcDropdown" style="width:350px;"></div>
					</div>
					<input type="hidden" name="conducting_doctorId"/>
				</td>
				<td></td>
				<td></td>
			</tr>
		</table>
		</fieldset>

		<fieldset class="fieldSetBorder" id="conductingDoctorFS" style="display: none">
			<legend class="fieldSetLabel"><insta:ltext key="laboratory.incomingsampleregistration.conducting.doctors"></insta:ltext></legend>
			<table class="detailList" id="conductingDoctorsTable">
				<tr>
					<th><insta:ltext key="laboratory.incomingsampleregistration.conducting.activity_type"/></th>
					<th><insta:ltext key="laboratory.incomingsampleregistration.conducting.test_name"/></th>
					<th><insta:ltext key="laboratory.incomingsampleregistration.conducting.doctor_name"/></th>
				</tr>
			</table>
		</fieldset>

		<table>
			<tr>
				<td>
					<button type="button" name="addBtn" accesskey="A" onclick="addTest()">
					<b><u><insta:ltext key="laboratory.incomingsampleregistration.register.a"/></u></b><insta:ltext key="laboratory.incomingsampleregistration.register.dd"/></button>
				</td>
				<td>
					<c:set var="prevButton">
						<insta:ltext key="laboratory.incomingsampleregistration.previous"/>
					</c:set>
					<input type="button" name="addPrevious" onclick="onPrevious()" value="${prevButton}"/>
				</td>
				<td>
					<c:set var="nextButton">
						<insta:ltext key="laboratory.incomingsampleregistration.next"/>
					</c:set>
					<input type="button" name="addNext" onclick="onNext()" value="${nextButton}" />
				</td>
				<td>&nbsp;|&nbsp;</td>
				<td>
					<button type="button" accesskey="C" onclick="closeDialog();"><b><u><insta:ltext key="laboratory.incomingsampleregistration.register.c"/></u></b><insta:ltext key="laboratory.incomingsampleregistration.register.lose"/></button>
				</td>
			</tr>
		</table>
	</div>
</div>

<div id="editDialog" style="visibility: hidden">
	<div class="bd">
		<fieldset class="fieldSetBorder">
		<legend class="fieldSetLabel"><insta:ltext key="laboratory.incomingsampleregistration.register.testdetails"/></legend>
		<table class="formtable">
			<tr>
				<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.test"/>:</td>
				<td class="forminfo">
					<label id="e_testlbl"></label>
					<input type="hidden" name="dialogId" id="dialogId" value=""/>
				</td>
				<c:choose>
					<c:when test="${category == 'DEP_LAB'}">
						<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.sampletype"/>:</td>
						<td class="forminfo">
							<insta:selectdb name="e_sampleType"
								id="e_sampleType" table="sample_type" valuecol="sample_type_id"
								displaycol="sample_type" dummyvalue="${select}" dummyvalueId="" />
						</td>
					</c:when>
					<c:otherwise>
						<td></td>
					</c:otherwise>
				</c:choose>
			</tr>
			<tr>
			</tr>
			<tr>
				<c:if test="${category == 'DEP_LAB'}">
					<td class="formlabel" id="e_sampleIdlbl"><insta:ltext key="laboratory.incomingsampleregistration.register.sampleid"/>:</td>
					<td class="forminfo" id="e_sampleIdField">
						<input type="text" name="e_insampleId" id="e_insampleId" size='9' maxlength="50" ${isautogenerateSampleIdReq eq 'Y' ? 'readonly' : ''}>
					</td>
					<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.originalsampleno"/>:</td>
					<td class="forminfo">
						<input type="text" name="e_originalSampleNo" id="e_originalSampleNo"/>
						<c:if test="${genPrefs.sampleNoBase!='B'}">
							<span class="star"> *</span>
						</c:if>
					</td>
					<td class="formlabel"><insta:ltext key="laboratory.incomingsampleregistration.register.outhouse"/>:</td>
					<td class="forminfo" >
						<select name="editOuthouseEle" class="dropdown"  id="editOuthouseEle">
							<option value="">${select}</option>
						</select>
					</td>
				</c:if>

			</tr>
		</table>
		</fieldset>

		<table>
			<tr>
				<td>
					<button type="button" name="add" accesskey="A" onclick="saveTest('add')">
					<b><u><insta:ltext key="laboratory.incomingsampleregistration.register.o"/></u></b><insta:ltext key="laboratory.incomingsampleregistration.register.k"/></button>
				</td>
				<td>
					<button type="button" accesskey="C" onclick="closeEditDialog();"><b><u><insta:ltext key="laboratory.incomingsampleregistration.register.c"/></u></b><insta:ltext key="laboratory.incomingsampleregistration.register.ancel"/></button>
				</td>
				<td><input type="button" onclick="showNextOrPrevTest('prev')" name="prevBtn" id="prevBtn" value="<<Prev"/></td>
				<td><input type="button" onclick="showNextOrPrevTest('next')" name="nextBtn"  id="nextBtn" value="Next>>"/></td>
			</tr>
		</table>
	</div>
</div>

</form>
<insta:link type="js" file="select2.min.js"/>
<script type="text/javascript">

	incomingHospitalJSON = ${incomingHospitalJSON};
	referalDoctorsJSON = ${referalDoctorsJSON};
	var salutationJSON = ${salutationQueryJson};
	var specimenType=${specimenType};
	var isSampleIdAutoGenerateReq="<%= request.getAttribute("isautogenerateSampleIdReq") %>";
	var category = '${ifn:cleanJavaScript(category)}';
	var printType = '${genPrefs.sampleCollectionPrintType}';
	var cpath = '${cpath}';
	var centerId = ${centerId};
	var max_centers_inc_default = ${max_centers_inc_default};
	var sampleNoGeneration = '${genPrefs.sampleNoBase}';
	var outhousesAgainstTestsJson = ${outhousesAgainstTestsJson};
	var url = '${cpath}/gettests.do?${masterTimeStamp}&${ifn:cleanJavaScript(sesHospitalId)}&module=${ifn:cleanJavaScript(category)}&packages=Y&center_id=${centerId}';
	var billNumber = 'ISR'; // Use this store as reference to Paytm transaction
	//Phone number logic
	(function(){
		var patientPhone = $("#phone_no");		
		var patientPhoneNational=$("#phone_no_national");
		var patientPhoneCountryCode=$("#phone_no_country_code");
		var patientPhoneHelp=$("#phone_no_help");
		var patientPhoneError =$("#phone_no_error");
		var patientPhoneValid = $("#phone_no_valid");

		
		patientPhoneCountryCode.select2();
		
		patientPhoneCountryCode.on('change', function (e) {
			//get text for help menu
		    getExamplePhoneNumber(this.value,patientPhoneHelp,patientPhoneError);
		});
		
		patientPhoneCountryCode.on('select2:select', function (e) {
		    patientPhoneNational.focus();
		});	
		
		patientPhoneNational.on('blur',function(e,eventDataObj){

			clearErrorsAndValidatePhoneNumber(patientPhone,patientPhoneValid,
					patientPhoneNational,patientPhoneCountryCode,patientPhoneError,'N',eventDataObj);
				
		});
		// Get help text for phone_no
		getExamplePhoneNumber(defaultCountryCode,patientPhoneHelp,patientPhoneError);
	
})();
</script>
<jsp:include page="/pages/dialogBox/processPaymentDialog.jsp"></jsp:include>
<jsp:include page="/pages/dialogBox/loyaltyDialog.jsp"></jsp:include>
</body>
</html>
