package com.insta.hms.core.clinical.outpatient;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Arrays;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DoctorConsultImagesIdSequence generated by hbm2java
 */
@Embeddable
public class DoctorConsultImagesIdSequence implements java.io.Serializable {

	private Integer consultationId;
	private byte[] image;
	private String contentType;
	private Date datetime;
	private Integer imageId;

	public DoctorConsultImagesIdSequence() {
	}

	public DoctorConsultImagesIdSequence(Integer consultationId, byte[] image, String contentType, Date datetime,
			Integer imageId) {
		this.consultationId = consultationId;
		this.image = image;
		this.contentType = contentType;
		this.datetime = datetime;
		this.imageId = imageId;
	}

	@Column(name = "consultation_id")
	public Integer getConsultationId() {
		return this.consultationId;
	}

	public void setConsultationId(Integer consultationId) {
		this.consultationId = consultationId;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "content_type")
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "datetime", length = 29)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "image_id")
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DoctorConsultImagesIdSequence))
			return false;
		DoctorConsultImagesIdSequence castOther = (DoctorConsultImagesIdSequence) other;

		return ((this.getConsultationId() == castOther.getConsultationId())
				|| (this.getConsultationId() != null && castOther.getConsultationId() != null
						&& this.getConsultationId().equals(castOther.getConsultationId())))
				&& ((this.getImage() == castOther.getImage()) || (this.getImage() != null
						&& castOther.getImage() != null && Arrays.equals(this.getImage(), castOther.getImage())))
				&& ((this.getContentType() == castOther.getContentType())
						|| (this.getContentType() != null && castOther.getContentType() != null
								&& this.getContentType().equals(castOther.getContentType())))
				&& ((this.getDatetime() == castOther.getDatetime()) || (this.getDatetime() != null
						&& castOther.getDatetime() != null && this.getDatetime().equals(castOther.getDatetime())))
				&& ((this.getImageId() == castOther.getImageId()) || (this.getImageId() != null
						&& castOther.getImageId() != null && this.getImageId().equals(castOther.getImageId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getConsultationId() == null ? 0 : this.getConsultationId().hashCode());
		int imageHashcode = 0;
		byte[] imageProperty = this.getImage();
		if (imageProperty != null) {
			imageHashcode = 1;
			for (int i = 0; i < imageProperty.length; i++) {
				imageHashcode = 37 * imageHashcode + imageProperty[i];
			}
		}

		result = 37 * result + imageHashcode;

		result = 37 * result + (getContentType() == null ? 0 : this.getContentType().hashCode());
		result = 37 * result + (getDatetime() == null ? 0 : this.getDatetime().hashCode());
		result = 37 * result + (getImageId() == null ? 0 : this.getImageId().hashCode());
		return result;
	}

}
