package com.insta.hms.mdm.dialysisaccesstypes;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DialysisAccessTypesModel generated by hbm2java
 */
@Entity
@Table(name = "dialysis_access_types", uniqueConstraints = @UniqueConstraint(columnNames = "access_type"))
public class DialysisAccessTypesModel implements java.io.Serializable {

	private int accessTypeId;
	private String accessType;
	private String description;
	private Character status;
	private Character accessPatency;
	private Character accessMode;
	private String accessCategory;
	private Set dialysisSessions = new HashSet(0);

	public DialysisAccessTypesModel() {
	}

	public DialysisAccessTypesModel(int accessTypeId, String accessType, String accessCategory) {
		this.accessTypeId = accessTypeId;
		this.accessType = accessType;
		this.accessCategory = accessCategory;
	}

	public DialysisAccessTypesModel(int accessTypeId, String accessType, String description, Character status,
			Character accessPatency, Character accessMode, String accessCategory, Set dialysisSessions) {
		this.accessTypeId = accessTypeId;
		this.accessType = accessType;
		this.description = description;
		this.status = status;
		this.accessPatency = accessPatency;
		this.accessMode = accessMode;
		this.accessCategory = accessCategory;
		this.dialysisSessions = dialysisSessions;
	}

	@Id

	@Column(name = "access_type_id", unique = true, nullable = false)
	public int getAccessTypeId() {
		return this.accessTypeId;
	}

	public void setAccessTypeId(int accessTypeId) {
		this.accessTypeId = accessTypeId;
	}

	@Column(name = "access_type", unique = true, nullable = false, length = 30)
	public String getAccessType() {
		return this.accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "access_patency", length = 1)
	public Character getAccessPatency() {
		return this.accessPatency;
	}

	public void setAccessPatency(Character accessPatency) {
		this.accessPatency = accessPatency;
	}

	@Column(name = "access_mode", length = 1)
	public Character getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(Character accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "access_category", nullable = false, length = 5)
	public String getAccessCategory() {
		return this.accessCategory;
	}

	public void setAccessCategory(String accessCategory) {
		this.accessCategory = accessCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dialysisAccessTypes")
	public Set getDialysisSessions() {
		return this.dialysisSessions;
	}

	public void setDialysisSessions(Set dialysisSessions) {
		this.dialysisSessions = dialysisSessions;
	}

}
