package com.insta.hms.mdm.item;

// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.servicesubgroup.ServiceSubGroupModel;
import com.insta.hms.model.StoreCategoryMasterModel;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StoreItemDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "store_item_details", uniqueConstraints = {
    @UniqueConstraint(columnNames = "medicine_name"),
    @UniqueConstraint(columnNames = "item_barcode_id"),
    @UniqueConstraint(columnNames = "cust_item_code") })
public class StoreItemDetailsModel implements java.io.Serializable {

  private int medicineId;
  private String medicineName;
  private String genericName;
  private String composition;
  private String therapaticUse;
  private BigDecimal issueBaseUnit;
  private String packageType;
  private char HDrugStatus;
  private char status;
  private String medicineShortName;
  private Integer medCategoryId;
  private String issueUnits;
  private BigDecimal maxCostPrice;
  private BigDecimal issueQty;
  private char value;
  private String supplierName;
  private String invoiceDetails;
  private String itemCodeObsolete;
  private String codeTypeObsolete;
  private ServiceSubGroupModel serviceSubGroupId;
  private String obsoleteConsumptionUom;
  private BigDecimal consumptionCapacity;
  private Integer insuranceCategoryId;
  private Integer controlTypeId;
  private String routeOfAdmin;
  private String itemBarcodeId;
  private String codeDesc;
  private Character priorAuthRequired;
  private String packageUom;
  private String obsoletePreferredSupplier;
  private Integer itemFormId;
  private String itemStrength;
  private Date createdTimestamp;
  private Date updatedTimestamp;
  private BigDecimal taxRate;
  private String taxType;
  private String bin;
  private Character batchNoApplicable;
  private BigDecimal itemSellingPrice;
  private Integer itemStrengthUnits;
  private Character highCostConsumable;
  private String custItemCode;
  private StoreCategoryMasterModel storeCategoryMaster;
  private Integer consUomId;

  public StoreItemDetailsModel() {
  }

  public StoreItemDetailsModel(int medicineId, String medicineName, BigDecimal issueBaseUnit,
      char HDrugStatus, char status, char value, ServiceSubGroupModel serviceSubGroupId,
      BigDecimal consumptionCapacity, Date createdTimestamp, Date updatedTimestamp,
      BigDecimal taxRate, String taxType) {
    this.medicineId = medicineId;
    this.medicineName = medicineName;
    this.issueBaseUnit = issueBaseUnit;
    this.HDrugStatus = HDrugStatus;
    this.status = status;
    this.value = value;
    this.serviceSubGroupId = serviceSubGroupId;
    this.consumptionCapacity = consumptionCapacity;
    this.createdTimestamp = createdTimestamp;
    this.updatedTimestamp = updatedTimestamp;
    this.taxRate = taxRate;
    this.taxType = taxType;
  }

  public StoreItemDetailsModel(int medicineId, String medicineName, String genericName,
      String composition, String therapaticUse, BigDecimal issueBaseUnit, String packageType,
      char HDrugStatus, char status, String medicineShortName, Integer medCategoryId,
      String issueUnits, BigDecimal maxCostPrice, BigDecimal issueQty, char value,
      String supplierName, String invoiceDetails, String itemCodeObsolete, String codeTypeObsolete,
      ServiceSubGroupModel serviceSubGroupId, String consumptionUom,
      BigDecimal consumptionCapacity, Integer insuranceCategoryId, Integer controlTypeId,
      String routeOfAdmin, String itemBarcodeId, String codeDesc, Character priorAuthRequired,
      String packageUom, String obsoletePreferredSupplier, Integer itemFormId, String itemStrength,
      Date createdTimestamp, Date updatedTimestamp, BigDecimal taxRate, String taxType, String bin,
      Character batchNoApplicable, BigDecimal itemSellingPrice, Integer itemStrengthUnits,
      Character highCostConsumable, String custItemCode, Integer consUomId) {
    this.medicineId = medicineId;
    this.medicineName = medicineName;
    this.genericName = genericName;
    this.composition = composition;
    this.therapaticUse = therapaticUse;
    this.issueBaseUnit = issueBaseUnit;
    this.packageType = packageType;
    this.HDrugStatus = HDrugStatus;
    this.status = status;
    this.medicineShortName = medicineShortName;
    this.medCategoryId = medCategoryId;
    this.issueUnits = issueUnits;
    this.maxCostPrice = maxCostPrice;
    this.issueQty = issueQty;
    this.value = value;
    this.supplierName = supplierName;
    this.invoiceDetails = invoiceDetails;
    this.itemCodeObsolete = itemCodeObsolete;
    this.codeTypeObsolete = codeTypeObsolete;
    this.serviceSubGroupId = serviceSubGroupId;
    this.obsoleteConsumptionUom = consumptionUom;
    this.consumptionCapacity = consumptionCapacity;
    this.insuranceCategoryId = insuranceCategoryId;
    this.controlTypeId = controlTypeId;
    this.routeOfAdmin = routeOfAdmin;
    this.itemBarcodeId = itemBarcodeId;
    this.codeDesc = codeDesc;
    this.priorAuthRequired = priorAuthRequired;
    this.packageUom = packageUom;
    this.obsoletePreferredSupplier = obsoletePreferredSupplier;
    this.itemFormId = itemFormId;
    this.itemStrength = itemStrength;
    this.createdTimestamp = createdTimestamp;
    this.updatedTimestamp = updatedTimestamp;
    this.taxRate = taxRate;
    this.taxType = taxType;
    this.bin = bin;
    this.batchNoApplicable = batchNoApplicable;
    this.itemSellingPrice = itemSellingPrice;
    this.itemStrengthUnits = itemStrengthUnits;
    this.highCostConsumable = highCostConsumable;
    this.custItemCode = custItemCode;
    this.consUomId = consUomId;
  }

  @Id
  @Column(name = "medicine_id", unique = true, nullable = false)
  public int getMedicineId() {
    return this.medicineId;
  }

  public void setMedicineId(int medicineId) {
    this.medicineId = medicineId;
  }

  @Column(name = "medicine_name", unique = true, nullable = false, length = 200)
  public String getMedicineName() {
    return this.medicineName;
  }

  public void setMedicineName(String medicineName) {
    this.medicineName = medicineName;
  }

  @Column(name = "generic_name", length = 30)
  public String getGenericName() {
    return this.genericName;
  }

  public void setGenericName(String genericName) {
    this.genericName = genericName;
  }

  @Column(name = "composition", length = 150)
  public String getComposition() {
    return this.composition;
  }

  public void setComposition(String composition) {
    this.composition = composition;
  }

  @Column(name = "therapatic_use", length = 200)
  public String getTherapaticUse() {
    return this.therapaticUse;
  }

  public void setTherapaticUse(String therapaticUse) {
    this.therapaticUse = therapaticUse;
  }

  @Column(name = "issue_base_unit", nullable = false, precision = 131089, scale = 0)
  public BigDecimal getIssueBaseUnit() {
    return this.issueBaseUnit;
  }

  public void setIssueBaseUnit(BigDecimal issueBaseUnit) {
    this.issueBaseUnit = issueBaseUnit;
  }

  @Column(name = "package_type", length = 50)
  public String getPackageType() {
    return this.packageType;
  }

  public void setPackageType(String packageType) {
    this.packageType = packageType;
  }

  @Column(name = "h_drug_status", nullable = false, length = 1)
  public char getHDrugStatus() {
    return this.HDrugStatus;
  }

  public void setHDrugStatus(char HDrugStatus) {
    this.HDrugStatus = HDrugStatus;
  }

  @Column(name = "status", nullable = false, length = 1)
  public char getStatus() {
    return this.status;
  }

  public void setStatus(char status) {
    this.status = status;
  }

  @Column(name = "medicine_short_name", length = 200)
  public String getMedicineShortName() {
    return this.medicineShortName;
  }

  public void setMedicineShortName(String medicineShortName) {
    this.medicineShortName = medicineShortName;
  }

  @Column(name = "med_category_id")
  public Integer getMedCategoryId() {
    return this.medCategoryId;
  }

  public void setMedCategoryId(Integer medCategoryId) {
    this.medCategoryId = medCategoryId;
  }

  @Column(name = "issue_units", length = 100)
  public String getIssueUnits() {
    return this.issueUnits;
  }

  public void setIssueUnits(String issueUnits) {
    this.issueUnits = issueUnits;
  }

  @Column(name = "max_cost_price", precision = 15)
  public BigDecimal getMaxCostPrice() {
    return this.maxCostPrice;
  }

  public void setMaxCostPrice(BigDecimal maxCostPrice) {
    this.maxCostPrice = maxCostPrice;
  }

  @Column(name = "issue_qty", precision = 131089, scale = 0)
  public BigDecimal getIssueQty() {
    return this.issueQty;
  }

  public void setIssueQty(BigDecimal issueQty) {
    this.issueQty = issueQty;
  }

  @Column(name = "value", nullable = false, length = 1)
  public char getValue() {
    return this.value;
  }

  public void setValue(char value) {
    this.value = value;
  }

  @Column(name = "supplier_name", length = 100)
  public String getSupplierName() {
    return this.supplierName;
  }

  public void setSupplierName(String supplierName) {
    this.supplierName = supplierName;
  }

  @Column(name = "invoice_details", length = 100)
  public String getInvoiceDetails() {
    return this.invoiceDetails;
  }

  public void setInvoiceDetails(String invoiceDetails) {
    this.invoiceDetails = invoiceDetails;
  }

  @Column(name = "item_code_obsolete")
  public String getItemCodeObsolete() {
    return this.itemCodeObsolete;
  }

  public void setItemCodeObsolete(String itemCodeObsolete) {
    this.itemCodeObsolete = itemCodeObsolete;
  }

  @Column(name = "code_type_obsolete", length = 50)
  public String getCodeTypeObsolete() {
    return this.codeTypeObsolete;
  }

  public void setCodeTypeObsolete(String codeTypeObsolete) {
    this.codeTypeObsolete = codeTypeObsolete;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "service_sub_group_id", nullable = false, insertable = false, updatable = false)
  public ServiceSubGroupModel getServiceSubGroupId() {
    return this.serviceSubGroupId;
  }

  public void setServiceSubGroupId(ServiceSubGroupModel serviceSubGroupId) {
    this.serviceSubGroupId = serviceSubGroupId;
  }

  @Column(name = "obsolete_consumption_uom", length = 50)
  public String getConsumptionUom() {
    return this.obsoleteConsumptionUom;
  }

  public void setConsumptionUom(String consumptionUom) {
    this.obsoleteConsumptionUom = consumptionUom;
  }

  @Column(name = "consumption_capacity", nullable = false, precision = 10)
  public BigDecimal getConsumptionCapacity() {
    return this.consumptionCapacity;
  }

  public void setConsumptionCapacity(BigDecimal consumptionCapacity) {
    this.consumptionCapacity = consumptionCapacity;
  }

  @Column(name = "insurance_category_id")
  public Integer getInsuranceCategoryId() {
    return this.insuranceCategoryId;
  }

  public void setInsuranceCategoryId(Integer insuranceCategoryId) {
    this.insuranceCategoryId = insuranceCategoryId;
  }

  @Column(name = "control_type_id")
  public Integer getControlTypeId() {
    return this.controlTypeId;
  }

  public void setControlTypeId(Integer controlTypeId) {
    this.controlTypeId = controlTypeId;
  }

  @Column(name = "route_of_admin")
  public String getRouteOfAdmin() {
    return this.routeOfAdmin;
  }

  public void setRouteOfAdmin(String routeOfAdmin) {
    this.routeOfAdmin = routeOfAdmin;
  }

  @Column(name = "item_barcode_id", unique = true)
  public String getItemBarcodeId() {
    return this.itemBarcodeId;
  }

  public void setItemBarcodeId(String itemBarcodeId) {
    this.itemBarcodeId = itemBarcodeId;
  }

  @Column(name = "code_desc")
  public String getCodeDesc() {
    return this.codeDesc;
  }

  public void setCodeDesc(String codeDesc) {
    this.codeDesc = codeDesc;
  }

  @Column(name = "prior_auth_required", length = 1)
  public Character getPriorAuthRequired() {
    return this.priorAuthRequired;
  }

  public void setPriorAuthRequired(Character priorAuthRequired) {
    this.priorAuthRequired = priorAuthRequired;
  }

  @Column(name = "package_uom", length = 100)
  public String getPackageUom() {
    return this.packageUom;
  }

  public void setPackageUom(String packageUom) {
    this.packageUom = packageUom;
  }

  @Column(name = "obsolete_preferred_supplier", length = 100)
  public String getObsoletePreferredSupplier() {
    return this.obsoletePreferredSupplier;
  }

  public void setObsoletePreferredSupplier(String obsoletePreferredSupplier) {
    this.obsoletePreferredSupplier = obsoletePreferredSupplier;
  }

  @Column(name = "item_form_id")
  public Integer getItemFormId() {
    return this.itemFormId;
  }

  public void setItemFormId(Integer itemFormId) {
    this.itemFormId = itemFormId;
  }

  @Column(name = "item_strength", length = 50)
  public String getItemStrength() {
    return this.itemStrength;
  }

  public void setItemStrength(String itemStrength) {
    this.itemStrength = itemStrength;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "created_timestamp", nullable = false, length = 29)
  public Date getCreatedTimestamp() {
    return this.createdTimestamp;
  }

  public void setCreatedTimestamp(Date createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updated_timestamp", nullable = false, length = 29)
  public Date getUpdatedTimestamp() {
    return this.updatedTimestamp;
  }

  public void setUpdatedTimestamp(Date updatedTimestamp) {
    this.updatedTimestamp = updatedTimestamp;
  }

  @Column(name = "tax_rate", nullable = false, precision = 131089, scale = 0)
  public BigDecimal getTaxRate() {
    return this.taxRate;
  }

  public void setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
  }

  @Column(name = "tax_type", nullable = false, length = 2)
  public String getTaxType() {
    return this.taxType;
  }

  public void setTaxType(String taxType) {
    this.taxType = taxType;
  }

  @Column(name = "bin", length = 50)
  public String getBin() {
    return this.bin;
  }

  public void setBin(String bin) {
    this.bin = bin;
  }

  @Column(name = "batch_no_applicable", length = 1)
  public Character getBatchNoApplicable() {
    return this.batchNoApplicable;
  }

  public void setBatchNoApplicable(Character batchNoApplicable) {
    this.batchNoApplicable = batchNoApplicable;
  }

  @Column(name = "item_selling_price", precision = 131089, scale = 0)
  public BigDecimal getItemSellingPrice() {
    return this.itemSellingPrice;
  }

  public void setItemSellingPrice(BigDecimal itemSellingPrice) {
    this.itemSellingPrice = itemSellingPrice;
  }

  @Column(name = "item_strength_units")
  public Integer getItemStrengthUnits() {
    return this.itemStrengthUnits;
  }

  public void setItemStrengthUnits(Integer itemStrengthUnits) {
    this.itemStrengthUnits = itemStrengthUnits;
  }

  @Column(name = "high_cost_consumable", length = 1)
  public Character getHighCostConsumable() {
    return this.highCostConsumable;
  }

  public void setHighCostConsumable(Character highCostConsumable) {
    this.highCostConsumable = highCostConsumable;
  }

  @Column(name = "cust_item_code", unique = true, length = 20)
  public String getCustItemCode() {
    return this.custItemCode;
  }

  public void setCustItemCode(String custItemCode) {
    this.custItemCode = custItemCode;
  }
  
  @Column(name = "cons_uom_id")
  public Integer getConsUomId() {
    return this.consUomId;
  }
  
  public void setConsUomId(Integer consUomId) {
    this.consUomId = consUomId;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "med_category_id", referencedColumnName = "category_id", nullable = false, insertable = false, updatable = false)
  public StoreCategoryMasterModel getStoreCategoryMaster() {
    return storeCategoryMaster;
  }

  public void setStoreCategoryMaster(StoreCategoryMasterModel storeCategoryMaster) {
    this.storeCategoryMaster = storeCategoryMaster;
  }

}
