package com.insta.hms.mdm.vitalparameters;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VitalParameterMasterModel generated by hbm2java
 */
@Entity
@Table(name = "vital_parameter_master")
public class VitalParameterMasterModel implements java.io.Serializable {

	private int paramId;
	private char paramContainer;
	private String paramLabel;
	private String paramUom;
	private int paramOrder;
	private char paramStatus;
	private char mandatoryInTx;
	private String observationType;
	private String observationCode;
	private String visitType;
	private String exprForCalcResult;
	private Character systemVital;
	private Set vitalReadings = new HashSet(0);
	private Set vitalReferenceRangeMasters = new HashSet(0);

	public VitalParameterMasterModel() {
	}

	public VitalParameterMasterModel(int paramId, char paramContainer, String paramLabel, int paramOrder, char paramStatus,
			char mandatoryInTx) {
		this.paramId = paramId;
		this.paramContainer = paramContainer;
		this.paramLabel = paramLabel;
		this.paramOrder = paramOrder;
		this.paramStatus = paramStatus;
		this.mandatoryInTx = mandatoryInTx;
	}

	public VitalParameterMasterModel(int paramId, char paramContainer, String paramLabel, String paramUom, int paramOrder,
			char paramStatus, char mandatoryInTx, String observationType, String observationCode, String visitType,
			String exprForCalcResult, Character systemVital, Set vitalReadings, Set vitalReferenceRangeMasters) {
		this.paramId = paramId;
		this.paramContainer = paramContainer;
		this.paramLabel = paramLabel;
		this.paramUom = paramUom;
		this.paramOrder = paramOrder;
		this.paramStatus = paramStatus;
		this.mandatoryInTx = mandatoryInTx;
		this.observationType = observationType;
		this.observationCode = observationCode;
		this.visitType = visitType;
		this.exprForCalcResult = exprForCalcResult;
		this.systemVital = systemVital;
		this.vitalReadings = vitalReadings;
		this.vitalReferenceRangeMasters = vitalReferenceRangeMasters;
	}

	@Id

	@Column(name = "param_id", unique = true, nullable = false)
	public int getParamId() {
		return this.paramId;
	}

	public void setParamId(int paramId) {
		this.paramId = paramId;
	}

	@Column(name = "param_container", nullable = false, length = 1)
	public char getParamContainer() {
		return this.paramContainer;
	}

	public void setParamContainer(char paramContainer) {
		this.paramContainer = paramContainer;
	}

	@Column(name = "param_label", nullable = false, length = 50)
	public String getParamLabel() {
		return this.paramLabel;
	}

	public void setParamLabel(String paramLabel) {
		this.paramLabel = paramLabel;
	}

	@Column(name = "param_uom", length = 15)
	public String getParamUom() {
		return this.paramUom;
	}

	public void setParamUom(String paramUom) {
		this.paramUom = paramUom;
	}

	@Column(name = "param_order", nullable = false)
	public int getParamOrder() {
		return this.paramOrder;
	}

	public void setParamOrder(int paramOrder) {
		this.paramOrder = paramOrder;
	}

	@Column(name = "param_status", nullable = false, length = 1)
	public char getParamStatus() {
		return this.paramStatus;
	}

	public void setParamStatus(char paramStatus) {
		this.paramStatus = paramStatus;
	}

	@Column(name = "mandatory_in_tx", nullable = false, length = 1)
	public char getMandatoryInTx() {
		return this.mandatoryInTx;
	}

	public void setMandatoryInTx(char mandatoryInTx) {
		this.mandatoryInTx = mandatoryInTx;
	}

	@Column(name = "observation_type", length = 50)
	public String getObservationType() {
		return this.observationType;
	}

	public void setObservationType(String observationType) {
		this.observationType = observationType;
	}

	@Column(name = "observation_code", length = 15)
	public String getObservationCode() {
		return this.observationCode;
	}

	public void setObservationCode(String observationCode) {
		this.observationCode = observationCode;
	}

	@Column(name = "visit_type", length = 1)
	public String getVisitType() {
		return this.visitType;
	}

	public void setVisitType(String visitType) {
		this.visitType = visitType;
	}

	@Column(name = "expr_for_calc_result", length = 100)
	public String getExprForCalcResult() {
		return this.exprForCalcResult;
	}

	public void setExprForCalcResult(String exprForCalcResult) {
		this.exprForCalcResult = exprForCalcResult;
	}

	@Column(name = "system_vital", length = 1)
	public Character getSystemVital() {
		return this.systemVital;
	}

	public void setSystemVital(Character systemVital) {
		this.systemVital = systemVital;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vitalParameterMaster")
	public Set getVitalReadings() {
		return this.vitalReadings;
	}

	public void setVitalReadings(Set vitalReadings) {
		this.vitalReadings = vitalReadings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vitalParameterMaster")
	public Set getVitalReferenceRangeMasters() {
		return this.vitalReferenceRangeMasters;
	}

	public void setVitalReferenceRangeMasters(Set vitalReferenceRangeMasters) {
		this.vitalReferenceRangeMasters = vitalReferenceRangeMasters;
	}

}
