
package com.insta.hms.ceed.generated_test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Gateway", targetNamespace = "http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", wsdlLocation = "https://eclaimlink.dimensions-healthcare.net/DHCEG/gateway.asmx?wsdl")
public class Gateway
    extends Service
{

    private final static URL GATEWAY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.insta.hms.ceed.generated_test.Gateway.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.insta.hms.ceed.generated_test.Gateway.class.getResource(".");
            url = new URL(baseUrl, "https://eclaimlink.dimensions-healthcare.net/DHCEG/gateway.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://eclaimlink.dimensions-healthcare.net/DHCEG/gateway.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GATEWAY_WSDL_LOCATION = url;
    }

    public Gateway(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Gateway() {
        super(GATEWAY_WSDL_LOCATION, new QName("http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", "Gateway"));
    }

    /**
     * 
     * @return
     *     returns GatewaySoap
     */
    @WebEndpoint(name = "GatewaySoap")
    public GatewaySoap getGatewaySoap() {
        return super.getPort(new QName("http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", "GatewaySoap"), GatewaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GatewaySoap
     */
    @WebEndpoint(name = "GatewaySoap")
    public GatewaySoap getGatewaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", "GatewaySoap"), GatewaySoap.class, features);
    }

}
