package com.insta.hms.mdm.insuranceplandetails;
// default package
// Generated Dec 6, 2017 5:49:34 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * InsurancePlanDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "insurance_plan_details", uniqueConstraints = @UniqueConstraint(columnNames = "insurance_plan_details_id"))
public class InsurancePlanDetailsModel implements java.io.Serializable {

	private InsurancePlanDetailsIdSequence id;
	private BigDecimal patientAmount;
	private BigDecimal patientPercent;
	private BigDecimal patientAmountCap;
	private BigDecimal perTreatmentLimit;
	private BigDecimal patientAmountPerCategory;
	private String username;
	private String categoryPayable;
	private Character categoryPriorAuthRequired;
	private Integer insurancePlanDetailsId;

	public InsurancePlanDetailsModel() {
	}

	public InsurancePlanDetailsModel(InsurancePlanDetailsIdSequence id, BigDecimal patientAmount, BigDecimal patientPercent,
			BigDecimal patientAmountPerCategory) {
		this.id = id;
		this.patientAmount = patientAmount;
		this.patientPercent = patientPercent;
		this.patientAmountPerCategory = patientAmountPerCategory;
	}

	public InsurancePlanDetailsModel(InsurancePlanDetailsIdSequence id, BigDecimal patientAmount, BigDecimal patientPercent,
			BigDecimal patientAmountCap, BigDecimal perTreatmentLimit, BigDecimal patientAmountPerCategory,
			String username, String categoryPayable, Character categoryPriorAuthRequired,
			Integer insurancePlanDetailsId) {
		this.id = id;
		this.patientAmount = patientAmount;
		this.patientPercent = patientPercent;
		this.patientAmountCap = patientAmountCap;
		this.perTreatmentLimit = perTreatmentLimit;
		this.patientAmountPerCategory = patientAmountPerCategory;
		this.username = username;
		this.categoryPayable = categoryPayable;
		this.categoryPriorAuthRequired = categoryPriorAuthRequired;
		this.insurancePlanDetailsId = insurancePlanDetailsId;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "planId", column = @Column(name = "plan_id", nullable = false)),
			@AttributeOverride(name = "insuranceCategoryId", column = @Column(name = "insurance_category_id", nullable = false)),
			@AttributeOverride(name = "patientType", column = @Column(name = "patient_type", nullable = false, length = 1)) })
	public InsurancePlanDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(InsurancePlanDetailsIdSequence id) {
		this.id = id;
	}

	@Column(name = "patient_amount", nullable = false, precision = 15)
	public BigDecimal getPatientAmount() {
		return this.patientAmount;
	}

	public void setPatientAmount(BigDecimal patientAmount) {
		this.patientAmount = patientAmount;
	}

	@Column(name = "patient_percent", nullable = false, precision = 10)
	public BigDecimal getPatientPercent() {
		return this.patientPercent;
	}

	public void setPatientPercent(BigDecimal patientPercent) {
		this.patientPercent = patientPercent;
	}

	@Column(name = "patient_amount_cap", precision = 15)
	public BigDecimal getPatientAmountCap() {
		return this.patientAmountCap;
	}

	public void setPatientAmountCap(BigDecimal patientAmountCap) {
		this.patientAmountCap = patientAmountCap;
	}

	@Column(name = "per_treatment_limit", precision = 15)
	public BigDecimal getPerTreatmentLimit() {
		return this.perTreatmentLimit;
	}

	public void setPerTreatmentLimit(BigDecimal perTreatmentLimit) {
		this.perTreatmentLimit = perTreatmentLimit;
	}

	@Column(name = "patient_amount_per_category", nullable = false, precision = 15)
	public BigDecimal getPatientAmountPerCategory() {
		return this.patientAmountPerCategory;
	}

	public void setPatientAmountPerCategory(BigDecimal patientAmountPerCategory) {
		this.patientAmountPerCategory = patientAmountPerCategory;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "category_payable", length = 1)
	public String getCategoryPayable() {
		return this.categoryPayable;
	}

	public void setCategoryPayable(String categoryPayable) {
		this.categoryPayable = categoryPayable;
	}

	@Column(name = "category_prior_auth_required", length = 1)
	public Character getCategoryPriorAuthRequired() {
		return this.categoryPriorAuthRequired;
	}

	public void setCategoryPriorAuthRequired(Character categoryPriorAuthRequired) {
		this.categoryPriorAuthRequired = categoryPriorAuthRequired;
	}

	@Column(name = "insurance_plan_details_id", unique = true)
	public Integer getInsurancePlanDetailsIdSequence() {
		return this.insurancePlanDetailsId;
	}

	public void setInsurancePlanDetailsIdSequence(Integer insurancePlanDetailsId) {
		this.insurancePlanDetailsId = insurancePlanDetailsId;
	}

}
