package com.insta.hms.mdm.phrasesuggestionscategories;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PhraseSuggestionsCategoryMasterModel generated by hbm2java
 */
@Entity
@Table(name = "phrase_suggestions_category_master")
public class PhraseSuggestionsCategoryMasterModel implements java.io.Serializable {

	private int phraseSuggestionsCategoryId;
	private String phraseSuggestionsCategory;
	private String status;

	public PhraseSuggestionsCategoryMasterModel() {
	}

	public PhraseSuggestionsCategoryMasterModel(int phraseSuggestionsCategoryId) {
		this.phraseSuggestionsCategoryId = phraseSuggestionsCategoryId;
	}

	public PhraseSuggestionsCategoryMasterModel(int phraseSuggestionsCategoryId, String phraseSuggestionsCategory,
			String status) {
		this.phraseSuggestionsCategoryId = phraseSuggestionsCategoryId;
		this.phraseSuggestionsCategory = phraseSuggestionsCategory;
		this.status = status;
	}

	@Id

	@Column(name = "phrase_suggestions_category_id", unique = true, nullable = false)
	public int getPhraseSuggestionsCategoryId() {
		return this.phraseSuggestionsCategoryId;
	}

	public void setPhraseSuggestionsCategoryId(int phraseSuggestionsCategoryId) {
		this.phraseSuggestionsCategoryId = phraseSuggestionsCategoryId;
	}

	@Column(name = "phrase_suggestions_category", length = 100)
	public String getPhraseSuggestionsCategory() {
		return this.phraseSuggestionsCategory;
	}

	public void setPhraseSuggestionsCategory(String phraseSuggestionsCategory) {
		this.phraseSuggestionsCategory = phraseSuggestionsCategory;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
