package com.insta.hms.mdm.dialyzertypes;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DialyzerTypesModel generated by hbm2java
 */
@Entity
@Table(name = "dialyzer_types", uniqueConstraints = @UniqueConstraint(columnNames = "dialyzer_type_name"))
public class DialyzerTypesModel implements java.io.Serializable {

	private int dialyzerTypeId;
	private String dialyzerTypeName;
	private String description;
	private Character status;
	private Set dialysisSessions = new HashSet(0);

	public DialyzerTypesModel() {
	}

	public DialyzerTypesModel(int dialyzerTypeId, String dialyzerTypeName) {
		this.dialyzerTypeId = dialyzerTypeId;
		this.dialyzerTypeName = dialyzerTypeName;
	}

	public DialyzerTypesModel(int dialyzerTypeId, String dialyzerTypeName, String description, Character status,
			Set dialysisSessions) {
		this.dialyzerTypeId = dialyzerTypeId;
		this.dialyzerTypeName = dialyzerTypeName;
		this.description = description;
		this.status = status;
		this.dialysisSessions = dialysisSessions;
	}

	@Id

	@Column(name = "dialyzer_type_id", unique = true, nullable = false)
	public int getDialyzerTypeId() {
		return this.dialyzerTypeId;
	}

	public void setDialyzerTypeId(int dialyzerTypeId) {
		this.dialyzerTypeId = dialyzerTypeId;
	}

	@Column(name = "dialyzer_type_name", unique = true, nullable = false, length = 30)
	public String getDialyzerTypeName() {
		return this.dialyzerTypeName;
	}

	public void setDialyzerTypeName(String dialyzerTypeName) {
		this.dialyzerTypeName = dialyzerTypeName;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dialyzerTypes")
	public Set getDialysisSessions() {
		return this.dialysisSessions;
	}

	public void setDialysisSessions(Set dialysisSessions) {
		this.dialysisSessions = dialysisSessions;
	}

}
