package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountingXmlExportImportLogIdSequence generated by hbm2java
 */
@Embeddable
public class AccountingXmlExportImportLogIdSequence implements java.io.Serializable {

	private String fileName;
	private Date exportedDateTime;
	private String status;
	private int exportNo;
	private String message;
	private int accountGroup;
	private String exportDir;
	private int centerId;
	private String exportType;
	private Integer scheduleId;
	private Date voucherDate;

	public AccountingXmlExportImportLogIdSequence() {
	}

	public AccountingXmlExportImportLogIdSequence(int exportNo, String message, int accountGroup, int centerId,
			String exportType) {
		this.exportNo = exportNo;
		this.message = message;
		this.accountGroup = accountGroup;
		this.centerId = centerId;
		this.exportType = exportType;
	}

	public AccountingXmlExportImportLogIdSequence(String fileName, Date exportedDateTime, String status, int exportNo,
			String message, int accountGroup, String exportDir, int centerId, String exportType, Integer scheduleId,
			Date voucherDate) {
		this.fileName = fileName;
		this.exportedDateTime = exportedDateTime;
		this.status = status;
		this.exportNo = exportNo;
		this.message = message;
		this.accountGroup = accountGroup;
		this.exportDir = exportDir;
		this.centerId = centerId;
		this.exportType = exportType;
		this.scheduleId = scheduleId;
		this.voucherDate = voucherDate;
	}

	@Column(name = "file_name", length = 1000)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "exported_date_time", length = 29)
	public Date getExportedDateTime() {
		return this.exportedDateTime;
	}

	public void setExportedDateTime(Date exportedDateTime) {
		this.exportedDateTime = exportedDateTime;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "export_no", nullable = false)
	public int getExportNo() {
		return this.exportNo;
	}

	public void setExportNo(int exportNo) {
		this.exportNo = exportNo;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "account_group", nullable = false)
	public int getAccountGroup() {
		return this.accountGroup;
	}

	public void setAccountGroup(int accountGroup) {
		this.accountGroup = accountGroup;
	}

	@Column(name = "export_dir", length = 1000)
	public String getExportDir() {
		return this.exportDir;
	}

	public void setExportDir(String exportDir) {
		this.exportDir = exportDir;
	}

	@Column(name = "center_id", nullable = false)
	public int getCenterId() {
		return this.centerId;
	}

	public void setCenterId(int centerId) {
		this.centerId = centerId;
	}

	@Column(name = "export_type", nullable = false, length = 20)
	public String getExportType() {
		return this.exportType;
	}

	public void setExportType(String exportType) {
		this.exportType = exportType;
	}

	@Column(name = "schedule_id")
	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	@Column(name = "voucher_date", length = 13)
	public Date getVoucherDate() {
		return this.voucherDate;
	}

	public void setVoucherDate(Date voucherDate) {
		this.voucherDate = voucherDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountingXmlExportImportLogIdSequence))
			return false;
		AccountingXmlExportImportLogIdSequence castOther = (AccountingXmlExportImportLogIdSequence) other;

		return ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null
				&& castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())))
				&& ((this.getExportedDateTime() == castOther.getExportedDateTime())
						|| (this.getExportedDateTime() != null && castOther.getExportedDateTime() != null
								&& this.getExportedDateTime().equals(castOther.getExportedDateTime())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& (this.getExportNo() == castOther.getExportNo())
				&& ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& (this.getAccountGroup() == castOther.getAccountGroup())
				&& ((this.getExportDir() == castOther.getExportDir()) || (this.getExportDir() != null
						&& castOther.getExportDir() != null && this.getExportDir().equals(castOther.getExportDir())))
				&& (this.getCenterId() == castOther.getCenterId())
				&& ((this.getExportType() == castOther.getExportType()) || (this.getExportType() != null
						&& castOther.getExportType() != null && this.getExportType().equals(castOther.getExportType())))
				&& ((this.getScheduleId() == castOther.getScheduleId()) || (this.getScheduleId() != null
						&& castOther.getScheduleId() != null && this.getScheduleId().equals(castOther.getScheduleId())))
				&& ((this.getVoucherDate() == castOther.getVoucherDate())
						|| (this.getVoucherDate() != null && castOther.getVoucherDate() != null
								&& this.getVoucherDate().equals(castOther.getVoucherDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result + (getExportedDateTime() == null ? 0 : this.getExportedDateTime().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + this.getExportNo();
		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + this.getAccountGroup();
		result = 37 * result + (getExportDir() == null ? 0 : this.getExportDir().hashCode());
		result = 37 * result + this.getCenterId();
		result = 37 * result + (getExportType() == null ? 0 : this.getExportType().hashCode());
		result = 37 * result + (getScheduleId() == null ? 0 : this.getScheduleId().hashCode());
		result = 37 * result + (getVoucherDate() == null ? 0 : this.getVoucherDate().hashCode());
		return result;
	}

}
