package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AccountingXmlExportImportLogModel generated by hbm2java
 */
@Entity
@Table(name = "accounting_xml_export_import_log")
public class AccountingXmlExportImportLogModel implements java.io.Serializable {

	private AccountingXmlExportImportLogIdSequence id;

	public AccountingXmlExportImportLogModel() {
	}

	public AccountingXmlExportImportLogModel(AccountingXmlExportImportLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "fileName", column = @Column(name = "file_name", length = 1000)),
			@AttributeOverride(name = "exportedDateTime", column = @Column(name = "exported_date_time", length = 29)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 50)),
			@AttributeOverride(name = "exportNo", column = @Column(name = "export_no", nullable = false)),
			@AttributeOverride(name = "message", column = @Column(name = "message", nullable = false)),
			@AttributeOverride(name = "accountGroup", column = @Column(name = "account_group", nullable = false)),
			@AttributeOverride(name = "exportDir", column = @Column(name = "export_dir", length = 1000)),
			@AttributeOverride(name = "centerId", column = @Column(name = "center_id", nullable = false)),
			@AttributeOverride(name = "exportType", column = @Column(name = "export_type", nullable = false, length = 20)),
			@AttributeOverride(name = "scheduleId", column = @Column(name = "schedule_id")),
			@AttributeOverride(name = "voucherDate", column = @Column(name = "voucher_date", length = 13)) })
	public AccountingXmlExportImportLogIdSequence getId() {
		return this.id;
	}

	public void setId(AccountingXmlExportImportLogIdSequence id) {
		this.id = id;
	}

}
