package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActionRightsModel generated by hbm2java
 */
@Entity
@Table(name = "action_rights")
public class ActionRightsModel implements java.io.Serializable {

	private ActionRightsIdSequence id;
	private char rights;

	public ActionRightsModel() {
	}

	public ActionRightsModel(ActionRightsIdSequence id, char rights) {
		this.id = id;
		this.rights = rights;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "action", column = @Column(name = "action", nullable = false, length = 100)) })
	public ActionRightsIdSequence getId() {
		return this.id;
	}

	public void setId(ActionRightsIdSequence id) {
		this.id = id;
	}

	@Column(name = "rights", nullable = false, length = 1)
	public char getRights() {
		return this.rights;
	}

	public void setRights(char rights) {
		this.rights = rights;
	}

}
