package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmissionModel generated by hbm2java
 */
@Entity
@Table(name = "admission")
public class AdmissionModel implements java.io.Serializable {

	private String patientId;
	private String mrNo;
	private Date admitDate;
	private Character daycareStatus;
	private BigDecimal estimatedDays;
	private Date admitTime;
	private Character isbaby;
	private String parentId;
	private Integer bedId;
	private Character graceperiodOverride;
	private String daysorhrs;
	private Date lastUpdated;
	private Date finalizedTime;

	public AdmissionModel() {
	}

	public AdmissionModel(String patientId, String mrNo, Date admitDate, Date admitTime) {
		this.patientId = patientId;
		this.mrNo = mrNo;
		this.admitDate = admitDate;
		this.admitTime = admitTime;
	}

	public AdmissionModel(String patientId, String mrNo, Date admitDate, Character daycareStatus, BigDecimal estimatedDays,
			Date admitTime, Character isbaby, String parentId, Integer bedId, Character graceperiodOverride,
			String daysorhrs, Date lastUpdated, Date finalizedTime) {
		this.patientId = patientId;
		this.mrNo = mrNo;
		this.admitDate = admitDate;
		this.daycareStatus = daycareStatus;
		this.estimatedDays = estimatedDays;
		this.admitTime = admitTime;
		this.isbaby = isbaby;
		this.parentId = parentId;
		this.bedId = bedId;
		this.graceperiodOverride = graceperiodOverride;
		this.daysorhrs = daysorhrs;
		this.lastUpdated = lastUpdated;
		this.finalizedTime = finalizedTime;
	}

	@Id

	@Column(name = "patient_id", unique = true, nullable = false, length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "mr_no", nullable = false, length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admit_date", nullable = false, length = 13)
	public Date getAdmitDate() {
		return this.admitDate;
	}

	public void setAdmitDate(Date admitDate) {
		this.admitDate = admitDate;
	}

	@Column(name = "daycare_status", length = 1)
	public Character getDaycareStatus() {
		return this.daycareStatus;
	}

	public void setDaycareStatus(Character daycareStatus) {
		this.daycareStatus = daycareStatus;
	}

	@Column(name = "estimated_days", precision = 131089, scale = 0)
	public BigDecimal getEstimatedDays() {
		return this.estimatedDays;
	}

	public void setEstimatedDays(BigDecimal estimatedDays) {
		this.estimatedDays = estimatedDays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "admit_time", nullable = false, length = 29)
	public Date getAdmitTime() {
		return this.admitTime;
	}

	public void setAdmitTime(Date admitTime) {
		this.admitTime = admitTime;
	}

	@Column(name = "isbaby", length = 1)
	public Character getIsbaby() {
		return this.isbaby;
	}

	public void setIsbaby(Character isbaby) {
		this.isbaby = isbaby;
	}

	@Column(name = "parent_id", length = 15)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "bed_id")
	public Integer getBedId() {
		return this.bedId;
	}

	public void setBedId(Integer bedId) {
		this.bedId = bedId;
	}

	@Column(name = "graceperiod_override", length = 1)
	public Character getGraceperiodOverride() {
		return this.graceperiodOverride;
	}

	public void setGraceperiodOverride(Character graceperiodOverride) {
		this.graceperiodOverride = graceperiodOverride;
	}

	@Column(name = "daysorhrs", length = 4)
	public String getDaysorhrs() {
		return this.daysorhrs;
	}

	public void setDaysorhrs(String daysorhrs) {
		this.daysorhrs = daysorhrs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finalized_time", length = 29)
	public Date getFinalizedTime() {
		return this.finalizedTime;
	}

	public void setFinalizedTime(Date finalizedTime) {
		this.finalizedTime = finalizedTime;
	}

}
