package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlternateActivityCodesIdSequence generated by hbm2java
 */
@Embeddable
public class AlternateActivityCodesIdSequence implements java.io.Serializable {

	private String itemId;
	private String itemCode;
	private String codeType;
	private String healthAuthority;
	private String sponsorId;
	private String alternateCode;

	public AlternateActivityCodesIdSequence() {
	}

	public AlternateActivityCodesIdSequence(String itemId, String itemCode, String codeType, String healthAuthority,
			String sponsorId, String alternateCode) {
		this.itemId = itemId;
		this.itemCode = itemCode;
		this.codeType = codeType;
		this.healthAuthority = healthAuthority;
		this.sponsorId = sponsorId;
		this.alternateCode = alternateCode;
	}

	@Column(name = "item_id", nullable = false)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Column(name = "item_code", nullable = false)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "code_type", nullable = false)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "health_authority", nullable = false)
	public String getHealthAuthority() {
		return this.healthAuthority;
	}

	public void setHealthAuthority(String healthAuthority) {
		this.healthAuthority = healthAuthority;
	}

	@Column(name = "sponsor_id", nullable = false)
	public String getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(String sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "alternate_code", nullable = false)
	public String getAlternateCode() {
		return this.alternateCode;
	}

	public void setAlternateCode(String alternateCode) {
		this.alternateCode = alternateCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlternateActivityCodesIdSequence))
			return false;
		AlternateActivityCodesIdSequence castOther = (AlternateActivityCodesIdSequence) other;

		return ((this.getItemId() == castOther.getItemId()) || (this.getItemId() != null
				&& castOther.getItemId() != null && this.getItemId().equals(castOther.getItemId())))
				&& ((this.getItemCode() == castOther.getItemCode()) || (this.getItemCode() != null
						&& castOther.getItemCode() != null && this.getItemCode().equals(castOther.getItemCode())))
				&& ((this.getCodeType() == castOther.getCodeType()) || (this.getCodeType() != null
						&& castOther.getCodeType() != null && this.getCodeType().equals(castOther.getCodeType())))
				&& ((this.getHealthAuthority() == castOther.getHealthAuthority())
						|| (this.getHealthAuthority() != null && castOther.getHealthAuthority() != null
								&& this.getHealthAuthority().equals(castOther.getHealthAuthority())))
				&& ((this.getSponsorId() == castOther.getSponsorId()) || (this.getSponsorId() != null
						&& castOther.getSponsorId() != null && this.getSponsorId().equals(castOther.getSponsorId())))
				&& ((this.getAlternateCode() == castOther.getAlternateCode())
						|| (this.getAlternateCode() != null && castOther.getAlternateCode() != null
								&& this.getAlternateCode().equals(castOther.getAlternateCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getItemId() == null ? 0 : this.getItemId().hashCode());
		result = 37 * result + (getItemCode() == null ? 0 : this.getItemCode().hashCode());
		result = 37 * result + (getCodeType() == null ? 0 : this.getCodeType().hashCode());
		result = 37 * result + (getHealthAuthority() == null ? 0 : this.getHealthAuthority().hashCode());
		result = 37 * result + (getSponsorId() == null ? 0 : this.getSponsorId().hashCode());
		result = 37 * result + (getAlternateCode() == null ? 0 : this.getAlternateCode().hashCode());
		return result;
	}

}
