package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AmbulanceUsageModel generated by hbm2java
 */
@Entity
@Table(name = "ambulance_usage")
public class AmbulanceUsageModel implements java.io.Serializable {

	private int ambulanceUsageId;
	private int ambulanceId;
	private String patientMrno;
	private String patientName;
	private String patientAddress;
	private String patientPhone;
	private Integer startMileage;
	private Integer endMileage;
	private Date startDateTime;
	private Date endDateTime;
	private Integer callId;
	private String remarks;

	public AmbulanceUsageModel() {
	}

	public AmbulanceUsageModel(int ambulanceUsageId, int ambulanceId, String patientName) {
		this.ambulanceUsageId = ambulanceUsageId;
		this.ambulanceId = ambulanceId;
		this.patientName = patientName;
	}

	public AmbulanceUsageModel(int ambulanceUsageId, int ambulanceId, String patientMrno, String patientName,
			String patientAddress, String patientPhone, Integer startMileage, Integer endMileage, Date startDateTime,
			Date endDateTime, Integer callId, String remarks) {
		this.ambulanceUsageId = ambulanceUsageId;
		this.ambulanceId = ambulanceId;
		this.patientMrno = patientMrno;
		this.patientName = patientName;
		this.patientAddress = patientAddress;
		this.patientPhone = patientPhone;
		this.startMileage = startMileage;
		this.endMileage = endMileage;
		this.startDateTime = startDateTime;
		this.endDateTime = endDateTime;
		this.callId = callId;
		this.remarks = remarks;
	}

	@Id

	@Column(name = "ambulance_usage_id", unique = true, nullable = false)
	public int getAmbulanceUsageIdSequence() {
		return this.ambulanceUsageId;
	}

	public void setAmbulanceUsageIdSequence(int ambulanceUsageId) {
		this.ambulanceUsageId = ambulanceUsageId;
	}

	@Column(name = "ambulance_id", nullable = false)
	public int getAmbulanceId() {
		return this.ambulanceId;
	}

	public void setAmbulanceId(int ambulanceId) {
		this.ambulanceId = ambulanceId;
	}

	@Column(name = "patient_mrno", length = 20)
	public String getPatientMrno() {
		return this.patientMrno;
	}

	public void setPatientMrno(String patientMrno) {
		this.patientMrno = patientMrno;
	}

	@Column(name = "patient_name", nullable = false, length = 100)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "patient_address", length = 200)
	public String getPatientAddress() {
		return this.patientAddress;
	}

	public void setPatientAddress(String patientAddress) {
		this.patientAddress = patientAddress;
	}

	@Column(name = "patient_phone", length = 20)
	public String getPatientPhone() {
		return this.patientPhone;
	}

	public void setPatientPhone(String patientPhone) {
		this.patientPhone = patientPhone;
	}

	@Column(name = "start_mileage")
	public Integer getStartMileage() {
		return this.startMileage;
	}

	public void setStartMileage(Integer startMileage) {
		this.startMileage = startMileage;
	}

	@Column(name = "end_mileage")
	public Integer getEndMileage() {
		return this.endMileage;
	}

	public void setEndMileage(Integer endMileage) {
		this.endMileage = endMileage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date_time", length = 29)
	public Date getStartDateTime() {
		return this.startDateTime;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date_time", length = 29)
	public Date getEndDateTime() {
		return this.endDateTime;
	}

	public void setEndDateTime(Date endDateTime) {
		this.endDateTime = endDateTime;
	}

	@Column(name = "call_id")
	public Integer getCallId() {
		return this.callId;
	}

	public void setCallId(Integer callId) {
		this.callId = callId;
	}

	@Column(name = "remarks", length = 200)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
