package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AnesthesiaTypeChargesModel generated by hbm2java
 */
@Entity
@Table(name = "anesthesia_type_charges")
public class AnesthesiaTypeChargesModel implements java.io.Serializable {

	private AnesthesiaTypeChargesIdSequence id;
	private BigDecimal minCharge;
	private BigDecimal slab1Charge;
	private BigDecimal incrCharge;
	private BigDecimal minChargeDiscount;
	private BigDecimal incrChargeDiscount;
	private BigDecimal slab1ChargeDiscount;
	private String isOverride;

	public AnesthesiaTypeChargesModel() {
	}

	public AnesthesiaTypeChargesModel(AnesthesiaTypeChargesIdSequence id, BigDecimal minCharge, BigDecimal slab1Charge,
			BigDecimal incrCharge, BigDecimal minChargeDiscount, BigDecimal incrChargeDiscount,
			BigDecimal slab1ChargeDiscount) {
		this.id = id;
		this.minCharge = minCharge;
		this.slab1Charge = slab1Charge;
		this.incrCharge = incrCharge;
		this.minChargeDiscount = minChargeDiscount;
		this.incrChargeDiscount = incrChargeDiscount;
		this.slab1ChargeDiscount = slab1ChargeDiscount;
	}

	public AnesthesiaTypeChargesModel(AnesthesiaTypeChargesIdSequence id, BigDecimal minCharge, BigDecimal slab1Charge,
			BigDecimal incrCharge, BigDecimal minChargeDiscount, BigDecimal incrChargeDiscount,
			BigDecimal slab1ChargeDiscount, String isOverride) {
		this.id = id;
		this.minCharge = minCharge;
		this.slab1Charge = slab1Charge;
		this.incrCharge = incrCharge;
		this.minChargeDiscount = minChargeDiscount;
		this.incrChargeDiscount = incrChargeDiscount;
		this.slab1ChargeDiscount = slab1ChargeDiscount;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "anesthesiaTypeId", column = @Column(name = "anesthesia_type_id", nullable = false, length = 50)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 200)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", nullable = false, length = 200)) })
	public AnesthesiaTypeChargesIdSequence getId() {
		return this.id;
	}

	public void setId(AnesthesiaTypeChargesIdSequence id) {
		this.id = id;
	}

	@Column(name = "min_charge", nullable = false, precision = 15)
	public BigDecimal getMinCharge() {
		return this.minCharge;
	}

	public void setMinCharge(BigDecimal minCharge) {
		this.minCharge = minCharge;
	}

	@Column(name = "slab_1_charge", nullable = false, precision = 15)
	public BigDecimal getSlab1Charge() {
		return this.slab1Charge;
	}

	public void setSlab1Charge(BigDecimal slab1Charge) {
		this.slab1Charge = slab1Charge;
	}

	@Column(name = "incr_charge", nullable = false, precision = 15)
	public BigDecimal getIncrCharge() {
		return this.incrCharge;
	}

	public void setIncrCharge(BigDecimal incrCharge) {
		this.incrCharge = incrCharge;
	}

	@Column(name = "min_charge_discount", nullable = false, precision = 15)
	public BigDecimal getMinChargeDiscount() {
		return this.minChargeDiscount;
	}

	public void setMinChargeDiscount(BigDecimal minChargeDiscount) {
		this.minChargeDiscount = minChargeDiscount;
	}

	@Column(name = "incr_charge_discount", nullable = false, precision = 15)
	public BigDecimal getIncrChargeDiscount() {
		return this.incrChargeDiscount;
	}

	public void setIncrChargeDiscount(BigDecimal incrChargeDiscount) {
		this.incrChargeDiscount = incrChargeDiscount;
	}

	@Column(name = "slab_1_charge_discount", nullable = false, precision = 15)
	public BigDecimal getSlab1ChargeDiscount() {
		return this.slab1ChargeDiscount;
	}

	public void setSlab1ChargeDiscount(BigDecimal slab1ChargeDiscount) {
		this.slab1ChargeDiscount = slab1ChargeDiscount;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
