package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.adminmasters.bedmaster.BedDetailsIdSequence;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BedDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "bed_details")
public class BedDetailsModel implements java.io.Serializable {

	private BedDetailsIdSequence id;
	private BigDecimal bedCharge;
	private BigDecimal nursingCharge;
	private BigDecimal initialPayment;
	private BigDecimal dutyCharge;
	private BigDecimal maintainanceCharge;
	private Character chargeType;
	private String bedStatus;
	private BigDecimal luxaryTax;
	private Character intensiveBedStatus;
	private Character childBedStatus;
	private BigDecimal hourlyCharge;
	private BigDecimal bedChargeDiscount;
	private BigDecimal nursingChargeDiscount;
	private BigDecimal dutyChargeDiscount;
	private BigDecimal maintainanceChargeDiscount;
	private BigDecimal hourlyChargeDiscount;
	private BigDecimal initialPaymentDiscount;
	private BigDecimal daycareSlab1Charge;
	private BigDecimal daycareSlab1ChargeDiscount;
	private BigDecimal daycareSlab2Charge;
	private BigDecimal daycareSlab2ChargeDiscount;
	private BigDecimal daycareSlab3Charge;
	private BigDecimal daycareSlab3ChargeDiscount;
	private String isOverride;

	public BedDetailsModel() {
	}

	public BedDetailsModel(BedDetailsIdSequence id, BigDecimal bedCharge, BigDecimal nursingCharge, BigDecimal initialPayment,
			BigDecimal dutyCharge, BigDecimal maintainanceCharge, BigDecimal bedChargeDiscount,
			BigDecimal nursingChargeDiscount, BigDecimal dutyChargeDiscount, BigDecimal maintainanceChargeDiscount,
			BigDecimal hourlyChargeDiscount, BigDecimal initialPaymentDiscount, BigDecimal daycareSlab1Charge,
			BigDecimal daycareSlab1ChargeDiscount, BigDecimal daycareSlab2Charge, BigDecimal daycareSlab2ChargeDiscount,
			BigDecimal daycareSlab3Charge, BigDecimal daycareSlab3ChargeDiscount) {
		this.id = id;
		this.bedCharge = bedCharge;
		this.nursingCharge = nursingCharge;
		this.initialPayment = initialPayment;
		this.dutyCharge = dutyCharge;
		this.maintainanceCharge = maintainanceCharge;
		this.bedChargeDiscount = bedChargeDiscount;
		this.nursingChargeDiscount = nursingChargeDiscount;
		this.dutyChargeDiscount = dutyChargeDiscount;
		this.maintainanceChargeDiscount = maintainanceChargeDiscount;
		this.hourlyChargeDiscount = hourlyChargeDiscount;
		this.initialPaymentDiscount = initialPaymentDiscount;
		this.daycareSlab1Charge = daycareSlab1Charge;
		this.daycareSlab1ChargeDiscount = daycareSlab1ChargeDiscount;
		this.daycareSlab2Charge = daycareSlab2Charge;
		this.daycareSlab2ChargeDiscount = daycareSlab2ChargeDiscount;
		this.daycareSlab3Charge = daycareSlab3Charge;
		this.daycareSlab3ChargeDiscount = daycareSlab3ChargeDiscount;
	}

	public BedDetailsModel(BedDetailsIdSequence id, BigDecimal bedCharge, BigDecimal nursingCharge, BigDecimal initialPayment,
			BigDecimal dutyCharge, BigDecimal maintainanceCharge, Character chargeType, String bedStatus,
			BigDecimal luxaryTax, Character intensiveBedStatus, Character childBedStatus, BigDecimal hourlyCharge,
			BigDecimal bedChargeDiscount, BigDecimal nursingChargeDiscount, BigDecimal dutyChargeDiscount,
			BigDecimal maintainanceChargeDiscount, BigDecimal hourlyChargeDiscount, BigDecimal initialPaymentDiscount,
			BigDecimal daycareSlab1Charge, BigDecimal daycareSlab1ChargeDiscount, BigDecimal daycareSlab2Charge,
			BigDecimal daycareSlab2ChargeDiscount, BigDecimal daycareSlab3Charge, BigDecimal daycareSlab3ChargeDiscount,
			String isOverride) {
		this.id = id;
		this.bedCharge = bedCharge;
		this.nursingCharge = nursingCharge;
		this.initialPayment = initialPayment;
		this.dutyCharge = dutyCharge;
		this.maintainanceCharge = maintainanceCharge;
		this.chargeType = chargeType;
		this.bedStatus = bedStatus;
		this.luxaryTax = luxaryTax;
		this.intensiveBedStatus = intensiveBedStatus;
		this.childBedStatus = childBedStatus;
		this.hourlyCharge = hourlyCharge;
		this.bedChargeDiscount = bedChargeDiscount;
		this.nursingChargeDiscount = nursingChargeDiscount;
		this.dutyChargeDiscount = dutyChargeDiscount;
		this.maintainanceChargeDiscount = maintainanceChargeDiscount;
		this.hourlyChargeDiscount = hourlyChargeDiscount;
		this.initialPaymentDiscount = initialPaymentDiscount;
		this.daycareSlab1Charge = daycareSlab1Charge;
		this.daycareSlab1ChargeDiscount = daycareSlab1ChargeDiscount;
		this.daycareSlab2Charge = daycareSlab2Charge;
		this.daycareSlab2ChargeDiscount = daycareSlab2ChargeDiscount;
		this.daycareSlab3Charge = daycareSlab3Charge;
		this.daycareSlab3ChargeDiscount = daycareSlab3ChargeDiscount;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", nullable = false, length = 50)),
			@AttributeOverride(name = "organization", column = @Column(name = "organization", nullable = false, length = 100)) })
	public BedDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(BedDetailsIdSequence id) {
		this.id = id;
	}

	@Column(name = "bed_charge", nullable = false, precision = 15)
	public BigDecimal getBedCharge() {
		return this.bedCharge;
	}

	public void setBedCharge(BigDecimal bedCharge) {
		this.bedCharge = bedCharge;
	}

	@Column(name = "nursing_charge", nullable = false, precision = 15)
	public BigDecimal getNursingCharge() {
		return this.nursingCharge;
	}

	public void setNursingCharge(BigDecimal nursingCharge) {
		this.nursingCharge = nursingCharge;
	}

	@Column(name = "initial_payment", nullable = false, precision = 15)
	public BigDecimal getInitialPayment() {
		return this.initialPayment;
	}

	public void setInitialPayment(BigDecimal initialPayment) {
		this.initialPayment = initialPayment;
	}

	@Column(name = "duty_charge", nullable = false, precision = 15)
	public BigDecimal getDutyCharge() {
		return this.dutyCharge;
	}

	public void setDutyCharge(BigDecimal dutyCharge) {
		this.dutyCharge = dutyCharge;
	}

	@Column(name = "maintainance_charge", nullable = false, precision = 15)
	public BigDecimal getMaintainanceCharge() {
		return this.maintainanceCharge;
	}

	public void setMaintainanceCharge(BigDecimal maintainanceCharge) {
		this.maintainanceCharge = maintainanceCharge;
	}

	@Column(name = "charge_type", length = 1)
	public Character getChargeType() {
		return this.chargeType;
	}

	public void setChargeType(Character chargeType) {
		this.chargeType = chargeType;
	}

	@Column(name = "bed_status", length = 1)
	public String getBedStatus() {
		return this.bedStatus;
	}

	public void setBedStatus(String bedStatus) {
		this.bedStatus = bedStatus;
	}

	@Column(name = "luxary_tax", precision = 15)
	public BigDecimal getLuxaryTax() {
		return this.luxaryTax;
	}

	public void setLuxaryTax(BigDecimal luxaryTax) {
		this.luxaryTax = luxaryTax;
	}

	@Column(name = "intensive_bed_status", length = 1)
	public Character getIntensiveBedStatus() {
		return this.intensiveBedStatus;
	}

	public void setIntensiveBedStatus(Character intensiveBedStatus) {
		this.intensiveBedStatus = intensiveBedStatus;
	}

	@Column(name = "child_bed_status", length = 1)
	public Character getChildBedStatus() {
		return this.childBedStatus;
	}

	public void setChildBedStatus(Character childBedStatus) {
		this.childBedStatus = childBedStatus;
	}

	@Column(name = "hourly_charge", precision = 15)
	public BigDecimal getHourlyCharge() {
		return this.hourlyCharge;
	}

	public void setHourlyCharge(BigDecimal hourlyCharge) {
		this.hourlyCharge = hourlyCharge;
	}

	@Column(name = "bed_charge_discount", nullable = false, precision = 15)
	public BigDecimal getBedChargeDiscount() {
		return this.bedChargeDiscount;
	}

	public void setBedChargeDiscount(BigDecimal bedChargeDiscount) {
		this.bedChargeDiscount = bedChargeDiscount;
	}

	@Column(name = "nursing_charge_discount", nullable = false, precision = 15)
	public BigDecimal getNursingChargeDiscount() {
		return this.nursingChargeDiscount;
	}

	public void setNursingChargeDiscount(BigDecimal nursingChargeDiscount) {
		this.nursingChargeDiscount = nursingChargeDiscount;
	}

	@Column(name = "duty_charge_discount", nullable = false, precision = 15)
	public BigDecimal getDutyChargeDiscount() {
		return this.dutyChargeDiscount;
	}

	public void setDutyChargeDiscount(BigDecimal dutyChargeDiscount) {
		this.dutyChargeDiscount = dutyChargeDiscount;
	}

	@Column(name = "maintainance_charge_discount", nullable = false, precision = 15)
	public BigDecimal getMaintainanceChargeDiscount() {
		return this.maintainanceChargeDiscount;
	}

	public void setMaintainanceChargeDiscount(BigDecimal maintainanceChargeDiscount) {
		this.maintainanceChargeDiscount = maintainanceChargeDiscount;
	}

	@Column(name = "hourly_charge_discount", nullable = false, precision = 15)
	public BigDecimal getHourlyChargeDiscount() {
		return this.hourlyChargeDiscount;
	}

	public void setHourlyChargeDiscount(BigDecimal hourlyChargeDiscount) {
		this.hourlyChargeDiscount = hourlyChargeDiscount;
	}

	@Column(name = "initial_payment_discount", nullable = false, precision = 15)
	public BigDecimal getInitialPaymentDiscount() {
		return this.initialPaymentDiscount;
	}

	public void setInitialPaymentDiscount(BigDecimal initialPaymentDiscount) {
		this.initialPaymentDiscount = initialPaymentDiscount;
	}

	@Column(name = "daycare_slab_1_charge", nullable = false, precision = 15)
	public BigDecimal getDaycareSlab1Charge() {
		return this.daycareSlab1Charge;
	}

	public void setDaycareSlab1Charge(BigDecimal daycareSlab1Charge) {
		this.daycareSlab1Charge = daycareSlab1Charge;
	}

	@Column(name = "daycare_slab_1_charge_discount", nullable = false, precision = 15)
	public BigDecimal getDaycareSlab1ChargeDiscount() {
		return this.daycareSlab1ChargeDiscount;
	}

	public void setDaycareSlab1ChargeDiscount(BigDecimal daycareSlab1ChargeDiscount) {
		this.daycareSlab1ChargeDiscount = daycareSlab1ChargeDiscount;
	}

	@Column(name = "daycare_slab_2_charge", nullable = false, precision = 15)
	public BigDecimal getDaycareSlab2Charge() {
		return this.daycareSlab2Charge;
	}

	public void setDaycareSlab2Charge(BigDecimal daycareSlab2Charge) {
		this.daycareSlab2Charge = daycareSlab2Charge;
	}

	@Column(name = "daycare_slab_2_charge_discount", nullable = false, precision = 15)
	public BigDecimal getDaycareSlab2ChargeDiscount() {
		return this.daycareSlab2ChargeDiscount;
	}

	public void setDaycareSlab2ChargeDiscount(BigDecimal daycareSlab2ChargeDiscount) {
		this.daycareSlab2ChargeDiscount = daycareSlab2ChargeDiscount;
	}

	@Column(name = "daycare_slab_3_charge", nullable = false, precision = 15)
	public BigDecimal getDaycareSlab3Charge() {
		return this.daycareSlab3Charge;
	}

	public void setDaycareSlab3Charge(BigDecimal daycareSlab3Charge) {
		this.daycareSlab3Charge = daycareSlab3Charge;
	}

	@Column(name = "daycare_slab_3_charge_discount", nullable = false, precision = 15)
	public BigDecimal getDaycareSlab3ChargeDiscount() {
		return this.daycareSlab3ChargeDiscount;
	}

	public void setDaycareSlab3ChargeDiscount(BigDecimal daycareSlab3ChargeDiscount) {
		this.daycareSlab3ChargeDiscount = daycareSlab3ChargeDiscount;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
