package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BedNamesModel generated by hbm2java
 */
@Entity
@Table(name = "bed_names")
public class BedNamesModel implements java.io.Serializable {

	private int bedId;
	private String wardNo;
	private String bedType;
	private String bedName;
	private String occupancy;
	private Character status;
	private Integer bedRefId;
	private Date avilableDate;
	private String remarks;
	private Character bedStatus;
	private Set bedLinenCurrentLists = new HashSet(0);

	public BedNamesModel() {
	}

	public BedNamesModel(int bedId, String wardNo, String bedType, String bedName) {
		this.bedId = bedId;
		this.wardNo = wardNo;
		this.bedType = bedType;
		this.bedName = bedName;
	}

	public BedNamesModel(int bedId, String wardNo, String bedType, String bedName, String occupancy, Character status,
			Integer bedRefId, Date avilableDate, String remarks, Character bedStatus, Set bedLinenCurrentLists) {
		this.bedId = bedId;
		this.wardNo = wardNo;
		this.bedType = bedType;
		this.bedName = bedName;
		this.occupancy = occupancy;
		this.status = status;
		this.bedRefId = bedRefId;
		this.avilableDate = avilableDate;
		this.remarks = remarks;
		this.bedStatus = bedStatus;
		this.bedLinenCurrentLists = bedLinenCurrentLists;
	}

	@Id

	@Column(name = "bed_id", unique = true, nullable = false)
	public int getBedId() {
		return this.bedId;
	}

	public void setBedId(int bedId) {
		this.bedId = bedId;
	}

	@Column(name = "ward_no", nullable = false, length = 100)
	public String getWardNo() {
		return this.wardNo;
	}

	public void setWardNo(String wardNo) {
		this.wardNo = wardNo;
	}

	@Column(name = "bed_type", nullable = false, length = 50)
	public String getBedType() {
		return this.bedType;
	}

	public void setBedType(String bedType) {
		this.bedType = bedType;
	}

	@Column(name = "bed_name", nullable = false, length = 100)
	public String getBedName() {
		return this.bedName;
	}

	public void setBedName(String bedName) {
		this.bedName = bedName;
	}

	@Column(name = "occupancy", length = 3)
	public String getOccupancy() {
		return this.occupancy;
	}

	public void setOccupancy(String occupancy) {
		this.occupancy = occupancy;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "bed_ref_id")
	public Integer getBedRefId() {
		return this.bedRefId;
	}

	public void setBedRefId(Integer bedRefId) {
		this.bedRefId = bedRefId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "avilable_date", length = 29)
	public Date getAvilableDate() {
		return this.avilableDate;
	}

	public void setAvilableDate(Date avilableDate) {
		this.avilableDate = avilableDate;
	}

	@Column(name = "remarks", length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "bed_status", length = 1)
	public Character getBedStatus() {
		return this.bedStatus;
	}

	public void setBedStatus(Character bedStatus) {
		this.bedStatus = bedStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bedNames")
	public Set getBedLinenCurrentLists() {
		return this.bedLinenCurrentLists;
	}

	public void setBedLinenCurrentLists(Set bedLinenCurrentLists) {
		this.bedLinenCurrentLists = bedLinenCurrentLists;
	}

}
