package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BedOperationSecondaryModel generated by hbm2java
 */
@Entity
@Table(name = "bed_operation_secondary")
public class BedOperationSecondaryModel implements java.io.Serializable {

	private BedOperationSecondaryIdSequence id;

	public BedOperationSecondaryModel() {
	}

	public BedOperationSecondaryModel(BedOperationSecondaryIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "secPrescribedId", column = @Column(name = "sec_prescribed_id", nullable = false)),
			@AttributeOverride(name = "prescribedId", column = @Column(name = "prescribed_id", nullable = false)),
			@AttributeOverride(name = "operationId", column = @Column(name = "operation_id")),
			@AttributeOverride(name = "remarks", column = @Column(name = "remarks", length = 2000)),
			@AttributeOverride(name = "stockReduced", column = @Column(name = "stock_reduced")) })
	public BedOperationSecondaryIdSequence getId() {
		return this.id;
	}

	public void setId(BedOperationSecondaryIdSequence id) {
		this.id = id;
	}

}
