package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BillChargeAdjustmentIdSequence generated by hbm2java
 */
@Embeddable
public class BillChargeAdjustmentIdSequence implements java.io.Serializable {

	private String billChargeAdjustmentId;
	private String adjustmentType;
	private String chargeId;
	private String billNo;
	private BigDecimal actRate;
	private BigDecimal actQuantity;
	private BigDecimal amount;
	private BigDecimal discount;
	private BigDecimal paidAmount;
	private Date postedDate;
	private char status;
	private String username;
	private Date modTime;
	private BigDecimal origRate;
	private BigDecimal packageUnit;
	private BigDecimal doctorAmount;
	private BigDecimal insuranceClaimAmount;
	private BigDecimal referalAmount;
	private BigDecimal outHouseAmount;
	private BigDecimal prescribingDrAmount;
	private BigDecimal overallDiscountAmt;
	private BigDecimal drDiscountAmt;
	private BigDecimal presDrDiscountAmt;
	private BigDecimal refDiscountAmt;
	private BigDecimal hospDiscountAmt;
	private BigDecimal claimRecdTotal;
	private BigDecimal returnInsuranceClaimAmt;
	private BigDecimal returnAmt;
	private BigDecimal returnQty;
	private int redeemedPoints;
	private BigDecimal amountIncluded;
	private BigDecimal qtyIncluded;
	private BigDecimal origInsuranceClaimAmount;
	private String adjustmentRemarks;
	private String chargeHead;
	private String chargeGroup;
	private Integer patientCategoryId;
	private String primarySponsorId;
	private String secondarySponsorId;
	private Integer serviceSubGroupId;
	private Boolean sponsorSwitch;

	public BillChargeAdjustmentIdSequence() {
	}

	public BillChargeAdjustmentIdSequence(String billChargeAdjustmentId, String chargeId, String billNo, BigDecimal amount,
			Date postedDate, char status, Date modTime, BigDecimal insuranceClaimAmount, int redeemedPoints,
			BigDecimal amountIncluded, BigDecimal qtyIncluded, BigDecimal origInsuranceClaimAmount) {
		this.billChargeAdjustmentId = billChargeAdjustmentId;
		this.chargeId = chargeId;
		this.billNo = billNo;
		this.amount = amount;
		this.postedDate = postedDate;
		this.status = status;
		this.modTime = modTime;
		this.insuranceClaimAmount = insuranceClaimAmount;
		this.redeemedPoints = redeemedPoints;
		this.amountIncluded = amountIncluded;
		this.qtyIncluded = qtyIncluded;
		this.origInsuranceClaimAmount = origInsuranceClaimAmount;
	}

	public BillChargeAdjustmentIdSequence(String billChargeAdjustmentId, String adjustmentType, String chargeId, String billNo,
			BigDecimal actRate, BigDecimal actQuantity, BigDecimal amount, BigDecimal discount, BigDecimal paidAmount,
			Date postedDate, char status, String username, Date modTime, BigDecimal origRate, BigDecimal packageUnit,
			BigDecimal doctorAmount, BigDecimal insuranceClaimAmount, BigDecimal referalAmount,
			BigDecimal outHouseAmount, BigDecimal prescribingDrAmount, BigDecimal overallDiscountAmt,
			BigDecimal drDiscountAmt, BigDecimal presDrDiscountAmt, BigDecimal refDiscountAmt,
			BigDecimal hospDiscountAmt, BigDecimal claimRecdTotal, BigDecimal returnInsuranceClaimAmt,
			BigDecimal returnAmt, BigDecimal returnQty, int redeemedPoints, BigDecimal amountIncluded,
			BigDecimal qtyIncluded, BigDecimal origInsuranceClaimAmount, String adjustmentRemarks, String chargeHead,
			String chargeGroup, Integer patientCategoryId, String primarySponsorId, String secondarySponsorId,
			Integer serviceSubGroupId, Boolean sponsorSwitch) {
		this.billChargeAdjustmentId = billChargeAdjustmentId;
		this.adjustmentType = adjustmentType;
		this.chargeId = chargeId;
		this.billNo = billNo;
		this.actRate = actRate;
		this.actQuantity = actQuantity;
		this.amount = amount;
		this.discount = discount;
		this.paidAmount = paidAmount;
		this.postedDate = postedDate;
		this.status = status;
		this.username = username;
		this.modTime = modTime;
		this.origRate = origRate;
		this.packageUnit = packageUnit;
		this.doctorAmount = doctorAmount;
		this.insuranceClaimAmount = insuranceClaimAmount;
		this.referalAmount = referalAmount;
		this.outHouseAmount = outHouseAmount;
		this.prescribingDrAmount = prescribingDrAmount;
		this.overallDiscountAmt = overallDiscountAmt;
		this.drDiscountAmt = drDiscountAmt;
		this.presDrDiscountAmt = presDrDiscountAmt;
		this.refDiscountAmt = refDiscountAmt;
		this.hospDiscountAmt = hospDiscountAmt;
		this.claimRecdTotal = claimRecdTotal;
		this.returnInsuranceClaimAmt = returnInsuranceClaimAmt;
		this.returnAmt = returnAmt;
		this.returnQty = returnQty;
		this.redeemedPoints = redeemedPoints;
		this.amountIncluded = amountIncluded;
		this.qtyIncluded = qtyIncluded;
		this.origInsuranceClaimAmount = origInsuranceClaimAmount;
		this.adjustmentRemarks = adjustmentRemarks;
		this.chargeHead = chargeHead;
		this.chargeGroup = chargeGroup;
		this.patientCategoryId = patientCategoryId;
		this.primarySponsorId = primarySponsorId;
		this.secondarySponsorId = secondarySponsorId;
		this.serviceSubGroupId = serviceSubGroupId;
		this.sponsorSwitch = sponsorSwitch;
	}

	@Column(name = "bill_charge_adjustment_id", nullable = false, length = 15)
	public String getBillChargeAdjustmentIdSequence() {
		return this.billChargeAdjustmentId;
	}

	public void setBillChargeAdjustmentIdSequence(String billChargeAdjustmentId) {
		this.billChargeAdjustmentId = billChargeAdjustmentId;
	}

	@Column(name = "adjustment_type", length = 1)
	public String getAdjustmentType() {
		return this.adjustmentType;
	}

	public void setAdjustmentType(String adjustmentType) {
		this.adjustmentType = adjustmentType;
	}

	@Column(name = "charge_id", nullable = false, length = 15)
	public String getChargeId() {
		return this.chargeId;
	}

	public void setChargeId(String chargeId) {
		this.chargeId = chargeId;
	}

	@Column(name = "bill_no", nullable = false, length = 15)
	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	@Column(name = "act_rate", precision = 15)
	public BigDecimal getActRate() {
		return this.actRate;
	}

	public void setActRate(BigDecimal actRate) {
		this.actRate = actRate;
	}

	@Column(name = "act_quantity", precision = 131089, scale = 0)
	public BigDecimal getActQuantity() {
		return this.actQuantity;
	}

	public void setActQuantity(BigDecimal actQuantity) {
		this.actQuantity = actQuantity;
	}

	@Column(name = "amount", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "discount", precision = 15)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "paid_amount", precision = 15)
	public BigDecimal getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(BigDecimal paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Column(name = "posted_date", nullable = false, length = 35)
	public Date getPostedDate() {
		return this.postedDate;
	}

	public void setPostedDate(Date postedDate) {
		this.postedDate = postedDate;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "mod_time", nullable = false, length = 35)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "orig_rate", precision = 15)
	public BigDecimal getOrigRate() {
		return this.origRate;
	}

	public void setOrigRate(BigDecimal origRate) {
		this.origRate = origRate;
	}

	@Column(name = "package_unit", precision = 131089, scale = 0)
	public BigDecimal getPackageUnit() {
		return this.packageUnit;
	}

	public void setPackageUnit(BigDecimal packageUnit) {
		this.packageUnit = packageUnit;
	}

	@Column(name = "doctor_amount", precision = 15)
	public BigDecimal getDoctorAmount() {
		return this.doctorAmount;
	}

	public void setDoctorAmount(BigDecimal doctorAmount) {
		this.doctorAmount = doctorAmount;
	}

	@Column(name = "insurance_claim_amount", nullable = false, precision = 15)
	public BigDecimal getInsuranceClaimAmount() {
		return this.insuranceClaimAmount;
	}

	public void setInsuranceClaimAmount(BigDecimal insuranceClaimAmount) {
		this.insuranceClaimAmount = insuranceClaimAmount;
	}

	@Column(name = "referal_amount", precision = 15)
	public BigDecimal getReferalAmount() {
		return this.referalAmount;
	}

	public void setReferalAmount(BigDecimal referalAmount) {
		this.referalAmount = referalAmount;
	}

	@Column(name = "out_house_amount", precision = 15)
	public BigDecimal getOutHouseAmount() {
		return this.outHouseAmount;
	}

	public void setOutHouseAmount(BigDecimal outHouseAmount) {
		this.outHouseAmount = outHouseAmount;
	}

	@Column(name = "prescribing_dr_amount", precision = 15)
	public BigDecimal getPrescribingDrAmount() {
		return this.prescribingDrAmount;
	}

	public void setPrescribingDrAmount(BigDecimal prescribingDrAmount) {
		this.prescribingDrAmount = prescribingDrAmount;
	}

	@Column(name = "overall_discount_amt", precision = 15)
	public BigDecimal getOverallDiscountAmt() {
		return this.overallDiscountAmt;
	}

	public void setOverallDiscountAmt(BigDecimal overallDiscountAmt) {
		this.overallDiscountAmt = overallDiscountAmt;
	}

	@Column(name = "dr_discount_amt", precision = 15)
	public BigDecimal getDrDiscountAmt() {
		return this.drDiscountAmt;
	}

	public void setDrDiscountAmt(BigDecimal drDiscountAmt) {
		this.drDiscountAmt = drDiscountAmt;
	}

	@Column(name = "pres_dr_discount_amt", precision = 15)
	public BigDecimal getPresDrDiscountAmt() {
		return this.presDrDiscountAmt;
	}

	public void setPresDrDiscountAmt(BigDecimal presDrDiscountAmt) {
		this.presDrDiscountAmt = presDrDiscountAmt;
	}

	@Column(name = "ref_discount_amt", precision = 15)
	public BigDecimal getRefDiscountAmt() {
		return this.refDiscountAmt;
	}

	public void setRefDiscountAmt(BigDecimal refDiscountAmt) {
		this.refDiscountAmt = refDiscountAmt;
	}

	@Column(name = "hosp_discount_amt", precision = 15)
	public BigDecimal getHospDiscountAmt() {
		return this.hospDiscountAmt;
	}

	public void setHospDiscountAmt(BigDecimal hospDiscountAmt) {
		this.hospDiscountAmt = hospDiscountAmt;
	}

	@Column(name = "claim_recd_total", precision = 15)
	public BigDecimal getClaimRecdTotal() {
		return this.claimRecdTotal;
	}

	public void setClaimRecdTotal(BigDecimal claimRecdTotal) {
		this.claimRecdTotal = claimRecdTotal;
	}

	@Column(name = "return_insurance_claim_amt", precision = 15)
	public BigDecimal getReturnInsuranceClaimAmt() {
		return this.returnInsuranceClaimAmt;
	}

	public void setReturnInsuranceClaimAmt(BigDecimal returnInsuranceClaimAmt) {
		this.returnInsuranceClaimAmt = returnInsuranceClaimAmt;
	}

	@Column(name = "return_amt", precision = 15)
	public BigDecimal getReturnAmt() {
		return this.returnAmt;
	}

	public void setReturnAmt(BigDecimal returnAmt) {
		this.returnAmt = returnAmt;
	}

	@Column(name = "return_qty", precision = 131089, scale = 0)
	public BigDecimal getReturnQty() {
		return this.returnQty;
	}

	public void setReturnQty(BigDecimal returnQty) {
		this.returnQty = returnQty;
	}

	@Column(name = "redeemed_points", nullable = false)
	public int getRedeemedPoints() {
		return this.redeemedPoints;
	}

	public void setRedeemedPoints(int redeemedPoints) {
		this.redeemedPoints = redeemedPoints;
	}

	@Column(name = "amount_included", nullable = false, precision = 15)
	public BigDecimal getAmountIncluded() {
		return this.amountIncluded;
	}

	public void setAmountIncluded(BigDecimal amountIncluded) {
		this.amountIncluded = amountIncluded;
	}

	@Column(name = "qty_included", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQtyIncluded() {
		return this.qtyIncluded;
	}

	public void setQtyIncluded(BigDecimal qtyIncluded) {
		this.qtyIncluded = qtyIncluded;
	}

	@Column(name = "orig_insurance_claim_amount", nullable = false, precision = 15)
	public BigDecimal getOrigInsuranceClaimAmount() {
		return this.origInsuranceClaimAmount;
	}

	public void setOrigInsuranceClaimAmount(BigDecimal origInsuranceClaimAmount) {
		this.origInsuranceClaimAmount = origInsuranceClaimAmount;
	}

	@Column(name = "adjustment_remarks", length = 100)
	public String getAdjustmentRemarks() {
		return this.adjustmentRemarks;
	}

	public void setAdjustmentRemarks(String adjustmentRemarks) {
		this.adjustmentRemarks = adjustmentRemarks;
	}

	@Column(name = "charge_head", length = 20)
	public String getChargeHead() {
		return this.chargeHead;
	}

	public void setChargeHead(String chargeHead) {
		this.chargeHead = chargeHead;
	}

	@Column(name = "charge_group", length = 40)
	public String getChargeGroup() {
		return this.chargeGroup;
	}

	public void setChargeGroup(String chargeGroup) {
		this.chargeGroup = chargeGroup;
	}

	@Column(name = "patient_category_id")
	public Integer getPatientCategoryId() {
		return this.patientCategoryId;
	}

	public void setPatientCategoryId(Integer patientCategoryId) {
		this.patientCategoryId = patientCategoryId;
	}

	@Column(name = "primary_sponsor_id", length = 20)
	public String getPrimarySponsorId() {
		return this.primarySponsorId;
	}

	public void setPrimarySponsorId(String primarySponsorId) {
		this.primarySponsorId = primarySponsorId;
	}

	@Column(name = "secondary_sponsor_id", length = 20)
	public String getSecondarySponsorId() {
		return this.secondarySponsorId;
	}

	public void setSecondarySponsorId(String secondarySponsorId) {
		this.secondarySponsorId = secondarySponsorId;
	}

	@Column(name = "service_sub_group_id")
	public Integer getServiceSubGroupId() {
		return this.serviceSubGroupId;
	}

	public void setServiceSubGroupId(Integer serviceSubGroupId) {
		this.serviceSubGroupId = serviceSubGroupId;
	}

	@Column(name = "sponsor_switch")
	public Boolean getSponsorSwitch() {
		return this.sponsorSwitch;
	}

	public void setSponsorSwitch(Boolean sponsorSwitch) {
		this.sponsorSwitch = sponsorSwitch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BillChargeAdjustmentIdSequence))
			return false;
		BillChargeAdjustmentIdSequence castOther = (BillChargeAdjustmentIdSequence) other;

		return ((this.getBillChargeAdjustmentIdSequence() == castOther.getBillChargeAdjustmentIdSequence())
				|| (this.getBillChargeAdjustmentIdSequence() != null && castOther.getBillChargeAdjustmentIdSequence() != null
						&& this.getBillChargeAdjustmentIdSequence().equals(castOther.getBillChargeAdjustmentIdSequence())))
				&& ((this.getAdjustmentType() == castOther.getAdjustmentType())
						|| (this.getAdjustmentType() != null && castOther.getAdjustmentType() != null
								&& this.getAdjustmentType().equals(castOther.getAdjustmentType())))
				&& ((this.getChargeId() == castOther.getChargeId()) || (this.getChargeId() != null
						&& castOther.getChargeId() != null && this.getChargeId().equals(castOther.getChargeId())))
				&& ((this.getBillNo() == castOther.getBillNo()) || (this.getBillNo() != null
						&& castOther.getBillNo() != null && this.getBillNo().equals(castOther.getBillNo())))
				&& ((this.getActRate() == castOther.getActRate()) || (this.getActRate() != null
						&& castOther.getActRate() != null && this.getActRate().equals(castOther.getActRate())))
				&& ((this.getActQuantity() == castOther.getActQuantity())
						|| (this.getActQuantity() != null && castOther.getActQuantity() != null
								&& this.getActQuantity().equals(castOther.getActQuantity())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& ((this.getDiscount() == castOther.getDiscount()) || (this.getDiscount() != null
						&& castOther.getDiscount() != null && this.getDiscount().equals(castOther.getDiscount())))
				&& ((this.getPaidAmount() == castOther.getPaidAmount()) || (this.getPaidAmount() != null
						&& castOther.getPaidAmount() != null && this.getPaidAmount().equals(castOther.getPaidAmount())))
				&& ((this.getPostedDate() == castOther.getPostedDate()) || (this.getPostedDate() != null
						&& castOther.getPostedDate() != null && this.getPostedDate().equals(castOther.getPostedDate())))
				&& (this.getStatus() == castOther.getStatus())
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getModTime() == castOther.getModTime()) || (this.getModTime() != null
						&& castOther.getModTime() != null && this.getModTime().equals(castOther.getModTime())))
				&& ((this.getOrigRate() == castOther.getOrigRate()) || (this.getOrigRate() != null
						&& castOther.getOrigRate() != null && this.getOrigRate().equals(castOther.getOrigRate())))
				&& ((this.getPackageUnit() == castOther.getPackageUnit())
						|| (this.getPackageUnit() != null && castOther.getPackageUnit() != null
								&& this.getPackageUnit().equals(castOther.getPackageUnit())))
				&& ((this.getDoctorAmount() == castOther.getDoctorAmount())
						|| (this.getDoctorAmount() != null && castOther.getDoctorAmount() != null
								&& this.getDoctorAmount().equals(castOther.getDoctorAmount())))
				&& ((this.getInsuranceClaimAmount() == castOther.getInsuranceClaimAmount())
						|| (this.getInsuranceClaimAmount() != null && castOther.getInsuranceClaimAmount() != null
								&& this.getInsuranceClaimAmount().equals(castOther.getInsuranceClaimAmount())))
				&& ((this.getReferalAmount() == castOther.getReferalAmount())
						|| (this.getReferalAmount() != null && castOther.getReferalAmount() != null
								&& this.getReferalAmount().equals(castOther.getReferalAmount())))
				&& ((this.getOutHouseAmount() == castOther.getOutHouseAmount())
						|| (this.getOutHouseAmount() != null && castOther.getOutHouseAmount() != null
								&& this.getOutHouseAmount().equals(castOther.getOutHouseAmount())))
				&& ((this.getPrescribingDrAmount() == castOther.getPrescribingDrAmount())
						|| (this.getPrescribingDrAmount() != null && castOther.getPrescribingDrAmount() != null
								&& this.getPrescribingDrAmount().equals(castOther.getPrescribingDrAmount())))
				&& ((this.getOverallDiscountAmt() == castOther.getOverallDiscountAmt())
						|| (this.getOverallDiscountAmt() != null && castOther.getOverallDiscountAmt() != null
								&& this.getOverallDiscountAmt().equals(castOther.getOverallDiscountAmt())))
				&& ((this.getDrDiscountAmt() == castOther.getDrDiscountAmt())
						|| (this.getDrDiscountAmt() != null && castOther.getDrDiscountAmt() != null
								&& this.getDrDiscountAmt().equals(castOther.getDrDiscountAmt())))
				&& ((this.getPresDrDiscountAmt() == castOther.getPresDrDiscountAmt())
						|| (this.getPresDrDiscountAmt() != null && castOther.getPresDrDiscountAmt() != null
								&& this.getPresDrDiscountAmt().equals(castOther.getPresDrDiscountAmt())))
				&& ((this.getRefDiscountAmt() == castOther.getRefDiscountAmt())
						|| (this.getRefDiscountAmt() != null && castOther.getRefDiscountAmt() != null
								&& this.getRefDiscountAmt().equals(castOther.getRefDiscountAmt())))
				&& ((this.getHospDiscountAmt() == castOther.getHospDiscountAmt())
						|| (this.getHospDiscountAmt() != null && castOther.getHospDiscountAmt() != null
								&& this.getHospDiscountAmt().equals(castOther.getHospDiscountAmt())))
				&& ((this.getClaimRecdTotal() == castOther.getClaimRecdTotal())
						|| (this.getClaimRecdTotal() != null && castOther.getClaimRecdTotal() != null
								&& this.getClaimRecdTotal().equals(castOther.getClaimRecdTotal())))
				&& ((this.getReturnInsuranceClaimAmt() == castOther.getReturnInsuranceClaimAmt())
						|| (this.getReturnInsuranceClaimAmt() != null && castOther.getReturnInsuranceClaimAmt() != null
								&& this.getReturnInsuranceClaimAmt().equals(castOther.getReturnInsuranceClaimAmt())))
				&& ((this.getReturnAmt() == castOther.getReturnAmt()) || (this.getReturnAmt() != null
						&& castOther.getReturnAmt() != null && this.getReturnAmt().equals(castOther.getReturnAmt())))
				&& ((this.getReturnQty() == castOther.getReturnQty()) || (this.getReturnQty() != null
						&& castOther.getReturnQty() != null && this.getReturnQty().equals(castOther.getReturnQty())))
				&& (this.getRedeemedPoints() == castOther.getRedeemedPoints())
				&& ((this.getAmountIncluded() == castOther.getAmountIncluded())
						|| (this.getAmountIncluded() != null && castOther.getAmountIncluded() != null
								&& this.getAmountIncluded().equals(castOther.getAmountIncluded())))
				&& ((this.getQtyIncluded() == castOther.getQtyIncluded())
						|| (this.getQtyIncluded() != null && castOther.getQtyIncluded() != null
								&& this.getQtyIncluded().equals(castOther.getQtyIncluded())))
				&& ((this.getOrigInsuranceClaimAmount() == castOther.getOrigInsuranceClaimAmount())
						|| (this.getOrigInsuranceClaimAmount() != null
								&& castOther.getOrigInsuranceClaimAmount() != null
								&& this.getOrigInsuranceClaimAmount().equals(castOther.getOrigInsuranceClaimAmount())))
				&& ((this.getAdjustmentRemarks() == castOther.getAdjustmentRemarks())
						|| (this.getAdjustmentRemarks() != null && castOther.getAdjustmentRemarks() != null
								&& this.getAdjustmentRemarks().equals(castOther.getAdjustmentRemarks())))
				&& ((this.getChargeHead() == castOther.getChargeHead()) || (this.getChargeHead() != null
						&& castOther.getChargeHead() != null && this.getChargeHead().equals(castOther.getChargeHead())))
				&& ((this.getChargeGroup() == castOther.getChargeGroup())
						|| (this.getChargeGroup() != null && castOther.getChargeGroup() != null
								&& this.getChargeGroup().equals(castOther.getChargeGroup())))
				&& ((this.getPatientCategoryId() == castOther.getPatientCategoryId())
						|| (this.getPatientCategoryId() != null && castOther.getPatientCategoryId() != null
								&& this.getPatientCategoryId().equals(castOther.getPatientCategoryId())))
				&& ((this.getPrimarySponsorId() == castOther.getPrimarySponsorId())
						|| (this.getPrimarySponsorId() != null && castOther.getPrimarySponsorId() != null
								&& this.getPrimarySponsorId().equals(castOther.getPrimarySponsorId())))
				&& ((this.getSecondarySponsorId() == castOther.getSecondarySponsorId())
						|| (this.getSecondarySponsorId() != null && castOther.getSecondarySponsorId() != null
								&& this.getSecondarySponsorId().equals(castOther.getSecondarySponsorId())))
				&& ((this.getServiceSubGroupId() == castOther.getServiceSubGroupId())
						|| (this.getServiceSubGroupId() != null && castOther.getServiceSubGroupId() != null
								&& this.getServiceSubGroupId().equals(castOther.getServiceSubGroupId())))
				&& ((this.getSponsorSwitch() == castOther.getSponsorSwitch())
						|| (this.getSponsorSwitch() != null && castOther.getSponsorSwitch() != null
								&& this.getSponsorSwitch().equals(castOther.getSponsorSwitch())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBillChargeAdjustmentIdSequence() == null ? 0 : this.getBillChargeAdjustmentIdSequence().hashCode());
		result = 37 * result + (getAdjustmentType() == null ? 0 : this.getAdjustmentType().hashCode());
		result = 37 * result + (getChargeId() == null ? 0 : this.getChargeId().hashCode());
		result = 37 * result + (getBillNo() == null ? 0 : this.getBillNo().hashCode());
		result = 37 * result + (getActRate() == null ? 0 : this.getActRate().hashCode());
		result = 37 * result + (getActQuantity() == null ? 0 : this.getActQuantity().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getDiscount() == null ? 0 : this.getDiscount().hashCode());
		result = 37 * result + (getPaidAmount() == null ? 0 : this.getPaidAmount().hashCode());
		result = 37 * result + (getPostedDate() == null ? 0 : this.getPostedDate().hashCode());
		result = 37 * result + this.getStatus();
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getModTime() == null ? 0 : this.getModTime().hashCode());
		result = 37 * result + (getOrigRate() == null ? 0 : this.getOrigRate().hashCode());
		result = 37 * result + (getPackageUnit() == null ? 0 : this.getPackageUnit().hashCode());
		result = 37 * result + (getDoctorAmount() == null ? 0 : this.getDoctorAmount().hashCode());
		result = 37 * result + (getInsuranceClaimAmount() == null ? 0 : this.getInsuranceClaimAmount().hashCode());
		result = 37 * result + (getReferalAmount() == null ? 0 : this.getReferalAmount().hashCode());
		result = 37 * result + (getOutHouseAmount() == null ? 0 : this.getOutHouseAmount().hashCode());
		result = 37 * result + (getPrescribingDrAmount() == null ? 0 : this.getPrescribingDrAmount().hashCode());
		result = 37 * result + (getOverallDiscountAmt() == null ? 0 : this.getOverallDiscountAmt().hashCode());
		result = 37 * result + (getDrDiscountAmt() == null ? 0 : this.getDrDiscountAmt().hashCode());
		result = 37 * result + (getPresDrDiscountAmt() == null ? 0 : this.getPresDrDiscountAmt().hashCode());
		result = 37 * result + (getRefDiscountAmt() == null ? 0 : this.getRefDiscountAmt().hashCode());
		result = 37 * result + (getHospDiscountAmt() == null ? 0 : this.getHospDiscountAmt().hashCode());
		result = 37 * result + (getClaimRecdTotal() == null ? 0 : this.getClaimRecdTotal().hashCode());
		result = 37 * result
				+ (getReturnInsuranceClaimAmt() == null ? 0 : this.getReturnInsuranceClaimAmt().hashCode());
		result = 37 * result + (getReturnAmt() == null ? 0 : this.getReturnAmt().hashCode());
		result = 37 * result + (getReturnQty() == null ? 0 : this.getReturnQty().hashCode());
		result = 37 * result + this.getRedeemedPoints();
		result = 37 * result + (getAmountIncluded() == null ? 0 : this.getAmountIncluded().hashCode());
		result = 37 * result + (getQtyIncluded() == null ? 0 : this.getQtyIncluded().hashCode());
		result = 37 * result
				+ (getOrigInsuranceClaimAmount() == null ? 0 : this.getOrigInsuranceClaimAmount().hashCode());
		result = 37 * result + (getAdjustmentRemarks() == null ? 0 : this.getAdjustmentRemarks().hashCode());
		result = 37 * result + (getChargeHead() == null ? 0 : this.getChargeHead().hashCode());
		result = 37 * result + (getChargeGroup() == null ? 0 : this.getChargeGroup().hashCode());
		result = 37 * result + (getPatientCategoryId() == null ? 0 : this.getPatientCategoryId().hashCode());
		result = 37 * result + (getPrimarySponsorId() == null ? 0 : this.getPrimarySponsorId().hashCode());
		result = 37 * result + (getSecondarySponsorId() == null ? 0 : this.getSecondarySponsorId().hashCode());
		result = 37 * result + (getServiceSubGroupId() == null ? 0 : this.getServiceSubGroupId().hashCode());
		result = 37 * result + (getSponsorSwitch() == null ? 0 : this.getSponsorSwitch().hashCode());
		return result;
	}

}
