package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BillCreditNotesModel generated by hbm2java
 */
@Entity
@Table(name = "bill_credit_notes")
public class BillCreditNotesModel implements java.io.Serializable {

	private BillCreditNotesIdSequence id;

	public BillCreditNotesModel() {
	}

	public BillCreditNotesModel(BillCreditNotesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "billNo", column = @Column(name = "bill_no", length = 15)),
			@AttributeOverride(name = "creditNoteBillNo", column = @Column(name = "credit_note_bill_no", length = 15)),
			@AttributeOverride(name = "totalAmount", column = @Column(name = "total_amount", precision = 15)),
			@AttributeOverride(name = "totalClaim", column = @Column(name = "total_claim", precision = 15)) })
	public BillCreditNotesIdSequence getId() {
		return this.id;
	}

	public void setId(BillCreditNotesIdSequence id) {
		this.id = id;
	}

}
