package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BillAvailableTemplatesModel generated by hbm2java
 */
@Entity
@Table(name = "bill_available_templates")
public class BillAvailableTemplatesModel implements java.io.Serializable {

	private BillAvailableTemplatesIdSequence id;

	public BillAvailableTemplatesModel() {
	}

	public BillAvailableTemplatesModel(BillAvailableTemplatesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "templateId", column = @Column(name = "template_id")),
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name")),
			@AttributeOverride(name = "billType", column = @Column(name = "bill_type", length = 1)),
			@AttributeOverride(name = "insuranceType", column = @Column(name = "insurance_type", length = 1)),
			@AttributeOverride(name = "displayOrder", column = @Column(name = "display_order")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)) })
	public BillAvailableTemplatesIdSequence getId() {
		return this.id;
	}

	public void setId(BillAvailableTemplatesIdSequence id) {
		this.id = id;
	}

}
