package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillSponsorModel generated by hbm2java
 */
@Entity
@Table(name = "bill_sponsor")
public class BillSponsorModel implements java.io.Serializable {

	private String sponsorBillNo;
	private String sponsorId;
	private BigDecimal claimAmt;
	private Date claimDate;
	private Character status;
	private String userid;
	private String remarks;
	private char sponsorType;
	private Date sentDate;
	private String sentBy;
	private Date closedDate;
	private String closedBy;
	private String cancelReason;
	private Date modTime;

	public BillSponsorModel() {
	}

	public BillSponsorModel(String sponsorBillNo, String sponsorId, BigDecimal claimAmt, Date claimDate, char sponsorType,
			Date modTime) {
		this.sponsorBillNo = sponsorBillNo;
		this.sponsorId = sponsorId;
		this.claimAmt = claimAmt;
		this.claimDate = claimDate;
		this.sponsorType = sponsorType;
		this.modTime = modTime;
	}

	public BillSponsorModel(String sponsorBillNo, String sponsorId, BigDecimal claimAmt, Date claimDate, Character status,
			String userid, String remarks, char sponsorType, Date sentDate, String sentBy, Date closedDate,
			String closedBy, String cancelReason, Date modTime) {
		this.sponsorBillNo = sponsorBillNo;
		this.sponsorId = sponsorId;
		this.claimAmt = claimAmt;
		this.claimDate = claimDate;
		this.status = status;
		this.userid = userid;
		this.remarks = remarks;
		this.sponsorType = sponsorType;
		this.sentDate = sentDate;
		this.sentBy = sentBy;
		this.closedDate = closedDate;
		this.closedBy = closedBy;
		this.cancelReason = cancelReason;
		this.modTime = modTime;
	}

	@Id

	@Column(name = "sponsor_bill_no", unique = true, nullable = false, length = 15)
	public String getSponsorBillNo() {
		return this.sponsorBillNo;
	}

	public void setSponsorBillNo(String sponsorBillNo) {
		this.sponsorBillNo = sponsorBillNo;
	}

	@Column(name = "sponsor_id", nullable = false, length = 15)
	public String getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(String sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "claim_amt", nullable = false, precision = 15)
	public BigDecimal getClaimAmt() {
		return this.claimAmt;
	}

	public void setClaimAmt(BigDecimal claimAmt) {
		this.claimAmt = claimAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "claim_date", nullable = false, length = 29)
	public Date getClaimDate() {
		return this.claimDate;
	}

	public void setClaimDate(Date claimDate) {
		this.claimDate = claimDate;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "userid", length = 30)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "sponsor_type", nullable = false, length = 1)
	public char getSponsorType() {
		return this.sponsorType;
	}

	public void setSponsorType(char sponsorType) {
		this.sponsorType = sponsorType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sent_date", length = 29)
	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	@Column(name = "sent_by", length = 30)
	public String getSentBy() {
		return this.sentBy;
	}

	public void setSentBy(String sentBy) {
		this.sentBy = sentBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "closed_date", length = 29)
	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	@Column(name = "closed_by", length = 30)
	public String getClosedBy() {
		return this.closedBy;
	}

	public void setClosedBy(String closedBy) {
		this.closedBy = closedBy;
	}

	@Column(name = "cancel_reason", length = 100)
	public String getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

}
