package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillApprovalsModel generated by hbm2java
 */
@Entity
@Table(name = "bill_approvals")
public class BillApprovalsModel implements java.io.Serializable {

	private String approvalId;
	private Date approvalDate;
	private String username;
	private char exported;
	private int numTxns;
	private Date minTxnDate;
	private Date maxTxnDate;

	public BillApprovalsModel() {
	}

	public BillApprovalsModel(String approvalId, Date approvalDate, String username, char exported, int numTxns) {
		this.approvalId = approvalId;
		this.approvalDate = approvalDate;
		this.username = username;
		this.exported = exported;
		this.numTxns = numTxns;
	}

	public BillApprovalsModel(String approvalId, Date approvalDate, String username, char exported, int numTxns,
			Date minTxnDate, Date maxTxnDate) {
		this.approvalId = approvalId;
		this.approvalDate = approvalDate;
		this.username = username;
		this.exported = exported;
		this.numTxns = numTxns;
		this.minTxnDate = minTxnDate;
		this.maxTxnDate = maxTxnDate;
	}

	@Id

	@Column(name = "approval_id", unique = true, nullable = false, length = 10)
	public String getApprovalId() {
		return this.approvalId;
	}

	public void setApprovalId(String approvalId) {
		this.approvalId = approvalId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "approval_date", nullable = false, length = 13)
	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "exported", nullable = false, length = 1)
	public char getExported() {
		return this.exported;
	}

	public void setExported(char exported) {
		this.exported = exported;
	}

	@Column(name = "num_txns", nullable = false)
	public int getNumTxns() {
		return this.numTxns;
	}

	public void setNumTxns(int numTxns) {
		this.numTxns = numTxns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "min_txn_date", length = 13)
	public Date getMinTxnDate() {
		return this.minTxnDate;
	}

	public void setMinTxnDate(Date minTxnDate) {
		this.minTxnDate = minTxnDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "max_txn_date", length = 13)
	public Date getMaxTxnDate() {
		return this.maxTxnDate;
	}

	public void setMaxTxnDate(Date maxTxnDate) {
		this.maxTxnDate = maxTxnDate;
	}

}
