package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BloodComponentsMasterModel generated by hbm2java
 */
@Entity
@Table(name = "blood_components_master")
public class BloodComponentsMasterModel implements java.io.Serializable {

	private String bcmasterId;
	private String donorBloodComponentName;
	private Character status;

	public BloodComponentsMasterModel() {
	}

	public BloodComponentsMasterModel(String bcmasterId) {
		this.bcmasterId = bcmasterId;
	}

	public BloodComponentsMasterModel(String bcmasterId, String donorBloodComponentName, Character status) {
		this.bcmasterId = bcmasterId;
		this.donorBloodComponentName = donorBloodComponentName;
		this.status = status;
	}

	@Id

	@Column(name = "bcmaster_id", unique = true, nullable = false, length = 50)
	public String getBcmasterId() {
		return this.bcmasterId;
	}

	public void setBcmasterId(String bcmasterId) {
		this.bcmasterId = bcmasterId;
	}

	@Column(name = "donor_blood_component_name", length = 50)
	public String getDonorBloodComponentName() {
		return this.donorBloodComponentName;
	}

	public void setDonorBloodComponentName(String donorBloodComponentName) {
		this.donorBloodComponentName = donorBloodComponentName;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

}
