package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CeedIntegrationDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "ceed_integration_details")
public class CeedIntegrationDetailsModel implements java.io.Serializable {

	private CeedIntegrationDetailsIdSequence id;

	public CeedIntegrationDetailsModel() {
	}

	public CeedIntegrationDetailsModel(CeedIntegrationDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "claimId", column = @Column(name = "claim_id")),
			@AttributeOverride(name = "claimRefNum", column = @Column(name = "claim_ref_num")),
			@AttributeOverride(name = "activityId", column = @Column(name = "activity_id")),
			@AttributeOverride(name = "activityCodeType", column = @Column(name = "activity_code_type", length = 50)),
			@AttributeOverride(name = "activityCode", column = @Column(name = "activity_code", length = 100)),
			@AttributeOverride(name = "claimEditId", column = @Column(name = "claim_edit_id")),
			@AttributeOverride(name = "claimEditSubType", column = @Column(name = "claim_edit_sub_type")),
			@AttributeOverride(name = "claimEditCode", column = @Column(name = "claim_edit_code")),
			@AttributeOverride(name = "claimEditRank", column = @Column(name = "claim_edit_rank", length = 2)),
			@AttributeOverride(name = "claimEditResponseComments", column = @Column(name = "claim_edit_response_comments")),
			@AttributeOverride(name = "chargeId", column = @Column(name = "charge_id", length = 15)) })
	public CeedIntegrationDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(CeedIntegrationDetailsIdSequence id) {
		this.id = id;
	}

}
