package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CenterReportDelivDaysOverridesModel generated by hbm2java
 */
@Entity
@Table(name = "center_report_deliv_days_overrides")
public class CenterReportDelivDaysOverridesModel implements java.io.Serializable {

	private int repDelivOverrideId;
	private Integer centerId;
	private Date day;

	public CenterReportDelivDaysOverridesModel() {
	}

	public CenterReportDelivDaysOverridesModel(int repDelivOverrideId) {
		this.repDelivOverrideId = repDelivOverrideId;
	}

	public CenterReportDelivDaysOverridesModel(int repDelivOverrideId, Integer centerId, Date day) {
		this.repDelivOverrideId = repDelivOverrideId;
		this.centerId = centerId;
		this.day = day;
	}

	@Id

	@Column(name = "rep_deliv_override_id", unique = true, nullable = false)
	public int getRepDelivOverrideId() {
		return this.repDelivOverrideId;
	}

	public void setRepDelivOverrideId(int repDelivOverrideId) {
		this.repDelivOverrideId = repDelivOverrideId;
	}

	@Column(name = "center_id")
	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "day", length = 13)
	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

}
