package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CenterReportDelivOverrideDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "center_report_deliv_override_details")
public class CenterReportDelivOverrideDetailsModel implements java.io.Serializable {

	private int repDeliveryOverrideTimeId;
	private Integer repDelivOverrideId;
	private Date deliveryTime;

	public CenterReportDelivOverrideDetailsModel() {
	}

	public CenterReportDelivOverrideDetailsModel(int repDeliveryOverrideTimeId) {
		this.repDeliveryOverrideTimeId = repDeliveryOverrideTimeId;
	}

	public CenterReportDelivOverrideDetailsModel(int repDeliveryOverrideTimeId, Integer repDelivOverrideId,
			Date deliveryTime) {
		this.repDeliveryOverrideTimeId = repDeliveryOverrideTimeId;
		this.repDelivOverrideId = repDelivOverrideId;
		this.deliveryTime = deliveryTime;
	}

	@Id

	@Column(name = "rep_delivery_override_time_id", unique = true, nullable = false)
	public int getRepDeliveryOverrideTimeId() {
		return this.repDeliveryOverrideTimeId;
	}

	public void setRepDeliveryOverrideTimeId(int repDeliveryOverrideTimeId) {
		this.repDeliveryOverrideTimeId = repDeliveryOverrideTimeId;
	}

	@Column(name = "rep_deliv_override_id")
	public Integer getRepDelivOverrideId() {
		return this.repDelivOverrideId;
	}

	public void setRepDelivOverrideId(Integer repDelivOverrideId) {
		this.repDelivOverrideId = repDelivOverrideId;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "delivery_time", length = 15)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

}
