package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CenterOutsourcesModel generated by hbm2java
 */
@Entity
@Table(name = "center_outsources")
public class CenterOutsourcesModel implements java.io.Serializable {

	private CenterOutsourcesIdSequence id;

	public CenterOutsourcesModel() {
	}

	public CenterOutsourcesModel(CenterOutsourcesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "outsourceId", column = @Column(name = "outsource_id", nullable = false, length = 50)),
			@AttributeOverride(name = "centerId", column = @Column(name = "center_id", nullable = false)),
			@AttributeOverride(name = "obsoleteDefaultOutsource", column = @Column(name = "obsolete_default_outsource", length = 1)) })
	public CenterOutsourcesIdSequence getId() {
		return this.id;
	}

	public void setId(CenterOutsourcesIdSequence id) {
		this.id = id;
	}

}
