package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClinicalInfectionsModel generated by hbm2java
 */
@Entity
@Table(name = "clinical_infections")
public class ClinicalInfectionsModel implements java.io.Serializable {

	private int infectionId;
	private int clinicalInfectionsRecordedId;
	private Integer infectionTypeId;
	private Date infectionEffectiveDate;
	private String infectingOrganism;
	private String antiMicrobialSusceptibility;
	private char infectionStatus;
	private String remarks;
	private Integer infectionSiteId;

	public ClinicalInfectionsModel() {
	}

	public ClinicalInfectionsModel(int infectionId, int clinicalInfectionsRecordedId, char infectionStatus) {
		this.infectionId = infectionId;
		this.clinicalInfectionsRecordedId = clinicalInfectionsRecordedId;
		this.infectionStatus = infectionStatus;
	}

	public ClinicalInfectionsModel(int infectionId, int clinicalInfectionsRecordedId, Integer infectionTypeId,
			Date infectionEffectiveDate, String infectingOrganism, String antiMicrobialSusceptibility,
			char infectionStatus, String remarks, Integer infectionSiteId) {
		this.infectionId = infectionId;
		this.clinicalInfectionsRecordedId = clinicalInfectionsRecordedId;
		this.infectionTypeId = infectionTypeId;
		this.infectionEffectiveDate = infectionEffectiveDate;
		this.infectingOrganism = infectingOrganism;
		this.antiMicrobialSusceptibility = antiMicrobialSusceptibility;
		this.infectionStatus = infectionStatus;
		this.remarks = remarks;
		this.infectionSiteId = infectionSiteId;
	}

	@Id

	@Column(name = "infection_id", unique = true, nullable = false)
	public int getInfectionId() {
		return this.infectionId;
	}

	public void setInfectionId(int infectionId) {
		this.infectionId = infectionId;
	}

	@Column(name = "clinical_infections_recorded_id", nullable = false)
	public int getClinicalInfectionsModelRecordedId() {
		return this.clinicalInfectionsRecordedId;
	}

	public void setClinicalInfectionsModelRecordedId(int clinicalInfectionsRecordedId) {
		this.clinicalInfectionsRecordedId = clinicalInfectionsRecordedId;
	}

	@Column(name = "infection_type_id")
	public Integer getInfectionTypeId() {
		return this.infectionTypeId;
	}

	public void setInfectionTypeId(Integer infectionTypeId) {
		this.infectionTypeId = infectionTypeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "infection_effective_date", length = 13)
	public Date getInfectionEffectiveDate() {
		return this.infectionEffectiveDate;
	}

	public void setInfectionEffectiveDate(Date infectionEffectiveDate) {
		this.infectionEffectiveDate = infectionEffectiveDate;
	}

	@Column(name = "infecting_organism", length = 500)
	public String getInfectingOrganism() {
		return this.infectingOrganism;
	}

	public void setInfectingOrganism(String infectingOrganism) {
		this.infectingOrganism = infectingOrganism;
	}

	@Column(name = "anti_microbial_susceptibility", length = 200)
	public String getAntiMicrobialSusceptibility() {
		return this.antiMicrobialSusceptibility;
	}

	public void setAntiMicrobialSusceptibility(String antiMicrobialSusceptibility) {
		this.antiMicrobialSusceptibility = antiMicrobialSusceptibility;
	}

	@Column(name = "infection_status", nullable = false, length = 1)
	public char getInfectionStatus() {
		return this.infectionStatus;
	}

	public void setInfectionStatus(char infectionStatus) {
		this.infectionStatus = infectionStatus;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "infection_site_id")
	public Integer getInfectionSiteId() {
		return this.infectionSiteId;
	}

	public void setInfectionSiteId(Integer infectionSiteId) {
		this.infectionSiteId = infectionSiteId;
	}

}
