package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClinicalHospitalizationDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "clinical_hospitalization_details")
public class ClinicalHospitalizationDetailsModel implements java.io.Serializable {

	private int hospitalizationDetailsId;
	private int hospitalizationId;
	private String hospitalName;
	private Date admissionDate;
	private Date dischargeDate;
	private int reasonId;
	private String remarks;

	public ClinicalHospitalizationDetailsModel() {
	}

	public ClinicalHospitalizationDetailsModel(int hospitalizationDetailsId, int hospitalizationId, int reasonId) {
		this.hospitalizationDetailsId = hospitalizationDetailsId;
		this.hospitalizationId = hospitalizationId;
		this.reasonId = reasonId;
	}

	public ClinicalHospitalizationDetailsModel(int hospitalizationDetailsId, int hospitalizationId, String hospitalName,
			Date admissionDate, Date dischargeDate, int reasonId, String remarks) {
		this.hospitalizationDetailsId = hospitalizationDetailsId;
		this.hospitalizationId = hospitalizationId;
		this.hospitalName = hospitalName;
		this.admissionDate = admissionDate;
		this.dischargeDate = dischargeDate;
		this.reasonId = reasonId;
		this.remarks = remarks;
	}

	@Id

	@Column(name = "hospitalization_details_id", unique = true, nullable = false)
	public int getHospitalizationDetailsId() {
		return this.hospitalizationDetailsId;
	}

	public void setHospitalizationDetailsId(int hospitalizationDetailsId) {
		this.hospitalizationDetailsId = hospitalizationDetailsId;
	}

	@Column(name = "hospitalization_id", nullable = false)
	public int getHospitalizationId() {
		return this.hospitalizationId;
	}

	public void setHospitalizationId(int hospitalizationId) {
		this.hospitalizationId = hospitalizationId;
	}

	@Column(name = "hospital_name", length = 500)
	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admission_date", length = 13)
	public Date getAdmissionDate() {
		return this.admissionDate;
	}

	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "discharge_date", length = 13)
	public Date getDischargeDate() {
		return this.dischargeDate;
	}

	public void setDischargeDate(Date dischargeDate) {
		this.dischargeDate = dischargeDate;
	}

	@Column(name = "reason_id", nullable = false)
	public int getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(int reasonId) {
		this.reasonId = reasonId;
	}

	@Column(name = "remarks", length = 2000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
