package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClinicalBloodTransfusionsModel generated by hbm2java
 */
@Entity
@Table(name = "clinical_blood_transfusions")
public class ClinicalBloodTransfusionsModel implements java.io.Serializable {

	private int transfusionId;
	private String mrNo;
	private Date dataAsOfDate;
	private String userName;
	private Date modTime;
	private Set clinicalTransfusionDetailses = new HashSet(0);

	public ClinicalBloodTransfusionsModel() {
	}

	public ClinicalBloodTransfusionsModel(int transfusionId) {
		this.transfusionId = transfusionId;
	}

	public ClinicalBloodTransfusionsModel(int transfusionId, String mrNo, Date dataAsOfDate, String userName, Date modTime,
			Set clinicalTransfusionDetailses) {
		this.transfusionId = transfusionId;
		this.mrNo = mrNo;
		this.dataAsOfDate = dataAsOfDate;
		this.userName = userName;
		this.modTime = modTime;
		this.clinicalTransfusionDetailses = clinicalTransfusionDetailses;
	}

	@Id

	@Column(name = "transfusion_id", unique = true, nullable = false)
	public int getTransfusionId() {
		return this.transfusionId;
	}

	public void setTransfusionId(int transfusionId) {
		this.transfusionId = transfusionId;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_as_of_date", length = 13)
	public Date getDataAsOfDate() {
		return this.dataAsOfDate;
	}

	public void setDataAsOfDate(Date dataAsOfDate) {
		this.dataAsOfDate = dataAsOfDate;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clinicalBloodTransfusions")
	public Set getClinicalTransfusionDetailses() {
		return this.clinicalTransfusionDetailses;
	}

	public void setClinicalTransfusionDetailses(Set clinicalTransfusionDetailses) {
		this.clinicalTransfusionDetailses = clinicalTransfusionDetailses;
	}

}
