package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClinicalVaccinationsDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "clinical_vaccinations_details")
public class ClinicalVaccinationsDetailsModel implements java.io.Serializable {

	private int vaccinationDetailsId;
	private int vaccinationId;
	private int vaccinationTypeId;
	private String vaccinationStatus;
	private Integer noReasonId;
	private Date vaccinationDate;
	private Date nextDueDate;
	private String remarks;

	public ClinicalVaccinationsDetailsModel() {
	}

	public ClinicalVaccinationsDetailsModel(int vaccinationDetailsId, int vaccinationId, int vaccinationTypeId) {
		this.vaccinationDetailsId = vaccinationDetailsId;
		this.vaccinationId = vaccinationId;
		this.vaccinationTypeId = vaccinationTypeId;
	}

	public ClinicalVaccinationsDetailsModel(int vaccinationDetailsId, int vaccinationId, int vaccinationTypeId,
			String vaccinationStatus, Integer noReasonId, Date vaccinationDate, Date nextDueDate, String remarks) {
		this.vaccinationDetailsId = vaccinationDetailsId;
		this.vaccinationId = vaccinationId;
		this.vaccinationTypeId = vaccinationTypeId;
		this.vaccinationStatus = vaccinationStatus;
		this.noReasonId = noReasonId;
		this.vaccinationDate = vaccinationDate;
		this.nextDueDate = nextDueDate;
		this.remarks = remarks;
	}

	@Id

	@Column(name = "vaccination_details_id", unique = true, nullable = false)
	public int getVaccinationDetailsId() {
		return this.vaccinationDetailsId;
	}

	public void setVaccinationDetailsId(int vaccinationDetailsId) {
		this.vaccinationDetailsId = vaccinationDetailsId;
	}

	@Column(name = "vaccination_id", nullable = false)
	public int getVaccinationId() {
		return this.vaccinationId;
	}

	public void setVaccinationId(int vaccinationId) {
		this.vaccinationId = vaccinationId;
	}

	@Column(name = "vaccination_type_id", nullable = false)
	public int getVaccinationTypeId() {
		return this.vaccinationTypeId;
	}

	public void setVaccinationTypeId(int vaccinationTypeId) {
		this.vaccinationTypeId = vaccinationTypeId;
	}

	@Column(name = "vaccination_status", length = 1)
	public String getVaccinationStatus() {
		return this.vaccinationStatus;
	}

	public void setVaccinationStatus(String vaccinationStatus) {
		this.vaccinationStatus = vaccinationStatus;
	}

	@Column(name = "no_reason_id")
	public Integer getNoReasonId() {
		return this.noReasonId;
	}

	public void setNoReasonId(Integer noReasonId) {
		this.noReasonId = noReasonId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vaccination_date", length = 13)
	public Date getVaccinationDate() {
		return this.vaccinationDate;
	}

	public void setVaccinationDate(Date vaccinationDate) {
		this.vaccinationDate = vaccinationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "next_due_date", length = 13)
	public Date getNextDueDate() {
		return this.nextDueDate;
	}

	public void setNextDueDate(Date nextDueDate) {
		this.nextDueDate = nextDueDate;
	}

	@Column(name = "remarks", length = 2000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
