package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommonmedicineTimestampModel generated by hbm2java
 */
@Entity
@Table(name = "commonmedicine_timestamp")
public class CommonmedicineTimestampModel implements java.io.Serializable {

	private int medicineTimestamp;

	public CommonmedicineTimestampModel() {
	}

	public CommonmedicineTimestampModel(int medicineTimestamp) {
		this.medicineTimestamp = medicineTimestamp;
	}

	@Id

	@Column(name = "medicine_timestamp", nullable = false)
	public int getMedicineTimestamp() {
		return this.medicineTimestamp;
	}

	public void setMedicineTimestamp(int medicineTimestamp) {
		this.medicineTimestamp = medicineTimestamp;
	}

}
