package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComplaintslogModel generated by hbm2java
 */
@Entity
@Table(name = "complaintslog")
public class ComplaintslogModel implements java.io.Serializable {

	private BigDecimal complaintId;
	private String loggedBy;
	private Date loggedDate;
	private String complaintModule;
	private String complaintSummary;
	private String complaintDesc;
	private String complaintStatus;
	private String updatedBy;
	private String complaintClosureNote;
	private Date updatedDate;
	private String versionNo;
	private String phoneNo;

	public ComplaintslogModel() {
	}

	public ComplaintslogModel(BigDecimal complaintId) {
		this.complaintId = complaintId;
	}

	public ComplaintslogModel(BigDecimal complaintId, String loggedBy, Date loggedDate, String complaintModule,
			String complaintSummary, String complaintDesc, String complaintStatus, String updatedBy,
			String complaintClosureNote, Date updatedDate, String versionNo, String phoneNo) {
		this.complaintId = complaintId;
		this.loggedBy = loggedBy;
		this.loggedDate = loggedDate;
		this.complaintModule = complaintModule;
		this.complaintSummary = complaintSummary;
		this.complaintDesc = complaintDesc;
		this.complaintStatus = complaintStatus;
		this.updatedBy = updatedBy;
		this.complaintClosureNote = complaintClosureNote;
		this.updatedDate = updatedDate;
		this.versionNo = versionNo;
		this.phoneNo = phoneNo;
	}

	@Id

	@Column(name = "complaint_id", unique = true, nullable = false, precision = 131089, scale = 0)
	public BigDecimal getComplaintId() {
		return this.complaintId;
	}

	public void setComplaintId(BigDecimal complaintId) {
		this.complaintId = complaintId;
	}

	@Column(name = "logged_by")
	public String getLoggedBy() {
		return this.loggedBy;
	}

	public void setLoggedBy(String loggedBy) {
		this.loggedBy = loggedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logged_date", length = 29)
	public Date getLoggedDate() {
		return this.loggedDate;
	}

	public void setLoggedDate(Date loggedDate) {
		this.loggedDate = loggedDate;
	}

	@Column(name = "complaint_module")
	public String getComplaintModule() {
		return this.complaintModule;
	}

	public void setComplaintModule(String complaintModule) {
		this.complaintModule = complaintModule;
	}

	@Column(name = "complaint_summary")
	public String getComplaintSummary() {
		return this.complaintSummary;
	}

	public void setComplaintSummary(String complaintSummary) {
		this.complaintSummary = complaintSummary;
	}

	@Column(name = "complaint_desc")
	public String getComplaintDesc() {
		return this.complaintDesc;
	}

	public void setComplaintDesc(String complaintDesc) {
		this.complaintDesc = complaintDesc;
	}

	@Column(name = "complaint_status")
	public String getComplaintStatus() {
		return this.complaintStatus;
	}

	public void setComplaintStatus(String complaintStatus) {
		this.complaintStatus = complaintStatus;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "complaint_closure_note")
	public String getComplaintClosureNote() {
		return this.complaintClosureNote;
	}

	public void setComplaintClosureNote(String complaintClosureNote) {
		this.complaintClosureNote = complaintClosureNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "version_no", length = 20)
	public String getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(String versionNo) {
		this.versionNo = versionNo;
	}

	@Column(name = "phone_no", length = 20)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

}
