package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsultationEmCalculationModel generated by hbm2java
 */
@Entity
@Table(name = "consultation_em_calculation")
public class ConsultationEmCalculationModel implements java.io.Serializable {

	private int consultationId;
	private Character visitType;
	private Integer hpiCount;
	private Integer rosCount;
	private Integer pfshCount;
	private Integer peCount;
	private String problemStatus;
	private Integer treatmentOptionsCount;
	private Integer calculatedTreatmentOptionsCount;
	private Integer dataAmountComplexityCount;
	private Integer riskCount;
	private Integer mdmValue;
	private Integer emCode;
	private Character complexity1;
	private Character complexity2;
	private Character complexity3;
	private Character complexity4;
	private Character complexity5;
	private Character complexity6;
	private Character complexity7;
	private String remarks;
	private Date codeFinalizedDate;
	private String userName;
	private String finalizedUserName;
	private Integer finalizedEmCode;
	private Date modTime;

	public ConsultationEmCalculationModel() {
	}

	public ConsultationEmCalculationModel(int consultationId) {
		this.consultationId = consultationId;
	}

	public ConsultationEmCalculationModel(int consultationId, Character visitType, Integer hpiCount, Integer rosCount,
			Integer pfshCount, Integer peCount, String problemStatus, Integer treatmentOptionsCount,
			Integer calculatedTreatmentOptionsCount, Integer dataAmountComplexityCount, Integer riskCount,
			Integer mdmValue, Integer emCode, Character complexity1, Character complexity2, Character complexity3,
			Character complexity4, Character complexity5, Character complexity6, Character complexity7, String remarks,
			Date codeFinalizedDate, String userName, String finalizedUserName, Integer finalizedEmCode, Date modTime) {
		this.consultationId = consultationId;
		this.visitType = visitType;
		this.hpiCount = hpiCount;
		this.rosCount = rosCount;
		this.pfshCount = pfshCount;
		this.peCount = peCount;
		this.problemStatus = problemStatus;
		this.treatmentOptionsCount = treatmentOptionsCount;
		this.calculatedTreatmentOptionsCount = calculatedTreatmentOptionsCount;
		this.dataAmountComplexityCount = dataAmountComplexityCount;
		this.riskCount = riskCount;
		this.mdmValue = mdmValue;
		this.emCode = emCode;
		this.complexity1 = complexity1;
		this.complexity2 = complexity2;
		this.complexity3 = complexity3;
		this.complexity4 = complexity4;
		this.complexity5 = complexity5;
		this.complexity6 = complexity6;
		this.complexity7 = complexity7;
		this.remarks = remarks;
		this.codeFinalizedDate = codeFinalizedDate;
		this.userName = userName;
		this.finalizedUserName = finalizedUserName;
		this.finalizedEmCode = finalizedEmCode;
		this.modTime = modTime;
	}

	@Id

	@Column(name = "consultation_id", unique = true, nullable = false)
	public int getConsultationId() {
		return this.consultationId;
	}

	public void setConsultationId(int consultationId) {
		this.consultationId = consultationId;
	}

	@Column(name = "visit_type", length = 1)
	public Character getVisitType() {
		return this.visitType;
	}

	public void setVisitType(Character visitType) {
		this.visitType = visitType;
	}

	@Column(name = "hpi_count")
	public Integer getHpiCount() {
		return this.hpiCount;
	}

	public void setHpiCount(Integer hpiCount) {
		this.hpiCount = hpiCount;
	}

	@Column(name = "ros_count")
	public Integer getRosCount() {
		return this.rosCount;
	}

	public void setRosCount(Integer rosCount) {
		this.rosCount = rosCount;
	}

	@Column(name = "pfsh_count")
	public Integer getPfshCount() {
		return this.pfshCount;
	}

	public void setPfshCount(Integer pfshCount) {
		this.pfshCount = pfshCount;
	}

	@Column(name = "pe_count")
	public Integer getPeCount() {
		return this.peCount;
	}

	public void setPeCount(Integer peCount) {
		this.peCount = peCount;
	}

	@Column(name = "problem_status", length = 2)
	public String getProblemStatus() {
		return this.problemStatus;
	}

	public void setProblemStatus(String problemStatus) {
		this.problemStatus = problemStatus;
	}

	@Column(name = "treatment_options_count")
	public Integer getTreatmentOptionsCount() {
		return this.treatmentOptionsCount;
	}

	public void setTreatmentOptionsCount(Integer treatmentOptionsCount) {
		this.treatmentOptionsCount = treatmentOptionsCount;
	}

	@Column(name = "calculated_treatment_options_count")
	public Integer getCalculatedTreatmentOptionsCount() {
		return this.calculatedTreatmentOptionsCount;
	}

	public void setCalculatedTreatmentOptionsCount(Integer calculatedTreatmentOptionsCount) {
		this.calculatedTreatmentOptionsCount = calculatedTreatmentOptionsCount;
	}

	@Column(name = "data_amount_complexity_count")
	public Integer getDataAmountComplexityCount() {
		return this.dataAmountComplexityCount;
	}

	public void setDataAmountComplexityCount(Integer dataAmountComplexityCount) {
		this.dataAmountComplexityCount = dataAmountComplexityCount;
	}

	@Column(name = "risk_count")
	public Integer getRiskCount() {
		return this.riskCount;
	}

	public void setRiskCount(Integer riskCount) {
		this.riskCount = riskCount;
	}

	@Column(name = "mdm_value")
	public Integer getMdmValue() {
		return this.mdmValue;
	}

	public void setMdmValue(Integer mdmValue) {
		this.mdmValue = mdmValue;
	}

	@Column(name = "em_code")
	public Integer getEmCode() {
		return this.emCode;
	}

	public void setEmCode(Integer emCode) {
		this.emCode = emCode;
	}

	@Column(name = "complexity1", length = 1)
	public Character getComplexity1() {
		return this.complexity1;
	}

	public void setComplexity1(Character complexity1) {
		this.complexity1 = complexity1;
	}

	@Column(name = "complexity2", length = 1)
	public Character getComplexity2() {
		return this.complexity2;
	}

	public void setComplexity2(Character complexity2) {
		this.complexity2 = complexity2;
	}

	@Column(name = "complexity3", length = 1)
	public Character getComplexity3() {
		return this.complexity3;
	}

	public void setComplexity3(Character complexity3) {
		this.complexity3 = complexity3;
	}

	@Column(name = "complexity4", length = 1)
	public Character getComplexity4() {
		return this.complexity4;
	}

	public void setComplexity4(Character complexity4) {
		this.complexity4 = complexity4;
	}

	@Column(name = "complexity5", length = 1)
	public Character getComplexity5() {
		return this.complexity5;
	}

	public void setComplexity5(Character complexity5) {
		this.complexity5 = complexity5;
	}

	@Column(name = "complexity6", length = 1)
	public Character getComplexity6() {
		return this.complexity6;
	}

	public void setComplexity6(Character complexity6) {
		this.complexity6 = complexity6;
	}

	@Column(name = "complexity7", length = 1)
	public Character getComplexity7() {
		return this.complexity7;
	}

	public void setComplexity7(Character complexity7) {
		this.complexity7 = complexity7;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "code_finalized_date", length = 29)
	public Date getCodeFinalizedDate() {
		return this.codeFinalizedDate;
	}

	public void setCodeFinalizedDate(Date codeFinalizedDate) {
		this.codeFinalizedDate = codeFinalizedDate;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "finalized_user_name", length = 30)
	public String getFinalizedUserName() {
		return this.finalizedUserName;
	}

	public void setFinalizedUserName(String finalizedUserName) {
		this.finalizedUserName = finalizedUserName;
	}

	@Column(name = "finalized_em_code")
	public Integer getFinalizedEmCode() {
		return this.finalizedEmCode;
	}

	public void setFinalizedEmCode(Integer finalizedEmCode) {
		this.finalizedEmCode = finalizedEmCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

}
