package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ConsultationOrgDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "consultation_org_details")
public class ConsultationOrgDetailsModel implements java.io.Serializable {

	private ConsultationOrgDetailsIdSequence id;

	public ConsultationOrgDetailsModel() {
	}

	public ConsultationOrgDetailsModel(ConsultationOrgDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "consultationTypeId", column = @Column(name = "consultation_type_id", nullable = false)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 10)),
			@AttributeOverride(name = "applicable", column = @Column(name = "applicable", nullable = false)),
			@AttributeOverride(name = "itemCode", column = @Column(name = "item_code", length = 50)),
			@AttributeOverride(name = "codeType", column = @Column(name = "code_type", length = 50)),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 50)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)),
			@AttributeOverride(name = "baseRateSheetId", column = @Column(name = "base_rate_sheet_id", length = 10)),
			@AttributeOverride(name = "isOverride", column = @Column(name = "is_override", length = 1)) })
	public ConsultationOrgDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(ConsultationOrgDetailsIdSequence id) {
		this.id = id;
	}

}
