package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CorporateDocsDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "corporate_docs_details")
public class CorporateDocsDetailsModel implements java.io.Serializable {

	private CorporateDocsDetailsIdSequence id;

	public CorporateDocsDetailsModel() {
	}

	public CorporateDocsDetailsModel(CorporateDocsDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "docId", column = @Column(name = "doc_id")),
			@AttributeOverride(name = "docName", column = @Column(name = "doc_name")),
			@AttributeOverride(name = "docDate", column = @Column(name = "doc_date", length = 13)),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 50)),
			@AttributeOverride(name = "patientCorporateId", column = @Column(name = "patient_corporate_id")) })
	public CorporateDocsDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(CorporateDocsDetailsIdSequence id) {
		this.id = id;
	}

}
