package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CronDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "cron_details")
public class CronDetailsModel implements java.io.Serializable {

	private String cronName;
	private Date lastExecTime;

	public CronDetailsModel() {
	}

	public CronDetailsModel(String cronName) {
		this.cronName = cronName;
	}

	public CronDetailsModel(String cronName, Date lastExecTime) {
		this.cronName = cronName;
		this.lastExecTime = lastExecTime;
	}

	@Id

	@Column(name = "cron_name", unique = true, nullable = false, length = 100)
	public String getCronName() {
		return this.cronName;
	}

	public void setCronName(String cronName) {
		this.cronName = cronName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_exec_time", length = 29)
	public Date getLastExecTime() {
		return this.lastExecTime;
	}

	public void setLastExecTime(Date lastExecTime) {
		this.lastExecTime = lastExecTime;
	}

}
