package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CustomList4MasterModel generated by hbm2java
 */
@Entity
@Table(name = "custom_list4_master")
public class CustomList4MasterModel implements java.io.Serializable {

	private CustomList4MasterIdSequence id;

	public CustomList4MasterModel() {
	}

	public CustomList4MasterModel(CustomList4MasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "customValue", column = @Column(name = "custom_value", length = 50)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)) })
	public CustomList4MasterIdSequence getId() {
		return this.id;
	}

	public void setId(CustomList4MasterIdSequence id) {
		this.id = id;
	}

}
