package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DentalSuppliesOrderModel generated by hbm2java
 */
@Entity
@Table(name = "dental_supplies_order")
public class DentalSuppliesOrderModel implements java.io.Serializable {

	private int suppliesOrderId;
	private String mrNo;
	private char suppliesOrderStatus;
	private Integer supplierId;
	private String orderedBy;
	private Date orderedDate;
	private String remarks;
	private int centerId;
	private Integer treatmentId;
	private Set dentalSuppliesItemses = new HashSet(0);

	public DentalSuppliesOrderModel() {
	}

	public DentalSuppliesOrderModel(int suppliesOrderId, String mrNo, char suppliesOrderStatus, int centerId) {
		this.suppliesOrderId = suppliesOrderId;
		this.mrNo = mrNo;
		this.suppliesOrderStatus = suppliesOrderStatus;
		this.centerId = centerId;
	}

	public DentalSuppliesOrderModel(int suppliesOrderId, String mrNo, char suppliesOrderStatus, Integer supplierId,
			String orderedBy, Date orderedDate, String remarks, int centerId, Integer treatmentId,
			Set dentalSuppliesItemses) {
		this.suppliesOrderId = suppliesOrderId;
		this.mrNo = mrNo;
		this.suppliesOrderStatus = suppliesOrderStatus;
		this.supplierId = supplierId;
		this.orderedBy = orderedBy;
		this.orderedDate = orderedDate;
		this.remarks = remarks;
		this.centerId = centerId;
		this.treatmentId = treatmentId;
		this.dentalSuppliesItemses = dentalSuppliesItemses;
	}

	@Id

	@Column(name = "supplies_order_id", unique = true, nullable = false)
	public int getSuppliesOrderId() {
		return this.suppliesOrderId;
	}

	public void setSuppliesOrderId(int suppliesOrderId) {
		this.suppliesOrderId = suppliesOrderId;
	}

	@Column(name = "mr_no", nullable = false, length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "supplies_order_status", nullable = false, length = 1)
	public char getSuppliesOrderStatus() {
		return this.suppliesOrderStatus;
	}

	public void setSuppliesOrderStatus(char suppliesOrderStatus) {
		this.suppliesOrderStatus = suppliesOrderStatus;
	}

	@Column(name = "supplier_id")
	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "ordered_by", length = 20)
	public String getOrderedBy() {
		return this.orderedBy;
	}

	public void setOrderedBy(String orderedBy) {
		this.orderedBy = orderedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ordered_date", length = 13)
	public Date getOrderedDate() {
		return this.orderedDate;
	}

	public void setOrderedDate(Date orderedDate) {
		this.orderedDate = orderedDate;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "center_id", nullable = false)
	public int getCenterId() {
		return this.centerId;
	}

	public void setCenterId(int centerId) {
		this.centerId = centerId;
	}

	@Column(name = "treatment_id")
	public Integer getTreatmentId() {
		return this.treatmentId;
	}

	public void setTreatmentId(Integer treatmentId) {
		this.treatmentId = treatmentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dentalSuppliesOrder")
	public Set getDentalSuppliesItemses() {
		return this.dentalSuppliesItemses;
	}

	public void setDentalSuppliesItemses(Set dentalSuppliesItemses) {
		this.dentalSuppliesItemses = dentalSuppliesItemses;
	}

}
