package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DiagnosticOuthousePrintTemplateModel generated by hbm2java
 */
@Entity
@Table(name = "diagnostic_outhouse_print_template")
public class DiagnosticOuthousePrintTemplateModel implements java.io.Serializable {

	private DiagnosticOuthousePrintTemplateIdSequence id;

	public DiagnosticOuthousePrintTemplateModel() {
	}

	public DiagnosticOuthousePrintTemplateModel(DiagnosticOuthousePrintTemplateIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", nullable = false, length = 50)),
			@AttributeOverride(name = "diagOuthouseTemplateContent", column = @Column(name = "diag_outhouse_template_content")),
			@AttributeOverride(name = "templateMode", column = @Column(name = "template_mode", length = 1)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 100)),
			@AttributeOverride(name = "reason", column = @Column(name = "reason", length = 500)) })
	public DiagnosticOuthousePrintTemplateIdSequence getId() {
		return this.id;
	}

	public void setId(DiagnosticOuthousePrintTemplateIdSequence id) {
		this.id = id;
	}

}
