package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.item.StoreItemDetailsModel;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DiagnosticsReagentsModel generated by hbm2java
 */
@Entity
@Table(name = "diagnostics_reagents")
public class DiagnosticsReagentsModel implements java.io.Serializable {

	private DiagnosticsReagentsIdSequence id;
	private StoreItemDetailsModel StoreItemDetailsModel;

	public DiagnosticsReagentsModel() {
	}

	public DiagnosticsReagentsModel(DiagnosticsReagentsIdSequence id) {
		this.id = id;
	}

	public DiagnosticsReagentsModel(DiagnosticsReagentsIdSequence id, StoreItemDetailsModel StoreItemDetailsModel) {
		this.id = id;
		this.StoreItemDetailsModel = StoreItemDetailsModel;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "testId", column = @Column(name = "test_id", nullable = false, length = 50)),
			@AttributeOverride(name = "quantityNeeded", column = @Column(name = "quantity_needed", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "reagentId", column = @Column(name = "reagent_id")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "consumptionMethod", column = @Column(name = "consumption_method", length = 1)) })
	public DiagnosticsReagentsIdSequence getId() {
		return this.id;
	}

	public void setId(DiagnosticsReagentsIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reagent_id", insertable = false, updatable = false)
	public StoreItemDetailsModel getStoreItemDetailsModel() {
		return this.StoreItemDetailsModel;
	}

	public void setStoreItemDetailsModel(StoreItemDetailsModel StoreItemDetailsModel) {
		this.StoreItemDetailsModel = StoreItemDetailsModel;
	}

}
