package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiagnosticOuthousePrintTemplateIdSequence generated by hbm2java
 */
@Embeddable
public class DiagnosticOuthousePrintTemplateIdSequence implements java.io.Serializable {

	private String templateName;
	private String diagOuthouseTemplateContent;
	private Character templateMode;
	private String userName;
	private String reason;

	public DiagnosticOuthousePrintTemplateIdSequence() {
	}

	public DiagnosticOuthousePrintTemplateIdSequence(String templateName) {
		this.templateName = templateName;
	}

	public DiagnosticOuthousePrintTemplateIdSequence(String templateName, String diagOuthouseTemplateContent,
			Character templateMode, String userName, String reason) {
		this.templateName = templateName;
		this.diagOuthouseTemplateContent = diagOuthouseTemplateContent;
		this.templateMode = templateMode;
		this.userName = userName;
		this.reason = reason;
	}

	@Column(name = "template_name", nullable = false, length = 50)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "diag_outhouse_template_content")
	public String getDiagOuthouseTemplateContent() {
		return this.diagOuthouseTemplateContent;
	}

	public void setDiagOuthouseTemplateContent(String diagOuthouseTemplateContent) {
		this.diagOuthouseTemplateContent = diagOuthouseTemplateContent;
	}

	@Column(name = "template_mode", length = 1)
	public Character getTemplateMode() {
		return this.templateMode;
	}

	public void setTemplateMode(Character templateMode) {
		this.templateMode = templateMode;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "reason", length = 500)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiagnosticOuthousePrintTemplateIdSequence))
			return false;
		DiagnosticOuthousePrintTemplateIdSequence castOther = (DiagnosticOuthousePrintTemplateIdSequence) other;

		return ((this.getTemplateName() == castOther.getTemplateName()) || (this.getTemplateName() != null
				&& castOther.getTemplateName() != null && this.getTemplateName().equals(castOther.getTemplateName())))
				&& ((this.getDiagOuthouseTemplateContent() == castOther.getDiagOuthouseTemplateContent())
						|| (this.getDiagOuthouseTemplateContent() != null
								&& castOther.getDiagOuthouseTemplateContent() != null
								&& this.getDiagOuthouseTemplateContent()
										.equals(castOther.getDiagOuthouseTemplateContent())))
				&& ((this.getTemplateMode() == castOther.getTemplateMode())
						|| (this.getTemplateMode() != null && castOther.getTemplateMode() != null
								&& this.getTemplateMode().equals(castOther.getTemplateMode())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getReason() == castOther.getReason()) || (this.getReason() != null
						&& castOther.getReason() != null && this.getReason().equals(castOther.getReason())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTemplateName() == null ? 0 : this.getTemplateName().hashCode());
		result = 37 * result
				+ (getDiagOuthouseTemplateContent() == null ? 0 : this.getDiagOuthouseTemplateContent().hashCode());
		result = 37 * result + (getTemplateMode() == null ? 0 : this.getTemplateMode().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getReason() == null ? 0 : this.getReason().hashCode());
		return result;
	}

}
