package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DialysisAccessSitesModel generated by hbm2java
 */
@Entity
@Table(name = "dialysis_access_sites", uniqueConstraints = @UniqueConstraint(columnNames = "access_site"))
public class DialysisAccessSitesModel implements java.io.Serializable {

	private int accessSiteId;
	private String accessSite;
	private String description;
	private Character status;
	private Set dialysisSessions = new HashSet(0);

	public DialysisAccessSitesModel() {
	}

	public DialysisAccessSitesModel(int accessSiteId, String accessSite) {
		this.accessSiteId = accessSiteId;
		this.accessSite = accessSite;
	}

	public DialysisAccessSitesModel(int accessSiteId, String accessSite, String description, Character status,
			Set dialysisSessions) {
		this.accessSiteId = accessSiteId;
		this.accessSite = accessSite;
		this.description = description;
		this.status = status;
		this.dialysisSessions = dialysisSessions;
	}

	@Id

	@Column(name = "access_site_id", unique = true, nullable = false)
	public int getAccessSiteId() {
		return this.accessSiteId;
	}

	public void setAccessSiteId(int accessSiteId) {
		this.accessSiteId = accessSiteId;
	}

	@Column(name = "access_site", unique = true, nullable = false, length = 30)
	public String getAccessSite() {
		return this.accessSite;
	}

	public void setAccessSite(String accessSite) {
		this.accessSite = accessSite;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dialysisAccessSites")
	public Set getDialysisSessions() {
		return this.dialysisSessions;
	}

	public void setDialysisSessions(Set dialysisSessions) {
		this.dialysisSessions = dialysisSessions;
	}

}
