package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DialysisSessionParametersModel generated by hbm2java
 */
@Entity
@Table(name = "dialysis_session_parameters")
public class DialysisSessionParametersModel implements java.io.Serializable {

	private int observationId;
	private DialysisSessionModel DialysisSessionModel;
	private Date obsTime;
	private Character polledStatus;
	private BigDecimal ufGoal;
	private BigDecimal ufRemoved;
	private BigDecimal ufRate;
	private BigDecimal bloodPumpRate;
	private BigDecimal heparinRate;
	private BigDecimal dialysateTemp;
	private BigDecimal dialysateCond;
	private Integer venousPressure;
	private Integer dialysatePressure;
	private Integer tmp;
	private Integer dialysisTime;
	private BigDecimal dialysateRate;
	private Character tmpAlarm;
	private Character airAlarm;
	private Character bloodLeakAlarm;
	private Character otherAlarm;
	private Character treatmentMode;
	private BigDecimal substGoal;
	private BigDecimal substTransitVal;
	private BigDecimal substTemp;
	private Date bpTime;
	private Integer bpHigh;
	private Integer bpLow;
	private Integer pulseRate;
	private Character bpAlarm;
	private Character finalized;
	private String finalizedBy;
	private Date finalizedTime;
	private Character obsType;
	private Character temperatureAlarm;
	private Character conductivityAlarm;
	private Character venousPressureAlarm;
	private Character dialysatePressureAlarm;
	private BigDecimal substRate;
	private Character savedByFlag;

	public DialysisSessionParametersModel() {
	}

	public DialysisSessionParametersModel(int observationId) {
		this.observationId = observationId;
	}

	public DialysisSessionParametersModel(int observationId, DialysisSessionModel DialysisSessionModel, Date obsTime,
			Character polledStatus, BigDecimal ufGoal, BigDecimal ufRemoved, BigDecimal ufRate,
			BigDecimal bloodPumpRate, BigDecimal heparinRate, BigDecimal dialysateTemp, BigDecimal dialysateCond,
			Integer venousPressure, Integer dialysatePressure, Integer tmp, Integer dialysisTime,
			BigDecimal dialysateRate, Character tmpAlarm, Character airAlarm, Character bloodLeakAlarm,
			Character otherAlarm, Character treatmentMode, BigDecimal substGoal, BigDecimal substTransitVal,
			BigDecimal substTemp, Date bpTime, Integer bpHigh, Integer bpLow, Integer pulseRate, Character bpAlarm,
			Character finalized, String finalizedBy, Date finalizedTime, Character obsType, Character temperatureAlarm,
			Character conductivityAlarm, Character venousPressureAlarm, Character dialysatePressureAlarm,
			BigDecimal substRate, Character savedByFlag) {
		this.observationId = observationId;
		this.DialysisSessionModel = DialysisSessionModel;
		this.obsTime = obsTime;
		this.polledStatus = polledStatus;
		this.ufGoal = ufGoal;
		this.ufRemoved = ufRemoved;
		this.ufRate = ufRate;
		this.bloodPumpRate = bloodPumpRate;
		this.heparinRate = heparinRate;
		this.dialysateTemp = dialysateTemp;
		this.dialysateCond = dialysateCond;
		this.venousPressure = venousPressure;
		this.dialysatePressure = dialysatePressure;
		this.tmp = tmp;
		this.dialysisTime = dialysisTime;
		this.dialysateRate = dialysateRate;
		this.tmpAlarm = tmpAlarm;
		this.airAlarm = airAlarm;
		this.bloodLeakAlarm = bloodLeakAlarm;
		this.otherAlarm = otherAlarm;
		this.treatmentMode = treatmentMode;
		this.substGoal = substGoal;
		this.substTransitVal = substTransitVal;
		this.substTemp = substTemp;
		this.bpTime = bpTime;
		this.bpHigh = bpHigh;
		this.bpLow = bpLow;
		this.pulseRate = pulseRate;
		this.bpAlarm = bpAlarm;
		this.finalized = finalized;
		this.finalizedBy = finalizedBy;
		this.finalizedTime = finalizedTime;
		this.obsType = obsType;
		this.temperatureAlarm = temperatureAlarm;
		this.conductivityAlarm = conductivityAlarm;
		this.venousPressureAlarm = venousPressureAlarm;
		this.dialysatePressureAlarm = dialysatePressureAlarm;
		this.substRate = substRate;
		this.savedByFlag = savedByFlag;
	}

	@Id

	@Column(name = "observation_id", unique = true, nullable = false)
	public int getObservationId() {
		return this.observationId;
	}

	public void setObservationId(int observationId) {
		this.observationId = observationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public DialysisSessionModel getDialysisSessionModel() {
		return this.DialysisSessionModel;
	}

	public void setDialysisSessionModel(DialysisSessionModel DialysisSessionModel) {
		this.DialysisSessionModel = DialysisSessionModel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "obs_time", length = 29)
	public Date getObsTime() {
		return this.obsTime;
	}

	public void setObsTime(Date obsTime) {
		this.obsTime = obsTime;
	}

	@Column(name = "polled_status", length = 1)
	public Character getPolledStatus() {
		return this.polledStatus;
	}

	public void setPolledStatus(Character polledStatus) {
		this.polledStatus = polledStatus;
	}

	@Column(name = "uf_goal", precision = 131089, scale = 0)
	public BigDecimal getUfGoal() {
		return this.ufGoal;
	}

	public void setUfGoal(BigDecimal ufGoal) {
		this.ufGoal = ufGoal;
	}

	@Column(name = "uf_removed", precision = 131089, scale = 0)
	public BigDecimal getUfRemoved() {
		return this.ufRemoved;
	}

	public void setUfRemoved(BigDecimal ufRemoved) {
		this.ufRemoved = ufRemoved;
	}

	@Column(name = "uf_rate", precision = 131089, scale = 0)
	public BigDecimal getUfRate() {
		return this.ufRate;
	}

	public void setUfRate(BigDecimal ufRate) {
		this.ufRate = ufRate;
	}

	@Column(name = "blood_pump_rate", precision = 131089, scale = 0)
	public BigDecimal getBloodPumpRate() {
		return this.bloodPumpRate;
	}

	public void setBloodPumpRate(BigDecimal bloodPumpRate) {
		this.bloodPumpRate = bloodPumpRate;
	}

	@Column(name = "heparin_rate", precision = 131089, scale = 0)
	public BigDecimal getHeparinRate() {
		return this.heparinRate;
	}

	public void setHeparinRate(BigDecimal heparinRate) {
		this.heparinRate = heparinRate;
	}

	@Column(name = "dialysate_temp", precision = 131089, scale = 0)
	public BigDecimal getDialysateTemp() {
		return this.dialysateTemp;
	}

	public void setDialysateTemp(BigDecimal dialysateTemp) {
		this.dialysateTemp = dialysateTemp;
	}

	@Column(name = "dialysate_cond", precision = 131089, scale = 0)
	public BigDecimal getDialysateCond() {
		return this.dialysateCond;
	}

	public void setDialysateCond(BigDecimal dialysateCond) {
		this.dialysateCond = dialysateCond;
	}

	@Column(name = "venous_pressure")
	public Integer getVenousPressure() {
		return this.venousPressure;
	}

	public void setVenousPressure(Integer venousPressure) {
		this.venousPressure = venousPressure;
	}

	@Column(name = "dialysate_pressure")
	public Integer getDialysatePressure() {
		return this.dialysatePressure;
	}

	public void setDialysatePressure(Integer dialysatePressure) {
		this.dialysatePressure = dialysatePressure;
	}

	@Column(name = "tmp")
	public Integer getTmp() {
		return this.tmp;
	}

	public void setTmp(Integer tmp) {
		this.tmp = tmp;
	}

	@Column(name = "dialysis_time")
	public Integer getDialysisTime() {
		return this.dialysisTime;
	}

	public void setDialysisTime(Integer dialysisTime) {
		this.dialysisTime = dialysisTime;
	}

	@Column(name = "dialysate_rate", precision = 131089, scale = 0)
	public BigDecimal getDialysateRate() {
		return this.dialysateRate;
	}

	public void setDialysateRate(BigDecimal dialysateRate) {
		this.dialysateRate = dialysateRate;
	}

	@Column(name = "tmp_alarm", length = 1)
	public Character getTmpAlarm() {
		return this.tmpAlarm;
	}

	public void setTmpAlarm(Character tmpAlarm) {
		this.tmpAlarm = tmpAlarm;
	}

	@Column(name = "air_alarm", length = 1)
	public Character getAirAlarm() {
		return this.airAlarm;
	}

	public void setAirAlarm(Character airAlarm) {
		this.airAlarm = airAlarm;
	}

	@Column(name = "blood_leak_alarm", length = 1)
	public Character getBloodLeakAlarm() {
		return this.bloodLeakAlarm;
	}

	public void setBloodLeakAlarm(Character bloodLeakAlarm) {
		this.bloodLeakAlarm = bloodLeakAlarm;
	}

	@Column(name = "other_alarm", length = 1)
	public Character getOtherAlarm() {
		return this.otherAlarm;
	}

	public void setOtherAlarm(Character otherAlarm) {
		this.otherAlarm = otherAlarm;
	}

	@Column(name = "treatment_mode", length = 1)
	public Character getTreatmentMode() {
		return this.treatmentMode;
	}

	public void setTreatmentMode(Character treatmentMode) {
		this.treatmentMode = treatmentMode;
	}

	@Column(name = "subst_goal", precision = 131089, scale = 0)
	public BigDecimal getSubstGoal() {
		return this.substGoal;
	}

	public void setSubstGoal(BigDecimal substGoal) {
		this.substGoal = substGoal;
	}

	@Column(name = "subst_transit_val", precision = 131089, scale = 0)
	public BigDecimal getSubstTransitVal() {
		return this.substTransitVal;
	}

	public void setSubstTransitVal(BigDecimal substTransitVal) {
		this.substTransitVal = substTransitVal;
	}

	@Column(name = "subst_temp", precision = 131089, scale = 0)
	public BigDecimal getSubstTemp() {
		return this.substTemp;
	}

	public void setSubstTemp(BigDecimal substTemp) {
		this.substTemp = substTemp;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "bp_time", length = 15)
	public Date getBpTime() {
		return this.bpTime;
	}

	public void setBpTime(Date bpTime) {
		this.bpTime = bpTime;
	}

	@Column(name = "bp_high")
	public Integer getBpHigh() {
		return this.bpHigh;
	}

	public void setBpHigh(Integer bpHigh) {
		this.bpHigh = bpHigh;
	}

	@Column(name = "bp_low")
	public Integer getBpLow() {
		return this.bpLow;
	}

	public void setBpLow(Integer bpLow) {
		this.bpLow = bpLow;
	}

	@Column(name = "pulse_rate")
	public Integer getPulseRate() {
		return this.pulseRate;
	}

	public void setPulseRate(Integer pulseRate) {
		this.pulseRate = pulseRate;
	}

	@Column(name = "bp_alarm", length = 1)
	public Character getBpAlarm() {
		return this.bpAlarm;
	}

	public void setBpAlarm(Character bpAlarm) {
		this.bpAlarm = bpAlarm;
	}

	@Column(name = "finalized", length = 1)
	public Character getFinalized() {
		return this.finalized;
	}

	public void setFinalized(Character finalized) {
		this.finalized = finalized;
	}

	@Column(name = "finalized_by", length = 30)
	public String getFinalizedBy() {
		return this.finalizedBy;
	}

	public void setFinalizedBy(String finalizedBy) {
		this.finalizedBy = finalizedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finalized_time", length = 29)
	public Date getFinalizedTime() {
		return this.finalizedTime;
	}

	public void setFinalizedTime(Date finalizedTime) {
		this.finalizedTime = finalizedTime;
	}

	@Column(name = "obs_type", length = 1)
	public Character getObsType() {
		return this.obsType;
	}

	public void setObsType(Character obsType) {
		this.obsType = obsType;
	}

	@Column(name = "temperature_alarm", length = 1)
	public Character getTemperatureAlarm() {
		return this.temperatureAlarm;
	}

	public void setTemperatureAlarm(Character temperatureAlarm) {
		this.temperatureAlarm = temperatureAlarm;
	}

	@Column(name = "conductivity_alarm", length = 1)
	public Character getConductivityAlarm() {
		return this.conductivityAlarm;
	}

	public void setConductivityAlarm(Character conductivityAlarm) {
		this.conductivityAlarm = conductivityAlarm;
	}

	@Column(name = "venous_pressure_alarm", length = 1)
	public Character getVenousPressureAlarm() {
		return this.venousPressureAlarm;
	}

	public void setVenousPressureAlarm(Character venousPressureAlarm) {
		this.venousPressureAlarm = venousPressureAlarm;
	}

	@Column(name = "dialysate_pressure_alarm", length = 1)
	public Character getDialysatePressureAlarm() {
		return this.dialysatePressureAlarm;
	}

	public void setDialysatePressureAlarm(Character dialysatePressureAlarm) {
		this.dialysatePressureAlarm = dialysatePressureAlarm;
	}

	@Column(name = "subst_rate", precision = 131089, scale = 0)
	public BigDecimal getSubstRate() {
		return this.substRate;
	}

	public void setSubstRate(BigDecimal substRate) {
		this.substRate = substRate;
	}

	@Column(name = "saved_by_flag", length = 1)
	public Character getSavedByFlag() {
		return this.savedByFlag;
	}

	public void setSavedByFlag(Character savedByFlag) {
		this.savedByFlag = savedByFlag;
	}

}
