package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DialysisSessionNotesIdSequence generated by hbm2java
 */
@Embeddable
public class DialysisSessionNotesIdSequence implements java.io.Serializable {

	private int sessionNotesId;
	private int orderId;
	private Date sessionTime;
	private String username;
	private String plan;
	private String intervention;
	private String evaluation;

	public DialysisSessionNotesIdSequence() {
	}

	public DialysisSessionNotesIdSequence(int sessionNotesId, int orderId) {
		this.sessionNotesId = sessionNotesId;
		this.orderId = orderId;
	}

	public DialysisSessionNotesIdSequence(int sessionNotesId, int orderId, Date sessionTime, String username, String plan,
			String intervention, String evaluation) {
		this.sessionNotesId = sessionNotesId;
		this.orderId = orderId;
		this.sessionTime = sessionTime;
		this.username = username;
		this.plan = plan;
		this.intervention = intervention;
		this.evaluation = evaluation;
	}

	@Column(name = "session_notes_id", nullable = false)
	public int getSessionNotesId() {
		return this.sessionNotesId;
	}

	public void setSessionNotesId(int sessionNotesId) {
		this.sessionNotesId = sessionNotesId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "session_time", length = 15)
	public Date getSessionTime() {
		return this.sessionTime;
	}

	public void setSessionTime(Date sessionTime) {
		this.sessionTime = sessionTime;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "plan")
	public String getPlan() {
		return this.plan;
	}

	public void setPlan(String plan) {
		this.plan = plan;
	}

	@Column(name = "intervention")
	public String getIntervention() {
		return this.intervention;
	}

	public void setIntervention(String intervention) {
		this.intervention = intervention;
	}

	@Column(name = "evaluation")
	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DialysisSessionNotesIdSequence))
			return false;
		DialysisSessionNotesIdSequence castOther = (DialysisSessionNotesIdSequence) other;

		return (this.getSessionNotesId() == castOther.getSessionNotesId())
				&& (this.getOrderId() == castOther.getOrderId())
				&& ((this.getSessionTime() == castOther.getSessionTime())
						|| (this.getSessionTime() != null && castOther.getSessionTime() != null
								&& this.getSessionTime().equals(castOther.getSessionTime())))
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getPlan() == castOther.getPlan()) || (this.getPlan() != null && castOther.getPlan() != null
						&& this.getPlan().equals(castOther.getPlan())))
				&& ((this.getIntervention() == castOther.getIntervention())
						|| (this.getIntervention() != null && castOther.getIntervention() != null
								&& this.getIntervention().equals(castOther.getIntervention())))
				&& ((this.getEvaluation() == castOther.getEvaluation())
						|| (this.getEvaluation() != null && castOther.getEvaluation() != null
								&& this.getEvaluation().equals(castOther.getEvaluation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSessionNotesId();
		result = 37 * result + this.getOrderId();
		result = 37 * result + (getSessionTime() == null ? 0 : this.getSessionTime().hashCode());
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getPlan() == null ? 0 : this.getPlan().hashCode());
		result = 37 * result + (getIntervention() == null ? 0 : this.getIntervention().hashCode());
		result = 37 * result + (getEvaluation() == null ? 0 : this.getEvaluation().hashCode());
		return result;
	}

}
