package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DialysisPatientDrugsModel generated by hbm2java
 */
@Entity
@Table(name = "dialysis_patient_drugs")
public class DialysisPatientDrugsModel implements java.io.Serializable {

	private int dialysisPatientDrugId;
	private Integer orderId;
	private String medicineName;
	private Date dateTime;
	private String batchNo;
	private Character administered;
	private Date expiryDate;
	private String routeOfAdministration;
	private String administeredBy;
	private String doctor;

	public DialysisPatientDrugsModel() {
	}

	public DialysisPatientDrugsModel(int dialysisPatientDrugId) {
		this.dialysisPatientDrugId = dialysisPatientDrugId;
	}

	public DialysisPatientDrugsModel(int dialysisPatientDrugId, Integer orderId, String medicineName, Date dateTime,
			String batchNo, Character administered, Date expiryDate, String routeOfAdministration,
			String administeredBy, String doctor) {
		this.dialysisPatientDrugId = dialysisPatientDrugId;
		this.orderId = orderId;
		this.medicineName = medicineName;
		this.dateTime = dateTime;
		this.batchNo = batchNo;
		this.administered = administered;
		this.expiryDate = expiryDate;
		this.routeOfAdministration = routeOfAdministration;
		this.administeredBy = administeredBy;
		this.doctor = doctor;
	}

	@Id

	@Column(name = "dialysis_patient_drug_id", unique = true, nullable = false)
	public int getDialysisPatientDrugId() {
		return this.dialysisPatientDrugId;
	}

	public void setDialysisPatientDrugId(int dialysisPatientDrugId) {
		this.dialysisPatientDrugId = dialysisPatientDrugId;
	}

	@Column(name = "order_id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "medicine_name")
	public String getMedicineName() {
		return this.medicineName;
	}

	public void setMedicineName(String medicineName) {
		this.medicineName = medicineName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", length = 29)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "batch_no", length = 50)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "administered", length = 1)
	public Character getAdministered() {
		return this.administered;
	}

	public void setAdministered(Character administered) {
		this.administered = administered;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiry_date", length = 13)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "route_of_administration")
	public String getRouteOfAdministration() {
		return this.routeOfAdministration;
	}

	public void setRouteOfAdministration(String routeOfAdministration) {
		this.routeOfAdministration = routeOfAdministration;
	}

	@Column(name = "administered_by")
	public String getAdministeredBy() {
		return this.administeredBy;
	}

	public void setAdministeredBy(String administeredBy) {
		this.administeredBy = administeredBy;
	}

	@Column(name = "doctor")
	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

}
