package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DialysisPrescriptionsModel generated by hbm2java
 */
@Entity
@Table(name = "dialysis_prescriptions")
public class DialysisPrescriptionsModel implements java.io.Serializable {

	private int dialysisPrescId;
	private String mrNo;
	private String prescDoctor;
	private Date prescDate;
	private String diagnosis;
	private Date startDate;
	private Character status;
	private Date endDate;
	private BigDecimal targetWeight;
	private Integer dialysateTypeId;
	private BigDecimal dialysateTemp;
	private Integer dialyzerTypeId;
	private BigDecimal potassium;
	private BigDecimal calcium;
	private BigDecimal magnesium;
	private BigDecimal glucose;
	private BigDecimal targetBvp;
	private Integer accessTypeId;
	private Integer accessSiteId;
	private BigDecimal dialysateFlow;
	private String dialysateFlowProfile;
	private BigDecimal bloodFlow;
	private String bloodFlowProfile;
	private BigDecimal bicarb;
	private String bicarbProfile;
	private BigDecimal sodium;
	private String sodiumProfile;
	private String ufrProfile;
	private BigDecimal heparinBolus;
	private Integer heparinHourly;
	private Integer heparinCutoff;
	private String heparinProfile;
	private String comments;
	private String username;
	private Date modTime;
	private String deactivatedBy;
	private Date deactivatedTime;
	private BigDecimal ufRate;
	private Integer day1;
	private Integer shift1;
	private Integer day2;
	private Integer shift2;
	private Integer day3;
	private Integer shift3;
	private String notes;
	private Integer day4;
	private Integer shift4;
	private Integer day5;
	private Integer shift5;
	private Integer duration;
	private Date dryWtDate;
	private Integer weeklyFrequency;
	private Character dialysisMembrane;
	private Character heparinType;
	private BigDecimal lowHeparinInitialDose;
	private BigDecimal lowHeparinIntrimDose;

	public DialysisPrescriptionsModel() {
	}

	public DialysisPrescriptionsModel(int dialysisPrescId) {
		this.dialysisPrescId = dialysisPrescId;
	}

	public DialysisPrescriptionsModel(int dialysisPrescId, String mrNo, String prescDoctor, Date prescDate, String diagnosis,
			Date startDate, Character status, Date endDate, BigDecimal targetWeight, Integer dialysateTypeId,
			BigDecimal dialysateTemp, Integer dialyzerTypeId, BigDecimal potassium, BigDecimal calcium,
			BigDecimal magnesium, BigDecimal glucose, BigDecimal targetBvp, Integer accessTypeId, Integer accessSiteId,
			BigDecimal dialysateFlow, String dialysateFlowProfile, BigDecimal bloodFlow, String bloodFlowProfile,
			BigDecimal bicarb, String bicarbProfile, BigDecimal sodium, String sodiumProfile, String ufrProfile,
			BigDecimal heparinBolus, Integer heparinHourly, Integer heparinCutoff, String heparinProfile,
			String comments, String username, Date modTime, String deactivatedBy, Date deactivatedTime,
			BigDecimal ufRate, Integer day1, Integer shift1, Integer day2, Integer shift2, Integer day3, Integer shift3,
			String notes, Integer day4, Integer shift4, Integer day5, Integer shift5, Integer duration, Date dryWtDate,
			Integer weeklyFrequency, Character dialysisMembrane, Character heparinType,
			BigDecimal lowHeparinInitialDose, BigDecimal lowHeparinIntrimDose) {
		this.dialysisPrescId = dialysisPrescId;
		this.mrNo = mrNo;
		this.prescDoctor = prescDoctor;
		this.prescDate = prescDate;
		this.diagnosis = diagnosis;
		this.startDate = startDate;
		this.status = status;
		this.endDate = endDate;
		this.targetWeight = targetWeight;
		this.dialysateTypeId = dialysateTypeId;
		this.dialysateTemp = dialysateTemp;
		this.dialyzerTypeId = dialyzerTypeId;
		this.potassium = potassium;
		this.calcium = calcium;
		this.magnesium = magnesium;
		this.glucose = glucose;
		this.targetBvp = targetBvp;
		this.accessTypeId = accessTypeId;
		this.accessSiteId = accessSiteId;
		this.dialysateFlow = dialysateFlow;
		this.dialysateFlowProfile = dialysateFlowProfile;
		this.bloodFlow = bloodFlow;
		this.bloodFlowProfile = bloodFlowProfile;
		this.bicarb = bicarb;
		this.bicarbProfile = bicarbProfile;
		this.sodium = sodium;
		this.sodiumProfile = sodiumProfile;
		this.ufrProfile = ufrProfile;
		this.heparinBolus = heparinBolus;
		this.heparinHourly = heparinHourly;
		this.heparinCutoff = heparinCutoff;
		this.heparinProfile = heparinProfile;
		this.comments = comments;
		this.username = username;
		this.modTime = modTime;
		this.deactivatedBy = deactivatedBy;
		this.deactivatedTime = deactivatedTime;
		this.ufRate = ufRate;
		this.day1 = day1;
		this.shift1 = shift1;
		this.day2 = day2;
		this.shift2 = shift2;
		this.day3 = day3;
		this.shift3 = shift3;
		this.notes = notes;
		this.day4 = day4;
		this.shift4 = shift4;
		this.day5 = day5;
		this.shift5 = shift5;
		this.duration = duration;
		this.dryWtDate = dryWtDate;
		this.weeklyFrequency = weeklyFrequency;
		this.dialysisMembrane = dialysisMembrane;
		this.heparinType = heparinType;
		this.lowHeparinInitialDose = lowHeparinInitialDose;
		this.lowHeparinIntrimDose = lowHeparinIntrimDose;
	}

	@Id

	@Column(name = "dialysis_presc_id", unique = true, nullable = false)
	public int getDialysisPrescId() {
		return this.dialysisPrescId;
	}

	public void setDialysisPrescId(int dialysisPrescId) {
		this.dialysisPrescId = dialysisPrescId;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "presc_doctor", length = 20)
	public String getPrescDoctor() {
		return this.prescDoctor;
	}

	public void setPrescDoctor(String prescDoctor) {
		this.prescDoctor = prescDoctor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "presc_date", length = 13)
	public Date getPrescDate() {
		return this.prescDate;
	}

	public void setPrescDate(Date prescDate) {
		this.prescDate = prescDate;
	}

	@Column(name = "diagnosis", length = 100)
	public String getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(String diagnosis) {
		this.diagnosis = diagnosis;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 13)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 13)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "target_weight", precision = 6)
	public BigDecimal getTargetWeight() {
		return this.targetWeight;
	}

	public void setTargetWeight(BigDecimal targetWeight) {
		this.targetWeight = targetWeight;
	}

	@Column(name = "dialysate_type_id")
	public Integer getDialysateTypeId() {
		return this.dialysateTypeId;
	}

	public void setDialysateTypeId(Integer dialysateTypeId) {
		this.dialysateTypeId = dialysateTypeId;
	}

	@Column(name = "dialysate_temp", precision = 131089, scale = 0)
	public BigDecimal getDialysateTemp() {
		return this.dialysateTemp;
	}

	public void setDialysateTemp(BigDecimal dialysateTemp) {
		this.dialysateTemp = dialysateTemp;
	}

	@Column(name = "dialyzer_type_id")
	public Integer getDialyzerTypeId() {
		return this.dialyzerTypeId;
	}

	public void setDialyzerTypeId(Integer dialyzerTypeId) {
		this.dialyzerTypeId = dialyzerTypeId;
	}

	@Column(name = "potassium", precision = 131089, scale = 0)
	public BigDecimal getPotassium() {
		return this.potassium;
	}

	public void setPotassium(BigDecimal potassium) {
		this.potassium = potassium;
	}

	@Column(name = "calcium", precision = 131089, scale = 0)
	public BigDecimal getCalcium() {
		return this.calcium;
	}

	public void setCalcium(BigDecimal calcium) {
		this.calcium = calcium;
	}

	@Column(name = "magnesium", precision = 131089, scale = 0)
	public BigDecimal getMagnesium() {
		return this.magnesium;
	}

	public void setMagnesium(BigDecimal magnesium) {
		this.magnesium = magnesium;
	}

	@Column(name = "glucose", precision = 131089, scale = 0)
	public BigDecimal getGlucose() {
		return this.glucose;
	}

	public void setGlucose(BigDecimal glucose) {
		this.glucose = glucose;
	}

	@Column(name = "target_bvp", precision = 131089, scale = 0)
	public BigDecimal getTargetBvp() {
		return this.targetBvp;
	}

	public void setTargetBvp(BigDecimal targetBvp) {
		this.targetBvp = targetBvp;
	}

	@Column(name = "access_type_id")
	public Integer getAccessTypeId() {
		return this.accessTypeId;
	}

	public void setAccessTypeId(Integer accessTypeId) {
		this.accessTypeId = accessTypeId;
	}

	@Column(name = "access_site_id")
	public Integer getAccessSiteId() {
		return this.accessSiteId;
	}

	public void setAccessSiteId(Integer accessSiteId) {
		this.accessSiteId = accessSiteId;
	}

	@Column(name = "dialysate_flow", precision = 131089, scale = 0)
	public BigDecimal getDialysateFlow() {
		return this.dialysateFlow;
	}

	public void setDialysateFlow(BigDecimal dialysateFlow) {
		this.dialysateFlow = dialysateFlow;
	}

	@Column(name = "dialysate_flow_profile", length = 100)
	public String getDialysateFlowProfile() {
		return this.dialysateFlowProfile;
	}

	public void setDialysateFlowProfile(String dialysateFlowProfile) {
		this.dialysateFlowProfile = dialysateFlowProfile;
	}

	@Column(name = "blood_flow", precision = 131089, scale = 0)
	public BigDecimal getBloodFlow() {
		return this.bloodFlow;
	}

	public void setBloodFlow(BigDecimal bloodFlow) {
		this.bloodFlow = bloodFlow;
	}

	@Column(name = "blood_flow_profile", length = 100)
	public String getBloodFlowProfile() {
		return this.bloodFlowProfile;
	}

	public void setBloodFlowProfile(String bloodFlowProfile) {
		this.bloodFlowProfile = bloodFlowProfile;
	}

	@Column(name = "bicarb", precision = 131089, scale = 0)
	public BigDecimal getBicarb() {
		return this.bicarb;
	}

	public void setBicarb(BigDecimal bicarb) {
		this.bicarb = bicarb;
	}

	@Column(name = "bicarb_profile", length = 100)
	public String getBicarbProfile() {
		return this.bicarbProfile;
	}

	public void setBicarbProfile(String bicarbProfile) {
		this.bicarbProfile = bicarbProfile;
	}

	@Column(name = "sodium", precision = 131089, scale = 0)
	public BigDecimal getSodium() {
		return this.sodium;
	}

	public void setSodium(BigDecimal sodium) {
		this.sodium = sodium;
	}

	@Column(name = "sodium_profile", length = 100)
	public String getSodiumProfile() {
		return this.sodiumProfile;
	}

	public void setSodiumProfile(String sodiumProfile) {
		this.sodiumProfile = sodiumProfile;
	}

	@Column(name = "ufr_profile", length = 100)
	public String getUfrProfile() {
		return this.ufrProfile;
	}

	public void setUfrProfile(String ufrProfile) {
		this.ufrProfile = ufrProfile;
	}

	@Column(name = "heparin_bolus", precision = 10)
	public BigDecimal getHeparinBolus() {
		return this.heparinBolus;
	}

	public void setHeparinBolus(BigDecimal heparinBolus) {
		this.heparinBolus = heparinBolus;
	}

	@Column(name = "heparin_hourly")
	public Integer getHeparinHourly() {
		return this.heparinHourly;
	}

	public void setHeparinHourly(Integer heparinHourly) {
		this.heparinHourly = heparinHourly;
	}

	@Column(name = "heparin_cutoff")
	public Integer getHeparinCutoff() {
		return this.heparinCutoff;
	}

	public void setHeparinCutoff(Integer heparinCutoff) {
		this.heparinCutoff = heparinCutoff;
	}

	@Column(name = "heparin_profile", length = 100)
	public String getHeparinProfile() {
		return this.heparinProfile;
	}

	public void setHeparinProfile(String heparinProfile) {
		this.heparinProfile = heparinProfile;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "deactivated_by", length = 30)
	public String getDeactivatedBy() {
		return this.deactivatedBy;
	}

	public void setDeactivatedBy(String deactivatedBy) {
		this.deactivatedBy = deactivatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deactivated_time", length = 29)
	public Date getDeactivatedTime() {
		return this.deactivatedTime;
	}

	public void setDeactivatedTime(Date deactivatedTime) {
		this.deactivatedTime = deactivatedTime;
	}

	@Column(name = "uf_rate", precision = 131089, scale = 0)
	public BigDecimal getUfRate() {
		return this.ufRate;
	}

	public void setUfRate(BigDecimal ufRate) {
		this.ufRate = ufRate;
	}

	@Column(name = "day1")
	public Integer getDay1() {
		return this.day1;
	}

	public void setDay1(Integer day1) {
		this.day1 = day1;
	}

	@Column(name = "shift1")
	public Integer getShift1() {
		return this.shift1;
	}

	public void setShift1(Integer shift1) {
		this.shift1 = shift1;
	}

	@Column(name = "day2")
	public Integer getDay2() {
		return this.day2;
	}

	public void setDay2(Integer day2) {
		this.day2 = day2;
	}

	@Column(name = "shift2")
	public Integer getShift2() {
		return this.shift2;
	}

	public void setShift2(Integer shift2) {
		this.shift2 = shift2;
	}

	@Column(name = "day3")
	public Integer getDay3() {
		return this.day3;
	}

	public void setDay3(Integer day3) {
		this.day3 = day3;
	}

	@Column(name = "shift3")
	public Integer getShift3() {
		return this.shift3;
	}

	public void setShift3(Integer shift3) {
		this.shift3 = shift3;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "day4")
	public Integer getDay4() {
		return this.day4;
	}

	public void setDay4(Integer day4) {
		this.day4 = day4;
	}

	@Column(name = "shift4")
	public Integer getShift4() {
		return this.shift4;
	}

	public void setShift4(Integer shift4) {
		this.shift4 = shift4;
	}

	@Column(name = "day5")
	public Integer getDay5() {
		return this.day5;
	}

	public void setDay5(Integer day5) {
		this.day5 = day5;
	}

	@Column(name = "shift5")
	public Integer getShift5() {
		return this.shift5;
	}

	public void setShift5(Integer shift5) {
		this.shift5 = shift5;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dry_wt_date", length = 13)
	public Date getDryWtDate() {
		return this.dryWtDate;
	}

	public void setDryWtDate(Date dryWtDate) {
		this.dryWtDate = dryWtDate;
	}

	@Column(name = "weekly_frequency")
	public Integer getWeeklyFrequency() {
		return this.weeklyFrequency;
	}

	public void setWeeklyFrequency(Integer weeklyFrequency) {
		this.weeklyFrequency = weeklyFrequency;
	}

	@Column(name = "dialysis_membrane", length = 1)
	public Character getDialysisMembrane() {
		return this.dialysisMembrane;
	}

	public void setDialysisMembrane(Character dialysisMembrane) {
		this.dialysisMembrane = dialysisMembrane;
	}

	@Column(name = "heparin_type", length = 1)
	public Character getHeparinType() {
		return this.heparinType;
	}

	public void setHeparinType(Character heparinType) {
		this.heparinType = heparinType;
	}

	@Column(name = "low_heparin_initial_dose", precision = 10)
	public BigDecimal getLowHeparinInitialDose() {
		return this.lowHeparinInitialDose;
	}

	public void setLowHeparinInitialDose(BigDecimal lowHeparinInitialDose) {
		this.lowHeparinInitialDose = lowHeparinInitialDose;
	}

	@Column(name = "low_heparin_intrim_dose", precision = 10)
	public BigDecimal getLowHeparinIntrimDose() {
		return this.lowHeparinIntrimDose;
	}

	public void setLowHeparinIntrimDose(BigDecimal lowHeparinIntrimDose) {
		this.lowHeparinIntrimDose = lowHeparinIntrimDose;
	}

}
