package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiscountCategoryMasterIdSequence generated by hbm2java
 */
@Embeddable
public class DiscountCategoryMasterIdSequence implements java.io.Serializable {

	private int discountCatId;
	private String discountCatName;
	private Integer discountCatPerc;
	private String status;

	public DiscountCategoryMasterIdSequence() {
	}

	public DiscountCategoryMasterIdSequence(int discountCatId) {
		this.discountCatId = discountCatId;
	}

	public DiscountCategoryMasterIdSequence(int discountCatId, String discountCatName, Integer discountCatPerc, String status) {
		this.discountCatId = discountCatId;
		this.discountCatName = discountCatName;
		this.discountCatPerc = discountCatPerc;
		this.status = status;
	}

	@Column(name = "discount_cat_id", nullable = false)
	public int getDiscountCatId() {
		return this.discountCatId;
	}

	public void setDiscountCatId(int discountCatId) {
		this.discountCatId = discountCatId;
	}

	@Column(name = "discount_cat_name", length = 100)
	public String getDiscountCatName() {
		return this.discountCatName;
	}

	public void setDiscountCatName(String discountCatName) {
		this.discountCatName = discountCatName;
	}

	@Column(name = "discount_cat_perc")
	public Integer getDiscountCatPerc() {
		return this.discountCatPerc;
	}

	public void setDiscountCatPerc(Integer discountCatPerc) {
		this.discountCatPerc = discountCatPerc;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiscountCategoryMasterIdSequence))
			return false;
		DiscountCategoryMasterIdSequence castOther = (DiscountCategoryMasterIdSequence) other;

		return (this.getDiscountCatId() == castOther.getDiscountCatId())
				&& ((this.getDiscountCatName() == castOther.getDiscountCatName())
						|| (this.getDiscountCatName() != null && castOther.getDiscountCatName() != null
								&& this.getDiscountCatName().equals(castOther.getDiscountCatName())))
				&& ((this.getDiscountCatPerc() == castOther.getDiscountCatPerc())
						|| (this.getDiscountCatPerc() != null && castOther.getDiscountCatPerc() != null
								&& this.getDiscountCatPerc().equals(castOther.getDiscountCatPerc())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDiscountCatId();
		result = 37 * result + (getDiscountCatName() == null ? 0 : this.getDiscountCatName().hashCode());
		result = 37 * result + (getDiscountCatPerc() == null ? 0 : this.getDiscountCatPerc().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
