package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.discountplans.DiscountPlanMainModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DiscountPlanCenterMasterModel generated by hbm2java
 */
@Entity
@Table(name = "discount_plan_center_master")
public class DiscountPlanCenterMasterModel implements java.io.Serializable {

	private int discountPlanCenterId;
	private DiscountPlanMainModel DiscountPlanMainModel;
	private Integer centerId;
	private Character status;

	public DiscountPlanCenterMasterModel() {
	}

	public DiscountPlanCenterMasterModel(int discountPlanCenterId, DiscountPlanMainModel DiscountPlanMainModel) {
		this.discountPlanCenterId = discountPlanCenterId;
		this.DiscountPlanMainModel = DiscountPlanMainModel;
	}

	public DiscountPlanCenterMasterModel(int discountPlanCenterId, DiscountPlanMainModel DiscountPlanMainModel, Integer centerId,
			Character status) {
		this.discountPlanCenterId = discountPlanCenterId;
		this.DiscountPlanMainModel = DiscountPlanMainModel;
		this.centerId = centerId;
		this.status = status;
	}

	@Id

	@Column(name = "discount_plan_center_id", unique = true, nullable = false)
	public int getDiscountPlanCenterId() {
		return this.discountPlanCenterId;
	}

	public void setDiscountPlanCenterId(int discountPlanCenterId) {
		this.discountPlanCenterId = discountPlanCenterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discount_plan_id", nullable = false)
	public DiscountPlanMainModel getDiscountPlanMainModel() {
		return this.DiscountPlanMainModel;
	}

	public void setDiscountPlanMainModel(DiscountPlanMainModel DiscountPlanMainModel) {
		this.DiscountPlanMainModel = DiscountPlanMainModel;
	}

	@Column(name = "center_id")
	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

}
