package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DischargeFileuploadModel generated by hbm2java
 */
@Entity
@Table(name = "discharge_fileupload")
public class DischargeFileuploadModel implements java.io.Serializable {

	private int docid;
	private String patientId;
	private byte[] imagefile;
	private String contenttype;
	private String contentfilename;
	private String originalExtension;

	public DischargeFileuploadModel() {
	}

	public DischargeFileuploadModel(int docid, String originalExtension) {
		this.docid = docid;
		this.originalExtension = originalExtension;
	}

	public DischargeFileuploadModel(int docid, String patientId, byte[] imagefile, String contenttype,
			String contentfilename, String originalExtension) {
		this.docid = docid;
		this.patientId = patientId;
		this.imagefile = imagefile;
		this.contenttype = contenttype;
		this.contentfilename = contentfilename;
		this.originalExtension = originalExtension;
	}

	@Id

	@Column(name = "docid", unique = true, nullable = false)
	public int getDocid() {
		return this.docid;
	}

	public void setDocid(int docid) {
		this.docid = docid;
	}

	@Column(name = "patient_id", length = 20)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "imagefile")
	public byte[] getImagefile() {
		return this.imagefile;
	}

	public void setImagefile(byte[] imagefile) {
		this.imagefile = imagefile;
	}

	@Column(name = "contenttype")
	public String getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(String contenttype) {
		this.contenttype = contenttype;
	}

	@Column(name = "contentfilename")
	public String getContentfilename() {
		return this.contentfilename;
	}

	public void setContentfilename(String contentfilename) {
		this.contentfilename = contentfilename;
	}

	@Column(name = "original_extension", nullable = false, length = 200)
	public String getOriginalExtension() {
		return this.originalExtension;
	}

	public void setOriginalExtension(String originalExtension) {
		this.originalExtension = originalExtension;
	}

}
