package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DiscountCategoryChargeheadsModel generated by hbm2java
 */
@Entity
@Table(name = "discount_category_chargeheads")
public class DiscountCategoryChargeheadsModel implements java.io.Serializable {

	private DiscountCategoryChargeheadsIdSequence id;

	public DiscountCategoryChargeheadsModel() {
	}

	public DiscountCategoryChargeheadsModel(DiscountCategoryChargeheadsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "discountCatId", column = @Column(name = "discount_cat_id", nullable = false)),
			@AttributeOverride(name = "chargeHead", column = @Column(name = "charge_head", length = 20)) })
	public DiscountCategoryChargeheadsIdSequence getId() {
		return this.id;
	}

	public void setId(DiscountCategoryChargeheadsIdSequence id) {
		this.id = id;
	}

}
