package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DiscountAuthorizerModel generated by hbm2java
 */
@Entity
@Table(name = "discount_authorizer")
public class DiscountAuthorizerModel implements java.io.Serializable {

	private int discAuthId;
	private String discAuthName;
	private String status;
	private Date createdTimestamp;
	private Date updatedTimestamp;
	private String centerId;

	public DiscountAuthorizerModel() {
	}

	public DiscountAuthorizerModel(int discAuthId, Date createdTimestamp, Date updatedTimestamp, String centerId) {
		this.discAuthId = discAuthId;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
		this.centerId = centerId;
	}

	public DiscountAuthorizerModel(int discAuthId, String discAuthName, String status, Date createdTimestamp,
			Date updatedTimestamp, String centerId) {
		this.discAuthId = discAuthId;
		this.discAuthName = discAuthName;
		this.status = status;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
		this.centerId = centerId;
	}

	@Id

	@Column(name = "disc_auth_id", unique = true, nullable = false)
	public int getDiscAuthId() {
		return this.discAuthId;
	}

	public void setDiscAuthId(int discAuthId) {
		this.discAuthId = discAuthId;
	}

	@Column(name = "disc_auth_name", length = 100)
	public String getDiscAuthName() {
		return this.discAuthName;
	}

	public void setDiscAuthName(String discAuthName) {
		this.discAuthName = discAuthName;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_timestamp", nullable = false, length = 29)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_timestamp", nullable = false, length = 29)
	public Date getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	@Column(name = "center_id", nullable = false, length = 100)
	public String getCenterId() {
		return this.centerId;
	}

	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

}
