package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DischargeMedicationModel generated by hbm2java
 */
@Entity
@Table(name = "discharge_medication", uniqueConstraints = @UniqueConstraint(columnNames = "visit_id"))
public class DischargeMedicationModel implements java.io.Serializable {

	private int medicationId;
	private String visitId;
	private String doctorId;
	private String userName;
	private Date modTime;

	public DischargeMedicationModel() {
	}

	public DischargeMedicationModel(int medicationId, String visitId, String doctorId) {
		this.medicationId = medicationId;
		this.visitId = visitId;
		this.doctorId = doctorId;
	}

	public DischargeMedicationModel(int medicationId, String visitId, String doctorId, String userName, Date modTime) {
		this.medicationId = medicationId;
		this.visitId = visitId;
		this.doctorId = doctorId;
		this.userName = userName;
		this.modTime = modTime;
	}

	@Id

	@Column(name = "medication_id", unique = true, nullable = false)
	public int getMedicationId() {
		return this.medicationId;
	}

	public void setMedicationId(int medicationId) {
		this.medicationId = medicationId;
	}

	@Column(name = "visit_id", unique = true, nullable = false, length = 15)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Column(name = "doctor_id", nullable = false, length = 20)
	public String getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

}
