package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DocPdfTemplateExtFieldsModel generated by hbm2java
 */
@Entity
@Table(name = "doc_pdf_template_ext_fields")
public class DocPdfTemplateExtFieldsModel implements java.io.Serializable {

	private DocPdfTemplateExtFieldsIdSequence id;

	public DocPdfTemplateExtFieldsModel() {
	}

	public DocPdfTemplateExtFieldsModel(DocPdfTemplateExtFieldsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "templateId", column = @Column(name = "template_id")),
			@AttributeOverride(name = "fieldId", column = @Column(name = "field_id")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name", length = 100)),
			@AttributeOverride(name = "displayName", column = @Column(name = "display_name", length = 100)),
			@AttributeOverride(name = "fieldInput", column = @Column(name = "field_input", length = 1)) })
	public DocPdfTemplateExtFieldsIdSequence getId() {
		return this.id;
	}

	public void setId(DocPdfTemplateExtFieldsIdSequence id) {
		this.id = id;
	}

}
