package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.doctors.DoctorsModel;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DoctorConsultationChargeModel generated by hbm2java
 */
@Entity
@Table(name = "doctor_consultation_charge")
public class DoctorConsultationChargeModel implements java.io.Serializable {

	private DoctorConsultationChargeIdSequence id;
	private DoctorsModel DoctorsModel;
	private BigDecimal doctorIpCharge;
	private BigDecimal nightIpCharge;
	private BigDecimal otCharge;
	private BigDecimal coSurgeonCharge;
	private BigDecimal assntSurgeonCharge;
	private BigDecimal doctorIpChargeDiscount;
	private BigDecimal nightIpChargeDiscount;
	private BigDecimal otChargeDiscount;
	private BigDecimal coSurgeonChargeDiscount;
	private BigDecimal assntSurgeonChargeDiscount;
	private BigDecimal wardIpCharge;
	private BigDecimal wardIpChargeDiscount;
	private String isOverride;

	public DoctorConsultationChargeModel() {
	}

	public DoctorConsultationChargeModel(DoctorConsultationChargeIdSequence id, DoctorsModel DoctorsModel, BigDecimal doctorIpCharge,
			BigDecimal nightIpCharge, BigDecimal otCharge, BigDecimal coSurgeonCharge, BigDecimal assntSurgeonCharge,
			BigDecimal doctorIpChargeDiscount, BigDecimal nightIpChargeDiscount, BigDecimal otChargeDiscount,
			BigDecimal coSurgeonChargeDiscount, BigDecimal assntSurgeonChargeDiscount, BigDecimal wardIpCharge,
			BigDecimal wardIpChargeDiscount) {
		this.id = id;
		this.DoctorsModel = DoctorsModel;
		this.doctorIpCharge = doctorIpCharge;
		this.nightIpCharge = nightIpCharge;
		this.otCharge = otCharge;
		this.coSurgeonCharge = coSurgeonCharge;
		this.assntSurgeonCharge = assntSurgeonCharge;
		this.doctorIpChargeDiscount = doctorIpChargeDiscount;
		this.nightIpChargeDiscount = nightIpChargeDiscount;
		this.otChargeDiscount = otChargeDiscount;
		this.coSurgeonChargeDiscount = coSurgeonChargeDiscount;
		this.assntSurgeonChargeDiscount = assntSurgeonChargeDiscount;
		this.wardIpCharge = wardIpCharge;
		this.wardIpChargeDiscount = wardIpChargeDiscount;
	}

	public DoctorConsultationChargeModel(DoctorConsultationChargeIdSequence id, DoctorsModel DoctorsModel, BigDecimal doctorIpCharge,
			BigDecimal nightIpCharge, BigDecimal otCharge, BigDecimal coSurgeonCharge, BigDecimal assntSurgeonCharge,
			BigDecimal doctorIpChargeDiscount, BigDecimal nightIpChargeDiscount, BigDecimal otChargeDiscount,
			BigDecimal coSurgeonChargeDiscount, BigDecimal assntSurgeonChargeDiscount, BigDecimal wardIpCharge,
			BigDecimal wardIpChargeDiscount, String isOverride) {
		this.id = id;
		this.DoctorsModel = DoctorsModel;
		this.doctorIpCharge = doctorIpCharge;
		this.nightIpCharge = nightIpCharge;
		this.otCharge = otCharge;
		this.coSurgeonCharge = coSurgeonCharge;
		this.assntSurgeonCharge = assntSurgeonCharge;
		this.doctorIpChargeDiscount = doctorIpChargeDiscount;
		this.nightIpChargeDiscount = nightIpChargeDiscount;
		this.otChargeDiscount = otChargeDiscount;
		this.coSurgeonChargeDiscount = coSurgeonChargeDiscount;
		this.assntSurgeonChargeDiscount = assntSurgeonChargeDiscount;
		this.wardIpCharge = wardIpCharge;
		this.wardIpChargeDiscount = wardIpChargeDiscount;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "organization", column = @Column(name = "organization", nullable = false, length = 100)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", nullable = false, length = 100)),
			@AttributeOverride(name = "doctorName", column = @Column(name = "doctor_name", nullable = false, length = 20)) })
	public DoctorConsultationChargeIdSequence getId() {
		return this.id;
	}

	public void setId(DoctorConsultationChargeIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_name", nullable = false, insertable = false, updatable = false)
	public DoctorsModel getDoctorsModel() {
		return this.DoctorsModel;
	}

	public void setDoctorsModel(DoctorsModel DoctorsModel) {
		this.DoctorsModel = DoctorsModel;
	}

	@Column(name = "doctor_ip_charge", nullable = false, precision = 15)
	public BigDecimal getDoctorIpCharge() {
		return this.doctorIpCharge;
	}

	public void setDoctorIpCharge(BigDecimal doctorIpCharge) {
		this.doctorIpCharge = doctorIpCharge;
	}

	@Column(name = "night_ip_charge", nullable = false, precision = 15)
	public BigDecimal getNightIpCharge() {
		return this.nightIpCharge;
	}

	public void setNightIpCharge(BigDecimal nightIpCharge) {
		this.nightIpCharge = nightIpCharge;
	}

	@Column(name = "ot_charge", nullable = false, precision = 15)
	public BigDecimal getOtCharge() {
		return this.otCharge;
	}

	public void setOtCharge(BigDecimal otCharge) {
		this.otCharge = otCharge;
	}

	@Column(name = "co_surgeon_charge", nullable = false, precision = 15)
	public BigDecimal getCoSurgeonCharge() {
		return this.coSurgeonCharge;
	}

	public void setCoSurgeonCharge(BigDecimal coSurgeonCharge) {
		this.coSurgeonCharge = coSurgeonCharge;
	}

	@Column(name = "assnt_surgeon_charge", nullable = false, precision = 15)
	public BigDecimal getAssntSurgeonCharge() {
		return this.assntSurgeonCharge;
	}

	public void setAssntSurgeonCharge(BigDecimal assntSurgeonCharge) {
		this.assntSurgeonCharge = assntSurgeonCharge;
	}

	@Column(name = "doctor_ip_charge_discount", nullable = false, precision = 15)
	public BigDecimal getDoctorIpChargeDiscount() {
		return this.doctorIpChargeDiscount;
	}

	public void setDoctorIpChargeDiscount(BigDecimal doctorIpChargeDiscount) {
		this.doctorIpChargeDiscount = doctorIpChargeDiscount;
	}

	@Column(name = "night_ip_charge_discount", nullable = false, precision = 15)
	public BigDecimal getNightIpChargeDiscount() {
		return this.nightIpChargeDiscount;
	}

	public void setNightIpChargeDiscount(BigDecimal nightIpChargeDiscount) {
		this.nightIpChargeDiscount = nightIpChargeDiscount;
	}

	@Column(name = "ot_charge_discount", nullable = false, precision = 15)
	public BigDecimal getOtChargeDiscount() {
		return this.otChargeDiscount;
	}

	public void setOtChargeDiscount(BigDecimal otChargeDiscount) {
		this.otChargeDiscount = otChargeDiscount;
	}

	@Column(name = "co_surgeon_charge_discount", nullable = false, precision = 15)
	public BigDecimal getCoSurgeonChargeDiscount() {
		return this.coSurgeonChargeDiscount;
	}

	public void setCoSurgeonChargeDiscount(BigDecimal coSurgeonChargeDiscount) {
		this.coSurgeonChargeDiscount = coSurgeonChargeDiscount;
	}

	@Column(name = "assnt_surgeon_charge_discount", nullable = false, precision = 15)
	public BigDecimal getAssntSurgeonChargeDiscount() {
		return this.assntSurgeonChargeDiscount;
	}

	public void setAssntSurgeonChargeDiscount(BigDecimal assntSurgeonChargeDiscount) {
		this.assntSurgeonChargeDiscount = assntSurgeonChargeDiscount;
	}

	@Column(name = "ward_ip_charge", nullable = false, precision = 15)
	public BigDecimal getWardIpCharge() {
		return this.wardIpCharge;
	}

	public void setWardIpCharge(BigDecimal wardIpCharge) {
		this.wardIpCharge = wardIpCharge;
	}

	@Column(name = "ward_ip_charge_discount", nullable = false, precision = 15)
	public BigDecimal getWardIpChargeDiscount() {
		return this.wardIpChargeDiscount;
	}

	public void setWardIpChargeDiscount(BigDecimal wardIpChargeDiscount) {
		this.wardIpChargeDiscount = wardIpChargeDiscount;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
