package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DoctorOrderAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "doctor_order_audit_log")
public class DoctorOrderAuditLogModel implements java.io.Serializable {

	private DoctorOrderAuditLogIdSequence id;

	public DoctorOrderAuditLogModel() {
	}

	public DoctorOrderAuditLogModel(DoctorOrderAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", length = 15)),
			@AttributeOverride(name = "prescType", column = @Column(name = "presc_type", length = 1)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "operation", column = @Column(name = "operation")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")),
			@AttributeOverride(name = "prescriptionId", column = @Column(name = "prescription_id")) })
	public DoctorOrderAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(DoctorOrderAuditLogIdSequence id) {
		this.id = id;
	}

}
