package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DoctorImagesModel generated by hbm2java
 */
@Entity
@Table(name = "doctor_images")
public class DoctorImagesModel implements java.io.Serializable {

	private DoctorImagesIdSequence id;

	public DoctorImagesModel() {
	}

	public DoctorImagesModel(DoctorImagesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "doctorId", column = @Column(name = "doctor_id", length = 20)),
			@AttributeOverride(name = "photo", column = @Column(name = "photo")),
			@AttributeOverride(name = "contentType", column = @Column(name = "content_type", length = 200)) })
	public DoctorImagesIdSequence getId() {
		return this.id;
	}

	public void setId(DoctorImagesIdSequence id) {
		this.id = id;
	}

}
