package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.core.patient.PatientDetailsModel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DonorBloodGroupingModel generated by hbm2java
 */
@Entity
@Table(name = "donor_blood_grouping")
public class DonorBloodGroupingModel implements java.io.Serializable {

	private String donorBloodGroupingId;
	private DonorRegistrationModel donorRegistration;
	private DonorCollectionDetModel donorCollectionDet;
	private PatientDetailsModel patientDetails;
	private String bloodGroupName;
	private String donorBloodGroupingSbgroup;
	private String donorBloodGroupingAntibodydet;
	private String donorBloodGroupingNoname;
	private String donorBloodGroupingUnits;
	private String donorBloodGroupingNormalrange;
	private String donorBloodGroupingRemarks;
	private String donorBloodGroupingStorageloc;
	private String donorBloodGroupingBloodtestperson;
	private String donorBloodGroupingScrcompl;
	private String groupingstatus;
	private String rhtypeName;

	public DonorBloodGroupingModel() {
	}

	public DonorBloodGroupingModel(String donorBloodGroupingId) {
		this.donorBloodGroupingId = donorBloodGroupingId;
	}

	public DonorBloodGroupingModel(String donorBloodGroupingId, DonorRegistrationModel donorRegistration,
			DonorCollectionDetModel donorCollectionDet, PatientDetailsModel patientDetails, String bloodGroupName,
			String donorBloodGroupingSbgroup, String donorBloodGroupingAntibodydet, String donorBloodGroupingNoname,
			String donorBloodGroupingUnits, String donorBloodGroupingNormalrange, String donorBloodGroupingRemarks,
			String donorBloodGroupingStorageloc, String donorBloodGroupingBloodtestperson,
			String donorBloodGroupingScrcompl, String groupingstatus, String rhtypeName) {
		this.donorBloodGroupingId = donorBloodGroupingId;
		this.donorRegistration = donorRegistration;
		this.donorCollectionDet = donorCollectionDet;
		this.patientDetails = patientDetails;
		this.bloodGroupName = bloodGroupName;
		this.donorBloodGroupingSbgroup = donorBloodGroupingSbgroup;
		this.donorBloodGroupingAntibodydet = donorBloodGroupingAntibodydet;
		this.donorBloodGroupingNoname = donorBloodGroupingNoname;
		this.donorBloodGroupingUnits = donorBloodGroupingUnits;
		this.donorBloodGroupingNormalrange = donorBloodGroupingNormalrange;
		this.donorBloodGroupingRemarks = donorBloodGroupingRemarks;
		this.donorBloodGroupingStorageloc = donorBloodGroupingStorageloc;
		this.donorBloodGroupingBloodtestperson = donorBloodGroupingBloodtestperson;
		this.donorBloodGroupingScrcompl = donorBloodGroupingScrcompl;
		this.groupingstatus = groupingstatus;
		this.rhtypeName = rhtypeName;
	}

	@Id

	@Column(name = "donor_blood_grouping_id", unique = true, nullable = false, length = 50)
	public String getDonorBloodGroupingIdSequence() {
		return this.donorBloodGroupingId;
	}

	public void setDonorBloodGroupingIdSequence(String donorBloodGroupingId) {
		this.donorBloodGroupingId = donorBloodGroupingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "donor_reg_id")
	public DonorRegistrationModel getDonorRegistrationModel() {
		return this.donorRegistration;
	}

	public void setDonorRegistrationModel(DonorRegistrationModel donorRegistration) {
		this.donorRegistration = donorRegistration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "donor_collection_blood_bag_id")
	public DonorCollectionDetModel getDonorCollectionDetModel() {
		return this.donorCollectionDet;
	}

	public void setDonorCollectionDetModel(DonorCollectionDetModel donorCollectionDet) {
		this.donorCollectionDet = donorCollectionDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mr_no")
	public PatientDetailsModel getPatientDetailsModel() {
		return this.patientDetails;
	}

	public void setPatientDetailsModel(PatientDetailsModel patientDetails) {
		this.patientDetails = patientDetails;
	}

	@Column(name = "blood_group_name", length = 50)
	public String getBloodGroupName() {
		return this.bloodGroupName;
	}

	public void setBloodGroupName(String bloodGroupName) {
		this.bloodGroupName = bloodGroupName;
	}

	@Column(name = "donor_blood_grouping_sbgroup", length = 50)
	public String getDonorBloodGroupingModelSbgroup() {
		return this.donorBloodGroupingSbgroup;
	}

	public void setDonorBloodGroupingModelSbgroup(String donorBloodGroupingSbgroup) {
		this.donorBloodGroupingSbgroup = donorBloodGroupingSbgroup;
	}

	@Column(name = "donor_blood_grouping_antibodydet", length = 50)
	public String getDonorBloodGroupingModelAntibodydet() {
		return this.donorBloodGroupingAntibodydet;
	}

	public void setDonorBloodGroupingModelAntibodydet(String donorBloodGroupingAntibodydet) {
		this.donorBloodGroupingAntibodydet = donorBloodGroupingAntibodydet;
	}

	@Column(name = "donor_blood_grouping_noname", length = 50)
	public String getDonorBloodGroupingModelNoname() {
		return this.donorBloodGroupingNoname;
	}

	public void setDonorBloodGroupingModelNoname(String donorBloodGroupingNoname) {
		this.donorBloodGroupingNoname = donorBloodGroupingNoname;
	}

	@Column(name = "donor_blood_grouping_units", length = 50)
	public String getDonorBloodGroupingModelUnits() {
		return this.donorBloodGroupingUnits;
	}

	public void setDonorBloodGroupingModelUnits(String donorBloodGroupingUnits) {
		this.donorBloodGroupingUnits = donorBloodGroupingUnits;
	}

	@Column(name = "donor_blood_grouping_normalrange", length = 50)
	public String getDonorBloodGroupingModelNormalrange() {
		return this.donorBloodGroupingNormalrange;
	}

	public void setDonorBloodGroupingModelNormalrange(String donorBloodGroupingNormalrange) {
		this.donorBloodGroupingNormalrange = donorBloodGroupingNormalrange;
	}

	@Column(name = "donor_blood_grouping_remarks", length = 50)
	public String getDonorBloodGroupingModelRemarks() {
		return this.donorBloodGroupingRemarks;
	}

	public void setDonorBloodGroupingModelRemarks(String donorBloodGroupingRemarks) {
		this.donorBloodGroupingRemarks = donorBloodGroupingRemarks;
	}

	@Column(name = "donor_blood_grouping_storageloc", length = 50)
	public String getDonorBloodGroupingModelStorageloc() {
		return this.donorBloodGroupingStorageloc;
	}

	public void setDonorBloodGroupingModelStorageloc(String donorBloodGroupingStorageloc) {
		this.donorBloodGroupingStorageloc = donorBloodGroupingStorageloc;
	}

	@Column(name = "donor_blood_grouping_bloodtestperson", length = 50)
	public String getDonorBloodGroupingModelBloodtestperson() {
		return this.donorBloodGroupingBloodtestperson;
	}

	public void setDonorBloodGroupingModelBloodtestperson(String donorBloodGroupingBloodtestperson) {
		this.donorBloodGroupingBloodtestperson = donorBloodGroupingBloodtestperson;
	}

	@Column(name = "donor_blood_grouping_scrcompl", length = 50)
	public String getDonorBloodGroupingModelScrcompl() {
		return this.donorBloodGroupingScrcompl;
	}

	public void setDonorBloodGroupingModelScrcompl(String donorBloodGroupingScrcompl) {
		this.donorBloodGroupingScrcompl = donorBloodGroupingScrcompl;
	}

	@Column(name = "groupingstatus", length = 50)
	public String getGroupingstatus() {
		return this.groupingstatus;
	}

	public void setGroupingstatus(String groupingstatus) {
		this.groupingstatus = groupingstatus;
	}

	@Column(name = "rhtype_name", length = 50)
	public String getRhtypeName() {
		return this.rhtypeName;
	}

	public void setRhtypeName(String rhtypeName) {
		this.rhtypeName = rhtypeName;
	}

}
