package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.core.patient.PatientDetailsModel;
import com.insta.hms.mdm.areas.AreaMasterModel;
import com.insta.hms.mdm.countries.CountryMasterModel;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonorRegistrationModel generated by hbm2java
 */
@Entity
@Table(name = "donor_registration")
public class DonorRegistrationModel implements java.io.Serializable {

	private String donorRegId;
	private PatientDetailsModel patientDetails;
	private CountryMasterModel countryMaster;
	private AreaMasterModel areaMaster;
	private String donorRegGender;
	private String patientPhone;
	private Integer donorRegAge;
	private String donorRegAddress;
	private String patCityName;
	private String donorRegState;
	private String donorRegFirstName;
	private String donorRegLastname;
	private String bdtypeName;
	private Boolean donorRegCamp;
	private String donorRegCampDetails;
	private String donorRegRelatedToPatientMrNumber;
	private String donorRegRelation;
	private String donorRegDonorRejected;
	private Date donorRegOn;
	private String donorRegBy;
	private String donorRegRejectionReason;
	private Date donorRegDate;
	private String donorRegType;
	private String donorRegTitle;
	private String referaldoctorname;
	private String middleName;
	private Set donorBloodGroupings = new HashSet(0);
	private Set donorBloodDiscards = new HashSet(0);
	private Set donorCollectionDets = new HashSet(0);
	private Set donorBloodComponents = new HashSet(0);
	private Set donorBloodTestResultses = new HashSet(0);

	public DonorRegistrationModel() {
	}

	public DonorRegistrationModel(String donorRegId, String donorRegGender, String patientPhone, String donorRegAddress,
			String donorRegFirstName, String donorRegLastname, Date donorRegDate, String donorRegTitle,
			String middleName) {
		this.donorRegId = donorRegId;
		this.donorRegGender = donorRegGender;
		this.patientPhone = patientPhone;
		this.donorRegAddress = donorRegAddress;
		this.donorRegFirstName = donorRegFirstName;
		this.donorRegLastname = donorRegLastname;
		this.donorRegDate = donorRegDate;
		this.donorRegTitle = donorRegTitle;
		this.middleName = middleName;
	}

	public DonorRegistrationModel(String donorRegId, PatientDetailsModel patientDetails, CountryMasterModel countryMaster,
			AreaMasterModel areaMaster, String donorRegGender, String patientPhone, Integer donorRegAge,
			String donorRegAddress, String patCityName, String donorRegState, String donorRegFirstName,
			String donorRegLastname, String bdtypeName, Boolean donorRegCamp, String donorRegCampDetails,
			String donorRegRelatedToPatientMrNumber, String donorRegRelation, String donorRegDonorRejected,
			Date donorRegOn, String donorRegBy, String donorRegRejectionReason, Date donorRegDate, String donorRegType,
			String donorRegTitle, String referaldoctorname, String middleName, Set donorBloodGroupings,
			Set donorBloodDiscards, Set donorCollectionDets, Set donorBloodComponents, Set donorBloodTestResultses) {
		this.donorRegId = donorRegId;
		this.patientDetails = patientDetails;
		this.countryMaster = countryMaster;
		this.areaMaster = areaMaster;
		this.donorRegGender = donorRegGender;
		this.patientPhone = patientPhone;
		this.donorRegAge = donorRegAge;
		this.donorRegAddress = donorRegAddress;
		this.patCityName = patCityName;
		this.donorRegState = donorRegState;
		this.donorRegFirstName = donorRegFirstName;
		this.donorRegLastname = donorRegLastname;
		this.bdtypeName = bdtypeName;
		this.donorRegCamp = donorRegCamp;
		this.donorRegCampDetails = donorRegCampDetails;
		this.donorRegRelatedToPatientMrNumber = donorRegRelatedToPatientMrNumber;
		this.donorRegRelation = donorRegRelation;
		this.donorRegDonorRejected = donorRegDonorRejected;
		this.donorRegOn = donorRegOn;
		this.donorRegBy = donorRegBy;
		this.donorRegRejectionReason = donorRegRejectionReason;
		this.donorRegDate = donorRegDate;
		this.donorRegType = donorRegType;
		this.donorRegTitle = donorRegTitle;
		this.referaldoctorname = referaldoctorname;
		this.middleName = middleName;
		this.donorBloodGroupings = donorBloodGroupings;
		this.donorBloodDiscards = donorBloodDiscards;
		this.donorCollectionDets = donorCollectionDets;
		this.donorBloodComponents = donorBloodComponents;
		this.donorBloodTestResultses = donorBloodTestResultses;
	}

	@Id

	@Column(name = "donor_reg_id", unique = true, nullable = false, length = 50)
	public String getDonorRegId() {
		return this.donorRegId;
	}

	public void setDonorRegId(String donorRegId) {
		this.donorRegId = donorRegId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mrno")
	public PatientDetailsModel getPatientDetailsModel() {
		return this.patientDetails;
	}

	public void setPatientDetailsModel(PatientDetailsModel patientDetails) {
		this.patientDetails = patientDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "donor_reg_country")
	public CountryMasterModel getCountryMasterModel() {
		return this.countryMaster;
	}

	public void setCountryMasterModel(CountryMasterModel countryMaster) {
		this.countryMaster = countryMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_area")
	public AreaMasterModel getAreaMasterModel() {
		return this.areaMaster;
	}

	public void setAreaMasterModel(AreaMasterModel areaMaster) {
		this.areaMaster = areaMaster;
	}

	@Column(name = "donor_reg_gender", nullable = false, length = 10)
	public String getDonorRegGender() {
		return this.donorRegGender;
	}

	public void setDonorRegGender(String donorRegGender) {
		this.donorRegGender = donorRegGender;
	}

	@Column(name = "patient_phone", nullable = false, length = 15)
	public String getPatientPhone() {
		return this.patientPhone;
	}

	public void setPatientPhone(String patientPhone) {
		this.patientPhone = patientPhone;
	}

	@Column(name = "donor_reg_age")
	public Integer getDonorRegAge() {
		return this.donorRegAge;
	}

	public void setDonorRegAge(Integer donorRegAge) {
		this.donorRegAge = donorRegAge;
	}

	@Column(name = "donor_reg_address", nullable = false, length = 100)
	public String getDonorRegAddress() {
		return this.donorRegAddress;
	}

	public void setDonorRegAddress(String donorRegAddress) {
		this.donorRegAddress = donorRegAddress;
	}

	@Column(name = "pat_city_name", length = 50)
	public String getPatCityName() {
		return this.patCityName;
	}

	public void setPatCityName(String patCityName) {
		this.patCityName = patCityName;
	}

	@Column(name = "donor_reg_state", length = 50)
	public String getDonorRegState() {
		return this.donorRegState;
	}

	public void setDonorRegState(String donorRegState) {
		this.donorRegState = donorRegState;
	}

	@Column(name = "donor_reg_first_name", nullable = false)
	public String getDonorRegFirstName() {
		return this.donorRegFirstName;
	}

	public void setDonorRegFirstName(String donorRegFirstName) {
		this.donorRegFirstName = donorRegFirstName;
	}

	@Column(name = "donor_reg_lastname", nullable = false)
	public String getDonorRegLastname() {
		return this.donorRegLastname;
	}

	public void setDonorRegLastname(String donorRegLastname) {
		this.donorRegLastname = donorRegLastname;
	}

	@Column(name = "bdtype_name", length = 20)
	public String getBdtypeName() {
		return this.bdtypeName;
	}

	public void setBdtypeName(String bdtypeName) {
		this.bdtypeName = bdtypeName;
	}

	@Column(name = "donor_reg_camp")
	public Boolean getDonorRegCamp() {
		return this.donorRegCamp;
	}

	public void setDonorRegCamp(Boolean donorRegCamp) {
		this.donorRegCamp = donorRegCamp;
	}

	@Column(name = "donor_reg_camp_details", length = 50)
	public String getDonorRegCampDetails() {
		return this.donorRegCampDetails;
	}

	public void setDonorRegCampDetails(String donorRegCampDetails) {
		this.donorRegCampDetails = donorRegCampDetails;
	}

	@Column(name = "donor_reg_related_to_patient_mr_number", length = 50)
	public String getDonorRegRelatedToPatientMrNumber() {
		return this.donorRegRelatedToPatientMrNumber;
	}

	public void setDonorRegRelatedToPatientMrNumber(String donorRegRelatedToPatientMrNumber) {
		this.donorRegRelatedToPatientMrNumber = donorRegRelatedToPatientMrNumber;
	}

	@Column(name = "donor_reg_relation", length = 50)
	public String getDonorRegRelation() {
		return this.donorRegRelation;
	}

	public void setDonorRegRelation(String donorRegRelation) {
		this.donorRegRelation = donorRegRelation;
	}

	@Column(name = "donor_reg_donor_rejected", length = 5)
	public String getDonorRegDonorRejected() {
		return this.donorRegDonorRejected;
	}

	public void setDonorRegDonorRejected(String donorRegDonorRejected) {
		this.donorRegDonorRejected = donorRegDonorRejected;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "donor_reg_on", length = 13)
	public Date getDonorRegOn() {
		return this.donorRegOn;
	}

	public void setDonorRegOn(Date donorRegOn) {
		this.donorRegOn = donorRegOn;
	}

	@Column(name = "donor_reg_by", length = 50)
	public String getDonorRegBy() {
		return this.donorRegBy;
	}

	public void setDonorRegBy(String donorRegBy) {
		this.donorRegBy = donorRegBy;
	}

	@Column(name = "donor_reg_rejection_reason", length = 50)
	public String getDonorRegRejectionReason() {
		return this.donorRegRejectionReason;
	}

	public void setDonorRegRejectionReason(String donorRegRejectionReason) {
		this.donorRegRejectionReason = donorRegRejectionReason;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "donor_reg_date", nullable = false, length = 13)
	public Date getDonorRegDate() {
		return this.donorRegDate;
	}

	public void setDonorRegDate(Date donorRegDate) {
		this.donorRegDate = donorRegDate;
	}

	@Column(name = "donor_reg_type", length = 10)
	public String getDonorRegType() {
		return this.donorRegType;
	}

	public void setDonorRegType(String donorRegType) {
		this.donorRegType = donorRegType;
	}

	@Column(name = "donor_reg_title", nullable = false, length = 10)
	public String getDonorRegTitle() {
		return this.donorRegTitle;
	}

	public void setDonorRegTitle(String donorRegTitle) {
		this.donorRegTitle = donorRegTitle;
	}

	@Column(name = "referaldoctorname", length = 50)
	public String getReferaldoctorname() {
		return this.referaldoctorname;
	}

	public void setReferaldoctorname(String referaldoctorname) {
		this.referaldoctorname = referaldoctorname;
	}

	@Column(name = "middle_name", nullable = false, length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donorRegistration")
	public Set getDonorBloodGroupings() {
		return this.donorBloodGroupings;
	}

	public void setDonorBloodGroupings(Set donorBloodGroupings) {
		this.donorBloodGroupings = donorBloodGroupings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donorRegistration")
	public Set getDonorBloodDiscards() {
		return this.donorBloodDiscards;
	}

	public void setDonorBloodDiscards(Set donorBloodDiscards) {
		this.donorBloodDiscards = donorBloodDiscards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donorRegistration")
	public Set getDonorCollectionDets() {
		return this.donorCollectionDets;
	}

	public void setDonorCollectionDets(Set donorCollectionDets) {
		this.donorCollectionDets = donorCollectionDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donorRegistration")
	public Set getDonorBloodComponents() {
		return this.donorBloodComponents;
	}

	public void setDonorBloodComponents(Set donorBloodComponents) {
		this.donorBloodComponents = donorBloodComponents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donorRegistration")
	public Set getDonorBloodTestResultses() {
		return this.donorBloodTestResultses;
	}

	public void setDonorBloodTestResultses(Set donorBloodTestResultses) {
		this.donorBloodTestResultses = donorBloodTestResultses;
	}

}
