package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DonorBloodTestResultsIdSequence generated by hbm2java
 */
@Embeddable
public class DonorBloodTestResultsIdSequence implements java.io.Serializable {

	private String testName;
	private String value;
	private String severity;
	private String units;
	private String range;
	private String donorRegId;
	private String donorCollectionBloodBagId;

	public DonorBloodTestResultsIdSequence() {
	}

	public DonorBloodTestResultsIdSequence(String testName, String donorRegId) {
		this.testName = testName;
		this.donorRegId = donorRegId;
	}

	public DonorBloodTestResultsIdSequence(String testName, String value, String severity, String units, String range,
			String donorRegId, String donorCollectionBloodBagId) {
		this.testName = testName;
		this.value = value;
		this.severity = severity;
		this.units = units;
		this.range = range;
		this.donorRegId = donorRegId;
		this.donorCollectionBloodBagId = donorCollectionBloodBagId;
	}

	@Column(name = "test_name", nullable = false, length = 100)
	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "severity", length = 50)
	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	@Column(name = "units", length = 50)
	public String getUnits() {
		return this.units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	@Column(name = "range", length = 50)
	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

	@Column(name = "donor_reg_id", nullable = false, length = 50)
	public String getDonorRegId() {
		return this.donorRegId;
	}

	public void setDonorRegId(String donorRegId) {
		this.donorRegId = donorRegId;
	}

	@Column(name = "donor_collection_blood_bag_id", length = 50)
	public String getDonorCollectionBloodBagId() {
		return this.donorCollectionBloodBagId;
	}

	public void setDonorCollectionBloodBagId(String donorCollectionBloodBagId) {
		this.donorCollectionBloodBagId = donorCollectionBloodBagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DonorBloodTestResultsIdSequence))
			return false;
		DonorBloodTestResultsIdSequence castOther = (DonorBloodTestResultsIdSequence) other;

		return ((this.getTestName() == castOther.getTestName()) || (this.getTestName() != null
				&& castOther.getTestName() != null && this.getTestName().equals(castOther.getTestName())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())))
				&& ((this.getSeverity() == castOther.getSeverity()) || (this.getSeverity() != null
						&& castOther.getSeverity() != null && this.getSeverity().equals(castOther.getSeverity())))
				&& ((this.getUnits() == castOther.getUnits()) || (this.getUnits() != null
						&& castOther.getUnits() != null && this.getUnits().equals(castOther.getUnits())))
				&& ((this.getRange() == castOther.getRange()) || (this.getRange() != null
						&& castOther.getRange() != null && this.getRange().equals(castOther.getRange())))
				&& ((this.getDonorRegId() == castOther.getDonorRegId()) || (this.getDonorRegId() != null
						&& castOther.getDonorRegId() != null && this.getDonorRegId().equals(castOther.getDonorRegId())))
				&& ((this.getDonorCollectionBloodBagId() == castOther.getDonorCollectionBloodBagId())
						|| (this.getDonorCollectionBloodBagId() != null
								&& castOther.getDonorCollectionBloodBagId() != null
								&& this.getDonorCollectionBloodBagId()
										.equals(castOther.getDonorCollectionBloodBagId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTestName() == null ? 0 : this.getTestName().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + (getSeverity() == null ? 0 : this.getSeverity().hashCode());
		result = 37 * result + (getUnits() == null ? 0 : this.getUnits().hashCode());
		result = 37 * result + (getRange() == null ? 0 : this.getRange().hashCode());
		result = 37 * result + (getDonorRegId() == null ? 0 : this.getDonorRegId().hashCode());
		result = 37 * result
				+ (getDonorCollectionBloodBagId() == null ? 0 : this.getDonorCollectionBloodBagId().hashCode());
		return result;
	}

}
