package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DrgCodesMasterModel generated by hbm2java
 */
@Entity
@Table(name = "drg_codes_master")
public class DrgCodesMasterModel implements java.io.Serializable {

	private String drgCode;
	private String drgDescription;
	private Character patientType;
	private BigDecimal relativeWeight;
	private Character status;
	private String codeType;
	private String username;
	private BigDecimal hcpcsPortionPer;

	public DrgCodesMasterModel() {
	}

	public DrgCodesMasterModel(String drgCode, String drgDescription, String codeType, BigDecimal hcpcsPortionPer) {
		this.drgCode = drgCode;
		this.drgDescription = drgDescription;
		this.codeType = codeType;
		this.hcpcsPortionPer = hcpcsPortionPer;
	}

	public DrgCodesMasterModel(String drgCode, String drgDescription, Character patientType, BigDecimal relativeWeight,
			Character status, String codeType, String username, BigDecimal hcpcsPortionPer) {
		this.drgCode = drgCode;
		this.drgDescription = drgDescription;
		this.patientType = patientType;
		this.relativeWeight = relativeWeight;
		this.status = status;
		this.codeType = codeType;
		this.username = username;
		this.hcpcsPortionPer = hcpcsPortionPer;
	}

	@Id

	@Column(name = "drg_code", unique = true, nullable = false, length = 15)
	public String getDrgCode() {
		return this.drgCode;
	}

	public void setDrgCode(String drgCode) {
		this.drgCode = drgCode;
	}

	@Column(name = "drg_description", nullable = false)
	public String getDrgDescription() {
		return this.drgDescription;
	}

	public void setDrgDescription(String drgDescription) {
		this.drgDescription = drgDescription;
	}

	@Column(name = "patient_type", length = 1)
	public Character getPatientType() {
		return this.patientType;
	}

	public void setPatientType(Character patientType) {
		this.patientType = patientType;
	}

	@Column(name = "relative_weight", precision = 131089, scale = 0)
	public BigDecimal getRelativeWeight() {
		return this.relativeWeight;
	}

	public void setRelativeWeight(BigDecimal relativeWeight) {
		this.relativeWeight = relativeWeight;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "code_type", nullable = false, length = 50)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "hcpcs_portion_per", nullable = false, precision = 10)
	public BigDecimal getHcpcsPortionPer() {
		return this.hcpcsPortionPer;
	}

	public void setHcpcsPortionPer(BigDecimal hcpcsPortionPer) {
		this.hcpcsPortionPer = hcpcsPortionPer;
	}

}
