package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.organization.OrganizationDetailsModel;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DynaPackageOrgDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "dyna_package_org_details")
public class DynaPackageOrgDetailsModel implements java.io.Serializable {

	private DynaPackageOrgDetailsIdSequence id;
	private OrganizationDetailsModel organizationDetails;
	private DynaPackagesModel dynaPackages;
	private boolean applicable;
	private String itemCode;
	private String codeType;
	private String baseRateSheetId;
	private String isOverride;

	public DynaPackageOrgDetailsModel() {
	}

	public DynaPackageOrgDetailsModel(DynaPackageOrgDetailsIdSequence id, OrganizationDetailsModel organizationDetails,
			DynaPackagesModel dynaPackages, boolean applicable) {
		this.id = id;
		this.organizationDetails = organizationDetails;
		this.dynaPackages = dynaPackages;
		this.applicable = applicable;
	}

	public DynaPackageOrgDetailsModel(DynaPackageOrgDetailsIdSequence id, OrganizationDetailsModel organizationDetails,
			DynaPackagesModel dynaPackages, boolean applicable, String itemCode, String codeType, String baseRateSheetId,
			String isOverride) {
		this.id = id;
		this.organizationDetails = organizationDetails;
		this.dynaPackages = dynaPackages;
		this.applicable = applicable;
		this.itemCode = itemCode;
		this.codeType = codeType;
		this.baseRateSheetId = baseRateSheetId;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dynaPackageId", column = @Column(name = "dyna_package_id", nullable = false)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 10)) })
	public DynaPackageOrgDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(DynaPackageOrgDetailsIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false, insertable = false, updatable = false)
	public OrganizationDetailsModel getOrganizationDetailsModel() {
		return this.organizationDetails;
	}

	public void setOrganizationDetailsModel(OrganizationDetailsModel organizationDetails) {
		this.organizationDetails = organizationDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dyna_package_id", nullable = false, insertable = false, updatable = false)
	public DynaPackagesModel getDynaPackagesModel() {
		return this.dynaPackages;
	}

	public void setDynaPackagesModel(DynaPackagesModel dynaPackages) {
		this.dynaPackages = dynaPackages;
	}

	@Column(name = "applicable", nullable = false)
	public boolean isApplicable() {
		return this.applicable;
	}

	public void setApplicable(boolean applicable) {
		this.applicable = applicable;
	}

	@Column(name = "item_code", length = 20)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "code_type", length = 50)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "base_rate_sheet_id", length = 10)
	public String getBaseRateSheetId() {
		return this.baseRateSheetId;
	}

	public void setBaseRateSheetId(String baseRateSheetId) {
		this.baseRateSheetId = baseRateSheetId;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
