package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailCategoryMasterModel generated by hbm2java
 */
@Entity
@Table(name = "email_category_master")
public class EmailCategoryMasterModel implements java.io.Serializable {

	private EmailCategoryMasterIdSequence id;

	public EmailCategoryMasterModel() {
	}

	public EmailCategoryMasterModel(EmailCategoryMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "categoryName", column = @Column(name = "category_name", length = 50)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", length = 1)) })
	public EmailCategoryMasterIdSequence getId() {
		return this.id;
	}

	public void setId(EmailCategoryMasterIdSequence id) {
		this.id = id;
	}

}
