package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmrAccessRuleModel generated by hbm2java
 */
@Entity
@Table(name = "emr_access_rule")
public class EmrAccessRuleModel implements java.io.Serializable {

	private String ruleId;
	private String ruleType;
	private String docTypeId;
	private String docSubType;
	private String roleId;
	private String centerAccess;
	private String deptAccess;
	private String roleAccess;
	private String userAccess;
	private String docAccess;
	private Set emrAccessRuleDetailses = new HashSet(0);

	public EmrAccessRuleModel() {
	}

	public EmrAccessRuleModel(String ruleId, String ruleType) {
		this.ruleId = ruleId;
		this.ruleType = ruleType;
	}

	public EmrAccessRuleModel(String ruleId, String ruleType, String docTypeId, String docSubType, String roleId,
			String centerAccess, String deptAccess, String roleAccess, String userAccess, String docAccess,
			Set emrAccessRuleDetailses) {
		this.ruleId = ruleId;
		this.ruleType = ruleType;
		this.docTypeId = docTypeId;
		this.docSubType = docSubType;
		this.roleId = roleId;
		this.centerAccess = centerAccess;
		this.deptAccess = deptAccess;
		this.roleAccess = roleAccess;
		this.userAccess = userAccess;
		this.docAccess = docAccess;
		this.emrAccessRuleDetailses = emrAccessRuleDetailses;
	}

	@Id

	@Column(name = "rule_id", unique = true, nullable = false)
	public String getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(String ruleId) {
		this.ruleId = ruleId;
	}

	@Column(name = "rule_type", nullable = false, length = 100)
	public String getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	@Column(name = "doc_type_id", length = 20)
	public String getDocTypeId() {
		return this.docTypeId;
	}

	public void setDocTypeId(String docTypeId) {
		this.docTypeId = docTypeId;
	}

	@Column(name = "doc_sub_type", length = 100)
	public String getDocSubType() {
		return this.docSubType;
	}

	public void setDocSubType(String docSubType) {
		this.docSubType = docSubType;
	}

	@Column(name = "role_id", length = 20)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "center_access", length = 20)
	public String getCenterAccess() {
		return this.centerAccess;
	}

	public void setCenterAccess(String centerAccess) {
		this.centerAccess = centerAccess;
	}

	@Column(name = "dept_access", length = 20)
	public String getDeptAccess() {
		return this.deptAccess;
	}

	public void setDeptAccess(String deptAccess) {
		this.deptAccess = deptAccess;
	}

	@Column(name = "role_access", length = 20)
	public String getRoleAccess() {
		return this.roleAccess;
	}

	public void setRoleAccess(String roleAccess) {
		this.roleAccess = roleAccess;
	}

	@Column(name = "user_access", length = 20)
	public String getUserAccess() {
		return this.userAccess;
	}

	public void setUserAccess(String userAccess) {
		this.userAccess = userAccess;
	}

	@Column(name = "doc_access", length = 20)
	public String getDocAccess() {
		return this.docAccess;
	}

	public void setDocAccess(String docAccess) {
		this.docAccess = docAccess;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emrAccessRule")
	public Set getEmrAccessRuleModelDetailses() {
		return this.emrAccessRuleDetailses;
	}

	public void setEmrAccessRuleModelDetailses(Set emrAccessRuleDetailses) {
		this.emrAccessRuleDetailses = emrAccessRuleDetailses;
	}

}
