package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstimateHeaderIdSequence generated by hbm2java
 */
@Embeddable
public class EstimateHeaderIdSequence implements java.io.Serializable {

	private String estimateId;
	private String userId;
	private String organizationId;
	private String bedType;
	private Date updatedDate;

	public EstimateHeaderIdSequence() {
	}

	public EstimateHeaderIdSequence(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public EstimateHeaderIdSequence(String estimateId, String userId, String organizationId, String bedType, Date updatedDate) {
		this.estimateId = estimateId;
		this.userId = userId;
		this.organizationId = organizationId;
		this.bedType = bedType;
		this.updatedDate = updatedDate;
	}

	@Column(name = "estimate_id", length = 15)
	public String getEstimateId() {
		return this.estimateId;
	}

	public void setEstimateId(String estimateId) {
		this.estimateId = estimateId;
	}

	@Column(name = "user_id", length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "organization_id", length = 10)
	public String getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "bed_type", length = 50)
	public String getBedType() {
		return this.bedType;
	}

	public void setBedType(String bedType) {
		this.bedType = bedType;
	}

	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstimateHeaderIdSequence))
			return false;
		EstimateHeaderIdSequence castOther = (EstimateHeaderIdSequence) other;

		return ((this.getEstimateId() == castOther.getEstimateId()) || (this.getEstimateId() != null
				&& castOther.getEstimateId() != null && this.getEstimateId().equals(castOther.getEstimateId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getOrganizationId() == castOther.getOrganizationId())
						|| (this.getOrganizationId() != null && castOther.getOrganizationId() != null
								&& this.getOrganizationId().equals(castOther.getOrganizationId())))
				&& ((this.getBedType() == castOther.getBedType()) || (this.getBedType() != null
						&& castOther.getBedType() != null && this.getBedType().equals(castOther.getBedType())))
				&& ((this.getUpdatedDate() == castOther.getUpdatedDate())
						|| (this.getUpdatedDate() != null && castOther.getUpdatedDate() != null
								&& this.getUpdatedDate().equals(castOther.getUpdatedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEstimateId() == null ? 0 : this.getEstimateId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getOrganizationId() == null ? 0 : this.getOrganizationId().hashCode());
		result = 37 * result + (getBedType() == null ? 0 : this.getBedType().hashCode());
		result = 37 * result + (getUpdatedDate() == null ? 0 : this.getUpdatedDate().hashCode());
		return result;
	}

}
