package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstimateChargeModel generated by hbm2java
 */
@Entity
@Table(name = "estimate_charge")
public class EstimateChargeModel implements java.io.Serializable {

	private int chargeId;
	private int estimateNo;
	private String chargeGroup;
	private String chargeHead;
	private String actDepartmentId;
	private String actDescription;
	private String actRemarks;
	private BigDecimal actRate;
	private String actUnit;
	private BigDecimal actQuantity;
	private BigDecimal amount;
	private BigDecimal taxAmt;
	private String chargeRef;
	private char status;
	private String username;
	private Date modTime;
	private BigDecimal origRate;
	private String actDescriptionId;
	private Boolean hasactivity;
	private BigDecimal discount;
	private BigDecimal sponsorAmt;
	private BigDecimal sponsorTax;
	private BigDecimal patientAmt;
	private BigDecimal patientTax;
	private String remarks;

	public EstimateChargeModel() {
	}

	public EstimateChargeModel(int chargeId, int estimateNo, String chargeGroup, String chargeHead, BigDecimal amount,
			char status, Date modTime, BigDecimal origRate) {
		this.chargeId = chargeId;
		this.estimateNo = estimateNo;
		this.chargeGroup = chargeGroup;
		this.chargeHead = chargeHead;
		this.amount = amount;
		this.status = status;
		this.modTime = modTime;
		this.origRate = origRate;
	}

	public EstimateChargeModel(int chargeId, int estimateNo, String chargeGroup, String chargeHead, String actDepartmentId,
			String actDescription, String actRemarks, BigDecimal actRate, String actUnit, BigDecimal actQuantity,
			BigDecimal amount, String chargeRef, char status, String username, Date modTime, BigDecimal origRate,
			String actDescriptionId, Boolean hasactivity, BigDecimal discount, BigDecimal sponsorAmt,
			BigDecimal patientAmt, String remarks) {
		this.chargeId = chargeId;
		this.estimateNo = estimateNo;
		this.chargeGroup = chargeGroup;
		this.chargeHead = chargeHead;
		this.actDepartmentId = actDepartmentId;
		this.actDescription = actDescription;
		this.actRemarks = actRemarks;
		this.actRate = actRate;
		this.actUnit = actUnit;
		this.actQuantity = actQuantity;
		this.amount = amount;
		this.chargeRef = chargeRef;
		this.status = status;
		this.username = username;
		this.modTime = modTime;
		this.origRate = origRate;
		this.actDescriptionId = actDescriptionId;
		this.hasactivity = hasactivity;
		this.discount = discount;
		this.sponsorAmt = sponsorAmt;
		this.patientAmt = patientAmt;
		this.remarks = remarks;
	}

	@Id

	@Column(name = "charge_id", unique = true, nullable = false)
	public int getChargeId() {
		return this.chargeId;
	}

	public void setChargeId(int chargeId) {
		this.chargeId = chargeId;
	}

	@Column(name = "estimate_no", nullable = false)
	public int getEstimateNo() {
		return this.estimateNo;
	}

	public void setEstimateNo(int estimateNo) {
		this.estimateNo = estimateNo;
	}

	@Column(name = "charge_group", nullable = false, length = 40)
	public String getChargeGroup() {
		return this.chargeGroup;
	}

	public void setChargeGroup(String chargeGroup) {
		this.chargeGroup = chargeGroup;
	}

	@Column(name = "charge_head", nullable = false, length = 20)
	public String getChargeHead() {
		return this.chargeHead;
	}

	public void setChargeHead(String chargeHead) {
		this.chargeHead = chargeHead;
	}

	@Column(name = "act_department_id", length = 30)
	public String getActDepartmentId() {
		return this.actDepartmentId;
	}

	public void setActDepartmentId(String actDepartmentId) {
		this.actDepartmentId = actDepartmentId;
	}

	@Column(name = "act_description")
	public String getActDescription() {
		return this.actDescription;
	}

	public void setActDescription(String actDescription) {
		this.actDescription = actDescription;
	}

	@Column(name = "act_remarks")
	public String getActRemarks() {
		return this.actRemarks;
	}

	public void setActRemarks(String actRemarks) {
		this.actRemarks = actRemarks;
	}

	@Column(name = "act_rate", precision = 15)
	public BigDecimal getActRate() {
		return this.actRate;
	}

	public void setActRate(BigDecimal actRate) {
		this.actRate = actRate;
	}

	@Column(name = "act_unit", length = 10)
	public String getActUnit() {
		return this.actUnit;
	}

	public void setActUnit(String actUnit) {
		this.actUnit = actUnit;
	}

	@Column(name = "act_quantity", precision = 131089, scale = 0)
	public BigDecimal getActQuantity() {
		return this.actQuantity;
	}

	public void setActQuantity(BigDecimal actQuantity) {
		this.actQuantity = actQuantity;
	}

	@Column(name = "amount", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "tax_amt", nullable = false, precision = 15)
	public BigDecimal getTaxAmt() {
		return this.taxAmt;
	}

	public void setTaxAmt(BigDecimal taxAmt) {
		this.taxAmt = taxAmt;
	}

	@Column(name = "charge_ref", length = 15)
	public String getChargeRef() {
		return this.chargeRef;
	}

	public void setChargeRef(String chargeRef) {
		this.chargeRef = chargeRef;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", nullable = false, length = 35)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "orig_rate", nullable = false, precision = 15)
	public BigDecimal getOrigRate() {
		return this.origRate;
	}

	public void setOrigRate(BigDecimal origRate) {
		this.origRate = origRate;
	}

	@Column(name = "act_description_id", length = 50)
	public String getActDescriptionId() {
		return this.actDescriptionId;
	}

	public void setActDescriptionId(String actDescriptionId) {
		this.actDescriptionId = actDescriptionId;
	}

	@Column(name = "hasactivity")
	public Boolean getHasactivity() {
		return this.hasactivity;
	}

	public void setHasactivity(Boolean hasactivity) {
		this.hasactivity = hasactivity;
	}

	@Column(name = "discount", precision = 131089, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "sponsor_amt", precision = 131089, scale = 0)
	public BigDecimal getSponsorAmt() {
		return this.sponsorAmt;
	}

	public void setSponsorAmt(BigDecimal sponsorAmt) {
		this.sponsorAmt = sponsorAmt;
	}

	@Column(name = "sponsor_tax", precision = 131089, scale = 0)
	public BigDecimal getSponsorTax() {
		return this.sponsorTax;
	}

	public void setSponsorTax(BigDecimal sponsorTax) {
		this.sponsorTax = sponsorTax;
	}

	@Column(name = "patient_amt", precision = 131089, scale = 0)
	public BigDecimal getPatientAmt() {
		return this.patientAmt;
	}

	public void setPatientAmt(BigDecimal patientAmt) {
		this.patientAmt = patientAmt;
	}

	@Column(name = "patient_tax", precision = 131089, scale = 0)
	public BigDecimal getPatientTax() {
		return this.patientTax;
	}

	public void setPatientTax(BigDecimal patientTax) {
		this.patientTax = patientTax;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
