package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EstimateHeaderModel generated by hbm2java
 */
@Entity
@Table(name = "estimate_header")
public class EstimateHeaderModel implements java.io.Serializable {

	private EstimateHeaderIdSequence id;

	public EstimateHeaderModel() {
	}

	public EstimateHeaderModel(EstimateHeaderIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "estimateId", column = @Column(name = "estimate_id", length = 15)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", length = 30)),
			@AttributeOverride(name = "organizationId", column = @Column(name = "organization_id", length = 10)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", length = 50)),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "updated_date", nullable = false, length = 29)) })
	public EstimateHeaderIdSequence getId() {
		return this.id;
	}

	public void setId(EstimateHeaderIdSequence id) {
		this.id = id;
	}

}
