package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventLogModel generated by hbm2java
 */
@Entity
@Table(name = "event_log")
public class EventLogModel implements java.io.Serializable {

	private int eventId;
	private Date createdAt;
	private String entityId;
	private String remarks;
	private String eventType;
	private String userId;
	private String status;
	private String schemaName;

	public EventLogModel() {
	}

	public EventLogModel(int eventId, Date createdAt, String entityId, String userId, String status, String schemaName) {
		this.eventId = eventId;
		this.createdAt = createdAt;
		this.entityId = entityId;
		this.userId = userId;
		this.status = status;
		this.schemaName = schemaName;
	}

	public EventLogModel(int eventId, Date createdAt, String entityId, String remarks, String eventType, String userId,
			String status, String schemaName) {
		this.eventId = eventId;
		this.createdAt = createdAt;
		this.entityId = entityId;
		this.remarks = remarks;
		this.eventType = eventType;
		this.userId = userId;
		this.status = status;
		this.schemaName = schemaName;
	}

	@Id

	@Column(name = "event_id", unique = true, nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "entity_id", nullable = false, length = 50)
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "event_type", length = 50)
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@Column(name = "user_id", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "status", nullable = false, length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "schema_name", nullable = false, length = 50)
	public String getSchemaName() {
		return this.schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

}
