package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EyeTestMasterModel generated by hbm2java
 */
@Entity
@Table(name = "eye_test_master")
public class EyeTestMasterModel implements java.io.Serializable {

	private int testId;
	private String testName;
	private Character testStatus;
	private Set opthalTestAttributeses = new HashSet(0);
	private Set opthalTestDetailses = new HashSet(0);

	public EyeTestMasterModel() {
	}

	public EyeTestMasterModel(int testId, String testName) {
		this.testId = testId;
		this.testName = testName;
	}

	public EyeTestMasterModel(int testId, String testName, Character testStatus, Set opthalTestAttributeses,
			Set opthalTestDetailses) {
		this.testId = testId;
		this.testName = testName;
		this.testStatus = testStatus;
		this.opthalTestAttributeses = opthalTestAttributeses;
		this.opthalTestDetailses = opthalTestDetailses;
	}

	@Id

	@Column(name = "test_id", unique = true, nullable = false)
	public int getTestId() {
		return this.testId;
	}

	public void setTestId(int testId) {
		this.testId = testId;
	}

	@Column(name = "test_name", nullable = false, length = 200)
	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	@Column(name = "test_status", length = 1)
	public Character getTestStatus() {
		return this.testStatus;
	}

	public void setTestStatus(Character testStatus) {
		this.testStatus = testStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eyeTestMaster")
	public Set getOpthalTestAttributeses() {
		return this.opthalTestAttributeses;
	}

	public void setOpthalTestAttributeses(Set opthalTestAttributeses) {
		this.opthalTestAttributeses = opthalTestAttributeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eyeTestMaster")
	public Set getOpthalTestDetailses() {
		return this.opthalTestDetailses;
	}

	public void setOpthalTestDetailses(Set opthalTestDetailses) {
		this.opthalTestDetailses = opthalTestDetailses;
	}

}
