package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FavouriteReportsModel generated by hbm2java
 */
@Entity
@Table(name = "favourite_reports")
public class FavouriteReportsModel implements java.io.Serializable {

	private int reportId;
	private String reportTitle;
	private String actionId;
	private String userName;
	private String queryParams;
	private String parentReportName;
	private Date createdDate;
	private String customReportName;
	private String reportDescSrxml;
	private Character frequentlyViewed;
	private String reportGroup;
	private Boolean allowDateChange;

	public FavouriteReportsModel() {
	}

	public FavouriteReportsModel(int reportId, String reportTitle, String actionId, String userName, String reportGroup) {
		this.reportId = reportId;
		this.reportTitle = reportTitle;
		this.actionId = actionId;
		this.userName = userName;
		this.reportGroup = reportGroup;
	}

	public FavouriteReportsModel(int reportId, String reportTitle, String actionId, String userName, String queryParams,
			String parentReportName, Date createdDate, String customReportName, String reportDescSrxml,
			Character frequentlyViewed, String reportGroup, Boolean allowDateChange) {
		this.reportId = reportId;
		this.reportTitle = reportTitle;
		this.actionId = actionId;
		this.userName = userName;
		this.queryParams = queryParams;
		this.parentReportName = parentReportName;
		this.createdDate = createdDate;
		this.customReportName = customReportName;
		this.reportDescSrxml = reportDescSrxml;
		this.frequentlyViewed = frequentlyViewed;
		this.reportGroup = reportGroup;
		this.allowDateChange = allowDateChange;
	}

	@Id

	@Column(name = "report_id", unique = true, nullable = false)
	public int getReportId() {
		return this.reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	@Column(name = "report_title", nullable = false, length = 100)
	public String getReportTitle() {
		return this.reportTitle;
	}

	public void setReportTitle(String reportTitle) {
		this.reportTitle = reportTitle;
	}

	@Column(name = "action_id", nullable = false)
	public String getActionId() {
		return this.actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	@Column(name = "user_name", nullable = false, length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "query_params")
	public String getQueryParams() {
		return this.queryParams;
	}

	public void setQueryParams(String queryParams) {
		this.queryParams = queryParams;
	}

	@Column(name = "parent_report_name")
	public String getParentReportName() {
		return this.parentReportName;
	}

	public void setParentReportName(String parentReportName) {
		this.parentReportName = parentReportName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 13)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "custom_report_name")
	public String getCustomReportName() {
		return this.customReportName;
	}

	public void setCustomReportName(String customReportName) {
		this.customReportName = customReportName;
	}

	@Column(name = "report_desc_srxml")
	public String getReportDescSrxml() {
		return this.reportDescSrxml;
	}

	public void setReportDescSrxml(String reportDescSrxml) {
		this.reportDescSrxml = reportDescSrxml;
	}

	@Column(name = "frequently_viewed", length = 1)
	public Character getFrequentlyViewed() {
		return this.frequentlyViewed;
	}

	public void setFrequentlyViewed(Character frequentlyViewed) {
		this.frequentlyViewed = frequentlyViewed;
	}

	@Column(name = "report_group", nullable = false, length = 100)
	public String getReportGroup() {
		return this.reportGroup;
	}

	public void setReportGroup(String reportGroup) {
		this.reportGroup = reportGroup;
	}

	@Column(name = "allow_date_change")
	public Boolean getAllowDateChange() {
		return this.allowDateChange;
	}

	public void setAllowDateChange(Boolean allowDateChange) {
		this.allowDateChange = allowDateChange;
	}

}
