package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavouriteReportRightsIdSequence generated by hbm2java
 */
@Embeddable
public class FavouriteReportRightsIdSequence implements java.io.Serializable {

	private int roleId;
	private int favouriteReportId;

	public FavouriteReportRightsIdSequence() {
	}

	public FavouriteReportRightsIdSequence(int roleId, int favouriteReportId) {
		this.roleId = roleId;
		this.favouriteReportId = favouriteReportId;
	}

	@Column(name = "role_id", nullable = false, precision = 5, scale = 0)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "favourite_report_id", nullable = false)
	public int getFavouriteReportId() {
		return this.favouriteReportId;
	}

	public void setFavouriteReportId(int favouriteReportId) {
		this.favouriteReportId = favouriteReportId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavouriteReportRightsIdSequence))
			return false;
		FavouriteReportRightsIdSequence castOther = (FavouriteReportRightsIdSequence) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getFavouriteReportId() == castOther.getFavouriteReportId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getFavouriteReportId();
		return result;
	}

}
