package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FixedAssetMasterModel generated by hbm2java
 */
@Entity
@Table(name = "fixed_asset_master")
public class FixedAssetMasterModel implements java.io.Serializable {

	private int assetSeq;
	private int assetId;
	private String assetMake;
	private String assetModel;
	private BigDecimal assetPurchaseVal;
	private Date installationDate;
	private Integer parentAssetId;
	private String assetGenericName;
	private String assetBillNo;
	private Integer assetLocationId;
	private int assetDept;
	private String assetSerialNo;
	private String assetRemarks;
	private String assetStatus;
	private Set fixedAssetUploadses = new HashSet(0);

	public FixedAssetMasterModel() {
	}

	public FixedAssetMasterModel(int assetSeq, int assetId, int assetDept, String assetSerialNo) {
		this.assetSeq = assetSeq;
		this.assetId = assetId;
		this.assetDept = assetDept;
		this.assetSerialNo = assetSerialNo;
	}

	public FixedAssetMasterModel(int assetSeq, int assetId, String assetMake, String assetModel, BigDecimal assetPurchaseVal,
			Date installationDate, Integer parentAssetId, String assetGenericName, String assetBillNo,
			Integer assetLocationId, int assetDept, String assetSerialNo, String assetRemarks, String assetStatus,
			Set fixedAssetUploadses) {
		this.assetSeq = assetSeq;
		this.assetId = assetId;
		this.assetMake = assetMake;
		this.assetModel = assetModel;
		this.assetPurchaseVal = assetPurchaseVal;
		this.installationDate = installationDate;
		this.parentAssetId = parentAssetId;
		this.assetGenericName = assetGenericName;
		this.assetBillNo = assetBillNo;
		this.assetLocationId = assetLocationId;
		this.assetDept = assetDept;
		this.assetSerialNo = assetSerialNo;
		this.assetRemarks = assetRemarks;
		this.assetStatus = assetStatus;
		this.fixedAssetUploadses = fixedAssetUploadses;
	}

	@Id

	@Column(name = "asset_seq", unique = true, nullable = false)
	public int getAssetSeq() {
		return this.assetSeq;
	}

	public void setAssetSeq(int assetSeq) {
		this.assetSeq = assetSeq;
	}

	@Column(name = "asset_id", nullable = false)
	public int getAssetId() {
		return this.assetId;
	}

	public void setAssetId(int assetId) {
		this.assetId = assetId;
	}

	@Column(name = "asset_make")
	public String getAssetMake() {
		return this.assetMake;
	}

	public void setAssetMake(String assetMake) {
		this.assetMake = assetMake;
	}

	@Column(name = "asset_model")
	public String getAssetModel() {
		return this.assetModel;
	}

	public void setAssetModel(String assetModel) {
		this.assetModel = assetModel;
	}

	@Column(name = "asset_purchase_val", precision = 131089, scale = 0)
	public BigDecimal getAssetPurchaseVal() {
		return this.assetPurchaseVal;
	}

	public void setAssetPurchaseVal(BigDecimal assetPurchaseVal) {
		this.assetPurchaseVal = assetPurchaseVal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "installation_date", length = 13)
	public Date getInstallationDate() {
		return this.installationDate;
	}

	public void setInstallationDate(Date installationDate) {
		this.installationDate = installationDate;
	}

	@Column(name = "parent_asset_id")
	public Integer getParentAssetId() {
		return this.parentAssetId;
	}

	public void setParentAssetId(Integer parentAssetId) {
		this.parentAssetId = parentAssetId;
	}

	@Column(name = "asset_generic_name")
	public String getAssetGenericName() {
		return this.assetGenericName;
	}

	public void setAssetGenericName(String assetGenericName) {
		this.assetGenericName = assetGenericName;
	}

	@Column(name = "asset_bill_no")
	public String getAssetBillNo() {
		return this.assetBillNo;
	}

	public void setAssetBillNo(String assetBillNo) {
		this.assetBillNo = assetBillNo;
	}

	@Column(name = "asset_location_id")
	public Integer getAssetLocationId() {
		return this.assetLocationId;
	}

	public void setAssetLocationId(Integer assetLocationId) {
		this.assetLocationId = assetLocationId;
	}

	@Column(name = "asset_dept", nullable = false)
	public int getAssetDept() {
		return this.assetDept;
	}

	public void setAssetDept(int assetDept) {
		this.assetDept = assetDept;
	}

	@Column(name = "asset_serial_no", nullable = false)
	public String getAssetSerialNo() {
		return this.assetSerialNo;
	}

	public void setAssetSerialNo(String assetSerialNo) {
		this.assetSerialNo = assetSerialNo;
	}

	@Column(name = "asset_remarks")
	public String getAssetRemarks() {
		return this.assetRemarks;
	}

	public void setAssetRemarks(String assetRemarks) {
		this.assetRemarks = assetRemarks;
	}

	@Column(name = "asset_status")
	public String getAssetStatus() {
		return this.assetStatus;
	}

	public void setAssetStatus(String assetStatus) {
		this.assetStatus = assetStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fixedAssetMaster")
	public Set getFixedAssetUploadses() {
		return this.fixedAssetUploadses;
	}

	public void setFixedAssetUploadses(Set fixedAssetUploadses) {
		this.fixedAssetUploadses = fixedAssetUploadses;
	}

}
