package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ForeignCurrencyModel generated by hbm2java
 */
@Entity
@Table(name = "foreign_currency")
public class ForeignCurrencyModel implements java.io.Serializable {

	private int currencyId;
	private String currency;
	private BigDecimal conversionRate;
	private Date modTime;
	private String username;
	private Character status;

	public ForeignCurrencyModel() {
	}

	public ForeignCurrencyModel(int currencyId) {
		this.currencyId = currencyId;
	}

	public ForeignCurrencyModel(int currencyId, String currency, BigDecimal conversionRate, Date modTime, String username,
			Character status) {
		this.currencyId = currencyId;
		this.currency = currency;
		this.conversionRate = conversionRate;
		this.modTime = modTime;
		this.username = username;
		this.status = status;
	}

	@Id

	@Column(name = "currency_id", unique = true, nullable = false)
	public int getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(int currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "currency", length = 300)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "conversion_rate", precision = 131089, scale = 0)
	public BigDecimal getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(BigDecimal conversionRate) {
		this.conversionRate = conversionRate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

}
