package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GeneralReagentUsageDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "general_reagent_usage_details")
public class GeneralReagentUsageDetailsModel implements java.io.Serializable {

	private int reagentDetailId;
	private String consumptionId;
	private BigDecimal stockQty;
	private BigDecimal qty;
	private Integer itemBatchId;

	public GeneralReagentUsageDetailsModel() {
	}

	public GeneralReagentUsageDetailsModel(int reagentDetailId, String consumptionId) {
		this.reagentDetailId = reagentDetailId;
		this.consumptionId = consumptionId;
	}

	public GeneralReagentUsageDetailsModel(int reagentDetailId, String consumptionId, BigDecimal stockQty, BigDecimal qty,
			Integer itemBatchId) {
		this.reagentDetailId = reagentDetailId;
		this.consumptionId = consumptionId;
		this.stockQty = stockQty;
		this.qty = qty;
		this.itemBatchId = itemBatchId;
	}

	@Id

	@Column(name = "reagent_detail_id", unique = true, nullable = false)
	public int getReagentDetailId() {
		return this.reagentDetailId;
	}

	public void setReagentDetailId(int reagentDetailId) {
		this.reagentDetailId = reagentDetailId;
	}

	@Column(name = "consumption_id", nullable = false, length = 10)
	public String getConsumptionId() {
		return this.consumptionId;
	}

	public void setConsumptionId(String consumptionId) {
		this.consumptionId = consumptionId;
	}

	@Column(name = "stock_qty", precision = 10)
	public BigDecimal getStockQty() {
		return this.stockQty;
	}

	public void setStockQty(BigDecimal stockQty) {
		this.stockQty = stockQty;
	}

	@Column(name = "qty", precision = 10)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "item_batch_id")
	public Integer getItemBatchId() {
		return this.itemBatchId;
	}

	public void setItemBatchId(Integer itemBatchId) {
		this.itemBatchId = itemBatchId;
	}

}
