package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GrowthChartReferenceDataModel generated by hbm2java
 */
@Entity
@Table(name = "growth_chart_reference_data")
public class GrowthChartReferenceDataModel implements java.io.Serializable {

	private String id;
	private String sex;
	private Long year;
	private Long month;
	private String l;
	private String m;
	private String s;
	private String sd;
	private String length;
	private String stature;
	private String per1;
	private String per3;
	private String per5;
	private String per15;
	private String per25;
	private String per50;
	private String per75;
	private String per85;
	private String per95;
	private String per97;
	private String per99;
	private String chartType;
	private String per10;
	private String per90;

	public GrowthChartReferenceDataModel() {
	}

	public GrowthChartReferenceDataModel(String id, String sex) {
		this.id = id;
		this.sex = sex;
	}

	public GrowthChartReferenceDataModel(String id, String sex, Long year, Long month, String l, String m, String s,
			String sd, String length, String stature, String per1, String per3, String per5, String per15, String per25,
			String per50, String per75, String per85, String per95, String per97, String per99, String chartType,
			String per10, String per90) {
		this.id = id;
		this.sex = sex;
		this.year = year;
		this.month = month;
		this.l = l;
		this.m = m;
		this.s = s;
		this.sd = sd;
		this.length = length;
		this.stature = stature;
		this.per1 = per1;
		this.per3 = per3;
		this.per5 = per5;
		this.per15 = per15;
		this.per25 = per25;
		this.per50 = per50;
		this.per75 = per75;
		this.per85 = per85;
		this.per95 = per95;
		this.per97 = per97;
		this.per99 = per99;
		this.chartType = chartType;
		this.per10 = per10;
		this.per90 = per90;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "sex", nullable = false)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "year", precision = 10, scale = 0)
	public Long getYear() {
		return this.year;
	}

	public void setYear(Long year) {
		this.year = year;
	}

	@Column(name = "month", precision = 10, scale = 0)
	public Long getMonth() {
		return this.month;
	}

	public void setMonth(Long month) {
		this.month = month;
	}

	@Column(name = "l")
	public String getL() {
		return this.l;
	}

	public void setL(String l) {
		this.l = l;
	}

	@Column(name = "m")
	public String getM() {
		return this.m;
	}

	public void setM(String m) {
		this.m = m;
	}

	@Column(name = "s")
	public String getS() {
		return this.s;
	}

	public void setS(String s) {
		this.s = s;
	}

	@Column(name = "sd")
	public String getSd() {
		return this.sd;
	}

	public void setSd(String sd) {
		this.sd = sd;
	}

	@Column(name = "length")
	public String getLength() {
		return this.length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	@Column(name = "stature")
	public String getStature() {
		return this.stature;
	}

	public void setStature(String stature) {
		this.stature = stature;
	}

	@Column(name = "per_1")
	public String getPer1() {
		return this.per1;
	}

	public void setPer1(String per1) {
		this.per1 = per1;
	}

	@Column(name = "per_3")
	public String getPer3() {
		return this.per3;
	}

	public void setPer3(String per3) {
		this.per3 = per3;
	}

	@Column(name = "per_5")
	public String getPer5() {
		return this.per5;
	}

	public void setPer5(String per5) {
		this.per5 = per5;
	}

	@Column(name = "per_15")
	public String getPer15() {
		return this.per15;
	}

	public void setPer15(String per15) {
		this.per15 = per15;
	}

	@Column(name = "per_25")
	public String getPer25() {
		return this.per25;
	}

	public void setPer25(String per25) {
		this.per25 = per25;
	}

	@Column(name = "per_50")
	public String getPer50() {
		return this.per50;
	}

	public void setPer50(String per50) {
		this.per50 = per50;
	}

	@Column(name = "per_75")
	public String getPer75() {
		return this.per75;
	}

	public void setPer75(String per75) {
		this.per75 = per75;
	}

	@Column(name = "per_85")
	public String getPer85() {
		return this.per85;
	}

	public void setPer85(String per85) {
		this.per85 = per85;
	}

	@Column(name = "per_95")
	public String getPer95() {
		return this.per95;
	}

	public void setPer95(String per95) {
		this.per95 = per95;
	}

	@Column(name = "per_97")
	public String getPer97() {
		return this.per97;
	}

	public void setPer97(String per97) {
		this.per97 = per97;
	}

	@Column(name = "per_99")
	public String getPer99() {
		return this.per99;
	}

	public void setPer99(String per99) {
		this.per99 = per99;
	}

	@Column(name = "chart_type")
	public String getChartType() {
		return this.chartType;
	}

	public void setChartType(String chartType) {
		this.chartType = chartType;
	}

	@Column(name = "per_10")
	public String getPer10() {
		return this.per10;
	}

	public void setPer10(String per10) {
		this.per10 = per10;
	}

	@Column(name = "per_90")
	public String getPer90() {
		return this.per90;
	}

	public void setPer90(String per90) {
		this.per90 = per90;
	}

}
