package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Hl7OrderItemsModel generated by hbm2java
 */
@Entity
@Table(name = "hl7_order_items")
public class Hl7OrderItemsModel implements java.io.Serializable {

	private Hl7OrderItemsIdSequence id;

	public Hl7OrderItemsModel() {
	}

	public Hl7OrderItemsModel(Hl7OrderItemsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemType", column = @Column(name = "item_type")),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id")),
			@AttributeOverride(name = "insertedTs", column = @Column(name = "inserted_ts", length = 29)),
			@AttributeOverride(name = "exportedTs", column = @Column(name = "exported_ts", length = 29)),
			@AttributeOverride(name = "exportId", column = @Column(name = "export_id")),
			@AttributeOverride(name = "interfaceName", column = @Column(name = "interface_name")),
			@AttributeOverride(name = "exportStatus", column = @Column(name = "export_status", length = 1)),
			@AttributeOverride(name = "exportMsgId", column = @Column(name = "export_msg_id")),
			@AttributeOverride(name = "exportFailureMsg", column = @Column(name = "export_failure_msg")),
			@AttributeOverride(name = "billPaid", column = @Column(name = "bill_paid", length = 1)),
			@AttributeOverride(name = "opCode", column = @Column(name = "op_code", length = 1)),
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", length = 15)),
			@AttributeOverride(name = "prescribedId", column = @Column(name = "prescribed_id")),
			@AttributeOverride(name = "testName", column = @Column(name = "test_name", length = 600)),
			@AttributeOverride(name = "hl7ExportCode", column = @Column(name = "hl7_export_code")),
			@AttributeOverride(name = "testId", column = @Column(name = "test_id", length = 50)),
			@AttributeOverride(name = "presDate", column = @Column(name = "pres_date")),
			@AttributeOverride(name = "commonOrderId", column = @Column(name = "common_order_id")),
			@AttributeOverride(name = "scheduledTimeStart", column = @Column(name = "scheduled_time_start")),
			@AttributeOverride(name = "startDateTime", column = @Column(name = "start_date_time")),
			@AttributeOverride(name = "scheduledTimeEnd", column = @Column(name = "scheduled_time_end")),
			@AttributeOverride(name = "equipmentCode", column = @Column(name = "equipment_code")),
			@AttributeOverride(name = "sampleSno", column = @Column(name = "sample_sno", length = 30)),
			@AttributeOverride(name = "sampleDate", column = @Column(name = "sample_date")),
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", length = 15)),
			@AttributeOverride(name = "oldmrno", column = @Column(name = "oldmrno", length = 20)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name")),
			@AttributeOverride(name = "patientName", column = @Column(name = "patient_name")),
			@AttributeOverride(name = "salutation", column = @Column(name = "salutation", length = 50)),
			@AttributeOverride(name = "patientGender", column = @Column(name = "patient_gender")),
			@AttributeOverride(name = "expectedDob", column = @Column(name = "expected_dob")),
			@AttributeOverride(name = "patientAddress", column = @Column(name = "patient_address")),
			@AttributeOverride(name = "cityname", column = @Column(name = "cityname")),
			@AttributeOverride(name = "cityCode", column = @Column(name = "city_code")),
			@AttributeOverride(name = "statename", column = @Column(name = "statename")),
			@AttributeOverride(name = "stateCode", column = @Column(name = "state_code")),
			@AttributeOverride(name = "countryName", column = @Column(name = "country_name")),
			@AttributeOverride(name = "countryCode", column = @Column(name = "country_code")),
			@AttributeOverride(name = "patientPhone", column = @Column(name = "patient_phone", length = 16)),
			@AttributeOverride(name = "regDate", column = @Column(name = "reg_date")),
			@AttributeOverride(name = "doctor", column = @Column(name = "doctor", length = 30)),
			@AttributeOverride(name = "doctorName", column = @Column(name = "doctor_name")),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", length = 50)),
			@AttributeOverride(name = "wardName", column = @Column(name = "ward_name", length = 100)),
			@AttributeOverride(name = "referenceDoctoId", column = @Column(name = "reference_docto_id", length = 10)),
			@AttributeOverride(name = "diagnosisCode", column = @Column(name = "diagnosis_code", length = 100)),
			@AttributeOverride(name = "diagnosis", column = @Column(name = "diagnosis")),
			@AttributeOverride(name = "visitType", column = @Column(name = "visit_type", length = 1)),
			@AttributeOverride(name = "refdoctorname", column = @Column(name = "refdoctorname")),
			@AttributeOverride(name = "conductionFormat", column = @Column(name = "conduction_format", length = 1)),
			@AttributeOverride(name = "resultlabelId", column = @Column(name = "resultlabel_id")),
			@AttributeOverride(name = "resultlabel", column = @Column(name = "resultlabel", length = 100)),
			@AttributeOverride(name = "centerId", column = @Column(name = "center_id")),
			@AttributeOverride(name = "centerName", column = @Column(name = "center_name", length = 100)),
			@AttributeOverride(name = "conductingDoctorId", column = @Column(name = "conducting_doctor_id", length = 20)),
			@AttributeOverride(name = "conductingDoctorName", column = @Column(name = "conducting_doctor_name", length = 100)),
			@AttributeOverride(name = "prescriptionDoctorId", column = @Column(name = "prescription_doctor_id", length = 20)),
			@AttributeOverride(name = "prescriptionDoctorName", column = @Column(name = "prescription_doctor_name", length = 100)),
			@AttributeOverride(name = "prescriptionDepartment", column = @Column(name = "prescription_department", length = 100)),
			@AttributeOverride(name = "receivedStatus", column = @Column(name = "received_status")),
			@AttributeOverride(name = "outHouseSample", column = @Column(name = "out_house_sample")),
			@AttributeOverride(name = "middleName", column = @Column(name = "middle_name", length = 200)) })
	public Hl7OrderItemsIdSequence getId() {
		return this.id;
	}

	public void setId(Hl7OrderItemsIdSequence id) {
		this.id = id;
	}

}
