package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hl7PatientDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "hl7_patient_details")
public class Hl7PatientDetailsModel implements java.io.Serializable {

	private int hl7PatientDetailsId;
	private String mrNo;
	private String oldmrno;
	private String lastName;
	private String patientName;
	private String middleName;
	private String salutation;
	private String patientGender;
	private String expectedDob;
	private String patientAddress;
	private String cityname;
	private String cityCode;
	private String statename;
	private String stateCode;
	private String countryName;
	private String countryCode;
	private String patientPhone;
	private Date insertedTs;
	private Date exportedTs;
	private String emailId;
	private String patientDetailsStatus;

	public Hl7PatientDetailsModel() {
	}

	public Hl7PatientDetailsModel(int hl7PatientDetailsId) {
		this.hl7PatientDetailsId = hl7PatientDetailsId;
	}

	public Hl7PatientDetailsModel(int hl7PatientDetailsId, String mrNo, String oldmrno, String lastName, String patientName,
			String middleName, String salutation, String patientGender, String expectedDob, String patientAddress,
			String cityname, String cityCode, String statename, String stateCode, String countryName,
			String countryCode, String patientPhone, Date insertedTs, Date exportedTs, String emailId,
			String patientDetailsStatus) {
		this.hl7PatientDetailsId = hl7PatientDetailsId;
		this.mrNo = mrNo;
		this.oldmrno = oldmrno;
		this.lastName = lastName;
		this.patientName = patientName;
		this.middleName = middleName;
		this.salutation = salutation;
		this.patientGender = patientGender;
		this.expectedDob = expectedDob;
		this.patientAddress = patientAddress;
		this.cityname = cityname;
		this.cityCode = cityCode;
		this.statename = statename;
		this.stateCode = stateCode;
		this.countryName = countryName;
		this.countryCode = countryCode;
		this.patientPhone = patientPhone;
		this.insertedTs = insertedTs;
		this.exportedTs = exportedTs;
		this.emailId = emailId;
		this.patientDetailsStatus = patientDetailsStatus;
	}

	@Id

	@Column(name = "hl7_patient_details_id", unique = true, nullable = false)
	public int getHl7PatientDetailsIdSequence() {
		return this.hl7PatientDetailsId;
	}

	public void setHl7PatientDetailsIdSequence(int hl7PatientDetailsId) {
		this.hl7PatientDetailsId = hl7PatientDetailsId;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "oldmrno", length = 20)
	public String getOldmrno() {
		return this.oldmrno;
	}

	public void setOldmrno(String oldmrno) {
		this.oldmrno = oldmrno;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "patient_name")
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "middle_name", length = 200)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "salutation", length = 50)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "patient_gender")
	public String getPatientGender() {
		return this.patientGender;
	}

	public void setPatientGender(String patientGender) {
		this.patientGender = patientGender;
	}

	@Column(name = "expected_dob")
	public String getExpectedDob() {
		return this.expectedDob;
	}

	public void setExpectedDob(String expectedDob) {
		this.expectedDob = expectedDob;
	}

	@Column(name = "patient_address")
	public String getPatientAddress() {
		return this.patientAddress;
	}

	public void setPatientAddress(String patientAddress) {
		this.patientAddress = patientAddress;
	}

	@Column(name = "cityname")
	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	@Column(name = "city_code")
	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	@Column(name = "statename")
	public String getStatename() {
		return this.statename;
	}

	public void setStatename(String statename) {
		this.statename = statename;
	}

	@Column(name = "state_code")
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "country_name")
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "country_code")
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "patient_phone", length = 16)
	public String getPatientPhone() {
		return this.patientPhone;
	}

	public void setPatientPhone(String patientPhone) {
		this.patientPhone = patientPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inserted_ts", length = 29)
	public Date getInsertedTs() {
		return this.insertedTs;
	}

	public void setInsertedTs(Date insertedTs) {
		this.insertedTs = insertedTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exported_ts", length = 29)
	public Date getExportedTs() {
		return this.exportedTs;
	}

	public void setExportedTs(Date exportedTs) {
		this.exportedTs = exportedTs;
	}

	@Column(name = "email_id", length = 200)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "patient_details_status", length = 5)
	public String getPatientDetailsStatus() {
		return this.patientDetailsStatus;
	}

	public void setPatientDetailsStatus(String patientDetailsStatus) {
		this.patientDetailsStatus = patientDetailsStatus;
	}

}
