package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Hl7VisitDetailsIdSequence generated by hbm2java
 */
@Embeddable
public class Hl7VisitDetailsIdSequence implements java.io.Serializable {

	private String mrNo;
	private String originPatientId;
	private Date insertedTs;
	private Date exportedTs;
	private String tpaName;
	private String planName;
	private String employeeId;
	private String patientDetailsStatus;

	public Hl7VisitDetailsIdSequence() {
	}

	public Hl7VisitDetailsIdSequence(String mrNo, String originPatientId, Date insertedTs, Date exportedTs, String tpaName,
			String planName, String employeeId, String patientDetailsStatus) {
		this.mrNo = mrNo;
		this.originPatientId = originPatientId;
		this.insertedTs = insertedTs;
		this.exportedTs = exportedTs;
		this.tpaName = tpaName;
		this.planName = planName;
		this.employeeId = employeeId;
		this.patientDetailsStatus = patientDetailsStatus;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "origin_patient_id", length = 15)
	public String getOriginPatientId() {
		return this.originPatientId;
	}

	public void setOriginPatientId(String originPatientId) {
		this.originPatientId = originPatientId;
	}

	@Column(name = "inserted_ts", length = 29)
	public Date getInsertedTs() {
		return this.insertedTs;
	}

	public void setInsertedTs(Date insertedTs) {
		this.insertedTs = insertedTs;
	}

	@Column(name = "exported_ts", length = 29)
	public Date getExportedTs() {
		return this.exportedTs;
	}

	public void setExportedTs(Date exportedTs) {
		this.exportedTs = exportedTs;
	}

	@Column(name = "tpa_name", length = 200)
	public String getTpaName() {
		return this.tpaName;
	}

	public void setTpaName(String tpaName) {
		this.tpaName = tpaName;
	}

	@Column(name = "plan_name", length = 100)
	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	@Column(name = "employee_id", length = 40)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "patient_details_status", length = 5)
	public String getPatientDetailsStatus() {
		return this.patientDetailsStatus;
	}

	public void setPatientDetailsStatus(String patientDetailsStatus) {
		this.patientDetailsStatus = patientDetailsStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Hl7VisitDetailsIdSequence))
			return false;
		Hl7VisitDetailsIdSequence castOther = (Hl7VisitDetailsIdSequence) other;

		return ((this.getMrNo() == castOther.getMrNo()) || (this.getMrNo() != null && castOther.getMrNo() != null
				&& this.getMrNo().equals(castOther.getMrNo())))
				&& ((this.getOriginPatientId() == castOther.getOriginPatientId())
						|| (this.getOriginPatientId() != null && castOther.getOriginPatientId() != null
								&& this.getOriginPatientId().equals(castOther.getOriginPatientId())))
				&& ((this.getInsertedTs() == castOther.getInsertedTs()) || (this.getInsertedTs() != null
						&& castOther.getInsertedTs() != null && this.getInsertedTs().equals(castOther.getInsertedTs())))
				&& ((this.getExportedTs() == castOther.getExportedTs()) || (this.getExportedTs() != null
						&& castOther.getExportedTs() != null && this.getExportedTs().equals(castOther.getExportedTs())))
				&& ((this.getTpaName() == castOther.getTpaName()) || (this.getTpaName() != null
						&& castOther.getTpaName() != null && this.getTpaName().equals(castOther.getTpaName())))
				&& ((this.getPlanName() == castOther.getPlanName()) || (this.getPlanName() != null
						&& castOther.getPlanName() != null && this.getPlanName().equals(castOther.getPlanName())))
				&& ((this.getEmployeeId() == castOther.getEmployeeId()) || (this.getEmployeeId() != null
						&& castOther.getEmployeeId() != null && this.getEmployeeId().equals(castOther.getEmployeeId())))
				&& ((this.getPatientDetailsStatus() == castOther.getPatientDetailsStatus())
						|| (this.getPatientDetailsStatus() != null && castOther.getPatientDetailsStatus() != null
								&& this.getPatientDetailsStatus().equals(castOther.getPatientDetailsStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMrNo() == null ? 0 : this.getMrNo().hashCode());
		result = 37 * result + (getOriginPatientId() == null ? 0 : this.getOriginPatientId().hashCode());
		result = 37 * result + (getInsertedTs() == null ? 0 : this.getInsertedTs().hashCode());
		result = 37 * result + (getExportedTs() == null ? 0 : this.getExportedTs().hashCode());
		result = 37 * result + (getTpaName() == null ? 0 : this.getTpaName().hashCode());
		result = 37 * result + (getPlanName() == null ? 0 : this.getPlanName().hashCode());
		result = 37 * result + (getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode());
		result = 37 * result + (getPatientDetailsStatus() == null ? 0 : this.getPatientDetailsStatus().hashCode());
		return result;
	}

}
