package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HospGrnSeqPrefsModel generated by hbm2java
 */
@Entity
@Table(name = "hosp_grn_seq_prefs")
public class HospGrnSeqPrefsModel implements java.io.Serializable {

	private HospGrnSeqPrefsIdSequence id;

	public HospGrnSeqPrefsModel() {
	}

	public HospGrnSeqPrefsModel(HospGrnSeqPrefsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "priority", column = @Column(name = "priority", nullable = false)),
			@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false)),
			@AttributeOverride(name = "patternId", column = @Column(name = "pattern_id", nullable = false)),
			@AttributeOverride(name = "patternType", column = @Column(name = "pattern_type")) })
	public HospGrnSeqPrefsIdSequence getId() {
		return this.id;
	}

	public void setId(HospGrnSeqPrefsIdSequence id) {
		this.id = id;
	}

}
