package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HospPoSeqPrefsModel generated by hbm2java
 */
@Entity
@Table(name = "hosp_po_seq_prefs")
public class HospPoSeqPrefsModel implements java.io.Serializable {

	private HospPoSeqPrefsIdSequence id;

	public HospPoSeqPrefsModel() {
	}

	public HospPoSeqPrefsModel(HospPoSeqPrefsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "priority", column = @Column(name = "priority", nullable = false)),
			@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false)),
			@AttributeOverride(name = "patternId", column = @Column(name = "pattern_id", nullable = false)) })
	public HospPoSeqPrefsIdSequence getId() {
		return this.id;
	}

	public void setId(HospPoSeqPrefsIdSequence id) {
		this.id = id;
	}

}
