package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InsuranceClaimTemplateModel generated by hbm2java
 */
@Entity
@Table(name = "insurance_claim_template")
public class InsuranceClaimTemplateModel implements java.io.Serializable {

	private InsuranceClaimTemplateIdSequence id;

	public InsuranceClaimTemplateModel() {
	}

	public InsuranceClaimTemplateModel(InsuranceClaimTemplateIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "claimTemplateId", column = @Column(name = "claim_template_id", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", length = 50)),
			@AttributeOverride(name = "templateContent", column = @Column(name = "template_content")),
			@AttributeOverride(name = "templateType", column = @Column(name = "template_type", length = 1)) })
	public InsuranceClaimTemplateIdSequence getId() {
		return this.id;
	}

	public void setId(InsuranceClaimTemplateIdSequence id) {
		this.id = id;
	}

}
