package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InsurancePreauthModel generated by hbm2java
 */
@Entity
@Table(name = "insurance_preauth")
public class InsurancePreauthModel implements java.io.Serializable {

	private InsurancePreauthIdSequence id;

	public InsurancePreauthModel() {
	}

	public InsurancePreauthModel(InsurancePreauthIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "insuranceId", column = @Column(name = "insurance_id", nullable = false)),
			@AttributeOverride(name = "preAuthId", column = @Column(name = "pre_auth_id", nullable = false)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "created_by", length = 30)),
			@AttributeOverride(name = "createdDatetime", column = @Column(name = "created_datetime", length = 29)),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "updated_by", length = 30)),
			@AttributeOverride(name = "updatedDatetime", column = @Column(name = "updated_datetime", length = 29)),
			@AttributeOverride(name = "preauthFormId", column = @Column(name = "preauth_form_id", length = 5)),
			@AttributeOverride(name = "tpaId", column = @Column(name = "tpa_id", length = 15)),
			@AttributeOverride(name = "docId", column = @Column(name = "doc_id")) })
	public InsurancePreauthIdSequence getId() {
		return this.id;
	}

	public void setId(InsurancePreauthIdSequence id) {
		this.id = id;
	}

}
