package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InsuranceCompanyTpaMasterModel generated by hbm2java
 */
@Entity
@Table(name = "insurance_company_tpa_master")
public class InsuranceCompanyTpaMasterModel implements java.io.Serializable {

	private InsuranceCompanyTpaMasterIdSequence id;

	public InsuranceCompanyTpaMasterModel() {
	}

	public InsuranceCompanyTpaMasterModel(InsuranceCompanyTpaMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "insuranceCoId", column = @Column(name = "insurance_co_id", nullable = false, length = 10)),
			@AttributeOverride(name = "tpaId", column = @Column(name = "tpa_id", nullable = false, length = 15)) })
	public InsuranceCompanyTpaMasterIdSequence getId() {
		return this.id;
	}

	public void setId(InsuranceCompanyTpaMasterIdSequence id) {
		this.id = id;
	}

}
