package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InsurancePaymentAllocationModel generated by hbm2java
 */
@Entity
@Table(name = "insurance_payment_allocation")
public class InsurancePaymentAllocationModel implements java.io.Serializable {

	private InsurancePaymentAllocationIdSequence id;

	public InsurancePaymentAllocationModel() {
	}

	public InsurancePaymentAllocationModel(InsurancePaymentAllocationIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "remittanceId", column = @Column(name = "remittance_id")),
			@AttributeOverride(name = "chargeId", column = @Column(name = "charge_id", nullable = false, length = 15)),
			@AttributeOverride(name = "denialCode", column = @Column(name = "denial_code", length = 10)),
			@AttributeOverride(name = "paymentReference", column = @Column(name = "payment_reference", length = 50)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", precision = 15)),
			@AttributeOverride(name = "chargeType", column = @Column(name = "charge_type", length = 1)),
			@AttributeOverride(name = "saleItemId", column = @Column(name = "sale_item_id")),
			@AttributeOverride(name = "denialRemarks", column = @Column(name = "denial_remarks")),
			@AttributeOverride(name = "isRecovery", column = @Column(name = "is_recovery", nullable = false, length = 1)),
			@AttributeOverride(name = "claimId", column = @Column(name = "claim_id", length = 15)) })
	public InsurancePaymentAllocationIdSequence getId() {
		return this.id;
	}

	public void setId(InsurancePaymentAllocationIdSequence id) {
		this.id = id;
	}

}
