package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Arrays;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InsuranceTpaDocsIdSequence generated by hbm2java
 */
@Embeddable
public class InsuranceTpaDocsIdSequence implements java.io.Serializable {

	private int tpaDocId;
	private int insuranceId;
	private String documentName;
	private String description;
	private byte[] docContent;
	private Date docRecdDate;
	private String createdBy;
	private String contentType;
	private String originalExtension;

	public InsuranceTpaDocsIdSequence() {
	}

	public InsuranceTpaDocsIdSequence(int tpaDocId, int insuranceId) {
		this.tpaDocId = tpaDocId;
		this.insuranceId = insuranceId;
	}

	public InsuranceTpaDocsIdSequence(int tpaDocId, int insuranceId, String documentName, String description, byte[] docContent,
			Date docRecdDate, String createdBy, String contentType, String originalExtension) {
		this.tpaDocId = tpaDocId;
		this.insuranceId = insuranceId;
		this.documentName = documentName;
		this.description = description;
		this.docContent = docContent;
		this.docRecdDate = docRecdDate;
		this.createdBy = createdBy;
		this.contentType = contentType;
		this.originalExtension = originalExtension;
	}

	@Column(name = "tpa_doc_id", nullable = false)
	public int getTpaDocId() {
		return this.tpaDocId;
	}

	public void setTpaDocId(int tpaDocId) {
		this.tpaDocId = tpaDocId;
	}

	@Column(name = "insurance_id", nullable = false)
	public int getInsuranceId() {
		return this.insuranceId;
	}

	public void setInsuranceId(int insuranceId) {
		this.insuranceId = insuranceId;
	}

	@Column(name = "document_name", length = 50)
	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "doc_content")
	public byte[] getDocContent() {
		return this.docContent;
	}

	public void setDocContent(byte[] docContent) {
		this.docContent = docContent;
	}

	@Column(name = "doc_recd_date", length = 13)
	public Date getDocRecdDate() {
		return this.docRecdDate;
	}

	public void setDocRecdDate(Date docRecdDate) {
		this.docRecdDate = docRecdDate;
	}

	@Column(name = "created_by", length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "content_type")
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "original_extension", length = 20)
	public String getOriginalExtension() {
		return this.originalExtension;
	}

	public void setOriginalExtension(String originalExtension) {
		this.originalExtension = originalExtension;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InsuranceTpaDocsIdSequence))
			return false;
		InsuranceTpaDocsIdSequence castOther = (InsuranceTpaDocsIdSequence) other;

		return (this.getTpaDocId() == castOther.getTpaDocId()) && (this.getInsuranceId() == castOther.getInsuranceId())
				&& ((this.getDocumentName() == castOther.getDocumentName())
						|| (this.getDocumentName() != null && castOther.getDocumentName() != null
								&& this.getDocumentName().equals(castOther.getDocumentName())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getDocContent() == castOther.getDocContent())
						|| (this.getDocContent() != null && castOther.getDocContent() != null
								&& Arrays.equals(this.getDocContent(), castOther.getDocContent())))
				&& ((this.getDocRecdDate() == castOther.getDocRecdDate())
						|| (this.getDocRecdDate() != null && castOther.getDocRecdDate() != null
								&& this.getDocRecdDate().equals(castOther.getDocRecdDate())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getContentType() == castOther.getContentType())
						|| (this.getContentType() != null && castOther.getContentType() != null
								&& this.getContentType().equals(castOther.getContentType())))
				&& ((this.getOriginalExtension() == castOther.getOriginalExtension())
						|| (this.getOriginalExtension() != null && castOther.getOriginalExtension() != null
								&& this.getOriginalExtension().equals(castOther.getOriginalExtension())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTpaDocId();
		result = 37 * result + this.getInsuranceId();
		result = 37 * result + (getDocumentName() == null ? 0 : this.getDocumentName().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		int docContentHashcode = 0;
		byte[] docContentProperty = this.getDocContent();
		if (docContentProperty != null) {
			docContentHashcode = 1;
			for (int i = 0; i < docContentProperty.length; i++) {
				docContentHashcode = 37 * docContentHashcode + docContentProperty[i];
			}
		}

		result = 37 * result + docContentHashcode;

		result = 37 * result + (getDocRecdDate() == null ? 0 : this.getDocRecdDate().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getContentType() == null ? 0 : this.getContentType().hashCode());
		result = 37 * result + (getOriginalExtension() == null ? 0 : this.getOriginalExtension().hashCode());
		return result;
	}

}
