package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IntegDiagInBkpModel generated by hbm2java
 */
@Entity
@Table(name = "integ_diag_in_bkp")
public class IntegDiagInBkpModel implements java.io.Serializable {

	private IntegDiagInBkpIdSequence id;

	public IntegDiagInBkpModel() {
	}

	public IntegDiagInBkpModel(IntegDiagInBkpIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "interfaceName", column = @Column(name = "interface_name")),
			@AttributeOverride(name = "prescribedId", column = @Column(name = "prescribed_id")),
			@AttributeOverride(name = "resultlabelId", column = @Column(name = "resultlabel_id", length = 500)),
			@AttributeOverride(name = "sampleNo", column = @Column(name = "sample_no", length = 30)),
			@AttributeOverride(name = "reportValue", column = @Column(name = "report_value")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "comments", column = @Column(name = "comments")),
			@AttributeOverride(name = "insertedTs", column = @Column(name = "inserted_ts", length = 29)),
			@AttributeOverride(name = "readTs", column = @Column(name = "read_ts", length = 29)),
			@AttributeOverride(name = "exportFailureMsg", column = @Column(name = "export_failure_msg")),
			@AttributeOverride(name = "valueType", column = @Column(name = "value_type", length = 4)),
			@AttributeOverride(name = "patId", column = @Column(name = "pat_id", length = 15)) })
	public IntegDiagInBkpIdSequence getId() {
		return this.id;
	}

	public void setId(IntegDiagInBkpIdSequence id) {
		this.id = id;
	}

}
