package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ItemStoreLevelDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "item_store_level_details")
public class ItemStoreLevelDetailsModel implements java.io.Serializable {

	private ItemStoreLevelDetailsIdSequence id;
	private BigDecimal minLevel;
	private BigDecimal maxLevel;
	private BigDecimal reorderLevel;
	private BigDecimal dangerLevel;
	private String dangerUom;
	private String bin;

	public ItemStoreLevelDetailsModel() {
	}

	public ItemStoreLevelDetailsModel(ItemStoreLevelDetailsIdSequence id) {
		this.id = id;
	}

	public ItemStoreLevelDetailsModel(ItemStoreLevelDetailsIdSequence id, BigDecimal minLevel, BigDecimal maxLevel,
			BigDecimal reorderLevel, BigDecimal dangerLevel, String dangerUom, String bin) {
		this.id = id;
		this.minLevel = minLevel;
		this.maxLevel = maxLevel;
		this.reorderLevel = reorderLevel;
		this.dangerLevel = dangerLevel;
		this.dangerUom = dangerUom;
		this.bin = bin;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "medicineId", column = @Column(name = "medicine_id", nullable = false)),
			@AttributeOverride(name = "deptId", column = @Column(name = "dept_id", nullable = false)) })
	public ItemStoreLevelDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(ItemStoreLevelDetailsIdSequence id) {
		this.id = id;
	}

	@Column(name = "min_level", precision = 131089, scale = 0)
	public BigDecimal getMinLevel() {
		return this.minLevel;
	}

	public void setMinLevel(BigDecimal minLevel) {
		this.minLevel = minLevel;
	}

	@Column(name = "max_level", precision = 131089, scale = 0)
	public BigDecimal getMaxLevel() {
		return this.maxLevel;
	}

	public void setMaxLevel(BigDecimal maxLevel) {
		this.maxLevel = maxLevel;
	}

	@Column(name = "reorder_level", precision = 131089, scale = 0)
	public BigDecimal getReorderLevel() {
		return this.reorderLevel;
	}

	public void setReorderLevel(BigDecimal reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	@Column(name = "danger_level", precision = 131089, scale = 0)
	public BigDecimal getDangerLevel() {
		return this.dangerLevel;
	}

	public void setDangerLevel(BigDecimal dangerLevel) {
		this.dangerLevel = dangerLevel;
	}

	@Column(name = "danger_uom", length = 20)
	public String getDangerUom() {
		return this.dangerUom;
	}

	public void setDangerUom(String dangerUom) {
		this.dangerUom = dangerUom;
	}

	@Column(name = "bin", length = 50)
	public String getBin() {
		return this.bin;
	}

	public void setBin(String bin) {
		this.bin = bin;
	}

}
