package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IvfCompleEmbryoInfModel generated by hbm2java
 */
@Entity
@Table(name = "ivf_comple_embryo_inf")
public class IvfCompleEmbryoInfModel implements java.io.Serializable {

	private IvfCompleEmbryoInfIdSequence id;

	public IvfCompleEmbryoInfModel() {
	}

	public IvfCompleEmbryoInfModel(IvfCompleEmbryoInfIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ivfCycleEmbryoId", column = @Column(name = "ivf_cycle_embryo_id", nullable = false)),
			@AttributeOverride(name = "ivfCycleId", column = @Column(name = "ivf_cycle_id")),
			@AttributeOverride(name = "embryoOp", column = @Column(name = "embryo_op", length = 1)),
			@AttributeOverride(name = "embNumber", column = @Column(name = "emb_number")),
			@AttributeOverride(name = "embState", column = @Column(name = "emb_state", length = 10)),
			@AttributeOverride(name = "embGrade", column = @Column(name = "emb_grade", length = 10)) })
	public IvfCompleEmbryoInfIdSequence getId() {
		return this.id;
	}

	public void setId(IvfCompleEmbryoInfIdSequence id) {
		this.id = id;
	}

}
