package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IvfDailyDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "ivf_daily_details")
public class IvfDailyDetailsModel implements java.io.Serializable {

	private int ivfCycleDailyId;
	private Integer ivfCycleId;
	private Date treatmentDate;
	private Integer treatmentDaysFromStart;
	private BigDecimal endometriumThickness;
	private String finalRemarks;
	private String uterusRemarks;
	private String doctor;

	public IvfDailyDetailsModel() {
	}

	public IvfDailyDetailsModel(int ivfCycleDailyId) {
		this.ivfCycleDailyId = ivfCycleDailyId;
	}

	public IvfDailyDetailsModel(int ivfCycleDailyId, Integer ivfCycleId, Date treatmentDate, Integer treatmentDaysFromStart,
			BigDecimal endometriumThickness, String finalRemarks, String uterusRemarks, String doctor) {
		this.ivfCycleDailyId = ivfCycleDailyId;
		this.ivfCycleId = ivfCycleId;
		this.treatmentDate = treatmentDate;
		this.treatmentDaysFromStart = treatmentDaysFromStart;
		this.endometriumThickness = endometriumThickness;
		this.finalRemarks = finalRemarks;
		this.uterusRemarks = uterusRemarks;
		this.doctor = doctor;
	}

	@Id

	@Column(name = "ivf_cycle_daily_id", unique = true, nullable = false)
	public int getIvfCycleDailyId() {
		return this.ivfCycleDailyId;
	}

	public void setIvfCycleDailyId(int ivfCycleDailyId) {
		this.ivfCycleDailyId = ivfCycleDailyId;
	}

	@Column(name = "ivf_cycle_id")
	public Integer getIvfCycleId() {
		return this.ivfCycleId;
	}

	public void setIvfCycleId(Integer ivfCycleId) {
		this.ivfCycleId = ivfCycleId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "treatment_date", length = 13)
	public Date getTreatmentDate() {
		return this.treatmentDate;
	}

	public void setTreatmentDate(Date treatmentDate) {
		this.treatmentDate = treatmentDate;
	}

	@Column(name = "treatment_days_from_start")
	public Integer getTreatmentDaysFromStart() {
		return this.treatmentDaysFromStart;
	}

	public void setTreatmentDaysFromStart(Integer treatmentDaysFromStart) {
		this.treatmentDaysFromStart = treatmentDaysFromStart;
	}

	@Column(name = "endometrium_thickness", precision = 131089, scale = 0)
	public BigDecimal getEndometriumThickness() {
		return this.endometriumThickness;
	}

	public void setEndometriumThickness(BigDecimal endometriumThickness) {
		this.endometriumThickness = endometriumThickness;
	}

	@Column(name = "final_remarks", length = 2000)
	public String getFinalRemarks() {
		return this.finalRemarks;
	}

	public void setFinalRemarks(String finalRemarks) {
		this.finalRemarks = finalRemarks;
	}

	@Column(name = "uterus_remarks", length = 1000)
	public String getUterusRemarks() {
		return this.uterusRemarks;
	}

	public void setUterusRemarks(String uterusRemarks) {
		this.uterusRemarks = uterusRemarks;
	}

	@Column(name = "doctor", length = 20)
	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

}
