package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IvfDailyFolliclesModel generated by hbm2java
 */
@Entity
@Table(name = "ivf_daily_follicles")
public class IvfDailyFolliclesModel implements java.io.Serializable {

	private IvfDailyFolliclesIdSequence id;

	public IvfDailyFolliclesModel() {
	}

	public IvfDailyFolliclesModel(IvfDailyFolliclesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ivfCycleDailyId", column = @Column(name = "ivf_cycle_daily_id")),
			@AttributeOverride(name = "ovaryPosition", column = @Column(name = "ovary_position", length = 1)),
			@AttributeOverride(name = "folliclesCount", column = @Column(name = "follicles_count")),
			@AttributeOverride(name = "folliclesSize", column = @Column(name = "follicles_size", precision = 131089, scale = 0)) })
	public IvfDailyFolliclesIdSequence getId() {
		return this.id;
	}

	public void setId(IvfDailyFolliclesIdSequence id) {
		this.id = id;
	}

}
