package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IvfDailyHormoneResultsIdSequence generated by hbm2java
 */
@Embeddable
public class IvfDailyHormoneResultsIdSequence implements java.io.Serializable {

	private Integer ivfCycleDailyId;
	private BigDecimal fshValue;
	private BigDecimal p4Value;
	private BigDecimal e2Value;
	private BigDecimal lhValue;
	private BigDecimal tshValue;

	public IvfDailyHormoneResultsIdSequence() {
	}

	public IvfDailyHormoneResultsIdSequence(Integer ivfCycleDailyId, BigDecimal fshValue, BigDecimal p4Value,
			BigDecimal e2Value, BigDecimal lhValue, BigDecimal tshValue) {
		this.ivfCycleDailyId = ivfCycleDailyId;
		this.fshValue = fshValue;
		this.p4Value = p4Value;
		this.e2Value = e2Value;
		this.lhValue = lhValue;
		this.tshValue = tshValue;
	}

	@Column(name = "ivf_cycle_daily_id")
	public Integer getIvfCycleDailyId() {
		return this.ivfCycleDailyId;
	}

	public void setIvfCycleDailyId(Integer ivfCycleDailyId) {
		this.ivfCycleDailyId = ivfCycleDailyId;
	}

	@Column(name = "fsh_value", precision = 131089, scale = 0)
	public BigDecimal getFshValue() {
		return this.fshValue;
	}

	public void setFshValue(BigDecimal fshValue) {
		this.fshValue = fshValue;
	}

	@Column(name = "p4_value", precision = 131089, scale = 0)
	public BigDecimal getP4Value() {
		return this.p4Value;
	}

	public void setP4Value(BigDecimal p4Value) {
		this.p4Value = p4Value;
	}

	@Column(name = "e2_value", precision = 131089, scale = 0)
	public BigDecimal getE2Value() {
		return this.e2Value;
	}

	public void setE2Value(BigDecimal e2Value) {
		this.e2Value = e2Value;
	}

	@Column(name = "lh_value", precision = 131089, scale = 0)
	public BigDecimal getLhValue() {
		return this.lhValue;
	}

	public void setLhValue(BigDecimal lhValue) {
		this.lhValue = lhValue;
	}

	@Column(name = "tsh_value", precision = 131089, scale = 0)
	public BigDecimal getTshValue() {
		return this.tshValue;
	}

	public void setTshValue(BigDecimal tshValue) {
		this.tshValue = tshValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IvfDailyHormoneResultsIdSequence))
			return false;
		IvfDailyHormoneResultsIdSequence castOther = (IvfDailyHormoneResultsIdSequence) other;

		return ((this.getIvfCycleDailyId() == castOther.getIvfCycleDailyId())
				|| (this.getIvfCycleDailyId() != null && castOther.getIvfCycleDailyId() != null
						&& this.getIvfCycleDailyId().equals(castOther.getIvfCycleDailyId())))
				&& ((this.getFshValue() == castOther.getFshValue()) || (this.getFshValue() != null
						&& castOther.getFshValue() != null && this.getFshValue().equals(castOther.getFshValue())))
				&& ((this.getP4Value() == castOther.getP4Value()) || (this.getP4Value() != null
						&& castOther.getP4Value() != null && this.getP4Value().equals(castOther.getP4Value())))
				&& ((this.getE2Value() == castOther.getE2Value()) || (this.getE2Value() != null
						&& castOther.getE2Value() != null && this.getE2Value().equals(castOther.getE2Value())))
				&& ((this.getLhValue() == castOther.getLhValue()) || (this.getLhValue() != null
						&& castOther.getLhValue() != null && this.getLhValue().equals(castOther.getLhValue())))
				&& ((this.getTshValue() == castOther.getTshValue()) || (this.getTshValue() != null
						&& castOther.getTshValue() != null && this.getTshValue().equals(castOther.getTshValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIvfCycleDailyId() == null ? 0 : this.getIvfCycleDailyId().hashCode());
		result = 37 * result + (getFshValue() == null ? 0 : this.getFshValue().hashCode());
		result = 37 * result + (getP4Value() == null ? 0 : this.getP4Value().hashCode());
		result = 37 * result + (getE2Value() == null ? 0 : this.getE2Value().hashCode());
		result = 37 * result + (getLhValue() == null ? 0 : this.getLhValue().hashCode());
		result = 37 * result + (getTshValue() == null ? 0 : this.getTshValue().hashCode());
		return result;
	}

}
