package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IvfLutealHormoneLevelsModel generated by hbm2java
 */
@Entity
@Table(name = "ivf_luteal_hormone_levels")
public class IvfLutealHormoneLevelsModel implements java.io.Serializable {

	private IvfLutealHormoneLevelsIdSequence id;

	public IvfLutealHormoneLevelsModel() {
	}

	public IvfLutealHormoneLevelsModel(IvfLutealHormoneLevelsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ivfCycleId", column = @Column(name = "ivf_cycle_id")),
			@AttributeOverride(name = "betaHcgValue", column = @Column(name = "beta_hcg_value", precision = 131089, scale = 0)),
			@AttributeOverride(name = "progValue", column = @Column(name = "prog_value", precision = 131089, scale = 0)),
			@AttributeOverride(name = "bloodTestDate", column = @Column(name = "blood_test_date", length = 13)),
			@AttributeOverride(name = "e2Value", column = @Column(name = "e2_value", precision = 131089, scale = 0)) })
	public IvfLutealHormoneLevelsIdSequence getId() {
		return this.id;
	}

	public void setId(IvfLutealHormoneLevelsIdSequence id) {
		this.id = id;
	}

}
