package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LicenseTypeMasterModel generated by hbm2java
 */
@Entity
@Table(name = "license_type_master")
public class LicenseTypeMasterModel implements java.io.Serializable {

	private BigDecimal licenseTypeId;
	private String licenseType;
	private String status;
	private Set licenseses = new HashSet(0);

	public LicenseTypeMasterModel() {
	}

	public LicenseTypeMasterModel(BigDecimal licenseTypeId) {
		this.licenseTypeId = licenseTypeId;
	}

	public LicenseTypeMasterModel(BigDecimal licenseTypeId, String licenseType, String status, Set licenseses) {
		this.licenseTypeId = licenseTypeId;
		this.licenseType = licenseType;
		this.status = status;
		this.licenseses = licenseses;
	}

	@Id

	@Column(name = "license_type_id", unique = true, nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLicenseTypeId() {
		return this.licenseTypeId;
	}

	public void setLicenseTypeId(BigDecimal licenseTypeId) {
		this.licenseTypeId = licenseTypeId;
	}

	@Column(name = "license_type", length = 30)
	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseTypeMaster")
	public Set getLicenseses() {
		return this.licenseses;
	}

	public void setLicenseses(Set licenseses) {
		this.licenseses = licenseses;
	}

}
