package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.storescontractor.ContractorMasterModel;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LicensesModel generated by hbm2java
 */
@Entity
@Table(name = "licenses")
public class LicensesModel implements java.io.Serializable {

	private BigDecimal licenseId;
	private ContractorMasterModel ContractorMasterModel;
	private LicenseTypeMasterModel LicenseTypeMasterModel;
	private String licenseDesc;
	private Date licenseStartDate;
	private Date licenseEndDate;
	private Date licenseRenewalDate;
	private BigDecimal licenseValue;
	private String licenseNote;
	private byte[] licenseAttachment;
	private char licenseStatus;

	public LicensesModel() {
	}

	public LicensesModel(BigDecimal licenseId, char licenseStatus) {
		this.licenseId = licenseId;
		this.licenseStatus = licenseStatus;
	}

	public LicensesModel(BigDecimal licenseId, ContractorMasterModel ContractorMasterModel, LicenseTypeMasterModel LicenseTypeMasterModel,
			String licenseDesc, Date licenseStartDate, Date licenseEndDate, Date licenseRenewalDate,
			BigDecimal licenseValue, String licenseNote, byte[] licenseAttachment, char licenseStatus) {
		this.licenseId = licenseId;
		this.ContractorMasterModel = ContractorMasterModel;
		this.LicenseTypeMasterModel = LicenseTypeMasterModel;
		this.licenseDesc = licenseDesc;
		this.licenseStartDate = licenseStartDate;
		this.licenseEndDate = licenseEndDate;
		this.licenseRenewalDate = licenseRenewalDate;
		this.licenseValue = licenseValue;
		this.licenseNote = licenseNote;
		this.licenseAttachment = licenseAttachment;
		this.licenseStatus = licenseStatus;
	}

	@Id

	@Column(name = "license_id", unique = true, nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(BigDecimal licenseId) {
		this.licenseId = licenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contractor_id")
	public ContractorMasterModel getContractorMasterModel() {
		return this.ContractorMasterModel;
	}

	public void setContractorMasterModel(ContractorMasterModel ContractorMasterModel) {
		this.ContractorMasterModel = ContractorMasterModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "license_type_id")
	public LicenseTypeMasterModel getLicenseTypeMasterModel() {
		return this.LicenseTypeMasterModel;
	}

	public void setLicenseTypeMasterModel(LicenseTypeMasterModel LicenseTypeMasterModel) {
		this.LicenseTypeMasterModel = LicenseTypeMasterModel;
	}

	@Column(name = "license_desc", length = 50)
	public String getLicenseDesc() {
		return this.licenseDesc;
	}

	public void setLicenseDesc(String licenseDesc) {
		this.licenseDesc = licenseDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "license_start_date", length = 13)
	public Date getLicenseStartDate() {
		return this.licenseStartDate;
	}

	public void setLicenseStartDate(Date licenseStartDate) {
		this.licenseStartDate = licenseStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "license_end_date", length = 13)
	public Date getLicenseEndDate() {
		return this.licenseEndDate;
	}

	public void setLicenseEndDate(Date licenseEndDate) {
		this.licenseEndDate = licenseEndDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "license_renewal_date", length = 13)
	public Date getLicenseRenewalDate() {
		return this.licenseRenewalDate;
	}

	public void setLicenseRenewalDate(Date licenseRenewalDate) {
		this.licenseRenewalDate = licenseRenewalDate;
	}

	@Column(name = "license_value", precision = 131089, scale = 0)
	public BigDecimal getLicenseValue() {
		return this.licenseValue;
	}

	public void setLicenseValue(BigDecimal licenseValue) {
		this.licenseValue = licenseValue;
	}

	@Column(name = "license_note")
	public String getLicenseNote() {
		return this.licenseNote;
	}

	public void setLicenseNote(String licenseNote) {
		this.licenseNote = licenseNote;
	}

	@Column(name = "license_attachment")
	public byte[] getLicenseAttachment() {
		return this.licenseAttachment;
	}

	public void setLicenseAttachment(byte[] licenseAttachment) {
		this.licenseAttachment = licenseAttachment;
	}

	@Column(name = "license_status", nullable = false, length = 1)
	public char getLicenseStatus() {
		return this.licenseStatus;
	}

	public void setLicenseStatus(char licenseStatus) {
		this.licenseStatus = licenseStatus;
	}

}
