package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.item.StoreItemDetailsModel;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinenUsageDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "linen_usage_details")
public class LinenUsageDetailsModel implements java.io.Serializable {

	private LinenUsageDetailsIdSequence id;
	private LinenUsageMainModel LinenUsageMainModel;
	private StoreItemDetailsModel storeItemDetails;

	public LinenUsageDetailsModel() {
	}

	public LinenUsageDetailsModel(LinenUsageDetailsIdSequence id, LinenUsageMainModel LinenUsageMainModel, StoreItemDetailsModel storeItemDetails) {
		this.id = id;
		this.LinenUsageMainModel = LinenUsageMainModel;
		this.storeItemDetails = storeItemDetails;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "entryId", column = @Column(name = "entry_id", nullable = false)),
			@AttributeOverride(name = "linenId", column = @Column(name = "linen_id", nullable = false)),
			@AttributeOverride(name = "batchNo", column = @Column(name = "batch_no", nullable = false, length = 50)),
			@AttributeOverride(name = "qty", column = @Column(name = "qty", precision = 131089, scale = 0)),
			@AttributeOverride(name = "remarks", column = @Column(name = "remarks", length = 200)),
			@AttributeOverride(name = "cleaningType", column = @Column(name = "cleaning_type", length = 50)),
			@AttributeOverride(name = "reuseFlag", column = @Column(name = "reuse_flag", length = 1)) })
	public LinenUsageDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(LinenUsageDetailsIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entry_id", nullable = false, insertable = false, updatable = false)
	public LinenUsageMainModel getLinenUsageMainModel() {
		return this.LinenUsageMainModel;
	}

	public void setLinenUsageMainModel(LinenUsageMainModel LinenUsageMainModel) {
		this.LinenUsageMainModel = LinenUsageMainModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "linen_id", nullable = false, insertable = false, updatable = false)
	public StoreItemDetailsModel getStoreItemDetailsModel() {
		return this.storeItemDetails;
	}

	public void setStoreItemDetailsModel(StoreItemDetailsModel storeItemDetails) {
		this.storeItemDetails = storeItemDetails;
	}

}
