package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LinenUsageMainModel generated by hbm2java
 */
@Entity
@Table(name = "linen_usage_main")
public class LinenUsageMainModel implements java.io.Serializable {

	private int entryId;
	private String linenUserType;
	private String linenUserId;
	private String specificUserId;
	private String userName;
	private Date modifiedDate;
	private Set linenUsageDetailses = new HashSet(0);

	public LinenUsageMainModel() {
	}

	public LinenUsageMainModel(int entryId, Date modifiedDate) {
		this.entryId = entryId;
		this.modifiedDate = modifiedDate;
	}

	public LinenUsageMainModel(int entryId, String linenUserType, String linenUserId, String specificUserId, String userName,
			Date modifiedDate, Set linenUsageDetailses) {
		this.entryId = entryId;
		this.linenUserType = linenUserType;
		this.linenUserId = linenUserId;
		this.specificUserId = specificUserId;
		this.userName = userName;
		this.modifiedDate = modifiedDate;
		this.linenUsageDetailses = linenUsageDetailses;
	}

	@Id

	@Column(name = "entry_id", unique = true, nullable = false)
	public int getEntryId() {
		return this.entryId;
	}

	public void setEntryId(int entryId) {
		this.entryId = entryId;
	}

	@Column(name = "linen_user_type", length = 50)
	public String getLinenUserType() {
		return this.linenUserType;
	}

	public void setLinenUserType(String linenUserType) {
		this.linenUserType = linenUserType;
	}

	@Column(name = "linen_user_id", length = 100)
	public String getLinenUserId() {
		return this.linenUserId;
	}

	public void setLinenUserId(String linenUserId) {
		this.linenUserId = linenUserId;
	}

	@Column(name = "specific_user_id", length = 50)
	public String getSpecificUserId() {
		return this.specificUserId;
	}

	public void setSpecificUserId(String specificUserId) {
		this.specificUserId = specificUserId;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linenUsageMain")
	public Set getLinenUsageDetailses() {
		return this.linenUsageDetailses;
	}

	public void setLinenUsageDetailses(Set linenUsageDetailses) {
		this.linenUsageDetailses = linenUsageDetailses;
	}

}
