package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LinenUserMasterModel generated by hbm2java
 */
@Entity
@Table(name = "linen_user_master")
public class LinenUserMasterModel implements java.io.Serializable {

	private LinenUserMasterIdSequence id;

	public LinenUserMasterModel() {
	}

	public LinenUserMasterModel(LinenUserMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "categoryId", column = @Column(name = "category_id")),
			@AttributeOverride(name = "categoryUserId", column = @Column(name = "category_user_id")),
			@AttributeOverride(name = "categoryUserName", column = @Column(name = "category_user_name", length = 30)) })
	public LinenUserMasterIdSequence getId() {
		return this.id;
	}

	public void setId(LinenUserMasterIdSequence id) {
		this.id = id;
	}

}
