package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LocationMasterModel generated by hbm2java
 */
@Entity
@Table(name = "location_master", uniqueConstraints = @UniqueConstraint(columnNames = "location_name"))
public class LocationMasterModel implements java.io.Serializable {

	private int locationId;
	private String locationName;
	private Character status;
	private String remarks;
	private int centerId;
	private Set dialysisSessions = new HashSet(0);

	public LocationMasterModel() {
	}

	public LocationMasterModel(int locationId, String locationName, int centerId) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.centerId = centerId;
	}

	public LocationMasterModel(int locationId, String locationName, Character status, String remarks, int centerId,
			Set dialysisSessions) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.status = status;
		this.remarks = remarks;
		this.centerId = centerId;
		this.dialysisSessions = dialysisSessions;
	}

	@Id

	@Column(name = "location_id", unique = true, nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	@Column(name = "location_name", unique = true, nullable = false, length = 30)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "remarks", length = 250)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "center_id", nullable = false)
	public int getCenterId() {
		return this.centerId;
	}

	public void setCenterId(int centerId) {
		this.centerId = centerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationMaster")
	public Set getDialysisSessions() {
		return this.dialysisSessions;
	}

	public void setDialysisSessions(Set dialysisSessions) {
		this.dialysisSessions = dialysisSessions;
	}

}
