package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ManfMasterModel generated by hbm2java
 */
@Entity
@Table(name = "manf_master", uniqueConstraints = @UniqueConstraint(columnNames = "manf_name"))
public class ManfMasterModel implements java.io.Serializable {

	private String manfCode;
	private String manfName;
	private String manfAddress;
	private String manfCity;
	private String manfState;
	private String manfCountry;
	private String manfPin;
	private String manfPhone1;
	private String manfPhone2;
	private String manfFax;
	private String manfMailid;
	private String manfWebsite;
	private char status;
	private String manfMnemonic;
	private Boolean pharmacy;
	private Boolean inventory;
	private Set storeItemDetailses = new HashSet(0);

	public ManfMasterModel() {
	}

	public ManfMasterModel(String manfCode, String manfName, char status, String manfMnemonic) {
		this.manfCode = manfCode;
		this.manfName = manfName;
		this.status = status;
		this.manfMnemonic = manfMnemonic;
	}

	public ManfMasterModel(String manfCode, String manfName, String manfAddress, String manfCity, String manfState,
			String manfCountry, String manfPin, String manfPhone1, String manfPhone2, String manfFax, String manfMailid,
			String manfWebsite, char status, String manfMnemonic, Boolean pharmacy, Boolean inventory,
			Set storeItemDetailses) {
		this.manfCode = manfCode;
		this.manfName = manfName;
		this.manfAddress = manfAddress;
		this.manfCity = manfCity;
		this.manfState = manfState;
		this.manfCountry = manfCountry;
		this.manfPin = manfPin;
		this.manfPhone1 = manfPhone1;
		this.manfPhone2 = manfPhone2;
		this.manfFax = manfFax;
		this.manfMailid = manfMailid;
		this.manfWebsite = manfWebsite;
		this.status = status;
		this.manfMnemonic = manfMnemonic;
		this.pharmacy = pharmacy;
		this.inventory = inventory;
		this.storeItemDetailses = storeItemDetailses;
	}

	@Id

	@Column(name = "manf_code", unique = true, nullable = false, length = 30)
	public String getManfCode() {
		return this.manfCode;
	}

	public void setManfCode(String manfCode) {
		this.manfCode = manfCode;
	}

	@Column(name = "manf_name", unique = true, nullable = false, length = 100)
	public String getManfName() {
		return this.manfName;
	}

	public void setManfName(String manfName) {
		this.manfName = manfName;
	}

	@Column(name = "manf_address", length = 250)
	public String getManfAddress() {
		return this.manfAddress;
	}

	public void setManfAddress(String manfAddress) {
		this.manfAddress = manfAddress;
	}

	@Column(name = "manf_city", length = 30)
	public String getManfCity() {
		return this.manfCity;
	}

	public void setManfCity(String manfCity) {
		this.manfCity = manfCity;
	}

	@Column(name = "manf_state", length = 30)
	public String getManfState() {
		return this.manfState;
	}

	public void setManfState(String manfState) {
		this.manfState = manfState;
	}

	@Column(name = "manf_country", length = 30)
	public String getManfCountry() {
		return this.manfCountry;
	}

	public void setManfCountry(String manfCountry) {
		this.manfCountry = manfCountry;
	}

	@Column(name = "manf_pin", length = 10)
	public String getManfPin() {
		return this.manfPin;
	}

	public void setManfPin(String manfPin) {
		this.manfPin = manfPin;
	}

	@Column(name = "manf_phone1", length = 20)
	public String getManfPhone1() {
		return this.manfPhone1;
	}

	public void setManfPhone1(String manfPhone1) {
		this.manfPhone1 = manfPhone1;
	}

	@Column(name = "manf_phone2", length = 20)
	public String getManfPhone2() {
		return this.manfPhone2;
	}

	public void setManfPhone2(String manfPhone2) {
		this.manfPhone2 = manfPhone2;
	}

	@Column(name = "manf_fax", length = 20)
	public String getManfFax() {
		return this.manfFax;
	}

	public void setManfFax(String manfFax) {
		this.manfFax = manfFax;
	}

	@Column(name = "manf_mailid", length = 100)
	public String getManfMailid() {
		return this.manfMailid;
	}

	public void setManfMailid(String manfMailid) {
		this.manfMailid = manfMailid;
	}

	@Column(name = "manf_website", length = 100)
	public String getManfWebsite() {
		return this.manfWebsite;
	}

	public void setManfWebsite(String manfWebsite) {
		this.manfWebsite = manfWebsite;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "manf_mnemonic", nullable = false, length = 5)
	public String getManfMnemonic() {
		return this.manfMnemonic;
	}

	public void setManfMnemonic(String manfMnemonic) {
		this.manfMnemonic = manfMnemonic;
	}

	@Column(name = "pharmacy")
	public Boolean getPharmacy() {
		return this.pharmacy;
	}

	public void setPharmacy(Boolean pharmacy) {
		this.pharmacy = pharmacy;
	}

	@Column(name = "inventory")
	public Boolean getInventory() {
		return this.inventory;
	}

	public void setInventory(Boolean inventory) {
		this.inventory = inventory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manfMaster")
	public Set getStoreItemDetailses() {
		return this.storeItemDetailses;
	}

	public void setStoreItemDetailses(Set storeItemDetailses) {
		this.storeItemDetailses = storeItemDetailses;
	}

}
