package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MedicalFileuploadModel generated by hbm2java
 */
@Entity
@Table(name = "medical_fileupload")
public class MedicalFileuploadModel implements java.io.Serializable {

	private String docid;
	private byte[] imagefile;
	private String mrNo;
	private String docName;
	private String docType;
	private String userId;
	private Date uploadDate;
	private String patientId;
	private String contenttype;
	private String contentfilename;
	private String moduleId;

	public MedicalFileuploadModel() {
	}

	public MedicalFileuploadModel(String docid, String userId) {
		this.docid = docid;
		this.userId = userId;
	}

	public MedicalFileuploadModel(String docid, byte[] imagefile, String mrNo, String docName, String docType, String userId,
			Date uploadDate, String patientId, String contenttype, String contentfilename, String moduleId) {
		this.docid = docid;
		this.imagefile = imagefile;
		this.mrNo = mrNo;
		this.docName = docName;
		this.docType = docType;
		this.userId = userId;
		this.uploadDate = uploadDate;
		this.patientId = patientId;
		this.contenttype = contenttype;
		this.contentfilename = contentfilename;
		this.moduleId = moduleId;
	}

	@Id

	@Column(name = "docid", unique = true, nullable = false, length = 10)
	public String getDocid() {
		return this.docid;
	}

	public void setDocid(String docid) {
		this.docid = docid;
	}

	@Column(name = "imagefile")
	public byte[] getImagefile() {
		return this.imagefile;
	}

	public void setImagefile(byte[] imagefile) {
		this.imagefile = imagefile;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "doc_name", length = 50)
	public String getDocName() {
		return this.docName;
	}

	public void setDocName(String docName) {
		this.docName = docName;
	}

	@Column(name = "doc_type", length = 10)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "user_id", nullable = false, length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "upload_date", length = 13)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	@Column(name = "patient_id", length = 20)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "contenttype", length = 50)
	public String getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(String contenttype) {
		this.contenttype = contenttype;
	}

	@Column(name = "contentfilename", length = 50)
	public String getContentfilename() {
		return this.contentfilename;
	}

	public void setContentfilename(String contentfilename) {
		this.contentfilename = contentfilename;
	}

	@Column(name = "module_id", length = 20)
	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

}
