package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MessageEventsModel generated by hbm2java
 */
@Entity
@Table(name = "message_events")
public class MessageEventsModel implements java.io.Serializable {

	private String eventId;
	private String eventName;
	private String eventDescription;
	private Set messageTypeses = new HashSet(0);

	public MessageEventsModel() {
	}

	public MessageEventsModel(String eventId) {
		this.eventId = eventId;
	}

	public MessageEventsModel(String eventId, String eventName, String eventDescription, Set messageTypeses) {
		this.eventId = eventId;
		this.eventName = eventName;
		this.eventDescription = eventDescription;
		this.messageTypeses = messageTypeses;
	}

	@Id

	@Column(name = "event_id", unique = true, nullable = false, length = 50)
	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	@Column(name = "event_name", length = 100)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "event_description", length = 100)
	public String getEventDescription() {
		return this.eventDescription;
	}

	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messageEvents")
	public Set getMessageTypeses() {
		return this.messageTypeses;
	}

	public void setMessageTypeses(Set messageTypeses) {
		this.messageTypeses = messageTypeses;
	}

}
