package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MessageTypeActionsModel generated by hbm2java
 */
@Entity
@Table(name = "message_type_actions")
public class MessageTypeActionsModel implements java.io.Serializable {

	private MessageTypeActionsIdSequence id;

	public MessageTypeActionsModel() {
	}

	public MessageTypeActionsModel(MessageTypeActionsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "messageTypeId", column = @Column(name = "message_type_id", length = 100)),
			@AttributeOverride(name = "messageActionMask", column = @Column(name = "message_action_mask")),
			@AttributeOverride(name = "senderOverrideMask", column = @Column(name = "sender_override_mask")) })
	public MessageTypeActionsIdSequence getId() {
		return this.id;
	}

	public void setId(MessageTypeActionsIdSequence id) {
		this.id = id;
	}

}
