package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MessageTypesModel generated by hbm2java
 */
@Entity
@Table(name = "message_types")
public class MessageTypesModel implements java.io.Serializable {

	private String messageTypeId;
	private MessageCategoryModel messageCategory;
	private MessageEventsModel messageEvents;
	private String messageTypeName;
	private String messageTypeDescription;
	private String messageSender;
	private String messageTo;
	private String messageSubject;
	private String messageBody;
	private String messageCc;
	private String messageBcc;
	private String messageMode;
	private Character status;
	private String messageGroup;
	private Character editability;
	private String messageFooter;
	private Set messageAttachmentses = new HashSet(0);
	private Set messageConfigs = new HashSet(0);
	private Set messageLogs = new HashSet(0);

	public MessageTypesModel() {
	}

	public MessageTypesModel(String messageTypeId, MessageEventsModel messageEvents) {
		this.messageTypeId = messageTypeId;
		this.messageEvents = messageEvents;
	}

	public MessageTypesModel(String messageTypeId, MessageCategoryModel messageCategory, MessageEventsModel messageEvents,
			String messageTypeName, String messageTypeDescription, String messageSender, String messageTo,
			String messageSubject, String messageBody, String messageCc, String messageBcc, String messageMode,
			Character status, String messageGroup, Character editability, String messageFooter,
			Set messageAttachmentses, Set messageConfigs, Set messageLogs) {
		this.messageTypeId = messageTypeId;
		this.messageCategory = messageCategory;
		this.messageEvents = messageEvents;
		this.messageTypeName = messageTypeName;
		this.messageTypeDescription = messageTypeDescription;
		this.messageSender = messageSender;
		this.messageTo = messageTo;
		this.messageSubject = messageSubject;
		this.messageBody = messageBody;
		this.messageCc = messageCc;
		this.messageBcc = messageBcc;
		this.messageMode = messageMode;
		this.status = status;
		this.messageGroup = messageGroup;
		this.editability = editability;
		this.messageFooter = messageFooter;
		this.messageAttachmentses = messageAttachmentses;
		this.messageConfigs = messageConfigs;
		this.messageLogs = messageLogs;
	}

	@Id

	@Column(name = "message_type_id", unique = true, nullable = false, length = 100)
	public String getMessageTypeId() {
		return this.messageTypeId;
	}

	public void setMessageTypeId(String messageTypeId) {
		this.messageTypeId = messageTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public MessageCategoryModel getMessageCategoryModel() {
		return this.messageCategory;
	}

	public void setMessageCategoryModel(MessageCategoryModel messageCategory) {
		this.messageCategory = messageCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id", nullable = false)
	public MessageEventsModel getMessageEventsModel() {
		return this.messageEvents;
	}

	public void setMessageEventsModel(MessageEventsModel messageEvents) {
		this.messageEvents = messageEvents;
	}

	@Column(name = "message_type_name", length = 100)
	public String getMessageTypeName() {
		return this.messageTypeName;
	}

	public void setMessageTypeName(String messageTypeName) {
		this.messageTypeName = messageTypeName;
	}

	@Column(name = "message_type_description", length = 250)
	public String getMessageTypeDescription() {
		return this.messageTypeDescription;
	}

	public void setMessageTypeDescription(String messageTypeDescription) {
		this.messageTypeDescription = messageTypeDescription;
	}

	@Column(name = "message_sender", length = 100)
	public String getMessageSender() {
		return this.messageSender;
	}

	public void setMessageSender(String messageSender) {
		this.messageSender = messageSender;
	}

	@Column(name = "message_to")
	public String getMessageTo() {
		return this.messageTo;
	}

	public void setMessageTo(String messageTo) {
		this.messageTo = messageTo;
	}

	@Column(name = "message_subject", length = 100)
	public String getMessageSubject() {
		return this.messageSubject;
	}

	public void setMessageSubject(String messageSubject) {
		this.messageSubject = messageSubject;
	}

	@Column(name = "message_body")
	public String getMessageBody() {
		return this.messageBody;
	}

	public void setMessageBody(String messageBody) {
		this.messageBody = messageBody;
	}

	@Column(name = "message_cc")
	public String getMessageCc() {
		return this.messageCc;
	}

	public void setMessageCc(String messageCc) {
		this.messageCc = messageCc;
	}

	@Column(name = "message_bcc")
	public String getMessageBcc() {
		return this.messageBcc;
	}

	public void setMessageBcc(String messageBcc) {
		this.messageBcc = messageBcc;
	}

	@Column(name = "message_mode", length = 30)
	public String getMessageMode() {
		return this.messageMode;
	}

	public void setMessageMode(String messageMode) {
		this.messageMode = messageMode;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public void setMessageGroup(String messageGroup) {
		this.messageGroup = messageGroup;
	}

	@Column(name = "editability", length = 1)
	public Character getEditability() {
		return this.editability;
	}

	public void setEditability(Character editability) {
		this.editability = editability;
	}

	@Column(name = "message_footer", length = 100)
	public String getMessageFooter() {
		return this.messageFooter;
	}

	public void setMessageFooter(String messageFooter) {
		this.messageFooter = messageFooter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messageTypes")
	public Set getMessageAttachmentses() {
		return this.messageAttachmentses;
	}

	public void setMessageAttachmentses(Set messageAttachmentses) {
		this.messageAttachmentses = messageAttachmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messageTypes")
	public Set getMessageConfigs() {
		return this.messageConfigs;
	}

	public void setMessageConfigs(Set messageConfigs) {
		this.messageConfigs = messageConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messageTypes")
	public Set getMessageLogs() {
		return this.messageLogs;
	}

	public void setMessageLogs(Set messageLogs) {
		this.messageLogs = messageLogs;
	}

}
