package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MicroOrgGroupMasterModel generated by hbm2java
 */
@Entity
@Table(name = "micro_org_group_master")
public class MicroOrgGroupMasterModel implements java.io.Serializable {

	private int orgGroupId;
	private String orgGroupName;
	private Character status;
	private Set microAbstOrggrs = new HashSet(0);
	private Set microOrganismMasters = new HashSet(0);

	public MicroOrgGroupMasterModel() {
	}

	public MicroOrgGroupMasterModel(int orgGroupId) {
		this.orgGroupId = orgGroupId;
	}

	public MicroOrgGroupMasterModel(int orgGroupId, String orgGroupName, Character status, Set microAbstOrggrs,
			Set microOrganismMasters) {
		this.orgGroupId = orgGroupId;
		this.orgGroupName = orgGroupName;
		this.status = status;
		this.microAbstOrggrs = microAbstOrggrs;
		this.microOrganismMasters = microOrganismMasters;
	}

	@Id

	@Column(name = "org_group_id", unique = true, nullable = false)
	public int getOrgGroupId() {
		return this.orgGroupId;
	}

	public void setOrgGroupId(int orgGroupId) {
		this.orgGroupId = orgGroupId;
	}

	@Column(name = "org_group_name", length = 100)
	public String getOrgGroupName() {
		return this.orgGroupName;
	}

	public void setOrgGroupName(String orgGroupName) {
		this.orgGroupName = orgGroupName;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "microOrgGroupMaster")
	public Set getMicroAbstOrggrs() {
		return this.microAbstOrggrs;
	}

	public void setMicroAbstOrggrs(Set microAbstOrggrs) {
		this.microAbstOrggrs = microAbstOrggrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "microOrgGroupMaster")
	public Set getMicroOrganismMasters() {
		return this.microOrganismMasters;
	}

	public void setMicroOrganismMasters(Set microOrganismMasters) {
		this.microOrganismMasters = microOrganismMasters;
	}

}
