package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MrdCasefileIndentModel generated by hbm2java
 */
@Entity
@Table(name = "mrd_casefile_indent")
public class MrdCasefileIndentModel implements java.io.Serializable {

	private MrdCasefileIndentIdSequence id;

	public MrdCasefileIndentModel() {
	}

	public MrdCasefileIndentModel(MrdCasefileIndentIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", nullable = false, length = 15)),
			@AttributeOverride(name = "indentNo", column = @Column(name = "indent_no", nullable = false)),
			@AttributeOverride(name = "requestDate", column = @Column(name = "request_date", length = 35)),
			@AttributeOverride(name = "requestingDept", column = @Column(name = "requesting_dept", nullable = false, length = 50)),
			@AttributeOverride(name = "requestedBy", column = @Column(name = "requested_by", nullable = false, length = 50)),
			@AttributeOverride(name = "issuedId", column = @Column(name = "issued_id")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "remarks", column = @Column(name = "remarks", length = 100)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "created_date", length = 13)) })
	public MrdCasefileIndentIdSequence getId() {
		return this.id;
	}

	public void setId(MrdCasefileIndentIdSequence id) {
		this.id = id;
	}

}
