package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MrdDiagnosisAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "mrd_diagnosis_audit_log")
public class MrdDiagnosisAuditLogModel implements java.io.Serializable {

	private MrdDiagnosisAuditLogIdSequence id;

	public MrdDiagnosisAuditLogModel() {
	}

	public MrdDiagnosisAuditLogModel(MrdDiagnosisAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "admRequestId", column = @Column(name = "adm_request_id")),
			@AttributeOverride(name = "visitId", column = @Column(name = "visit_id", length = 15)),
			@AttributeOverride(name = "id", column = @Column(name = "id", precision = 131089, scale = 0)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 30)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 35)),
			@AttributeOverride(name = "operation", column = @Column(name = "operation")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")) })
	public MrdDiagnosisAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(MrdDiagnosisAuditLogIdSequence id) {
		this.id = id;
	}

}
