package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NetworkCenterDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "network_center_details")
public class NetworkCenterDetailsModel implements java.io.Serializable {

	private int centerId;
	private String ipAddress;
	private String centerName;
	private String subCenterName;
	private String status;
	private String appVersion;
	private Date lastSuccessfulIncrSyncTime;
	private Date lastIncrSyncAttemptedTime;
	private String lastIncrSyncAttemptedStatus;
	private String lastIncrSyncAttemptedMsg;

	public NetworkCenterDetailsModel() {
	}

	public NetworkCenterDetailsModel(int centerId, String ipAddress, String centerName, String subCenterName,
			String status) {
		this.centerId = centerId;
		this.ipAddress = ipAddress;
		this.centerName = centerName;
		this.subCenterName = subCenterName;
		this.status = status;
	}

	public NetworkCenterDetailsModel(int centerId, String ipAddress, String centerName, String subCenterName, String status,
			String appVersion, Date lastSuccessfulIncrSyncTime, Date lastIncrSyncAttemptedTime,
			String lastIncrSyncAttemptedStatus, String lastIncrSyncAttemptedMsg) {
		this.centerId = centerId;
		this.ipAddress = ipAddress;
		this.centerName = centerName;
		this.subCenterName = subCenterName;
		this.status = status;
		this.appVersion = appVersion;
		this.lastSuccessfulIncrSyncTime = lastSuccessfulIncrSyncTime;
		this.lastIncrSyncAttemptedTime = lastIncrSyncAttemptedTime;
		this.lastIncrSyncAttemptedStatus = lastIncrSyncAttemptedStatus;
		this.lastIncrSyncAttemptedMsg = lastIncrSyncAttemptedMsg;
	}

	@Id

	@Column(name = "center_id", unique = true, nullable = false)
	public int getCenterId() {
		return this.centerId;
	}

	public void setCenterId(int centerId) {
		this.centerId = centerId;
	}

	@Column(name = "ip_address", nullable = false)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "center_name", nullable = false)
	public String getCenterName() {
		return this.centerName;
	}

	public void setCenterName(String centerName) {
		this.centerName = centerName;
	}

	@Column(name = "sub_center_name", nullable = false)
	public String getSubCenterName() {
		return this.subCenterName;
	}

	public void setSubCenterName(String subCenterName) {
		this.subCenterName = subCenterName;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "app_version")
	public String getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_successful_incr_sync_time", length = 29)
	public Date getLastSuccessfulIncrSyncTime() {
		return this.lastSuccessfulIncrSyncTime;
	}

	public void setLastSuccessfulIncrSyncTime(Date lastSuccessfulIncrSyncTime) {
		this.lastSuccessfulIncrSyncTime = lastSuccessfulIncrSyncTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_incr_sync_attempted_time", length = 29)
	public Date getLastIncrSyncAttemptedTime() {
		return this.lastIncrSyncAttemptedTime;
	}

	public void setLastIncrSyncAttemptedTime(Date lastIncrSyncAttemptedTime) {
		this.lastIncrSyncAttemptedTime = lastIncrSyncAttemptedTime;
	}

	@Column(name = "last_incr_sync_attempted_status", length = 1)
	public String getLastIncrSyncAttemptedStatus() {
		return this.lastIncrSyncAttemptedStatus;
	}

	public void setLastIncrSyncAttemptedStatus(String lastIncrSyncAttemptedStatus) {
		this.lastIncrSyncAttemptedStatus = lastIncrSyncAttemptedStatus;
	}

	@Column(name = "last_incr_sync_attempted_msg")
	public String getLastIncrSyncAttemptedMsg() {
		return this.lastIncrSyncAttemptedMsg;
	}

	public void setLastIncrSyncAttemptedMsg(String lastIncrSyncAttemptedMsg) {
		this.lastIncrSyncAttemptedMsg = lastIncrSyncAttemptedMsg;
	}

}
