package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ObsoleteVitalsScheduleModel generated by hbm2java
 */
@Entity
@Table(name = "obsolete_vitals_schedule")
public class ObsoleteVitalsScheduleModel implements java.io.Serializable {

	private ObsoleteVitalsScheduleIdSequence id;

	public ObsoleteVitalsScheduleModel() {
	}

	public ObsoleteVitalsScheduleModel(ObsoleteVitalsScheduleIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", nullable = false, length = 15)),
			@AttributeOverride(name = "freqType", column = @Column(name = "freq_type", nullable = false, length = 1)),
			@AttributeOverride(name = "recurrenceDailyId", column = @Column(name = "recurrence_daily_id")),
			@AttributeOverride(name = "repeatInterval", column = @Column(name = "repeat_interval")),
			@AttributeOverride(name = "nextDue", column = @Column(name = "next_due", nullable = false, length = 29)) })
	public ObsoleteVitalsScheduleIdSequence getId() {
		return this.id;
	}

	public void setId(ObsoleteVitalsScheduleIdSequence id) {
		this.id = id;
	}

}
