package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObsoleteMedicationOrderMainModel generated by hbm2java
 */
@Entity
@Table(name = "obsolete_medication_order_main")
public class ObsoleteMedicationOrderMainModel implements java.io.Serializable {

	private int medOrderId;
	private String patientId;
	private Date orderDate;
	private String status;
	private Date finalizedDate;

	public ObsoleteMedicationOrderMainModel() {
	}

	public ObsoleteMedicationOrderMainModel(int medOrderId, String patientId, Date orderDate) {
		this.medOrderId = medOrderId;
		this.patientId = patientId;
		this.orderDate = orderDate;
	}

	public ObsoleteMedicationOrderMainModel(int medOrderId, String patientId, Date orderDate, String status,
			Date finalizedDate) {
		this.medOrderId = medOrderId;
		this.patientId = patientId;
		this.orderDate = orderDate;
		this.status = status;
		this.finalizedDate = finalizedDate;
	}

	@Id

	@Column(name = "med_order_id", unique = true, nullable = false)
	public int getMedOrderId() {
		return this.medOrderId;
	}

	public void setMedOrderId(int medOrderId) {
		this.medOrderId = medOrderId;
	}

	@Column(name = "patient_id", nullable = false, length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 29)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finalized_date", length = 29)
	public Date getFinalizedDate() {
		return this.finalizedDate;
	}

	public void setFinalizedDate(Date finalizedDate) {
		this.finalizedDate = finalizedDate;
	}

}
