package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ObsoletePatientDoctorInstructionsModel generated by hbm2java
 */
@Entity
@Table(name = "obsolete_patient_doctor_instructions")
public class ObsoletePatientDoctorInstructionsModel implements java.io.Serializable {

	private ObsoletePatientDoctorInstructionsIdSequence id;

	public ObsoletePatientDoctorInstructionsModel() {
	}

	public ObsoletePatientDoctorInstructionsModel(ObsoletePatientDoctorInstructionsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prescriptionId", column = @Column(name = "prescription_id", nullable = false)),
			@AttributeOverride(name = "consultationId", column = @Column(name = "consultation_id", nullable = false)),
			@AttributeOverride(name = "instructions", column = @Column(name = "instructions", nullable = false, length = 2000)),
			@AttributeOverride(name = "prescribedDate", column = @Column(name = "prescribed_date", nullable = false, length = 29)),
			@AttributeOverride(name = "activityDueDate", column = @Column(name = "activity_due_date", length = 29)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 50)) })
	public ObsoletePatientDoctorInstructionsIdSequence getId() {
		return this.id;
	}

	public void setId(ObsoletePatientDoctorInstructionsIdSequence id) {
		this.id = id;
	}

}
