package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ObsoleteInsuranceClaimResubmissionModel generated by hbm2java
 */
@Entity
@Table(name = "obsolete_insurance_claim_resubmission")
public class ObsoleteInsuranceClaimResubmissionModel implements java.io.Serializable {

	private ObsoleteInsuranceClaimResubmissionIdSequence id;

	public ObsoleteInsuranceClaimResubmissionModel() {
	}

	public ObsoleteInsuranceClaimResubmissionModel(ObsoleteInsuranceClaimResubmissionIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "claimId", column = @Column(name = "claim_id", nullable = false, length = 15)),
			@AttributeOverride(name = "resubmissionBatchId", column = @Column(name = "resubmission_batch_id", nullable = false, length = 15)) })
	public ObsoleteInsuranceClaimResubmissionIdSequence getId() {
		return this.id;
	}

	public void setId(ObsoleteInsuranceClaimResubmissionIdSequence id) {
		this.id = id;
	}

}
