package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ObsoleteMedicationOrderDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "obsolete_medication_order_details")
public class ObsoleteMedicationOrderDetailsModel implements java.io.Serializable {

	private int medOrderItemId;
	private int medOrderId;
	private Integer prescriptionId;
	private BigDecimal qtyOrdered;
	private String dispenseStatus;
	private BigDecimal qtyDispensed;

	public ObsoleteMedicationOrderDetailsModel() {
	}

	public ObsoleteMedicationOrderDetailsModel(int medOrderItemId, int medOrderId) {
		this.medOrderItemId = medOrderItemId;
		this.medOrderId = medOrderId;
	}

	public ObsoleteMedicationOrderDetailsModel(int medOrderItemId, int medOrderId, Integer prescriptionId,
			BigDecimal qtyOrdered, String dispenseStatus, BigDecimal qtyDispensed) {
		this.medOrderItemId = medOrderItemId;
		this.medOrderId = medOrderId;
		this.prescriptionId = prescriptionId;
		this.qtyOrdered = qtyOrdered;
		this.dispenseStatus = dispenseStatus;
		this.qtyDispensed = qtyDispensed;
	}

	@Id

	@Column(name = "med_order_item_id", unique = true, nullable = false)
	public int getMedOrderItemId() {
		return this.medOrderItemId;
	}

	public void setMedOrderItemId(int medOrderItemId) {
		this.medOrderItemId = medOrderItemId;
	}

	@Column(name = "med_order_id", nullable = false)
	public int getMedOrderId() {
		return this.medOrderId;
	}

	public void setMedOrderId(int medOrderId) {
		this.medOrderId = medOrderId;
	}

	@Column(name = "prescription_id")
	public Integer getPrescriptionId() {
		return this.prescriptionId;
	}

	public void setPrescriptionId(Integer prescriptionId) {
		this.prescriptionId = prescriptionId;
	}

	@Column(name = "qty_ordered", precision = 131089, scale = 0)
	public BigDecimal getQtyOrdered() {
		return this.qtyOrdered;
	}

	public void setQtyOrdered(BigDecimal qtyOrdered) {
		this.qtyOrdered = qtyOrdered;
	}

	@Column(name = "dispense_status", length = 1)
	public String getDispenseStatus() {
		return this.dispenseStatus;
	}

	public void setDispenseStatus(String dispenseStatus) {
		this.dispenseStatus = dispenseStatus;
	}

	@Column(name = "qty_dispensed", precision = 131089, scale = 0)
	public BigDecimal getQtyDispensed() {
		return this.qtyDispensed;
	}

	public void setQtyDispensed(BigDecimal qtyDispensed) {
		this.qtyDispensed = qtyDispensed;
	}

}
