package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ObsoleteIpRecordModel generated by hbm2java
 */
@Entity
@Table(name = "obsolete_ip_record")
public class ObsoleteIpRecordModel implements java.io.Serializable {

	private ObsoleteIpRecordIdSequence id;

	public ObsoleteIpRecordModel() {
	}

	public ObsoleteIpRecordModel(ObsoleteIpRecordIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", nullable = false, length = 15)),
			@AttributeOverride(name = "consultationForms", column = @Column(name = "consultation_forms")) })
	public ObsoleteIpRecordIdSequence getId() {
		return this.id;
	}

	public void setId(ObsoleteIpRecordIdSequence id) {
		this.id = id;
	}

}
