package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OhSampleRegistrationModel generated by hbm2java
 */
@Entity
@Table(name = "oh_sample_registration")
public class OhSampleRegistrationModel implements java.io.Serializable {

	private OhSampleRegistrationIdSequence id;

	public OhSampleRegistrationModel() {
	}

	public OhSampleRegistrationModel(OhSampleRegistrationIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", nullable = false, length = 15)),
			@AttributeOverride(name = "visitId", column = @Column(name = "visit_id", nullable = false, length = 15)),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 150)),
			@AttributeOverride(name = "testId", column = @Column(name = "test_id", nullable = false, length = 20)),
			@AttributeOverride(name = "ohName", column = @Column(name = "oh_name", length = 15)),
			@AttributeOverride(name = "sampleId", column = @Column(name = "sample_id", length = 20)),
			@AttributeOverride(name = "prescribedId", column = @Column(name = "prescribed_id", nullable = false)) })
	public OhSampleRegistrationIdSequence getId() {
		return this.id;
	}

	public void setId(OhSampleRegistrationIdSequence id) {
		this.id = id;
	}

}
