package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OperationScheduleModel generated by hbm2java
 */
@Entity
@Table(name = "operation_schedule")
public class OperationScheduleModel implements java.io.Serializable {

	private OperationScheduleIdSequence id;

	public OperationScheduleModel() {
	}

	public OperationScheduleModel(OperationScheduleIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", nullable = false, length = 15)),
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", nullable = false, length = 15)),
			@AttributeOverride(name = "deptId", column = @Column(name = "dept_id", nullable = false, length = 15)),
			@AttributeOverride(name = "operationId", column = @Column(name = "operation_id", nullable = false, length = 100)),
			@AttributeOverride(name = "theatreId", column = @Column(name = "theatre_id", nullable = false, length = 100)),
			@AttributeOverride(name = "equipmentId", column = @Column(name = "equipment_id", nullable = false, length = 2000)),
			@AttributeOverride(name = "operationDate", column = @Column(name = "operation_date", length = 13)),
			@AttributeOverride(name = "stTime", column = @Column(name = "st_time", length = 15)),
			@AttributeOverride(name = "expectedEndTime", column = @Column(name = "expected_end_time", length = 15)),
			@AttributeOverride(name = "surgeon", column = @Column(name = "surgeon", nullable = false, length = 60)),
			@AttributeOverride(name = "asstSurgeon", column = @Column(name = "asst_surgeon", length = 60)),
			@AttributeOverride(name = "anaesthest", column = @Column(name = "anaesthest", length = 60)),
			@AttributeOverride(name = "asstAnaesthest", column = @Column(name = "asst_anaesthest", length = 60)),
			@AttributeOverride(name = "conducted", column = @Column(name = "conducted", nullable = false, length = 60)),
			@AttributeOverride(name = "billRaised", column = @Column(name = "bill_raised", nullable = false, length = 30)),
			@AttributeOverride(name = "surgeonCharges", column = @Column(name = "surgeon_charges", nullable = false, precision = 15)),
			@AttributeOverride(name = "asstSurgeonCharges", column = @Column(name = "asst_surgeon_charges", precision = 15)),
			@AttributeOverride(name = "anaesthestCharges", column = @Column(name = "anaesthest_charges", nullable = false, precision = 15)),
			@AttributeOverride(name = "asstAnaesthestCharges", column = @Column(name = "asst_anaesthest_charges", precision = 15)),
			@AttributeOverride(name = "equipmentCharges", column = @Column(name = "equipment_charges", nullable = false, precision = 15)),
			@AttributeOverride(name = "opScheduleId", column = @Column(name = "op_schedule_id", nullable = false, length = 200)),
			@AttributeOverride(name = "otScheduleStatus", column = @Column(name = "ot_schedule_status", length = 1)) })
	public OperationScheduleIdSequence getId() {
		return this.id;
	}

	public void setId(OperationScheduleIdSequence id) {
		this.id = id;
	}

}
