package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.operations.OperationMasterModel;
import com.insta.hms.mdm.organization.OrganizationDetailsModel;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OperationOrgDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "operation_org_details")
public class OperationOrgDetailsModel implements java.io.Serializable {

	private OperationOrgDetailsIdSequence id;
	private OperationMasterModel operationMaster;
	private OrganizationDetailsModel organizationDetails;
	private boolean applicable;
	private String itemCode;
	private String codeType;
	private String baseRateSheetId;
	private String isOverride;

	public OperationOrgDetailsModel() {
	}

	public OperationOrgDetailsModel(OperationOrgDetailsIdSequence id, OperationMasterModel operationMaster,
			OrganizationDetailsModel organizationDetails, boolean applicable) {
		this.id = id;
		this.operationMaster = operationMaster;
		this.organizationDetails = organizationDetails;
		this.applicable = applicable;
	}

	public OperationOrgDetailsModel(OperationOrgDetailsIdSequence id, OperationMasterModel operationMaster,
			OrganizationDetailsModel organizationDetails, boolean applicable, String itemCode, String codeType,
			String baseRateSheetId, String isOverride) {
		this.id = id;
		this.operationMaster = operationMaster;
		this.organizationDetails = organizationDetails;
		this.applicable = applicable;
		this.itemCode = itemCode;
		this.codeType = codeType;
		this.baseRateSheetId = baseRateSheetId;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "operationId", column = @Column(name = "operation_id", nullable = false, length = 10)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 10)) })
	public OperationOrgDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(OperationOrgDetailsIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operation_id", nullable = false, insertable = false, updatable = false)
	public OperationMasterModel getOperationMasterModel() {
		return this.operationMaster;
	}

	public void setOperationMasterModel(OperationMasterModel operationMaster) {
		this.operationMaster = operationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false, insertable = false, updatable = false)
	public OrganizationDetailsModel getOrganizationDetailsModel() {
		return this.organizationDetails;
	}

	public void setOrganizationDetailsModel(OrganizationDetailsModel organizationDetails) {
		this.organizationDetails = organizationDetails;
	}

	@Column(name = "applicable", nullable = false)
	public boolean isApplicable() {
		return this.applicable;
	}

	public void setApplicable(boolean applicable) {
		this.applicable = applicable;
	}

	@Column(name = "item_code", length = 600)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "code_type", length = 50)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "base_rate_sheet_id", length = 10)
	public String getBaseRateSheetId() {
		return this.baseRateSheetId;
	}

	public void setBaseRateSheetId(String baseRateSheetId) {
		this.baseRateSheetId = baseRateSheetId;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
