package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OperationChargesBackupModel generated by hbm2java
 */
@Entity
@Table(name = "operation_charges_backup")
public class OperationChargesBackupModel implements java.io.Serializable {

	private OperationChargesBackupIdSequence id;

	public OperationChargesBackupModel() {
	}

	public OperationChargesBackupModel(OperationChargesBackupIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "bkpTime", column = @Column(name = "bkp_time", length = 29)),
			@AttributeOverride(name = "opId", column = @Column(name = "op_id")),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type")),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id")),
			@AttributeOverride(name = "surgAsstanceCharge", column = @Column(name = "surg_asstance_charge", precision = 15)),
			@AttributeOverride(name = "surgeonCharge", column = @Column(name = "surgeon_charge", precision = 15)),
			@AttributeOverride(name = "anesthetistCharge", column = @Column(name = "anesthetist_charge", precision = 15)),
			@AttributeOverride(name = "surgAsstDiscount", column = @Column(name = "surg_asst_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "surgDiscount", column = @Column(name = "surg_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "anestDiscount", column = @Column(name = "anest_discount", nullable = false, precision = 15)) })
	public OperationChargesBackupIdSequence getId() {
		return this.id;
	}

	public void setId(OperationChargesBackupIdSequence id) {
		this.id = id;
	}

}
