package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OperationTeamModel generated by hbm2java
 */
@Entity
@Table(name = "operation_team")
public class OperationTeamModel implements java.io.Serializable {

	private OperationTeamIdSequence id;

	public OperationTeamModel() {
	}

	public OperationTeamModel(OperationTeamIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "operationTeamId", column = @Column(name = "operation_team_id", nullable = false)),
			@AttributeOverride(name = "operationDetailsId", column = @Column(name = "operation_details_id", nullable = false)),
			@AttributeOverride(name = "resourceId", column = @Column(name = "resource_id", length = 30)),
			@AttributeOverride(name = "operationSpeciality", column = @Column(name = "operation_speciality", length = 50)) })
	public OperationTeamIdSequence getId() {
		return this.id;
	}

	public void setId(OperationTeamIdSequence id) {
		this.id = id;
	}

}
