package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OpthalDoctorFundusExamModel generated by hbm2java
 */
@Entity
@Table(name = "opthal_doctor_fundus_exam")
public class OpthalDoctorFundusExamModel implements java.io.Serializable {

	private int fundusExamId;
	private OpthalDoctorExamMainModel opthalDoctorExamMain;
	private String patientId;
	private Integer consultId;
	private String opticdiskRe;
	private String cdratioRe;
	private String notesRe;
	private String opticdiskLe;
	private String cdratioLe;
	private String notesLe;
	private Date startTime;
	private Date endTime;

	public OpthalDoctorFundusExamModel() {
	}

	public OpthalDoctorFundusExamModel(int fundusExamId) {
		this.fundusExamId = fundusExamId;
	}

	public OpthalDoctorFundusExamModel(int fundusExamId, OpthalDoctorExamMainModel opthalDoctorExamMain, String patientId,
			Integer consultId, String opticdiskRe, String cdratioRe, String notesRe, String opticdiskLe,
			String cdratioLe, String notesLe, Date startTime, Date endTime) {
		this.fundusExamId = fundusExamId;
		this.opthalDoctorExamMain = opthalDoctorExamMain;
		this.patientId = patientId;
		this.consultId = consultId;
		this.opticdiskRe = opticdiskRe;
		this.cdratioRe = cdratioRe;
		this.notesRe = notesRe;
		this.opticdiskLe = opticdiskLe;
		this.cdratioLe = cdratioLe;
		this.notesLe = notesLe;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id

	@Column(name = "fundus_exam_id", unique = true, nullable = false)
	public int getFundusExamId() {
		return this.fundusExamId;
	}

	public void setFundusExamId(int fundusExamId) {
		this.fundusExamId = fundusExamId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_exam_id")
	public OpthalDoctorExamMainModel getOpthalDoctorExamMainModel() {
		return this.opthalDoctorExamMain;
	}

	public void setOpthalDoctorExamMainModel(OpthalDoctorExamMainModel opthalDoctorExamMain) {
		this.opthalDoctorExamMain = opthalDoctorExamMain;
	}

	@Column(name = "patient_id", length = 50)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "consult_id")
	public Integer getConsultId() {
		return this.consultId;
	}

	public void setConsultId(Integer consultId) {
		this.consultId = consultId;
	}

	@Column(name = "opticdisk_re", length = 50)
	public String getOpticdiskRe() {
		return this.opticdiskRe;
	}

	public void setOpticdiskRe(String opticdiskRe) {
		this.opticdiskRe = opticdiskRe;
	}

	@Column(name = "cdratio_re", length = 50)
	public String getCdratioRe() {
		return this.cdratioRe;
	}

	public void setCdratioRe(String cdratioRe) {
		this.cdratioRe = cdratioRe;
	}

	@Column(name = "notes_re", length = 200)
	public String getNotesRe() {
		return this.notesRe;
	}

	public void setNotesRe(String notesRe) {
		this.notesRe = notesRe;
	}

	@Column(name = "opticdisk_le", length = 50)
	public String getOpticdiskLe() {
		return this.opticdiskLe;
	}

	public void setOpticdiskLe(String opticdiskLe) {
		this.opticdiskLe = opticdiskLe;
	}

	@Column(name = "cdratio_le", length = 50)
	public String getCdratioLe() {
		return this.cdratioLe;
	}

	public void setCdratioLe(String cdratioLe) {
		this.cdratioLe = cdratioLe;
	}

	@Column(name = "notes_le", length = 200)
	public String getNotesLe() {
		return this.notesLe;
	}

	public void setNotesLe(String notesLe) {
		this.notesLe = notesLe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 29)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 29)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
