package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OpthalTestDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "opthal_test_details")
public class OpthalTestDetailsModel implements java.io.Serializable {

	private int valueId;
	private EyeTestMasterModel eyeTestMaster;
	private EyeTestAttribMasterModel eyeTestAttribMaster;
	private OpthalTestMainModel opthalTestMain;
	private String testValues;

	public OpthalTestDetailsModel() {
	}

	public OpthalTestDetailsModel(int valueId, EyeTestMasterModel eyeTestMaster, EyeTestAttribMasterModel eyeTestAttribMaster,
			OpthalTestMainModel opthalTestMain) {
		this.valueId = valueId;
		this.eyeTestMaster = eyeTestMaster;
		this.eyeTestAttribMaster = eyeTestAttribMaster;
		this.opthalTestMain = opthalTestMain;
	}

	public OpthalTestDetailsModel(int valueId, EyeTestMasterModel eyeTestMaster, EyeTestAttribMasterModel eyeTestAttribMaster,
			OpthalTestMainModel opthalTestMain, String testValues) {
		this.valueId = valueId;
		this.eyeTestMaster = eyeTestMaster;
		this.eyeTestAttribMaster = eyeTestAttribMaster;
		this.opthalTestMain = opthalTestMain;
		this.testValues = testValues;
	}

	@Id

	@Column(name = "value_id", unique = true, nullable = false)
	public int getValueId() {
		return this.valueId;
	}

	public void setValueId(int valueId) {
		this.valueId = valueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_id", nullable = false)
	public EyeTestMasterModel getEyeTestMasterModel() {
		return this.eyeTestMaster;
	}

	public void setEyeTestMasterModel(EyeTestMasterModel eyeTestMaster) {
		this.eyeTestMaster = eyeTestMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_id", nullable = false)
	public EyeTestAttribMasterModel getEyeTestAttribMasterModel() {
		return this.eyeTestAttribMaster;
	}

	public void setEyeTestAttribMasterModel(EyeTestAttribMasterModel eyeTestAttribMaster) {
		this.eyeTestAttribMaster = eyeTestAttribMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "opthal_id", nullable = false)
	public OpthalTestMainModel getOpthalTestMainModel() {
		return this.opthalTestMain;
	}

	public void setOpthalTestMainModel(OpthalTestMainModel opthalTestMain) {
		this.opthalTestMain = opthalTestMain;
	}

	@Column(name = "test_values", length = 200)
	public String getTestValues() {
		return this.testValues;
	}

	public void setTestValues(String testValues) {
		this.testValues = testValues;
	}

}
