package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OpthalTestAttributesModel generated by hbm2java
 */
@Entity
@Table(name = "opthal_test_attributes")
public class OpthalTestAttributesModel implements java.io.Serializable {

	private int testAttribId;
	private EyeTestMasterModel eyeTestMaster;
	private EyeTestAttribMasterModel eyeTestAttribMaster;
	private Integer displayOrder;

	public OpthalTestAttributesModel() {
	}

	public OpthalTestAttributesModel(int testAttribId, EyeTestMasterModel eyeTestMaster,
			EyeTestAttribMasterModel eyeTestAttribMaster) {
		this.testAttribId = testAttribId;
		this.eyeTestMaster = eyeTestMaster;
		this.eyeTestAttribMaster = eyeTestAttribMaster;
	}

	public OpthalTestAttributesModel(int testAttribId, EyeTestMasterModel eyeTestMaster, EyeTestAttribMasterModel eyeTestAttribMaster,
			Integer displayOrder) {
		this.testAttribId = testAttribId;
		this.eyeTestMaster = eyeTestMaster;
		this.eyeTestAttribMaster = eyeTestAttribMaster;
		this.displayOrder = displayOrder;
	}

	@Id

	@Column(name = "test_attrib_id", unique = true, nullable = false)
	public int getTestAttribId() {
		return this.testAttribId;
	}

	public void setTestAttribId(int testAttribId) {
		this.testAttribId = testAttribId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_id", nullable = false)
	public EyeTestMasterModel getEyeTestMasterModel() {
		return this.eyeTestMaster;
	}

	public void setEyeTestMasterModel(EyeTestMasterModel eyeTestMaster) {
		this.eyeTestMaster = eyeTestMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_id", nullable = false)
	public EyeTestAttribMasterModel getEyeTestAttribMasterModel() {
		return this.eyeTestAttribMaster;
	}

	public void setEyeTestAttribMasterModel(EyeTestAttribMasterModel eyeTestAttribMaster) {
		this.eyeTestAttribMaster = eyeTestAttribMaster;
	}

	@Column(name = "display_order")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

}
