package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.core.clinical.outpatient.DoctorConsultationModel;
import com.insta.hms.core.patient.registration.PatientRegistrationModel;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OpthalDoctorExamMainModel generated by hbm2java
 */
@Entity
@Table(name = "opthal_doctor_exam_main")
public class OpthalDoctorExamMainModel implements java.io.Serializable {

	private int doctorExamId;
	private DoctorConsultationModel doctorConsultation;
	private PatientRegistrationModel patientRegistration;
	private String doctorNotes;
	private Set opthalDoctorOverallExams = new HashSet(0);
	private Set opthalDoctorLensExams = new HashSet(0);
	private Set opthalDoctorFundusExams = new HashSet(0);

	public OpthalDoctorExamMainModel() {
	}

	public OpthalDoctorExamMainModel(int doctorExamId) {
		this.doctorExamId = doctorExamId;
	}

	public OpthalDoctorExamMainModel(int doctorExamId, DoctorConsultationModel doctorConsultation,
			PatientRegistrationModel patientRegistration, String doctorNotes, Set opthalDoctorOverallExams,
			Set opthalDoctorLensExams, Set opthalDoctorFundusExams) {
		this.doctorExamId = doctorExamId;
		this.doctorConsultation = doctorConsultation;
		this.patientRegistration = patientRegistration;
		this.doctorNotes = doctorNotes;
		this.opthalDoctorOverallExams = opthalDoctorOverallExams;
		this.opthalDoctorLensExams = opthalDoctorLensExams;
		this.opthalDoctorFundusExams = opthalDoctorFundusExams;
	}

	@Id

	@Column(name = "doctor_exam_id", unique = true, nullable = false)
	public int getDoctorExamId() {
		return this.doctorExamId;
	}

	public void setDoctorExamId(int doctorExamId) {
		this.doctorExamId = doctorExamId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consult_id")
	public DoctorConsultationModel getDoctorConsultationModel() {
		return this.doctorConsultation;
	}

	public void setDoctorConsultationModel(DoctorConsultationModel doctorConsultation) {
		this.doctorConsultation = doctorConsultation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id")
	public PatientRegistrationModel getPatientRegistrationModel() {
		return this.patientRegistration;
	}

	public void setPatientRegistrationModel(PatientRegistrationModel patientRegistration) {
		this.patientRegistration = patientRegistration;
	}

	@Column(name = "doctor_notes", length = 200)
	public String getDoctorNotes() {
		return this.doctorNotes;
	}

	public void setDoctorNotes(String doctorNotes) {
		this.doctorNotes = doctorNotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opthalDoctorExamMain")
	public Set getOpthalDoctorOverallExams() {
		return this.opthalDoctorOverallExams;
	}

	public void setOpthalDoctorOverallExams(Set opthalDoctorOverallExams) {
		this.opthalDoctorOverallExams = opthalDoctorOverallExams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opthalDoctorExamMain")
	public Set getOpthalDoctorLensExams() {
		return this.opthalDoctorLensExams;
	}

	public void setOpthalDoctorLensExams(Set opthalDoctorLensExams) {
		this.opthalDoctorLensExams = opthalDoctorLensExams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opthalDoctorExamMain")
	public Set getOpthalDoctorFundusExams() {
		return this.opthalDoctorFundusExams;
	}

	public void setOpthalDoctorFundusExams(Set opthalDoctorFundusExams) {
		this.opthalDoctorFundusExams = opthalDoctorFundusExams;
	}

}
