package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OtActivitiesModel generated by hbm2java
 */
@Entity
@Table(name = "ot_activities")
public class OtActivitiesModel implements java.io.Serializable {

	private OtActivitiesIdSequence id;

	public OtActivitiesModel() {
	}

	public OtActivitiesModel(OtActivitiesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", nullable = false, length = 20)),
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", nullable = false, length = 20)),
			@AttributeOverride(name = "activityGroup", column = @Column(name = "activity_group", nullable = false, length = 10)),
			@AttributeOverride(name = "activityId", column = @Column(name = "activity_id", nullable = false, length = 50)),
			@AttributeOverride(name = "activityDept", column = @Column(name = "activity_dept", length = 20)),
			@AttributeOverride(name = "date", column = @Column(name = "date")),
			@AttributeOverride(name = "remarks", column = @Column(name = "remarks", length = 200)),
			@AttributeOverride(name = "operationRef", column = @Column(name = "operation_ref", precision = 131089, scale = 0)),
			@AttributeOverride(name = "cancelStatus", column = @Column(name = "cancel_status", length = 10)),
			@AttributeOverride(name = "prescribedId", column = @Column(name = "prescribed_id", precision = 131089, scale = 0)) })
	public OtActivitiesIdSequence getId() {
		return this.id;
	}

	public void setId(OtActivitiesIdSequence id) {
		this.id = id;
	}

}
