package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OtConsumablesIdSequence generated by hbm2java
 */
@Embeddable
public class OtConsumablesIdSequence implements java.io.Serializable {

	private String operationId;
	private BigDecimal qtyNeeded;
	private Integer consumableId;
	private Character status;

	public OtConsumablesIdSequence() {
	}

	public OtConsumablesIdSequence(String operationId, BigDecimal qtyNeeded, Integer consumableId, Character status) {
		this.operationId = operationId;
		this.qtyNeeded = qtyNeeded;
		this.consumableId = consumableId;
		this.status = status;
	}

	@Column(name = "operation_id", length = 20)
	public String getOperationId() {
		return this.operationId;
	}

	public void setOperationId(String operationId) {
		this.operationId = operationId;
	}

	@Column(name = "qty_needed", precision = 131089, scale = 0)
	public BigDecimal getQtyNeeded() {
		return this.qtyNeeded;
	}

	public void setQtyNeeded(BigDecimal qtyNeeded) {
		this.qtyNeeded = qtyNeeded;
	}

	@Column(name = "consumable_id")
	public Integer getConsumableId() {
		return this.consumableId;
	}

	public void setConsumableId(Integer consumableId) {
		this.consumableId = consumableId;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OtConsumablesIdSequence))
			return false;
		OtConsumablesIdSequence castOther = (OtConsumablesIdSequence) other;

		return ((this.getOperationId() == castOther.getOperationId()) || (this.getOperationId() != null
				&& castOther.getOperationId() != null && this.getOperationId().equals(castOther.getOperationId())))
				&& ((this.getQtyNeeded() == castOther.getQtyNeeded()) || (this.getQtyNeeded() != null
						&& castOther.getQtyNeeded() != null && this.getQtyNeeded().equals(castOther.getQtyNeeded())))
				&& ((this.getConsumableId() == castOther.getConsumableId())
						|| (this.getConsumableId() != null && castOther.getConsumableId() != null
								&& this.getConsumableId().equals(castOther.getConsumableId())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOperationId() == null ? 0 : this.getOperationId().hashCode());
		result = 37 * result + (getQtyNeeded() == null ? 0 : this.getQtyNeeded().hashCode());
		result = 37 * result + (getConsumableId() == null ? 0 : this.getConsumableId().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
