package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OtherChargeMasterModel generated by hbm2java
 */
@Entity
@Table(name = "other_charge_master")
public class OtherChargeMasterModel implements java.io.Serializable {

	private OtherChargeMasterIdSequence id;

	public OtherChargeMasterModel() {
	}

	public OtherChargeMasterModel(OtherChargeMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "chargeName", column = @Column(name = "charge_name", nullable = false, length = 50)),
			@AttributeOverride(name = "charge", column = @Column(name = "charge", nullable = false, precision = 15)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)) })
	public OtherChargeMasterIdSequence getId() {
		return this.id;
	}

	public void setId(OtherChargeMasterIdSequence id) {
		this.id = id;
	}

}
