package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PackOrgDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "pack_org_details")
public class PackOrgDetailsModel implements java.io.Serializable {

	private PackOrgDetailsIdSequence id;
	private Boolean applicable;
	private String itemCode;
	private String codeType;
	private String baseRateSheetId;
	private String isOverride;

	public PackOrgDetailsModel() {
	}

	public PackOrgDetailsModel(PackOrgDetailsIdSequence id) {
		this.id = id;
	}

	public PackOrgDetailsModel(PackOrgDetailsIdSequence id, Boolean applicable, String itemCode, String codeType,
			String baseRateSheetId, String isOverride) {
		this.id = id;
		this.applicable = applicable;
		this.itemCode = itemCode;
		this.codeType = codeType;
		this.baseRateSheetId = baseRateSheetId;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id", nullable = false)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 15)) })
	public PackOrgDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(PackOrgDetailsIdSequence id) {
		this.id = id;
	}

	@Column(name = "applicable")
	public Boolean getApplicable() {
		return this.applicable;
	}

	public void setApplicable(Boolean applicable) {
		this.applicable = applicable;
	}

	@Column(name = "item_code", length = 15)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "code_type", length = 50)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "base_rate_sheet_id", length = 10)
	public String getBaseRateSheetId() {
		return this.baseRateSheetId;
	}

	public void setBaseRateSheetId(String baseRateSheetId) {
		this.baseRateSheetId = baseRateSheetId;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
