package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PackageChargesModel generated by hbm2java
 */
@Entity
@Table(name = "package_charges")
public class PackageChargesModel implements java.io.Serializable {

	private PackageChargesIdSequence id;
	private BigDecimal charge;
	private BigDecimal discount;
	private String isOverride;

	public PackageChargesModel() {
	}

	public PackageChargesModel(PackageChargesIdSequence id, BigDecimal discount) {
		this.id = id;
		this.discount = discount;
	}

	public PackageChargesModel(PackageChargesIdSequence id, BigDecimal charge, BigDecimal discount, String isOverride) {
		this.id = id;
		this.charge = charge;
		this.discount = discount;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id", nullable = false)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 15)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", nullable = false, length = 50)) })
	public PackageChargesIdSequence getId() {
		return this.id;
	}

	public void setId(PackageChargesIdSequence id) {
		this.id = id;
	}

	@Column(name = "charge", precision = 15)
	public BigDecimal getCharge() {
		return this.charge;
	}

	public void setCharge(BigDecimal charge) {
		this.charge = charge;
	}

	@Column(name = "discount", nullable = false, precision = 15)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
