package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PasswordRuleModel generated by hbm2java
 */
@Entity
@Table(name = "password_rule")
public class PasswordRuleModel implements java.io.Serializable {

	private PasswordRuleIdSequence id;

	public PasswordRuleModel() {
	}

	public PasswordRuleModel(PasswordRuleIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "minLen", column = @Column(name = "min_len")),
			@AttributeOverride(name = "minLower", column = @Column(name = "min_lower")),
			@AttributeOverride(name = "minUpper", column = @Column(name = "min_upper")),
			@AttributeOverride(name = "minDigits", column = @Column(name = "min_digits")),
			@AttributeOverride(name = "minSpecialChars", column = @Column(name = "min_special_chars")),
			@AttributeOverride(name = "specailCharList", column = @Column(name = "specail_char_list", length = 50)),
			@AttributeOverride(name = "lastPasswordFrequency", column = @Column(name = "last_password_frequency")),
			@AttributeOverride(name = "passwordChangeFreqDays", column = @Column(name = "password_change_freq_days")),
			@AttributeOverride(name = "passwordChangeNotifyDays", column = @Column(name = "password_change_notify_days")),
			@AttributeOverride(name = "maxLoginAttempt", column = @Column(name = "max_login_attempt")) })
	public PasswordRuleIdSequence getId() {
		return this.id;
	}

	public void setId(PasswordRuleIdSequence id) {
		this.id = id;
	}

}
