package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PasswordHistoryIdSequence generated by hbm2java
 */
@Embeddable
public class PasswordHistoryIdSequence implements java.io.Serializable {

	private String username;
	private String prevPassword;
	private Integer passwordSeqNo;

	public PasswordHistoryIdSequence() {
	}

	public PasswordHistoryIdSequence(String username, String prevPassword, Integer passwordSeqNo) {
		this.username = username;
		this.prevPassword = prevPassword;
		this.passwordSeqNo = passwordSeqNo;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "prev_password", length = 100)
	public String getPrevPassword() {
		return this.prevPassword;
	}

	public void setPrevPassword(String prevPassword) {
		this.prevPassword = prevPassword;
	}

	@Column(name = "password_seq_no")
	public Integer getPasswordSeqNo() {
		return this.passwordSeqNo;
	}

	public void setPasswordSeqNo(Integer passwordSeqNo) {
		this.passwordSeqNo = passwordSeqNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PasswordHistoryIdSequence))
			return false;
		PasswordHistoryIdSequence castOther = (PasswordHistoryIdSequence) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getPrevPassword() == castOther.getPrevPassword())
						|| (this.getPrevPassword() != null && castOther.getPrevPassword() != null
								&& this.getPrevPassword().equals(castOther.getPrevPassword())))
				&& ((this.getPasswordSeqNo() == castOther.getPasswordSeqNo())
						|| (this.getPasswordSeqNo() != null && castOther.getPasswordSeqNo() != null
								&& this.getPasswordSeqNo().equals(castOther.getPasswordSeqNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getPrevPassword() == null ? 0 : this.getPrevPassword().hashCode());
		result = 37 * result + (getPasswordSeqNo() == null ? 0 : this.getPasswordSeqNo().hashCode());
		return result;
	}

}
