package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PasswordHistoryModel generated by hbm2java
 */
@Entity
@Table(name = "password_history")
public class PasswordHistoryModel implements java.io.Serializable {

	private PasswordHistoryIdSequence id;

	public PasswordHistoryModel() {
	}

	public PasswordHistoryModel(PasswordHistoryIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "username", column = @Column(name = "username", length = 30)),
			@AttributeOverride(name = "prevPassword", column = @Column(name = "prev_password", length = 100)),
			@AttributeOverride(name = "passwordSeqNo", column = @Column(name = "password_seq_no")) })
	public PasswordHistoryIdSequence getId() {
		return this.id;
	}

	public void setId(PasswordHistoryIdSequence id) {
		this.id = id;
	}

}
