package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatExportDataPrefModel generated by hbm2java
 */
@Entity
@Table(name = "pat_export_data_pref")
public class PatExportDataPrefModel implements java.io.Serializable {

	private PatExportDataPrefIdSequence id;

	public PatExportDataPrefModel() {
	}

	public PatExportDataPrefModel(PatExportDataPrefIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "hourlyTime", column = @Column(name = "hourly_time")),
			@AttributeOverride(name = "secondsTime", column = @Column(name = "seconds_time")) })
	public PatExportDataPrefIdSequence getId() {
		return this.id;
	}

	public void setId(PatExportDataPrefIdSequence id) {
		this.id = id;
	}

}
