package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientDepositsSetoffAdjustmentsModel generated by hbm2java
 */
@Entity
@Table(name = "patient_deposits_setoff_adjustments")
public class PatientDepositsSetoffAdjustmentsModel implements java.io.Serializable {

	private PatientDepositsSetoffAdjustmentsIdSequence id;

	public PatientDepositsSetoffAdjustmentsModel() {
	}
	
	public PatientDepositsSetoffAdjustmentsModel(String mrNo, String billNo, BigDecimal amount, String depositType, boolean isMultiPkg) {
	  Date now = new Date();
	  this.id = new PatientDepositsSetoffAdjustmentsIdSequence(mrNo, billNo, amount, now, now, depositType, isMultiPkg);
	}

	public PatientDepositsSetoffAdjustmentsModel(PatientDepositsSetoffAdjustmentsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", nullable = false, length = 15)),
			@AttributeOverride(name = "billNo", column = @Column(name = "bill_no", nullable = false, length = 15)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, precision = 15)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "created_date", nullable = false, length = 29)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "depositFor", column = @Column(name = "deposit_for", length = 1)),
			@AttributeOverride(name = "isMultiPkg", column = @Column(name = "is_multi_pkg")) })
	public PatientDepositsSetoffAdjustmentsIdSequence getId() {
		return this.id;
	}

	public void setId(PatientDepositsSetoffAdjustmentsIdSequence id) {
		this.id = id;
	}

}
