package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientGeneralImagesModel generated by hbm2java
 */
@Entity
@Table(name = "patient_general_images")
public class PatientGeneralImagesModel implements java.io.Serializable {

	private PatientGeneralImagesIdSequence id;
	private String imageName;
	private String contentType;
	private byte[] imageContent;

	public PatientGeneralImagesModel() {
	}

	public PatientGeneralImagesModel(PatientGeneralImagesIdSequence id, String imageName, String contentType, byte[] imageContent) {
		this.id = id;
		this.imageName = imageName;
		this.contentType = contentType;
		this.imageContent = imageContent;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "imageId", column = @Column(name = "image_id", nullable = false)),
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", nullable = false, length = 15)) })
	public PatientGeneralImagesIdSequence getId() {
		return this.id;
	}

	public void setId(PatientGeneralImagesIdSequence id) {
		this.id = id;
	}

	@Column(name = "image_name", nullable = false)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "content_type", nullable = false)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "image_content", nullable = false)
	public byte[] getImageContent() {
		return this.imageContent;
	}

	public void setImageContent(byte[] imageContent) {
		this.imageContent = imageContent;
	}

}
