package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientStandingInstructionsObsoleteModel generated by hbm2java
 */
@Entity
@Table(name = "patient_standing_instructions_obsolete")
public class PatientStandingInstructionsObsoleteModel implements java.io.Serializable {

	private PatientStandingInstructionsObsoleteIdSequence id;

	public PatientStandingInstructionsObsoleteModel() {
	}

	public PatientStandingInstructionsObsoleteModel(PatientStandingInstructionsObsoleteIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prescriptionId", column = @Column(name = "prescription_id", nullable = false)),
			@AttributeOverride(name = "visitId", column = @Column(name = "visit_id", nullable = false, length = 15)),
			@AttributeOverride(name = "doctorId", column = @Column(name = "doctor_id", nullable = false, length = 15)),
			@AttributeOverride(name = "prescribedDate", column = @Column(name = "prescribed_date", nullable = false, length = 29)),
			@AttributeOverride(name = "type", column = @Column(name = "type", length = 1)),
			@AttributeOverride(name = "itemName", column = @Column(name = "item_name", length = 100)),
			@AttributeOverride(name = "medicineDosage", column = @Column(name = "medicine_dosage", precision = 10)),
			@AttributeOverride(name = "remarks", column = @Column(name = "remarks", length = 2000)),
			@AttributeOverride(name = "freqType", column = @Column(name = "freq_type", nullable = false, length = 1)),
			@AttributeOverride(name = "recurrenceDailyId", column = @Column(name = "recurrence_daily_id")),
			@AttributeOverride(name = "repeatInterval", column = @Column(name = "repeat_interval")),
			@AttributeOverride(name = "orderLeadTime", column = @Column(name = "order_lead_time")),
			@AttributeOverride(name = "discontinued", column = @Column(name = "discontinued", nullable = false, length = 1)),
			@AttributeOverride(name = "nextDue", column = @Column(name = "next_due", nullable = false, length = 29)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 50)),
			@AttributeOverride(name = "ispackage", column = @Column(name = "ispackage")),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", length = 50)),
			@AttributeOverride(name = "routeOfAdmin", column = @Column(name = "route_of_admin")),
			@AttributeOverride(name = "itemFormId", column = @Column(name = "item_form_id")),
			@AttributeOverride(name = "itemStrength", column = @Column(name = "item_strength", length = 50)) })
	public PatientStandingInstructionsObsoleteIdSequence getId() {
		return this.id;
	}

	public void setId(PatientStandingInstructionsObsoleteIdSequence id) {
		this.id = id;
	}

}
