package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientVaccinationModel generated by hbm2java
 */
@Entity
@Table(name = "patient_vaccination")
public class PatientVaccinationModel implements java.io.Serializable {

	private int patVaccId;
	private String mrNo;
	private int vaccineDoseId;
	private Date vaccinationDatetime;
	private String vaccBy;
	private String vaccDoctorId;
	private String medName;
	private String manufacturer;
	private Date expiryDate;
	private String batch;
	private String modUser;
	private Date modTime;
	private Character vaccinationStatus;
	private String reasonForNot;
	private String remarks;

	public PatientVaccinationModel() {
	}

	public PatientVaccinationModel(int patVaccId, String mrNo, int vaccineDoseId) {
		this.patVaccId = patVaccId;
		this.mrNo = mrNo;
		this.vaccineDoseId = vaccineDoseId;
	}

	public PatientVaccinationModel(int patVaccId, String mrNo, int vaccineDoseId, Date vaccinationDatetime, String vaccBy,
			String vaccDoctorId, String medName, String manufacturer, Date expiryDate, String batch, String modUser,
			Date modTime, Character vaccinationStatus, String reasonForNot, String remarks) {
		this.patVaccId = patVaccId;
		this.mrNo = mrNo;
		this.vaccineDoseId = vaccineDoseId;
		this.vaccinationDatetime = vaccinationDatetime;
		this.vaccBy = vaccBy;
		this.vaccDoctorId = vaccDoctorId;
		this.medName = medName;
		this.manufacturer = manufacturer;
		this.expiryDate = expiryDate;
		this.batch = batch;
		this.modUser = modUser;
		this.modTime = modTime;
		this.vaccinationStatus = vaccinationStatus;
		this.reasonForNot = reasonForNot;
		this.remarks = remarks;
	}

	@Id

	@Column(name = "pat_vacc_id", unique = true, nullable = false)
	public int getPatVaccId() {
		return this.patVaccId;
	}

	public void setPatVaccId(int patVaccId) {
		this.patVaccId = patVaccId;
	}

	@Column(name = "mr_no", nullable = false, length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "vaccine_dose_id", nullable = false)
	public int getVaccineDoseId() {
		return this.vaccineDoseId;
	}

	public void setVaccineDoseId(int vaccineDoseId) {
		this.vaccineDoseId = vaccineDoseId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vaccination_datetime", length = 13)
	public Date getVaccinationDatetime() {
		return this.vaccinationDatetime;
	}

	public void setVaccinationDatetime(Date vaccinationDatetime) {
		this.vaccinationDatetime = vaccinationDatetime;
	}

	@Column(name = "vacc_by", length = 30)
	public String getVaccBy() {
		return this.vaccBy;
	}

	public void setVaccBy(String vaccBy) {
		this.vaccBy = vaccBy;
	}

	@Column(name = "vacc_doctor_id", length = 100)
	public String getVaccDoctorId() {
		return this.vaccDoctorId;
	}

	public void setVaccDoctorId(String vaccDoctorId) {
		this.vaccDoctorId = vaccDoctorId;
	}

	@Column(name = "med_name", length = 300)
	public String getMedName() {
		return this.medName;
	}

	public void setMedName(String medName) {
		this.medName = medName;
	}

	@Column(name = "manufacturer", length = 200)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiry_date", length = 13)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "batch", length = 100)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "mod_user", length = 30)
	public String getModUser() {
		return this.modUser;
	}

	public void setModUser(String modUser) {
		this.modUser = modUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "vaccination_status", length = 1)
	public Character getVaccinationStatus() {
		return this.vaccinationStatus;
	}

	public void setVaccinationStatus(Character vaccinationStatus) {
		this.vaccinationStatus = vaccinationStatus;
	}

	@Column(name = "reason_for_not")
	public String getReasonForNot() {
		return this.reasonForNot;
	}

	public void setReasonForNot(String reasonForNot) {
		this.reasonForNot = reasonForNot;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
