package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientPrescriptionAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "patient_prescription_audit_log")
public class PatientPrescriptionAuditLogModel implements java.io.Serializable {

	private PatientPrescriptionAuditLogIdSequence id;

	public PatientPrescriptionAuditLogModel() {
	}

	public PatientPrescriptionAuditLogModel(PatientPrescriptionAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")),
			@AttributeOverride(name = "patientPrescId", column = @Column(name = "patient_presc_id")),
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", length = 15)),
			@AttributeOverride(name = "visitId", column = @Column(name = "visit_id", length = 15)),
			@AttributeOverride(name = "consultationId", column = @Column(name = "consultation_id")),
			@AttributeOverride(name = "prescType", column = @Column(name = "presc_type", length = 50)),
			@AttributeOverride(name = "operation", column = @Column(name = "operation", length = 50)) })
	public PatientPrescriptionAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(PatientPrescriptionAuditLogIdSequence id) {
		this.id = id;
	}

}
