package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientDepositsModel generated by hbm2java
 */
@Entity
@Table(name = "patient_deposits")
public class PatientDepositsModel implements java.io.Serializable {

	private String depositNo;
	private String mrNo;
	private String depositType;
	private BigDecimal amount;
	private Date depositDate;
	private String counter;
	private String bankName;
	private String referenceNo;
	private String username;
	private String remarks;
	private Date modTime;
	private Character realized;
	private String depositAvailableFor;
	private String depositPayerName;
	private String payerPhoneNo;
	private String payerAddress;
	private String paidBy;
	private int paymentModeId;
	private Integer cardTypeId;
	private String bankBatchNo;
	private String cardAuthCode;
	private String cardHolderName;
	private Integer currencyId;
	private BigDecimal exchangeRate;
	private Date exchangeDate;
	private BigDecimal currencyAmt;
	private Date cardExpdate;
	private String cardNumber;
	private Integer packageId;
	private BigDecimal creditCardCommissionPercentage;
	private BigDecimal creditCardCommissionAmount;
	private String totp;
	private String mobNumber;

	public PatientDepositsModel() {
	}

	public PatientDepositsModel(String depositNo, String mrNo, String depositType, BigDecimal amount, String username,
			Date modTime, int paymentModeId) {
		this.depositNo = depositNo;
		this.mrNo = mrNo;
		this.depositType = depositType;
		this.amount = amount;
		this.username = username;
		this.modTime = modTime;
		this.paymentModeId = paymentModeId;
	}

	public PatientDepositsModel(String depositNo, String mrNo, String depositType, BigDecimal amount, Date depositDate,
			String counter, String bankName, String referenceNo, String username, String remarks, Date modTime,
			Character realized, String depositAvailableFor, String depositPayerName, String payerPhoneNo,
			String payerAddress, String paidBy, int paymentModeId, Integer cardTypeId, String bankBatchNo,
			String cardAuthCode, String cardHolderName, Integer currencyId, BigDecimal exchangeRate, Date exchangeDate,
			BigDecimal currencyAmt, Date cardExpdate, String cardNumber, Integer packageId,
			BigDecimal creditCardCommissionPercentage, BigDecimal creditCardCommissionAmount, String totp,
			String mobNumber) {
		this.depositNo = depositNo;
		this.mrNo = mrNo;
		this.depositType = depositType;
		this.amount = amount;
		this.depositDate = depositDate;
		this.counter = counter;
		this.bankName = bankName;
		this.referenceNo = referenceNo;
		this.username = username;
		this.remarks = remarks;
		this.modTime = modTime;
		this.realized = realized;
		this.depositAvailableFor = depositAvailableFor;
		this.depositPayerName = depositPayerName;
		this.payerPhoneNo = payerPhoneNo;
		this.payerAddress = payerAddress;
		this.paidBy = paidBy;
		this.paymentModeId = paymentModeId;
		this.cardTypeId = cardTypeId;
		this.bankBatchNo = bankBatchNo;
		this.cardAuthCode = cardAuthCode;
		this.cardHolderName = cardHolderName;
		this.currencyId = currencyId;
		this.exchangeRate = exchangeRate;
		this.exchangeDate = exchangeDate;
		this.currencyAmt = currencyAmt;
		this.cardExpdate = cardExpdate;
		this.cardNumber = cardNumber;
		this.packageId = packageId;
		this.creditCardCommissionPercentage = creditCardCommissionPercentage;
		this.creditCardCommissionAmount = creditCardCommissionAmount;
		this.totp = totp;
		this.mobNumber = mobNumber;
	}

	@Id

	@Column(name = "deposit_no", unique = true, nullable = false, length = 15)
	public String getDepositNo() {
		return this.depositNo;
	}

	public void setDepositNo(String depositNo) {
		this.depositNo = depositNo;
	}

	@Column(name = "mr_no", nullable = false, length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "deposit_type", nullable = false, length = 1)
	public String getDepositType() {
		return this.depositType;
	}

	public void setDepositType(String depositType) {
		this.depositType = depositType;
	}

	@Column(name = "amount", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deposit_date", length = 29)
	public Date getDepositDate() {
		return this.depositDate;
	}

	public void setDepositDate(Date depositDate) {
		this.depositDate = depositDate;
	}

	@Column(name = "counter", length = 20)
	public String getCounter() {
		return this.counter;
	}

	public void setCounter(String counter) {
		this.counter = counter;
	}

	@Column(name = "bank_name", length = 50)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "reference_no", length = 50)
	public String getReferenceNo() {
		return this.referenceNo;
	}

	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "remarks", length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "realized", length = 1)
	public Character getRealized() {
		return this.realized;
	}

	public void setRealized(Character realized) {
		this.realized = realized;
	}

	@Column(name = "deposit_available_for", length = 1)
	public String getDepositAvailableFor() {
		return this.depositAvailableFor;
	}

	public void setDepositAvailableFor(String depositAvailableFor) {
		this.depositAvailableFor = depositAvailableFor;
	}

	@Column(name = "deposit_payer_name", length = 100)
	public String getDepositPayerName() {
		return this.depositPayerName;
	}

	public void setDepositPayerName(String depositPayerName) {
		this.depositPayerName = depositPayerName;
	}

	@Column(name = "payer_phone_no", length = 16)
	public String getPayerPhoneNo() {
		return this.payerPhoneNo;
	}

	public void setPayerPhoneNo(String payerPhoneNo) {
		this.payerPhoneNo = payerPhoneNo;
	}

	@Column(name = "payer_address", length = 300)
	public String getPayerAddress() {
		return this.payerAddress;
	}

	public void setPayerAddress(String payerAddress) {
		this.payerAddress = payerAddress;
	}

	@Column(name = "paid_by", length = 100)
	public String getPaidBy() {
		return this.paidBy;
	}

	public void setPaidBy(String paidBy) {
		this.paidBy = paidBy;
	}

	@Column(name = "payment_mode_id", nullable = false)
	public int getPaymentModeId() {
		return this.paymentModeId;
	}

	public void setPaymentModeId(int paymentModeId) {
		this.paymentModeId = paymentModeId;
	}

	@Column(name = "card_type_id")
	public Integer getCardTypeId() {
		return this.cardTypeId;
	}

	public void setCardTypeId(Integer cardTypeId) {
		this.cardTypeId = cardTypeId;
	}

	@Column(name = "bank_batch_no", length = 100)
	public String getBankBatchNo() {
		return this.bankBatchNo;
	}

	public void setBankBatchNo(String bankBatchNo) {
		this.bankBatchNo = bankBatchNo;
	}

	@Column(name = "card_auth_code", length = 100)
	public String getCardAuthCode() {
		return this.cardAuthCode;
	}

	public void setCardAuthCode(String cardAuthCode) {
		this.cardAuthCode = cardAuthCode;
	}

	@Column(name = "card_holder_name", length = 300)
	public String getCardHolderName() {
		return this.cardHolderName;
	}

	public void setCardHolderName(String cardHolderName) {
		this.cardHolderName = cardHolderName;
	}

	@Column(name = "currency_id")
	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "exchange_rate", precision = 131089, scale = 0)
	public BigDecimal getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exchange_date", length = 29)
	public Date getExchangeDate() {
		return this.exchangeDate;
	}

	public void setExchangeDate(Date exchangeDate) {
		this.exchangeDate = exchangeDate;
	}

	@Column(name = "currency_amt", precision = 131089, scale = 0)
	public BigDecimal getCurrencyAmt() {
		return this.currencyAmt;
	}

	public void setCurrencyAmt(BigDecimal currencyAmt) {
		this.currencyAmt = currencyAmt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "card_expdate", length = 13)
	public Date getCardExpdate() {
		return this.cardExpdate;
	}

	public void setCardExpdate(Date cardExpdate) {
		this.cardExpdate = cardExpdate;
	}

	@Column(name = "card_number", length = 150)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "package_id")
	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	@Column(name = "credit_card_commission_percentage", precision = 131089, scale = 0)
	public BigDecimal getCreditCardCommissionPercentage() {
		return this.creditCardCommissionPercentage;
	}

	public void setCreditCardCommissionPercentage(BigDecimal creditCardCommissionPercentage) {
		this.creditCardCommissionPercentage = creditCardCommissionPercentage;
	}

	@Column(name = "credit_card_commission_amount", precision = 131089, scale = 0)
	public BigDecimal getCreditCardCommissionAmount() {
		return this.creditCardCommissionAmount;
	}

	public void setCreditCardCommissionAmount(BigDecimal creditCardCommissionAmount) {
		this.creditCardCommissionAmount = creditCardCommissionAmount;
	}

	@Column(name = "totp", length = 10)
	public String getTotp() {
		return this.totp;
	}

	public void setTotp(String totp) {
		this.totp = totp;
	}

	@Column(name = "mob_number", length = 20)
	public String getMobNumber() {
		return this.mobNumber;
	}

	public void setMobNumber(String mobNumber) {
		this.mobNumber = mobNumber;
	}

}
