package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientSectionDetailsAuditLogIdSequence generated by hbm2java
 */
@Embeddable
public class PatientSectionDetailsAuditLogIdSequence implements java.io.Serializable {

	private int logId;
	private String mrNo;
	private String patientId;
	private Integer sectionItemId;
	private Integer genericFormId;
	private Integer sectionDetailId;
	private Integer sectionId;
	private String userName;
	private Date modTime;
	private String operation;
	private String fieldName;
	private String oldValue;
	private String newValue;

	public PatientSectionDetailsAuditLogIdSequence() {
	}

	public PatientSectionDetailsAuditLogIdSequence(int logId, Date modTime) {
		this.logId = logId;
		this.modTime = modTime;
	}

	public PatientSectionDetailsAuditLogIdSequence(int logId, String mrNo, String patientId, Integer sectionItemId,
			Integer genericFormId, Integer sectionDetailId, Integer sectionId, String userName, Date modTime,
			String operation, String fieldName, String oldValue, String newValue) {
		this.logId = logId;
		this.mrNo = mrNo;
		this.patientId = patientId;
		this.sectionItemId = sectionItemId;
		this.genericFormId = genericFormId;
		this.sectionDetailId = sectionDetailId;
		this.sectionId = sectionId;
		this.userName = userName;
		this.modTime = modTime;
		this.operation = operation;
		this.fieldName = fieldName;
		this.oldValue = oldValue;
		this.newValue = newValue;
	}

	@Column(name = "log_id", nullable = false)
	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "patient_id", length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "section_item_id")
	public Integer getSectionItemId() {
		return this.sectionItemId;
	}

	public void setSectionItemId(Integer sectionItemId) {
		this.sectionItemId = sectionItemId;
	}

	@Column(name = "generic_form_id")
	public Integer getGenericFormId() {
		return this.genericFormId;
	}

	public void setGenericFormId(Integer genericFormId) {
		this.genericFormId = genericFormId;
	}

	@Column(name = "section_detail_id")
	public Integer getSectionDetailId() {
		return this.sectionDetailId;
	}

	public void setSectionDetailId(Integer sectionDetailId) {
		this.sectionDetailId = sectionDetailId;
	}

	@Column(name = "section_id")
	public Integer getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(Integer sectionId) {
		this.sectionId = sectionId;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "operation")
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "field_name")
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "old_value")
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "new_value")
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientSectionDetailsAuditLogIdSequence))
			return false;
		PatientSectionDetailsAuditLogIdSequence castOther = (PatientSectionDetailsAuditLogIdSequence) other;

		return (this.getLogId() == castOther.getLogId())
				&& ((this.getMrNo() == castOther.getMrNo()) || (this.getMrNo() != null && castOther.getMrNo() != null
						&& this.getMrNo().equals(castOther.getMrNo())))
				&& ((this.getPatientId() == castOther.getPatientId()) || (this.getPatientId() != null
						&& castOther.getPatientId() != null && this.getPatientId().equals(castOther.getPatientId())))
				&& ((this.getSectionItemId() == castOther.getSectionItemId())
						|| (this.getSectionItemId() != null && castOther.getSectionItemId() != null
								&& this.getSectionItemId().equals(castOther.getSectionItemId())))
				&& ((this.getGenericFormId() == castOther.getGenericFormId())
						|| (this.getGenericFormId() != null && castOther.getGenericFormId() != null
								&& this.getGenericFormId().equals(castOther.getGenericFormId())))
				&& ((this.getSectionDetailId() == castOther.getSectionDetailId())
						|| (this.getSectionDetailId() != null && castOther.getSectionDetailId() != null
								&& this.getSectionDetailId().equals(castOther.getSectionDetailId())))
				&& ((this.getSectionId() == castOther.getSectionId()) || (this.getSectionId() != null
						&& castOther.getSectionId() != null && this.getSectionId().equals(castOther.getSectionId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getModTime() == castOther.getModTime()) || (this.getModTime() != null
						&& castOther.getModTime() != null && this.getModTime().equals(castOther.getModTime())))
				&& ((this.getOperation() == castOther.getOperation()) || (this.getOperation() != null
						&& castOther.getOperation() != null && this.getOperation().equals(castOther.getOperation())))
				&& ((this.getFieldName() == castOther.getFieldName()) || (this.getFieldName() != null
						&& castOther.getFieldName() != null && this.getFieldName().equals(castOther.getFieldName())))
				&& ((this.getOldValue() == castOther.getOldValue()) || (this.getOldValue() != null
						&& castOther.getOldValue() != null && this.getOldValue().equals(castOther.getOldValue())))
				&& ((this.getNewValue() == castOther.getNewValue()) || (this.getNewValue() != null
						&& castOther.getNewValue() != null && this.getNewValue().equals(castOther.getNewValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLogId();
		result = 37 * result + (getMrNo() == null ? 0 : this.getMrNo().hashCode());
		result = 37 * result + (getPatientId() == null ? 0 : this.getPatientId().hashCode());
		result = 37 * result + (getSectionItemId() == null ? 0 : this.getSectionItemId().hashCode());
		result = 37 * result + (getGenericFormId() == null ? 0 : this.getGenericFormId().hashCode());
		result = 37 * result + (getSectionDetailId() == null ? 0 : this.getSectionDetailId().hashCode());
		result = 37 * result + (getSectionId() == null ? 0 : this.getSectionId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getModTime() == null ? 0 : this.getModTime().hashCode());
		result = 37 * result + (getOperation() == null ? 0 : this.getOperation().hashCode());
		result = 37 * result + (getFieldName() == null ? 0 : this.getFieldName().hashCode());
		result = 37 * result + (getOldValue() == null ? 0 : this.getOldValue().hashCode());
		result = 37 * result + (getNewValue() == null ? 0 : this.getNewValue().hashCode());
		return result;
	}

}
