package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatientInsuranceDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "patient_insurance_details")
public class PatientInsuranceDetailsModel implements java.io.Serializable {

	private String insId;
	private String mrno;
	private String ipno;
	private String tpaId;
	private String compId;
	private BigDecimal estimatedAmount;
	private BigDecimal sanctionedAmount;
	private Character finalized;
	private BigDecimal amountReceived;

	public PatientInsuranceDetailsModel() {
	}

	public PatientInsuranceDetailsModel(String insId, String mrno, String ipno, String tpaId, String compId) {
		this.insId = insId;
		this.mrno = mrno;
		this.ipno = ipno;
		this.tpaId = tpaId;
		this.compId = compId;
	}

	public PatientInsuranceDetailsModel(String insId, String mrno, String ipno, String tpaId, String compId,
			BigDecimal estimatedAmount, BigDecimal sanctionedAmount, Character finalized, BigDecimal amountReceived) {
		this.insId = insId;
		this.mrno = mrno;
		this.ipno = ipno;
		this.tpaId = tpaId;
		this.compId = compId;
		this.estimatedAmount = estimatedAmount;
		this.sanctionedAmount = sanctionedAmount;
		this.finalized = finalized;
		this.amountReceived = amountReceived;
	}

	@Id

	@Column(name = "ins_id", unique = true, nullable = false, length = 10)
	public String getInsId() {
		return this.insId;
	}

	public void setInsId(String insId) {
		this.insId = insId;
	}

	@Column(name = "mrno", nullable = false, length = 15)
	public String getMrno() {
		return this.mrno;
	}

	public void setMrno(String mrno) {
		this.mrno = mrno;
	}

	@Column(name = "ipno", nullable = false, length = 10)
	public String getIpno() {
		return this.ipno;
	}

	public void setIpno(String ipno) {
		this.ipno = ipno;
	}

	@Column(name = "tpa_id", nullable = false, length = 10)
	public String getTpaId() {
		return this.tpaId;
	}

	public void setTpaId(String tpaId) {
		this.tpaId = tpaId;
	}

	@Column(name = "comp_id", nullable = false, length = 10)
	public String getCompId() {
		return this.compId;
	}

	public void setCompId(String compId) {
		this.compId = compId;
	}

	@Column(name = "estimated_amount", precision = 15)
	public BigDecimal getEstimatedAmount() {
		return this.estimatedAmount;
	}

	public void setEstimatedAmount(BigDecimal estimatedAmount) {
		this.estimatedAmount = estimatedAmount;
	}

	@Column(name = "sanctioned_amount", precision = 15)
	public BigDecimal getSanctionedAmount() {
		return this.sanctionedAmount;
	}

	public void setSanctionedAmount(BigDecimal sanctionedAmount) {
		this.sanctionedAmount = sanctionedAmount;
	}

	@Column(name = "finalized", length = 1)
	public Character getFinalized() {
		return this.finalized;
	}

	public void setFinalized(Character finalized) {
		this.finalized = finalized;
	}

	@Column(name = "amount_received", precision = 15)
	public BigDecimal getAmountReceived() {
		return this.amountReceived;
	}

	public void setAmountReceived(BigDecimal amountReceived) {
		this.amountReceived = amountReceived;
	}

}
