package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientDemographicsModModel generated by hbm2java
 */
@Entity
@Table(name = "patient_demographics_mod")
public class PatientDemographicsModModel implements java.io.Serializable {

	private PatientDemographicsModIdSequence id;

	public PatientDemographicsModModel() {
	}

	public PatientDemographicsModModel(PatientDemographicsModIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", length = 15)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)) })
	public PatientDemographicsModIdSequence getId() {
		return this.id;
	}

	public void setId(PatientDemographicsModIdSequence id) {
		this.id = id;
	}

}
