package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientSponsorApprovalsDocsIdSequence generated by hbm2java
 */
@Embeddable
public class PatientSponsorApprovalsDocsIdSequence implements java.io.Serializable {

	private int sponsorApprovalId;
	private byte[] attachment;
	private String attachmentContentType;
	private String attachmentExtension;
	private String fileName;

	public PatientSponsorApprovalsDocsIdSequence() {
	}

	public PatientSponsorApprovalsDocsIdSequence(int sponsorApprovalId) {
		this.sponsorApprovalId = sponsorApprovalId;
	}

	public PatientSponsorApprovalsDocsIdSequence(int sponsorApprovalId, byte[] attachment, String attachmentContentType,
			String attachmentExtension, String fileName) {
		this.sponsorApprovalId = sponsorApprovalId;
		this.attachment = attachment;
		this.attachmentContentType = attachmentContentType;
		this.attachmentExtension = attachmentExtension;
		this.fileName = fileName;
	}

	@Column(name = "sponsor_approval_id", nullable = false)
	public int getSponsorApprovalId() {
		return this.sponsorApprovalId;
	}

	public void setSponsorApprovalId(int sponsorApprovalId) {
		this.sponsorApprovalId = sponsorApprovalId;
	}

	@Column(name = "attachment")
	public byte[] getAttachment() {
		return this.attachment;
	}

	public void setAttachment(byte[] attachment) {
		this.attachment = attachment;
	}

	@Column(name = "attachment_content_type")
	public String getAttachmentContentType() {
		return this.attachmentContentType;
	}

	public void setAttachmentContentType(String attachmentContentType) {
		this.attachmentContentType = attachmentContentType;
	}

	@Column(name = "attachment_extension")
	public String getAttachmentExtension() {
		return this.attachmentExtension;
	}

	public void setAttachmentExtension(String attachmentExtension) {
		this.attachmentExtension = attachmentExtension;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientSponsorApprovalsDocsIdSequence))
			return false;
		PatientSponsorApprovalsDocsIdSequence castOther = (PatientSponsorApprovalsDocsIdSequence) other;

		return (this.getSponsorApprovalId() == castOther.getSponsorApprovalId())
				&& ((this.getAttachment() == castOther.getAttachment())
						|| (this.getAttachment() != null && castOther.getAttachment() != null
								&& Arrays.equals(this.getAttachment(), castOther.getAttachment())))
				&& ((this.getAttachmentContentType() == castOther.getAttachmentContentType())
						|| (this.getAttachmentContentType() != null && castOther.getAttachmentContentType() != null
								&& this.getAttachmentContentType().equals(castOther.getAttachmentContentType())))
				&& ((this.getAttachmentExtension() == castOther.getAttachmentExtension())
						|| (this.getAttachmentExtension() != null && castOther.getAttachmentExtension() != null
								&& this.getAttachmentExtension().equals(castOther.getAttachmentExtension())))
				&& ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null
						&& castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSponsorApprovalId();
		int attachmentHashcode = 0;
		byte[] attachmentProperty = this.getAttachment();
		if (attachmentProperty != null) {
			attachmentHashcode = 1;
			for (int i = 0; i < attachmentProperty.length; i++) {
				attachmentHashcode = 37 * attachmentHashcode + attachmentProperty[i];
			}
		}

		result = 37 * result + attachmentHashcode;

		result = 37 * result + (getAttachmentContentType() == null ? 0 : this.getAttachmentContentType().hashCode());
		result = 37 * result + (getAttachmentExtension() == null ? 0 : this.getAttachmentExtension().hashCode());
		result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
		return result;
	}

}
