package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientDentalConditionDetailsIdSequence generated by hbm2java
 */
@Embeddable
public class PatientDentalConditionDetailsIdSequence implements java.io.Serializable {

	private int dentalConditionId;
	private String unvNumber;
	private String toothPart;
	private Integer statusId;
	private Integer optionId;
	private Integer materialId;

	public PatientDentalConditionDetailsIdSequence() {
	}

	public PatientDentalConditionDetailsIdSequence(int dentalConditionId, String toothPart) {
		this.dentalConditionId = dentalConditionId;
		this.toothPart = toothPart;
	}

	public PatientDentalConditionDetailsIdSequence(int dentalConditionId, String unvNumber, String toothPart, Integer statusId,
			Integer optionId, Integer materialId) {
		this.dentalConditionId = dentalConditionId;
		this.unvNumber = unvNumber;
		this.toothPart = toothPart;
		this.statusId = statusId;
		this.optionId = optionId;
		this.materialId = materialId;
	}

	@Column(name = "dental_condition_id", nullable = false)
	public int getDentalConditionId() {
		return this.dentalConditionId;
	}

	public void setDentalConditionId(int dentalConditionId) {
		this.dentalConditionId = dentalConditionId;
	}

	@Column(name = "unv_number", length = 5)
	public String getUnvNumber() {
		return this.unvNumber;
	}

	public void setUnvNumber(String unvNumber) {
		this.unvNumber = unvNumber;
	}

	@Column(name = "tooth_part", nullable = false, length = 20)
	public String getToothPart() {
		return this.toothPart;
	}

	public void setToothPart(String toothPart) {
		this.toothPart = toothPart;
	}

	@Column(name = "status_id")
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "option_id")
	public Integer getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Integer optionId) {
		this.optionId = optionId;
	}

	@Column(name = "material_id")
	public Integer getMaterialId() {
		return this.materialId;
	}

	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientDentalConditionDetailsIdSequence))
			return false;
		PatientDentalConditionDetailsIdSequence castOther = (PatientDentalConditionDetailsIdSequence) other;

		return (this.getDentalConditionId() == castOther.getDentalConditionId())
				&& ((this.getUnvNumber() == castOther.getUnvNumber()) || (this.getUnvNumber() != null
						&& castOther.getUnvNumber() != null && this.getUnvNumber().equals(castOther.getUnvNumber())))
				&& ((this.getToothPart() == castOther.getToothPart()) || (this.getToothPart() != null
						&& castOther.getToothPart() != null && this.getToothPart().equals(castOther.getToothPart())))
				&& ((this.getStatusId() == castOther.getStatusId()) || (this.getStatusId() != null
						&& castOther.getStatusId() != null && this.getStatusId().equals(castOther.getStatusId())))
				&& ((this.getOptionId() == castOther.getOptionId()) || (this.getOptionId() != null
						&& castOther.getOptionId() != null && this.getOptionId().equals(castOther.getOptionId())))
				&& ((this.getMaterialId() == castOther.getMaterialId())
						|| (this.getMaterialId() != null && castOther.getMaterialId() != null
								&& this.getMaterialId().equals(castOther.getMaterialId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDentalConditionId();
		result = 37 * result + (getUnvNumber() == null ? 0 : this.getUnvNumber().hashCode());
		result = 37 * result + (getToothPart() == null ? 0 : this.getToothPart().hashCode());
		result = 37 * result + (getStatusId() == null ? 0 : this.getStatusId().hashCode());
		result = 37 * result + (getOptionId() == null ? 0 : this.getOptionId().hashCode());
		result = 37 * result + (getMaterialId() == null ? 0 : this.getMaterialId().hashCode());
		return result;
	}

}
