package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientSectionValuesAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "patient_section_values_audit_log")
public class PatientSectionValuesAuditLogModel implements java.io.Serializable {

	private PatientSectionValuesAuditLogIdSequence id;

	public PatientSectionValuesAuditLogModel() {
	}

	public PatientSectionValuesAuditLogModel(PatientSectionValuesAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "sectionDetailId", column = @Column(name = "section_detail_id")),
			@AttributeOverride(name = "fieldId", column = @Column(name = "field_id")),
			@AttributeOverride(name = "optionId", column = @Column(name = "option_id")),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 30)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)),
			@AttributeOverride(name = "operation", column = @Column(name = "operation")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")) })
	public PatientSectionValuesAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(PatientSectionValuesAuditLogIdSequence id) {
		this.id = id;
	}

}
