package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientHistoryModel generated by hbm2java
 */
@Entity
@Table(name = "patient_history")
public class PatientHistoryModel implements java.io.Serializable {

	private PatientHistoryIdSequence id;

	public PatientHistoryModel() {
	}

	public PatientHistoryModel(PatientHistoryIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", nullable = false, length = 15)),
			@AttributeOverride(name = "patientHistory", column = @Column(name = "patient_history", length = 250)),
			@AttributeOverride(name = "familyHistory", column = @Column(name = "family_history", length = 250)),
			@AttributeOverride(name = "pastSurgery", column = @Column(name = "past_surgery", length = 250)) })
	public PatientHistoryIdSequence getId() {
		return this.id;
	}

	public void setId(PatientHistoryIdSequence id) {
		this.id = id;
	}

}
