package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentsModel generated by hbm2java
 */
@Entity
@Table(name = "payments")
public class PaymentsModel implements java.io.Serializable {

	private String voucherNo;
	private char type;
	private BigDecimal amount;
	private String taxType;
	private BigDecimal taxAmount;
	private Date date;
	private String counter;
	private String username;
	private String bank;
	private String referenceNo;
	private String payeeName;
	private BigDecimal tdsAmount;
	private String remarks;
	private Date modTime;
	private Character voucherCategory;
	private Character paymentType;
	private BigDecimal roundOff;
	private int paymentModeId;
	private Integer cardTypeId;

	public PaymentsModel() {
	}

	public PaymentsModel(String voucherNo, char type, BigDecimal amount, Date date, String counter, String username,
			String payeeName, int paymentModeId) {
		this.voucherNo = voucherNo;
		this.type = type;
		this.amount = amount;
		this.date = date;
		this.counter = counter;
		this.username = username;
		this.payeeName = payeeName;
		this.paymentModeId = paymentModeId;
	}

	public PaymentsModel(String voucherNo, char type, BigDecimal amount, String taxType, BigDecimal taxAmount, Date date,
			String counter, String username, String bank, String referenceNo, String payeeName, BigDecimal tdsAmount,
			String remarks, Date modTime, Character voucherCategory, Character paymentType, BigDecimal roundOff,
			int paymentModeId, Integer cardTypeId) {
		this.voucherNo = voucherNo;
		this.type = type;
		this.amount = amount;
		this.taxType = taxType;
		this.taxAmount = taxAmount;
		this.date = date;
		this.counter = counter;
		this.username = username;
		this.bank = bank;
		this.referenceNo = referenceNo;
		this.payeeName = payeeName;
		this.tdsAmount = tdsAmount;
		this.remarks = remarks;
		this.modTime = modTime;
		this.voucherCategory = voucherCategory;
		this.paymentType = paymentType;
		this.roundOff = roundOff;
		this.paymentModeId = paymentModeId;
		this.cardTypeId = cardTypeId;
	}

	@Id

	@Column(name = "voucher_no", unique = true, nullable = false, length = 20)
	public String getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	@Column(name = "type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Column(name = "amount", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "tax_type", length = 15)
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Column(name = "tax_amount", precision = 15)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 35)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "counter", nullable = false, length = 10)
	public String getCounter() {
		return this.counter;
	}

	public void setCounter(String counter) {
		this.counter = counter;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "bank", length = 50)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "reference_no", length = 20)
	public String getReferenceNo() {
		return this.referenceNo;
	}

	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo;
	}

	@Column(name = "payee_name", nullable = false, length = 30)
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Column(name = "tds_amount", precision = 15)
	public BigDecimal getTdsAmount() {
		return this.tdsAmount;
	}

	public void setTdsAmount(BigDecimal tdsAmount) {
		this.tdsAmount = tdsAmount;
	}

	@Column(name = "remarks", length = 150)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "voucher_category", length = 1)
	public Character getVoucherCategory() {
		return this.voucherCategory;
	}

	public void setVoucherCategory(Character voucherCategory) {
		this.voucherCategory = voucherCategory;
	}

	@Column(name = "payment_type", length = 1)
	public Character getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(Character paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "round_off", precision = 131089, scale = 0)
	public BigDecimal getRoundOff() {
		return this.roundOff;
	}

	public void setRoundOff(BigDecimal roundOff) {
		this.roundOff = roundOff;
	}

	@Column(name = "payment_mode_id", nullable = false)
	public int getPaymentModeId() {
		return this.paymentModeId;
	}

	public void setPaymentModeId(int paymentModeId) {
		this.paymentModeId = paymentModeId;
	}

	@Column(name = "card_type_id")
	public Integer getCardTypeId() {
		return this.cardTypeId;
	}

	public void setCardTypeId(Integer cardTypeId) {
		this.cardTypeId = cardTypeId;
	}

}
