package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.paymentmode.PaymentModeMasterModel;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaymentTransactionsModel generated by hbm2java
 */
@Entity
@Table(name = "payment_transactions")
public class PaymentTransactionsModel implements java.io.Serializable {

	private PaymentTransactionsIdSequence id;
	private PaymentModeMasterModel paymentModeMaster;

	public PaymentTransactionsModel() {
	}

	public PaymentTransactionsModel(PaymentTransactionsIdSequence id, PaymentModeMasterModel paymentModeMaster) {
		this.id = id;
		this.paymentModeMaster = paymentModeMaster;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "paymentTransactionId", column = @Column(name = "payment_transaction_id", nullable = false)),
			@AttributeOverride(name = "modeId", column = @Column(name = "mode_id", nullable = false)),
			@AttributeOverride(name = "transactionType", column = @Column(name = "transaction_type", length = 20)),
			@AttributeOverride(name = "totp", column = @Column(name = "totp", length = 10)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "mobile_no", length = 16)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, precision = 15)),
			@AttributeOverride(name = "billNo", column = @Column(name = "bill_no", length = 15)),
			@AttributeOverride(name = "transactionId", column = @Column(name = "transaction_id", length = 50)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false)),
			@AttributeOverride(name = "statusCode", column = @Column(name = "status_code", length = 20)),
			@AttributeOverride(name = "statusMessage", column = @Column(name = "status_message", length = 100)),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", nullable = false, length = 29)) })
	public PaymentTransactionsIdSequence getId() {
		return this.id;
	}

	public void setId(PaymentTransactionsIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mode_id", nullable = false, insertable = false, updatable = false)
	public PaymentModeMasterModel getPaymentModeMasterModel() {
		return this.paymentModeMaster;
	}

	public void setPaymentModeMasterModel(PaymentModeMasterModel paymentModeMaster) {
		this.paymentModeMaster = paymentModeMaster;
	}

}
