package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PbmApprovalAmountDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "pbm_approval_amount_details")
public class PbmApprovalAmountDetailsModel implements java.io.Serializable {

	private PbmApprovalAmountDetailsIdSequence id;

	public PbmApprovalAmountDetailsModel() {
	}

	public PbmApprovalAmountDetailsModel(PbmApprovalAmountDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pbmRequestId", column = @Column(name = "pbm_request_id", nullable = false)),
			@AttributeOverride(name = "pbmMedicinePresId", column = @Column(name = "pbm_medicine_pres_id", nullable = false)),
			@AttributeOverride(name = "denialCode", column = @Column(name = "denial_code", length = 10)),
			@AttributeOverride(name = "pbmAuthIdPayer", column = @Column(name = "pbm_auth_id_payer", length = 100)),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", precision = 131089, scale = 0)),
			@AttributeOverride(name = "net", column = @Column(name = "net", precision = 15)),
			@AttributeOverride(name = "list", column = @Column(name = "list", precision = 15)),
			@AttributeOverride(name = "patientShare", column = @Column(name = "patient_share", precision = 15)),
			@AttributeOverride(name = "paymentAmount", column = @Column(name = "payment_amount", precision = 15)) })
	public PbmApprovalAmountDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(PbmApprovalAmountDetailsIdSequence id) {
		this.id = id;
	}

}
