package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PbmPrescriptionRequestModel generated by hbm2java
 */
@Entity
@Table(name = "pbm_prescription_request")
public class PbmPrescriptionRequestModel implements java.io.Serializable {

	private PbmPrescriptionRequestIdSequence id;
	private PbmPrescriptionModel pbmPrescription;

	public PbmPrescriptionRequestModel() {
	}

	public PbmPrescriptionRequestModel(PbmPrescriptionRequestIdSequence id, PbmPrescriptionModel pbmPrescription) {
		this.id = id;
		this.pbmPrescription = pbmPrescription;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pbmPrescId", column = @Column(name = "pbm_presc_id", nullable = false)),
			@AttributeOverride(name = "pbmRequestId", column = @Column(name = "pbm_request_id", nullable = false, length = 50)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 30)),
			@AttributeOverride(name = "fileId", column = @Column(name = "file_id")),
			@AttributeOverride(name = "approvalRecdDate", column = @Column(name = "approval_recd_date", length = 29)),
			@AttributeOverride(name = "pbmAuthIdPayer", column = @Column(name = "pbm_auth_id_payer", length = 100)),
			@AttributeOverride(name = "approvalStatus", column = @Column(name = "approval_status", length = 1)),
			@AttributeOverride(name = "approvalComments", column = @Column(name = "approval_comments")),
			@AttributeOverride(name = "approvalResult", column = @Column(name = "approval_result", length = 3)),
			@AttributeOverride(name = "approvalLimit", column = @Column(name = "approval_limit", precision = 131089, scale = 0)) })
	public PbmPrescriptionRequestIdSequence getId() {
		return this.id;
	}

	public void setId(PbmPrescriptionRequestIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pbm_presc_id", nullable = false, insertable = false, updatable = false)
	public PbmPrescriptionModel getPbmPrescriptionModel() {
		return this.pbmPrescription;
	}

	public void setPbmPrescriptionModel(PbmPrescriptionModel pbmPrescription) {
		this.pbmPrescription = pbmPrescription;
	}

}
