package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PbmRequestApprovalDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "pbm_request_approval_details")
public class PbmRequestApprovalDetailsModel implements java.io.Serializable {

	private String pbmRequestId;
	private String pbmRequestType;
	private Date requestDate;
	private String requestBy;
	private Integer accountGroup;
	private Integer centerId;
	private String fileName;
	private String fileId;
	private char isResubmit;
	private Date approvalRecdDate;
	private String pbmAuthIdPayer;
	private Character approvalStatus;
	private String approvalComments;
	private String approvalResult;
	private BigDecimal approvalLimit;
	private String pbmSenderId;
	private String pbmReceiverId;
	private Set pbmPrescriptions = new HashSet(0);

	public PbmRequestApprovalDetailsModel() {
	}

	public PbmRequestApprovalDetailsModel(String pbmRequestId, String pbmRequestType, Date requestDate, char isResubmit) {
		this.pbmRequestId = pbmRequestId;
		this.pbmRequestType = pbmRequestType;
		this.requestDate = requestDate;
		this.isResubmit = isResubmit;
	}

	public PbmRequestApprovalDetailsModel(String pbmRequestId, String pbmRequestType, Date requestDate, String requestBy,
			Integer accountGroup, Integer centerId, String fileName, String fileId, char isResubmit,
			Date approvalRecdDate, String pbmAuthIdPayer, Character approvalStatus, String approvalComments,
			String approvalResult, BigDecimal approvalLimit, String pbmSenderId, String pbmReceiverId,
			Set pbmPrescriptions) {
		this.pbmRequestId = pbmRequestId;
		this.pbmRequestType = pbmRequestType;
		this.requestDate = requestDate;
		this.requestBy = requestBy;
		this.accountGroup = accountGroup;
		this.centerId = centerId;
		this.fileName = fileName;
		this.fileId = fileId;
		this.isResubmit = isResubmit;
		this.approvalRecdDate = approvalRecdDate;
		this.pbmAuthIdPayer = pbmAuthIdPayer;
		this.approvalStatus = approvalStatus;
		this.approvalComments = approvalComments;
		this.approvalResult = approvalResult;
		this.approvalLimit = approvalLimit;
		this.pbmSenderId = pbmSenderId;
		this.pbmReceiverId = pbmReceiverId;
		this.pbmPrescriptions = pbmPrescriptions;
	}

	@Id

	@Column(name = "pbm_request_id", unique = true, nullable = false, length = 50)
	public String getPbmRequestId() {
		return this.pbmRequestId;
	}

	public void setPbmRequestId(String pbmRequestId) {
		this.pbmRequestId = pbmRequestId;
	}

	@Column(name = "pbm_request_type", nullable = false, length = 30)
	public String getPbmRequestType() {
		return this.pbmRequestType;
	}

	public void setPbmRequestType(String pbmRequestType) {
		this.pbmRequestType = pbmRequestType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_date", nullable = false, length = 29)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Column(name = "request_by", length = 30)
	public String getRequestBy() {
		return this.requestBy;
	}

	public void setRequestBy(String requestBy) {
		this.requestBy = requestBy;
	}

	@Column(name = "account_group")
	public Integer getAccountGroup() {
		return this.accountGroup;
	}

	public void setAccountGroup(Integer accountGroup) {
		this.accountGroup = accountGroup;
	}

	@Column(name = "center_id")
	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_id")
	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	@Column(name = "is_resubmit", nullable = false, length = 1)
	public char getIsResubmit() {
		return this.isResubmit;
	}

	public void setIsResubmit(char isResubmit) {
		this.isResubmit = isResubmit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approval_recd_date", length = 29)
	public Date getApprovalRecdDate() {
		return this.approvalRecdDate;
	}

	public void setApprovalRecdDate(Date approvalRecdDate) {
		this.approvalRecdDate = approvalRecdDate;
	}

	@Column(name = "pbm_auth_id_payer", length = 100)
	public String getPbmAuthIdPayer() {
		return this.pbmAuthIdPayer;
	}

	public void setPbmAuthIdPayer(String pbmAuthIdPayer) {
		this.pbmAuthIdPayer = pbmAuthIdPayer;
	}

	@Column(name = "approval_status", length = 1)
	public Character getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(Character approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	@Column(name = "approval_comments")
	public String getApprovalComments() {
		return this.approvalComments;
	}

	public void setApprovalComments(String approvalComments) {
		this.approvalComments = approvalComments;
	}

	@Column(name = "approval_result", length = 3)
	public String getApprovalResult() {
		return this.approvalResult;
	}

	public void setApprovalResult(String approvalResult) {
		this.approvalResult = approvalResult;
	}

	@Column(name = "approval_limit", precision = 131089, scale = 0)
	public BigDecimal getApprovalLimit() {
		return this.approvalLimit;
	}

	public void setApprovalLimit(BigDecimal approvalLimit) {
		this.approvalLimit = approvalLimit;
	}

	@Column(name = "pbm_sender_id")
	public String getPbmSenderId() {
		return this.pbmSenderId;
	}

	public void setPbmSenderId(String pbmSenderId) {
		this.pbmSenderId = pbmSenderId;
	}

	@Column(name = "pbm_receiver_id")
	public String getPbmReceiverId() {
		return this.pbmReceiverId;
	}

	public void setPbmReceiverId(String pbmReceiverId) {
		this.pbmReceiverId = pbmReceiverId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pbmRequestApprovalDetails")
	public Set getPbmPrescriptions() {
		return this.pbmPrescriptions;
	}

	public void setPbmPrescriptions(Set pbmPrescriptions) {
		this.pbmPrescriptions = pbmPrescriptions;
	}

}
