package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.perdiemcodes.PerDiemCodesMasterModel;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerDiemCodesChargesModel generated by hbm2java
 */
@Entity
@Table(name = "per_diem_codes_charges")
public class PerDiemCodesChargesModel implements java.io.Serializable {

	private PerDiemCodesChargesIdSequence id;
	private PerDiemCodesMasterModel perDiemCodesMaster;
	private BigDecimal charge;
	private String username;

	public PerDiemCodesChargesModel() {
	}

	public PerDiemCodesChargesModel(PerDiemCodesChargesIdSequence id, PerDiemCodesMasterModel perDiemCodesMaster, BigDecimal charge) {
		this.id = id;
		this.perDiemCodesMaster = perDiemCodesMaster;
		this.charge = charge;
	}

	public PerDiemCodesChargesModel(PerDiemCodesChargesIdSequence id, PerDiemCodesMasterModel perDiemCodesMaster, BigDecimal charge,
			String username) {
		this.id = id;
		this.perDiemCodesMaster = perDiemCodesMaster;
		this.charge = charge;
		this.username = username;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 50)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", nullable = false, length = 50)),
			@AttributeOverride(name = "perDiemCode", column = @Column(name = "per_diem_code", nullable = false, length = 15)) })
	public PerDiemCodesChargesIdSequence getId() {
		return this.id;
	}

	public void setId(PerDiemCodesChargesIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "per_diem_code", nullable = false, insertable = false, updatable = false)
	public PerDiemCodesMasterModel getPerDiemCodesMasterModel() {
		return this.perDiemCodesMaster;
	}

	public void setPerDiemCodesMasterModel(PerDiemCodesMasterModel perDiemCodesMaster) {
		this.perDiemCodesMaster = perDiemCodesMaster;
	}

	@Column(name = "charge", nullable = false, precision = 15)
	public BigDecimal getCharge() {
		return this.charge;
	}

	public void setCharge(BigDecimal charge) {
		this.charge = charge;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
