package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PerDiemCodesAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "per_diem_codes_audit_log")
public class PerDiemCodesAuditLogModel implements java.io.Serializable {

	private PerDiemCodesAuditLogIdSequence id;

	public PerDiemCodesAuditLogModel() {
	}

	public PerDiemCodesAuditLogModel(PerDiemCodesAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "operation", column = @Column(name = "operation")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")),
			@AttributeOverride(name = "perDiemCode", column = @Column(name = "per_diem_code")) })
	public PerDiemCodesAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(PerDiemCodesAuditLogIdSequence id) {
		this.id = id;
	}

}
