package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PharmacyMedicineCategoryModel generated by hbm2java
 */
@Entity
@Table(name = "pharmacy_medicine_category", uniqueConstraints = @UniqueConstraint(columnNames = "category_name"))
public class PharmacyMedicineCategoryModel implements java.io.Serializable {

	private int categoryId;
	private String categoryName;
	private char status;
	private Boolean claimable;
	private Integer tempCatId;

	public PharmacyMedicineCategoryModel() {
	}

	public PharmacyMedicineCategoryModel(int categoryId, String categoryName, char status) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.status = status;
	}

	public PharmacyMedicineCategoryModel(int categoryId, String categoryName, char status, Boolean claimable,
			Integer tempCatId) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.status = status;
		this.claimable = claimable;
		this.tempCatId = tempCatId;
	}

	@Id

	@Column(name = "category_id", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", unique = true, nullable = false, length = 50)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "claimable")
	public Boolean getClaimable() {
		return this.claimable;
	}

	public void setClaimable(Boolean claimable) {
		this.claimable = claimable;
	}

	@Column(name = "temp_cat_id")
	public Integer getTempCatId() {
		return this.tempCatId;
	}

	public void setTempCatId(Integer tempCatId) {
		this.tempCatId = tempCatId;
	}

}
