package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PreauthPrescriptionActivitiesModel generated by hbm2java
 */
@Entity
@Table(name = "preauth_prescription_activities")
public class PreauthPrescriptionActivitiesModel implements java.io.Serializable {

	private int preauthActId;
	private PreauthPrescriptionModel preauthPrescription;
	private int consultationId;
	private int patientPresId;
	private String preauthActType;
	private String preauthActItemId;
	private char status;
	private int actQty;
	private String actCodeType;
	private String actCode;
	private String toothUnvNumber;
	private String toothFdiNumber;
	private Date activityDueDate;
	private Date modTime;
	private String username;
	private String preauthActItemRemarks;
	private char addedToBill;
	private Boolean ispackage;
	private String mrNo;
	private String visitId;
	private char preauthRequired;
	private char preauthActStatus;
	private String preauthId;
	private Integer preauthMode;
	private String denialCode;
	private String denialRemarks;
	private BigDecimal amount;
	private BigDecimal claimNetAmount;
	private BigDecimal claimNetApprovedAmount;
	private BigDecimal rate;
	private BigDecimal discount;
	private int docConsType;
	private Date prescribedDate;
	private BigDecimal patientShare;

	public PreauthPrescriptionActivitiesModel() {
	}

	public PreauthPrescriptionActivitiesModel(int preauthActId, int consultationId, int patientPresId, String preauthActType,
			char status, int actQty, Date modTime, char addedToBill, char preauthRequired, char preauthActStatus,
			BigDecimal amount, BigDecimal claimNetAmount, BigDecimal claimNetApprovedAmount, BigDecimal rate,
			BigDecimal discount, int docConsType, Date prescribedDate, BigDecimal patientShare) {
		this.preauthActId = preauthActId;
		this.consultationId = consultationId;
		this.patientPresId = patientPresId;
		this.preauthActType = preauthActType;
		this.status = status;
		this.actQty = actQty;
		this.modTime = modTime;
		this.addedToBill = addedToBill;
		this.preauthRequired = preauthRequired;
		this.preauthActStatus = preauthActStatus;
		this.amount = amount;
		this.claimNetAmount = claimNetAmount;
		this.claimNetApprovedAmount = claimNetApprovedAmount;
		this.rate = rate;
		this.discount = discount;
		this.docConsType = docConsType;
		this.prescribedDate = prescribedDate;
		this.patientShare = patientShare;
	}

	public PreauthPrescriptionActivitiesModel(int preauthActId, PreauthPrescriptionModel preauthPrescription, int consultationId,
			int patientPresId, String preauthActType, String preauthActItemId, char status, int actQty,
			String actCodeType, String actCode, String toothUnvNumber, String toothFdiNumber, Date activityDueDate,
			Date modTime, String username, String preauthActItemRemarks, char addedToBill, Boolean ispackage,
			String mrNo, String visitId, char preauthRequired, char preauthActStatus, String preauthId,
			Integer preauthMode, String denialCode, String denialRemarks, BigDecimal amount, BigDecimal claimNetAmount,
			BigDecimal claimNetApprovedAmount, BigDecimal rate, BigDecimal discount, int docConsType,
			Date prescribedDate, BigDecimal patientShare) {
		this.preauthActId = preauthActId;
		this.preauthPrescription = preauthPrescription;
		this.consultationId = consultationId;
		this.patientPresId = patientPresId;
		this.preauthActType = preauthActType;
		this.preauthActItemId = preauthActItemId;
		this.status = status;
		this.actQty = actQty;
		this.actCodeType = actCodeType;
		this.actCode = actCode;
		this.toothUnvNumber = toothUnvNumber;
		this.toothFdiNumber = toothFdiNumber;
		this.activityDueDate = activityDueDate;
		this.modTime = modTime;
		this.username = username;
		this.preauthActItemRemarks = preauthActItemRemarks;
		this.addedToBill = addedToBill;
		this.ispackage = ispackage;
		this.mrNo = mrNo;
		this.visitId = visitId;
		this.preauthRequired = preauthRequired;
		this.preauthActStatus = preauthActStatus;
		this.preauthId = preauthId;
		this.preauthMode = preauthMode;
		this.denialCode = denialCode;
		this.denialRemarks = denialRemarks;
		this.amount = amount;
		this.claimNetAmount = claimNetAmount;
		this.claimNetApprovedAmount = claimNetApprovedAmount;
		this.rate = rate;
		this.discount = discount;
		this.docConsType = docConsType;
		this.prescribedDate = prescribedDate;
		this.patientShare = patientShare;
	}

	@Id

	@Column(name = "preauth_act_id", unique = true, nullable = false)
	public int getPreauthActId() {
		return this.preauthActId;
	}

	public void setPreauthActId(int preauthActId) {
		this.preauthActId = preauthActId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "preauth_presc_id")
	public PreauthPrescriptionModel getPreauthPrescriptionModel() {
		return this.preauthPrescription;
	}

	public void setPreauthPrescriptionModel(PreauthPrescriptionModel preauthPrescription) {
		this.preauthPrescription = preauthPrescription;
	}

	@Column(name = "consultation_id", nullable = false)
	public int getConsultationId() {
		return this.consultationId;
	}

	public void setConsultationId(int consultationId) {
		this.consultationId = consultationId;
	}

	@Column(name = "patient_pres_id", nullable = false)
	public int getPatientPresId() {
		return this.patientPresId;
	}

	public void setPatientPresId(int patientPresId) {
		this.patientPresId = patientPresId;
	}

	@Column(name = "preauth_act_type", nullable = false, length = 10)
	public String getPreauthActType() {
		return this.preauthActType;
	}

	public void setPreauthActType(String preauthActType) {
		this.preauthActType = preauthActType;
	}

	@Column(name = "preauth_act_item_id", length = 50)
	public String getPreauthActItemId() {
		return this.preauthActItemId;
	}

	public void setPreauthActItemId(String preauthActItemId) {
		this.preauthActItemId = preauthActItemId;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "act_qty", nullable = false)
	public int getActQty() {
		return this.actQty;
	}

	public void setActQty(int actQty) {
		this.actQty = actQty;
	}

	@Column(name = "act_code_type", length = 50)
	public String getActCodeType() {
		return this.actCodeType;
	}

	public void setActCodeType(String actCodeType) {
		this.actCodeType = actCodeType;
	}

	@Column(name = "act_code")
	public String getActCode() {
		return this.actCode;
	}

	public void setActCode(String actCode) {
		this.actCode = actCode;
	}

	@Column(name = "tooth_unv_number", length = 200)
	public String getToothUnvNumber() {
		return this.toothUnvNumber;
	}

	public void setToothUnvNumber(String toothUnvNumber) {
		this.toothUnvNumber = toothUnvNumber;
	}

	@Column(name = "tooth_fdi_number", length = 200)
	public String getToothFdiNumber() {
		return this.toothFdiNumber;
	}

	public void setToothFdiNumber(String toothFdiNumber) {
		this.toothFdiNumber = toothFdiNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "activity_due_date", length = 29)
	public Date getActivityDueDate() {
		return this.activityDueDate;
	}

	public void setActivityDueDate(Date activityDueDate) {
		this.activityDueDate = activityDueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "preauth_act_item_remarks", length = 2000)
	public String getPreauthActItemRemarks() {
		return this.preauthActItemRemarks;
	}

	public void setPreauthActItemRemarks(String preauthActItemRemarks) {
		this.preauthActItemRemarks = preauthActItemRemarks;
	}

	@Column(name = "added_to_bill", nullable = false, length = 1)
	public char getAddedToBill() {
		return this.addedToBill;
	}

	public void setAddedToBill(char addedToBill) {
		this.addedToBill = addedToBill;
	}

	@Column(name = "ispackage")
	public Boolean getIspackage() {
		return this.ispackage;
	}

	public void setIspackage(Boolean ispackage) {
		this.ispackage = ispackage;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "visit_id", length = 15)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Column(name = "preauth_required", nullable = false, length = 1)
	public char getPreauthRequired() {
		return this.preauthRequired;
	}

	public void setPreauthRequired(char preauthRequired) {
		this.preauthRequired = preauthRequired;
	}

	@Column(name = "preauth_act_status", nullable = false, length = 1)
	public char getPreauthActStatus() {
		return this.preauthActStatus;
	}

	public void setPreauthActStatus(char preauthActStatus) {
		this.preauthActStatus = preauthActStatus;
	}

	@Column(name = "preauth_id", length = 100)
	public String getPreauthId() {
		return this.preauthId;
	}

	public void setPreauthId(String preauthId) {
		this.preauthId = preauthId;
	}

	@Column(name = "preauth_mode")
	public Integer getPreauthMode() {
		return this.preauthMode;
	}

	public void setPreauthMode(Integer preauthMode) {
		this.preauthMode = preauthMode;
	}

	@Column(name = "denial_code", length = 15)
	public String getDenialCode() {
		return this.denialCode;
	}

	public void setDenialCode(String denialCode) {
		this.denialCode = denialCode;
	}

	@Column(name = "denial_remarks")
	public String getDenialRemarks() {
		return this.denialRemarks;
	}

	public void setDenialRemarks(String denialRemarks) {
		this.denialRemarks = denialRemarks;
	}

	@Column(name = "amount", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "claim_net_amount", nullable = false, precision = 15)
	public BigDecimal getClaimNetAmount() {
		return this.claimNetAmount;
	}

	public void setClaimNetAmount(BigDecimal claimNetAmount) {
		this.claimNetAmount = claimNetAmount;
	}

	@Column(name = "claim_net_approved_amount", nullable = false, precision = 15)
	public BigDecimal getClaimNetApprovedAmount() {
		return this.claimNetApprovedAmount;
	}

	public void setClaimNetApprovedAmount(BigDecimal claimNetApprovedAmount) {
		this.claimNetApprovedAmount = claimNetApprovedAmount;
	}

	@Column(name = "rate", nullable = false, precision = 15)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "discount", nullable = false, precision = 15)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "doc_cons_type", nullable = false)
	public int getDocConsType() {
		return this.docConsType;
	}

	public void setDocConsType(int docConsType) {
		this.docConsType = docConsType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prescribed_date", nullable = false, length = 29)
	public Date getPrescribedDate() {
		return this.prescribedDate;
	}

	public void setPrescribedDate(Date prescribedDate) {
		this.prescribedDate = prescribedDate;
	}

	@Column(name = "patient_share", nullable = false, precision = 15)
	public BigDecimal getPatientShare() {
		return this.patientShare;
	}

	public void setPatientShare(BigDecimal patientShare) {
		this.patientShare = patientShare;
	}

}
