package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PreauthApprovalAmountDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "preauth_approval_amount_details")
public class PreauthApprovalAmountDetailsModel implements java.io.Serializable {

	private PreauthApprovalAmountDetailsIdSequence id;

	public PreauthApprovalAmountDetailsModel() {
	}

	public PreauthApprovalAmountDetailsModel(PreauthApprovalAmountDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "preauthRequestId", column = @Column(name = "preauth_request_id", nullable = false)),
			@AttributeOverride(name = "preauthActId", column = @Column(name = "preauth_act_id", nullable = false)),
			@AttributeOverride(name = "denialCode", column = @Column(name = "denial_code", length = 10)),
			@AttributeOverride(name = "preauthIdPayer", column = @Column(name = "preauth_id_payer", length = 100)),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", precision = 131089, scale = 0)),
			@AttributeOverride(name = "net", column = @Column(name = "net", precision = 15)),
			@AttributeOverride(name = "list", column = @Column(name = "list", precision = 15)),
			@AttributeOverride(name = "patientShare", column = @Column(name = "patient_share", precision = 15)),
			@AttributeOverride(name = "paymentAmount", column = @Column(name = "payment_amount", precision = 15)) })
	public PreauthApprovalAmountDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(PreauthApprovalAmountDetailsIdSequence id) {
		this.id = id;
	}

}
