package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PreauthRequestApprovalDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "preauth_request_approval_details")
public class PreauthRequestApprovalDetailsModel implements java.io.Serializable {

	private String preauthRequestId;
	private String preauthRequestType;
	private Date requestDate;
	private String requestBy;
	private String fileName;
	private String fileId;
	private char isResubmit;
	private Date approvalRecdDate;
	private String preauthIdPayer;
	private Character approvalStatus;
	private String approvalComments;
	private String approvalResult;
	private BigDecimal approvalLimit;
	private Integer centerId;
	private String preauthSenderId;
	private String preauthReceiverId;
	private Set preauthPrescriptions = new HashSet(0);

	public PreauthRequestApprovalDetailsModel() {
	}

	public PreauthRequestApprovalDetailsModel(String preauthRequestId, String preauthRequestType, Date requestDate,
			char isResubmit) {
		this.preauthRequestId = preauthRequestId;
		this.preauthRequestType = preauthRequestType;
		this.requestDate = requestDate;
		this.isResubmit = isResubmit;
	}

	public PreauthRequestApprovalDetailsModel(String preauthRequestId, String preauthRequestType, Date requestDate,
			String requestBy, String fileName, String fileId, char isResubmit, Date approvalRecdDate,
			String preauthIdPayer, Character approvalStatus, String approvalComments, String approvalResult,
			BigDecimal approvalLimit, Integer centerId, String preauthSenderId, String preauthReceiverId,
			Set preauthPrescriptions) {
		this.preauthRequestId = preauthRequestId;
		this.preauthRequestType = preauthRequestType;
		this.requestDate = requestDate;
		this.requestBy = requestBy;
		this.fileName = fileName;
		this.fileId = fileId;
		this.isResubmit = isResubmit;
		this.approvalRecdDate = approvalRecdDate;
		this.preauthIdPayer = preauthIdPayer;
		this.approvalStatus = approvalStatus;
		this.approvalComments = approvalComments;
		this.approvalResult = approvalResult;
		this.approvalLimit = approvalLimit;
		this.centerId = centerId;
		this.preauthSenderId = preauthSenderId;
		this.preauthReceiverId = preauthReceiverId;
		this.preauthPrescriptions = preauthPrescriptions;
	}

	@Id

	@Column(name = "preauth_request_id", unique = true, nullable = false, length = 50)
	public String getPreauthRequestId() {
		return this.preauthRequestId;
	}

	public void setPreauthRequestId(String preauthRequestId) {
		this.preauthRequestId = preauthRequestId;
	}

	@Column(name = "preauth_request_type", nullable = false, length = 30)
	public String getPreauthRequestType() {
		return this.preauthRequestType;
	}

	public void setPreauthRequestType(String preauthRequestType) {
		this.preauthRequestType = preauthRequestType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_date", nullable = false, length = 29)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Column(name = "request_by", length = 30)
	public String getRequestBy() {
		return this.requestBy;
	}

	public void setRequestBy(String requestBy) {
		this.requestBy = requestBy;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_id")
	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	@Column(name = "is_resubmit", nullable = false, length = 1)
	public char getIsResubmit() {
		return this.isResubmit;
	}

	public void setIsResubmit(char isResubmit) {
		this.isResubmit = isResubmit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approval_recd_date", length = 29)
	public Date getApprovalRecdDate() {
		return this.approvalRecdDate;
	}

	public void setApprovalRecdDate(Date approvalRecdDate) {
		this.approvalRecdDate = approvalRecdDate;
	}

	@Column(name = "preauth_id_payer", length = 100)
	public String getPreauthIdPayer() {
		return this.preauthIdPayer;
	}

	public void setPreauthIdPayer(String preauthIdPayer) {
		this.preauthIdPayer = preauthIdPayer;
	}

	@Column(name = "approval_status", length = 1)
	public Character getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(Character approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	@Column(name = "approval_comments", length = 500)
	public String getApprovalComments() {
		return this.approvalComments;
	}

	public void setApprovalComments(String approvalComments) {
		this.approvalComments = approvalComments;
	}

	@Column(name = "approval_result", length = 3)
	public String getApprovalResult() {
		return this.approvalResult;
	}

	public void setApprovalResult(String approvalResult) {
		this.approvalResult = approvalResult;
	}

	@Column(name = "approval_limit", precision = 131089, scale = 0)
	public BigDecimal getApprovalLimit() {
		return this.approvalLimit;
	}

	public void setApprovalLimit(BigDecimal approvalLimit) {
		this.approvalLimit = approvalLimit;
	}

	@Column(name = "center_id")
	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	@Column(name = "preauth_sender_id")
	public String getPreauthSenderId() {
		return this.preauthSenderId;
	}

	public void setPreauthSenderId(String preauthSenderId) {
		this.preauthSenderId = preauthSenderId;
	}

	@Column(name = "preauth_receiver_id")
	public String getPreauthReceiverId() {
		return this.preauthReceiverId;
	}

	public void setPreauthReceiverId(String preauthReceiverId) {
		this.preauthReceiverId = preauthReceiverId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preauthRequestApprovalDetails")
	public Set getPreauthPrescriptions() {
		return this.preauthPrescriptions;
	}

	public void setPreauthPrescriptions(Set preauthPrescriptions) {
		this.preauthPrescriptions = preauthPrescriptions;
	}

}
