package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProgressNotesModel generated by hbm2java
 */
@Entity
@Table(name = "progress_notes")
public class ProgressNotesModel implements java.io.Serializable {

	private ProgressNotesIdSequence id;

	public ProgressNotesModel() {
	}

	public ProgressNotesModel(ProgressNotesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "progressNotesId", column = @Column(name = "progress_notes_id", nullable = false)),
			@AttributeOverride(name = "mrNo", column = @Column(name = "mr_no", length = 15)),
			@AttributeOverride(name = "dateTime", column = @Column(name = "date_time", length = 29)),
			@AttributeOverride(name = "doctor", column = @Column(name = "doctor", length = 20)),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 30)),
			@AttributeOverride(name = "notes", column = @Column(name = "notes")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "visitId", column = @Column(name = "visit_id", length = 15)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)) })
	public ProgressNotesIdSequence getId() {
		return this.id;
	}

	public void setId(ProgressNotesIdSequence id) {
		this.id = id;
	}

}
