package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RegistrationChargesBackupModel generated by hbm2java
 */
@Entity
@Table(name = "registration_charges_backup")
public class RegistrationChargesBackupModel implements java.io.Serializable {

	private RegistrationChargesBackupIdSequence id;

	public RegistrationChargesBackupModel() {
	}

	public RegistrationChargesBackupModel(RegistrationChargesBackupIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "bkpTime", column = @Column(name = "bkp_time", length = 29)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", length = 50)),
			@AttributeOverride(name = "ipRegCharge", column = @Column(name = "ip_reg_charge", precision = 15)),
			@AttributeOverride(name = "opRegCharge", column = @Column(name = "op_reg_charge", precision = 15)),
			@AttributeOverride(name = "genRegCharge", column = @Column(name = "gen_reg_charge", precision = 15)),
			@AttributeOverride(name = "regRenewalCharge", column = @Column(name = "reg_renewal_charge", precision = 15)),
			@AttributeOverride(name = "mrcharge", column = @Column(name = "mrcharge", precision = 15)),
			@AttributeOverride(name = "ipMlccharge", column = @Column(name = "ip_mlccharge", precision = 15)),
			@AttributeOverride(name = "genRegChargeDiscount", column = @Column(name = "gen_reg_charge_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "opRegChargeDiscount", column = @Column(name = "op_reg_charge_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "regRenewalChargeDiscount", column = @Column(name = "reg_renewal_charge_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "ipRegChargeDiscount", column = @Column(name = "ip_reg_charge_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "ipMlcchargeDiscount", column = @Column(name = "ip_mlccharge_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "mrchargeDiscount", column = @Column(name = "mrcharge_discount", nullable = false, precision = 15)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", length = 50)),
			@AttributeOverride(name = "opMlccharge", column = @Column(name = "op_mlccharge", nullable = false, precision = 15)),
			@AttributeOverride(name = "opMlcchargeDiscount", column = @Column(name = "op_mlccharge_discount", nullable = false, precision = 15)) })
	public RegistrationChargesBackupIdSequence getId() {
		return this.id;
	}

	public void setId(RegistrationChargesBackupIdSequence id) {
		this.id = id;
	}

}
