package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RelationMasterModel generated by hbm2java
 */
@Entity
@Table(name = "relation_master")
public class RelationMasterModel implements java.io.Serializable {

	private RelationMasterIdSequence id;

	public RelationMasterModel() {
	}

	public RelationMasterModel(RelationMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "relationId", column = @Column(name = "relation_id", nullable = false, length = 15)),
			@AttributeOverride(name = "relationName", column = @Column(name = "relation__name", nullable = false, length = 50)) })
	public RelationMasterIdSequence getId() {
		return this.id;
	}

	public void setId(RelationMasterIdSequence id) {
		this.id = id;
	}

}
