package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RewardPointsEarningsModel generated by hbm2java
 */
@Entity
@Table(name = "reward_points_earnings")
public class RewardPointsEarningsModel implements java.io.Serializable {

	private int entryId;
	private String mrNo;
	private Date date;
	private char entryType;
	private String billNo;
	private BigDecimal eligibleValue;
	private int points;
	private String remarks;

	public RewardPointsEarningsModel() {
	}

	public RewardPointsEarningsModel(int entryId, String mrNo, Date date, char entryType, String billNo,
			BigDecimal eligibleValue, int points) {
		this.entryId = entryId;
		this.mrNo = mrNo;
		this.date = date;
		this.entryType = entryType;
		this.billNo = billNo;
		this.eligibleValue = eligibleValue;
		this.points = points;
	}

	public RewardPointsEarningsModel(int entryId, String mrNo, Date date, char entryType, String billNo,
			BigDecimal eligibleValue, int points, String remarks) {
		this.entryId = entryId;
		this.mrNo = mrNo;
		this.date = date;
		this.entryType = entryType;
		this.billNo = billNo;
		this.eligibleValue = eligibleValue;
		this.points = points;
		this.remarks = remarks;
	}

	@Id

	@Column(name = "entry_id", unique = true, nullable = false)
	public int getEntryId() {
		return this.entryId;
	}

	public void setEntryId(int entryId) {
		this.entryId = entryId;
	}

	@Column(name = "mr_no", nullable = false, length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "entry_type", nullable = false, length = 1)
	public char getEntryType() {
		return this.entryType;
	}

	public void setEntryType(char entryType) {
		this.entryType = entryType;
	}

	@Column(name = "bill_no", nullable = false, length = 15)
	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	@Column(name = "eligible_value", nullable = false, precision = 15)
	public BigDecimal getEligibleValue() {
		return this.eligibleValue;
	}

	public void setEligibleValue(BigDecimal eligibleValue) {
		this.eligibleValue = eligibleValue;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	@Column(name = "remarks", length = 4000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
