package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SampleBarCodePrintTemplatesModel generated by hbm2java
 */
@Entity
@Table(name = "sample_bar_code_print_templates")
public class SampleBarCodePrintTemplatesModel implements java.io.Serializable {

	private SampleBarCodePrintTemplatesIdSequence id;

	public SampleBarCodePrintTemplatesModel() {
	}

	public SampleBarCodePrintTemplatesModel(SampleBarCodePrintTemplatesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", length = 50)),
			@AttributeOverride(name = "printTemplateContent", column = @Column(name = "print_template_content")),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 50)),
			@AttributeOverride(name = "reason", column = @Column(name = "reason", length = 100)) })
	public SampleBarCodePrintTemplatesIdSequence getId() {
		return this.id;
	}

	public void setId(SampleBarCodePrintTemplatesIdSequence id) {
		this.id = id;
	}

}
