package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SampleRejectionsIdSequence generated by hbm2java
 */
@Embeddable
public class SampleRejectionsIdSequence implements java.io.Serializable {

	private int rejectionId;
	private Integer testPrescribedId;
	private Integer sampleCollectionId;

	public SampleRejectionsIdSequence() {
	}

	public SampleRejectionsIdSequence(int rejectionId) {
		this.rejectionId = rejectionId;
	}

	public SampleRejectionsIdSequence(int rejectionId, Integer testPrescribedId, Integer sampleCollectionId) {
		this.rejectionId = rejectionId;
		this.testPrescribedId = testPrescribedId;
		this.sampleCollectionId = sampleCollectionId;
	}

	@Column(name = "rejection_id", nullable = false)
	public int getRejectionId() {
		return this.rejectionId;
	}

	public void setRejectionId(int rejectionId) {
		this.rejectionId = rejectionId;
	}

	@Column(name = "test_prescribed_id")
	public Integer getTestPrescribedId() {
		return this.testPrescribedId;
	}

	public void setTestPrescribedId(Integer testPrescribedId) {
		this.testPrescribedId = testPrescribedId;
	}

	@Column(name = "sample_collection_id")
	public Integer getSampleCollectionId() {
		return this.sampleCollectionId;
	}

	public void setSampleCollectionId(Integer sampleCollectionId) {
		this.sampleCollectionId = sampleCollectionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SampleRejectionsIdSequence))
			return false;
		SampleRejectionsIdSequence castOther = (SampleRejectionsIdSequence) other;

		return (this.getRejectionId() == castOther.getRejectionId())
				&& ((this.getTestPrescribedId() == castOther.getTestPrescribedId())
						|| (this.getTestPrescribedId() != null && castOther.getTestPrescribedId() != null
								&& this.getTestPrescribedId().equals(castOther.getTestPrescribedId())))
				&& ((this.getSampleCollectionId() == castOther.getSampleCollectionId())
						|| (this.getSampleCollectionId() != null && castOther.getSampleCollectionId() != null
								&& this.getSampleCollectionId().equals(castOther.getSampleCollectionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRejectionId();
		result = 37 * result + (getTestPrescribedId() == null ? 0 : this.getTestPrescribedId().hashCode());
		result = 37 * result + (getSampleCollectionId() == null ? 0 : this.getSampleCollectionId().hashCode());
		return result;
	}

}
