package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ScheduledExportPrefsModel generated by hbm2java
 */
@Entity
@Table(name = "scheduled_export_prefs", uniqueConstraints = @UniqueConstraint(columnNames = "directory"))
public class ScheduledExportPrefsModel implements java.io.Serializable {

	private ScheduledExportPrefsIdSequence id;

	public ScheduledExportPrefsModel() {
	}

	public ScheduledExportPrefsModel(ScheduledExportPrefsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "period", column = @Column(name = "period", nullable = false, length = 5)),
			@AttributeOverride(name = "hourlyTime", column = @Column(name = "hourly_time")),
			@AttributeOverride(name = "dailyOrWeeklyTime", column = @Column(name = "daily_or_weekly_time", length = 15)),
			@AttributeOverride(name = "weeklyOn", column = @Column(name = "weekly_on", length = 3)),
			@AttributeOverride(name = "accountGroup", column = @Column(name = "account_group", nullable = false)),
			@AttributeOverride(name = "exportItems", column = @Column(name = "export_items")),
			@AttributeOverride(name = "directory", column = @Column(name = "directory", unique = true, length = 1000)),
			@AttributeOverride(name = "scheduleName", column = @Column(name = "schedule_name", length = 100)),
			@AttributeOverride(name = "scheduleId", column = @Column(name = "schedule_id", nullable = false)),
			@AttributeOverride(name = "centerId", column = @Column(name = "center_id", nullable = false)),
			@AttributeOverride(name = "exportType", column = @Column(name = "export_type", nullable = false, length = 20)),
			@AttributeOverride(name = "targetUrl", column = @Column(name = "target_url", length = 2000)),
			@AttributeOverride(name = "voucherDate", column = @Column(name = "voucher_date", length = 13)) })
	public ScheduledExportPrefsIdSequence getId() {
		return this.id;
	}

	public void setId(ScheduledExportPrefsIdSequence id) {
		this.id = id;
	}

}
