package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SchedulerAppointmentItemsModel generated by hbm2java
 */
@Entity
@Table(name = "scheduler_appointment_items")
public class SchedulerAppointmentItemsModel implements java.io.Serializable {

	private SchedulerAppointmentItemsIdSequence id;

	public SchedulerAppointmentItemsModel() {
	}

	public SchedulerAppointmentItemsModel(SchedulerAppointmentItemsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "appointmentId", column = @Column(name = "appointment_id")),
			@AttributeOverride(name = "resourceType", column = @Column(name = "resource_type", length = 10)),
			@AttributeOverride(name = "resourceId", column = @Column(name = "resource_id", length = 10)),
			@AttributeOverride(name = "appointmentItemId", column = @Column(name = "appointment_item_id")),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 30)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", length = 29)) })
	public SchedulerAppointmentItemsIdSequence getId() {
		return this.id;
	}

	public void setId(SchedulerAppointmentItemsIdSequence id) {
		this.id = id;
	}

}
