package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScoreCardMainModel generated by hbm2java
 */
@Entity
@Table(name = "score_card_main")
public class ScoreCardMainModel implements java.io.Serializable {

	private int scoreCardId;
	private String mrNo;
	private Byte cardMonth;
	private Short cardYear;
	private String nephrologist;
	private Date saveDate;
	private String username;

	public ScoreCardMainModel() {
	}

	public ScoreCardMainModel(int scoreCardId) {
		this.scoreCardId = scoreCardId;
	}

	public ScoreCardMainModel(int scoreCardId, String mrNo, Byte cardMonth, Short cardYear, String nephrologist,
			Date saveDate, String username) {
		this.scoreCardId = scoreCardId;
		this.mrNo = mrNo;
		this.cardMonth = cardMonth;
		this.cardYear = cardYear;
		this.nephrologist = nephrologist;
		this.saveDate = saveDate;
		this.username = username;
	}

	@Id

	@Column(name = "score_card_id", unique = true, nullable = false)
	public int getScoreCardId() {
		return this.scoreCardId;
	}

	public void setScoreCardId(int scoreCardId) {
		this.scoreCardId = scoreCardId;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "card_month", precision = 2, scale = 0)
	public Byte getCardMonth() {
		return this.cardMonth;
	}

	public void setCardMonth(Byte cardMonth) {
		this.cardMonth = cardMonth;
	}

	@Column(name = "card_year", precision = 4, scale = 0)
	public Short getCardYear() {
		return this.cardYear;
	}

	public void setCardYear(Short cardYear) {
		this.cardYear = cardYear;
	}

	@Column(name = "nephrologist")
	public String getNephrologist() {
		return this.nephrologist;
	}

	public void setNephrologist(String nephrologist) {
		this.nephrologist = nephrologist;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "save_date", length = 29)
	public Date getSaveDate() {
		return this.saveDate;
	}

	public void setSaveDate(Date saveDate) {
		this.saveDate = saveDate;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
