package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ScoreCardDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "score_card_details")
public class ScoreCardDetailsModel implements java.io.Serializable {

	private ScoreCardDetailsIdSequence id;
	private String severity;
	private String value;
	private String range;

	public ScoreCardDetailsModel() {
	}

	public ScoreCardDetailsModel(ScoreCardDetailsIdSequence id) {
		this.id = id;
	}

	public ScoreCardDetailsModel(ScoreCardDetailsIdSequence id, String severity, String value, String range) {
		this.id = id;
		this.severity = severity;
		this.value = value;
		this.range = range;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "scoreCardId", column = @Column(name = "score_card_id", nullable = false)),
			@AttributeOverride(name = "attribute", column = @Column(name = "attribute", nullable = false, length = 100)) })
	public ScoreCardDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(ScoreCardDetailsIdSequence id) {
		this.id = id;
	}

	@Column(name = "severity", length = 100)
	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "range")
	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

}
