package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScreenGroupRightsIdSequence generated by hbm2java
 */
@Embeddable
public class ScreenGroupRightsIdSequence implements java.io.Serializable {

	private Integer roleId;
	private String groupId;
	private Character rights;

	public ScreenGroupRightsIdSequence() {
	}

	public ScreenGroupRightsIdSequence(Integer roleId, String groupId, Character rights) {
		this.roleId = roleId;
		this.groupId = groupId;
		this.rights = rights;
	}

	@Column(name = "role_id", precision = 5, scale = 0)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "group_id", length = 40)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "rights", length = 1)
	public Character getRights() {
		return this.rights;
	}

	public void setRights(Character rights) {
		this.rights = rights;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScreenGroupRightsIdSequence))
			return false;
		ScreenGroupRightsIdSequence castOther = (ScreenGroupRightsIdSequence) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
				&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this.getGroupId() != null
						&& castOther.getGroupId() != null && this.getGroupId().equals(castOther.getGroupId())))
				&& ((this.getRights() == castOther.getRights()) || (this.getRights() != null
						&& castOther.getRights() != null && this.getRights().equals(castOther.getRights())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		result = 37 * result + (getRights() == null ? 0 : this.getRights().hashCode());
		return result;
	}

}
