package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.item.StoreItemDetailsModel;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServiceConsumablesModel generated by hbm2java
 */
@Entity
@Table(name = "service_consumables")
public class ServiceConsumablesModel implements java.io.Serializable {

	private ServiceConsumablesIdSequence id;
	private StoreItemDetailsModel storeItemDetails;

	public ServiceConsumablesModel() {
	}

	public ServiceConsumablesModel(ServiceConsumablesIdSequence id, StoreItemDetailsModel storeItemDetails) {
		this.id = id;
		this.storeItemDetails = storeItemDetails;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "serviceId", column = @Column(name = "service_id", nullable = false, length = 20)),
			@AttributeOverride(name = "quantityNeeded", column = @Column(name = "quantity_needed", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "consumableId", column = @Column(name = "consumable_id", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 1)) })
	public ServiceConsumablesIdSequence getId() {
		return this.id;
	}

	public void setId(ServiceConsumablesIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consumable_id", nullable = false, insertable = false, updatable = false)
	public StoreItemDetailsModel getStoreItemDetailsModel() {
		return this.storeItemDetails;
	}

	public void setStoreItemDetailsModel(StoreItemDetailsModel storeItemDetails) {
		this.storeItemDetails = storeItemDetails;
	}

}
