package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServicesPrescTasksModel generated by hbm2java
 */
@Entity
@Table(name = "services_presc_tasks")
public class ServicesPrescTasksModel implements java.io.Serializable {

	private int taskPrescId;
	private Integer treatmentId;
	private Integer subTaskId;
	private String completedBy;
	private Date completionTime;
	private String status;

	public ServicesPrescTasksModel() {
	}

	public ServicesPrescTasksModel(int taskPrescId) {
		this.taskPrescId = taskPrescId;
	}

	public ServicesPrescTasksModel(int taskPrescId, Integer treatmentId, Integer subTaskId, String completedBy,
			Date completionTime, String status) {
		this.taskPrescId = taskPrescId;
		this.treatmentId = treatmentId;
		this.subTaskId = subTaskId;
		this.completedBy = completedBy;
		this.completionTime = completionTime;
		this.status = status;
	}

	@Id

	@Column(name = "task_presc_id", unique = true, nullable = false)
	public int getTaskPrescId() {
		return this.taskPrescId;
	}

	public void setTaskPrescId(int taskPrescId) {
		this.taskPrescId = taskPrescId;
	}

	@Column(name = "treatment_id")
	public Integer getTreatmentId() {
		return this.treatmentId;
	}

	public void setTreatmentId(Integer treatmentId) {
		this.treatmentId = treatmentId;
	}

	@Column(name = "sub_task_id")
	public Integer getSubTaskId() {
		return this.subTaskId;
	}

	public void setSubTaskId(Integer subTaskId) {
		this.subTaskId = subTaskId;
	}

	@Column(name = "completed_by", length = 30)
	public String getCompletedBy() {
		return this.completedBy;
	}

	public void setCompletedBy(String completedBy) {
		this.completedBy = completedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "completion_time", length = 29)
	public Date getCompletionTime() {
		return this.completionTime;
	}

	public void setCompletionTime(Date completionTime) {
		this.completionTime = completionTime;
	}

	@Column(name = "status", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
