package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShiftMasterModel generated by hbm2java
 */
@Entity
@Table(name = "shift_master")
public class ShiftMasterModel implements java.io.Serializable {

	private int shiftId;
	private String shiftName;
	private Date shiftStartTime;
	private Date shiftEndTime;
	private String status;
	private int shiftOrder;
	private int centerId;

	public ShiftMasterModel() {
	}

	public ShiftMasterModel(int shiftId, String shiftName, Date shiftStartTime, Date shiftEndTime, int shiftOrder,
			int centerId) {
		this.shiftId = shiftId;
		this.shiftName = shiftName;
		this.shiftStartTime = shiftStartTime;
		this.shiftEndTime = shiftEndTime;
		this.shiftOrder = shiftOrder;
		this.centerId = centerId;
	}

	public ShiftMasterModel(int shiftId, String shiftName, Date shiftStartTime, Date shiftEndTime, String status,
			int shiftOrder, int centerId) {
		this.shiftId = shiftId;
		this.shiftName = shiftName;
		this.shiftStartTime = shiftStartTime;
		this.shiftEndTime = shiftEndTime;
		this.status = status;
		this.shiftOrder = shiftOrder;
		this.centerId = centerId;
	}

	@Id

	@Column(name = "shift_id", unique = true, nullable = false)
	public int getShiftId() {
		return this.shiftId;
	}

	public void setShiftId(int shiftId) {
		this.shiftId = shiftId;
	}

	@Column(name = "shift_name", nullable = false, length = 50)
	public String getShiftName() {
		return this.shiftName;
	}

	public void setShiftName(String shiftName) {
		this.shiftName = shiftName;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "shift_start_time", nullable = false, length = 15)
	public Date getShiftStartTime() {
		return this.shiftStartTime;
	}

	public void setShiftStartTime(Date shiftStartTime) {
		this.shiftStartTime = shiftStartTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "shift_end_time", nullable = false, length = 15)
	public Date getShiftEndTime() {
		return this.shiftEndTime;
	}

	public void setShiftEndTime(Date shiftEndTime) {
		this.shiftEndTime = shiftEndTime;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "shift_order", nullable = false)
	public int getShiftOrder() {
		return this.shiftOrder;
	}

	public void setShiftOrder(int shiftOrder) {
		this.shiftOrder = shiftOrder;
	}

	@Column(name = "center_id", nullable = false)
	public int getCenterId() {
		return this.centerId;
	}

	public void setCenterId(int centerId) {
		this.centerId = centerId;
	}

}
