package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SoldPackagesContentsModel generated by hbm2java
 */
@Entity
@Table(name = "sold_packages_contents")
public class SoldPackagesContentsModel implements java.io.Serializable {

	private int soldPackagesContentsId;
	private int soldPackageId;
	private String activityId;
	private String activityType;
	private Integer activityQty;
	private String activityQtyUom;
	private String activityRemarks;
	private String doctorId;
	private String deptId;
	private Integer displayOrder;
	private String modifiedBy;
	private Date modifiedAt;
	private String createdBy;
	private Date createdAt;

	public SoldPackagesContentsModel() {
	}

	public SoldPackagesContentsModel(int soldPackagesContentsId, int soldPackageId) {
		this.soldPackagesContentsId = soldPackagesContentsId;
		this.soldPackageId = soldPackageId;
	}

	public SoldPackagesContentsModel(int soldPackagesContentsId, int soldPackageId, String activityId, String activityType,
			Integer activityQty, String activityQtyUom, String activityRemarks, String doctorId, String deptId,
			Integer displayOrder, String modifiedBy, Date modifiedAt, String createdBy, Date createdAt) {
		this.soldPackagesContentsId = soldPackagesContentsId;
		this.soldPackageId = soldPackageId;
		this.activityId = activityId;
		this.activityType = activityType;
		this.activityQty = activityQty;
		this.activityQtyUom = activityQtyUom;
		this.activityRemarks = activityRemarks;
		this.doctorId = doctorId;
		this.deptId = deptId;
		this.displayOrder = displayOrder;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
	}

	@Id

	@Column(name = "sold_packages_contents_id", unique = true, nullable = false)
	public int getSoldPackagesContentsIdSequence() {
		return this.soldPackagesContentsId;
	}

	public void setSoldPackagesContentsIdSequence(int soldPackagesContentsId) {
		this.soldPackagesContentsId = soldPackagesContentsId;
	}

	@Column(name = "sold_package_id", nullable = false)
	public int getSoldPackageId() {
		return this.soldPackageId;
	}

	public void setSoldPackageId(int soldPackageId) {
		this.soldPackageId = soldPackageId;
	}

	@Column(name = "activity_id", length = 200)
	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	@Column(name = "activity_type", length = 50)
	public String getActivityType() {
		return this.activityType;
	}

	public void setActivityType(String activityType) {
		this.activityType = activityType;
	}

	@Column(name = "activity_qty")
	public Integer getActivityQty() {
		return this.activityQty;
	}

	public void setActivityQty(Integer activityQty) {
		this.activityQty = activityQty;
	}

	@Column(name = "activity_qty_uom")
	public String getActivityQtyUom() {
		return this.activityQtyUom;
	}

	public void setActivityQtyUom(String activityQtyUom) {
		this.activityQtyUom = activityQtyUom;
	}

	@Column(name = "activity_remarks")
	public String getActivityRemarks() {
		return this.activityRemarks;
	}

	public void setActivityRemarks(String activityRemarks) {
		this.activityRemarks = activityRemarks;
	}

	@Column(name = "doctor_id", length = 20)
	public String getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "dept_id", length = 20)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "display_order")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "modified_by", length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_at", length = 29)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
