package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SponsorPrintTemplatesModel generated by hbm2java
 */
@Entity
@Table(name = "sponsor_print_templates")
public class SponsorPrintTemplatesModel implements java.io.Serializable {

	private SponsorPrintTemplatesIdSequence id;

	public SponsorPrintTemplatesModel() {
	}

	public SponsorPrintTemplatesModel(SponsorPrintTemplatesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "sponsorId", column = @Column(name = "sponsor_id", length = 15)),
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", length = 50)) })
	public SponsorPrintTemplatesIdSequence getId() {
		return this.id;
	}

	public void setId(SponsorPrintTemplatesIdSequence id) {
		this.id = id;
	}

}
