package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SponsorApprovedChargesModel generated by hbm2java
 */
@Entity
@Table(name = "sponsor_approved_charges")
public class SponsorApprovedChargesModel implements java.io.Serializable {

	private SponsorApprovedChargesIdSequence id;

	public SponsorApprovedChargesModel() {
	}

	public SponsorApprovedChargesModel(SponsorApprovedChargesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "chargeId", column = @Column(name = "charge_id", nullable = false, length = 15)),
			@AttributeOverride(name = "sponsorApprovalDetailId", column = @Column(name = "sponsor_approval_detail_id", nullable = false)),
			@AttributeOverride(name = "originalChargeId", column = @Column(name = "original_charge_id", length = 15)) })
	public SponsorApprovedChargesIdSequence getId() {
		return this.id;
	}

	public void setId(SponsorApprovedChargesIdSequence id) {
		this.id = id;
	}

}
