package com.insta.hms.model;

// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.stores.StoresModel;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockIssueMainModel generated by hbm2java
 */
@Entity
@Table(name = "stock_issue_main")
public class StockIssueMainModel implements java.io.Serializable {

  private BigDecimal userIssueNo;
  private StoresModel stores;
  private Date dateTime;
  private String userType;
  private String issuedTo;
  private String reference;
  private String username;
  private String wardNo;

  public StockIssueMainModel() {
  }

  public StockIssueMainModel(BigDecimal userIssueNo, StoresModel stores, String userType) {
    this.userIssueNo = userIssueNo;
    this.stores = stores;
    this.userType = userType;
  }

  public StockIssueMainModel(BigDecimal userIssueNo, StoresModel stores,
      Date dateTime, String userType, String issuedTo,
      String reference, String username, String wardNo) {
    this.userIssueNo = userIssueNo;
    this.stores = stores;
    this.dateTime = dateTime;
    this.userType = userType;
    this.issuedTo = issuedTo;
    this.reference = reference;
    this.username = username;
    this.wardNo = wardNo;
  }

  @Id
  @Column(name = "user_issue_no", unique = true, nullable = false, precision = 131089, scale = 0)
  public BigDecimal getUserIssueNo() {
    return this.userIssueNo;
  }

  public void setUserIssueNo(BigDecimal userIssueNo) {
    this.userIssueNo = userIssueNo;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "dept_from", nullable = false)
  public StoresModel getStoresModel() {
    return this.stores;
  }

  public void setStoresModel(StoresModel stores) {
    this.stores = stores;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "date_time", length = 29)
  public Date getDateTime() {
    return this.dateTime;
  }

  public void setDateTime(Date dateTime) {
    this.dateTime = dateTime;
  }

  @Column(name = "user_type", nullable = false, length = 20)
  public String getUserType() {
    return this.userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }

  @Column(name = "issued_to", length = 60)
  public String getIssuedTo() {
    return this.issuedTo;
  }

  public void setIssuedTo(String issuedTo) {
    this.issuedTo = issuedTo;
  }

  @Column(name = "reference")
  public String getReference() {
    return this.reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  @Column(name = "username")
  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  @Column(name = "ward_no", length = 10)
  public String getWardNo() {
    return this.wardNo;
  }

  public void setWardNo(String wardNo) {
    this.wardNo = wardNo;
  }
}
