package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.item.StoreItemDetailsModel;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StoreConsignmentInvoiceModel generated by hbm2java
 */
@Entity
@Table(name = "store_consignment_invoice")
public class StoreConsignmentInvoiceModel implements java.io.Serializable {

	private StoreConsignmentInvoiceIdSequence id;
	private StoreItemDetailsModel storeItemDetails;
	private StoreInvoiceModel storeInvoice;

	public StoreConsignmentInvoiceModel() {
	}

	public StoreConsignmentInvoiceModel(StoreConsignmentInvoiceIdSequence id, StoreItemDetailsModel storeItemDetails,
			StoreInvoiceModel storeInvoice) {
		this.id = id;
		this.storeItemDetails = storeItemDetails;
		this.storeInvoice = storeInvoice;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "grnNo", column = @Column(name = "grn_no", nullable = false, length = 20)),
			@AttributeOverride(name = "conInvoiceDate", column = @Column(name = "con_invoice_date", nullable = false, length = 29)),
			@AttributeOverride(name = "issueId", column = @Column(name = "issue_id", nullable = false)),
			@AttributeOverride(name = "medicineId", column = @Column(name = "medicine_id", nullable = false)),
			@AttributeOverride(name = "batchNo", column = @Column(name = "batch_no", nullable = false, length = 100)),
			@AttributeOverride(name = "qty", column = @Column(name = "qty", precision = 10)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", precision = 15)),
			@AttributeOverride(name = "billNo", column = @Column(name = "bill_no", length = 15)),
			@AttributeOverride(name = "amountPayable", column = @Column(name = "amount_payable", precision = 15)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 50)),
			@AttributeOverride(name = "paymentId", column = @Column(name = "payment_id", length = 20)),
			@AttributeOverride(name = "supplierInvoiceId", column = @Column(name = "supplier_invoice_id", nullable = false)),
			@AttributeOverride(name = "consignmentInvoiceNo", column = @Column(name = "consignment_invoice_no")) })
	public StoreConsignmentInvoiceIdSequence getId() {
		return this.id;
	}

	public void setId(StoreConsignmentInvoiceIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicine_id", nullable = false, insertable = false, updatable = false)
	public StoreItemDetailsModel getStoreItemDetailsModel() {
		return this.storeItemDetails;
	}

	public void setStoreItemDetailsModel(StoreItemDetailsModel storeItemDetails) {
		this.storeItemDetails = storeItemDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_invoice_id", nullable = false, insertable = false, updatable = false)
	public StoreInvoiceModel getStoreInvoiceModel() {
		return this.storeInvoice;
	}

	public void setStoreInvoiceModel(StoreInvoiceModel storeInvoice) {
		this.storeInvoice = storeInvoice;
	}

}
