package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StoreTransferReceiveIndentModel generated by hbm2java
 */
@Entity
@Table(name = "store_transfer_receive_indent")
public class StoreTransferReceiveIndentModel implements java.io.Serializable {

	private StoreTransferReceiveIndentIdSequence id;

	public StoreTransferReceiveIndentModel() {
	}

	public StoreTransferReceiveIndentModel(StoreTransferReceiveIndentIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "transferReceiptId", column = @Column(name = "transfer_receipt_id", nullable = false)),
			@AttributeOverride(name = "transferDetailNo", column = @Column(name = "transfer_detail_no")),
			@AttributeOverride(name = "qtyRecd", column = @Column(name = "qty_recd", nullable = false, precision = 10)),
			@AttributeOverride(name = "qtyRejected", column = @Column(name = "qty_rejected", nullable = false, precision = 10)),
			@AttributeOverride(name = "costValue", column = @Column(name = "cost_value", precision = 131089, scale = 0)),
			@AttributeOverride(name = "receiveDatetime", column = @Column(name = "receive_datetime", length = 29)) })
	public StoreTransferReceiveIndentIdSequence getId() {
		return this.id;
	}

	public void setId(StoreTransferReceiveIndentIdSequence id) {
		this.id = id;
	}

}
