package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StoreCategoryMasterModel generated by hbm2java
 */
@Entity
@Table(name = "store_category_master", uniqueConstraints = @UniqueConstraint(columnNames = "category"))
public class StoreCategoryMasterModel implements java.io.Serializable {

	private int categoryId;
	private String category;
	private char identification;
	private char issueType;
	private boolean billable;
	private Character status;
	private Boolean claimable;
	private Boolean expiryDateVal;
	private Boolean retailable;
	private BigDecimal discount;
	private String purchasesCatVatAccountPrefix;
	private String purchasesCatCstAccountPrefix;
	private String salesCatVatAccountPrefix;
	private Character assetTracking;

	public StoreCategoryMasterModel() {
	}

	public StoreCategoryMasterModel(int categoryId, String category, char identification, char issueType, boolean billable,
			String purchasesCatVatAccountPrefix, String purchasesCatCstAccountPrefix) {
		this.categoryId = categoryId;
		this.category = category;
		this.identification = identification;
		this.issueType = issueType;
		this.billable = billable;
		this.purchasesCatVatAccountPrefix = purchasesCatVatAccountPrefix;
		this.purchasesCatCstAccountPrefix = purchasesCatCstAccountPrefix;
	}

	public StoreCategoryMasterModel(int categoryId, String category, char identification, char issueType, boolean billable,
			Character status, Boolean claimable, Boolean expiryDateVal, Boolean retailable, BigDecimal discount,
			String purchasesCatVatAccountPrefix, String purchasesCatCstAccountPrefix, String salesCatVatAccountPrefix,
			Character assetTracking) {
		this.categoryId = categoryId;
		this.category = category;
		this.identification = identification;
		this.issueType = issueType;
		this.billable = billable;
		this.status = status;
		this.claimable = claimable;
		this.expiryDateVal = expiryDateVal;
		this.retailable = retailable;
		this.discount = discount;
		this.purchasesCatVatAccountPrefix = purchasesCatVatAccountPrefix;
		this.purchasesCatCstAccountPrefix = purchasesCatCstAccountPrefix;
		this.salesCatVatAccountPrefix = salesCatVatAccountPrefix;
		this.assetTracking = assetTracking;
	}

	@Id

	@Column(name = "category_id", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category", unique = true, nullable = false, length = 200)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "identification", nullable = false, length = 1)
	public char getIdentification() {
		return this.identification;
	}

	public void setIdentification(char identification) {
		this.identification = identification;
	}

	@Column(name = "issue_type", nullable = false, length = 1)
	public char getIssueType() {
		return this.issueType;
	}

	public void setIssueType(char issueType) {
		this.issueType = issueType;
	}

	@Column(name = "billable", nullable = false)
	public boolean isBillable() {
		return this.billable;
	}

	public void setBillable(boolean billable) {
		this.billable = billable;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "claimable")
	public Boolean getClaimable() {
		return this.claimable;
	}

	public void setClaimable(Boolean claimable) {
		this.claimable = claimable;
	}

	@Column(name = "expiry_date_val")
	public Boolean getExpiryDateVal() {
		return this.expiryDateVal;
	}

	public void setExpiryDateVal(Boolean expiryDateVal) {
		this.expiryDateVal = expiryDateVal;
	}

	@Column(name = "retailable")
	public Boolean getRetailable() {
		return this.retailable;
	}

	public void setRetailable(Boolean retailable) {
		this.retailable = retailable;
	}

	@Column(name = "discount", precision = 10)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "purchases_cat_vat_account_prefix", nullable = false, length = 50)
	public String getPurchasesCatVatAccountPrefix() {
		return this.purchasesCatVatAccountPrefix;
	}

	public void setPurchasesCatVatAccountPrefix(String purchasesCatVatAccountPrefix) {
		this.purchasesCatVatAccountPrefix = purchasesCatVatAccountPrefix;
	}

	@Column(name = "purchases_cat_cst_account_prefix", nullable = false, length = 50)
	public String getPurchasesCatCstAccountPrefix() {
		return this.purchasesCatCstAccountPrefix;
	}

	public void setPurchasesCatCstAccountPrefix(String purchasesCatCstAccountPrefix) {
		this.purchasesCatCstAccountPrefix = purchasesCatCstAccountPrefix;
	}

	@Column(name = "sales_cat_vat_account_prefix", length = 50)
	public String getSalesCatVatAccountPrefix() {
		return this.salesCatVatAccountPrefix;
	}

	public void setSalesCatVatAccountPrefix(String salesCatVatAccountPrefix) {
		this.salesCatVatAccountPrefix = salesCatVatAccountPrefix;
	}

	@Column(name = "asset_tracking", length = 1)
	public Character getAssetTracking() {
		return this.assetTracking;
	}

	public void setAssetTracking(Character assetTracking) {
		this.assetTracking = assetTracking;
	}

}
