package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.stores.StoresModel;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StoreTransferMainModel generated by hbm2java
 */
@Entity
@Table(name = "store_transfer_main", uniqueConstraints = @UniqueConstraint(columnNames = "appointment_id"))
public class StoreTransferMainModel implements java.io.Serializable {

	private int transferNo;
	private StoresModel storesByStoreFrom;
	private StoresModel storesByStoreTo;
	private Date dateTime;
	private String username;
	private String reason;
	private Integer appointmentId;
	private Character returnStatus;
	private Date receivedDate;
	private String receivedBy;
	private Integer indentNo;
	private Set storeTransferDetailses = new HashSet(0);

	public StoreTransferMainModel() {
	}

	public StoreTransferMainModel(int transferNo, Date dateTime) {
		this.transferNo = transferNo;
		this.dateTime = dateTime;
	}

	public StoreTransferMainModel(int transferNo, StoresModel storesByStoreFrom, StoresModel storesByStoreTo, Date dateTime,
			String username, String reason, Integer appointmentId, Character returnStatus, Date receivedDate,
			String receivedBy, Integer indentNo, Set storeTransferDetailses) {
		this.transferNo = transferNo;
		this.storesByStoreFrom = storesByStoreFrom;
		this.storesByStoreTo = storesByStoreTo;
		this.dateTime = dateTime;
		this.username = username;
		this.reason = reason;
		this.appointmentId = appointmentId;
		this.returnStatus = returnStatus;
		this.receivedDate = receivedDate;
		this.receivedBy = receivedBy;
		this.indentNo = indentNo;
		this.storeTransferDetailses = storeTransferDetailses;
	}

	@Id

	@Column(name = "transfer_no", unique = true, nullable = false)
	public int getTransferNo() {
		return this.transferNo;
	}

	public void setTransferNo(int transferNo) {
		this.transferNo = transferNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_from")
	public StoresModel getStoresByStoreFrom() {
		return this.storesByStoreFrom;
	}

	public void setStoresByStoreFrom(StoresModel storesByStoreFrom) {
		this.storesByStoreFrom = storesByStoreFrom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_to")
	public StoresModel getStoresByStoreTo() {
		return this.storesByStoreTo;
	}

	public void setStoresByStoreTo(StoresModel storesByStoreTo) {
		this.storesByStoreTo = storesByStoreTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, length = 29)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "reason", length = 1000)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "appointment_id", unique = true)
	public Integer getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Integer appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "return_status", length = 1)
	public Character getReturnStatus() {
		return this.returnStatus;
	}

	public void setReturnStatus(Character returnStatus) {
		this.returnStatus = returnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_date", length = 29)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	@Column(name = "received_by", length = 30)
	public String getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	@Column(name = "indent_no")
	public Integer getIndentNo() {
		return this.indentNo;
	}

	public void setIndentNo(Integer indentNo) {
		this.indentNo = indentNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storeTransferMain")
	public Set getStoreTransferDetailses() {
		return this.storeTransferDetailses;
	}

	public void setStoreTransferDetailses(Set storeTransferDetailses) {
		this.storeTransferDetailses = storeTransferDetailses;
	}

}
