package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StorePatientIndentDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "store_patient_indent_details")
public class StorePatientIndentDetailsModel implements java.io.Serializable {

	private int indentItemId;
	private String patientIndentNo;
	private int medicineId;
	private BigDecimal qtyRequired;
	private BigDecimal qtyReceived;
	private char qtyUnit;
	private char dispenseStatus;
	private Integer saleItemId;
	private Integer itemIssueNo;
	private Integer itemBatchId;

	public StorePatientIndentDetailsModel() {
	}

	public StorePatientIndentDetailsModel(int indentItemId, int medicineId, BigDecimal qtyRequired, BigDecimal qtyReceived,
			char qtyUnit, char dispenseStatus) {
		this.indentItemId = indentItemId;
		this.medicineId = medicineId;
		this.qtyRequired = qtyRequired;
		this.qtyReceived = qtyReceived;
		this.qtyUnit = qtyUnit;
		this.dispenseStatus = dispenseStatus;
	}

	public StorePatientIndentDetailsModel(int indentItemId, String patientIndentNo, int medicineId, BigDecimal qtyRequired,
			BigDecimal qtyReceived, char qtyUnit, char dispenseStatus, Integer saleItemId, Integer itemIssueNo,
			Integer itemBatchId) {
		this.indentItemId = indentItemId;
		this.patientIndentNo = patientIndentNo;
		this.medicineId = medicineId;
		this.qtyRequired = qtyRequired;
		this.qtyReceived = qtyReceived;
		this.qtyUnit = qtyUnit;
		this.dispenseStatus = dispenseStatus;
		this.saleItemId = saleItemId;
		this.itemIssueNo = itemIssueNo;
		this.itemBatchId = itemBatchId;
	}

	@Id

	@Column(name = "indent_item_id", unique = true, nullable = false)
	public int getIndentItemId() {
		return this.indentItemId;
	}

	public void setIndentItemId(int indentItemId) {
		this.indentItemId = indentItemId;
	}

	@Column(name = "patient_indent_no", length = 15)
	public String getPatientIndentNo() {
		return this.patientIndentNo;
	}

	public void setPatientIndentNo(String patientIndentNo) {
		this.patientIndentNo = patientIndentNo;
	}

	@Column(name = "medicine_id", nullable = false)
	public int getMedicineId() {
		return this.medicineId;
	}

	public void setMedicineId(int medicineId) {
		this.medicineId = medicineId;
	}

	@Column(name = "qty_required", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQtyRequired() {
		return this.qtyRequired;
	}

	public void setQtyRequired(BigDecimal qtyRequired) {
		this.qtyRequired = qtyRequired;
	}

	@Column(name = "qty_received", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQtyReceived() {
		return this.qtyReceived;
	}

	public void setQtyReceived(BigDecimal qtyReceived) {
		this.qtyReceived = qtyReceived;
	}

	@Column(name = "qty_unit", nullable = false, length = 1)
	public char getQtyUnit() {
		return this.qtyUnit;
	}

	public void setQtyUnit(char qtyUnit) {
		this.qtyUnit = qtyUnit;
	}

	@Column(name = "dispense_status", nullable = false, length = 1)
	public char getDispenseStatus() {
		return this.dispenseStatus;
	}

	public void setDispenseStatus(char dispenseStatus) {
		this.dispenseStatus = dispenseStatus;
	}

	@Column(name = "sale_item_id")
	public Integer getSaleItemId() {
		return this.saleItemId;
	}

	public void setSaleItemId(Integer saleItemId) {
		this.saleItemId = saleItemId;
	}

	@Column(name = "item_issue_no")
	public Integer getItemIssueNo() {
		return this.itemIssueNo;
	}

	public void setItemIssueNo(Integer itemIssueNo) {
		this.itemIssueNo = itemIssueNo;
	}

	@Column(name = "item_batch_id")
	public Integer getItemBatchId() {
		return this.itemBatchId;
	}

	public void setItemBatchId(Integer itemBatchId) {
		this.itemBatchId = itemBatchId;
	}

}
