package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.item.StoreItemDetailsModel;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StoreAdjDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "store_adj_details")
public class StoreAdjDetailsModel implements java.io.Serializable {

	private int adjDetailNo;
	private StoreAdjMainModel storeAdjMain;
	private StoreItemDetailsModel storeItemDetails;
	private String batchNo;
	private String type;
	private BigDecimal qty;
	private String description;
	private Integer itemBatchId;
	private BigDecimal costValue;
	private String externalAdjNo;

	public StoreAdjDetailsModel() {
	}

	public StoreAdjDetailsModel(int adjDetailNo, StoreAdjMainModel storeAdjMain, BigDecimal qty) {
		this.adjDetailNo = adjDetailNo;
		this.storeAdjMain = storeAdjMain;
		this.qty = qty;
	}

	public StoreAdjDetailsModel(int adjDetailNo, StoreAdjMainModel storeAdjMain, StoreItemDetailsModel storeItemDetails,
			String batchNo, String type, BigDecimal qty, String description, Integer itemBatchId, BigDecimal costValue,
			String externalAdjNo) {
		this.adjDetailNo = adjDetailNo;
		this.storeAdjMain = storeAdjMain;
		this.storeItemDetails = storeItemDetails;
		this.batchNo = batchNo;
		this.type = type;
		this.qty = qty;
		this.description = description;
		this.itemBatchId = itemBatchId;
		this.costValue = costValue;
		this.externalAdjNo = externalAdjNo;
	}

	@Id

	@Column(name = "adj_detail_no", unique = true, nullable = false)
	public int getAdjDetailNo() {
		return this.adjDetailNo;
	}

	public void setAdjDetailNo(int adjDetailNo) {
		this.adjDetailNo = adjDetailNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adj_no", nullable = false)
	public StoreAdjMainModel getStoreAdjMainModel() {
		return this.storeAdjMain;
	}

	public void setStoreAdjMainModel(StoreAdjMainModel storeAdjMain) {
		this.storeAdjMain = storeAdjMain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicine_id")
	public StoreItemDetailsModel getStoreItemDetailsModel() {
		return this.storeItemDetails;
	}

	public void setStoreItemDetailsModel(StoreItemDetailsModel storeItemDetails) {
		this.storeItemDetails = storeItemDetails;
	}

	@Column(name = "batch_no", length = 50)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "type", length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "qty", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "item_batch_id")
	public Integer getItemBatchId() {
		return this.itemBatchId;
	}

	public void setItemBatchId(Integer itemBatchId) {
		this.itemBatchId = itemBatchId;
	}

	@Column(name = "cost_value", precision = 131089, scale = 0)
	public BigDecimal getCostValue() {
		return this.costValue;
	}

	public void setCostValue(BigDecimal costValue) {
		this.costValue = costValue;
	}

	@Column(name = "external_adj_no", length = 30)
	public String getExternalAdjNo() {
		return this.externalAdjNo;
	}

	public void setExternalAdjNo(String externalAdjNo) {
		this.externalAdjNo = externalAdjNo;
	}

}
