package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoreIndentMainModel generated by hbm2java
 */
@Entity
@Table(name = "store_indent_main")
public class StoreIndentMainModel implements java.io.Serializable {

	private int indentNo;
	private Date dateTime;
	private String indentType;
	private String deptFrom;
	private String requesterName;
	private Date expectedDate;
	private String remarks;
	private String status;
	private String storeUser;
	private Date updatedDate;
	private String closureReasons;
	private String approverRemarks;
	private Integer indentStore;
	private String locationType;
	private Integer requestingCenterId;
	private Date approvedDate;
	private String approvedBy;
	private Date cancelledDate;
	private String cancelledBy;
	private Set storeTransferDetailses = new HashSet(0);
	private Set stockIssueDetailses = new HashSet(0);
	private Set storeIndentDetailses = new HashSet(0);

	public StoreIndentMainModel() {
	}

	public StoreIndentMainModel(int indentNo, Date dateTime, String indentType, String requesterName, String status,
			Date updatedDate) {
		this.indentNo = indentNo;
		this.dateTime = dateTime;
		this.indentType = indentType;
		this.requesterName = requesterName;
		this.status = status;
		this.updatedDate = updatedDate;
	}

	public StoreIndentMainModel(int indentNo, Date dateTime, String indentType, String deptFrom, String requesterName,
			Date expectedDate, String remarks, String status, String storeUser, Date updatedDate, String closureReasons,
			String approverRemarks, Integer indentStore, String locationType, Integer requestingCenterId,
			Date approvedDate, String approvedBy, Date cancelledDate, String cancelledBy, Set storeTransferDetailses,
			Set stockIssueDetailses, Set storeIndentDetailses) {
		this.indentNo = indentNo;
		this.dateTime = dateTime;
		this.indentType = indentType;
		this.deptFrom = deptFrom;
		this.requesterName = requesterName;
		this.expectedDate = expectedDate;
		this.remarks = remarks;
		this.status = status;
		this.storeUser = storeUser;
		this.updatedDate = updatedDate;
		this.closureReasons = closureReasons;
		this.approverRemarks = approverRemarks;
		this.indentStore = indentStore;
		this.locationType = locationType;
		this.requestingCenterId = requestingCenterId;
		this.approvedDate = approvedDate;
		this.approvedBy = approvedBy;
		this.cancelledDate = cancelledDate;
		this.cancelledBy = cancelledBy;
		this.storeTransferDetailses = storeTransferDetailses;
		this.stockIssueDetailses = stockIssueDetailses;
		this.storeIndentDetailses = storeIndentDetailses;
	}

	@Id

	@Column(name = "indent_no", unique = true, nullable = false)
	public int getIndentNo() {
		return this.indentNo;
	}

	public void setIndentNo(int indentNo) {
		this.indentNo = indentNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, length = 29)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "indent_type", nullable = false, length = 1)
	public String getIndentType() {
		return this.indentType;
	}

	public void setIndentType(String indentType) {
		this.indentType = indentType;
	}

	@Column(name = "dept_from")
	public String getDeptFrom() {
		return this.deptFrom;
	}

	public void setDeptFrom(String deptFrom) {
		this.deptFrom = deptFrom;
	}

	@Column(name = "requester_name", nullable = false, length = 30)
	public String getRequesterName() {
		return this.requesterName;
	}

	public void setRequesterName(String requesterName) {
		this.requesterName = requesterName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expected_date", length = 29)
	public Date getExpectedDate() {
		return this.expectedDate;
	}

	public void setExpectedDate(Date expectedDate) {
		this.expectedDate = expectedDate;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "store_user", length = 30)
	public String getStoreUser() {
		return this.storeUser;
	}

	public void setStoreUser(String storeUser) {
		this.storeUser = storeUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "closure_reasons")
	public String getClosureReasons() {
		return this.closureReasons;
	}

	public void setClosureReasons(String closureReasons) {
		this.closureReasons = closureReasons;
	}

	@Column(name = "approver_remarks")
	public String getApproverRemarks() {
		return this.approverRemarks;
	}

	public void setApproverRemarks(String approverRemarks) {
		this.approverRemarks = approverRemarks;
	}

	@Column(name = "indent_store")
	public Integer getIndentStore() {
		return this.indentStore;
	}

	public void setIndentStore(Integer indentStore) {
		this.indentStore = indentStore;
	}

	@Column(name = "location_type", length = 1)
	public String getLocationType() {
		return this.locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	@Column(name = "requesting_center_id")
	public Integer getRequestingCenterId() {
		return this.requestingCenterId;
	}

	public void setRequestingCenterId(Integer requestingCenterId) {
		this.requestingCenterId = requestingCenterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approved_date", length = 29)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@Column(name = "approved_by", length = 30)
	public String getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelled_date", length = 29)
	public Date getCancelledDate() {
		return this.cancelledDate;
	}

	public void setCancelledDate(Date cancelledDate) {
		this.cancelledDate = cancelledDate;
	}

	@Column(name = "cancelled_by", length = 30)
	public String getCancelledBy() {
		return this.cancelledBy;
	}

	public void setCancelledBy(String cancelledBy) {
		this.cancelledBy = cancelledBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storeIndentMain")
	public Set getStoreTransferDetailses() {
		return this.storeTransferDetailses;
	}

	public void setStoreTransferDetailses(Set storeTransferDetailses) {
		this.storeTransferDetailses = storeTransferDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storeIndentMain")
	public Set getStockIssueDetailses() {
		return this.stockIssueDetailses;
	}

	public void setStockIssueDetailses(Set stockIssueDetailses) {
		this.stockIssueDetailses = stockIssueDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storeIndentMain")
	public Set getStoreIndentDetailses() {
		return this.storeIndentDetailses;
	}

	public void setStoreIndentDetailses(Set storeIndentDetailses) {
		this.storeIndentDetailses = storeIndentDetailses;
	}

}
