package com.insta.hms.model;

// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.core.inventory.sales.SalesClaimDetailsModel;
import com.insta.hms.mdm.item.StoreItemDetailsModel;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoreSalesDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "store_sales_details")
public class StoreSalesDetailsModel implements java.io.Serializable {

  private int saleItemId;
  private StoreSalesMainModel saleId;
  private String batchNo;
  private BigDecimal quantity;
  private BigDecimal tax;
  private BigDecimal taxRate;
  private BigDecimal rate;
  private BigDecimal amount;
  private BigDecimal origRate;
  private BigDecimal packageUnit;
  private Date expiryDate;
  private BigDecimal disc;
  private char basis;
  private BigDecimal discountPer;
  private Integer medicineId;
  private BigDecimal pkgMrp;
  private BigDecimal pkgCp;
  private String codeType;
  private String itemCode;
  private Character discountType;
  private Character claimStatus;
  private BigDecimal insuranceClaimAmt;
  private BigDecimal claimRecdTotal;
  private String denialCode;
  private Integer insuranceCategoryId;
  private Character saleUnit;
  private BigDecimal returnInsuranceClaimAmt;
  private BigDecimal returnAmt;
  private BigDecimal returnQty;
  private String priorAuthId;
  private Integer priorAuthModeId;
  private String denialRemarks;
  private BigDecimal amountIncluded;
  private BigDecimal qtyIncluded;
  private char packageFinalized;
  private Integer itemBatchId;
  private BigDecimal costValue;
  private String frequency;
  private String dosage;
  private String dosageUnit;
  private Integer routeOfAdmin;
  private String doctorRemarks;
  private String salesRemarks;
  private Integer labelId;
  private Character durationUnits;
  private Integer duration;
  private String specialInstr;
  private boolean isClaimLocked;
  private boolean includeInClaimCalc;
  private Set<SalesClaimDetailsModel> salesClaimDetails;
  private Set<StoreSalesTaxDetailsModel> storeSalesTaxDetails;
  private StoreItemDetailsModel storeItemDetails;

  public StoreSalesDetailsModel() {
  }

  public StoreSalesDetailsModel(int saleItemId, StoreSalesMainModel saleId, BigDecimal quantity,
      BigDecimal tax, char basis, BigDecimal pkgMrp, BigDecimal pkgCp,
      BigDecimal insuranceClaimAmt, BigDecimal amountIncluded, BigDecimal qtyIncluded,
      char packageFinalized, boolean isClaimLocked, boolean includeInClaimCalc) {
    this.saleItemId = saleItemId;
    this.saleId = saleId;
    this.quantity = quantity;
    this.tax = tax;
    this.basis = basis;
    this.pkgMrp = pkgMrp;
    this.pkgCp = pkgCp;
    this.insuranceClaimAmt = insuranceClaimAmt;
    this.amountIncluded = amountIncluded;
    this.qtyIncluded = qtyIncluded;
    this.packageFinalized = packageFinalized;
    this.isClaimLocked = isClaimLocked;
    this.includeInClaimCalc = includeInClaimCalc;
  }

  public StoreSalesDetailsModel(int saleItemId, StoreSalesMainModel saleId, String batchNo,
      BigDecimal quantity, BigDecimal tax, BigDecimal taxRate, BigDecimal rate, BigDecimal amount,
      BigDecimal origRate, BigDecimal packageUnit, Date expiryDate, BigDecimal disc, char basis,
      BigDecimal discountPer, Integer medicineId, BigDecimal pkgMrp, BigDecimal pkgCp,
      String codeType, String itemCode, Character discountType, Character claimStatus,
      BigDecimal insuranceClaimAmt, BigDecimal claimRecdTotal, String denialCode,
      Integer insuranceCategoryId, Character saleUnit, BigDecimal returnInsuranceClaimAmt,
      BigDecimal returnAmt, BigDecimal returnQty, String priorAuthId, Integer priorAuthModeId,
      String denialRemarks, BigDecimal amountIncluded, BigDecimal qtyIncluded,
      char packageFinalized, Integer itemBatchId, BigDecimal costValue, String frequency,
      String dosage, String dosageUnit, Integer routeOfAdmin, String doctorRemarks,
      String salesRemarks, Integer labelId, Character durationUnits, Integer duration,
      String specialInstr, boolean isClaimLocked, boolean includeInClaimCalc) {
    this.saleItemId = saleItemId;
    this.saleId = saleId;
    this.batchNo = batchNo;
    this.quantity = quantity;
    this.tax = tax;
    this.taxRate = taxRate;
    this.rate = rate;
    this.amount = amount;
    this.origRate = origRate;
    this.packageUnit = packageUnit;
    this.expiryDate = expiryDate;
    this.disc = disc;
    this.basis = basis;
    this.discountPer = discountPer;
    this.medicineId = medicineId;
    this.pkgMrp = pkgMrp;
    this.pkgCp = pkgCp;
    this.codeType = codeType;
    this.itemCode = itemCode;
    this.discountType = discountType;
    this.claimStatus = claimStatus;
    this.insuranceClaimAmt = insuranceClaimAmt;
    this.claimRecdTotal = claimRecdTotal;
    this.denialCode = denialCode;
    this.insuranceCategoryId = insuranceCategoryId;
    this.saleUnit = saleUnit;
    this.returnInsuranceClaimAmt = returnInsuranceClaimAmt;
    this.returnAmt = returnAmt;
    this.returnQty = returnQty;
    this.priorAuthId = priorAuthId;
    this.priorAuthModeId = priorAuthModeId;
    this.denialRemarks = denialRemarks;
    this.amountIncluded = amountIncluded;
    this.qtyIncluded = qtyIncluded;
    this.packageFinalized = packageFinalized;
    this.itemBatchId = itemBatchId;
    this.costValue = costValue;
    this.frequency = frequency;
    this.dosage = dosage;
    this.dosageUnit = dosageUnit;
    this.routeOfAdmin = routeOfAdmin;
    this.doctorRemarks = doctorRemarks;
    this.salesRemarks = salesRemarks;
    this.labelId = labelId;
    this.durationUnits = durationUnits;
    this.duration = duration;
    this.specialInstr = specialInstr;
    this.isClaimLocked = isClaimLocked;
    this.includeInClaimCalc = includeInClaimCalc;
  }

  @Id
  @Column(name = "sale_item_id", unique = true, nullable = false)
  public int getSaleItemId() {
    return this.saleItemId;
  }

  public void setSaleItemId(int saleItemId) {
    this.saleItemId = saleItemId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "sale_id")
  public StoreSalesMainModel getSaleId() {
    return this.saleId;
  }

  public void setSaleId(StoreSalesMainModel saleId) {
    this.saleId = saleId;
  }

  @Column(name = "batch_no", length = 50)
  public String getBatchNo() {
    return this.batchNo;
  }

  public void setBatchNo(String batchNo) {
    this.batchNo = batchNo;
  }

  @Column(name = "quantity", nullable = false, precision = 131089, scale = 0)
  public BigDecimal getQuantity() {
    return this.quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  @Column(name = "tax", nullable = false, precision = 15)
  public BigDecimal getTax() {
    return this.tax;
  }

  public void setTax(BigDecimal tax) {
    this.tax = tax;
  }

  @Column(name = "tax_rate", precision = 15)
  public BigDecimal getTaxRate() {
    return this.taxRate;
  }

  public void setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
  }

  @Column(name = "rate", precision = 15)
  public BigDecimal getRate() {
    return this.rate;
  }

  public void setRate(BigDecimal rate) {
    this.rate = rate;
  }

  @Column(name = "amount", precision = 15)
  public BigDecimal getAmount() {
    return this.amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  @Column(name = "orig_rate", precision = 15)
  public BigDecimal getOrigRate() {
    return this.origRate;
  }

  public void setOrigRate(BigDecimal origRate) {
    this.origRate = origRate;
  }

  @Column(name = "package_unit", precision = 131089, scale = 0)
  public BigDecimal getPackageUnit() {
    return this.packageUnit;
  }

  public void setPackageUnit(BigDecimal packageUnit) {
    this.packageUnit = packageUnit;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "expiry_date", length = 13)
  public Date getExpiryDate() {
    return this.expiryDate;
  }

  public void setExpiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
  }

  @Column(name = "disc", precision = 15)
  public BigDecimal getDisc() {
    return this.disc;
  }

  public void setDisc(BigDecimal disc) {
    this.disc = disc;
  }

  @Column(name = "basis", nullable = false, length = 1)
  public char getBasis() {
    return this.basis;
  }

  public void setBasis(char basis) {
    this.basis = basis;
  }

  @Column(name = "discount_per", precision = 10)
  public BigDecimal getDiscountPer() {
    return this.discountPer;
  }

  public void setDiscountPer(BigDecimal discountPer) {
    this.discountPer = discountPer;
  }

  @Column(name = "medicine_id")
  public Integer getMedicineId() {
    return this.medicineId;
  }

  public void setMedicineId(Integer medicineId) {
    this.medicineId = medicineId;
  }

  @Column(name = "pkg_mrp", nullable = false, precision = 15)
  public BigDecimal getPkgMrp() {
    return this.pkgMrp;
  }

  public void setPkgMrp(BigDecimal pkgMrp) {
    this.pkgMrp = pkgMrp;
  }

  @Column(name = "pkg_cp", nullable = false, precision = 15)
  public BigDecimal getPkgCp() {
    return this.pkgCp;
  }

  public void setPkgCp(BigDecimal pkgCp) {
    this.pkgCp = pkgCp;
  }

  @Column(name = "code_type", length = 50)
  public String getCodeType() {
    return this.codeType;
  }

  public void setCodeType(String codeType) {
    this.codeType = codeType;
  }

  @Column(name = "item_code")
  public String getItemCode() {
    return this.itemCode;
  }

  public void setItemCode(String itemCode) {
    this.itemCode = itemCode;
  }

  @Column(name = "discount_type", length = 1)
  public Character getDiscountType() {
    return this.discountType;
  }

  public void setDiscountType(Character discountType) {
    this.discountType = discountType;
  }

  @Column(name = "claim_status", length = 1)
  public Character getClaimStatus() {
    return this.claimStatus;
  }

  public void setClaimStatus(Character claimStatus) {
    this.claimStatus = claimStatus;
  }

  @Column(name = "insurance_claim_amt", nullable = false, precision = 15)
  public BigDecimal getInsuranceClaimAmt() {
    return this.insuranceClaimAmt;
  }

  public void setInsuranceClaimAmt(BigDecimal insuranceClaimAmt) {
    this.insuranceClaimAmt = insuranceClaimAmt;
  }

  @Column(name = "claim_recd_total", precision = 15)
  public BigDecimal getClaimRecdTotal() {
    return this.claimRecdTotal;
  }

  public void setClaimRecdTotal(BigDecimal claimRecdTotal) {
    this.claimRecdTotal = claimRecdTotal;
  }

  @Column(name = "denial_code", length = 10)
  public String getDenialCode() {
    return this.denialCode;
  }

  public void setDenialCode(String denialCode) {
    this.denialCode = denialCode;
  }

  @Column(name = "insurance_category_id")
  public Integer getInsuranceCategoryId() {
    return this.insuranceCategoryId;
  }

  public void setInsuranceCategoryId(Integer insuranceCategoryId) {
    this.insuranceCategoryId = insuranceCategoryId;
  }

  @Column(name = "sale_unit", length = 1)
  public Character getSaleUnit() {
    return this.saleUnit;
  }

  public void setSaleUnit(Character saleUnit) {
    this.saleUnit = saleUnit;
  }

  @Column(name = "return_insurance_claim_amt", precision = 15)
  public BigDecimal getReturnInsuranceClaimAmt() {
    return this.returnInsuranceClaimAmt;
  }

  public void setReturnInsuranceClaimAmt(BigDecimal returnInsuranceClaimAmt) {
    this.returnInsuranceClaimAmt = returnInsuranceClaimAmt;
  }

  @Column(name = "return_amt", precision = 15)
  public BigDecimal getReturnAmt() {
    return this.returnAmt;
  }

  public void setReturnAmt(BigDecimal returnAmt) {
    this.returnAmt = returnAmt;
  }

  @Column(name = "return_qty", precision = 131089, scale = 0)
  public BigDecimal getReturnQty() {
    return this.returnQty;
  }

  public void setReturnQty(BigDecimal returnQty) {
    this.returnQty = returnQty;
  }

  @Column(name = "prior_auth_id", length = 50)
  public String getPriorAuthId() {
    return this.priorAuthId;
  }

  public void setPriorAuthId(String priorAuthId) {
    this.priorAuthId = priorAuthId;
  }

  @Column(name = "prior_auth_mode_id")
  public Integer getPriorAuthModeId() {
    return this.priorAuthModeId;
  }

  public void setPriorAuthModeId(Integer priorAuthModeId) {
    this.priorAuthModeId = priorAuthModeId;
  }

  @Column(name = "denial_remarks")
  public String getDenialRemarks() {
    return this.denialRemarks;
  }

  public void setDenialRemarks(String denialRemarks) {
    this.denialRemarks = denialRemarks;
  }

  @Column(name = "amount_included", nullable = false, precision = 15)
  public BigDecimal getAmountIncluded() {
    return this.amountIncluded;
  }

  public void setAmountIncluded(BigDecimal amountIncluded) {
    this.amountIncluded = amountIncluded;
  }

  @Column(name = "qty_included", nullable = false, precision = 131089, scale = 0)
  public BigDecimal getQtyIncluded() {
    return this.qtyIncluded;
  }

  public void setQtyIncluded(BigDecimal qtyIncluded) {
    this.qtyIncluded = qtyIncluded;
  }

  @Column(name = "package_finalized", nullable = false, length = 1)
  public char getPackageFinalized() {
    return this.packageFinalized;
  }

  public void setPackageFinalized(char packageFinalized) {
    this.packageFinalized = packageFinalized;
  }

  @Column(name = "item_batch_id")
  public Integer getItemBatchId() {
    return this.itemBatchId;
  }

  public void setItemBatchId(Integer itemBatchId) {
    this.itemBatchId = itemBatchId;
  }

  @Column(name = "cost_value", precision = 131089, scale = 0)
  public BigDecimal getCostValue() {
    return this.costValue;
  }

  public void setCostValue(BigDecimal costValue) {
    this.costValue = costValue;
  }

  @Column(name = "frequency", length = 50)
  public String getFrequency() {
    return this.frequency;
  }

  public void setFrequency(String frequency) {
    this.frequency = frequency;
  }

  @Column(name = "dosage", length = 50)
  public String getDosage() {
    return this.dosage;
  }

  public void setDosage(String dosage) {
    this.dosage = dosage;
  }

  @Column(name = "dosage_unit", length = 50)
  public String getDosageUnit() {
    return this.dosageUnit;
  }

  public void setDosageUnit(String dosageUnit) {
    this.dosageUnit = dosageUnit;
  }

  @Column(name = "route_of_admin")
  public Integer getRouteOfAdmin() {
    return this.routeOfAdmin;
  }

  public void setRouteOfAdmin(Integer routeOfAdmin) {
    this.routeOfAdmin = routeOfAdmin;
  }

  @Column(name = "doctor_remarks", length = 2000)
  public String getDoctorRemarks() {
    return this.doctorRemarks;
  }

  public void setDoctorRemarks(String doctorRemarks) {
    this.doctorRemarks = doctorRemarks;
  }

  @Column(name = "sales_remarks", length = 2000)
  public String getSalesRemarks() {
    return this.salesRemarks;
  }

  public void setSalesRemarks(String salesRemarks) {
    this.salesRemarks = salesRemarks;
  }

  @Column(name = "label_id")
  public Integer getLabelId() {
    return this.labelId;
  }

  public void setLabelId(Integer labelId) {
    this.labelId = labelId;
  }

  @Column(name = "duration_units", length = 1)
  public Character getDurationUnits() {
    return this.durationUnits;
  }

  public void setDurationUnits(Character durationUnits) {
    this.durationUnits = durationUnits;
  }

  @Column(name = "duration")
  public Integer getDuration() {
    return this.duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  @Column(name = "special_instr", length = 2000)
  public String getSpecialInstr() {
    return this.specialInstr;
  }

  public void setSpecialInstr(String specialInstr) {
    this.specialInstr = specialInstr;
  }

  @Column(name = "is_claim_locked", nullable = false)
  public boolean isIsClaimLocked() {
    return this.isClaimLocked;
  }

  public void setIsClaimLocked(boolean isClaimLocked) {
    this.isClaimLocked = isClaimLocked;
  }

  @Column(name = "include_in_claim_calc", nullable = false)
  public boolean isIncludeInClaimCalc() {
    return this.includeInClaimCalc;
  }

  public void setIncludeInClaimCalc(boolean includeInClaimCalc) {
    this.includeInClaimCalc = includeInClaimCalc;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "saleItemId")
  public Set<SalesClaimDetailsModel> getSalesClaimDetails() {
    return salesClaimDetails;
  }

  public void setSalesClaimDetails(Set<SalesClaimDetailsModel> salesClaimDetails) {
    this.salesClaimDetails = salesClaimDetails;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "saleItemId")
  public Set<StoreSalesTaxDetailsModel> getStoreSalesTaxDetails() {
    return storeSalesTaxDetails;
  }

  public void setStoreSalesTaxDetails(Set<StoreSalesTaxDetailsModel> storeSalesTaxDetails) {
    this.storeSalesTaxDetails = storeSalesTaxDetails;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "medicine_id", nullable = false, insertable = false, updatable = false)
  public StoreItemDetailsModel getStoreItemDetails() {
    return storeItemDetails;
  }

  public void setStoreItemDetails(StoreItemDetailsModel storeItemDetails) {
    this.storeItemDetails = storeItemDetails;
  }

}
