package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.item.StoreItemDetailsModel;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StorePoModel generated by hbm2java
 */
@Entity
@Table(name = "store_po")
public class StorePoModel implements java.io.Serializable {

	private StorePoIdSequence id;
	private StoreItemDetailsModel storeItemDetails;
	private StorePoMainModel storePoMain;
	private BigDecimal qtyReq;
	private BigDecimal mrp;
	private BigDecimal adjMrp;
	private BigDecimal costPrice;
	private BigDecimal vat;
	private BigDecimal discount;
	private BigDecimal medTotal;
	private BigDecimal vatRate;
	private BigDecimal qtyReceived;
	private String vatType;
	private String status;
	private BigDecimal bonusQtyReq;
	private BigDecimal bonusQtyReceived;
	private BigDecimal discountPer;
	private String itemRemarks;
	private BigDecimal poPkgSize;
	private BigDecimal itemCedPer;
	private BigDecimal itemCed;
	private int itemOrder;

	public StorePoModel() {
	}

	public StorePoModel(StorePoIdSequence id, StoreItemDetailsModel storeItemDetails, StorePoMainModel storePoMain, BigDecimal qtyReceived,
			String vatType, String status, BigDecimal poPkgSize, BigDecimal itemCedPer, BigDecimal itemCed,
			int itemOrder) {
		this.id = id;
		this.storeItemDetails = storeItemDetails;
		this.storePoMain = storePoMain;
		this.qtyReceived = qtyReceived;
		this.vatType = vatType;
		this.status = status;
		this.poPkgSize = poPkgSize;
		this.itemCedPer = itemCedPer;
		this.itemCed = itemCed;
		this.itemOrder = itemOrder;
	}

	public StorePoModel(StorePoIdSequence id, StoreItemDetailsModel storeItemDetails, StorePoMainModel storePoMain, BigDecimal qtyReq,
			BigDecimal mrp, BigDecimal adjMrp, BigDecimal costPrice, BigDecimal vat, BigDecimal discount,
			BigDecimal medTotal, BigDecimal vatRate, BigDecimal qtyReceived, String vatType, String status,
			BigDecimal bonusQtyReq, BigDecimal bonusQtyReceived, BigDecimal discountPer, String itemRemarks,
			BigDecimal poPkgSize, BigDecimal itemCedPer, BigDecimal itemCed, int itemOrder) {
		this.id = id;
		this.storeItemDetails = storeItemDetails;
		this.storePoMain = storePoMain;
		this.qtyReq = qtyReq;
		this.mrp = mrp;
		this.adjMrp = adjMrp;
		this.costPrice = costPrice;
		this.vat = vat;
		this.discount = discount;
		this.medTotal = medTotal;
		this.vatRate = vatRate;
		this.qtyReceived = qtyReceived;
		this.vatType = vatType;
		this.status = status;
		this.bonusQtyReq = bonusQtyReq;
		this.bonusQtyReceived = bonusQtyReceived;
		this.discountPer = discountPer;
		this.itemRemarks = itemRemarks;
		this.poPkgSize = poPkgSize;
		this.itemCedPer = itemCedPer;
		this.itemCed = itemCed;
		this.itemOrder = itemOrder;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "poNo", column = @Column(name = "po_no", nullable = false, length = 20)),
			@AttributeOverride(name = "medicineId", column = @Column(name = "medicine_id", nullable = false)) })
	public StorePoIdSequence getId() {
		return this.id;
	}

	public void setId(StorePoIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicine_id", nullable = false, insertable = false, updatable = false)
	public StoreItemDetailsModel getStoreItemDetailsModel() {
		return this.storeItemDetails;
	}

	public void setStoreItemDetailsModel(StoreItemDetailsModel storeItemDetails) {
		this.storeItemDetails = storeItemDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_no", nullable = false, insertable = false, updatable = false)
	public StorePoMainModel getStorePoMainModel() {
		return this.storePoMain;
	}

	public void setStorePoMainModel(StorePoMainModel storePoMain) {
		this.storePoMain = storePoMain;
	}

	@Column(name = "qty_req", precision = 131089, scale = 0)
	public BigDecimal getQtyReq() {
		return this.qtyReq;
	}

	public void setQtyReq(BigDecimal qtyReq) {
		this.qtyReq = qtyReq;
	}

	@Column(name = "mrp", precision = 15)
	public BigDecimal getMrp() {
		return this.mrp;
	}

	public void setMrp(BigDecimal mrp) {
		this.mrp = mrp;
	}

	@Column(name = "adj_mrp", precision = 15)
	public BigDecimal getAdjMrp() {
		return this.adjMrp;
	}

	public void setAdjMrp(BigDecimal adjMrp) {
		this.adjMrp = adjMrp;
	}

	@Column(name = "cost_price", precision = 15)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "vat", precision = 15)
	public BigDecimal getVat() {
		return this.vat;
	}

	public void setVat(BigDecimal vat) {
		this.vat = vat;
	}

	@Column(name = "discount", precision = 15)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "med_total", precision = 15)
	public BigDecimal getMedTotal() {
		return this.medTotal;
	}

	public void setMedTotal(BigDecimal medTotal) {
		this.medTotal = medTotal;
	}

	@Column(name = "vat_rate", precision = 15)
	public BigDecimal getVatRate() {
		return this.vatRate;
	}

	public void setVatRate(BigDecimal vatRate) {
		this.vatRate = vatRate;
	}

	@Column(name = "qty_received", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQtyReceived() {
		return this.qtyReceived;
	}

	public void setQtyReceived(BigDecimal qtyReceived) {
		this.qtyReceived = qtyReceived;
	}

	@Column(name = "vat_type", nullable = false, length = 2)
	public String getVatType() {
		return this.vatType;
	}

	public void setVatType(String vatType) {
		this.vatType = vatType;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "bonus_qty_req", precision = 131089, scale = 0)
	public BigDecimal getBonusQtyReq() {
		return this.bonusQtyReq;
	}

	public void setBonusQtyReq(BigDecimal bonusQtyReq) {
		this.bonusQtyReq = bonusQtyReq;
	}

	@Column(name = "bonus_qty_received", precision = 131089, scale = 0)
	public BigDecimal getBonusQtyReceived() {
		return this.bonusQtyReceived;
	}

	public void setBonusQtyReceived(BigDecimal bonusQtyReceived) {
		this.bonusQtyReceived = bonusQtyReceived;
	}

	@Column(name = "discount_per", precision = 10)
	public BigDecimal getDiscountPer() {
		return this.discountPer;
	}

	public void setDiscountPer(BigDecimal discountPer) {
		this.discountPer = discountPer;
	}

	@Column(name = "item_remarks")
	public String getItemRemarks() {
		return this.itemRemarks;
	}

	public void setItemRemarks(String itemRemarks) {
		this.itemRemarks = itemRemarks;
	}

	@Column(name = "po_pkg_size", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPoPkgSize() {
		return this.poPkgSize;
	}

	public void setPoPkgSize(BigDecimal poPkgSize) {
		this.poPkgSize = poPkgSize;
	}

	@Column(name = "item_ced_per", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getItemCedPer() {
		return this.itemCedPer;
	}

	public void setItemCedPer(BigDecimal itemCedPer) {
		this.itemCedPer = itemCedPer;
	}

	@Column(name = "item_ced", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getItemCed() {
		return this.itemCed;
	}

	public void setItemCed(BigDecimal itemCed) {
		this.itemCed = itemCed;
	}

	@Column(name = "item_order", nullable = false)
	public int getItemOrder() {
		return this.itemOrder;
	}

	public void setItemOrder(int itemOrder) {
		this.itemOrder = itemOrder;
	}

}
