package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StoreMiscellaneousSettingsIdSequence generated by hbm2java
 */
@Embeddable
public class StoreMiscellaneousSettingsIdSequence implements java.io.Serializable {

	private String pharmacyTinNo;
	private String pharmacyDrugLicenseNo;
	private String hospitalTermsConditions;
	private String creditPeriod;
	private String indentProcessNo;
	private String delivery;

	public StoreMiscellaneousSettingsIdSequence() {
	}

	public StoreMiscellaneousSettingsIdSequence(String pharmacyTinNo, String pharmacyDrugLicenseNo,
			String hospitalTermsConditions, String creditPeriod, String indentProcessNo, String delivery) {
		this.pharmacyTinNo = pharmacyTinNo;
		this.pharmacyDrugLicenseNo = pharmacyDrugLicenseNo;
		this.hospitalTermsConditions = hospitalTermsConditions;
		this.creditPeriod = creditPeriod;
		this.indentProcessNo = indentProcessNo;
		this.delivery = delivery;
	}

	@Column(name = "pharmacy_tin_no", length = 35)
	public String getPharmacyTinNo() {
		return this.pharmacyTinNo;
	}

	public void setPharmacyTinNo(String pharmacyTinNo) {
		this.pharmacyTinNo = pharmacyTinNo;
	}

	@Column(name = "pharmacy_drug_license_no", length = 35)
	public String getPharmacyDrugLicenseNo() {
		return this.pharmacyDrugLicenseNo;
	}

	public void setPharmacyDrugLicenseNo(String pharmacyDrugLicenseNo) {
		this.pharmacyDrugLicenseNo = pharmacyDrugLicenseNo;
	}

	@Column(name = "hospital_terms_conditions", length = 4000)
	public String getHospitalTermsConditions() {
		return this.hospitalTermsConditions;
	}

	public void setHospitalTermsConditions(String hospitalTermsConditions) {
		this.hospitalTermsConditions = hospitalTermsConditions;
	}

	@Column(name = "credit_period", length = 10)
	public String getCreditPeriod() {
		return this.creditPeriod;
	}

	public void setCreditPeriod(String creditPeriod) {
		this.creditPeriod = creditPeriod;
	}

	@Column(name = "indent_process_no", length = 10)
	public String getIndentProcessNo() {
		return this.indentProcessNo;
	}

	public void setIndentProcessNo(String indentProcessNo) {
		this.indentProcessNo = indentProcessNo;
	}

	@Column(name = "delivery", length = 10)
	public String getDelivery() {
		return this.delivery;
	}

	public void setDelivery(String delivery) {
		this.delivery = delivery;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StoreMiscellaneousSettingsIdSequence))
			return false;
		StoreMiscellaneousSettingsIdSequence castOther = (StoreMiscellaneousSettingsIdSequence) other;

		return ((this.getPharmacyTinNo() == castOther.getPharmacyTinNo())
				|| (this.getPharmacyTinNo() != null && castOther.getPharmacyTinNo() != null
						&& this.getPharmacyTinNo().equals(castOther.getPharmacyTinNo())))
				&& ((this.getPharmacyDrugLicenseNo() == castOther.getPharmacyDrugLicenseNo())
						|| (this.getPharmacyDrugLicenseNo() != null && castOther.getPharmacyDrugLicenseNo() != null
								&& this.getPharmacyDrugLicenseNo().equals(castOther.getPharmacyDrugLicenseNo())))
				&& ((this.getHospitalTermsConditions() == castOther.getHospitalTermsConditions())
						|| (this.getHospitalTermsConditions() != null && castOther.getHospitalTermsConditions() != null
								&& this.getHospitalTermsConditions().equals(castOther.getHospitalTermsConditions())))
				&& ((this.getCreditPeriod() == castOther.getCreditPeriod())
						|| (this.getCreditPeriod() != null && castOther.getCreditPeriod() != null
								&& this.getCreditPeriod().equals(castOther.getCreditPeriod())))
				&& ((this.getIndentProcessNo() == castOther.getIndentProcessNo())
						|| (this.getIndentProcessNo() != null && castOther.getIndentProcessNo() != null
								&& this.getIndentProcessNo().equals(castOther.getIndentProcessNo())))
				&& ((this.getDelivery() == castOther.getDelivery()) || (this.getDelivery() != null
						&& castOther.getDelivery() != null && this.getDelivery().equals(castOther.getDelivery())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPharmacyTinNo() == null ? 0 : this.getPharmacyTinNo().hashCode());
		result = 37 * result + (getPharmacyDrugLicenseNo() == null ? 0 : this.getPharmacyDrugLicenseNo().hashCode());
		result = 37 * result
				+ (getHospitalTermsConditions() == null ? 0 : this.getHospitalTermsConditions().hashCode());
		result = 37 * result + (getCreditPeriod() == null ? 0 : this.getCreditPeriod().hashCode());
		result = 37 * result + (getIndentProcessNo() == null ? 0 : this.getIndentProcessNo().hashCode());
		result = 37 * result + (getDelivery() == null ? 0 : this.getDelivery().hashCode());
		return result;
	}

}
