package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StoreGrnDetailsIdSequence generated by hbm2java
 */
@Embeddable
public class StoreGrnDetailsIdSequence implements java.io.Serializable {

	private String grnNo;
	private String batchNo;
	private Date expDt;
	private BigDecimal mrp;
	private BigDecimal billedQty;
	private BigDecimal bonusQty;
	private BigDecimal costPrice;
	private BigDecimal discount;
	private BigDecimal taxRate;
	private BigDecimal tax;
	private BigDecimal adjMrp;
	private String taxType;
	private BigDecimal outgoingTaxRate;
	private Integer medicineId;
	private BigDecimal issueQty;
	private BigDecimal totalQty;
	private BigDecimal grnPkgSize;
	private BigDecimal origDebitRate;
	private BigDecimal origDiscount;
	private BigDecimal origTax;
	private BigDecimal itemCedPer;
	private BigDecimal itemCed;
	private BigDecimal origCed;
	private int itemOrder;
	private String grnPackageUom;
	private Integer itemBatchId;
	private BigDecimal bonusTax;
	private BigDecimal schemeDiscount;
	private BigDecimal origSchemeDiscount;

	public StoreGrnDetailsIdSequence() {
	}

	public StoreGrnDetailsIdSequence(String grnNo, String batchNo, BigDecimal grnPkgSize, BigDecimal itemCedPer,
			BigDecimal itemCed, BigDecimal origCed, int itemOrder, BigDecimal bonusTax) {
		this.grnNo = grnNo;
		this.batchNo = batchNo;
		this.grnPkgSize = grnPkgSize;
		this.itemCedPer = itemCedPer;
		this.itemCed = itemCed;
		this.origCed = origCed;
		this.itemOrder = itemOrder;
		this.bonusTax = bonusTax;
	}

	public StoreGrnDetailsIdSequence(String grnNo, String batchNo, Date expDt, BigDecimal mrp, BigDecimal billedQty,
			BigDecimal bonusQty, BigDecimal costPrice, BigDecimal discount, BigDecimal taxRate, BigDecimal tax,
			BigDecimal adjMrp, String taxType, BigDecimal outgoingTaxRate, Integer medicineId, BigDecimal issueQty,
			BigDecimal totalQty, BigDecimal grnPkgSize, BigDecimal origDebitRate, BigDecimal origDiscount,
			BigDecimal origTax, BigDecimal itemCedPer, BigDecimal itemCed, BigDecimal origCed, int itemOrder,
			String grnPackageUom, Integer itemBatchId, BigDecimal bonusTax, BigDecimal schemeDiscount,
			BigDecimal origSchemeDiscount) {
		this.grnNo = grnNo;
		this.batchNo = batchNo;
		this.expDt = expDt;
		this.mrp = mrp;
		this.billedQty = billedQty;
		this.bonusQty = bonusQty;
		this.costPrice = costPrice;
		this.discount = discount;
		this.taxRate = taxRate;
		this.tax = tax;
		this.adjMrp = adjMrp;
		this.taxType = taxType;
		this.outgoingTaxRate = outgoingTaxRate;
		this.medicineId = medicineId;
		this.issueQty = issueQty;
		this.totalQty = totalQty;
		this.grnPkgSize = grnPkgSize;
		this.origDebitRate = origDebitRate;
		this.origDiscount = origDiscount;
		this.origTax = origTax;
		this.itemCedPer = itemCedPer;
		this.itemCed = itemCed;
		this.origCed = origCed;
		this.itemOrder = itemOrder;
		this.grnPackageUom = grnPackageUom;
		this.itemBatchId = itemBatchId;
		this.bonusTax = bonusTax;
		this.schemeDiscount = schemeDiscount;
		this.origSchemeDiscount = origSchemeDiscount;
	}

	@Column(name = "grn_no", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	@Column(name = "batch_no", nullable = false, length = 50)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "exp_dt", length = 13)
	public Date getExpDt() {
		return this.expDt;
	}

	public void setExpDt(Date expDt) {
		this.expDt = expDt;
	}

	@Column(name = "mrp", precision = 15)
	public BigDecimal getMrp() {
		return this.mrp;
	}

	public void setMrp(BigDecimal mrp) {
		this.mrp = mrp;
	}

	@Column(name = "billed_qty", precision = 131089, scale = 0)
	public BigDecimal getBilledQty() {
		return this.billedQty;
	}

	public void setBilledQty(BigDecimal billedQty) {
		this.billedQty = billedQty;
	}

	@Column(name = "bonus_qty", precision = 131089, scale = 0)
	public BigDecimal getBonusQty() {
		return this.bonusQty;
	}

	public void setBonusQty(BigDecimal bonusQty) {
		this.bonusQty = bonusQty;
	}

	@Column(name = "cost_price", precision = 15)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "discount", precision = 15)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "tax_rate", precision = 15)
	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "tax", precision = 131089, scale = 0)
	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	@Column(name = "adj_mrp", precision = 15)
	public BigDecimal getAdjMrp() {
		return this.adjMrp;
	}

	public void setAdjMrp(BigDecimal adjMrp) {
		this.adjMrp = adjMrp;
	}

	@Column(name = "tax_type", length = 2)
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Column(name = "outgoing_tax_rate", precision = 15)
	public BigDecimal getOutgoingTaxRate() {
		return this.outgoingTaxRate;
	}

	public void setOutgoingTaxRate(BigDecimal outgoingTaxRate) {
		this.outgoingTaxRate = outgoingTaxRate;
	}

	@Column(name = "medicine_id")
	public Integer getMedicineId() {
		return this.medicineId;
	}

	public void setMedicineId(Integer medicineId) {
		this.medicineId = medicineId;
	}

	@Column(name = "issue_qty", precision = 131089, scale = 0)
	public BigDecimal getIssueQty() {
		return this.issueQty;
	}

	public void setIssueQty(BigDecimal issueQty) {
		this.issueQty = issueQty;
	}

	@Column(name = "total_qty", precision = 131089, scale = 0)
	public BigDecimal getTotalQty() {
		return this.totalQty;
	}

	public void setTotalQty(BigDecimal totalQty) {
		this.totalQty = totalQty;
	}

	@Column(name = "grn_pkg_size", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getGrnPkgSize() {
		return this.grnPkgSize;
	}

	public void setGrnPkgSize(BigDecimal grnPkgSize) {
		this.grnPkgSize = grnPkgSize;
	}

	@Column(name = "orig_debit_rate", precision = 15)
	public BigDecimal getOrigDebitRate() {
		return this.origDebitRate;
	}

	public void setOrigDebitRate(BigDecimal origDebitRate) {
		this.origDebitRate = origDebitRate;
	}

	@Column(name = "orig_discount", precision = 15)
	public BigDecimal getOrigDiscount() {
		return this.origDiscount;
	}

	public void setOrigDiscount(BigDecimal origDiscount) {
		this.origDiscount = origDiscount;
	}

	@Column(name = "orig_tax", precision = 15)
	public BigDecimal getOrigTax() {
		return this.origTax;
	}

	public void setOrigTax(BigDecimal origTax) {
		this.origTax = origTax;
	}

	@Column(name = "item_ced_per", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getItemCedPer() {
		return this.itemCedPer;
	}

	public void setItemCedPer(BigDecimal itemCedPer) {
		this.itemCedPer = itemCedPer;
	}

	@Column(name = "item_ced", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getItemCed() {
		return this.itemCed;
	}

	public void setItemCed(BigDecimal itemCed) {
		this.itemCed = itemCed;
	}

	@Column(name = "orig_ced", nullable = false, precision = 15)
	public BigDecimal getOrigCed() {
		return this.origCed;
	}

	public void setOrigCed(BigDecimal origCed) {
		this.origCed = origCed;
	}

	@Column(name = "item_order", nullable = false)
	public int getItemOrder() {
		return this.itemOrder;
	}

	public void setItemOrder(int itemOrder) {
		this.itemOrder = itemOrder;
	}

	@Column(name = "grn_package_uom", length = 100)
	public String getGrnPackageUom() {
		return this.grnPackageUom;
	}

	public void setGrnPackageUom(String grnPackageUom) {
		this.grnPackageUom = grnPackageUom;
	}

	@Column(name = "item_batch_id")
	public Integer getItemBatchId() {
		return this.itemBatchId;
	}

	public void setItemBatchId(Integer itemBatchId) {
		this.itemBatchId = itemBatchId;
	}

	@Column(name = "bonus_tax", nullable = false, precision = 15)
	public BigDecimal getBonusTax() {
		return this.bonusTax;
	}

	public void setBonusTax(BigDecimal bonusTax) {
		this.bonusTax = bonusTax;
	}

	@Column(name = "scheme_discount", precision = 15)
	public BigDecimal getSchemeDiscount() {
		return this.schemeDiscount;
	}

	public void setSchemeDiscount(BigDecimal schemeDiscount) {
		this.schemeDiscount = schemeDiscount;
	}

	@Column(name = "orig_scheme_discount", precision = 15)
	public BigDecimal getOrigSchemeDiscount() {
		return this.origSchemeDiscount;
	}

	public void setOrigSchemeDiscount(BigDecimal origSchemeDiscount) {
		this.origSchemeDiscount = origSchemeDiscount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StoreGrnDetailsIdSequence))
			return false;
		StoreGrnDetailsIdSequence castOther = (StoreGrnDetailsIdSequence) other;

		return ((this.getGrnNo() == castOther.getGrnNo()) || (this.getGrnNo() != null && castOther.getGrnNo() != null
				&& this.getGrnNo().equals(castOther.getGrnNo())))
				&& ((this.getBatchNo() == castOther.getBatchNo()) || (this.getBatchNo() != null
						&& castOther.getBatchNo() != null && this.getBatchNo().equals(castOther.getBatchNo())))
				&& ((this.getExpDt() == castOther.getExpDt()) || (this.getExpDt() != null
						&& castOther.getExpDt() != null && this.getExpDt().equals(castOther.getExpDt())))
				&& ((this.getMrp() == castOther.getMrp()) || (this.getMrp() != null && castOther.getMrp() != null
						&& this.getMrp().equals(castOther.getMrp())))
				&& ((this.getBilledQty() == castOther.getBilledQty()) || (this.getBilledQty() != null
						&& castOther.getBilledQty() != null && this.getBilledQty().equals(castOther.getBilledQty())))
				&& ((this.getBonusQty() == castOther.getBonusQty()) || (this.getBonusQty() != null
						&& castOther.getBonusQty() != null && this.getBonusQty().equals(castOther.getBonusQty())))
				&& ((this.getCostPrice() == castOther.getCostPrice()) || (this.getCostPrice() != null
						&& castOther.getCostPrice() != null && this.getCostPrice().equals(castOther.getCostPrice())))
				&& ((this.getDiscount() == castOther.getDiscount()) || (this.getDiscount() != null
						&& castOther.getDiscount() != null && this.getDiscount().equals(castOther.getDiscount())))
				&& ((this.getTaxRate() == castOther.getTaxRate()) || (this.getTaxRate() != null
						&& castOther.getTaxRate() != null && this.getTaxRate().equals(castOther.getTaxRate())))
				&& ((this.getTax() == castOther.getTax()) || (this.getTax() != null && castOther.getTax() != null
						&& this.getTax().equals(castOther.getTax())))
				&& ((this.getAdjMrp() == castOther.getAdjMrp()) || (this.getAdjMrp() != null
						&& castOther.getAdjMrp() != null && this.getAdjMrp().equals(castOther.getAdjMrp())))
				&& ((this.getTaxType() == castOther.getTaxType()) || (this.getTaxType() != null
						&& castOther.getTaxType() != null && this.getTaxType().equals(castOther.getTaxType())))
				&& ((this.getOutgoingTaxRate() == castOther.getOutgoingTaxRate())
						|| (this.getOutgoingTaxRate() != null && castOther.getOutgoingTaxRate() != null
								&& this.getOutgoingTaxRate().equals(castOther.getOutgoingTaxRate())))
				&& ((this.getMedicineId() == castOther.getMedicineId()) || (this.getMedicineId() != null
						&& castOther.getMedicineId() != null && this.getMedicineId().equals(castOther.getMedicineId())))
				&& ((this.getIssueQty() == castOther.getIssueQty()) || (this.getIssueQty() != null
						&& castOther.getIssueQty() != null && this.getIssueQty().equals(castOther.getIssueQty())))
				&& ((this.getTotalQty() == castOther.getTotalQty()) || (this.getTotalQty() != null
						&& castOther.getTotalQty() != null && this.getTotalQty().equals(castOther.getTotalQty())))
				&& ((this.getGrnPkgSize() == castOther.getGrnPkgSize()) || (this.getGrnPkgSize() != null
						&& castOther.getGrnPkgSize() != null && this.getGrnPkgSize().equals(castOther.getGrnPkgSize())))
				&& ((this.getOrigDebitRate() == castOther.getOrigDebitRate())
						|| (this.getOrigDebitRate() != null && castOther.getOrigDebitRate() != null
								&& this.getOrigDebitRate().equals(castOther.getOrigDebitRate())))
				&& ((this.getOrigDiscount() == castOther.getOrigDiscount())
						|| (this.getOrigDiscount() != null && castOther.getOrigDiscount() != null
								&& this.getOrigDiscount().equals(castOther.getOrigDiscount())))
				&& ((this.getOrigTax() == castOther.getOrigTax()) || (this.getOrigTax() != null
						&& castOther.getOrigTax() != null && this.getOrigTax().equals(castOther.getOrigTax())))
				&& ((this.getItemCedPer() == castOther.getItemCedPer()) || (this.getItemCedPer() != null
						&& castOther.getItemCedPer() != null && this.getItemCedPer().equals(castOther.getItemCedPer())))
				&& ((this.getItemCed() == castOther.getItemCed()) || (this.getItemCed() != null
						&& castOther.getItemCed() != null && this.getItemCed().equals(castOther.getItemCed())))
				&& ((this.getOrigCed() == castOther.getOrigCed()) || (this.getOrigCed() != null
						&& castOther.getOrigCed() != null && this.getOrigCed().equals(castOther.getOrigCed())))
				&& (this.getItemOrder() == castOther.getItemOrder())
				&& ((this.getGrnPackageUom() == castOther.getGrnPackageUom())
						|| (this.getGrnPackageUom() != null && castOther.getGrnPackageUom() != null
								&& this.getGrnPackageUom().equals(castOther.getGrnPackageUom())))
				&& ((this.getItemBatchId() == castOther.getItemBatchId())
						|| (this.getItemBatchId() != null && castOther.getItemBatchId() != null
								&& this.getItemBatchId().equals(castOther.getItemBatchId())))
				&& ((this.getBonusTax() == castOther.getBonusTax()) || (this.getBonusTax() != null
						&& castOther.getBonusTax() != null && this.getBonusTax().equals(castOther.getBonusTax())))
				&& ((this.getSchemeDiscount() == castOther.getSchemeDiscount())
						|| (this.getSchemeDiscount() != null && castOther.getSchemeDiscount() != null
								&& this.getSchemeDiscount().equals(castOther.getSchemeDiscount())))
				&& ((this.getOrigSchemeDiscount() == castOther.getOrigSchemeDiscount())
						|| (this.getOrigSchemeDiscount() != null && castOther.getOrigSchemeDiscount() != null
								&& this.getOrigSchemeDiscount().equals(castOther.getOrigSchemeDiscount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		result = 37 * result + (getBatchNo() == null ? 0 : this.getBatchNo().hashCode());
		result = 37 * result + (getExpDt() == null ? 0 : this.getExpDt().hashCode());
		result = 37 * result + (getMrp() == null ? 0 : this.getMrp().hashCode());
		result = 37 * result + (getBilledQty() == null ? 0 : this.getBilledQty().hashCode());
		result = 37 * result + (getBonusQty() == null ? 0 : this.getBonusQty().hashCode());
		result = 37 * result + (getCostPrice() == null ? 0 : this.getCostPrice().hashCode());
		result = 37 * result + (getDiscount() == null ? 0 : this.getDiscount().hashCode());
		result = 37 * result + (getTaxRate() == null ? 0 : this.getTaxRate().hashCode());
		result = 37 * result + (getTax() == null ? 0 : this.getTax().hashCode());
		result = 37 * result + (getAdjMrp() == null ? 0 : this.getAdjMrp().hashCode());
		result = 37 * result + (getTaxType() == null ? 0 : this.getTaxType().hashCode());
		result = 37 * result + (getOutgoingTaxRate() == null ? 0 : this.getOutgoingTaxRate().hashCode());
		result = 37 * result + (getMedicineId() == null ? 0 : this.getMedicineId().hashCode());
		result = 37 * result + (getIssueQty() == null ? 0 : this.getIssueQty().hashCode());
		result = 37 * result + (getTotalQty() == null ? 0 : this.getTotalQty().hashCode());
		result = 37 * result + (getGrnPkgSize() == null ? 0 : this.getGrnPkgSize().hashCode());
		result = 37 * result + (getOrigDebitRate() == null ? 0 : this.getOrigDebitRate().hashCode());
		result = 37 * result + (getOrigDiscount() == null ? 0 : this.getOrigDiscount().hashCode());
		result = 37 * result + (getOrigTax() == null ? 0 : this.getOrigTax().hashCode());
		result = 37 * result + (getItemCedPer() == null ? 0 : this.getItemCedPer().hashCode());
		result = 37 * result + (getItemCed() == null ? 0 : this.getItemCed().hashCode());
		result = 37 * result + (getOrigCed() == null ? 0 : this.getOrigCed().hashCode());
		result = 37 * result + this.getItemOrder();
		result = 37 * result + (getGrnPackageUom() == null ? 0 : this.getGrnPackageUom().hashCode());
		result = 37 * result + (getItemBatchId() == null ? 0 : this.getItemBatchId().hashCode());
		result = 37 * result + (getBonusTax() == null ? 0 : this.getBonusTax().hashCode());
		result = 37 * result + (getSchemeDiscount() == null ? 0 : this.getSchemeDiscount().hashCode());
		result = 37 * result + (getOrigSchemeDiscount() == null ? 0 : this.getOrigSchemeDiscount().hashCode());
		return result;
	}

}
