package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.insta.hms.mdm.item.StoreItemDetailsModel;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoreTransferDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "store_transfer_details")
public class StoreTransferDetailsModel implements java.io.Serializable {

	private int transferDetailNo;
	private StoreTransferMainModel storeTransferMain;
	private StoreIndentMainModel storeIndentMain;
	private StoreItemDetailsModel storeItemDetails;
	private String batchNo;
	private BigDecimal qty;
	private BigDecimal qtyRejected;
	private BigDecimal qtyRecd;
	private Character itemUnit;
	private BigDecimal trnPkgSize;
	private Integer itemBatchId;
	private BigDecimal costValue;
	private String description;
	private char isRejectedQtyTaken;
	private Date receivedDate;
	private String receivedBy;
	private Date processedDate;
	private String processedBy;
	private Date reconsolidatedDate;
	private String reconsolidatedBy;
	private BigDecimal receivedCostValue;

	public StoreTransferDetailsModel() {
	}

	public StoreTransferDetailsModel(int transferDetailNo, StoreTransferMainModel storeTransferMain,
			StoreItemDetailsModel storeItemDetails, BigDecimal qty, BigDecimal qtyRejected, BigDecimal qtyRecd,
			char isRejectedQtyTaken) {
		this.transferDetailNo = transferDetailNo;
		this.storeTransferMain = storeTransferMain;
		this.storeItemDetails = storeItemDetails;
		this.qty = qty;
		this.qtyRejected = qtyRejected;
		this.qtyRecd = qtyRecd;
		this.isRejectedQtyTaken = isRejectedQtyTaken;
	}

	public StoreTransferDetailsModel(int transferDetailNo, StoreTransferMainModel storeTransferMain,
			StoreIndentMainModel storeIndentMain, StoreItemDetailsModel storeItemDetails, String batchNo, BigDecimal qty,
			BigDecimal qtyRejected, BigDecimal qtyRecd, Character itemUnit, BigDecimal trnPkgSize, Integer itemBatchId,
			BigDecimal costValue, String description, char isRejectedQtyTaken, Date receivedDate, String receivedBy,
			Date processedDate, String processedBy, Date reconsolidatedDate, String reconsolidatedBy,
			BigDecimal receivedCostValue) {
		this.transferDetailNo = transferDetailNo;
		this.storeTransferMain = storeTransferMain;
		this.storeIndentMain = storeIndentMain;
		this.storeItemDetails = storeItemDetails;
		this.batchNo = batchNo;
		this.qty = qty;
		this.qtyRejected = qtyRejected;
		this.qtyRecd = qtyRecd;
		this.itemUnit = itemUnit;
		this.trnPkgSize = trnPkgSize;
		this.itemBatchId = itemBatchId;
		this.costValue = costValue;
		this.description = description;
		this.isRejectedQtyTaken = isRejectedQtyTaken;
		this.receivedDate = receivedDate;
		this.receivedBy = receivedBy;
		this.processedDate = processedDate;
		this.processedBy = processedBy;
		this.reconsolidatedDate = reconsolidatedDate;
		this.reconsolidatedBy = reconsolidatedBy;
		this.receivedCostValue = receivedCostValue;
	}

	@Id

	@Column(name = "transfer_detail_no", unique = true, nullable = false)
	public int getTransferDetailNo() {
		return this.transferDetailNo;
	}

	public void setTransferDetailNo(int transferDetailNo) {
		this.transferDetailNo = transferDetailNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transfer_no", nullable = false)
	public StoreTransferMainModel getStoreTransferMainModel() {
		return this.storeTransferMain;
	}

	public void setStoreTransferMainModel(StoreTransferMainModel storeTransferMain) {
		this.storeTransferMain = storeTransferMain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "indent_no")
	public StoreIndentMainModel getStoreIndentMainModel() {
		return this.storeIndentMain;
	}

	public void setStoreIndentMainModel(StoreIndentMainModel storeIndentMain) {
		this.storeIndentMain = storeIndentMain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicine_id", nullable = false)
	public StoreItemDetailsModel getStoreItemDetailsModel() {
		return this.storeItemDetails;
	}

	public void setStoreItemDetailsModel(StoreItemDetailsModel storeItemDetails) {
		this.storeItemDetails = storeItemDetails;
	}

	@Column(name = "batch_no", length = 100)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "qty", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "qty_rejected", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQtyRejected() {
		return this.qtyRejected;
	}

	public void setQtyRejected(BigDecimal qtyRejected) {
		this.qtyRejected = qtyRejected;
	}

	@Column(name = "qty_recd", nullable = false, precision = 10)
	public BigDecimal getQtyRecd() {
		return this.qtyRecd;
	}

	public void setQtyRecd(BigDecimal qtyRecd) {
		this.qtyRecd = qtyRecd;
	}

	@Column(name = "item_unit", length = 1)
	public Character getItemUnit() {
		return this.itemUnit;
	}

	public void setItemUnit(Character itemUnit) {
		this.itemUnit = itemUnit;
	}

	@Column(name = "trn_pkg_size", precision = 131089, scale = 0)
	public BigDecimal getTrnPkgSize() {
		return this.trnPkgSize;
	}

	public void setTrnPkgSize(BigDecimal trnPkgSize) {
		this.trnPkgSize = trnPkgSize;
	}

	@Column(name = "item_batch_id")
	public Integer getItemBatchId() {
		return this.itemBatchId;
	}

	public void setItemBatchId(Integer itemBatchId) {
		this.itemBatchId = itemBatchId;
	}

	@Column(name = "cost_value", precision = 131089, scale = 0)
	public BigDecimal getCostValue() {
		return this.costValue;
	}

	public void setCostValue(BigDecimal costValue) {
		this.costValue = costValue;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_rejected_qty_taken", nullable = false, length = 1)
	public char getIsRejectedQtyTaken() {
		return this.isRejectedQtyTaken;
	}

	public void setIsRejectedQtyTaken(char isRejectedQtyTaken) {
		this.isRejectedQtyTaken = isRejectedQtyTaken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_date", length = 29)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	@Column(name = "received_by", length = 30)
	public String getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "processed_date", length = 29)
	public Date getProcessedDate() {
		return this.processedDate;
	}

	public void setProcessedDate(Date processedDate) {
		this.processedDate = processedDate;
	}

	@Column(name = "processed_by", length = 30)
	public String getProcessedBy() {
		return this.processedBy;
	}

	public void setProcessedBy(String processedBy) {
		this.processedBy = processedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reconsolidated_date", length = 29)
	public Date getReconsolidatedDate() {
		return this.reconsolidatedDate;
	}

	public void setReconsolidatedDate(Date reconsolidatedDate) {
		this.reconsolidatedDate = reconsolidatedDate;
	}

	@Column(name = "reconsolidated_by", length = 30)
	public String getReconsolidatedBy() {
		return this.reconsolidatedBy;
	}

	public void setReconsolidatedBy(String reconsolidatedBy) {
		this.reconsolidatedBy = reconsolidatedBy;
	}

	@Column(name = "received_cost_value", precision = 131089, scale = 0)
	public BigDecimal getReceivedCostValue() {
		return this.receivedCostValue;
	}

	public void setReceivedCostValue(BigDecimal receivedCostValue) {
		this.receivedCostValue = receivedCostValue;
	}

}
