package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SupplierCenterMasterModel generated by hbm2java
 */
@Entity
@Table(name = "supplier_center_master", uniqueConstraints = @UniqueConstraint(columnNames = { "center_id",
		"supplier_code" }))
public class SupplierCenterMasterModel implements java.io.Serializable {

	private int suppCenterId;
	private int centerId;
	private String supplierCode;
	private String status;

	public SupplierCenterMasterModel() {
	}

	public SupplierCenterMasterModel(int suppCenterId, int centerId, String supplierCode, String status) {
		this.suppCenterId = suppCenterId;
		this.centerId = centerId;
		this.supplierCode = supplierCode;
		this.status = status;
	}

	@Id

	@Column(name = "supp_center_id", unique = true, nullable = false)
	public int getSuppCenterId() {
		return this.suppCenterId;
	}

	public void setSuppCenterId(int suppCenterId) {
		this.suppCenterId = suppCenterId;
	}

	@Column(name = "center_id", nullable = false)
	public int getCenterId() {
		return this.centerId;
	}

	public void setCenterId(int centerId) {
		this.centerId = centerId;
	}

	@Column(name = "supplier_code", nullable = false, length = 10)
	public String getSupplierCode() {
		return this.supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
