package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SurveyRatingTypeMasterModel generated by hbm2java
 */
@Entity
@Table(name = "survey_rating_type_master")
public class SurveyRatingTypeMasterModel implements java.io.Serializable {

	private int ratingTypeId;
	private String ratingType;
	private String status;

	public SurveyRatingTypeMasterModel() {
	}

	public SurveyRatingTypeMasterModel(int ratingTypeId) {
		this.ratingTypeId = ratingTypeId;
	}

	public SurveyRatingTypeMasterModel(int ratingTypeId, String ratingType, String status) {
		this.ratingTypeId = ratingTypeId;
		this.ratingType = ratingType;
		this.status = status;
	}

	@Id

	@Column(name = "rating_type_id", unique = true, nullable = false)
	public int getRatingTypeId() {
		return this.ratingTypeId;
	}

	public void setRatingTypeId(int ratingTypeId) {
		this.ratingTypeId = ratingTypeId;
	}

	@Column(name = "rating_type", length = 300)
	public String getRatingType() {
		return this.ratingType;
	}

	public void setRatingType(String ratingType) {
		this.ratingType = ratingType;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
