package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SurveyQuestionCategoryMasterModel generated by hbm2java
 */
@Entity
@Table(name = "survey_question_category_master")
public class SurveyQuestionCategoryMasterModel implements java.io.Serializable {

	private int categoryId;
	private String category;
	private String categoryDesc;
	private String status;

	public SurveyQuestionCategoryMasterModel() {
	}

	public SurveyQuestionCategoryMasterModel(int categoryId) {
		this.categoryId = categoryId;
	}

	public SurveyQuestionCategoryMasterModel(int categoryId, String category, String categoryDesc, String status) {
		this.categoryId = categoryId;
		this.category = category;
		this.categoryDesc = categoryDesc;
		this.status = status;
	}

	@Id

	@Column(name = "category_id", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category", length = 300)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "category_desc", length = 500)
	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
