package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SystemMessagesModel generated by hbm2java
 */
@Entity
@Table(name = "system_messages")
public class SystemMessagesModel implements java.io.Serializable {

	private SystemMessagesIdSequence id;

	public SystemMessagesModel() {
	}

	public SystemMessagesModel(SystemMessagesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "messageId", column = @Column(name = "message_id")),
			@AttributeOverride(name = "messages", column = @Column(name = "messages", length = 300)),
			@AttributeOverride(name = "systemType", column = @Column(name = "system_type")),
			@AttributeOverride(name = "severity", column = @Column(name = "severity", length = 1)),
			@AttributeOverride(name = "displayOrder", column = @Column(name = "display_order")),
			@AttributeOverride(name = "screenId", column = @Column(name = "screen_id", nullable = false)),
			@AttributeOverride(name = "param1", column = @Column(name = "param1")),
			@AttributeOverride(name = "param2", column = @Column(name = "param2")) })
	public SystemMessagesIdSequence getId() {
		return this.id;
	}

	public void setId(SystemMessagesIdSequence id) {
		this.id = id;
	}

}
