package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SystemPreferencesAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "system_preferences_audit_log")
public class SystemPreferencesAuditLogModel implements java.io.Serializable {

	private SystemPreferencesAuditLogIdSequence id;

	public SystemPreferencesAuditLogModel() {
	}

	public SystemPreferencesAuditLogModel(SystemPreferencesAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "operation", column = @Column(name = "operation")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")) })
	public SystemPreferencesAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(SystemPreferencesAuditLogIdSequence id) {
		this.id = id;
	}

}
