package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TestEquipmentMasterModel generated by hbm2java
 */
@Entity
@Table(name = "test_equipment_master")
public class TestEquipmentMasterModel implements java.io.Serializable {

	private TestEquipmentMasterIdSequence id;

	public TestEquipmentMasterModel() {
	}

	public TestEquipmentMasterModel(TestEquipmentMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "eqId", column = @Column(name = "eq_id")),
			@AttributeOverride(name = "equipmentName", column = @Column(name = "equipment_name", length = 100)),
			@AttributeOverride(name = "schedule", column = @Column(name = "schedule")),
			@AttributeOverride(name = "hl7ExportCode", column = @Column(name = "hl7_export_code", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "obsoleteOverbook", column = @Column(name = "obsolete_overbook")),
			@AttributeOverride(name = "centerId", column = @Column(name = "center_id", nullable = false)),
			@AttributeOverride(name = "ddeptId", column = @Column(name = "ddept_id", length = 10)),
			@AttributeOverride(name = "overbookLimit", column = @Column(name = "overbook_limit")) })
	public TestEquipmentMasterIdSequence getId() {
		return this.id;
	}

	public void setId(TestEquipmentMasterIdSequence id) {
		this.id = id;
	}

}
