package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestCytologyResultsModel generated by hbm2java
 */
@Entity
@Table(name = "test_cytology_results")
public class TestCytologyResultsModel implements java.io.Serializable {

	private String cytoId;
	private String mrNo;
	private String patientId;
	private String testId;
	private int prescribedId;
	private String testType;
	private String microscopicDetails;
	private String specimenAdequacy;
	private String smearReceived;
	private Integer impressionId;
	private String clinicalDetails;
	private String impressionDetails;

	public TestCytologyResultsModel() {
	}

	public TestCytologyResultsModel(String cytoId, String patientId, int prescribedId) {
		this.cytoId = cytoId;
		this.patientId = patientId;
		this.prescribedId = prescribedId;
	}

	public TestCytologyResultsModel(String cytoId, String mrNo, String patientId, String testId, int prescribedId,
			String testType, String microscopicDetails, String specimenAdequacy, String smearReceived,
			Integer impressionId, String clinicalDetails, String impressionDetails) {
		this.cytoId = cytoId;
		this.mrNo = mrNo;
		this.patientId = patientId;
		this.testId = testId;
		this.prescribedId = prescribedId;
		this.testType = testType;
		this.microscopicDetails = microscopicDetails;
		this.specimenAdequacy = specimenAdequacy;
		this.smearReceived = smearReceived;
		this.impressionId = impressionId;
		this.clinicalDetails = clinicalDetails;
		this.impressionDetails = impressionDetails;
	}

	@Id

	@Column(name = "cyto_id", unique = true, nullable = false, length = 50)
	public String getCytoId() {
		return this.cytoId;
	}

	public void setCytoId(String cytoId) {
		this.cytoId = cytoId;
	}

	@Column(name = "mr_no", length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "patient_id", nullable = false, length = 40)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "test_id", length = 10)
	public String getTestId() {
		return this.testId;
	}

	public void setTestId(String testId) {
		this.testId = testId;
	}

	@Column(name = "prescribed_id", nullable = false)
	public int getPrescribedId() {
		return this.prescribedId;
	}

	public void setPrescribedId(int prescribedId) {
		this.prescribedId = prescribedId;
	}

	@Column(name = "test_type", length = 1)
	public String getTestType() {
		return this.testType;
	}

	public void setTestType(String testType) {
		this.testType = testType;
	}

	@Column(name = "microscopic_details", length = 5000)
	public String getMicroscopicDetails() {
		return this.microscopicDetails;
	}

	public void setMicroscopicDetails(String microscopicDetails) {
		this.microscopicDetails = microscopicDetails;
	}

	@Column(name = "specimen_adequacy", length = 500)
	public String getSpecimenAdequacy() {
		return this.specimenAdequacy;
	}

	public void setSpecimenAdequacy(String specimenAdequacy) {
		this.specimenAdequacy = specimenAdequacy;
	}

	@Column(name = "smear_received", length = 10)
	public String getSmearReceived() {
		return this.smearReceived;
	}

	public void setSmearReceived(String smearReceived) {
		this.smearReceived = smearReceived;
	}

	@Column(name = "impression_id")
	public Integer getImpressionId() {
		return this.impressionId;
	}

	public void setImpressionId(Integer impressionId) {
		this.impressionId = impressionId;
	}

	@Column(name = "clinical_details", length = 5000)
	public String getClinicalDetails() {
		return this.clinicalDetails;
	}

	public void setClinicalDetails(String clinicalDetails) {
		this.clinicalDetails = clinicalDetails;
	}

	@Column(name = "impression_details", length = 500)
	public String getImpressionDetails() {
		return this.impressionDetails;
	}

	public void setImpressionDetails(String impressionDetails) {
		this.impressionDetails = impressionDetails;
	}

}
