package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestsConductedAuditLogIdSequence generated by hbm2java
 */
@Embeddable
public class TestsConductedAuditLogIdSequence implements java.io.Serializable {

	private int logId;
	private Integer prescribedId;
	private String patientId;
	private String testId;
	private String userName;
	private Date modTime;
	private String operation;
	private String fieldName;
	private String oldValue;
	private String newValue;

	public TestsConductedAuditLogIdSequence() {
	}

	public TestsConductedAuditLogIdSequence(int logId, Date modTime) {
		this.logId = logId;
		this.modTime = modTime;
	}

	public TestsConductedAuditLogIdSequence(int logId, Integer prescribedId, String patientId, String testId, String userName,
			Date modTime, String operation, String fieldName, String oldValue, String newValue) {
		this.logId = logId;
		this.prescribedId = prescribedId;
		this.patientId = patientId;
		this.testId = testId;
		this.userName = userName;
		this.modTime = modTime;
		this.operation = operation;
		this.fieldName = fieldName;
		this.oldValue = oldValue;
		this.newValue = newValue;
	}

	@Column(name = "log_id", nullable = false)
	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	@Column(name = "prescribed_id")
	public Integer getPrescribedId() {
		return this.prescribedId;
	}

	public void setPrescribedId(Integer prescribedId) {
		this.prescribedId = prescribedId;
	}

	@Column(name = "patient_id", length = 15)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "test_id", length = 10)
	public String getTestId() {
		return this.testId;
	}

	public void setTestId(String testId) {
		this.testId = testId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "operation")
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "field_name")
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "old_value")
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "new_value")
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestsConductedAuditLogIdSequence))
			return false;
		TestsConductedAuditLogIdSequence castOther = (TestsConductedAuditLogIdSequence) other;

		return (this.getLogId() == castOther.getLogId())
				&& ((this.getPrescribedId() == castOther.getPrescribedId())
						|| (this.getPrescribedId() != null && castOther.getPrescribedId() != null
								&& this.getPrescribedId().equals(castOther.getPrescribedId())))
				&& ((this.getPatientId() == castOther.getPatientId()) || (this.getPatientId() != null
						&& castOther.getPatientId() != null && this.getPatientId().equals(castOther.getPatientId())))
				&& ((this.getTestId() == castOther.getTestId()) || (this.getTestId() != null
						&& castOther.getTestId() != null && this.getTestId().equals(castOther.getTestId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getModTime() == castOther.getModTime()) || (this.getModTime() != null
						&& castOther.getModTime() != null && this.getModTime().equals(castOther.getModTime())))
				&& ((this.getOperation() == castOther.getOperation()) || (this.getOperation() != null
						&& castOther.getOperation() != null && this.getOperation().equals(castOther.getOperation())))
				&& ((this.getFieldName() == castOther.getFieldName()) || (this.getFieldName() != null
						&& castOther.getFieldName() != null && this.getFieldName().equals(castOther.getFieldName())))
				&& ((this.getOldValue() == castOther.getOldValue()) || (this.getOldValue() != null
						&& castOther.getOldValue() != null && this.getOldValue().equals(castOther.getOldValue())))
				&& ((this.getNewValue() == castOther.getNewValue()) || (this.getNewValue() != null
						&& castOther.getNewValue() != null && this.getNewValue().equals(castOther.getNewValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLogId();
		result = 37 * result + (getPrescribedId() == null ? 0 : this.getPrescribedId().hashCode());
		result = 37 * result + (getPatientId() == null ? 0 : this.getPatientId().hashCode());
		result = 37 * result + (getTestId() == null ? 0 : this.getTestId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getModTime() == null ? 0 : this.getModTime().hashCode());
		result = 37 * result + (getOperation() == null ? 0 : this.getOperation().hashCode());
		result = 37 * result + (getFieldName() == null ? 0 : this.getFieldName().hashCode());
		result = 37 * result + (getOldValue() == null ? 0 : this.getOldValue().hashCode());
		result = 37 * result + (getNewValue() == null ? 0 : this.getNewValue().hashCode());
		return result;
	}

}
