package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TestsPrescribedAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "tests_prescribed_audit_log")
public class TestsPrescribedAuditLogModel implements java.io.Serializable {

	private TestsPrescribedAuditLogIdSequence id;

	public TestsPrescribedAuditLogModel() {
	}

	public TestsPrescribedAuditLogModel(TestsPrescribedAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "prescribedId", column = @Column(name = "prescribed_id")),
			@AttributeOverride(name = "patId", column = @Column(name = "pat_id", length = 15)),
			@AttributeOverride(name = "testId", column = @Column(name = "test_id", length = 10)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name")),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "operation", column = @Column(name = "operation")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")) })
	public TestsPrescribedAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(TestsPrescribedAuditLogIdSequence id) {
		this.id = id;
	}

}
