package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestVisitReportSignaturesIdSequence generated by hbm2java
 */
@Embeddable
public class TestVisitReportSignaturesIdSequence implements java.io.Serializable {

	private Integer reportId;
	private Integer prescribedId;
	private Character signedAs;
	private String signatoryUsername;
	private String doctorId;

	public TestVisitReportSignaturesIdSequence() {
	}

	public TestVisitReportSignaturesIdSequence(Integer reportId, Integer prescribedId, Character signedAs,
			String signatoryUsername, String doctorId) {
		this.reportId = reportId;
		this.prescribedId = prescribedId;
		this.signedAs = signedAs;
		this.signatoryUsername = signatoryUsername;
		this.doctorId = doctorId;
	}

	@Column(name = "report_id")
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@Column(name = "prescribed_id")
	public Integer getPrescribedId() {
		return this.prescribedId;
	}

	public void setPrescribedId(Integer prescribedId) {
		this.prescribedId = prescribedId;
	}

	@Column(name = "signed_as", length = 1)
	public Character getSignedAs() {
		return this.signedAs;
	}

	public void setSignedAs(Character signedAs) {
		this.signedAs = signedAs;
	}

	@Column(name = "signatory_username", length = 30)
	public String getSignatoryUsername() {
		return this.signatoryUsername;
	}

	public void setSignatoryUsername(String signatoryUsername) {
		this.signatoryUsername = signatoryUsername;
	}

	@Column(name = "doctor_id", length = 20)
	public String getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestVisitReportSignaturesIdSequence))
			return false;
		TestVisitReportSignaturesIdSequence castOther = (TestVisitReportSignaturesIdSequence) other;

		return ((this.getReportId() == castOther.getReportId()) || (this.getReportId() != null
				&& castOther.getReportId() != null && this.getReportId().equals(castOther.getReportId())))
				&& ((this.getPrescribedId() == castOther.getPrescribedId())
						|| (this.getPrescribedId() != null && castOther.getPrescribedId() != null
								&& this.getPrescribedId().equals(castOther.getPrescribedId())))
				&& ((this.getSignedAs() == castOther.getSignedAs()) || (this.getSignedAs() != null
						&& castOther.getSignedAs() != null && this.getSignedAs().equals(castOther.getSignedAs())))
				&& ((this.getSignatoryUsername() == castOther.getSignatoryUsername())
						|| (this.getSignatoryUsername() != null && castOther.getSignatoryUsername() != null
								&& this.getSignatoryUsername().equals(castOther.getSignatoryUsername())))
				&& ((this.getDoctorId() == castOther.getDoctorId()) || (this.getDoctorId() != null
						&& castOther.getDoctorId() != null && this.getDoctorId().equals(castOther.getDoctorId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getReportId() == null ? 0 : this.getReportId().hashCode());
		result = 37 * result + (getPrescribedId() == null ? 0 : this.getPrescribedId().hashCode());
		result = 37 * result + (getSignedAs() == null ? 0 : this.getSignedAs().hashCode());
		result = 37 * result + (getSignatoryUsername() == null ? 0 : this.getSignatoryUsername().hashCode());
		result = 37 * result + (getDoctorId() == null ? 0 : this.getDoctorId().hashCode());
		return result;
	}

}
