package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TheatreChargesModel generated by hbm2java
 */
@Entity
@Table(name = "theatre_charges")
public class TheatreChargesModel implements java.io.Serializable {

	private TheatreChargesIdSequence id;
	private TheatreMasterModel theatreMaster;
	private BigDecimal dailyCharge;
	private BigDecimal minCharge;
	private BigDecimal incrCharge;
	private BigDecimal tax;
	private BigDecimal dailyChargeDiscount;
	private BigDecimal minChargeDiscount;
	private BigDecimal incrChargeDiscount;
	private BigDecimal slab1Charge;
	private BigDecimal slab1ChargeDiscount;
	private String isOverride;

	public TheatreChargesModel() {
	}

	public TheatreChargesModel(TheatreChargesIdSequence id, TheatreMasterModel theatreMaster, BigDecimal dailyCharge,
			BigDecimal minCharge, BigDecimal incrCharge, BigDecimal dailyChargeDiscount, BigDecimal minChargeDiscount,
			BigDecimal incrChargeDiscount) {
		this.id = id;
		this.theatreMaster = theatreMaster;
		this.dailyCharge = dailyCharge;
		this.minCharge = minCharge;
		this.incrCharge = incrCharge;
		this.dailyChargeDiscount = dailyChargeDiscount;
		this.minChargeDiscount = minChargeDiscount;
		this.incrChargeDiscount = incrChargeDiscount;
	}

	public TheatreChargesModel(TheatreChargesIdSequence id, TheatreMasterModel theatreMaster, BigDecimal dailyCharge,
			BigDecimal minCharge, BigDecimal incrCharge, BigDecimal tax, BigDecimal dailyChargeDiscount,
			BigDecimal minChargeDiscount, BigDecimal incrChargeDiscount, BigDecimal slab1Charge,
			BigDecimal slab1ChargeDiscount, String isOverride) {
		this.id = id;
		this.theatreMaster = theatreMaster;
		this.dailyCharge = dailyCharge;
		this.minCharge = minCharge;
		this.incrCharge = incrCharge;
		this.tax = tax;
		this.dailyChargeDiscount = dailyChargeDiscount;
		this.minChargeDiscount = minChargeDiscount;
		this.incrChargeDiscount = incrChargeDiscount;
		this.slab1Charge = slab1Charge;
		this.slab1ChargeDiscount = slab1ChargeDiscount;
		this.isOverride = isOverride;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false, length = 10)),
			@AttributeOverride(name = "bedType", column = @Column(name = "bed_type", nullable = false, length = 50)),
			@AttributeOverride(name = "theatreId", column = @Column(name = "theatre_id", nullable = false, length = 10)) })
	public TheatreChargesIdSequence getId() {
		return this.id;
	}

	public void setId(TheatreChargesIdSequence id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "theatre_id", nullable = false, insertable = false, updatable = false)
	public TheatreMasterModel getTheatreMasterModel() {
		return this.theatreMaster;
	}

	public void setTheatreMasterModel(TheatreMasterModel theatreMaster) {
		this.theatreMaster = theatreMaster;
	}

	@Column(name = "daily_charge", nullable = false, precision = 15)
	public BigDecimal getDailyCharge() {
		return this.dailyCharge;
	}

	public void setDailyCharge(BigDecimal dailyCharge) {
		this.dailyCharge = dailyCharge;
	}

	@Column(name = "min_charge", nullable = false, precision = 15)
	public BigDecimal getMinCharge() {
		return this.minCharge;
	}

	public void setMinCharge(BigDecimal minCharge) {
		this.minCharge = minCharge;
	}

	@Column(name = "incr_charge", nullable = false, precision = 15)
	public BigDecimal getIncrCharge() {
		return this.incrCharge;
	}

	public void setIncrCharge(BigDecimal incrCharge) {
		this.incrCharge = incrCharge;
	}

	@Column(name = "tax", precision = 15)
	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	@Column(name = "daily_charge_discount", nullable = false, precision = 15)
	public BigDecimal getDailyChargeDiscount() {
		return this.dailyChargeDiscount;
	}

	public void setDailyChargeDiscount(BigDecimal dailyChargeDiscount) {
		this.dailyChargeDiscount = dailyChargeDiscount;
	}

	@Column(name = "min_charge_discount", nullable = false, precision = 15)
	public BigDecimal getMinChargeDiscount() {
		return this.minChargeDiscount;
	}

	public void setMinChargeDiscount(BigDecimal minChargeDiscount) {
		this.minChargeDiscount = minChargeDiscount;
	}

	@Column(name = "incr_charge_discount", nullable = false, precision = 15)
	public BigDecimal getIncrChargeDiscount() {
		return this.incrChargeDiscount;
	}

	public void setIncrChargeDiscount(BigDecimal incrChargeDiscount) {
		this.incrChargeDiscount = incrChargeDiscount;
	}

	@Column(name = "slab_1_charge", precision = 15)
	public BigDecimal getSlab1Charge() {
		return this.slab1Charge;
	}

	public void setSlab1Charge(BigDecimal slab1Charge) {
		this.slab1Charge = slab1Charge;
	}

	@Column(name = "slab_1_charge_discount", precision = 15)
	public BigDecimal getSlab1ChargeDiscount() {
		return this.slab1ChargeDiscount;
	}

	public void setSlab1ChargeDiscount(BigDecimal slab1ChargeDiscount) {
		this.slab1ChargeDiscount = slab1ChargeDiscount;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

}
