package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TreatmentChartModel generated by hbm2java
 */
@Entity
@Table(name = "treatment_chart")
public class TreatmentChartModel implements java.io.Serializable {

	private int prescriptionId;
	private String mrNo;
	private Date prescribedDate;
	private Character type;
	private String itemName;
	private Integer recurrenceDailyId;
	private String medicineDosage;
	private String remarks;
	private char freqType;
	private char discontinued;
	private Date modTime;
	private String username;
	private Boolean ispackage;
	private String itemId;
	private Integer routeOfAdmin;
	private Integer days;
	private String visitId;
	private Integer orderId;
	private Integer itemFormId;
	private String itemStrength;

	public TreatmentChartModel() {
	}

	public TreatmentChartModel(int prescriptionId, String mrNo, Date prescribedDate, char freqType, char discontinued,
			Date modTime) {
		this.prescriptionId = prescriptionId;
		this.mrNo = mrNo;
		this.prescribedDate = prescribedDate;
		this.freqType = freqType;
		this.discontinued = discontinued;
		this.modTime = modTime;
	}

	public TreatmentChartModel(int prescriptionId, String mrNo, Date prescribedDate, Character type, String itemName,
			Integer recurrenceDailyId, String medicineDosage, String remarks, char freqType, char discontinued,
			Date modTime, String username, Boolean ispackage, String itemId, Integer routeOfAdmin, Integer days,
			String visitId, Integer orderId, Integer itemFormId, String itemStrength) {
		this.prescriptionId = prescriptionId;
		this.mrNo = mrNo;
		this.prescribedDate = prescribedDate;
		this.type = type;
		this.itemName = itemName;
		this.recurrenceDailyId = recurrenceDailyId;
		this.medicineDosage = medicineDosage;
		this.remarks = remarks;
		this.freqType = freqType;
		this.discontinued = discontinued;
		this.modTime = modTime;
		this.username = username;
		this.ispackage = ispackage;
		this.itemId = itemId;
		this.routeOfAdmin = routeOfAdmin;
		this.days = days;
		this.visitId = visitId;
		this.orderId = orderId;
		this.itemFormId = itemFormId;
		this.itemStrength = itemStrength;
	}

	@Id

	@Column(name = "prescription_id", unique = true, nullable = false)
	public int getPrescriptionId() {
		return this.prescriptionId;
	}

	public void setPrescriptionId(int prescriptionId) {
		this.prescriptionId = prescriptionId;
	}

	@Column(name = "mr_no", nullable = false, length = 15)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "prescribed_date", nullable = false, length = 13)
	public Date getPrescribedDate() {
		return this.prescribedDate;
	}

	public void setPrescribedDate(Date prescribedDate) {
		this.prescribedDate = prescribedDate;
	}

	@Column(name = "type", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "item_name", length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "recurrence_daily_id")
	public Integer getRecurrenceDailyId() {
		return this.recurrenceDailyId;
	}

	public void setRecurrenceDailyId(Integer recurrenceDailyId) {
		this.recurrenceDailyId = recurrenceDailyId;
	}

	@Column(name = "medicine_dosage", length = 30)
	public String getMedicineDosage() {
		return this.medicineDosage;
	}

	public void setMedicineDosage(String medicineDosage) {
		this.medicineDosage = medicineDosage;
	}

	@Column(name = "remarks", length = 2000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "freq_type", nullable = false, length = 1)
	public char getFreqType() {
		return this.freqType;
	}

	public void setFreqType(char freqType) {
		this.freqType = freqType;
	}

	@Column(name = "discontinued", nullable = false, length = 1)
	public char getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(char discontinued) {
		this.discontinued = discontinued;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mod_time", nullable = false, length = 29)
	public Date getModTime() {
		return this.modTime;
	}

	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "ispackage")
	public Boolean getIspackage() {
		return this.ispackage;
	}

	public void setIspackage(Boolean ispackage) {
		this.ispackage = ispackage;
	}

	@Column(name = "item_id", length = 50)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Column(name = "route_of_admin")
	public Integer getRouteOfAdmin() {
		return this.routeOfAdmin;
	}

	public void setRouteOfAdmin(Integer routeOfAdmin) {
		this.routeOfAdmin = routeOfAdmin;
	}

	@Column(name = "days")
	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	@Column(name = "visit_id", length = 15)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Column(name = "order_id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "item_form_id")
	public Integer getItemFormId() {
		return this.itemFormId;
	}

	public void setItemFormId(Integer itemFormId) {
		this.itemFormId = itemFormId;
	}

	@Column(name = "item_strength", length = 50)
	public String getItemStrength() {
		return this.itemStrength;
	}

	public void setItemStrength(String itemStrength) {
		this.itemStrength = itemStrength;
	}

}
