package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UnitsModel generated by hbm2java
 */
@Entity
@Table(name = "units")
public class UnitsModel implements java.io.Serializable {

	private UnitsIdSequence id;

	public UnitsModel() {
	}

	public UnitsModel(UnitsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "units", column = @Column(name = "units", nullable = false, length = 50)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)) })
	public UnitsIdSequence getId() {
		return this.id;
	}

	public void setId(UnitsIdSequence id) {
		this.id = id;
	}

}
