package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserImagesModel generated by hbm2java
 */
@Entity
@Table(name = "user_images")
public class UserImagesModel implements java.io.Serializable {

	private UserImagesIdSequence id;

	public UserImagesModel() {
	}

	public UserImagesModel(UserImagesIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empUsername", column = @Column(name = "emp_username", length = 30)),
			@AttributeOverride(name = "signature", column = @Column(name = "signature")),
			@AttributeOverride(name = "signatureContentType", column = @Column(name = "signature_content_type", length = 200)),
			@AttributeOverride(name = "doctorId", column = @Column(name = "doctor_id", length = 20)) })
	public UserImagesIdSequence getId() {
		return this.id;
	}

	public void setId(UserImagesIdSequence id) {
		this.id = id;
	}

}
