package com.insta.hms.model;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VitalReadingAuditLogModel generated by hbm2java
 */
@Entity
@Table(name = "vital_reading_audit_log")
public class VitalReadingAuditLogModel implements java.io.Serializable {

	private VitalReadingAuditLogIdSequence id;

	public VitalReadingAuditLogModel() {
	}

	public VitalReadingAuditLogModel(VitalReadingAuditLogIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "logId", column = @Column(name = "log_id", nullable = false)),
			@AttributeOverride(name = "vitalReadingId", column = @Column(name = "vital_reading_id")),
			@AttributeOverride(name = "paramId", column = @Column(name = "param_id")),
			@AttributeOverride(name = "paramValue", column = @Column(name = "param_value", length = 30)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 30)),
			@AttributeOverride(name = "modTime", column = @Column(name = "mod_time", nullable = false, length = 29)),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value")),
			@AttributeOverride(name = "operation", column = @Column(name = "operation")),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name")),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value")) })
	public VitalReadingAuditLogIdSequence getId() {
		return this.id;
	}

	public void setId(VitalReadingAuditLogIdSequence id) {
		this.id = id;
	}

}
