package com.insta.hms.mdm.registrationcharges;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegistrationChargesIdSequence generated by hbm2java
 */
@Embeddable
public class RegistrationChargesIdSequence implements java.io.Serializable {

	private String orgId;
	private BigDecimal ipRegCharge;
	private BigDecimal opRegCharge;
	private BigDecimal genRegCharge;
	private BigDecimal regRenewalCharge;
	private BigDecimal mrcharge;
	private BigDecimal ipMlccharge;
	private BigDecimal genRegChargeDiscount;
	private BigDecimal opRegChargeDiscount;
	private BigDecimal regRenewalChargeDiscount;
	private BigDecimal ipRegChargeDiscount;
	private BigDecimal ipMlcchargeDiscount;
	private BigDecimal mrchargeDiscount;
	private String bedType;
	private BigDecimal opMlccharge;
	private BigDecimal opMlcchargeDiscount;
	private String isOverride;

	public RegistrationChargesIdSequence() {
	}

	public RegistrationChargesIdSequence(String orgId, BigDecimal ipRegCharge, BigDecimal opRegCharge, BigDecimal genRegCharge,
			BigDecimal regRenewalCharge, BigDecimal mrcharge, BigDecimal ipMlccharge, BigDecimal genRegChargeDiscount,
			BigDecimal opRegChargeDiscount, BigDecimal regRenewalChargeDiscount, BigDecimal ipRegChargeDiscount,
			BigDecimal ipMlcchargeDiscount, BigDecimal mrchargeDiscount, String bedType, BigDecimal opMlccharge,
			BigDecimal opMlcchargeDiscount) {
		this.orgId = orgId;
		this.ipRegCharge = ipRegCharge;
		this.opRegCharge = opRegCharge;
		this.genRegCharge = genRegCharge;
		this.regRenewalCharge = regRenewalCharge;
		this.mrcharge = mrcharge;
		this.ipMlccharge = ipMlccharge;
		this.genRegChargeDiscount = genRegChargeDiscount;
		this.opRegChargeDiscount = opRegChargeDiscount;
		this.regRenewalChargeDiscount = regRenewalChargeDiscount;
		this.ipRegChargeDiscount = ipRegChargeDiscount;
		this.ipMlcchargeDiscount = ipMlcchargeDiscount;
		this.mrchargeDiscount = mrchargeDiscount;
		this.bedType = bedType;
		this.opMlccharge = opMlccharge;
		this.opMlcchargeDiscount = opMlcchargeDiscount;
	}

	public RegistrationChargesIdSequence(String orgId, BigDecimal ipRegCharge, BigDecimal opRegCharge, BigDecimal genRegCharge,
			BigDecimal regRenewalCharge, BigDecimal mrcharge, BigDecimal ipMlccharge, BigDecimal genRegChargeDiscount,
			BigDecimal opRegChargeDiscount, BigDecimal regRenewalChargeDiscount, BigDecimal ipRegChargeDiscount,
			BigDecimal ipMlcchargeDiscount, BigDecimal mrchargeDiscount, String bedType, BigDecimal opMlccharge,
			BigDecimal opMlcchargeDiscount, String isOverride) {
		this.orgId = orgId;
		this.ipRegCharge = ipRegCharge;
		this.opRegCharge = opRegCharge;
		this.genRegCharge = genRegCharge;
		this.regRenewalCharge = regRenewalCharge;
		this.mrcharge = mrcharge;
		this.ipMlccharge = ipMlccharge;
		this.genRegChargeDiscount = genRegChargeDiscount;
		this.opRegChargeDiscount = opRegChargeDiscount;
		this.regRenewalChargeDiscount = regRenewalChargeDiscount;
		this.ipRegChargeDiscount = ipRegChargeDiscount;
		this.ipMlcchargeDiscount = ipMlcchargeDiscount;
		this.mrchargeDiscount = mrchargeDiscount;
		this.bedType = bedType;
		this.opMlccharge = opMlccharge;
		this.opMlcchargeDiscount = opMlcchargeDiscount;
		this.isOverride = isOverride;
	}

	@Column(name = "org_id", nullable = false, length = 50)
	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "ip_reg_charge", nullable = false, precision = 15)
	public BigDecimal getIpRegCharge() {
		return this.ipRegCharge;
	}

	public void setIpRegCharge(BigDecimal ipRegCharge) {
		this.ipRegCharge = ipRegCharge;
	}

	@Column(name = "op_reg_charge", nullable = false, precision = 15)
	public BigDecimal getOpRegCharge() {
		return this.opRegCharge;
	}

	public void setOpRegCharge(BigDecimal opRegCharge) {
		this.opRegCharge = opRegCharge;
	}

	@Column(name = "gen_reg_charge", nullable = false, precision = 15)
	public BigDecimal getGenRegCharge() {
		return this.genRegCharge;
	}

	public void setGenRegCharge(BigDecimal genRegCharge) {
		this.genRegCharge = genRegCharge;
	}

	@Column(name = "reg_renewal_charge", nullable = false, precision = 15)
	public BigDecimal getRegRenewalCharge() {
		return this.regRenewalCharge;
	}

	public void setRegRenewalCharge(BigDecimal regRenewalCharge) {
		this.regRenewalCharge = regRenewalCharge;
	}

	@Column(name = "mrcharge", nullable = false, precision = 15)
	public BigDecimal getMrcharge() {
		return this.mrcharge;
	}

	public void setMrcharge(BigDecimal mrcharge) {
		this.mrcharge = mrcharge;
	}

	@Column(name = "ip_mlccharge", nullable = false, precision = 15)
	public BigDecimal getIpMlccharge() {
		return this.ipMlccharge;
	}

	public void setIpMlccharge(BigDecimal ipMlccharge) {
		this.ipMlccharge = ipMlccharge;
	}

	@Column(name = "gen_reg_charge_discount", nullable = false, precision = 15)
	public BigDecimal getGenRegChargeDiscount() {
		return this.genRegChargeDiscount;
	}

	public void setGenRegChargeDiscount(BigDecimal genRegChargeDiscount) {
		this.genRegChargeDiscount = genRegChargeDiscount;
	}

	@Column(name = "op_reg_charge_discount", nullable = false, precision = 15)
	public BigDecimal getOpRegChargeDiscount() {
		return this.opRegChargeDiscount;
	}

	public void setOpRegChargeDiscount(BigDecimal opRegChargeDiscount) {
		this.opRegChargeDiscount = opRegChargeDiscount;
	}

	@Column(name = "reg_renewal_charge_discount", nullable = false, precision = 15)
	public BigDecimal getRegRenewalChargeDiscount() {
		return this.regRenewalChargeDiscount;
	}

	public void setRegRenewalChargeDiscount(BigDecimal regRenewalChargeDiscount) {
		this.regRenewalChargeDiscount = regRenewalChargeDiscount;
	}

	@Column(name = "ip_reg_charge_discount", nullable = false, precision = 15)
	public BigDecimal getIpRegChargeDiscount() {
		return this.ipRegChargeDiscount;
	}

	public void setIpRegChargeDiscount(BigDecimal ipRegChargeDiscount) {
		this.ipRegChargeDiscount = ipRegChargeDiscount;
	}

	@Column(name = "ip_mlccharge_discount", nullable = false, precision = 15)
	public BigDecimal getIpMlcchargeDiscount() {
		return this.ipMlcchargeDiscount;
	}

	public void setIpMlcchargeDiscount(BigDecimal ipMlcchargeDiscount) {
		this.ipMlcchargeDiscount = ipMlcchargeDiscount;
	}

	@Column(name = "mrcharge_discount", nullable = false, precision = 15)
	public BigDecimal getMrchargeDiscount() {
		return this.mrchargeDiscount;
	}

	public void setMrchargeDiscount(BigDecimal mrchargeDiscount) {
		this.mrchargeDiscount = mrchargeDiscount;
	}

	@Column(name = "bed_type", nullable = false, length = 50)
	public String getBedType() {
		return this.bedType;
	}

	public void setBedType(String bedType) {
		this.bedType = bedType;
	}

	@Column(name = "op_mlccharge", nullable = false, precision = 15)
	public BigDecimal getOpMlccharge() {
		return this.opMlccharge;
	}

	public void setOpMlccharge(BigDecimal opMlccharge) {
		this.opMlccharge = opMlccharge;
	}

	@Column(name = "op_mlccharge_discount", nullable = false, precision = 15)
	public BigDecimal getOpMlcchargeDiscount() {
		return this.opMlcchargeDiscount;
	}

	public void setOpMlcchargeDiscount(BigDecimal opMlcchargeDiscount) {
		this.opMlcchargeDiscount = opMlcchargeDiscount;
	}

	@Column(name = "is_override", length = 1)
	public String getIsOverride() {
		return this.isOverride;
	}

	public void setIsOverride(String isOverride) {
		this.isOverride = isOverride;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegistrationChargesIdSequence))
			return false;
		RegistrationChargesIdSequence castOther = (RegistrationChargesIdSequence) other;

		return ((this.getOrgId() == castOther.getOrgId()) || (this.getOrgId() != null && castOther.getOrgId() != null
				&& this.getOrgId().equals(castOther.getOrgId())))
				&& ((this.getIpRegCharge() == castOther.getIpRegCharge())
						|| (this.getIpRegCharge() != null && castOther.getIpRegCharge() != null
								&& this.getIpRegCharge().equals(castOther.getIpRegCharge())))
				&& ((this.getOpRegCharge() == castOther.getOpRegCharge())
						|| (this.getOpRegCharge() != null && castOther.getOpRegCharge() != null
								&& this.getOpRegCharge().equals(castOther.getOpRegCharge())))
				&& ((this.getGenRegCharge() == castOther.getGenRegCharge())
						|| (this.getGenRegCharge() != null && castOther.getGenRegCharge() != null
								&& this.getGenRegCharge().equals(castOther.getGenRegCharge())))
				&& ((this.getRegRenewalCharge() == castOther.getRegRenewalCharge())
						|| (this.getRegRenewalCharge() != null && castOther.getRegRenewalCharge() != null
								&& this.getRegRenewalCharge().equals(castOther.getRegRenewalCharge())))
				&& ((this.getMrcharge() == castOther.getMrcharge()) || (this.getMrcharge() != null
						&& castOther.getMrcharge() != null && this.getMrcharge().equals(castOther.getMrcharge())))
				&& ((this.getIpMlccharge() == castOther.getIpMlccharge())
						|| (this.getIpMlccharge() != null && castOther.getIpMlccharge() != null
								&& this.getIpMlccharge().equals(castOther.getIpMlccharge())))
				&& ((this.getGenRegChargeDiscount() == castOther.getGenRegChargeDiscount())
						|| (this.getGenRegChargeDiscount() != null && castOther.getGenRegChargeDiscount() != null
								&& this.getGenRegChargeDiscount().equals(castOther.getGenRegChargeDiscount())))
				&& ((this.getOpRegChargeDiscount() == castOther.getOpRegChargeDiscount())
						|| (this.getOpRegChargeDiscount() != null && castOther.getOpRegChargeDiscount() != null
								&& this.getOpRegChargeDiscount().equals(castOther.getOpRegChargeDiscount())))
				&& ((this.getRegRenewalChargeDiscount() == castOther.getRegRenewalChargeDiscount())
						|| (this.getRegRenewalChargeDiscount() != null
								&& castOther.getRegRenewalChargeDiscount() != null
								&& this.getRegRenewalChargeDiscount().equals(castOther.getRegRenewalChargeDiscount())))
				&& ((this.getIpRegChargeDiscount() == castOther.getIpRegChargeDiscount())
						|| (this.getIpRegChargeDiscount() != null && castOther.getIpRegChargeDiscount() != null
								&& this.getIpRegChargeDiscount().equals(castOther.getIpRegChargeDiscount())))
				&& ((this.getIpMlcchargeDiscount() == castOther.getIpMlcchargeDiscount())
						|| (this.getIpMlcchargeDiscount() != null && castOther.getIpMlcchargeDiscount() != null
								&& this.getIpMlcchargeDiscount().equals(castOther.getIpMlcchargeDiscount())))
				&& ((this.getMrchargeDiscount() == castOther.getMrchargeDiscount())
						|| (this.getMrchargeDiscount() != null && castOther.getMrchargeDiscount() != null
								&& this.getMrchargeDiscount().equals(castOther.getMrchargeDiscount())))
				&& ((this.getBedType() == castOther.getBedType()) || (this.getBedType() != null
						&& castOther.getBedType() != null && this.getBedType().equals(castOther.getBedType())))
				&& ((this.getOpMlccharge() == castOther.getOpMlccharge())
						|| (this.getOpMlccharge() != null && castOther.getOpMlccharge() != null
								&& this.getOpMlccharge().equals(castOther.getOpMlccharge())))
				&& ((this.getOpMlcchargeDiscount() == castOther.getOpMlcchargeDiscount())
						|| (this.getOpMlcchargeDiscount() != null && castOther.getOpMlcchargeDiscount() != null
								&& this.getOpMlcchargeDiscount().equals(castOther.getOpMlcchargeDiscount())))
				&& ((this.getIsOverride() == castOther.getIsOverride())
						|| (this.getIsOverride() != null && castOther.getIsOverride() != null
								&& this.getIsOverride().equals(castOther.getIsOverride())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrgId() == null ? 0 : this.getOrgId().hashCode());
		result = 37 * result + (getIpRegCharge() == null ? 0 : this.getIpRegCharge().hashCode());
		result = 37 * result + (getOpRegCharge() == null ? 0 : this.getOpRegCharge().hashCode());
		result = 37 * result + (getGenRegCharge() == null ? 0 : this.getGenRegCharge().hashCode());
		result = 37 * result + (getRegRenewalCharge() == null ? 0 : this.getRegRenewalCharge().hashCode());
		result = 37 * result + (getMrcharge() == null ? 0 : this.getMrcharge().hashCode());
		result = 37 * result + (getIpMlccharge() == null ? 0 : this.getIpMlccharge().hashCode());
		result = 37 * result + (getGenRegChargeDiscount() == null ? 0 : this.getGenRegChargeDiscount().hashCode());
		result = 37 * result + (getOpRegChargeDiscount() == null ? 0 : this.getOpRegChargeDiscount().hashCode());
		result = 37 * result
				+ (getRegRenewalChargeDiscount() == null ? 0 : this.getRegRenewalChargeDiscount().hashCode());
		result = 37 * result + (getIpRegChargeDiscount() == null ? 0 : this.getIpRegChargeDiscount().hashCode());
		result = 37 * result + (getIpMlcchargeDiscount() == null ? 0 : this.getIpMlcchargeDiscount().hashCode());
		result = 37 * result + (getMrchargeDiscount() == null ? 0 : this.getMrchargeDiscount().hashCode());
		result = 37 * result + (getBedType() == null ? 0 : this.getBedType().hashCode());
		result = 37 * result + (getOpMlccharge() == null ? 0 : this.getOpMlccharge().hashCode());
		result = 37 * result + (getOpMlcchargeDiscount() == null ? 0 : this.getOpMlcchargeDiscount().hashCode());
		result = 37 * result + (getIsOverride() == null ? 0 : this.getIsOverride().hashCode());
		return result;
	}

}
