package com.insta.hms.mdm.operations;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OperationMasterModel generated by hbm2java
 */
@Entity
@Table(name = "operation_master")
public class OperationMasterModel implements java.io.Serializable {

	private String opId;
	private String operationName;
	private String deptId;
	private String operationCode;
	private Character status;
	private Boolean conductionApplicable;
	private String username;
	private Integer serviceSubGroupId;
	private Integer insuranceCategoryId;
	private Character priorAuthRequired;
	private boolean allowRateIncrease;
	private boolean allowRateDecrease;
	private String remarks;
	private Integer kitId;
	private Set operationChargeses = new HashSet(0);
	private Set operationOrgDetailses = new HashSet(0);

	public OperationMasterModel() {
	}

	public OperationMasterModel(String opId, boolean allowRateIncrease, boolean allowRateDecrease) {
		this.opId = opId;
		this.allowRateIncrease = allowRateIncrease;
		this.allowRateDecrease = allowRateDecrease;
	}

	public OperationMasterModel(String opId, String operationName, String deptId, String operationCode, Character status,
			Boolean conductionApplicable, String username, Integer serviceSubGroupId, Integer insuranceCategoryId,
			Character priorAuthRequired, boolean allowRateIncrease, boolean allowRateDecrease, String remarks,
			Integer kitId, Set operationChargeses, Set operationOrgDetailses) {
		this.opId = opId;
		this.operationName = operationName;
		this.deptId = deptId;
		this.operationCode = operationCode;
		this.status = status;
		this.conductionApplicable = conductionApplicable;
		this.username = username;
		this.serviceSubGroupId = serviceSubGroupId;
		this.insuranceCategoryId = insuranceCategoryId;
		this.priorAuthRequired = priorAuthRequired;
		this.allowRateIncrease = allowRateIncrease;
		this.allowRateDecrease = allowRateDecrease;
		this.remarks = remarks;
		this.kitId = kitId;
		this.operationChargeses = operationChargeses;
		this.operationOrgDetailses = operationOrgDetailses;
	}

	@Id

	@Column(name = "op_id", unique = true, nullable = false, length = 10)
	public String getOpId() {
		return this.opId;
	}

	public void setOpId(String opId) {
		this.opId = opId;
	}

	@Column(name = "operation_name", length = 600)
	public String getOperationName() {
		return this.operationName;
	}

	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	@Column(name = "dept_id", length = 100)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "operation_code", length = 50)
	public String getOperationCode() {
		return this.operationCode;
	}

	public void setOperationCode(String operationCode) {
		this.operationCode = operationCode;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "conduction_applicable")
	public Boolean getConductionApplicable() {
		return this.conductionApplicable;
	}

	public void setConductionApplicable(Boolean conductionApplicable) {
		this.conductionApplicable = conductionApplicable;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "service_sub_group_id")
	public Integer getServiceSubGroupId() {
		return this.serviceSubGroupId;
	}

	public void setServiceSubGroupId(Integer serviceSubGroupId) {
		this.serviceSubGroupId = serviceSubGroupId;
	}

	@Column(name = "insurance_category_id")
	public Integer getInsuranceCategoryId() {
		return this.insuranceCategoryId;
	}

	public void setInsuranceCategoryId(Integer insuranceCategoryId) {
		this.insuranceCategoryId = insuranceCategoryId;
	}

	@Column(name = "prior_auth_required", length = 1)
	public Character getPriorAuthRequired() {
		return this.priorAuthRequired;
	}

	public void setPriorAuthRequired(Character priorAuthRequired) {
		this.priorAuthRequired = priorAuthRequired;
	}

	@Column(name = "allow_rate_increase", nullable = false)
	public boolean isAllowRateIncrease() {
		return this.allowRateIncrease;
	}

	public void setAllowRateIncrease(boolean allowRateIncrease) {
		this.allowRateIncrease = allowRateIncrease;
	}

	@Column(name = "allow_rate_decrease", nullable = false)
	public boolean isAllowRateDecrease() {
		return this.allowRateDecrease;
	}

	public void setAllowRateDecrease(boolean allowRateDecrease) {
		this.allowRateDecrease = allowRateDecrease;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "kit_id")
	public Integer getKitId() {
		return this.kitId;
	}

	public void setKitId(Integer kitId) {
		this.kitId = kitId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operationMaster")
	public Set getOperationChargeses() {
		return this.operationChargeses;
	}

	public void setOperationChargeses(Set operationChargeses) {
		this.operationChargeses = operationChargeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operationMaster")
	public Set getOperationOrgDetailses() {
		return this.operationOrgDetailses;
	}

	public void setOperationOrgDetailses(Set operationOrgDetailses) {
		this.operationOrgDetailses = operationOrgDetailses;
	}

}
