package com.insta.hms.extension.payments;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PaymentRulesModel generated by hbm2java
 */
@Entity
@Table(name = "payment_rules", uniqueConstraints = { @UniqueConstraint(columnNames = { "rate_plan", "doctor_category",
		"referrer_category", "prescribed_category", "charge_head", "activity_id", "center_id" }),
		@UniqueConstraint(columnNames = "precedance") })
public class PaymentRulesModel implements java.io.Serializable {

	private int paymentId;
	private String doctorCategory;
	private String referrerCategory;
	private String ratePlan;
	private String chargeHead;
	private String activityId;
	private int precedance;
	private char drPaymentOption;
	private BigDecimal drPaymentValue;
	private char refPaymentOption;
	private BigDecimal refPaymentValue;
	private char hospPaymentOption;
	private BigDecimal hospPaymentValue;
	private String prescribedCategory;
	private String prescPaymentOption;
	private BigDecimal prescPaymentValue;
	private BigDecimal drPkgAmt;
	private String username;
	private String drPaymentExpr;
	private String refPaymentExpr;
	private String prescPaymentExpr;
	private String useDiscountedAmount;
	private String centerId;

	public PaymentRulesModel() {
	}

	public PaymentRulesModel(int paymentId, String doctorCategory, String ratePlan, String chargeHead, int precedance,
			char drPaymentOption, BigDecimal drPaymentValue, char refPaymentOption, BigDecimal refPaymentValue,
			char hospPaymentOption, BigDecimal hospPaymentValue, String prescPaymentOption,
			BigDecimal prescPaymentValue, BigDecimal drPkgAmt, String useDiscountedAmount) {
		this.paymentId = paymentId;
		this.doctorCategory = doctorCategory;
		this.ratePlan = ratePlan;
		this.chargeHead = chargeHead;
		this.precedance = precedance;
		this.drPaymentOption = drPaymentOption;
		this.drPaymentValue = drPaymentValue;
		this.refPaymentOption = refPaymentOption;
		this.refPaymentValue = refPaymentValue;
		this.hospPaymentOption = hospPaymentOption;
		this.hospPaymentValue = hospPaymentValue;
		this.prescPaymentOption = prescPaymentOption;
		this.prescPaymentValue = prescPaymentValue;
		this.drPkgAmt = drPkgAmt;
		this.useDiscountedAmount = useDiscountedAmount;
	}

	public PaymentRulesModel(int paymentId, String doctorCategory, String referrerCategory, String ratePlan,
			String chargeHead, String activityId, int precedance, char drPaymentOption, BigDecimal drPaymentValue,
			char refPaymentOption, BigDecimal refPaymentValue, char hospPaymentOption, BigDecimal hospPaymentValue,
			String prescribedCategory, String prescPaymentOption, BigDecimal prescPaymentValue, BigDecimal drPkgAmt,
			String username, String drPaymentExpr, String refPaymentExpr, String prescPaymentExpr,
			String useDiscountedAmount, String centerId) {
		this.paymentId = paymentId;
		this.doctorCategory = doctorCategory;
		this.referrerCategory = referrerCategory;
		this.ratePlan = ratePlan;
		this.chargeHead = chargeHead;
		this.activityId = activityId;
		this.precedance = precedance;
		this.drPaymentOption = drPaymentOption;
		this.drPaymentValue = drPaymentValue;
		this.refPaymentOption = refPaymentOption;
		this.refPaymentValue = refPaymentValue;
		this.hospPaymentOption = hospPaymentOption;
		this.hospPaymentValue = hospPaymentValue;
		this.prescribedCategory = prescribedCategory;
		this.prescPaymentOption = prescPaymentOption;
		this.prescPaymentValue = prescPaymentValue;
		this.drPkgAmt = drPkgAmt;
		this.username = username;
		this.drPaymentExpr = drPaymentExpr;
		this.refPaymentExpr = refPaymentExpr;
		this.prescPaymentExpr = prescPaymentExpr;
		this.useDiscountedAmount = useDiscountedAmount;
		this.centerId = centerId;
	}

	@Id

	@Column(name = "payment_id", unique = true, nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "doctor_category", nullable = false, length = 10)
	public String getDoctorCategory() {
		return this.doctorCategory;
	}

	public void setDoctorCategory(String doctorCategory) {
		this.doctorCategory = doctorCategory;
	}

	@Column(name = "referrer_category", length = 10)
	public String getReferrerCategory() {
		return this.referrerCategory;
	}

	public void setReferrerCategory(String referrerCategory) {
		this.referrerCategory = referrerCategory;
	}

	@Column(name = "rate_plan", nullable = false, length = 10)
	public String getRatePlan() {
		return this.ratePlan;
	}

	public void setRatePlan(String ratePlan) {
		this.ratePlan = ratePlan;
	}

	@Column(name = "charge_head", nullable = false, length = 10)
	public String getChargeHead() {
		return this.chargeHead;
	}

	public void setChargeHead(String chargeHead) {
		this.chargeHead = chargeHead;
	}

	@Column(name = "activity_id", length = 10)
	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	@Column(name = "precedance", unique = true, nullable = false)
	public int getPrecedance() {
		return this.precedance;
	}

	public void setPrecedance(int precedance) {
		this.precedance = precedance;
	}

	@Column(name = "dr_payment_option", nullable = false, length = 1)
	public char getDrPaymentOption() {
		return this.drPaymentOption;
	}

	public void setDrPaymentOption(char drPaymentOption) {
		this.drPaymentOption = drPaymentOption;
	}

	@Column(name = "dr_payment_value", nullable = false, precision = 15)
	public BigDecimal getDrPaymentValue() {
		return this.drPaymentValue;
	}

	public void setDrPaymentValue(BigDecimal drPaymentValue) {
		this.drPaymentValue = drPaymentValue;
	}

	@Column(name = "ref_payment_option", nullable = false, length = 1)
	public char getRefPaymentOption() {
		return this.refPaymentOption;
	}

	public void setRefPaymentOption(char refPaymentOption) {
		this.refPaymentOption = refPaymentOption;
	}

	@Column(name = "ref_payment_value", nullable = false, precision = 15)
	public BigDecimal getRefPaymentValue() {
		return this.refPaymentValue;
	}

	public void setRefPaymentValue(BigDecimal refPaymentValue) {
		this.refPaymentValue = refPaymentValue;
	}

	@Column(name = "hosp_payment_option", nullable = false, length = 1)
	public char getHospPaymentOption() {
		return this.hospPaymentOption;
	}

	public void setHospPaymentOption(char hospPaymentOption) {
		this.hospPaymentOption = hospPaymentOption;
	}

	@Column(name = "hosp_payment_value", nullable = false, precision = 15)
	public BigDecimal getHospPaymentValue() {
		return this.hospPaymentValue;
	}

	public void setHospPaymentValue(BigDecimal hospPaymentValue) {
		this.hospPaymentValue = hospPaymentValue;
	}

	@Column(name = "prescribed_category", length = 10)
	public String getPrescribedCategory() {
		return this.prescribedCategory;
	}

	public void setPrescribedCategory(String prescribedCategory) {
		this.prescribedCategory = prescribedCategory;
	}

	@Column(name = "presc_payment_option", nullable = false, length = 1)
	public String getPrescPaymentOption() {
		return this.prescPaymentOption;
	}

	public void setPrescPaymentOption(String prescPaymentOption) {
		this.prescPaymentOption = prescPaymentOption;
	}

	@Column(name = "presc_payment_value", nullable = false, precision = 15)
	public BigDecimal getPrescPaymentValue() {
		return this.prescPaymentValue;
	}

	public void setPrescPaymentValue(BigDecimal prescPaymentValue) {
		this.prescPaymentValue = prescPaymentValue;
	}

	@Column(name = "dr_pkg_amt", nullable = false, precision = 15)
	public BigDecimal getDrPkgAmt() {
		return this.drPkgAmt;
	}

	public void setDrPkgAmt(BigDecimal drPkgAmt) {
		this.drPkgAmt = drPkgAmt;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "dr_payment_expr", length = 4000)
	public String getDrPaymentExpr() {
		return this.drPaymentExpr;
	}

	public void setDrPaymentExpr(String drPaymentExpr) {
		this.drPaymentExpr = drPaymentExpr;
	}

	@Column(name = "ref_payment_expr", length = 4000)
	public String getRefPaymentExpr() {
		return this.refPaymentExpr;
	}

	public void setRefPaymentExpr(String refPaymentExpr) {
		this.refPaymentExpr = refPaymentExpr;
	}

	@Column(name = "presc_payment_expr", length = 4000)
	public String getPrescPaymentExpr() {
		return this.prescPaymentExpr;
	}

	public void setPrescPaymentExpr(String prescPaymentExpr) {
		this.prescPaymentExpr = prescPaymentExpr;
	}

	@Column(name = "use_discounted_amount", nullable = false, length = 1)
	public String getUseDiscountedAmount() {
		return this.useDiscountedAmount;
	}

	public void setUseDiscountedAmount(String useDiscountedAmount) {
		this.useDiscountedAmount = useDiscountedAmount;
	}

	@Column(name = "center_id", length = 15)
	public String getCenterId() {
		return this.centerId;
	}

	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

}
