package com.insta.hms.mdm.pharmacyprinttemplate;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StorePrintTemplateModel generated by hbm2java
 */
@Entity
@Table(name = "store_print_template")
public class StorePrintTemplateModel implements java.io.Serializable {

	private StorePrintTemplateIdSequence id;

	public StorePrintTemplateModel() {
	}

	public StorePrintTemplateModel(StorePrintTemplateIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", nullable = false, length = 50)),
			@AttributeOverride(name = "pharmacyTemplateContent", column = @Column(name = "pharmacy_template_content")),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 100)),
			@AttributeOverride(name = "reason", column = @Column(name = "reason", length = 500)),
			@AttributeOverride(name = "templateMode", column = @Column(name = "template_mode", length = 1)) })
	public StorePrintTemplateIdSequence getId() {
		return this.id;
	}

	public void setId(StorePrintTemplateIdSequence id) {
		this.id = id;
	}

}
