package com.insta.hms.integration.insurance.remittance;
// Generated 28 Aug, 2018 12:23:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InsuranceRemittanceActivityDetailsId generated by hbm2java
 */
@Embeddable
public class InsuranceRemittanceActivityDetailsIdSequence implements java.io.Serializable {

  private String activityId;
  private Integer remittanceId;
  private String claimId;

  public InsuranceRemittanceActivityDetailsIdSequence() {
  }

  public InsuranceRemittanceActivityDetailsIdSequence(int remittanceId, String claimId) {
    this.remittanceId = remittanceId;
    this.claimId = claimId;
  }

  public InsuranceRemittanceActivityDetailsIdSequence(String activityId, int remittanceId,
      String claimId) {
    this.activityId = activityId;
    this.remittanceId = remittanceId;
    this.claimId = claimId;
  }

  @Column(name = "activity_id", length = 50)
  public String getActivityId() {
    return this.activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  @Column(name = "remittance_id", nullable = false)
  public Integer getRemittanceId() {
    return this.remittanceId;
  }

  public void setRemittanceId(int remittanceId) {
    this.remittanceId = remittanceId;
  }

  @Column(name = "claim_id", nullable = false, length = 50)
  public String getClaimId() {
    return this.claimId;
  }

  public void setClaimId(String claimId) {
    this.claimId = claimId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof InsuranceRemittanceActivityDetailsIdSequence))
      return false;
    InsuranceRemittanceActivityDetailsIdSequence castOther = (InsuranceRemittanceActivityDetailsIdSequence) other;

    return (((this.getActivityId() == castOther.getActivityId())
        || (this.getActivityId() != null && castOther.getActivityId() != null
            && this.getActivityId().equals(castOther.getActivityId())))
        && (this.getRemittanceId() == castOther.getRemittanceId())
        && ((this.getClaimId() == castOther.getClaimId())
            || (this.getClaimId() != null && castOther.getClaimId() != null
                && this.getClaimId().equals(castOther.getClaimId()))));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getActivityId() == null ? 0 : this.getActivityId().hashCode());
    result = 37 * result + (getRemittanceId() == null ? 0 : this.getRemittanceId().hashCode());
    result = 37 * result + (getClaimId() == null ? 0 : this.getClaimId().hashCode());
    return result;
  }

}
