package com.insta.hms.integration.insurance.remittance;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InsuranceRemittanceDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "insurance_remittance_details")
public class InsuranceRemittanceDetailsModel implements java.io.Serializable {

	private InsuranceRemittanceDetailsIdSequence id;

	public InsuranceRemittanceDetailsModel() {
	}

	public InsuranceRemittanceDetailsModel(InsuranceRemittanceDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "claimId", column = @Column(name = "claim_id")),
			@AttributeOverride(name = "settlementDate", column = @Column(name = "settlement_date", length = 29)),
			@AttributeOverride(name = "payerId", column = @Column(name = "payer_id", length = 100)),
			@AttributeOverride(name = "paymentReference", column = @Column(name = "payment_reference", length = 100)),
			@AttributeOverride(name = "providerId", column = @Column(name = "provider_id", length = 50)),
			@AttributeOverride(name = "remittanceId", column = @Column(name = "remittance_id", nullable = false)),
			@AttributeOverride(name = "error", column = @Column(name = "error")),
			@AttributeOverride(name = "resubmissionType", column = @Column(name = "resubmission_type", length = 20)),
			@AttributeOverride(name = "resubmissionComments", column = @Column(name = "resubmission_comments")) })
	public InsuranceRemittanceDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(InsuranceRemittanceDetailsIdSequence id) {
		this.id = id;
	}

}
