package com.insta.hms.mdm.commoncharges;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/** CommonChargesMasterModel generated by hbm2java. */
@Entity
@Table(name = "common_charges_master")
public class CommonChargesMasterModel implements java.io.Serializable {

  private CommonChargesMasterIdSequence id;

  public CommonChargesMasterModel() {}

  public CommonChargesMasterModel(CommonChargesMasterIdSequence id) {
    this.id = id;
  }

  @EmbeddedId
  @AttributeOverrides({
      @AttributeOverride(
        name = "chargeName", 
        column = @Column(name = "charge_name", length = 50)
      ),
      @AttributeOverride(
        name = "chargeType", 
        column = @Column(name = "charge_type", length = 10)
      ),
      @AttributeOverride(
        name = "chargeGroup", 
        column = @Column(name = "charge_group", length = 10)
      ),
      @AttributeOverride(
        name = "charge", 
        column = @Column(name = "charge", precision = 15)
      ),
      @AttributeOverride(
        name = "status", 
        column = @Column(name = "status", length = 1)
      ),
      @AttributeOverride(
        name = "serviceSubGroupId",
        column = @Column(name = "service_sub_group_id")),
      @AttributeOverride(
        name = "otherchargeCode",
        column = @Column(name = "othercharge_code", length = 50)
      ),
      @AttributeOverride(
        name = "insuranceCategoryId",
        column = @Column(name = "insurance_category_id")
      ),
      @AttributeOverride(
        name = "allowRateIncrease",
        column = @Column(name = "allow_rate_increase", nullable = false)
      ),
      @AttributeOverride(
        name = "allowRateDecrease",
        column = @Column(name = "allow_rate_decrease", nullable = false)
      )
  })
  public CommonChargesMasterIdSequence getId() {
    return this.id;
  }

  public void setId(CommonChargesMasterIdSequence id) {
    this.id = id;
  }
}
