FORMAT: 1B
HOST: http://localhost:8080/instahms/

# Insta Patient Issues API

API documentation for Patient Issue screen.

## PATIENT ISSUE [/patientissues/]

### GET PATIENT ISSUE SCREEN [GET /inventory/patientissues/add.json?store_id=0]

+ Response 200 (application/json)

        {  
          "order_kits":[  
            {  
              "order_kit_name":"test",
              "order_kit_id":1
            },
            {  
              "order_kit_name":"test2",
              "order_kit_id":2
            }
          ],
          "discount_plans":[  
            {  
              "applicable_to_id_subgroup":"",
              "applicable_to_id":"ANAOPE",
              "discount_plan_detail_id":2,
              "discount_value":12.00,
              "priority":1,
              "discount_type":"P",
              "discount_plan_id":2,
              "applicable_type":"C"
            },
            {  
              "applicable_to_id_subgroup":"",
              "applicable_to_id":"3",
              "discount_plan_detail_id":1,
              "discount_value":30.00,
              "priority":1,
              "discount_type":"P",
              "discount_plan_id":1,
              "applicable_type":"N"
            },
            {  
              "applicable_to_id_subgroup":"",
              "applicable_to_id":"7",
              "discount_plan_detail_id":3,
              "discount_value":12.00,
              "priority":1,
              "discount_type":"P",
              "discount_plan_id":3,
              "applicable_type":"N"
            },
            {  
              "applicable_to_id_subgroup":"",
              "applicable_to_id":"CSTAX",
              "discount_plan_detail_id":4,
              "discount_value":11.00,
              "priority":1,
              "discount_type":"P",
              "discount_plan_id":4,
              "applicable_type":"C"
            },
            {  
              "applicable_to_id_subgroup":"",
              "applicable_to_id":"7",
              "discount_plan_detail_id":5,
              "discount_value":11.00,
              "priority":1,
              "discount_type":"P",
              "discount_plan_id":5,
              "applicable_type":"N"
            }
          ],
          "operation_details_id":"1",
          "store_id":"10",
          "generic_prefs":{  
              "points_earning_points":1,
              "after_decimal_digits":2,
              "points_earning_amt":100.00,
              "sample_no_generation":"P",
              "warn_expiry":30,
              "username":"",
              "email_bill_printer":1,
              "domain_name":"",
              "sampleflow_required":"Y",
              "aggregate_amt_on_remittance":"N",
              "default_voucher_print":"summary",
              "luxary_tax_applicable_on":"B",
              "ip_cases_across_doctors":"Y",
              "allow_all_cons_types_in_reg":"N",
              "stock_inc":"M",
              "pharma_return_restricted":"N",
              "cess_applicable":"Y",
              "default_po_print_template":"PO New",
              "allow_cons_qty_incr":"N",
              "appointment_name_order":"FML",
              "allow_consumable_stock_negative":"Y",
              "upload_limit_in_mb":10,
              "operation_apllicable_for":"b",
              "max_collection_centers_count":null,
              "show_hosp_amts_pharmasales":"N",
              "qty_default_to_issue_unit":"N",
              "allow_decimals_for_qty":"Y",
              "hospital_tin":"",
              "surgery_name_required":"O",
              "critical_color_code":"#FFB6B9",
              "default_printer_for_bill_now":1,
              "enable_sms":"Y",
              "validate_cost_price":"Y",
              "indent_approval_by":"I",
              "improbable_color_code":"#E18EF3",
              "auth_required":false,
              "bill_service_charge_percent":0.00,
              "currency_symbol":"Rs",
              "no_of_credit_debit_card_digits":10,
              "fixed_ot_charges":"N",
              "fin_year_end_month":3,
              "scheduler_generate_order":"Y",
              "check_insu_card_exp_in_sales":"Y",
              "cfd_max_count":4,
              "doctors_custom_field1":"",
              "doctors_custom_field2":"",
              "host_name":"mail1.insta.lan",
              "hospital_mail_id":"customer-support@instahealthsolutions.com",
              "doctors_custom_field5":"",
              "mobile_number_validation":"Y",
              "doctors_custom_field3":"",
              "restrict_inactive_visits":"B",
              "doctors_custom_field4":"",
              "obsolete_eclaim_xml_schema":"",
              "fp_authentication_url":"",
              "package_size":1,
              "menu_background_color":"",
              "show_central_excise_duty":"Y",
              "receipt_refund_print_default":"BUILTIN_HTML",
              "obsolete_pharmacy_defalut_vat_rate":5,
              "slida_mailslot_path":"",
              "sample_collection_print_type":"SB",
              "pharmacy_schedule_h_alert":"Y",
              "hijricalendar":"Y",
              "blood_exp":90,
              "barcode_for_item":"N",
              "obsolete_default_diagnosis_code_type":"",
              "is_return_against_grnno":false,
              "default_prescription_print_template":"Customized Case Sheet Print Template",
              "enable_nestloop":"Y",
              "autogenerate_labno":"Y",
              "pharmacy_patient_type":"R",
              "po_approval_reqd_more_than_amt":0,
              "auto_close_nocharge_op_bills":"A",
              "go_live_date":"07-12-2009",
              "default_prescribe_doctor":"Y",
              "consultation_reopen_time_limit":10000,
              "auto_close_indented_casefiles":"N",
              "mobile_starting_pattern":"50,52,54,55,56,58",
              "force_remarks_po_item_reject":"Y",
              "stock_negative_sale":"D",
              "gen_token_for_rad":"Y",
              "autogenerate_sampleid":"Y",
              "sale_expiry":"N",
              "enable_force_selection_for_mrno_search":"N",
              "auto_mail_po_to_sup":false,
              "points_redemption_rate":1.20,
              "allow_zero_claim_amount_for_op":"Y",
              "op_one_presc_doc":"Y",
              "deposit_cheque_realization_flow":"Y",
              "return_validity":4,
              "max_centers_inc_default":25,
              "allow_only_indent_based_issue":"N",
              "receive_transfer_indent":"Y",
              "protocol":"smtp",
              "issue_to_dept_only":"N",
              "user_name_in_bill_print":"Y",
              "abnormal_color_code":"#FFF3B6",
              "consultation_validity_units":"D",
              "port_no":25,
              "returns_against_specific_supplier":"N",
              "shafafiya_preauth_user_id_obsolete":null,
              "stock_entry_agnst_do":"N",
              "calendar_start_day":0,
              "sms_username":".instahms@smscountry.net",
              "patient_name_match_distance":0,
              "dental_chart":"Y",
              "currency_format":"Lakhs",
              "allow_zero_claim_amount_for_ip":"Y",
              "default_consultation_print_template":"BUILTIN_HTML",
              "claim_service_tax":10.30,
              "sales_returns_print_type":"R",
              "email_bill_now_template":"CUSTOM-Web Based Bill Now Print Template",
              "hospital_name":"Davita Nephrolife India Pvt. Ltd.",
              "pharma_allow_cp_sale":"N",
              "po_to_be_validated":"Y",
              "google_analytics_key":"",
              "diag_images":"T,P,G",
              "apply_supplier_tax_rules":false,
              "gen_token_for_lab":"Y",
              "default_prescription_web_printer":4,
              "pharma_auto_roundoff":"Y",
              "prescribing_doctor_required":"N",
              "bill_now_print_default":"BILL-DET-ALL",
              "op_consultation_edit_across_doctors":"Y",
              "shafafiya_user_id_obsolete":null,
              "sales_print_items":"BILLPRESC",
              "default_emr_print_template":"BUILTIN_HTML",
              "allow_bill_reopen":"Y",
              "hosp_uses_dynamic_addresses":"N",
              "default_dental_cons_print_template":"BUILTIN_HTML",
              "default_prescription_web_template":"Web Based Prescription Template",
              "package_uom":"Numbers",
              "pharmacy_sale_margin_in_per":0.00,
              "deposit_receipt_print_default":"BUILTIN_HTML",
              "issue_uom":"Numbers",
              "default_printer_for_bill_later":1,
              "daily_checkpoint2":"20:00:00",
              "daily_checkpoint1":"08:00:00",
              "separator_type":"",
              "shafafiya_preauth_active_obsolete":"N",
              "obsolete_vat_type":"C",
              "fin_year_start_month":4,
              "procurement_expiry_days":0,
              "bill_later_print_default":"CUSTOM-Detail Bill Print(Merge)",
              "mod_username":"InstaAdmin",
              "sample_assertion":"N",
              "procurement_tax_label":"G",
              "validate_diagnosis_codification":"Y",
              "password":"",
              "signature_device_ip":"",
              "se_with_po":"N",
              "auto_close_visit":"P",
              "shafafiya_preauth_password_obsolete":null,
              "shafafiya_password_obsolete":null,
              "pbm_price_threshold":0.00,
              "corporate_insurance":"N",
              "show_tests_in_emr":"A",
              "vat_applicable":"Y",
              "emr_url_date":"D",
              "diag_report_print_center":"col",
              "dhpo_facility_user_id_obsolete":null,
              "obsolete_rate_plan_for_non_insured_bill":"ORG0029",
              "hospital_pan":"",
              "allow_bill_now_insurance":"Y",
              "dhpo_facility_password_obsolete":null,
              "seperate_pharmacy_credit_bill":"N",
              "whole":"Rupees",
              "shafafiya_pbm_active_obsolete":"N",
              "default_grn_print_template":"GRN Print Template",
              "auto_close_claims_with_difference":0.00,
              "obsolete_prescriptions_by_generics":"N",
              "expired_items_procurement":"A",
              "normal_color_code":"#FFFFFF",
              "default_bill_later_creditsales":"Y",
              "deposit_avalibility":"B",
              "force_sub_group_selection":"N",
              "pac_validity_days":30,
              "max_dial_machine_count":null,
              "mobile_length_pattern":"9",
              "tooth_numbering_system":"F",
              "allow_decimals_in_qty_for_issues":"Y",
              "max_active_hosp_users":999,
              "bill_cancellation_requires_approval":"N",
              "service_name_required":"O",
              "hospital_address":"",
              "independent_generation_of_sample_id":"N",
              "use_smart_card":"Y",
              "decimal":"Paise",
              "allow_cross_center_indents":"Y",
              "email_bill_later_template":"CUSTOM-Web Based Bill Later Print Template",
              "prescription_uses_stores":"Y",
              "billing_bed_type_for_op":"GENERAL",
              "hospital_service_regn_no":"",
              "registration_on_arrival":"Y",
              "apply_rateplan_discount":"N",
              "nurse_staff_ward_assignments_applicable":"N"
            }
        }

### GET FIND PATIENT [GET /inventory/patientissues/patientsearch.json?query=MR013700&method=findPatientsJson&searchType=undefined&status=active&visitType=all]

+ Response 200 (application/json)

        {  
          "patients":[  
            {  
              "doctor_name":"DR.KIRAN",
              "age_in":"Y",
              "previous_visit_id":null,
              "government_identifier":null,
              "status":"A",
              "patient_name":"Neha",
              "salutation_name":"Ms.",
              "dept_name":"ANAESTHESIOLOGY",
              "patient_full_name":"Neha A A",
              "patient_phone_country_code":null,
              "patient_gender":"F",
              "visit_id":"OP121762",
              "age":46,
              "op_type":"M",
              "patient_phone":"",
              "last_name":"A",
              "visit_reg_date":1524729015154,
              "patient_id":"OP121762",
              "mr_no":"MR013700"
            }
          ]
        }
        
### GET PATIENT DETAILS [GET /inventory/patientissues/getpatientdetails.json?visit_id=0&store_id=0]

+ Response 200 (application/json)

        {  
          "patient_details":{  
            "insurance":[  
              {  
                "discount_plan_id":1,
                "policy_holder_name":"",
                "visit_max_copay_percentage":null,
                "per_diem_code":null,
                "prior_auth_mode_id":0,
                "priority":1,
                "visit_type":"o",
                "use_perdiem":"N",
                "policy_validity_start":null,
                "patient_relationship":"",
                "visit_limit":null,
                "insurance_approval":null,
                "episode_limit":null,
                "visit_per_day_limit":null,
                "status":"A",
                "episode_deductible":null,
                "visit_deductible":null,
                "tpa_name":"BAJAJ ALLIANZ's",
                "visit_copay_percentage":10.00,
                "patient_policy_id":3641,
                "prior_auth_id":"",
                "doc_id":null,
                "visit_id":"OP193866",
                "codification_status":" ",
                "policy_validity_end":null,
                "insurance_co_name":"Default Insurance Company",
                "mr_no":"MR117565",
                "plan_name":"Default Insurance Company Plan",
                "drg_code":"",
                "episode_copay_percentage":null,
                "policy_number":"",
                "plan_id":41,
                "plan_limit":null,
                "insurance_co":"ICM00011",
                "plan_type_id":144,
                "utilization_amount":null,
                "insurance_rules_doc_name":null,
                "use_drg":"N",
                "codification_remarks":"",
                "plan_exclusions":"",
                "sponsor_id":"TPAID0002",
                "employer_name":null,
                "member_id":"",
                "episode_max_copay_percentage":null,
                "plan_type_name":"Default Plan Type",
                "codified_by":"",
                "insurance_plan_details":[  
                  {  
                    "patient_amount_cap":0.00,
                    "insurance_plan_details_id":723,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "insurance_category_id":2,
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "insurance_plan_details_id":727,
                    "patient_amount_cap":0.00,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "insurance_category_id":4,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":0.00,
                    "insurance_plan_details_id":729,
                    "category_payable":"N",
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "insurance_category_id":5,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":0.00,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "insurance_plan_details_id":733,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "insurance_category_id":7,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "insurance_plan_details_id":725,
                    "patient_amount_cap":0.00,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "insurance_category_id":3,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "insurance_category_id":-1,
                    "patient_amount_cap":0.00,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "insurance_plan_details_id":737,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":0.00,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "insurance_plan_details_id":721,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o",
                    "insurance_category_id":1
                  },
                  {  
                    "patient_amount_cap":0.00,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "insurance_plan_details_id":731,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "insurance_category_id":6,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":0.00,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "per_treatment_limit":0.00,
                    "patient_percent":0.00,
                    "insurance_category_id":8,
                    "insurance_plan_details_id":735,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "insurance_category_id":-2,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_plan_details_id":837,
                    "plan_id":41,
                    "username":"InstaAdmin",
                    "category_prior_auth_required":" ",
                    "patient_type":"o"
                  }
                ],
                "plan_notes":"",
                "discount_plan_name":"Management",
                "sponsor_type":"I",
                "patient_id":"OP193866"
              },
              {  
                "discount_plan_id":null,
                "visit_max_copay_percentage":null,
                "policy_holder_name":"",
                "per_diem_code":null,
                "prior_auth_mode_id":0,
                "priority":2,
                "visit_type":"o",
                "use_perdiem":"N",
                "patient_relationship":"",
                "policy_validity_start":null,
                "insurance_approval":null,
                "visit_limit":null,
                "episode_limit":null,
                "visit_per_day_limit":null,
                "status":"A",
                "visit_deductible":null,
                "episode_deductible":null,
                "tpa_name":"TATA AIG",
                "visit_copay_percentage":10.00,
                "patient_policy_id":3642,
                "prior_auth_id":"",
                "doc_id":null,
                "visit_id":"OP193866",
                "codification_status":" ",
                "policy_validity_end":null,
                "insurance_co_name":"Maharatra Bank",
                "mr_no":"MR117565",
                "plan_name":"issurence",
                "drg_code":"",
                "episode_copay_percentage":null,
                "policy_number":"",
                "plan_id":1,
                "insurance_co":"ICM00003",
                "plan_type_id":133,
                "plan_limit":null,
                "utilization_amount":null,
                "insurance_rules_doc_name":"",
                "use_drg":"N",
                "codification_remarks":"",
                "plan_exclusions":null,
                "sponsor_id":"TPAID0038",
                "employer_name":null,
                "episode_max_copay_percentage":null,
                "member_id":"",
                "plan_type_name":"health plan",
                "codified_by":"",
                "insurance_plan_details":[  
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "insurance_category_id":-1,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_plan_details_id":10,
                    "plan_id":1,
                    "username":"InstaAdmin",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "plan_id":1,
                    "insurance_plan_details_id":11,
                    "username":"InstaAdmin",
                    "patient_type":"o",
                    "insurance_category_id":1
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_plan_details_id":12,
                    "plan_id":1,
                    "username":"InstaAdmin",
                    "insurance_category_id":2,
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "plan_id":1,
                    "insurance_category_id":3,
                    "username":"InstaAdmin",
                    "insurance_plan_details_id":13,
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_category_id":4,
                    "plan_id":1,
                    "insurance_plan_details_id":14,
                    "username":"InstaAdmin",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "insurance_plan_details_id":15,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_category_id":5,
                    "plan_id":1,
                    "username":"InstaAdmin",
                    "patient_type":"o"
                  },
                  {  
                    "insurance_plan_details_id":16,
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_category_id":6,
                    "plan_id":1,
                    "username":"InstaAdmin",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "insurance_plan_details_id":17,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_category_id":7,
                    "plan_id":1,
                    "username":"InstaAdmin",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "insurance_plan_details_id":18,
                    "category_prior_auth_required":null,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "insurance_category_id":8,
                    "plan_id":1,
                    "username":"InstaAdmin",
                    "patient_type":"o"
                  },
                  {  
                    "patient_amount_cap":null,
                    "per_treatment_limit":null,
                    "category_prior_auth_required":null,
                    "insurance_category_id":-2,
                    "patient_amount_per_category":0.00,
                    "patient_amount":0.00,
                    "category_payable":"Y",
                    "patient_percent":0.00,
                    "plan_id":1,
                    "insurance_plan_details_id":757,
                    "username":"InstaAdmin",
                    "patient_type":"o"
                  }
                ],
                "discount_plan_name":null,
                "plan_notes":null,
                "sponsor_type":"I",
                "patient_id":"OP193866"
              }
            ],
            "patient":{  
              "file_status":"U",
              "patient_city":"CT0637",
              "raise_case_file_indent":"Y",
              "passport_validity":null,
              "family_id":null,
              "nationality_name":"United Arab Emirates",
              "dateofbirth":null,
              "state_name":"UAE",
              "custom_list6_value":null,
              "patient_care_oftext_country_code":"",
              "country_name":"United Arab Emirates",
              "patient_category_id":1,
              "patient_phone2":null,
              "patient_care_oftext":null,
              "passport_issue_country":null,
              "email_id":null,
              "no_allergies":null,
              "current_age":23,
              "middle_name":"",
              "portal_access":"false",
              "photo_size":null,
              "custom_list3_value":null,
              "old_reg_auto_generate":"Y",
              "center_name":"Default Center",
              "mod_time":1525690293671,
              "visit_id":"OP193866",
              "last_name":"",
              "food_allergies":"",
              "city_name":"UAE",
              "next_of_kin_relation":null,
              "conditional_custom_field4":null,
              "conditional_custom_field3":null,
              "government_identifier":"84457ASAH",
              "conditional_custom_field2":null,
              "conditional_custom_field1":null,
              "reg_date":"2018-05-07",
              "dead_on_arrival":null,
              "identifier_id":5,
              "conditional_custom_field5":null,
              "patient_careof_address":null,
              "med_allergies":"",
              "visit_status":"A",
              "oldmrno":null,
              "first_visit_reg_date":"2018-05-07",
              "patient_name":"TestII",
              "reference_docto_id":null,
              "vip_status":null,
              "indented":"N",
              "original_mr_no":"",
              "clinical_field2":null,
              "statename":"UAE",
              "custom_list8_value":null,
              "clinical_field3":null,
              "patient_consultation_info":null,
              "salutation":"SALU0002",
              "clinical_field1":null,
              "patient_category":null,
              "mobile_access":"false",
              "age_text":"23y",
              "other_allergies":"",
              "category_expiry_date":null,
              "custom_list9_value":null,
              "expected_dob":"1994-11-07",
              "age":23,
              "visit_type":"o",
              "visa_validity":null,
              "death_date":null,
              "custom_field3":null,
              "custom_field2":null,
              "custom_field1":null,
              "relation":"",
              "custom_field7":null,
              "custom_field6":null,
              "custom_field5":null,
              "custom_field4":null,
              "custom_list4_value":null,
              "nationality_id":"CM0255",
              "primary_sponsor_id":"TPAID0002",
              "passport_no":null,
              "custom_field9":null,
              "custom_field8":null,
              "country":"CM0255",
              "patient_phone_country_code":"+91",
              "category_name":"General",
              "patient_gender":"M",
              "patient_category_custom_field":null,
              "mr_no":"MR117565",
              "casefile_no":"CS000341",
              "previous_visit_id":null,
              "patient_photo_available":"N",
              "custom_list5_value":null,
              "issued_to":"ANAESTHESIOLOGY",
              "current_agein":"Y",
              "remarks":null,
              "middle_name2":"",
              "patient_area":"",
              "name_local_language":null,
              "patient_phone":"+918123400921",
              "agein":"Y",
              "patient_address":"",
              "custom_field16":null,
              "custom_field15":null,
              "patient_state":"ST0039",
              "custom_field18":null,
              "custom_field17":null,
              "custom_field19":null,
              "sms_for_vaccination":"N",
              "custom_list1_value":null,
              "mobile_password":null,
              "patient_source_category":null,
              "custom_field10":null,
              "custom_field11":null,
              "custom_field12":null,
              "custom_field13":null,
              "custom_list2_value":null,
              "custom_field14":null,
              "cityname":"UAE",
              "center_id":0,
              "death_reason_id":null,
              "death_time":null,
              "custom_list7_value":null,
              "full_name":"Mr. TestII"
            },
            "visit":{  
              "admitting_diagnosis_code":null,
              "patient_city":"CT0637",
              "doctor_mail_id":"",
              "sec_patient_national_relation":null,
              "sec_employee_name":null,
              "family_id":null,
              "sec_citizen_name":null,
              "custom_list6_value":null,
              "patient_category_id":1,
              "tpa_pincode":"560035",
              "sec_sponsor_type":"I",
              "patient_care_oftext":null,
              "refdoctorname":"",
              "salutation_id":"SALU0002",
              "govt_type_label":"p- Govt ID",
              "email_id":null,
              "no_allergies":null,
              "primary_diagnosis_code":null,
              "main_visit_id":"OP193866",
              "token_no":null,
              "middle_name":"",
              "revisit":"N",
              "insurance_co_address":"",
              "visit_id":"OP193866",
              "last_name":"",
              "reg_charge_accepted":"Y",
              "bills":[  
                {  
                  "total_receipts":0.00,
                  "visit_id":"OP193866",
                  "mr_no":"MR117565",
                  "deposit_set_off":0.00,
                  "total_amount":291.00,
                  "bill_rate_plan_id":"ORG0001",
                  "bill_no":"BNA246980",
                  "status":"A",
                  "is_tpa":true,
                  "account_group":1,
                  "payment_status":"U",
                  "open_date":"2018-05-07",
                  "primary_sponsor_id":"TPAID0002",
                  "approval_amount":0.00
                },
                {  
                  "open_date":"2018-05-11",
                  "total_receipts":0.00,
                  "mr_no":"MR117565",
                  "bill_rate_plan_id":"ORG0001",
                  "status":"A",
                  "payment_status":"U",
                  "account_group":1,
                  "primary_sponsor_id":"TPAID0002",
                  "visit_id":"OP193866",
                  "bill_no":"BNA246981",
                  "deposit_set_off":0.00,
                  "is_tpa":true,
                  "total_amount":96.16,
                  "approval_amount":0.00
                }
              ],
              "food_allergies":"",
              "sec_policy_number":"",
              "center_code":"Default Center",
              "discharge_remarks":null,
              "government_identifier":"84457ASAH",
              "discharged_by":null,
              "discharge_date":null,
              "unit_id":null,
              "dead_on_arrival":null,
              "death_reason":null,
              "sec_policy_validity_start":null,
              "sec_patient_relationship":"",
              "admitted_dept":"DEP0002",
              "secondary_insurance_approval":null,
              "analysis_of_complaint":"",
              "alloc_bed_name":null,
              "secondary_diagnosis_description":"",
              "bed_type":"GENERAL",
              "mlc_remarks":null,
              "sec_national_id":null,
              "center_address":"",
              "oldmrno":null,
              "national_sponsor_id":null,
              "patient_name":"TestII",
              "vip_status":null,
              "indented":"N",
              "dept_name":"DEP0002",
              "member_id":"",
              "primary_plan_type_label":"Network / Plan Type",
              "custom_list8_value":null,
              "patient_consultation_info":null,
              "insurance_id":null,
              "sec_patient_corporate_relation":null,
              "patient_category":1,
              "sec_tpa_name":"TATA AIG",
              "patient_corporate_relation":null,
              "discharge_flag":"",
              "age_text":"23y",
              "ward_id":"",
              "doctor":"DOC0547",
              "corporate_sponsor_id":null,
              "qualification":"",
              "alloc_ward_name":null,
              "discharge_doctor_id":null,
              "custom_list9_value":null,
              "expected_dob":"1994-11-07",
              "reg_ward_name":null,
              "patient_relationship":"",
              "tpa_phone_no":"080-65656567",
              "visa_validity":null,
              "death_date":null,
              "sec_member_id":"",
              "relation":"",
              "secondary_plan_type_label":"Network / Plan Type",
              "tpa_name":"BAJAJ ALLIANZ's",
              "nationality_id":"CM0255",
              "police_stn":null,
              "passport_no":null,
              "country":"CM0255",
              "tpa_country":"INDIA",
              "sec_insurance_co_name":"Maharatra Bank",
              "patient_policy_id":0,
              "sec_employee_id":null,
              "primary_insurance_co":"ICM00011",
              "patient_category_custom_field":null,
              "doc_id":null,
              "insurance_co_name":"Default Insurance Company",
              "cons_time":"",
              "org_name":"GENERAL",
              "discharge_finalized_time":null,
              "verify_finger_print":"N",
              "patient_photo_available":"N",
              "custom_list5_value":null,
              "insurance_co_tin_number":null,
              "policy_number":"",
              "remarks":null,
              "primary_member_id_label":"Member ID",
              "plan_id":41,
              "patient_area":"",
              "discharge_time":null,
              "name_local_language":null,
              "patient_phone":"+918123400921",
              "use_drg":"N",
              "disch_date_for_disch_summary":null,
              "complaint":null,
              "alloc_bed_type":null,
              "patient_address":"",
              "tpa_state":"KARNATAKA",
              "custom_field16":null,
              "patient_state":"ST0039",
              "custom_field15":null,
              "custom_field18":null,
              "custom_field17":null,
              "signatory_username":null,
              "custom_field19":null,
              "custom_list1_value":null,
              "sec_tpa_tin_number":"",
              "org_id":"ORG0001",
              "secondary_insurance_co":"ICM00003",
              "primary_diagnosis_description":null,
              "custom_field10":null,
              "custom_field11":null,
              "health_authority":"Default",
              "custom_field12":null,
              "custom_field13":null,
              "custom_field14":null,
              "custom_list2_value":null,
              "patient_id":"OP193866",
              "sec_policy_holder_name":"",
              "secondary_approval_limit":null,
              "custom_list7_value":null,
              "file_status":"U",
              "sec_corporate_sponsor_id":null,
              "primary_insurance_approval":null,
              "passport_validity":null,
              "nationality_name":"United Arab Emirates",
              "dateofbirth":null,
              "citizen_name":null,
              "state_name":"UAE",
              "country_name":"United Arab Emirates",
              "employee_name":null,
              "passport_issue_country":null,
              "prior_auth_mode_id":0,
              "sec_insurance_co_address":"ere",
              "ins_prior_auth_id":null,
              "use_perdiem":"N",
              "discharge_type":null,
              "addnl_phone":null,
              "portal_access":false,
              "custom_list3_value":null,
              "discharge_doc_id":null,
              "user_name":"InstaAdmin",
              "center_name":"Default Center",
              "policy_validity_end":null,
              "secondary_sponsor_id":"TPAID0038",
              "require_pbm_authorization":"N",
              "doctor_name":" VINCENT",
              "next_of_kin_relation":null,
              "city_name":"UAE",
              "doctor_type":"CONSULTANT",
              "conditional_custom_field4":null,
              "conditional_custom_field3":null,
              "patient_national_relation":null,
              "conditional_custom_field2":null,
              "conditional_custom_field1":null,
              "mlc_status":null,
              "established_type":"N",
              "reg_date":"2018-05-07",
              "bill_and_payment_status":{  
                "visit_id":"OP193866",
                "total_receipts":0.00,
                "bill_status_ok":false,
                "total_amount":387.16,
                "credit_bill_exists":true,
                "approval_amount":0.00,
                "payment_ok":false
              },
              "admitting_diagnosis_description":null,
              "collection_center_id":-1,
              "mlc_type":null,
              "store_rate_plan_id":null,
              "tpa_tin_number":"",
              "identifier_id":5,
              "conditional_custom_field5":null,
              "specialization":"Anaesthetist",
              "patient_careof_address":null,
              "med_allergies":"",
              "national_id":null,
              "reference_docto_id":null,
              "mlc_no":null,
              "discharge_finalized_user":"",
              "tpa_address":"BANGALORE",
              "plan_type_name":"Default Plan Type",
              "center_contact_phone":"2323232",
              "original_mr_no":"",
              "disch_time_for_disch_summary":null,
              "plan_notes":"",
              "clinical_field2":null,
              "sec_insurance_co_tin_number":null,
              "op_type":"M",
              "statename":"UAE",
              "clinical_field3":null,
              "salutation":"Mr.",
              "patient_mod_time":1525690293671,
              "clinical_field1":null,
              "sec_national_sponsor_id":null,
              "collection_center":"In House",
              "visit_custom_field5":null,
              "prior_auth_mode_name":null,
              "visit_custom_field4":null,
              "visit_custom_field7":null,
              "visit_custom_field6":null,
              "bed_end_date":null,
              "visit_custom_field1":null,
              "discharge_finalized_date":null,
              "visit_custom_field3":null,
              "visit_custom_field2":null,
              "doctor_license_number":"",
              "discharge_format":null,
              "policy_holder_name":"",
              "visit_custom_field9":null,
              "other_allergies":"",
              "visit_custom_field8":null,
              "category_expiry_date":null,
              "per_diem_code":null,
              "bed_start_date":null,
              "age":23,
              "visit_type":"o",
              "policy_validity_start":null,
              "employee_id":null,
              "op_type_name":"Main Visit",
              "custom_field3":null,
              "status":"A",
              "custom_field2":null,
              "custom_field1":null,
              "custom_field7":null,
              "certificate_status":null,
              "secondary_member_id_label":"Member ID",
              "reg_time":"16:21:33",
              "category_id":144,
              "custom_field6":null,
              "accident_place":null,
              "main_visit_primary_insurance_approval":null,
              "main_visit_secondary_insurance_approval":null,
              "docs_download_passcode":585359,
              "custom_field5":null,
              "custom_field4":null,
              "custom_list4_value":null,
              "primary_sponsor_id":"TPAID0002",
              "bill_type":"C",
              "custom_field9":null,
              "tpa_city":"BANGALORE",
              "custom_field8":null,
              "doctor_mobile":"",
              "prior_auth_id":"",
              "patient_category_name":"General",
              "doctor_address":"Unity Hospital Mangalore\r\n   \r\n   \r\n   \r\n   \r\n   ",
              "category_name":"General",
              "patient_gender":"M",
              "codification_status":"P",
              "mr_no":"MR117565",
              "plan_name":"Default Insurance Company Plan",
              "casefile_no":"CS000341",
              "drg_code":null,
              "previous_visit_id":null,
              "issued_to":"ANAESTHESIOLOGY",
              "sec_policy_validity_end":null,
              "center_tin_number":null,
              "tpa_mobile_no":"",
              "admitted_dept_name":"ANAESTHESIOLOGY",
              "agein":"Y",
              "primary_approval_limit":null,
              "plan_exclusions":"",
              "res_phone":"",
              "first_bill_for_visit":"BNA246980",
              "patient_source_category":null,
              "registration_no":"",
              "sec_plan_name":"issurence",
              "clinic_phone":"",
              "sponsor_type":"I",
              "cons_date":"",
              "cityname":"UAE",
              "visit_custom_list2":null,
              "center_id":0,
              "unit_name":null,
              "death_time":null,
              "visit_custom_list1":null,
              "full_name":"Mr. TestII"
            }
          }
        }
        
### GET ITEM LIST [GET /inventory/patientissues/getmedicinesinstock.json?ts=45466&hosp=cen&issueType=CR&includeConsignmentStock=Y&storeId=0]

+ Response 200 (application/json)

        [  
          {  
            "item_code":null,
            "package_uom":"Numbers",
            "item_barcode_id":null,
            "medicine_id":1122,
            "cust_item_code_with_name":"WATER FOR INJ10ML",
            "issue_base_unit":1,
            "cust_item_code":null,
            "issue_units":"Numbers",
            "medicine_name":"WATER FOR INJ10ML"
          },
          {  
            "item_code":null,
            "package_uom":"STRIPS-10",
            "item_barcode_id":null,
            "medicine_id":2758,
            "cust_item_code_with_name":"KETOALFA TAB",
            "issue_base_unit":10.00,
            "cust_item_code":null,
            "issue_units":"1",
            "medicine_name":"KETOALFA TAB"
          }
        ]

### GET ITEM BATCH DETAILS [GET /inventory/patientissues/getitembatchdetails.json?store_id=0&medicine_id=35466]

+ Response 200 (application/json)

        [  
          {  
            "control_type_id":1,
            "item_batch_id":146302,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"dfvkjdfvkdf",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":144143,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":430.00,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"1212221sd",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146316,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"81234009211",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146572,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"dvfveve",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146314,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"12323112",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146276,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"kdfjvfdkjbdf",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146595,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"ffgbfgbfgbfgbgf",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146519,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":30,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"3434r34r34",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146310,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":50.00,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"321212",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146518,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"rifherifue",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146283,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"rinrgenrge",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146522,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fregerger",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146597,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":2788,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"81210999923",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146303,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"812109",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146521,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10.00,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"referfe",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146315,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"8123400921",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146307,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10.00,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"ffg34r",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146517,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":8710,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1669833000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"r33",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146290,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"erergrege",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146592,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":630,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fevevev",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146278,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"ererer",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146286,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fdfbdf",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146573,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"ererer3434t3",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146559,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":100,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"ewkjewfwe",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146309,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":60,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"123321",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146282,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":1,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"erreg233",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146526,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":1000,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"erkle8394785",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146593,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"12efcdkjsdvsk",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146263,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":50,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"34ferfefer",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146599,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":50,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fkjvnriutrn",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146596,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":994,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"rjerjgejrn",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146558,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":50,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"erfkjernrjke",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146591,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":250,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"dfkvjnkdfjvndfj",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146273,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"ergegerg",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146603,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"212313",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146288,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":3550.00,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fdvfbfg",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146261,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"433g4",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146297,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"ejhbjherg",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146523,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":90.00,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"erreergeerge",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146274,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"djvhbdfvjhdf",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146301,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":10,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fdvkfdnvjkd",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146594,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":2016988200000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fjvjfgfg",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146590,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":100,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"fdbgbfgbfg",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146281,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":1,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"erverger",
            "medicine_name":"irs_debit_note"
          },
          {  
            "control_type_id":1,
            "item_batch_id":146520,
            "issue_type":"CONSUMABLE",
            "package_uom":"Numbers-10",
            "item_barcode_id":"ITM00024",
            "category_id":152,
            "qty":20,
            "issue_units":"Numbers",
            "billable":true,
            "exp_dt":1701369000000,
            "consignment_stock":false,
            "dept_id":0,
            "package_type":"",
            "identification":"B",
            "control_type_name":"Normal",
            "medicine_id":35466,
            "issue_base_unit":10,
            "batch_no":"3igiu45gihu45",
            "medicine_name":"irs_debit_note"
          }
        ]
        
### GET ITEM AMOUNTS [GET /inventory/patientissues/getitemamounts.json?store_id=0&medicine_id=12323&item_batch_id=1201&visit_id=OP12321&discount_per=10&amount=120&issue_type=I]
        
+ Response 200 (application/json)

        {
            "amount_details":{  
                "mrp":120,
                "original_mrp":120,
                "unit_mrp":12,
                "discount_per":10,
                "discount_amt":10
            },
            "tax_details":{
                "net_amount":120,
                "tax_basis":"CB"
                "tax_map": {
                    {
                        "item_group_name":"GST",
                        "item_group_id":2,
                        "item_subgroup_name":"SGST",
                        "item_subgroup_id":13,
                        "tax_per":2.5,
                        "tax_amt":2.5
                    },
                    {
                        "item_group_name":"GST",
                        "item_group_id":2,
                        "item_subgroup_name":"CGST",
                        "item_subgroup_id":14,
                        "tax_per":2.5,
                        "tax_amt":2.5
                    }
                }
            }
        }
        
### POST ISSUE DETAILS [POST /inventory/patientissues/saveissuedetails.json]

+ Request (application/json)
        
        {
            "patient_issue_main":{
                "issued_to" : "IP044286",
                "dept_from" : 1,
                "user_type" : "Patient",
                "reference" : "ISSUED ON 26/10/11",
                "bill_no" : "BP1232323"
            },
            "patient_issue_details":[  
              {  
                "medicine_id" : 42352,
                "batch_no" : "ACD12232",
                "orig_rate" : 120,
                "act_rate" : 12,
                "discount" : 10,
                "amount": 120,
                "insurance_category_id": 12,
                "item_batch_id": 10001,
                "pkg_mrp": 120,
                "pri_inc_claim_amt": 0,
                "sec_inc_claim_amt": 0,
                "qty": 10,
                "hdeleted" : "true",
                "itemorkit" : "true",
                "is_consignment_stock" : "true",
                "gatepass" : "true",
                "item_unit" : "1",
                "issue_pkg_size" : "12",
                "dispense_status" : "F",
                "patient_indent_no" : "PI122323"
              },
              {  
                "medicine_id" : 42351,
                "batch_no" : "ACD12223",
                "orig_rate" : 120,
                "act_rate" : 12,
                "discount" : 10,
                "amount": 120,
                "insurance_category_id": 12,
                "item_batch_id": 10001,
                "pkg_mrp": 120,
                "pri_inc_claim_amt": 0,
                "sec_inc_claim_amt": 0,
                "qty": 10,
                "hdeleted" : "true",
                "itemorkit" : "true",
                "is_consignment_stock" : "true",
                "gatepass" : "true",
                "item_unit" : "1",
                "issue_pkg_size" : "12",
                "dispense_status" : "F",
                "patient_indent_no" : "PI122323"
              }
            ]
        }

+ Response 200 (application/json)
        
        {
            "status":"Successfully issued items to patient"
        }
