FORMAT: 1A
HOST: http://localhost:8080/instahms

# Insta-Session-Security-APIs

API for exposure of selected session and access control attributes.

## Session API [/session.json]

### List Exposed Session Attributes [GET]

+ Response 200 (application/json)

        {  
            "centerId":0,
            "sesHospitalId":"cen",
            "roleId":1,
            "roleName":"InstaAdmin",
            "userId":"InstaAdmin",
            "centerName":"Default Center",
            "billing_counter": "Billing Counter",
            "billing_counter_id": "CNT007"
        }

## Security API [/security.json]

### List Exposed Access Control Attributes [GET]

+ Response 200 (application/json)

        {  
            "groupAvlblMap":{  
              "grp_print_templates":"Y",
              "grp_doctor_consultation":"Y",
              "grp_ward_activities":"N",
              "grp_dietary":"N",
              "grp_stores_procurement":"Y",
              "grp_payments":"Y",
              "grp_opthalmology":"N",
              "grp_adv_ot_services":"Y",
              "grp_consultation_reports":"Y",
              "grp_ward_activities_reports":"Y",
              "grp_eclaim_erx":"N",
              "grp_billing":"Y",
              "grp_radiology":"Y",
              "grp_out_patient_select":"Y",
              "grp_laboratory_reports":"Y",
              "grp_transportation":"N",
              "grp_linen_reports":"N",
              "grp_patient_package_reports":"Y",
              "grp_transportation_reports":"N",
              "grp_medical_records":"Y",
              "grp_store_sales_reports":"Y",
              "grp_billing_prefs":"Y",
              "grp_hospital_billing_masters":"Y",
              "grp_blood_reports":"Y",
              "grp_patient_demography_reports":"Y",
              "grp_service_reports":"Y",
              "grp_adv_packages":"Y",
              "grp_scheduler_reports":"Y",
              "grp_dialysis":"Y",
              "grp_dental_masters":"Y",
              "grp_ins_ext":"Y",
              "grp_ot_reports":"Y",
              "grp_master_reports":"Y",
              "grp_stores_sales_issues":"Y",
              "grp_dashboard_statistics_reports":"Y",
              "grp_insurance_reports":"Y",
              "grp_eclaim_preauth":"N",
              "grp_fixed_asset_mgmt":"N",
              "grp_messaging_masters":"Y",
              "grp_eclaim_pbm":"N",
              "grp_store_mgmt_reports":"Y",
              "grp_common":"Y",
              "grp_stores_management":"Y",
              "grp_pharmacy_masters":"Y",
              "grp_bloodbank_masters":"Y",
              "grp_patient_feedback":"Y",
              "grp_registration":"Y",
              "grp_financial_reports":"Y",
              "grp_complaints_log":"Y",
              "grp_clinical_reports":"Y",
              "grp_ot_services":"Y",
              "grp_dietary_reports":"N",
              "grp_hospital_admin_masters":"Y",
              "grp_dialysis_reports":"Y",
              "grp_blood_bank":"Y",
              "grp_patientfeedback_reports":"Y",
              "grp_store_procure_reports":"Y",
              "grp_dental_reports":"Y",
              "grp_clinical_data":"Y",
              "grp_duty_roster":"N",
              "grp_fav_reports":"Y",
              "grp_new_ui":"N",
              "grp_discharge_summary":"N",
              "grp_patient_search":"Y",
              "grp_insta_subscriptions":"N",
              "grp_linen":"N",
              "grp_network_financial_reports":"N",
              "grp_hospital_templates":"Y",
              "grp_mrd_reports":"Y",
              "grp_scheduler":"Y",
              "grp_ipservices":"Y",
              "grp_hospital_prefs":"Y",
              "grp_roster_reports":"N",
              "grp_general_masters":"Y",
              "grp_services":"Y",
              "grp_billing_reports":"Y",
              "grp_custom_reports":"Y",
              "grp_diagnostics":"Y",
              "grp_resource_mgmt_reports":"N",
              "grp_ivf_reports":"N",
              "grp_cssd":"N",
              "grp_insurance":"Y",
              "grp_bed_reports":"Y",
              "grp_ivf":"N"
            },
            "actionRightsMap":{  
              "bed_close":"A",
              "edit_receipt_amounts":"A",
              "allow_new_registration":"A",
              "reopen_consultation_after_time_limit":"A",
              "allow_cancel_test":"A",
              "allow_backdated_app":"A",
              "edit_custom_fields":"A",
              "usr_or_counter_day_book_access":"N",
              "initiate_discharge":"A",
              "add_edit_scheduler_rights":"N",
              "allow_discount_plans_in_bill":"N",
              "edit_bill":"A",
              "view_ceed_response_comments":"N",
              "allow_ratedecrease":"A",
              "patient_category_change":"A",
              "reg_charges_app":"A",
              "dishcharge_close":"A",
              "allow_backdate":"A",
              "view_general_rates":"A",
              "direct_stock_entry":"N",
              "clinical_discharge":"A",
              "cancel_test_any_time":"A",
              "edit_patient_header":"A",
              "allow_dyna_package_include_exclude":"N",
              "change_max_costprice":"N",
              "show_other_center_patients":"N",
              "validate_test_results":"A",
              "edit_first_name":"A",
              "show_avbl_qty":"N",
              "amend_test_results":"N",
              "pbm_prescription_finalize":"N",
              "set_charged_bed_type":"A",
              "addtobill_charges":"A",
              "allow_print_report_visit_wise":"N",
              "allow_denial_acceptance":"N",
              "package_approval":"A",
              "allow_edit_bill_open_date":"N",
              "allow_pharmacy_item_return_after_validity_days":"N",
              "allow_discount":"A",
              "allow_receipt_backdate":"A",
              "reopen_codification":"A",
              "new_bill_for_order_screen":"A",
              "erx_consultation_access":"N",
              "allow_rateincrease":"A",
              "allow_credit_bill_later":"A",
              "cancel_scheduler_appointment":"A",
              "amend_score_card_values":"N",
              "allow_retail_credit_sales":"N",
              "create_bill_for_closed_visit":"A",
              "sign_off_lab_reports":"A",
              "allow_edit_dyna_package":"N",
              "cancel_elements_in_bill":"A",
              "view_all_rates":"A",
              "revert_signoff":"N",
              "cancel_bill":"A",
              "allow_delete_patient_doc":"N",
              "bill_reopen":"A",
              "allow_dynamic_copay_change":"N",
              "allow_refund":"A",
              "allow_preauth_prescription_edit":"N",
              "allow_retail_sales":"N"
           },
            "urlRightsMap":{  
              "mas_strength_unit":"A",
              "mas_recurrence_daily_master":"A",
              "doctor_order_print":"A",
              "rep_vital_measurement_builder":"A",
              "mas_blbag":"A",
              "survey_patient_responses":"A",
              "account_xml_import_export_log":"A",
              "pharma_view_grns":"A",
              "rep_trans_rev":"A",
              "bills_backup":"A",
              "change_billtype":"A",
              "mas_foreign_currency":"A",
              "general_message_send":"A",
              "mas_system_messages":"A",
              "consult_token_display_prefs":"N",
              "clinical_data_lab_results_master":"A",
              "test_documents_print":"A",
              "mas_common_charges":"A",
              "ins_generic_print":"A",
              "survey_record_patient_response":"A",
              "rep_network_bill_charge_builder":"N",
              "mas_insurance_cat":"A",
              "mas_ins_sponsor":"A",
              "pharma_sale_pending_bills":"A",
              "rep_store_purchase_details":"A",
              "rad_schedules_search":"A",
              "conduct_operation":"N",
              "admission_request_diagnosis_audit_log":"A",
              "bill_remittance":"A",
              "insurance_history":"N",
              "per_diem_codes_charges_audit_log":"A",
              "dental_consultations_print":"A",
              "preauth_presc_attach_file":"N",
              "lab_incoming_bill_list_print":"A",
              "mas_drg_codes":"A",
              "discharge_summary":"N",
              "transaction_approval":"N",
              "mas_printer_definition":"A",
              "approve_sponsors_approval":"A",
              "charge_head":"A",
              "rad_test_documents":"A",
              "triage_allergy_audit_log":"A",
              "stores_patient_indent_add":"A",
              "fav_rpt_dashbd":"A",
              "mas_insurance_item_cat":"A",
              "mas_fixed_assets":"N",
              "stores_validate_po":"A",
              "rep_store_sales_vat_report":"A",
              "rep_clinical_outcome":"A",
              "mas_tpa_center_association":"A",
              "ope_scheduler":"A",
              "mas_equipment":"A",
              "mas_med_cat":"A",
              "mas_medicines_prescribed":"A",
              "mas_form_components":"A",
              "patient_customfields":"A",
              "lab_prescribe_test":"A",
              "stores_audit_log":"A",
              "email_report_config":"A",
              "rep_pharmacy_stock_chk_point":"A",
              "patient_progress":"A",
              "adt":"A",
              "ivf_pre_cycle":"N",
              "cancel_appointments":"N",
              "mas_sample_barcode_template":"A",
              "mas_sam_collection":"A",
              "ph_receipts":"A",
              "Scheduler_Surgery_Appointment":"A",
              "stores_rate_plan_mas":"A",
              "ph_stock_movement":"A",
              "mas_icd_codes":"A",
              "bill_print":"A",
              "rad_unfinished_tests":"A",
              "mas_fav_rpt_dashbd":"A",
              "mas_region":"A",
              "service_sub_group":"A",
              "deposit_receipts":"A",
              "store_stock_consumption_new":"A",
              "Scheduler_Services_Appointment":"A",
              "insurance_claim_change_logs":"N",
              "mas_reg_charges_upload":"A",
              "usr_role_pagestats":"A",
              "reg_generic_docs":"A",
              "stores_indent":"A",
              "cat_resource_scheduler":"A",
              "rad_signedoff_report_list":"A",
              "service_docs":"A",
              "rep_bill_adj_builder":"A",
              "stores_user_indent":"A",
              "complaints_log_report":"A",
              "ipf_allergy_audit_log":"A",
              "stores_view_patient_issues":"A",
              "operations_pending_list":"N",
              "mas_insurance_comp":"A",
              "mas_shift_master":"N",
              "pharma_view_store_item_batch_details":"A",
              "po_audit_log":"A",
              "mas_insurance_company_tpa":"A",
              "mas_scheduler_message_configure":"A",
              "consolidated_sponsor_receipts":"A",
              "net_fav_rpt_dashbd":"N",
              "patient_inventory_return":"A",
              "ot_consumables":"A",
              "stores_indent_receive":"A",
              "mas_center_suppliers":"A",
              "stores_patient_indent_add_return":"A",
              "order":"A",
              "rep_bill_charge_adj_builder":"A",
              "mas_sections":"A",
              "dietary_daily_meals_report":"N",
              "doctor_order_audit_log":"A",
              "doc_scheduler":"A",
              "rep_clinical_lab":"A",
              "std_notification":"A",
              "donor_details_builder":"N",
              "reward_points":"A",
              "ip_preferences":"A",
              "cancel_pescription":"A",
              "pay_paymentscreen_combined":"A",
              "dialysis_post_sessions":"A",
              "patient_dental_supplies":"A",
              "user_inventory_return":"A",
              "mas_dyna_package_rule":"A",
              "op_out_patient":"A",
              "mrd_indent_close":"A",
              "operation_detailed_screen":"A",
              "mas_encounter_type":"A",
              "mas_order_kit":"A",
              "ambulance_services_rep_builder":"N",
              "get_dialysisorder_charge_claims":"A",
              "patient_dental_supplies_print":"A",
              "doc_appointments":"N",
              "change_visit_tpa":"A",
              "visit_summary":"A",
              "diag_fav_rpt_dashbd":"A",
              "stores_transfer_indent":"A",
              "dialysis_sessions_summary":"A",
              "pay_paymentscreen_ip":"A",
              "bill_email":"A",
              "rep_patient_packages_builder":"A",
              "pay_doctor":"A",
              "mas_generic_images":"A",
              "pharma_direct_stock_entry":"A",
              "sales_purchases_acc_prefixes":"A",
              "mas_prescription_label_template":"A",
              "mas_blood_comp":"A",
              "mas_diagnosis_status":"A",
              "mas_system_gen_sections":"A",
              "bill_fav_rpt_dashbd":"A",
              "ins_generic_image":"N",
              "grp_canteen":"N",
              "mas_medicines_issue_rates":"A",
              "patient_docket":"A",
              "mas_roster_resource_type_master":"N",
              "luxury_tax_rep_builder":"A",
              "rad_equipment_qa":"A",
              "vital_cons_form_audit_log":"A",
              "rep_collection_detailed_builder":"A",
              "patientfeedback_rep":"A",
              "ins_upload_docs":"N",
              "op_patient_docs":"A",
              "mas_collection_barcode_template":"A",
              "ph_purchase_rep_builder":"A",
              "po_builder":"A",
              "operations_audit_log":"A",
              "create_sponsor_credit_note":"A",
              "insurance_claim":"N",
              "view_work_order":"N",
              "insurance_claim_reconciliation":"A",
              "conduct_or_add_operation_doc":"A",
              "pharma_view_stock_adj":"A",
              "rep_reward_points":"A",
              "ip_bed_details":"A",
              "Scheduler_Tests_Appointment":"A",
              "mas_cities":"A",
              "mas_reports_cen_app":"A",
              "ivf_history":"N",
              "mas_diag_depts":"A",
              "ivf_daily_treatment":"N",
              "clinical_data_lab_results":"A",
              "diet_generic_document":"A",
              "patient_generic_form_list":"A",
              "initial_assessment_print":"A",
              "pharma_item_credit_bill":"A",
              "genf_diagnosis_audit_log":"A",
              "get_ot_management_screen":"A",
              "tpapreauth_templates":"N",
              "scheduler_generic_resource_master":"A",
              "complaints_gen_audit_log":"A",
              "rep_pharmacy_stock_catg_chk_point":"A",
              "mas_dialysis_prep":"A",
              "stores_patient_indent_edit":"A",
              "account_head":"A",
              "mas_service_templates":"A",
              "mas_discount_plan_center_ass":"A",
              "patient_dental_quotation_print":"A",
              "complaints_rep_builder":"N",
              "mas_generic_classification_names":"A",
              "mas_payment_mode":"A",
              "contracts":"N",
              "mas_doctors":"A",
              "pharma_pending_sales_print":"A",
              "mas_doctors_cen_app":"A",
              "clini_fav_rpt_dashbd":"A",
              "mas_scheduled_export_prefs":"A",
              "mas_item_form":"A",
              "mas_reg_prefs":"A",
              "tooth_surface_material_master":"A",
              "rep_pharmacy_bonus_items":"A",
              "dialysis_bill_audit_log":"A",
              "ph_stocktransfer_rep_builder":"A",
              "store_mg_fav_rpt_dashbd":"A",
              "usr_userdashboard":"A",
              "fin_fav_rpt_dashbd":"A",
              "preauth_requests":"N",
              "vital_form":"A",
              "mas_stock_adj_reason":"A",
              "patient_sponsors_approval":"A",
              "deposits_realization":"A",
              "ot_record_print":"A",
              "pay_paymentscreen_op":"A",
              "mas_center_outhouses":"A",
              "ambulance_service_list":"N",
              "donor_registry":"N",
              "intra_dialysis_builder":"A",
              "master_vaccine":"A",
              "mas_wards_beds":"A",
              "rep_ip_list_print":"A",
              "mas_transfer_hospitals":"A",
              "lab_test_documents_list":"A",
              "pharma_view_items_stock_level_list":"A",
              "mas_doctors_detail":"A",
              "slida_action":"N",
              "reg_general":"A",
              "sales_abc_blder":"A",
              "diag_builder":"A",
              "mas_package_category_master":"A",
              "doctor_order_report_builder":"A",
              "mas_ref_doctors_app":"A",
              "mas_patient_cat":"A",
              "mas_diag_test_list":"A",
              "patient_docs_audit_log":"A",
              "maintenance_schedule":"N",
              "emr_screen":"A",
              "rep_dialysis_frequency":"A",
              "dyna_package_category_limits_audit_log":"A",
              "ph_sale_item_rep_builder":"A",
              "rad_test_documents_list":"A",
              "mlc_generic_docs":"A",
              "service_sub_group_upload":"A",
              "complaints_log":"A",
              "lab_unfinished_tests_search":"A",
              "contracts_list":"N",
              "mas_test_tat_master":"A",
              "req_blood_donor":"A",
              "ph_indvl_stock_builder":"A",
              "rep_rate_master_print":"A",
              "stores_item_rates_mas":"A",
              "vital_gen_form_audit_log":"A",
              "mas_pbm_observations":"A",
              "ip_outstand_csv_report":"A",
              "rep_pharmacy_surplus_stock":"A",
              "reg_registration":"A",
              "pharma_sales":"A",
              "maint_activity_rep_builder":"N",
              "lab_schedules_list":"A",
              "gen_audit_log":"A",
              "mas_location":"A",
              "vaccination_info":"A",
              "ip_outstand_report":"A",
              "cssd_surgery_kit_avbl":"N",
              "lab_test_documents":"A",
              "dental_supplies_report_builder":"A",
              "paymentrule_audit_log":"A",
              "pres_lead_time_builder":"A",
              "mrd_file_issue":"A",
              "rep_pharmacy_tax":"A",
              "diag_rev_builder":"A",
              "mrd_fav_rpt_dashbd":"A",
              "mas_mlc_templates":"A",
              "mas_patient_header_templates":"A",
              "mas_reg_charges":"A",
              "ot_record":"A",
              "donor_component_search":"A",
              "edit_member_id":"A",
              "mas_sam_sources":"A",
              "visit_details_search":"A",
              "ip_beddetails":"A",
              "mas_claim_template":"N",
              "sponsor_procedure_master":"A",
              "reg_re_admit":"A",
              "cssd_sterile_stock_transfer":"N",
              "mas_payment_rule":"A",
              "fp_service_verify":"N",
              "blood_request_builder":"A",
              "op_case_form_template":"A",
              "today_resource_scheduler":"A",
              "mas_ph_ret_doc":"A",
              "mas_store_item_control_type":"A",
              "mas_general_message_configure":"A",
              "store_item_master_builder":"A",
              "rad_incoming_sample_reg":"A",
              "emr_screen_trendreport":"A",
              "lab_pending_samples":"A",
              "insurance_claim_submission":"A",
              "radio_prescribe_test":"A",
              "mas_diag_template":"A",
              "ip_ipservices_alt":"A",
              "patient_inventory_issue":"A",
              "dialysis_builder":"A",
              "mas_scheduler_message_type":"A",
              "icd_report":"A",
              "stores_process_indent":"A",
              "stores_patient_indent_view":"A",
              "ph_stock_adj_rep_builder":"A",
              "lab_test_reconduction":"A",
              "reg_blood_donor":"A",
              "vital_tri_form_audit_log":"A",
              "complaints_tri_audit_log":"A",
              "mas_bill_label":"A",
              "lab_transfer_sample_barcode":"A",
              "op_case_form":"A",
              "transport_fav_rpt_dashbd":"N",
              "reg_export_data":"A",
              "mas_services":"A",
              "mas_bank":"A",
              "mas_dept":"A",
              "mas_manf":"A",
              "ivf_sessions":"N",
              "indent_item_builder":"A",
              "receipts":"A",
              "pharma_view_supp_returns":"A",
              "mas_ph_po_template":"A",
              "reward_points_ledger":"A",
              "rep_patientstats_table_builder":"A",
              "sr_scanned_reports":"N",
              "op_ip_conversion":"A",
              "pat_discharge":"N",
              "adv_pkg_patient_packages_list":"A",
              "ip_registration":"A",
              "stores_view_patient_returns":"A",
              "medicine_route":"A",
              "credit_bill_collection":"A",
              "mas_message_category":"A",
              "mas_supplier_contract_item_rates":"A",
              "consult_charge":"A",
              "rep_outgoing_test_details":"A",
              "rep_visit_details_builder":"A",
              "pharma_estimate":"A",
              "ins_fav_rpt_dashbd":"A",
              "dial_prescriptions_audit_log":"A",
              "pharma_view_stock_trans":"A",
              "mas_discount_plan":"A",
              "mas_common_print_templates":"A",
              "mas_deposit_templates":"A",
              "pre_auth_forms_print":"A",
              "consult_charge_upload":"A",
              "edit_visit_details":"A",
              "pharma_returns":"A",
              "ot_schedule_rep_builder":"A",
              "bed_linen_current_usage_rep_builder":"N",
              "iss_blood_donor":"A",
              "mas_equipment_upload":"A",
              "mas_govt_type_id":"A",
              "diag_incoming_sample_reg":"A",
              "triage_audit_log":"A",
              "payment_details_builder":"A",
              "req_blbag":"A",
              "channeling_source":"A",
              "mas_pass_prefs":"A",
              "ip_bedshift":"A",
              "lab_manage_reports":"A",
              "consul_fav_rpt_dashbd":"A",
              "ivf_treatment_cycle_builder":"N",
              "erx_presc_list":"N",
              "pharma_retail_sale_pending_bills":"A",
              "mas_ot":"A",
              "cssd_ot_stock_consumption":"N",
              "insta_subscriptions":"N",
              "acc_voucher_types":"A",
              "get_planned_operations_list":"A",
              "mas_payment_category":"A",
              "lab_select_outhouse":"A",
              "autopost_payments":"A",
              "pharma_view_supp_returns_db":"A",
              "erx_request":"N",
              "visit_emr_screen":"A",
              "stores_view_pur_det":"A",
              "rep_ipstats":"A",
              "mas_print_templates":"A",
              "mas_dental_supplier_master":"A",
              "archive_notification":"A",
              "rad_manage_reports":"A",
              "st_in_out_reg_blder":"A",
              "patient_pending_prescriptions":"A",
              "stores_view_po":"A",
              "stores_amend_po":"A",
              "store_stock_consumption_list":"A",
              "mas_states":"A",
              "daybook_builder":"A",
              "mas_dial_machine":"A",
              "statistics":"A",
              "ope_week_scheduler":"A",
              "mas_supplier_rate_contracts_center_ass":"A",
              "rep_icd_codification":"A",
              "radiology_arrivals":"A",
              "pharma_sale_edit_bill":"A",
              "my_messages":"A",
              "custom_rpt_list":"A",
              "sch_fav_rpt_dashbd":"A",
              "insurance_plan_details_audit_log":"A",
              "reg_admission_request":"A",
              "mas_ins_tpas":"A",
              "mas_salutation":"A",
              "rep_progressive_test_details":"A",
              "vital_ia_form_audit_log":"A",
              "mas_packages":"A",
              "blood_transfusions":"A",
              "patient_duplicate_report":"A",
              "insurance_plan_main_audit_log":"A",
              "ip_ipservice_print":"A",
              "pay_reversal":"A",
              "pat_fav_rpt_dashbd":"A",
              "mas_ot_templates":"A",
              "preauth_patient_diagnosis_audit_log":"N",
              "dis_blood_donor":"A",
              "mas_ph_template":"A",
              "ot_fav_rpt_dashbd":"A",
              "mas_diag_templates":"A",
              "mas_supplier_rate_contracts":"A",
              "lab_transfer_sample_manual":"A",
              "change_visit_org":"A",
              "rep_pharmacy_purchase_vat_report":"A",
              "dietary_master_print":"A",
              "ip_diet_prescribe":"A",
              "service_subtask_builder":"A",
              "mas_supported_codes":"A",
              "mas_gen_pref":"A",
              "ins_newcase":"N",
              "dietary_templates":"N",
              "stores_po_approval":"A",
              "services_audit_log":"A",
              "partogram_form":"A",
              "erx_approval":"N",
              "rep_payment_consolidated_builder":"A",
              "rep_karnataka_sales_tax":"A",
              "patient_deposits":"A",
              "mas_dial_access_sites":"A",
              "ip_ipservices":"A",
              "ipf_diagnosis_audit_log":"A",
              "pay_ref_doctor":"A",
              "diet_fav_rpt_dashbd":"N",
              "mas_dial_ratings":"A",
              "mas_serv_dept":"A",
              "rep_presc_det_builder":"A",
              "ph_sale_bill_reports":"A",
              "dental_consultations":"A",
              "mas_misc_settings":"A",
              "billing_tally_export":"A",
              "linen_report_builder":"N",
              "dialysis_machine_status":"A",
              "cancel_radiology":"A",
              "stores_view_stock_issues":"A",
              "mas_dental_supplies_master":"A",
              "reg_quick_estimate":"A",
              "po_pending_item_builder":"A",
              "insurance_accumed_claim":"A",
              "generic_documents_list":"A",
              "rep_network_revenue_builder":"N",
              "mas_custom_list1":"A",
              "mas_custom_list3":"A",
              "clinical_hospitalization_information":"A",
              "get_bill_charge_claims":"A",
              "mas_custom_list2":"A",
              "rad_schedules_list":"A",
              "mas_custom_list5":"A",
              "service_order":"A",
              "mas_custom_list4":"A",
              "mas_custom_list7":"A",
              "lab_pending_sample_assertions":"A",
              "mas_custom_list6":"A",
              "res_availability":"A",
              "mas_custom_list9":"A",
              "mas_custom_list8":"A",
              "mas_dialysate_type":"A",
              "initial_assessment":"A",
              "mas_barcode_template":"A",
              "hl7_configuration":"A",
              "mas_reports_overrides":"A",
              "raise_claim_batch_submission":"A",
              "scheduler_message_send":"A",
              "mas_network_centers":"N",
              "insurance_claim_receipts":"A",
              "nurse_notes_audit_log":"A",
              "license_type":"N",
              "ph_invoice_rep_builder":"A",
              "case_file_details_builder":"A",
              "patient_writeoff_approval":"A",
              "preauth_approvals":"N",
              "adv_pkg_handedover_patient_packages_list":"A",
              "tooth_surface_status_master":"A",
              "dialysis_intra_sessions":"A",
              "linen_stats":"N",
              "mas_dial_access_types":"A",
              "infection_site_master":"A",
              "mas_phrase_suggestions_category_master":"A",
              "emr_access_right":"A",
              "rep_doc_consul_builder":"A",
              "saved_searches":"A",
              "rep_store_purchasesummary":"A",
              "mas_pat_visit_bills_template":"A",
              "pharma_presc_list":"A",
              "mas_receipt_refund_template":"A",
              "new_registration":"N",
              "mlc_genericdoc_print":"A",
              "stores_user_indent_approval":"A",
              "send_to_tpa":"N",
              "update_mrd":"A",
              "complaints_ip_audit_log":"A",
              "doc_week_scheduler":"A",
              "mrd_file_return":"A",
              "lab_edit_results":"A",
              "diag_edit_master_id":"A",
              "rep_stock_ledger":"A",
              "rep_pharmacy_purchase_items_vat_report":"A",
              "birth_details":"A",
              "operation_docs":"A",
              "bedu_fav_rpt_dashbd":"A",
              "mas_contractor":"A",
              "stock_inventory_issue":"A",
              "lab_schedules_search":"A",
              "ip_bed_utilization":"A",
              "rep_network_bill_builder":"N",
              "contract_report_builder":"N",
              "mas_scheduler_cron":"A",
              "ph_supplier_payments":"A",
              "cons_allergy_audit_log":"A",
              "pbm_requests":"N",
              "eandm_calculator":"A",
              "pending_service_prescriptions":"A",
              "bed_view":"A",
              "rep_revenue_builder_popup":"A",
              "rep_revenueaccrual":"A",
              "payment_audit_log":"A",
              "stores_patient_indent_list":"A",
              "stores_asset_approval":"A",
              "op_prescribe":"A",
              "rep_codes":"A",
              "patient_activities_audit_log":"A",
              "pay_miscellaneous":"A",
              "treatment_sheet_print":"A",
              "mas_edit_result_ranges":"A",
              "doctors_note":"A",
              "dietary_master":"N",
              "custom_rpt_add":"A",
              "service_docs_print":"A",
              "pending_radiology_prescriptions":"A",
              "mas_discount_authorizer":"A",
              "service_group":"A",
              "rep_rate_variation":"A",
              "mas_center_prefs":"A",
              "optometrist_screen":"N",
              "lab_incoming_bill_list":"A",
              "rep_rev_dashboard":"A",
              "mas_discharge_type":"A",
              "message_log":"A",
              "mas_hosp_roles":"A",
              "patient_writeoff":"A",
              "license_report_builder":"N",
              "dis_metadata":"A",
              "mas_user_location":"A",
              "vaccinations":"A",
              "pay_paymentscreen":"A",
              "bed_ward_wise_occu_rep_builder":"A",
              "mas_col_cards":"A",
              "doctor_notes_audit_log":"A",
              "mas_store_type":"A",
              "ot_bookings":"A",
              "rep_insurance_claim_batch_builder":"A",
              "registration_audit_log":"A",
              "new_prepaid_bills":"A",
              "mas_prescription_template":"A",
              "dialysis_medications":"A",
              "rep_payment_insurance":"N",
              "st_hdrug_sales":"A",
              "dialysis_pre_sessions":"A",
              "pending_services":"A",
              "mas_section_fields":"A",
              "mng_center_practo_profiles":"A",
              "dialysis_sessions_report":"A",
              "ward_activities":"A",
              "billing_daybook":"A",
              "hospitalization_reasons":"A",
              "doctor_eye_exam":"N",
              "deposit_builder":"A",
              "mas_bill_template":"A",
              "patient_activities_report_builder":"A",
              "stores_po":"A",
              "search_bills":"A",
              "stores_patient_indent_edit_return":"A",
              "dialysis_order":"A",
              "mas_counters":"A",
              "diag_internal_lab_builder":"A",
              "mas_anaesthesia":"A",
              "mas_countries":"A",
              "Scheduler_Doctors_Appointment":"A",
              "op_patient_docs_print":"A",
              "mas_out_houses":"A",
              "ip_audit_log":"A",
              "dialysis_prescriptions":"A",
              "mas_death_reason":"A",
              "service_group_upload":"A",
              "dyna_package_charges_audit_log":"A",
              "rep_pharmacy_purchase_vat_abated_report":"A",
              "lab_unfinished_tests":"A",
              "diagnosis_favourites":"A",
              "mas_bill_ac_vc_templates":"A",
              "operations_conducted_list":"N",
              "donor_screening_search":"A",
              "patient_deposits_collection":"A",
              "pay_paymentscreen_others":"A",
              "serv_cons_master":"A",
              "patient_indent_item_rep_builder":"A",
              "mas_Issue_users":"A",
              "pharma_retail_sale_pending_bills_print":"A",
              "rep_patient_admitdischarge_trend_builder":"A",
              "pending_consultation_prescriptions":"A",
              "test_equipment_master":"A",
              "nurse_note":"A",
              "edit_receipt":"A",
              "ot_cons_master":"A",
              "rep_bill_status_change":"A",
              "duty_roster_report":"N",
              "mas_system_preferences":"A",
              "rad_select_outhouse":"A",
              "stores_supp_cat_mas":"A",
              "genf_allergy_audit_log":"A",
              "pending_operation_prescriptions":"A",
              "triage_form":"A",
              "license":"N",
              "connect_disconnect_tpa":"A",
              "duty_roster":"N",
              "mas_results_cen_app":"A",
              "mas_vensite":"A",
              "consult_token_display_system":"N",
              "mas_generic_names":"A",
              "radiology_audit_log":"A",
              "usr_userdashboard_user":"A",
              "rep_test_equipment_details_builder":"A",
              "mas_plan":"A",
              "pbm_presc_list":"N",
              "mas_operation_templates":"A",
              "lab_test_audit_list":"A",
              "mas_sub_classification_names":"A",
              "accounting_group_master":"A",
              "mas_phrase_suggestions_master":"A",
              "mas_insurance_cat_center":"A",
              "stores_stock_adjust":"A",
              "pharmacy_stock_point":"A",
              "po_items_builder":"A",
              "folowup_details":"A",
              "lab_equipment_qa":"A",
              "insurance_view_msg":"N",
              "rep_network_collection_builder":"N",
              "mas_visit_custom_list2":"A",
              "mas_dialyzer_types":"A",
              "mat_blood_donor":"A",
              "ph_pend_rep_report":"A",
              "sample_rejections_builder":"A",
              "rep_patientvisitstats_trend_builder":"A",
              "mas_visit_custom_list1":"A",
              "receipt_print":"A",
              "pharma_view_store_item_batch_list":"A",
              "mas_reg_cards":"A",
              "lab_incoming_test_reconduction":"A",
              "mas_prescription_instructions_master":"A",
              "dialysis_adequacy":"A",
              "rep_ipopstats":"A",
              "ip_bedalloc":"A",
              "mas_anaesthesia_upload":"A",
              "ins_estimate":"N",
              "patient_expensive_statement":"A",
              "vital_form_audit_log":"A",
              "pbm_approvals":"N",
              "lab_test_result_builder":"A",
              "complaints_cons_audit_log":"A",
              "clinical_vaccination_no_reason":"A",
              "mrd_file_indent":"A",
              "complaints_surgery_audit_log":"A",
              "mas_suppliers":"A",
              "service_conduction_print":"A",
              "stock_upload":"A",
              "mas_out_houses_list":"A",
              "pharma_sales_print":"A",
              "ins_templates":"N",
              "patient_deposits_print":"A",
              "reagent_consumables_builder":"A",
              "intake_output":"A",
              "complaints_log_report_print":"A",
              "otrecord_diagnosis_audit_log":"A",
              "mas_image_markers":"A",
              "mas_payment_terms":"A",
              "ins_dashboard":"N",
              "pre_auth_forms":"N",
              "out_pat_reg":"A",
              "work_order":"N",
              "score_card_list":"A",
              "rep_insurance_claim_builder":"A",
              "mng_doc_practo_profiles":"A",
              "ip_prescriptions":"A",
              "rep_patient_dues_builder":"A",
              "patient_diag_status_search":"A",
              "mas_reg_templates":"A",
              "mas_dental_supplier_rate_master":"A",
              "mas_incoming_samples":"A",
              "payments_paid_builder":"A",
              "mas_areas":"A",
              "outhouse_payment":"A",
              "growth_chart":"A",
              "mas_operations":"A",
              "preauth_presc_list":"N",
              "cons_audit_log":"A",
              "stores_reorder":"A",
              "consolidated_bill":"A",
              "mrd_file_search":"A",
              "tests_presc_ordered_report":"A",
              "tooth_surface_option_master":"A",
              "usr_userdashboard_role":"A",
              "sponsor_writeoff_approval":"A",
              "rep_network_patients_builder":"N",
              "rad_incoming_bill_list_print":"A",
              "clinical_vaccinations":"A",
              "mas_ref_doctors":"A",
              "linen_fav_rpt_dashbd":"N",
              "mas_dyna_upload":"A",
              "diag_report_print":"A",
              "mas_component_barcode_template":"A",
              "mas_pkg_settings":"A",
              "clinical_infection_master":"A",
              "lab_pending_samples_search":"A",
              "crown_status_master":"A",
              "mas_icd_codes_cm_upload":"A",
              "mas_ph_ret_spon":"A",
              "serv_audit_log":"A",
              "radiology_test_reconduction":"A",
              "mas_doctors_upload":"A",
              "col_blood_donor":"A",
              "radiology_incoming_test_reconduction":"A",
              "preauth_presc":"N",
              "mas_store_dept":"A",
              "dialysis_machine_shift":"A",
              "cons_diagnosis_audit_log":"A",
              "stores_stock_ledger":"A",
              "stores_indent_approval":"A",
              "dialysis_receipts":"A",
              "discharge_summary_print":"A",
              "bill_audit_log":"A",
              "medication_chart":"A",
              "rateplan_spread_sheet":"A",
              "patient_summary":"A",
              "bed_occu_rep_builder":"A",
              "mas_allergy":"N",
              "rep_network_visits_builder":"N",
              "stores_batch_po":"A",
              "diagnosticTests_audit_log":"A",
              "mas_print":"A",
              "snp_scheduler":"A",
              "mas_plan_upload":"A",
              "per_diem_codes":"A",
              "rep_incoming_test_details":"A",
              "mas_dental_shades_master":"A",
              "show_maint_activity":"N",
              "mas_generic_doc_template":"A",
              "serv_res_master":"A",
              "patient_details_builder":"A",
              "change_consult_doctor":"A",
              "mas_rate_plan":"A",
              "survey_question_category":"A",
              "fp_service_enroll":"N",
              "conducted_services":"A",
              "ins_estimate_print":"N",
              "pending_lab_prescriptions":"A",
              "generic_documents_print":"A",
              "label_master":"A",
              "mas_doctempl_cen_app":"A",
              "mas_vitalparameters":"A",
              "reg_upload":"N",
              "asset_complaints":"N",
              "scheduler_audit_log":"A",
              "pay_supplier":"A",
              "op_op_prescription_print":"A",
              "lab_receive_split_sample":"A",
              "sale_fav_rpt_dashbd":"A",
              "rh_blood_group":"A",
              "mas_bedmaster":"A",
              "laboratory_audit_log":"A",
              "edit_claim":"A",
              "outstanding_deposits":"A",
              "ph_itemwise_stock_builder":"A",
              "pharma_stock_transfer":"A",
              "diag_reagent_master":"A",
              "mas_packages_applicability":"A",
              "consultation_favourites":"A",
              "ins_generic_docs":"N",
              "discharge_medication_print":"A",
              "score_card":"A",
              "lab_signedoff_report_list":"A",
              "generic_general_image":"A",
              "bloodbag_report_builder":"A",
              "pbm_presc":"N",
              "mas_health_authority_pref":"A",
              "pharma_item_credit_bill_print":"A",
              "mas_organizations":"A",
              "insurance_haad_claim":"A",
              "mas_medicine_dosage":"A",
              "mas_denial_codes":"A",
              "infections_data":"A",
              "indent_flow_builder":"A",
              "discharge_medication":"N",
              "bulk_arrival":"N",
              "stock_consumption_rep_builder":"A",
              "mas_icd_codes_cm":"A",
              "rep_bill_charge_builder":"A",
              "mas_mrd_casefile_users":"A",
              "op_cons_form":"A",
              "ia_audit_log":"A",
              "rep_collection_allocation_builder":"A",
              "stores_po_print":"A",
              "pay_dashboard":"A",
              "activities_list":"A",
              "pharmacy_doc_wise_sales_report":"A",
              "stores_view_user_returns":"A",
              "revenue_accrual_report_builder":"A",
              "diet_generic_document_print":"A",
              "stores_supp_ret_builder":"A",
              "mas_medicines":"A",
              "rad_edit_results":"A",
              "services_presc_ordered_report":"A",
              "UHID_search":"N",
              "mas_dyna_package_cat":"A",
              "rep_revenue_doctor":"A",
              "mas_card_type":"A",
              "rep_insurance_claim_det_builder":"A",
              "emergency_call_list_rep_builder":"N",
              "Doctor_Appointment":"A",
              "equipment_order":"A",
              "pharma_estimate_list":"A",
              "mas_hvf_template":"A",
              "rep_ip_list":"A",
              "comp_blood_donor":"A",
              "stores_patient_indent_view_return":"A",
              "dyna_package":"A",
              "grp_blood_donor":"A",
              "mas_item_kit":"N",
              "mas_bloodtype":"A",
              "rep_patientstats_trend_builder":"A",
              "rep_markup_rates_report":"A",
              "rep_revenue_builder":"A",
              "ot_audit_log":"A",
              "mas_operations_upload":"A",
              "operation_docs_print":"A",
              "linen_dashboard":"N",
              "rateplan_spread_sheet_upload":"A",
              "patient_details_search":"A",
              "patient_bed_occ_builder":"A",
              "mas_roster_resource_master":"N",
              "proc_fav_rpt_dashbd":"A",
              "search_resource_scheduler":"A",
              "collection_approval_receipts":"A",
              "mas_services_upload":"A",
              "rad_test_audit_list":"A",
              "diag_methodology_master_id":"A",
              "pharma_sale_duplicate_bill":"A",
              "mas_pat_header_prefs":"A",
              "operation_documents_list":"A",
              "donation_details":"N",
              "ivf_cycle_completion":"N",
              "change_billprimary":"A",
              "diag_sample_type_master":"A",
              "scheduler_generic_resource_type_master":"A",
              "my_msg_notification":"A",
              "rep_pharmacy_pharmacy_dues_report":"A",
              "reg_card_print":"A",
              "emergency_call_list":"N",
              "patient_category_change":"A",
              "pay_prescribe_doctor":"A",
              "mas_rejection_reason":"A",
              "donor_report_builder":"A",
              "survey_feedback_forms_mas":"A",
              "mas_emailTemplates":"A",
              "mas_general_message_type":"A",
              "maint_schedule_rep_builder":"N",
              "rep_pharmacy_chkpoint_difference":"A",
              "service_builder":"A",
              "addchannel_appointment":"N",
              "edit_pharmacy_item_amount":"A",
              "all_receipts_audit_log":"A",
              "serv_fav_rpt_dashbd":"A",
              "mas_dept_units":"A",
              "survey_rating_mas":"A",
              "dial_fav_rpt_dashbd":"A",
              "mas_blood_disc":"A",
              "create_patient_credit_note":"A",
              "deposit_receipts_builder":"A",
              "rad_incoming_bill_list":"A",
              "list_laundry":"N",
              "dia_scheduler":"A",
              "dental_trtment_report_builder":"A",
              "reg_expression":"A",
              "bill_pharma_sales_print":"A",
              "rep_bill_builder":"A",
              "dialysis_current_sessions":"A",
              "mas_centers":"A",
              "intake_output_audit_log":"A",
              "ins_remittance":"A",
              "bed_dur_occu_rep_builder":"A",
              "root_status_master":"A",
              "mas_scan_doc_types":"A"
           },
            "menuAvlblMap":{  
              "grp_print_templates":"Y",
              "grp_dietary":"N",
              "grp_stores_procurement":"Y",
              "grp_payments":"Y",
              "grp_opthalmology":"N",
              "grp_consultation_reports":"Y",
              "grp_ward_activities_reports":"Y",
              "grp_radiology":"Y",
              "grp_laboratory_reports":"Y",
              "grp_transportation":"N",
              "grp_linen_reports":"N",
              "grp_patient_package_reports":"Y",
              "grp_transportation_reports":"N",
              "grp_medical_records":"Y",
              "grp_store_sales_reports":"Y",
              "grp_reports":"Y",
              "grp_billing_prefs":"Y",
              "grp_hospital_billing_masters":"Y",
              "grp_blood_reports":"Y",
              "grp_patient_demography_reports":"Y",
              "grp_service_reports":"Y",
              "grp_adv_packages":"Y",
              "grp_scheduler_reports":"Y",
              "grp_dialysis":"Y",
              "grp_patient":"Y",
              "grp_dental_masters":"Y",
              "grp_masters":"Y",
              "grp_ot_reports":"Y",
              "grp_master_reports":"Y",
              "grp_ins_ext":"Y",
              "grp_stores_sales_issues":"Y",
              "grp_dashboard_statistics_reports":"Y",
              "grp_insurance_reports":"Y",
              "grp_eclaim_preauth":"N",
              "grp_fixed_asset_mgmt":"N",
              "grp_messaging_masters":"Y",
              "grp_store_mgmt_reports":"Y",
              "grp_eclaim_pbm":"N",
              "grp_stores_management":"Y",
              "grp_pharmacy_masters":"Y",
              "grp_bloodbank_masters":"Y",
              "grp_patient_feedback":"Y",
              "grp_registration":"Y",
              "grp_financial_reports":"Y",
              "grp_complaints_log":"Y",
              "grp_clinical_reports":"Y",
              "grp_dietary_reports":"N",
              "grp_hospital_admin_masters":"Y",
              "grp_dialysis_reports":"Y",
              "grp_patientfeedback_reports":"Y",
              "grp_blood_bank":"Y",
              "grp_store_procure_reports":"Y",
              "grp_dental_reports":"Y",
              "grp_clinical_data":"Y",
              "grp_duty_roster":"N",
              "grp_fav_reports":"Y",
              "grp_new_ui":"N",
              "grp_patient_search":"Y",
              "grp_insta_subscriptions":"N",
              "grp_quick_links":"Y",
              "grp_settings":"Y",
              "grp_linen":"N",
              "grp_network_financial_reports":"N",
              "grp_hospital_templates":"Y",
              "grp_mrd_reports":"Y",
              "grp_operations":"Y",
              "grp_hospital_prefs":"Y",
              "grp_scheduler":"Y",
              "grp_roster_reports":"N",
              "grp_general_masters":"Y",
              "grp_services":"Y",
              "grp_billing_reports":"Y",
              "grp_custom_reports":"Y",
              "grp_ivf_reports":"N",
              "grp_resource_mgmt_reports":"N",
              "grp_diagnostics":"Y",
              "grp_cssd":"N",
              "grp_bed_reports":"Y",
              "grp_insurance":"Y",
              "grp_ivf":"N"
           },
            "multiStoreAccess":"N",
            "modules_activated":[  
              "mod_op_forms",
              "mod_basic",
              "mod_messaging",
              "mod_trend",
              "mod_payments",
              "mod_op_prescription",
              "mod_services",
              "mod_op",
              "mod_stores",
              "mod_scheduler",
              "mod_scheduler_messages",
              "mod_registration",
              "mod_billing_ext",
              "mod_general_messages",
              "mod_prescribe",
              "mod_dialysis",
              "mod_mrd_icd",
              "mod_mrd",
              "mod_billing",
              "mod_tally",
              "mod_diagnostics",
              "mod_consumables_flow",
              "mod_pharmacy",
              "mod_centers",
              "mod_clinical_data",
              "mod_scorecard",
              "mod_ipservices",
              "mod_adt",
              "mod_reward_points",
              "mod_patient_feedback",
              "mod_wardactivities",
              "mod_mrd_casefile",
              "mod_adv_packages",
              "mod_clinical_reports",
              "mod_dental_chart",
              "mod_central_lab",
              "mod_vaccination",
              "mod_patient_portal",
              "mod_mobile",
              "mod_download_reports",
              "mod_practo_integration",
              "mod_notification",
              "mod_advanced_ot",
              "mod_blood_bank",
              "mod_eclaim",
              "mod_ins_ext",
              "mod_adv_ins"
           ]
        }


