-- liquibase formatted sql
-- changeset prashantbaisla:add-metadata-comments-to-remaining-tables splitStatements:false
-- validCheckSum: ANY

SELECT comment_on_table_or_sequence_if_exists('patient_pac', true,  'Txn',  'Holds data for Pre Anaesthetic Checkups' );
SELECT comment_on_table_or_sequence_if_exists('test_cytology_results', true,  'Txn',  'cytology test results' );
SELECT comment_on_table_or_sequence_if_exists('test_histopathology_results', true,  'Txn',  'histopathology test results' );
SELECT comment_on_table_or_sequence_if_exists('integ_diag_in', true,  'Txn',  'Staging table for sharing hl7 results' );
SELECT comment_on_table_or_sequence_if_exists('integ_diag_in_bkp', true,  'Txn',  'For long time backup of integ_diag_in after cleanup' );
SELECT comment_on_table_or_sequence_if_exists('mrd_icdcodes_cm', true,  'Master',  'MRD ICD codes' );
SELECT comment_on_table_or_sequence_if_exists('test_microbiology_results', true,  'Txn',  'Microbiology results' );
SELECT comment_on_table_or_sequence_if_exists('micro_abst_panel_master', true,  'Master',  'Microbiology abst panel' );
SELECT comment_on_table_or_sequence_if_exists('micro_abst_antibiotic_master', true,  'Master',  'Microbiology abst antibiotic mapping' );
SELECT comment_on_table_or_sequence_if_exists('micro_antibiotic_master', true,  'Master',  'Microbiology antibiotics' );
SELECT comment_on_table_or_sequence_if_exists('micro_growth_template_master', true,  'Master',  'Microbiology growth templates' );
SELECT comment_on_table_or_sequence_if_exists('micro_nogrowth_template_master', true,  'Master',  'Microbiology no growth templates' );
SELECT comment_on_table_or_sequence_if_exists('test_micro_antibiotic_details', true,  'Txn',  'Microbiology antibiotics details' );
SELECT comment_on_table_or_sequence_if_exists('test_micro_org_group_details', true,  'Txn',  'Microbiology organism details' );
SELECT comment_on_table_or_sequence_if_exists('micro_abst_orggr', true,  'Txn',  'Microbiology abst organism mapping' );
SELECT comment_on_table_or_sequence_if_exists('micro_org_group_master', true,  'Master',  'Microbiology organism groups' );
SELECT comment_on_table_or_sequence_if_exists('micro_organism_master', true,  'Master',  'Microbiology organisms' );
SELECT comment_on_table_or_sequence_if_exists('generic_preferences', true,  'Master',  'Generic Preferences. Please use the format for sms_username column value as
dot followed by registered username @ domain name - [.username@smscountry.net]' );
SELECT comment_on_table_or_sequence_if_exists('network_sync_status', true,  'Txn',  'Network Report Sync Status (Deprecated)' );
SELECT comment_on_table_or_sequence_if_exists('anesthesia_types_insurance_category_mapping', true,  'Master',  'Anesthesia types to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('bed_types_insurance_category_mapping', true,  'Master',  'Bed types to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('common_charges_insurance_category_mapping', true,  'Master',  'Direct Charges to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('consultation_types_insurance_category_mapping', true,  'Master',  'Consultation Types to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('diagnostic_test_insurance_category_mapping', true,  'Master',  'Tests to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('diet_insurance_category_mapping', true,  'Master',  'Diet Items to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('equipment_insurance_category_mapping', true,  'Master',  'Equipment charges to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('operation_insurance_category_mapping', true,  'Master',  'Operation charges to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('operation_schedule', true,  'Txn',  'Patient Operation Details' );
SELECT comment_on_table_or_sequence_if_exists('packages_insurance_category_mapping', true,  'Master',  'packages to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('service_insurance_category_mapping', true,  'Master',  'Services to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('store_items_insurance_category_mapping', true,  'Master',  'Stores items to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('theatre_insurance_category_mapping', true,  'Master',  'theatre to insurance category mapping' );
SELECT comment_on_table_or_sequence_if_exists('tickets', true,  'Txn',  'Coder Review Tickets Metadata' );
SELECT comment_on_table_or_sequence_if_exists('ticket_comments', true,  'Txn',  'Coder Review Ticket Comments' );
SELECT comment_on_table_or_sequence_if_exists('ticket_recipients', true,  'Txn',  'Coder Review Ticket Recipients' );
SELECT comment_on_table_or_sequence_if_exists('codification_ticket_details', true,  'Txn',  'Coder Review Ticket Details, child table of Tickets' );
SELECT comment_on_table_or_sequence_if_exists('complaint_type_master', true,  'Master',  'Define complaint types' );
SELECT comment_on_table_or_sequence_if_exists('practitioner_type_consultation_mapping', true,  'Master',  'practitioner_type_id and consultation_type_id mapping' );
SELECT comment_on_table_or_sequence_if_exists('doctor_consultation_audit_log', true,  'Txn',  'Doctor Consultation Audit Log' );
SELECT comment_on_table_or_sequence_if_exists('clinical_preferences', true,  'Master',  'Clinical Preferences' );
SELECT comment_on_table_or_sequence_if_exists('clinical_preferences_audit_log', true,  'Master',  'Clinical Preferences Audit Log' );
SELECT comment_on_table_or_sequence_if_exists('package_issue_uom', true,  'Master',  'Package UOM Master with Unit UOM and its package size.' );
SELECT comment_on_table_or_sequence_if_exists('print_templates_temp', true,  'Master',  'Print Templates (Temp of print_templates) ' );
SELECT comment_on_table_or_sequence_if_exists('triage_components', true,  'Master',  'Triage Components Master' );
SELECT comment_on_table_or_sequence_if_exists('patient_section_details_orig', true,  'Txn',  'Copy of patient_section_details' );
SELECT comment_on_table_or_sequence_if_exists('accounting_voucher_details', true,  'Txn',  'vouher details for Tally export and import' );
SELECT comment_on_table_or_sequence_if_exists('accounting_xml_export_import_log', true,  'Txn',  'Tally export or import File log' );
SELECT comment_on_table_or_sequence_if_exists('accounting_export_voucher', true,  'Txn',  'ZOHO export vouchers' );
SELECT comment_on_table_or_sequence_if_exists('accounting_export_log', true,  'Txn',  'ZOHO accounting export log' );
SELECT comment_on_table_or_sequence_if_exists('bill_approvals', true,  'Txn',  'Not used' );
SELECT comment_on_table_or_sequence_if_exists('bill_charge_item_account', true,  'Txn',  'Not used' );
SELECT comment_on_table_or_sequence_if_exists('bill_sponsor', true,  'Txn',  'Not used' );
SELECT comment_on_table_or_sequence_if_exists('bill_sponsor_receipts', true,  'Txn',  'No data found' );
SELECT comment_on_table_or_sequence_if_exists('patient_corporate_details', true,  'Txn',  'Patient Corporate Insurance Details' );
SELECT comment_on_table_or_sequence_if_exists('patient_national_sponsor_details', true,  'Txn',  'Patient National Sponsor Details' );
SELECT comment_on_table_or_sequence_if_exists('patient_visit_bills_template', true,  'Master',  'Patient Bill Template List' );
SELECT comment_on_table_or_sequence_if_exists('insurance_payment_allocation', true,  'Txn',  'Insurance Remittance Allocation Details' );
SELECT comment_on_table_or_sequence_if_exists('insurance_case', true,  'Txn',  'Insurance Case List' );
SELECT comment_on_table_or_sequence_if_exists('corporate_docs_details', true,  'Txn',  'Corporate Documents For Corporate Sponsor' );
SELECT comment_on_table_or_sequence_if_exists('discount_category_chargeheads', true,  'Master',  'Discount Category To Charge Head Mappings' ); 
SELECT comment_on_table_or_sequence_if_exists('discount_category_master', true,  'Master',  'Discount Category Master');
SELECT comment_on_table_or_sequence_if_exists('insurance_docs', true,  'Txn',  'Related to Deprecated Module Insurance Case');
SELECT comment_on_table_or_sequence_if_exists('insurance_estimate', true,  'Txn',  'Related to Deprecated Module Insurance Case Estimates' );
SELECT comment_on_table_or_sequence_if_exists('insurance_payment_unalloc_amount', true,  'Txn',  'Unallocated Payment Amount for each charge item' );
SELECT comment_on_table_or_sequence_if_exists('insurance_preauth', true,  'Txn',  'Related to Deprecated Module insurance case');
SELECT comment_on_table_or_sequence_if_exists('insurance_preauth_values', true,  'Txn',  'Related to Deprecated Module insurance case');
SELECT comment_on_table_or_sequence_if_exists('insurance_status', true,  'Master',  'Insurance statuses related to insurance case');
SELECT comment_on_table_or_sequence_if_exists('insurance_tpa_docs', true,  'Txn',  'Related to Deprecated Module insurance case');
SELECT comment_on_table_or_sequence_if_exists('insurance_transaction', true,  'Txn',  'Related to Deprecated Module insurance case');
SELECT comment_on_table_or_sequence_if_exists('insurance_transaction_attachments', true,  'Txn',  'Related to Deprecated Module insurance case');
SELECT comment_on_table_or_sequence_if_exists('national_sponsor_docs_details', true,   'Txn',  'National sponsor patients document details' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_dyna_package_master_charges', true,  'Master',  'It was used for dyna package charges(Deprecated Table)' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_dyna_package_master_charges_backup', true,  'Master',  'It was used for dyna package master backup charges(Deprecated Table)' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_insurance_claim_resubmission', true,  'Txn',  'It was used for insurance claim to resubmission batch mapping(Deprecated Table)' );
SELECT comment_on_table_or_sequence_if_exists('patient_insurance_details', true,  'Txn',  'Related to Deprecated Module insurance case' );
SELECT comment_on_table_or_sequence_if_exists('refdcoc_charge_details', true,  'Master',  'Referral doctor charge details' );
SELECT comment_on_table_or_sequence_if_exists('tpa_forms_pdf', true,  'Master',  'Not used(Deprecated Table)' );
SELECT comment_on_table_or_sequence_if_exists('insurance_company_category_mapping', true,  'Master',  'Insurance company to insurance categories mapping' );
SELECT comment_on_table_or_sequence_if_exists('patient_history', true,  'Txn',  'Save Patient Past history, family history and Medical/Surgery History' );
SELECT comment_on_table_or_sequence_if_exists('ivf_compl_oocyte', true,  'Txn',  'store oocyte details' );
SELECT comment_on_table_or_sequence_if_exists('ivf_compl_oocyte_assess', true,  'Txn',  'store oocyte assessment details' );
SELECT comment_on_table_or_sequence_if_exists('ivf_comple_embryo_inf', true,  'Txn',  'store embryo/transfer information' );
SELECT comment_on_table_or_sequence_if_exists('ivf_cycle', true,  'Txn',  'capture ivf cycle data' );
SELECT comment_on_table_or_sequence_if_exists('ivf_cycle_allergies', true,  'Txn',  'store the allergies that a patient has' );
SELECT comment_on_table_or_sequence_if_exists('ivf_daily_details', true,  'Txn',  'store the daily treatment details' );
SELECT comment_on_table_or_sequence_if_exists('ivf_daily_follicles', true,  'Txn',  'store follicular growth scan results' );
SELECT comment_on_table_or_sequence_if_exists('ivf_daily_hormone_results', true,  'Txn',  'store hormone results for the day' );
SELECT comment_on_table_or_sequence_if_exists('ivf_daily_prescription', true,  'Txn',  'capture association of ivf daily cycle to the prescription stored in treatment_chart' );
SELECT comment_on_table_or_sequence_if_exists('ivf_luteal_hormone_levels', true,  'Txn',  'store luteal support hormonal levels' );
SELECT comment_on_table_or_sequence_if_exists('ivf_luteal_prescriptions', true,  'Txn',  'store the prescriptions associated' );
SELECT comment_on_table_or_sequence_if_exists('hosp_special_account_names', true,  'Txn',  'Accounting names useful for Tally' );
SELECT comment_on_table_or_sequence_if_exists('hosp_party_account_names', true,  'Txn',  'Accounting party names useful for Tally' );
SELECT comment_on_table_or_sequence_if_exists('ambulance_master', true,  'Master',  'Ambulance Transport Master (Deprecated)' );
SELECT comment_on_table_or_sequence_if_exists('linen_user_category', true,  'Master',  'Linen user category (Deprecated)' );
SELECT comment_on_table_or_sequence_if_exists('linen_user_master', true,  'Master',  'Linen user master (Deprecated)' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_dyna_package_master_charges', true,  'Master',  '(Deprecated) obsolete_dyna_package_master_charges' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_dyna_package_master_charges_backup', true,  'Master',  '(Deprecated) obsolete_dyna_package_master_charges_backup' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_insurance_claim_resubmission', true,  'Txn',  '(Deprecated) obsolete_insurance_claim_resubmission' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_ip_record', true,  'Txn',  '(Deprecated) obsolete_ip_record' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_medication_order_details', true,  'Master',  '(Deprecated) obsolete_medication_order_details' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_medication_order_main', true,  'Master',  '(Deprecated) obsolete_medication_order_main' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_patient_doctor_instructions', true,  'Master',  '(Deprecated) obsolete_patient_doctor_instructions' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_test_report_images', true,  'Txn',  '(Deprecated) obsolete_test_report_images' );
SELECT comment_on_table_or_sequence_if_exists('obsolete_vitals_schedule', true,  'Master',  '(Deprecated) obsolete_vitals_schedule' );
SELECT comment_on_table_or_sequence_if_exists('patient_standing_instructions_obsolete', true,  'Txn',  '(Deprecated) used to store patient prescriptions information' );
SELECT comment_on_table_or_sequence_if_exists('linen_usage_main', true,  'Txn',  '(Deprecated) Linen Utilization' );
SELECT comment_on_table_or_sequence_if_exists('linen_usage_details', true,  'Txn',  '(Deprecated) Linen Utilization details' );
SELECT comment_on_table_or_sequence_if_exists('sold_packages', true,  'Txn',  'Package 3.0 - Package sold post customization to an MR No' );
SELECT comment_on_table_or_sequence_if_exists('sold_packages_contents', true,  'Txn',  'Package 3.0 - Contents of Package sold post customization to an MR No' );
SELECT comment_on_table_or_sequence_if_exists('shift_resources', true,  'Txn',  '(Deprecated) Duty Roster - Shift Resources' );
SELECT comment_on_table_or_sequence_if_exists('patient_activities_obsolete', true,  'Txn',  '(Deprecated) Ward Activities - Patient Activities' );
SELECT comment_on_table_or_sequence_if_exists('center_report_deliv_days_overrides', true,  'Master',  'Center Master - Center Delivery Times Overrides' );
SELECT comment_on_table_or_sequence_if_exists('center_report_deliv_override_details', true,  'Master',  'Center Master - Center Delivery Times Overrides Details' );
SELECT comment_on_table_or_sequence_if_exists('center_report_deliv_times_default', true,  'Master',  'Center Master - Default Center Delivery Times' );
SELECT comment_on_table_or_sequence_if_exists('docs_upload', true,  'Master',  'Insurance - Upload other docs from regsitration' );
SELECT comment_on_table_or_sequence_if_exists('fields', true,  'Master',  'Discharge Summary - Fields' );
SELECT comment_on_table_or_sequence_if_exists('medicine_type', true,  'Master',  '(Likely Deprecated) Prescription screen of OperationTheatre module' );
SELECT comment_on_table_or_sequence_if_exists('operation_report', true,  'Txn',  '(Likely Deprecated) Operation Theatre Report - OperationTheatre module' );
SELECT comment_on_table_or_sequence_if_exists('ot_activities', true,  'Txn',  '(Likely Deprecated) Operation Theatre Report - OperationTheatre module' );
SELECT comment_on_table_or_sequence_if_exists('event_log', true,  'Txn',  '(Likely Deprecated) Event Log' );
SELECT comment_on_table_or_sequence_if_exists('surveydata_answers', true,  'Txn',  '(Deprecated) Customized Patient Feedback Forms - Responses' );
SELECT comment_on_table_or_sequence_if_exists('surveydata_visit_info', true,  'Txn',  '(Deprecated) Customized Patient Feedback Forms - Visit Data' );
SELECT comment_on_table_or_sequence_if_exists('surveyform_general_info', true,  'Txn',  '(Deprecated) Customized Patient Feedback Forms - Template' );
SELECT comment_on_table_or_sequence_if_exists('surveyform_header_questions', true,  'Txn',  '(Deprecated) Customized Patient Feedback Forms - Header Questions' );
SELECT comment_on_table_or_sequence_if_exists('surveyform_rating_scale_desc', true,  'Txn',  '(Deprecated) Customized Patient Feedback Forms - Rating Questions' );
SELECT comment_on_table_or_sequence_if_exists('surveyform_summary_questions', true,  'Txn',  '(Deprecated) Customized Patient Feedback Forms - Summary Questions' );
SELECT comment_on_table_or_sequence_if_exists('surveyform_topic_questions', true,  'Txn',  '(Deprecated) Customized Patient Feedback Forms - Questions' );
SELECT comment_on_table_or_sequence_if_exists('tooth_treatment_details', true,  'Txn',  'Dental Consultation - Treatment/ treatment plan details' );
SELECT comment_on_table_or_sequence_if_exists('treatment_form_pdfs', true,  'Txn',  '(Deprecated) Support for Stemcell treatment related POC table' );
SELECT comment_on_table_or_sequence_if_exists('category_bed_markups', true,  'Master',  'Category Bed Type Markup (Likely deprecated)' );
SELECT comment_on_table_or_sequence_if_exists('medical_fileupload', true,  'Txn',  'Medical File Uploads - Old Discharge Summary (Likely deprecated)' );