-- liquibase formatted sql
-- changeset rajendratalekar:inject-master-ohsrsdohgovph-meta-data

insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','servicecapability','1','General');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','servicecapability','2','Specialty');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','servicecapability','3','Infirmary');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','general','1','Level 1 Hospital');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','general','2','Level 2 Hospital');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','general','3','Level 3 Hospital');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','specialty','1','Treats a particular disease');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','specialty','2','Treats a particular organ');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','specialty','3','Treats a particular class of patients');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','specialty','4','Others');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','traumacapability','1','Trauma Capable');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','traumacapability','2','Trauma Receiving');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','natureofownership','1','Government');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','natureofownership','2','Private');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','government','1','National');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','government','2','Local');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','government','3','State Universities and Colleges (SUCs)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','national','1','DOH Retained / Renationalized');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','national','2','DILG - PNP');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','national','3','DND - AFP');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','national','4','DOJ');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','local','1','Province');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','local','2','City');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','local','3','Municipality');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','private','1','Single Proprietorship');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','private','2','Partnership');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','private','3','Corporation');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','private','4','Religious');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','private','5','Civic Organization');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','private','6','Foundation');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoClassification','private','7','Cooperative');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoQualityManagement','qualitymgmttype','1','ISO Certified');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoQualityManagement','qualitymgmttype','2','International Accreditation');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoQualityManagement','qualitymgmttype','3','PhilHealth Accreditation');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoQualityManagement','qualitymgmttype','4','PCAHO');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoQualityManagement','philhealthaccreditation','1','Basic Participation');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('genInfoQualityManagement','philhealthaccreditation','2','Advanced Participation');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','1','Medicine');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','2','Obstetrics');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','3','Gynecology');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','4','Pediatrics');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','5','Pedia');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','6','Adult');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','7','Others');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','8','Pathologic');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesSpecialty','typeofservice','9','Non-Pathologic / Well-baby');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','1','X-Ray');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','2','Ultrasound');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','3','CT-Scan');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','4','MRI');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','5','Mammography');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','6','Angiography');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','7','Linear Accelerator');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','8','Dental X-Ray');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','9','Others');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','10','Urinalysis');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','11','Fecalysis');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','12','Hematology');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','13','Clinical chemistry');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','14','Immunology/Serology/HIV');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','15','Microbiology (Smears/Culture & Sensitivity)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','16','Surgical Pathology');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','17','Autopsy');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','18','Cytology');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testing','19','Number of Blood units Transfused');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testinggroup','1','Total number of medical imaging tests (all types including x-rays, ultrasound, CT scans, etc.)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testinggroup','2','Total number of laboratory and diagnostic tests (all types, excluding medical imaging)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('hospOptDischargesTesting','testinggroup','3','Blood Service Facilities');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','1','1. Consultants');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','2','1.1 Internal Medicine');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','3','a. Generalist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','4','b. Cardiologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','5','c. Endocrinologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','6','d. Gastro-Enterologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','7','e. Pulmonologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','8','f. Nephrologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','9','g. Neurologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','10','1.2. Obstetrics/ Gynecology (and sub-specialty)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','11','1.3. Pediatrics (and sub-specialty)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','12','1.4. Surgery (and sub-specialty)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','13','1.5. Anesthesiologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','14','1.6. Radiologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','15','1.7. Pathologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','16','2. Post-Graduate Fellows<br>(Indicate specialty/subspecialty)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','17','3. Residents');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','18','3.1. Internal Medicine');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','19','3.2. Obstetricts-Gynecology');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','20','3.3. Pediatrics');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','21','3.4. Surgery');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','22','1. Nurses');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','23','2. Midwives');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','24','3. Nursing Aides');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','25','4. Nutritionist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','27','5. Physical Therapist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','28','6. Pharmacists');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','29','7. Medical Technologist');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','30','8. Laboratory Technician');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','31','9. X-Ray Technologist/X-Ray Technician');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','32','10. Medical Equipment Technician');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','33','11. Social Worker');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','34','12. Medical Records Officer/ Hospital Health Information Officer');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','35','1. Chief Administrative Officer');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','36','2. Accountant');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','37','3. Budget officer');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','38','4. Cashier');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','39','5. Clerk');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','40','6. Engineer');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','41','7. Driver');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','42','9. General Support Staff');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','43','Janitorial');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','44','Maintenance');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPattern','professiondesignation','45','Security');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPatternOthers','parent','10','1. Consultants > 1.1 Internal Medicine > h. Others (Specify)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPatternOthers','parent','17','2. Post-Graduate Fellows (Indicate specialty/subspecialty) > Others, specify');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPatternOthers','parent','22','3. Residents > 3.5. Others (Specify)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPatternOthers','parent','35','B. Allied Medical > 13. Others (Specify)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPatternOthers','parent','42','C. Non-Medical > 8. Others (Specify)');
insert into ohsrsdohgovph_meta_data(ohsrs_function,field,value,description) values('staffingPatternOthers','parent','461','C. Non-Medical > 9. General Support Staff > - Others (Specify)');