-- liquibase formatted sql
-- changeset mancini2802:deprecate-accural-reports

delete from favourite_reports where action_id in ('rep_revenue_builder','revenue_accrual_report_builder','rep_revenueaccrual');

update u_role set stats_item1 ='' where stats_item1 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item2 ='' where stats_item2 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item3 ='' where stats_item3 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item4 ='' where stats_item4 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item5 ='' where stats_item5 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item6 ='' where stats_item6 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item7 ='' where stats_item7 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item8 ='' where stats_item8 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item9 ='' where stats_item9 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item10 ='' where stats_item10 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item11 ='' where stats_item11 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');

update u_role set stats_item12 ='' where stats_item12 in('TODAYS_REV','TODAYS_PHARMACY_REV','TODAYS_PAYMENTS','MONTHWISE_REV','YEARWISE_REV','MONTHWISE_PHARMACY_REV','YEARWISE_PHARMACY_REV','MONTHWISE_PAYMENTS','YEARWISE_PAYMENTS');
