-- liquibase formatted sql
-- changeset rajendratalekar:restore-comments-for-audit-log-tables-1200

COMMENT ON table bill_audit_log is '{ "type": "Txn", "comment": "Bill audit logs" }';
COMMENT ON table bill_charge_audit_log is '{ "type": "Txn", "comment": "Bill items audit logs" }';
COMMENT ON table bill_receipts_audit_log is '{ "type": "Txn", "comment": "Receipts associated with bills - Audit logs" }';
COMMENT ON table deposits_audit_log is '{ "type": "Txn", "comment": "Deposits audit log" }';
COMMENT ON table diagnostic_charges_audit_log is '{ "type": "Master", "comment": "Diagnostics - Rateplanwise charges audit logs" }';
COMMENT ON table dialysis_prescriptions_audit_log is '{ "type": "Txn", "comment": "Dialysis - Prescriptions audit logs" }';
COMMENT ON table doctor_notes_audit_log is '{ "type": "Txn", "comment": "Doctor Notes Audit Logs" }';
COMMENT ON table doctor_order_audit_log is '{ "type": "Txn", "comment": "Doctor Order Audit Logs" }';
COMMENT ON table dyna_package_audit_log is '{ "type": "Master", "comment": "Dyna Packages Audit logs" }';
COMMENT ON table dyna_package_category_limits_audit_log is '{ "type": "Master", "comment": "Dyna Packages - Category Limits Audit Logs" }';
COMMENT ON table dyna_package_charges_audit_log is '{ "type": "Master", "comment": "Dyna Packages - Rateplanwise charges Audit Log" }';
COMMENT ON table dyna_package_master_charges_audit_log is '{ "type": "Master", "comment": "Dyna Packages - Rateplanwise charges Audit Log" }';
COMMENT ON table mrd_diagnosis_audit_log is '{ "type": "Txn", "comment": "MRD codes audit log" }';
COMMENT ON table nurse_notes_audit_log is '{ "type": "Txn", "comment": "Nurse Notes Audit Log" }';
COMMENT ON table operation_charges_audit_log is '{ "type": "Master", "comment": "Surgeries - Rateplanwise charges audit log" }';
COMMENT ON table operation_master_audit_log is '{ "type": "Master", "comment": "Surgeries Audit Log" }';
COMMENT ON table patient_activities_audit_log is '{ "type": "Txn", "comment": "Patient Ward Activities Audit Logs" }';
COMMENT ON table patient_admission_request_audit_log is '{ "type": "Txn", "comment": "Admission Request Audit Logs" }';
COMMENT ON table patient_allergies_audit_log is '{ "type": "Txn", "comment": "Patient Allergies Audit Logs" }';
COMMENT ON table patient_consultation_prescriptions_audit_log is '{ "type": "Txn", "comment": "Consultation - Meta Data Audit Logs" }';
COMMENT ON table patient_details_audit_log is '{ "type": "Txn", "comment": "Registered Patients Demographics Audit Logs" }';
COMMENT ON table patient_general_docs_audit_log is '{ "type": "Txn", "comment": "All uploaded documents associated with registered patient - audit logs" }';
COMMENT ON table patient_medicine_prescriptions_audit_log is '{ "type": "Txn", "comment": "medicine prescribed by a doctor audit log" }';
COMMENT ON table patient_operation_prescriptions_audit_log is '{ "type": "Txn", "comment": "operation prescribed by a doctor - audit log" }';
COMMENT ON table patient_other_medicine_prescriptions_audit_log is '{ "type": "Txn", "comment": "Other medicines prescribed by doctor - audit log" }';
COMMENT ON table patient_other_prescriptions_audit_log is '{ "type": "Txn", "comment": "Any other prescription prescribed by doctor - audit logs" }';
COMMENT ON table patient_pdf_form_doc_values_audit_log is '{ "type": "Txn", "comment": "Patient Data - PDF Forms (Values) Audit Logs" }';
COMMENT ON table patient_prescription_audit_log is '{ "type": "Txn", "comment": "Prescription Audit Logs" }';
COMMENT ON table patient_registration_audit_log is '{ "type": "Txn", "comment": "Visit Audit Logs" }';
COMMENT ON table patient_section_details_audit_log is '{ "type": "Txn", "comment": "Consultation - Forms section details audit logs" }';
COMMENT ON table patient_section_fields_audit_log is '{ "type": "Txn", "comment": "Consultation - Forms section details (fields) audit log" }';
COMMENT ON table patient_section_options_audit_log is '{ "type": "Txn", "comment": "Consultation - Form Section options audit logs" }';
COMMENT ON table patient_section_values_audit_log is '{ "type": "Txn", "comment": "Consultation - Form Section Details (values) audit logs" }';
COMMENT ON table patient_service_prescriptions_audit_log is '{ "type": "Txn", "comment": "Service prescriptions - audit logs" }';
COMMENT ON table patient_test_prescriptions_audit_log is '{ "type": "Txn", "comment": "Investigation prescriptions audit logs" }';
COMMENT ON table payment_rules_audit_log is '{ "type": "Master", "comment": "Payment rules Audit - Master" }';
COMMENT ON table payments_audit_log is '{ "type": "Txn", "comment": "Payment audit logs" }';
COMMENT ON table payments_details_audit_log is '{ "type": "Txn", "comment": "payment details audit" }';
COMMENT ON table per_diem_codes_audit_log is '{ "type": "Txn", "comment": "Per Diem Codes audit logs" }';
COMMENT ON table per_diem_codes_charges_audit_log is '{ "type": "Txn", "comment": "Per Diem Codes - Rateplanwise charges audit logs" }';
COMMENT ON table sample_collection_audit_log is '{ "type": "Txn", "comment": "Collected samples (audit logs)" }';
COMMENT ON table scheduler_appointment_items_audit_log is '{ "type": "Txn", "comment": "Appointment Details audit logs" }';
COMMENT ON table scheduler_appointments_audit_log is '{ "type": "Txn", "comment": "Appointments audit logs" }';
COMMENT ON table secondary_complaints_audit_log is '{ "type": "Txn", "comment": "Secondary Complaints Audit Log" }';
COMMENT ON table service_master_charges_audit_log is '{ "type": "Master", "comment": "Services - Rateplanwise charges Audit logs" }';
COMMENT ON table services_audit_log is '{ "type": "Master", "comment": "Services Audit Log" }';
COMMENT ON table store_po_main_audit_log is '{ "type": "Txn", "comment": "PO" }';
COMMENT ON table store_stock_details_audit_log is '{ "type": "Txn", "comment": "Stock Audit Logs" }';
COMMENT ON table test_details_audit_log is '{ "type": "Txn", "comment": "Tests - Results details (Audit logs)" }';
COMMENT ON table test_visit_reports_audit_log is '{ "type": "Txn", "comment": "Tests - Reports (Audit Logs)" }';
COMMENT ON table tests_conducted_audit_log is '{ "type": "Txn", "comment": "Tests - Conductions Details (Audit Logs)" }';
COMMENT ON table tests_prescribed_audit_log is '{ "type": "Txn", "comment": "Tests Ordered Audit log" }';
COMMENT ON table diagnostics_audit_log is '{ "type": "Master", "comment": "Diagnostics audit log" }';
COMMENT ON table insurance_plan_details_audit_log is '{ "type": "Master", "comment": "Insurance Plan - Category Limits Audit log" }';
COMMENT ON table insurance_plan_main_audit_log is '{ "type": "Master", "comment": "Insurance Plan Audit log" }';
COMMENT ON table store_item_batch_details_audit_log is '{ "type": "Txn", "comment": "Store Items - Batch Details (Audit Logs)" }';
COMMENT ON table system_preferences_audit_log is '{ "type": "Master", "comment": "System Preferences" }';
COMMENT ON table visit_vitals_audit_log is '{ "type": "Txn", "comment": "Vitals caputred during visit - Audit logs" }';
COMMENT ON table vital_reading_audit_log is '{ "type": "Txn", "comment": "Vitals caputred during visit - Values (Audit logs)" }';
