package com.insta.hms.mdm.poprinttemplates;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PoPrintTemplateModel generated by hbm2java
 */
@Entity
@Table(name = "po_print_template", uniqueConstraints = @UniqueConstraint(columnNames = "template_name"))
public class PoPrintTemplateModel implements java.io.Serializable {

	private PoPrintTemplateIdSequence id;

	public PoPrintTemplateModel() {
	}

	public PoPrintTemplateModel(PoPrintTemplateIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", unique = true, nullable = false, length = 50)),
			@AttributeOverride(name = "pharmacyTemplateContent", column = @Column(name = "pharmacy_template_content")),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 100)),
			@AttributeOverride(name = "reason", column = @Column(name = "reason", length = 500)),
			@AttributeOverride(name = "templateMode", column = @Column(name = "template_mode", length = 1)) })
	public PoPrintTemplateIdSequence getId() {
		return this.id;
	}

	public void setId(PoPrintTemplateIdSequence id) {
		this.id = id;
	}

}
