package com.insta.hms.mdm.printerdefinition;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrinterDefinitionModel generated by hbm2java
 */
@Entity
@Table(name = "printer_definition")
public class PrinterDefinitionModel implements java.io.Serializable {

	private int printerId;
	private String printerDefinitionName;
	private Character printMode;
	private Character logoHeader;
	private Character footer;
	private Character continuousFeed;
	private Integer pageHeight;
	private Integer topMargin;
	private Integer bottomMargin;
	private Integer leftMargin;
	private String fontName;
	private Integer fontSize;
	private Integer pageWidth;
	private Integer textModeColumn;
	private Integer rightMargin;
	private Character orientation;
	private Character status;
	private char repeatPatientInfo;
	private Integer textModeExtraLines;
	private Character pageNumber;
	private Character pgNoPosition;
	private Integer pgNoFontSize;
	private char pgNoVerticalPosition;
	private char footerVerticalPosition;
	private Set hospPrintMasters = new HashSet(0);

	public PrinterDefinitionModel() {
	}

	public PrinterDefinitionModel(int printerId, String printerDefinitionName, char repeatPatientInfo,
			char pgNoVerticalPosition, char footerVerticalPosition) {
		this.printerId = printerId;
		this.printerDefinitionName = printerDefinitionName;
		this.repeatPatientInfo = repeatPatientInfo;
		this.pgNoVerticalPosition = pgNoVerticalPosition;
		this.footerVerticalPosition = footerVerticalPosition;
	}

	public PrinterDefinitionModel(int printerId, String printerDefinitionName, Character printMode, Character logoHeader,
			Character footer, Character continuousFeed, Integer pageHeight, Integer topMargin, Integer bottomMargin,
			Integer leftMargin, String fontName, Integer fontSize, Integer pageWidth, Integer textModeColumn,
			Integer rightMargin, Character orientation, Character status, char repeatPatientInfo,
			Integer textModeExtraLines, Character pageNumber, Character pgNoPosition, Integer pgNoFontSize,
			char pgNoVerticalPosition, char footerVerticalPosition, Set hospPrintMasters) {
		this.printerId = printerId;
		this.printerDefinitionName = printerDefinitionName;
		this.printMode = printMode;
		this.logoHeader = logoHeader;
		this.footer = footer;
		this.continuousFeed = continuousFeed;
		this.pageHeight = pageHeight;
		this.topMargin = topMargin;
		this.bottomMargin = bottomMargin;
		this.leftMargin = leftMargin;
		this.fontName = fontName;
		this.fontSize = fontSize;
		this.pageWidth = pageWidth;
		this.textModeColumn = textModeColumn;
		this.rightMargin = rightMargin;
		this.orientation = orientation;
		this.status = status;
		this.repeatPatientInfo = repeatPatientInfo;
		this.textModeExtraLines = textModeExtraLines;
		this.pageNumber = pageNumber;
		this.pgNoPosition = pgNoPosition;
		this.pgNoFontSize = pgNoFontSize;
		this.pgNoVerticalPosition = pgNoVerticalPosition;
		this.footerVerticalPosition = footerVerticalPosition;
		this.hospPrintMasters = hospPrintMasters;
	}

	@Id

	@Column(name = "printer_id", unique = true, nullable = false)
	public int getPrinterId() {
		return this.printerId;
	}

	public void setPrinterId(int printerId) {
		this.printerId = printerId;
	}

	@Column(name = "printer_definition_name", nullable = false, length = 100)
	public String getPrinterDefinitionModelName() {
		return this.printerDefinitionName;
	}

	public void setPrinterDefinitionModelName(String printerDefinitionName) {
		this.printerDefinitionName = printerDefinitionName;
	}

	@Column(name = "print_mode", length = 1)
	public Character getPrintMode() {
		return this.printMode;
	}

	public void setPrintMode(Character printMode) {
		this.printMode = printMode;
	}

	@Column(name = "logo_header", length = 1)
	public Character getLogoHeader() {
		return this.logoHeader;
	}

	public void setLogoHeader(Character logoHeader) {
		this.logoHeader = logoHeader;
	}

	@Column(name = "footer", length = 1)
	public Character getFooter() {
		return this.footer;
	}

	public void setFooter(Character footer) {
		this.footer = footer;
	}

	@Column(name = "continuous_feed", length = 1)
	public Character getContinuousFeed() {
		return this.continuousFeed;
	}

	public void setContinuousFeed(Character continuousFeed) {
		this.continuousFeed = continuousFeed;
	}

	@Column(name = "page_height")
	public Integer getPageHeight() {
		return this.pageHeight;
	}

	public void setPageHeight(Integer pageHeight) {
		this.pageHeight = pageHeight;
	}

	@Column(name = "top_margin")
	public Integer getTopMargin() {
		return this.topMargin;
	}

	public void setTopMargin(Integer topMargin) {
		this.topMargin = topMargin;
	}

	@Column(name = "bottom_margin")
	public Integer getBottomMargin() {
		return this.bottomMargin;
	}

	public void setBottomMargin(Integer bottomMargin) {
		this.bottomMargin = bottomMargin;
	}

	@Column(name = "left_margin")
	public Integer getLeftMargin() {
		return this.leftMargin;
	}

	public void setLeftMargin(Integer leftMargin) {
		this.leftMargin = leftMargin;
	}

	@Column(name = "font_name", length = 50)
	public String getFontName() {
		return this.fontName;
	}

	public void setFontName(String fontName) {
		this.fontName = fontName;
	}

	@Column(name = "font_size")
	public Integer getFontSize() {
		return this.fontSize;
	}

	public void setFontSize(Integer fontSize) {
		this.fontSize = fontSize;
	}

	@Column(name = "page_width")
	public Integer getPageWidth() {
		return this.pageWidth;
	}

	public void setPageWidth(Integer pageWidth) {
		this.pageWidth = pageWidth;
	}

	@Column(name = "text_mode_column")
	public Integer getTextModeColumn() {
		return this.textModeColumn;
	}

	public void setTextModeColumn(Integer textModeColumn) {
		this.textModeColumn = textModeColumn;
	}

	@Column(name = "right_margin")
	public Integer getRightMargin() {
		return this.rightMargin;
	}

	public void setRightMargin(Integer rightMargin) {
		this.rightMargin = rightMargin;
	}

	@Column(name = "orientation", length = 1)
	public Character getOrientation() {
		return this.orientation;
	}

	public void setOrientation(Character orientation) {
		this.orientation = orientation;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "repeat_patient_info", nullable = false, length = 1)
	public char getRepeatPatientInfo() {
		return this.repeatPatientInfo;
	}

	public void setRepeatPatientInfo(char repeatPatientInfo) {
		this.repeatPatientInfo = repeatPatientInfo;
	}

	@Column(name = "text_mode_extra_lines")
	public Integer getTextModeExtraLines() {
		return this.textModeExtraLines;
	}

	public void setTextModeExtraLines(Integer textModeExtraLines) {
		this.textModeExtraLines = textModeExtraLines;
	}

	@Column(name = "page_number", length = 1)
	public Character getPageNumber() {
		return this.pageNumber;
	}

	public void setPageNumber(Character pageNumber) {
		this.pageNumber = pageNumber;
	}

	@Column(name = "pg_no_position", length = 1)
	public Character getPgNoPosition() {
		return this.pgNoPosition;
	}

	public void setPgNoPosition(Character pgNoPosition) {
		this.pgNoPosition = pgNoPosition;
	}

	@Column(name = "pg_no_font_size")
	public Integer getPgNoFontSize() {
		return this.pgNoFontSize;
	}

	public void setPgNoFontSize(Integer pgNoFontSize) {
		this.pgNoFontSize = pgNoFontSize;
	}

	@Column(name = "pg_no_vertical_position", nullable = false, length = 1)
	public char getPgNoVerticalPosition() {
		return this.pgNoVerticalPosition;
	}

	public void setPgNoVerticalPosition(char pgNoVerticalPosition) {
		this.pgNoVerticalPosition = pgNoVerticalPosition;
	}

	@Column(name = "footer_vertical_position", nullable = false, length = 1)
	public char getFooterVerticalPosition() {
		return this.footerVerticalPosition;
	}

	public void setFooterVerticalPosition(char footerVerticalPosition) {
		this.footerVerticalPosition = footerVerticalPosition;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "printerDefinition")
	public Set getHospPrintMasters() {
		return this.hospPrintMasters;
	}

	public void setHospPrintMasters(Set hospPrintMasters) {
		this.hospPrintMasters = hospPrintMasters;
	}

}
