package com.insta.hms.mdm.depositreceiptrefundprinttemplates;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DepositReceiptRefundTemplateModel generated by hbm2java
 */
@Entity
@Table(name = "deposit_receipt_refund_template")
public class DepositReceiptRefundTemplateModel implements java.io.Serializable {

	private DepositReceiptRefundTemplateIdSequence id;

	public DepositReceiptRefundTemplateModel() {
	}

	public DepositReceiptRefundTemplateModel(DepositReceiptRefundTemplateIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", length = 50)),
			@AttributeOverride(name = "templateContent", column = @Column(name = "template_content")),
			@AttributeOverride(name = "templateMode", column = @Column(name = "template_mode", length = 1)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 100)),
			@AttributeOverride(name = "reason", column = @Column(name = "reason", length = 500)) })
	public DepositReceiptRefundTemplateIdSequence getId() {
		return this.id;
	}

	public void setId(DepositReceiptRefundTemplateIdSequence id) {
		this.id = id;
	}

}
