package com.insta.hms.mdm.genericclassifications;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GenericClassificationMasterModel generated by hbm2java
 */
@Entity
@Table(name = "generic_classification_master")
public class GenericClassificationMasterModel implements java.io.Serializable {

	private int classificationId;
	private String classificationName;
	private Set genericSubClassificationMasters = new HashSet(0);

	public GenericClassificationMasterModel() {
	}

	public GenericClassificationMasterModel(int classificationId, String classificationName) {
		this.classificationId = classificationId;
		this.classificationName = classificationName;
	}

	public GenericClassificationMasterModel(int classificationId, String classificationName,
			Set genericSubClassificationMasters) {
		this.classificationId = classificationId;
		this.classificationName = classificationName;
		this.genericSubClassificationMasters = genericSubClassificationMasters;
	}

	@Id

	@Column(name = "classification_id", unique = true, nullable = false)
	public int getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(int classificationId) {
		this.classificationId = classificationId;
	}

	@Column(name = "classification_name", nullable = false, length = 100)
	public String getClassificationName() {
		return this.classificationName;
	}

	public void setClassificationName(String classificationName) {
		this.classificationName = classificationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genericClassificationMaster")
	public Set getGenericSubClassificationMasters() {
		return this.genericSubClassificationMasters;
	}

	public void setGenericSubClassificationMasters(Set genericSubClassificationMasters) {
		this.genericSubClassificationMasters = genericSubClassificationMasters;
	}

}
