package com.insta.hms.mdm.formcomponents;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FormComponentsModel generated by hbm2java
 */
@Entity
@Table(name = "form_components")
public class FormComponentsModel implements java.io.Serializable {

	private FormComponentsIdSequence id;

	public FormComponentsModel() {
	}

	public FormComponentsModel(FormComponentsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "deptId", column = @Column(name = "dept_id", length = 50)),
			@AttributeOverride(name = "sections", column = @Column(name = "sections")),
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "groupPatientSections", column = @Column(name = "group_patient_sections", length = 1)),
			@AttributeOverride(name = "formType", column = @Column(name = "form_type", length = 50)),
			@AttributeOverride(name = "operationId", column = @Column(name = "operation_id", length = 10)),
			@AttributeOverride(name = "serviceId", column = @Column(name = "service_id", length = 50)),
			@AttributeOverride(name = "formName", column = @Column(name = "form_name", length = 1000)),
			@AttributeOverride(name = "immunization", column = @Column(name = "immunization", length = 1)),
			@AttributeOverride(name = "printTemplateId", column = @Column(name = "print_template_id")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "docType", column = @Column(name = "doc_type", length = 50)) })
	public FormComponentsIdSequence getId() {
		return this.id;
	}

	public void setId(FormComponentsIdSequence id) {
		this.id = id;
	}

}
