package com.insta.hms.mdm.organization;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrganizationDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "organization_details")
public class OrganizationDetailsModel implements java.io.Serializable {

	private String orgId;
	private String orgName;
	private String orgAbbreviation;
	private String orgAddress;
	private String orgCity;
	private String orgState;
	private String orgCountry;
	private BigDecimal orgPincode;
	private String orgPhone;
	private String orgPhone2;
	private String orgFax;
	private String orgMailid;
	private String orgWebsite;
	private String orgContactPerson;
	private Character status;
	private String consCode;
	private String revisitCode;
	private String privateConsCode;
	private String privateConsRevisitCode;
	private String moddConsCode;
	private String moddConsRevisitCode;
	private String splConsCode;
	private String splConsRevisitCode;
	private BigDecimal pharmacyDiscountPercentage;
	private Boolean hasDateValidity;
	private Date validFromDate;
	private Date validToDate;
	private String rateVariation;
	private Character pharmacyDiscountType;
	private Integer storeRatePlanId;
	private char eligibleToEarnPoints;
	private Date createdTimestamp;
	private Date updatedTimestamp;
	private char isRateSheet;
	private Set ratePlanParametersesForBaseRateSheetId = new HashSet(0);
	private Set serviceOrgDetailses = new HashSet(0);
	private Set dynaPackageOrgDetailses = new HashSet(0);
	private Set ratePlanParametersesForOrgId = new HashSet(0);
	private Set testOrgDetailses = new HashSet(0);
	private Set operationOrgDetailses = new HashSet(0);

	public OrganizationDetailsModel() {
	}

	public OrganizationDetailsModel(String orgId, char eligibleToEarnPoints, Date createdTimestamp, Date updatedTimestamp,
			char isRateSheet) {
		this.orgId = orgId;
		this.eligibleToEarnPoints = eligibleToEarnPoints;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
		this.isRateSheet = isRateSheet;
	}

	public OrganizationDetailsModel(String orgId, String orgName, String orgAbbreviation, String orgAddress, String orgCity,
			String orgState, String orgCountry, BigDecimal orgPincode, String orgPhone, String orgPhone2, String orgFax,
			String orgMailid, String orgWebsite, String orgContactPerson, Character status, String consCode,
			String revisitCode, String privateConsCode, String privateConsRevisitCode, String moddConsCode,
			String moddConsRevisitCode, String splConsCode, String splConsRevisitCode,
			BigDecimal pharmacyDiscountPercentage, Boolean hasDateValidity, Date validFromDate, Date validToDate,
			String rateVariation, Character pharmacyDiscountType, Integer storeRatePlanId, char eligibleToEarnPoints,
			Date createdTimestamp, Date updatedTimestamp, char isRateSheet, Set ratePlanParametersesForBaseRateSheetId,
			Set serviceOrgDetailses, Set dynaPackageOrgDetailses, Set ratePlanParametersesForOrgId,
			Set testOrgDetailses, Set operationOrgDetailses) {
		this.orgId = orgId;
		this.orgName = orgName;
		this.orgAbbreviation = orgAbbreviation;
		this.orgAddress = orgAddress;
		this.orgCity = orgCity;
		this.orgState = orgState;
		this.orgCountry = orgCountry;
		this.orgPincode = orgPincode;
		this.orgPhone = orgPhone;
		this.orgPhone2 = orgPhone2;
		this.orgFax = orgFax;
		this.orgMailid = orgMailid;
		this.orgWebsite = orgWebsite;
		this.orgContactPerson = orgContactPerson;
		this.status = status;
		this.consCode = consCode;
		this.revisitCode = revisitCode;
		this.privateConsCode = privateConsCode;
		this.privateConsRevisitCode = privateConsRevisitCode;
		this.moddConsCode = moddConsCode;
		this.moddConsRevisitCode = moddConsRevisitCode;
		this.splConsCode = splConsCode;
		this.splConsRevisitCode = splConsRevisitCode;
		this.pharmacyDiscountPercentage = pharmacyDiscountPercentage;
		this.hasDateValidity = hasDateValidity;
		this.validFromDate = validFromDate;
		this.validToDate = validToDate;
		this.rateVariation = rateVariation;
		this.pharmacyDiscountType = pharmacyDiscountType;
		this.storeRatePlanId = storeRatePlanId;
		this.eligibleToEarnPoints = eligibleToEarnPoints;
		this.createdTimestamp = createdTimestamp;
		this.updatedTimestamp = updatedTimestamp;
		this.isRateSheet = isRateSheet;
		this.ratePlanParametersesForBaseRateSheetId = ratePlanParametersesForBaseRateSheetId;
		this.serviceOrgDetailses = serviceOrgDetailses;
		this.dynaPackageOrgDetailses = dynaPackageOrgDetailses;
		this.ratePlanParametersesForOrgId = ratePlanParametersesForOrgId;
		this.testOrgDetailses = testOrgDetailses;
		this.operationOrgDetailses = operationOrgDetailses;
	}

	@Id

	@Column(name = "org_id", unique = true, nullable = false, length = 10)
	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "org_name", length = 100)
	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Column(name = "org_abbreviation", length = 100)
	public String getOrgAbbreviation() {
		return this.orgAbbreviation;
	}

	public void setOrgAbbreviation(String orgAbbreviation) {
		this.orgAbbreviation = orgAbbreviation;
	}

	@Column(name = "org_address", length = 100)
	public String getOrgAddress() {
		return this.orgAddress;
	}

	public void setOrgAddress(String orgAddress) {
		this.orgAddress = orgAddress;
	}

	@Column(name = "org_city", length = 20)
	public String getOrgCity() {
		return this.orgCity;
	}

	public void setOrgCity(String orgCity) {
		this.orgCity = orgCity;
	}

	@Column(name = "org_state", length = 20)
	public String getOrgState() {
		return this.orgState;
	}

	public void setOrgState(String orgState) {
		this.orgState = orgState;
	}

	@Column(name = "org_country", length = 20)
	public String getOrgCountry() {
		return this.orgCountry;
	}

	public void setOrgCountry(String orgCountry) {
		this.orgCountry = orgCountry;
	}

	@Column(name = "org_pincode", precision = 131089, scale = 0)
	public BigDecimal getOrgPincode() {
		return this.orgPincode;
	}

	public void setOrgPincode(BigDecimal orgPincode) {
		this.orgPincode = orgPincode;
	}

	@Column(name = "org_phone", length = 15)
	public String getOrgPhone() {
		return this.orgPhone;
	}

	public void setOrgPhone(String orgPhone) {
		this.orgPhone = orgPhone;
	}

	@Column(name = "org_phone2", length = 15)
	public String getOrgPhone2() {
		return this.orgPhone2;
	}

	public void setOrgPhone2(String orgPhone2) {
		this.orgPhone2 = orgPhone2;
	}

	@Column(name = "org_fax", length = 20)
	public String getOrgFax() {
		return this.orgFax;
	}

	public void setOrgFax(String orgFax) {
		this.orgFax = orgFax;
	}

	@Column(name = "org_mailid", length = 70)
	public String getOrgMailid() {
		return this.orgMailid;
	}

	public void setOrgMailid(String orgMailid) {
		this.orgMailid = orgMailid;
	}

	@Column(name = "org_website", length = 70)
	public String getOrgWebsite() {
		return this.orgWebsite;
	}

	public void setOrgWebsite(String orgWebsite) {
		this.orgWebsite = orgWebsite;
	}

	@Column(name = "org_contact_person", length = 70)
	public String getOrgContactPerson() {
		return this.orgContactPerson;
	}

	public void setOrgContactPerson(String orgContactPerson) {
		this.orgContactPerson = orgContactPerson;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "cons_code", length = 20)
	public String getConsCode() {
		return this.consCode;
	}

	public void setConsCode(String consCode) {
		this.consCode = consCode;
	}

	@Column(name = "revisit_code", length = 20)
	public String getRevisitCode() {
		return this.revisitCode;
	}

	public void setRevisitCode(String revisitCode) {
		this.revisitCode = revisitCode;
	}

	@Column(name = "private_cons_code", length = 20)
	public String getPrivateConsCode() {
		return this.privateConsCode;
	}

	public void setPrivateConsCode(String privateConsCode) {
		this.privateConsCode = privateConsCode;
	}

	@Column(name = "private_cons_revisit_code", length = 20)
	public String getPrivateConsRevisitCode() {
		return this.privateConsRevisitCode;
	}

	public void setPrivateConsRevisitCode(String privateConsRevisitCode) {
		this.privateConsRevisitCode = privateConsRevisitCode;
	}

	@Column(name = "modd_cons_code", length = 20)
	public String getModdConsCode() {
		return this.moddConsCode;
	}

	public void setModdConsCode(String moddConsCode) {
		this.moddConsCode = moddConsCode;
	}

	@Column(name = "modd_cons_revisit_code", length = 20)
	public String getModdConsRevisitCode() {
		return this.moddConsRevisitCode;
	}

	public void setModdConsRevisitCode(String moddConsRevisitCode) {
		this.moddConsRevisitCode = moddConsRevisitCode;
	}

	@Column(name = "spl_cons_code", length = 20)
	public String getSplConsCode() {
		return this.splConsCode;
	}

	public void setSplConsCode(String splConsCode) {
		this.splConsCode = splConsCode;
	}

	@Column(name = "spl_cons_revisit_code", length = 20)
	public String getSplConsRevisitCode() {
		return this.splConsRevisitCode;
	}

	public void setSplConsRevisitCode(String splConsRevisitCode) {
		this.splConsRevisitCode = splConsRevisitCode;
	}

	@Column(name = "pharmacy_discount_percentage", precision = 15)
	public BigDecimal getPharmacyDiscountPercentage() {
		return this.pharmacyDiscountPercentage;
	}

	public void setPharmacyDiscountPercentage(BigDecimal pharmacyDiscountPercentage) {
		this.pharmacyDiscountPercentage = pharmacyDiscountPercentage;
	}

	@Column(name = "has_date_validity")
	public Boolean getHasDateValidity() {
		return this.hasDateValidity;
	}

	public void setHasDateValidity(Boolean hasDateValidity) {
		this.hasDateValidity = hasDateValidity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from_date", length = 13)
	public Date getValidFromDate() {
		return this.validFromDate;
	}

	public void setValidFromDate(Date validFromDate) {
		this.validFromDate = validFromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to_date", length = 13)
	public Date getValidToDate() {
		return this.validToDate;
	}

	public void setValidToDate(Date validToDate) {
		this.validToDate = validToDate;
	}

	@Column(name = "rate_variation", length = 100)
	public String getRateVariation() {
		return this.rateVariation;
	}

	public void setRateVariation(String rateVariation) {
		this.rateVariation = rateVariation;
	}

	@Column(name = "pharmacy_discount_type", length = 1)
	public Character getPharmacyDiscountType() {
		return this.pharmacyDiscountType;
	}

	public void setPharmacyDiscountType(Character pharmacyDiscountType) {
		this.pharmacyDiscountType = pharmacyDiscountType;
	}

	@Column(name = "store_rate_plan_id")
	public Integer getStoreRatePlanId() {
		return this.storeRatePlanId;
	}

	public void setStoreRatePlanId(Integer storeRatePlanId) {
		this.storeRatePlanId = storeRatePlanId;
	}

	@Column(name = "eligible_to_earn_points", nullable = false, length = 1)
	public char getEligibleToEarnPoints() {
		return this.eligibleToEarnPoints;
	}

	public void setEligibleToEarnPoints(char eligibleToEarnPoints) {
		this.eligibleToEarnPoints = eligibleToEarnPoints;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_timestamp", nullable = false, length = 29)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_timestamp", nullable = false, length = 29)
	public Date getUpdatedTimestamp() {
		return this.updatedTimestamp;
	}

	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	@Column(name = "is_rate_sheet", nullable = false, length = 1)
	public char getIsRateSheet() {
		return this.isRateSheet;
	}

	public void setIsRateSheet(char isRateSheet) {
		this.isRateSheet = isRateSheet;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationDetailsByBaseRateSheetId")
	public Set getRatePlanParametersesForBaseRateSheetId() {
		return this.ratePlanParametersesForBaseRateSheetId;
	}

	public void setRatePlanParametersesForBaseRateSheetId(Set ratePlanParametersesForBaseRateSheetId) {
		this.ratePlanParametersesForBaseRateSheetId = ratePlanParametersesForBaseRateSheetId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationDetails")
	public Set getServiceOrgDetailses() {
		return this.serviceOrgDetailses;
	}

	public void setServiceOrgDetailses(Set serviceOrgDetailses) {
		this.serviceOrgDetailses = serviceOrgDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationDetails")
	public Set getDynaPackageOrgDetailses() {
		return this.dynaPackageOrgDetailses;
	}

	public void setDynaPackageOrgDetailses(Set dynaPackageOrgDetailses) {
		this.dynaPackageOrgDetailses = dynaPackageOrgDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationDetailsByOrgId")
	public Set getRatePlanParametersesForOrgId() {
		return this.ratePlanParametersesForOrgId;
	}

	public void setRatePlanParametersesForOrgId(Set ratePlanParametersesForOrgId) {
		this.ratePlanParametersesForOrgId = ratePlanParametersesForOrgId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationDetails")
	public Set getTestOrgDetailses() {
		return this.testOrgDetailses;
	}

	public void setTestOrgDetailses(Set testOrgDetailses) {
		this.testOrgDetailses = testOrgDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationDetails")
	public Set getOperationOrgDetailses() {
		return this.operationOrgDetailses;
	}

	public void setOperationOrgDetailses(Set operationOrgDetailses) {
		this.operationOrgDetailses = operationOrgDetailses;
	}

}
