package com.insta.hms.mdm.diagnosiscodefavourites;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MrdCodesDoctorMasterModel generated by hbm2java
 */
@Entity
@Table(name = "mrd_codes_doctor_master", uniqueConstraints = @UniqueConstraint(columnNames = { "code_type", "code",
		"doctor_id" }))
public class MrdCodesDoctorMasterModel implements java.io.Serializable {

	private int codeDocId;
	private String codeType;
	private String code;
	private String doctorId;

	public MrdCodesDoctorMasterModel() {
	}

	public MrdCodesDoctorMasterModel(int codeDocId) {
		this.codeDocId = codeDocId;
	}

	public MrdCodesDoctorMasterModel(int codeDocId, String codeType, String code, String doctorId) {
		this.codeDocId = codeDocId;
		this.codeType = codeType;
		this.code = code;
		this.doctorId = doctorId;
	}

	@Id

	@Column(name = "code_doc_id", unique = true, nullable = false)
	public int getCodeDocId() {
		return this.codeDocId;
	}

	public void setCodeDocId(int codeDocId) {
		this.codeDocId = codeDocId;
	}

	@Column(name = "code_type", length = 20)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "code", length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "doctor_id", length = 20)
	public String getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

}
