package com.insta.hms.core.clinical.order.otheritmes;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtherServicesPrescribedModel generated by hbm2java
 */
@Entity
@Table(name = "other_services_prescribed")
public class OtherServicesPrescribedModel implements java.io.Serializable {

	private int prescribedId;
	private String mrNo;
	private String patientId;
	private String serviceGroup;
	private String serviceName;
	private BigDecimal quantity;
	private String remarks;
	private String doctorId;
	private Date presTime;
	private String otDocRole;
	private String cancelStatus;
	private Integer operationRef;
	private Integer commonOrderId;
	private String userName;
	private Integer packageRef;

	public OtherServicesPrescribedModel() {
	}

	public OtherServicesPrescribedModel(int prescribedId, String mrNo, String patientId, String serviceGroup,
			String serviceName) {
		this.prescribedId = prescribedId;
		this.mrNo = mrNo;
		this.patientId = patientId;
		this.serviceGroup = serviceGroup;
		this.serviceName = serviceName;
	}

	public OtherServicesPrescribedModel(int prescribedId, String mrNo, String patientId, String serviceGroup,
			String serviceName, BigDecimal quantity, String remarks, String doctorId, Date presTime, String otDocRole,
			String cancelStatus, Integer operationRef, Integer commonOrderId, String userName, Integer packageRef) {
		this.prescribedId = prescribedId;
		this.mrNo = mrNo;
		this.patientId = patientId;
		this.serviceGroup = serviceGroup;
		this.serviceName = serviceName;
		this.quantity = quantity;
		this.remarks = remarks;
		this.doctorId = doctorId;
		this.presTime = presTime;
		this.otDocRole = otDocRole;
		this.cancelStatus = cancelStatus;
		this.operationRef = operationRef;
		this.commonOrderId = commonOrderId;
		this.userName = userName;
		this.packageRef = packageRef;
	}

	@Id

	@Column(name = "prescribed_id", unique = true, nullable = false)
	public int getPrescribedId() {
		return this.prescribedId;
	}

	public void setPrescribedId(int prescribedId) {
		this.prescribedId = prescribedId;
	}

	@Column(name = "mr_no", nullable = false, length = 20)
	public String getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	@Column(name = "patient_id", nullable = false, length = 20)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "service_group", nullable = false, length = 50)
	public String getServiceGroup() {
		return this.serviceGroup;
	}

	public void setServiceGroup(String serviceGroup) {
		this.serviceGroup = serviceGroup;
	}

	@Column(name = "service_name", nullable = false, length = 50)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "quantity", precision = 131089, scale = 0)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "doctor_id", length = 20)
	public String getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pres_time", length = 29)
	public Date getPresTime() {
		return this.presTime;
	}

	public void setPresTime(Date presTime) {
		this.presTime = presTime;
	}

	@Column(name = "ot_doc_role", length = 20)
	public String getOtDocRole() {
		return this.otDocRole;
	}

	public void setOtDocRole(String otDocRole) {
		this.otDocRole = otDocRole;
	}

	@Column(name = "cancel_status")
	public String getCancelStatus() {
		return this.cancelStatus;
	}

	public void setCancelStatus(String cancelStatus) {
		this.cancelStatus = cancelStatus;
	}

	@Column(name = "operation_ref")
	public Integer getOperationRef() {
		return this.operationRef;
	}

	public void setOperationRef(Integer operationRef) {
		this.operationRef = operationRef;
	}

	@Column(name = "common_order_id")
	public Integer getCommonOrderId() {
		return this.commonOrderId;
	}

	public void setCommonOrderId(Integer commonOrderId) {
		this.commonOrderId = commonOrderId;
	}

	@Column(name = "user_name", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "package_ref")
	public Integer getPackageRef() {
		return this.packageRef;
	}

	public void setPackageRef(Integer packageRef) {
		this.packageRef = packageRef;
	}

}
