package com.insta.hms.mdm.microabstantibiotics;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MicroAbstAntibioticMasterModel generated by hbm2java
 */
@Entity
@Table(name = "micro_abst_antibiotic_master")
public class MicroAbstAntibioticMasterModel implements java.io.Serializable {

	private MicroAbstAntibioticMasterIdSequence id;

	public MicroAbstAntibioticMasterModel() {
	}

	public MicroAbstAntibioticMasterModel(MicroAbstAntibioticMasterIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "antibioticId", column = @Column(name = "antibiotic_id", nullable = false)),
			@AttributeOverride(name = "abstPanelId", column = @Column(name = "abst_panel_id", nullable = false)) })
	public MicroAbstAntibioticMasterIdSequence getId() {
		return this.id;
	}

	public void setId(MicroAbstAntibioticMasterIdSequence id) {
		this.id = id;
	}

}
