package com.insta.hms.mdm.microabstantibiotics;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MicroAbstAntibioticMasterIdSequence generated by hbm2java
 */
@Embeddable
public class MicroAbstAntibioticMasterIdSequence implements java.io.Serializable {

	private int antibioticId;
	private int abstPanelId;

	public MicroAbstAntibioticMasterIdSequence() {
	}

	public MicroAbstAntibioticMasterIdSequence(int antibioticId, int abstPanelId) {
		this.antibioticId = antibioticId;
		this.abstPanelId = abstPanelId;
	}

	@Column(name = "antibiotic_id", nullable = false)
	public int getAntibioticId() {
		return this.antibioticId;
	}

	public void setAntibioticId(int antibioticId) {
		this.antibioticId = antibioticId;
	}

	@Column(name = "abst_panel_id", nullable = false)
	public int getAbstPanelId() {
		return this.abstPanelId;
	}

	public void setAbstPanelId(int abstPanelId) {
		this.abstPanelId = abstPanelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MicroAbstAntibioticMasterIdSequence))
			return false;
		MicroAbstAntibioticMasterIdSequence castOther = (MicroAbstAntibioticMasterIdSequence) other;

		return (this.getAntibioticId() == castOther.getAntibioticId())
				&& (this.getAbstPanelId() == castOther.getAbstPanelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAntibioticId();
		result = 37 * result + this.getAbstPanelId();
		return result;
	}

}
