package com.insta.hms.mdm.imagemarkers;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImageMarkersModel generated by hbm2java
 */
@Entity
@Table(name = "image_markers")
public class ImageMarkersModel implements java.io.Serializable {

	private ImageMarkersIdSequence id;

	public ImageMarkersModel() {
	}

	public ImageMarkersModel(ImageMarkersIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "imageId", column = @Column(name = "image_id", nullable = false)),
			@AttributeOverride(name = "label", column = @Column(name = "label", nullable = false, length = 200)),
			@AttributeOverride(name = "fileContent", column = @Column(name = "file_content")),
			@AttributeOverride(name = "contentType", column = @Column(name = "content_type", length = 500)),
			@AttributeOverride(name = "filename", column = @Column(name = "filename", length = 1000)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)) })
	public ImageMarkersIdSequence getId() {
		return this.id;
	}

	public void setId(ImageMarkersIdSequence id) {
		this.id = id;
	}

}
