package com.insta.hms.core.billing;
// Generated 28 Aug, 2018 12:23:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BillClaim generated by hbm2java
 */
@Entity
@Table(name = "bill_claim")
public class BillClaimModel implements java.io.Serializable {

	private BillClaimIdSequence id;

	public BillClaimModel() {
	}

	public BillClaimModel(BillClaimIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "visitId", column = @Column(name = "visit_id", nullable = false, length = 15)),
			@AttributeOverride(name = "billNo", column = @Column(name = "bill_no", nullable = false, length = 15)),
			@AttributeOverride(name = "planId", column = @Column(name = "plan_id", nullable = false)),
			@AttributeOverride(name = "sponsorId", column = @Column(name = "sponsor_id", nullable = false, length = 20)),
			@AttributeOverride(name = "claimId", column = @Column(name = "claim_id", nullable = false, length = 15)),
			@AttributeOverride(name = "priority", column = @Column(name = "priority")),
			@AttributeOverride(name = "claimStatus", column = @Column(name = "claim_status", length = 1)) })
	public BillClaimIdSequence getId() {
		return this.id;
	}

	public void setId(BillClaimIdSequence id) {
		this.id = id;
	}

}