package com.insta.hms.core.billing;
// Generated 28 Aug, 2018 12:23:10 PM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonView;
import com.insta.hms.core.diagnostics.incomingsampleregistration.IncomingSampleRegistrationModel;
import com.insta.hms.core.insurance.InsuranceClaimModel;
import com.insta.hms.core.patient.registration.PatientRegistrationModel;
import com.insta.hms.model.StoreRetailCustomersModel;
import com.insta.hms.util.ViewProfiles;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "bill")
public class BillModel implements java.io.Serializable {

  @JsonView(ViewProfiles.Public.class)
  private String billNo;
  @JsonView(ViewProfiles.Public.class)
  private PatientRegistrationModel visitId;
  @JsonView(ViewProfiles.Public.class)
  private char billType;
  @JsonView(ViewProfiles.Public.class)
  private Date openDate;
  @JsonView(ViewProfiles.Public.class)
  private char status;
  @JsonView(ViewProfiles.Public.class)
  private Date finalizedDate;
  @JsonView(ViewProfiles.Public.class)
  private Date lastFinalizedAt;
  @JsonView(ViewProfiles.Public.class)
  private Date closedDate;
  @JsonView(ViewProfiles.Public.class)
  private String username;
  @JsonView(ViewProfiles.Public.class)
  private char dischargeStatus;
  @JsonView(ViewProfiles.Public.class)
  private char appModified;
  @JsonView(ViewProfiles.Public.class)
  private Character visitType;
  @JsonView(ViewProfiles.Public.class)
  private String remarks;
  @JsonView(ViewProfiles.Public.class)
  private String closedBy;
  @JsonView(ViewProfiles.Public.class)
  private String openedBy;
  @JsonView(ViewProfiles.Public.class)
  private Date modTime;
  @JsonView(ViewProfiles.Public.class)
  private Character primaryClaimStatus;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal claimRecdAmount;
  @JsonView(ViewProfiles.Public.class)
  private String cancelReason;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal depositSetOff;
  @JsonView(ViewProfiles.Public.class)
  private Integer discountAuth;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal approvalAmount;
  @JsonView(ViewProfiles.Public.class)
  private Character restrictionType;
  @JsonView(ViewProfiles.Public.class)
  private int accountGroup;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalAmount;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalDiscount;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalClaim;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalReceipts;
  @JsonView(ViewProfiles.Public.class)
  private Integer noOfReceipts;
  @JsonView(ViewProfiles.Public.class)
  private String lastReceiptNo;
  @JsonView(ViewProfiles.Public.class)
  private int procedureNo;
  @JsonView(ViewProfiles.Public.class)
  private String sponsorBillNo;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal primaryTotalSponsorReceipts;
  @JsonView(ViewProfiles.Public.class)
  private Integer primaryNoOfSponsorReceipts;
  @JsonView(ViewProfiles.Public.class)
  private String lastSponsorReceiptNo;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal insuranceDeduction;
  @JsonView(ViewProfiles.Public.class)
  private int dynaPackageId;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal dynaPackageCharge;
  @JsonView(ViewProfiles.Public.class)
  private String obsoleteClaimId;
  @JsonView(ViewProfiles.Public.class)
  private boolean isTpa;
  @JsonView(ViewProfiles.Public.class)
  private boolean locked;
  @JsonView(ViewProfiles.Public.class)
  private char isPrimaryBill;
  @JsonView(ViewProfiles.Public.class)
  private char paymentStatus;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalClaimReturn;
  @JsonView(ViewProfiles.Public.class)
  private String finalizedBy;
  @JsonView(ViewProfiles.Public.class)
  private String billRatePlanId;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal claimRecdUnallocAmount;
  @JsonView(ViewProfiles.Public.class)
  private char dynaPkgProcessed;
  @JsonView(ViewProfiles.Public.class)
  private String billPrinted;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal primaryTotalClaim;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal secondaryTotalClaim;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal primaryApprovalAmount;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal secondaryApprovalAmount;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal secondaryTotalSponsorReceipts;
  @JsonView(ViewProfiles.Public.class)
  private Integer secondaryNoOfSponsor;
  @JsonView(ViewProfiles.Public.class)
  private Character secondaryClaimStatus;
  @JsonView(ViewProfiles.Public.class)
  private Integer nationalClaimNo;
  @JsonView(ViewProfiles.Public.class)
  private Integer billLabelId;
  @JsonView(ViewProfiles.Public.class)
  private String reopenReason;
  @JsonView(ViewProfiles.Public.class)
  private int pointsEarned;
  @JsonView(ViewProfiles.Public.class)
  private int pointsRedeemed;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal pointsRedeemedAmt;
  @JsonView(ViewProfiles.Public.class)
  private String auditControlNumber;
  @JsonView(ViewProfiles.Public.class)
  private char patientWriteoff;
  @JsonView(ViewProfiles.Public.class)
  private char sponsorWriteoff;
  @JsonView(ViewProfiles.Public.class)
  private String writeoffRemarks;
  @JsonView(ViewProfiles.Public.class)
  private String sponsorWriteoffRemarks;
  @JsonView(ViewProfiles.Public.class)
  private String cancellationApprovalStatus;
  @JsonView(ViewProfiles.Public.class)
  private String cancellationApprovedBy;
  @JsonView(ViewProfiles.Public.class)
  private Date cancellationApprovedDate;
  @JsonView(ViewProfiles.Public.class)
  private Integer discountCategoryId;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal cancelApproveAmount;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal ipDepositSetOff;
  @JsonView(ViewProfiles.Public.class)
  private String creditNoteReasons;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalTax;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalClaimTax;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal totalOriginalTaxAmt;
  @JsonView(ViewProfiles.Public.class)
  private int selfpayBatchId;
  @JsonView(ViewProfiles.Public.class)
  private Set<InsuranceClaimModel> claims;
  @JsonView(ViewProfiles.Public.class)
  private Set<BillChargeModel> billCharges;
  @JsonView(ViewProfiles.Public.class)
  private List<ReceiptModel> receipts;
  private StoreRetailCustomersModel storeRetailCustomers;
  private IncomingSampleRegistrationModel incomingSampleRegistration;

  public BillModel() {
  }

  public BillModel(String billNo) {
    this.billNo = billNo;
  }

  public BillModel(String billNo, PatientRegistrationModel visitId, char billType, Date openDate,
      char status, String username, char dischargeStatus, char appModified, Date modTime,
      BigDecimal claimRecdAmount, int accountGroup, BigDecimal totalAmount,
      BigDecimal totalDiscount, BigDecimal totalClaim, BigDecimal totalReceipts, int procedureNo,
      BigDecimal insuranceDeduction, int dynaPackageId, boolean isTpa, char isPrimaryBill,
      char paymentStatus, BigDecimal totalClaimReturn, String billRatePlanId,
      BigDecimal claimRecdUnallocAmount, char dynaPkgProcessed, String billPrinted,
      BigDecimal primaryTotalClaim, BigDecimal secondaryTotalClaim, int pointsEarned,
      int pointsRedeemed, BigDecimal pointsRedeemedAmt, char patientWriteoff, char sponsorWriteoff,
      BigDecimal totalTax, BigDecimal totalClaimTax, BigDecimal totalOriginalTaxAmt,
      int selfpayBatchId) {
    this.billNo = billNo;
    this.visitId = visitId;
    this.billType = billType;
    this.openDate = openDate;
    this.status = status;
    this.username = username;
    this.dischargeStatus = dischargeStatus;
    this.appModified = appModified;
    this.modTime = modTime;
    this.claimRecdAmount = claimRecdAmount;
    this.accountGroup = accountGroup;
    this.totalAmount = totalAmount;
    this.totalDiscount = totalDiscount;
    this.totalClaim = totalClaim;
    this.totalReceipts = totalReceipts;
    this.procedureNo = procedureNo;
    this.insuranceDeduction = insuranceDeduction;
    this.dynaPackageId = dynaPackageId;
    this.isTpa = isTpa;
    this.isPrimaryBill = isPrimaryBill;
    this.paymentStatus = paymentStatus;
    this.totalClaimReturn = totalClaimReturn;
    this.billRatePlanId = billRatePlanId;
    this.claimRecdUnallocAmount = claimRecdUnallocAmount;
    this.dynaPkgProcessed = dynaPkgProcessed;
    this.billPrinted = billPrinted;
    this.primaryTotalClaim = primaryTotalClaim;
    this.secondaryTotalClaim = secondaryTotalClaim;
    this.pointsEarned = pointsEarned;
    this.pointsRedeemed = pointsRedeemed;
    this.pointsRedeemedAmt = pointsRedeemedAmt;
    this.patientWriteoff = patientWriteoff;
    this.sponsorWriteoff = sponsorWriteoff;
    this.totalTax = totalTax;
    this.totalClaimTax = totalClaimTax;
    this.totalOriginalTaxAmt = totalOriginalTaxAmt;
    this.selfpayBatchId = selfpayBatchId;
  }

  public BillModel(String billNo, PatientRegistrationModel visitId, char billType, Date openDate,
      char status, Date finalizedDate, Date closedDate, String username, char dischargeStatus,
      char appModified, Character visitType, String remarks, String closedBy, String openedBy,
      Date modTime, Character primaryClaimStatus, BigDecimal claimRecdAmount, String cancelReason,
      BigDecimal depositSetOff, Integer discountAuth, BigDecimal approvalAmount,
      Character restrictionType, int accountGroup, BigDecimal totalAmount, BigDecimal totalDiscount,
      BigDecimal totalClaim, BigDecimal totalReceipts, Integer noOfReceipts, String lastReceiptNo,
      int procedureNo, String sponsorBillNo, BigDecimal primaryTotalSponsorReceipts,
      Integer primaryNoOfSponsorReceipts, String lastSponsorReceiptNo,
      BigDecimal insuranceDeduction, int dynaPackageId, BigDecimal dynaPackageCharge,
      String obsoleteClaimId, boolean isTpa, char isPrimaryBill, char paymentStatus,
      BigDecimal totalClaimReturn, String finalizedBy, String billRatePlanId,
      BigDecimal claimRecdUnallocAmount, char dynaPkgProcessed, String billPrinted,
      BigDecimal primaryTotalClaim, BigDecimal secondaryTotalClaim,
      BigDecimal primaryApprovalAmount, BigDecimal secondaryApprovalAmount,
      BigDecimal secondaryTotalSponsorReceipts, Integer secondaryNoOfSponsor,
      Character secondaryClaimStatus, Integer nationalClaimNo, Integer billLabelId,
      String reopenReason, int pointsEarned, int pointsRedeemed, BigDecimal pointsRedeemedAmt,
      String auditControlNumber, char patientWriteoff, char sponsorWriteoff, String writeoffRemarks,
      String sponsorWriteoffRemarks, String cancellationApprovalStatus,
      String cancellationApprovedBy, Date cancellationApprovedDate, Integer discountCategoryId,
      BigDecimal cancelApproveAmount, BigDecimal ipDepositSetOff, String creditNoteReasons,
      BigDecimal totalTax, BigDecimal totalClaimTax, BigDecimal totalOriginalTaxAmt,
      int selfpayBatchId, Set<InsuranceClaimModel> claims, Set<BillChargeModel> billCharges,
      List<ReceiptModel> receipts) {
    this.billNo = billNo;
    this.visitId = visitId;
    this.billType = billType;
    this.openDate = openDate;
    this.status = status;
    this.finalizedDate = finalizedDate;
    this.closedDate = closedDate;
    this.username = username;
    this.dischargeStatus = dischargeStatus;
    this.appModified = appModified;
    this.visitType = visitType;
    this.remarks = remarks;
    this.closedBy = closedBy;
    this.openedBy = openedBy;
    this.modTime = modTime;
    this.primaryClaimStatus = primaryClaimStatus;
    this.claimRecdAmount = claimRecdAmount;
    this.cancelReason = cancelReason;
    this.depositSetOff = depositSetOff;
    this.discountAuth = discountAuth;
    this.approvalAmount = approvalAmount;
    this.restrictionType = restrictionType;
    this.accountGroup = accountGroup;
    this.totalAmount = totalAmount;
    this.totalDiscount = totalDiscount;
    this.totalClaim = totalClaim;
    this.totalReceipts = totalReceipts;
    this.noOfReceipts = noOfReceipts;
    this.lastReceiptNo = lastReceiptNo;
    this.procedureNo = procedureNo;
    this.sponsorBillNo = sponsorBillNo;
    this.primaryTotalSponsorReceipts = primaryTotalSponsorReceipts;
    this.primaryNoOfSponsorReceipts = primaryNoOfSponsorReceipts;
    this.lastSponsorReceiptNo = lastSponsorReceiptNo;
    this.insuranceDeduction = insuranceDeduction;
    this.dynaPackageId = dynaPackageId;
    this.dynaPackageCharge = dynaPackageCharge;
    this.obsoleteClaimId = obsoleteClaimId;
    this.isTpa = isTpa;
    this.isPrimaryBill = isPrimaryBill;
    this.paymentStatus = paymentStatus;
    this.totalClaimReturn = totalClaimReturn;
    this.finalizedBy = finalizedBy;
    this.billRatePlanId = billRatePlanId;
    this.claimRecdUnallocAmount = claimRecdUnallocAmount;
    this.dynaPkgProcessed = dynaPkgProcessed;
    this.billPrinted = billPrinted;
    this.primaryTotalClaim = primaryTotalClaim;
    this.secondaryTotalClaim = secondaryTotalClaim;
    this.primaryApprovalAmount = primaryApprovalAmount;
    this.secondaryApprovalAmount = secondaryApprovalAmount;
    this.secondaryTotalSponsorReceipts = secondaryTotalSponsorReceipts;
    this.secondaryNoOfSponsor = secondaryNoOfSponsor;
    this.secondaryClaimStatus = secondaryClaimStatus;
    this.nationalClaimNo = nationalClaimNo;
    this.billLabelId = billLabelId;
    this.reopenReason = reopenReason;
    this.pointsEarned = pointsEarned;
    this.pointsRedeemed = pointsRedeemed;
    this.pointsRedeemedAmt = pointsRedeemedAmt;
    this.auditControlNumber = auditControlNumber;
    this.patientWriteoff = patientWriteoff;
    this.sponsorWriteoff = sponsorWriteoff;
    this.writeoffRemarks = writeoffRemarks;
    this.sponsorWriteoffRemarks = sponsorWriteoffRemarks;
    this.cancellationApprovalStatus = cancellationApprovalStatus;
    this.cancellationApprovedBy = cancellationApprovedBy;
    this.cancellationApprovedDate = cancellationApprovedDate;
    this.discountCategoryId = discountCategoryId;
    this.cancelApproveAmount = cancelApproveAmount;
    this.ipDepositSetOff = ipDepositSetOff;
    this.creditNoteReasons = creditNoteReasons;
    this.totalTax = totalTax;
    this.totalClaimTax = totalClaimTax;
    this.totalOriginalTaxAmt = totalOriginalTaxAmt;
    this.selfpayBatchId = selfpayBatchId;
    this.claims = claims;
    this.billCharges = billCharges;
    this.receipts = receipts;
  }

  @Id
  @Column(name = "bill_no", unique = true, nullable = false, length = 15)
  public String getBillNo() {
    return this.billNo;
  }

  public void setBillNo(String billNo) {
    this.billNo = billNo;
  }

  // @Column(name = "visit_id", nullable = false, length = 15)
  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "visit_id")
  @NotFound(action = NotFoundAction.IGNORE)
  public PatientRegistrationModel getVisitId() {
    return this.visitId;
  }

  public void setVisitId(PatientRegistrationModel visitId) {
    this.visitId = visitId;
  }

  @Column(name = "bill_type", nullable = false, length = 1)
  public char getBillType() {
    return this.billType;
  }

  public void setBillType(char billType) {
    this.billType = billType;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "open_date", nullable = false, length = 29)
  public Date getOpenDate() {
    return this.openDate;
  }

  public void setOpenDate(Date openDate) {
    this.openDate = openDate;
  }

  @Column(name = "status", nullable = false, length = 1)
  public char getStatus() {
    return this.status;
  }

  public void setStatus(char status) {
    this.status = status;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "finalized_date", length = 29)
  public Date getFinalizedDate() {
    return this.finalizedDate;
  }

  public void setFinalizedDate(Date finalizedDate) {
    this.finalizedDate = finalizedDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_finalized_at", length = 29)
  public Date getLastFinalizedAt() {
    return this.lastFinalizedAt;
  }

  public void setLastFinalizedAt(Date lastFinalizedAt) {
    this.lastFinalizedAt = lastFinalizedAt;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "closed_date", length = 29)
  public Date getClosedDate() {
    return this.closedDate;
  }

  public void setClosedDate(Date closedDate) {
    this.closedDate = closedDate;
  }

  @Column(name = "username", nullable = false, length = 30)
  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  @Column(name = "discharge_status", nullable = false, length = 1)
  public char getDischargeStatus() {
    return this.dischargeStatus;
  }

  public void setDischargeStatus(char dischargeStatus) {
    this.dischargeStatus = dischargeStatus;
  }

  @Column(name = "app_modified", nullable = false, length = 1)
  public char getAppModified() {
    return this.appModified;
  }

  public void setAppModified(char appModified) {
    this.appModified = appModified;
  }

  @Column(name = "visit_type", length = 1)
  public Character getVisitType() {
    return this.visitType;
  }

  public void setVisitType(Character visitType) {
    this.visitType = visitType;
  }

  @Column(name = "remarks", length = 200)
  public String getRemarks() {
    return this.remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  @Column(name = "closed_by", length = 30)
  public String getClosedBy() {
    return this.closedBy;
  }

  public void setClosedBy(String closedBy) {
    this.closedBy = closedBy;
  }

  @Column(name = "opened_by", length = 30)
  public String getOpenedBy() {
    return this.openedBy;
  }

  public void setOpenedBy(String openedBy) {
    this.openedBy = openedBy;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "mod_time", nullable = false, length = 29)
  public Date getModTime() {
    return this.modTime;
  }

  public void setModTime(Date modTime) {
    this.modTime = modTime;
  }

  @Column(name = "primary_claim_status", length = 1)
  public Character getPrimaryClaimStatus() {
    return this.primaryClaimStatus;
  }

  public void setPrimaryClaimStatus(Character primaryClaimStatus) {
    this.primaryClaimStatus = primaryClaimStatus;
  }

  @Column(name = "claim_recd_amount", nullable = false, precision = 15)
  public BigDecimal getClaimRecdAmount() {
    return this.claimRecdAmount;
  }

  public void setClaimRecdAmount(BigDecimal claimRecdAmount) {
    this.claimRecdAmount = claimRecdAmount;
  }

  @Column(name = "cancel_reason", length = 100)
  public String getCancelReason() {
    return this.cancelReason;
  }

  public void setCancelReason(String cancelReason) {
    this.cancelReason = cancelReason;
  }

  @Column(name = "deposit_set_off", precision = 15)
  public BigDecimal getDepositSetOff() {
    return this.depositSetOff;
  }

  public void setDepositSetOff(BigDecimal depositSetOff) {
    this.depositSetOff = depositSetOff;
  }

  @Column(name = "discount_auth")
  public Integer getDiscountAuth() {
    return this.discountAuth;
  }

  public void setDiscountAuth(Integer discountAuth) {
    this.discountAuth = discountAuth;
  }

  @Column(name = "approval_amount", precision = 15)
  public BigDecimal getApprovalAmount() {
    return this.approvalAmount;
  }

  public void setApprovalAmount(BigDecimal approvalAmount) {
    this.approvalAmount = approvalAmount;
  }

  @Column(name = "restriction_type", length = 1)
  public Character getRestrictionType() {
    return this.restrictionType;
  }

  public void setRestrictionType(Character restrictionType) {
    this.restrictionType = restrictionType;
  }

  @Column(name = "account_group", nullable = false)
  public int getAccountGroup() {
    return this.accountGroup;
  }

  public void setAccountGroup(int accountGroup) {
    this.accountGroup = accountGroup;
  }

  @Column(name = "total_amount", nullable = false, precision = 15)
  public BigDecimal getTotalAmount() {
    return this.totalAmount;
  }

  public void setTotalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
  }

  @Column(name = "total_discount", nullable = false, precision = 15)
  public BigDecimal getTotalDiscount() {
    return this.totalDiscount;
  }

  public void setTotalDiscount(BigDecimal totalDiscount) {
    this.totalDiscount = totalDiscount;
  }

  @Column(name = "total_claim", nullable = false, precision = 15)
  public BigDecimal getTotalClaim() {
    return this.totalClaim;
  }

  public void setTotalClaim(BigDecimal totalClaim) {
    this.totalClaim = totalClaim;
  }

  @Column(name = "total_receipts", nullable = false, precision = 15)
  public BigDecimal getTotalReceipts() {
    return this.totalReceipts;
  }

  public void setTotalReceipts(BigDecimal totalReceipts) {
    this.totalReceipts = totalReceipts;
  }

  @Column(name = "no_of_receipts")
  public Integer getNoOfReceipts() {
    return this.noOfReceipts;
  }

  public void setNoOfReceipts(Integer noOfReceipts) {
    this.noOfReceipts = noOfReceipts;
  }

  @Column(name = "last_receipt_no", length = 15)
  public String getLastReceiptNo() {
    return this.lastReceiptNo;
  }

  public void setLastReceiptNo(String lastReceiptNo) {
    this.lastReceiptNo = lastReceiptNo;
  }

  @Column(name = "procedure_no", nullable = false)
  public int getProcedureNo() {
    return this.procedureNo;
  }

  public void setProcedureNo(int procedureNo) {
    this.procedureNo = procedureNo;
  }

  @Column(name = "sponsor_bill_no", length = 15)
  public String getSponsorBillNo() {
    return this.sponsorBillNo;
  }

  public void setSponsorBillNo(String sponsorBillNo) {
    this.sponsorBillNo = sponsorBillNo;
  }

  @Column(name = "primary_total_sponsor_receipts", precision = 15)
  public BigDecimal getPrimaryTotalSponsorReceipts() {
    return this.primaryTotalSponsorReceipts;
  }

  public void setPrimaryTotalSponsorReceipts(BigDecimal primaryTotalSponsorReceipts) {
    this.primaryTotalSponsorReceipts = primaryTotalSponsorReceipts;
  }

  @Column(name = "primary_no_of_sponsor_receipts")
  public Integer getPrimaryNoOfSponsorReceipts() {
    return this.primaryNoOfSponsorReceipts;
  }

  public void setPrimaryNoOfSponsorReceipts(Integer primaryNoOfSponsorReceipts) {
    this.primaryNoOfSponsorReceipts = primaryNoOfSponsorReceipts;
  }

  @Column(name = "last_sponsor_receipt_no", length = 15)
  public String getLastSponsorReceiptNo() {
    return this.lastSponsorReceiptNo;
  }

  public void setLastSponsorReceiptNo(String lastSponsorReceiptNo) {
    this.lastSponsorReceiptNo = lastSponsorReceiptNo;
  }

  @Column(name = "insurance_deduction", nullable = false, precision = 15)
  public BigDecimal getInsuranceDeduction() {
    return this.insuranceDeduction;
  }

  public void setInsuranceDeduction(BigDecimal insuranceDeduction) {
    this.insuranceDeduction = insuranceDeduction;
  }

  @Column(name = "dyna_package_id", nullable = false)
  public int getDynaPackageId() {
    return this.dynaPackageId;
  }

  public void setDynaPackageId(int dynaPackageId) {
    this.dynaPackageId = dynaPackageId;
  }

  @Column(name = "dyna_package_charge", precision = 15)
  public BigDecimal getDynaPackageCharge() {
    return this.dynaPackageCharge;
  }

  public void setDynaPackageCharge(BigDecimal dynaPackageCharge) {
    this.dynaPackageCharge = dynaPackageCharge;
  }

  @Column(name = "obsolete_claim_id", length = 15)
  public String getObsoleteClaimId() {
    return this.obsoleteClaimId;
  }

  public void setObsoleteClaimId(String obsoleteClaimId) {
    this.obsoleteClaimId = obsoleteClaimId;
  }

  @Column(name = "is_tpa", nullable = false)
  public boolean getIsTpa() {
    return this.isTpa;
  }

  public void setLocked(boolean locked) {
    this.locked = locked;
  }

  @Column(name = "locked", nullable = true)
  public boolean getLocked() {
    return this.locked;
  }
  
  public void setIsTpa(boolean isTpa) {
    this.isTpa = isTpa;
  }

  @Column(name = "is_primary_bill", nullable = false, length = 1)
  public char getIsPrimaryBill() {
    return this.isPrimaryBill;
  }

  public void setIsPrimaryBill(char isPrimaryBill) {
    this.isPrimaryBill = isPrimaryBill;
  }

  @Column(name = "payment_status", nullable = false, length = 1)
  public char getPaymentStatus() {
    return this.paymentStatus;
  }

  public void setPaymentStatus(char paymentStatus) {
    this.paymentStatus = paymentStatus;
  }

  @Column(name = "total_claim_return", nullable = false, precision = 15)
  public BigDecimal getTotalClaimReturn() {
    return this.totalClaimReturn;
  }

  public void setTotalClaimReturn(BigDecimal totalClaimReturn) {
    this.totalClaimReturn = totalClaimReturn;
  }

  @Column(name = "finalized_by", length = 30)
  public String getFinalizedBy() {
    return this.finalizedBy;
  }

  public void setFinalizedBy(String finalizedBy) {
    this.finalizedBy = finalizedBy;
  }

  @Column(name = "bill_rate_plan_id", nullable = false, length = 10)
  public String getBillRatePlanId() {
    return this.billRatePlanId;
  }

  public void setBillRatePlanId(String billRatePlanId) {
    this.billRatePlanId = billRatePlanId;
  }

  @Column(name = "claim_recd_unalloc_amount", nullable = false, precision = 15)
  public BigDecimal getClaimRecdUnallocAmount() {
    return this.claimRecdUnallocAmount;
  }

  public void setClaimRecdUnallocAmount(BigDecimal claimRecdUnallocAmount) {
    this.claimRecdUnallocAmount = claimRecdUnallocAmount;
  }

  @Column(name = "dyna_pkg_processed", nullable = false, length = 1)
  public char getDynaPkgProcessed() {
    return this.dynaPkgProcessed;
  }

  public void setDynaPkgProcessed(char dynaPkgProcessed) {
    this.dynaPkgProcessed = dynaPkgProcessed;
  }

  @Column(name = "bill_printed", nullable = false)
  public String getBillPrinted() {
    return this.billPrinted;
  }

  public void setBillPrinted(String billPrinted) {
    this.billPrinted = billPrinted;
  }

  @Column(name = "primary_total_claim", nullable = false, precision = 15)
  public BigDecimal getPrimaryTotalClaim() {
    return this.primaryTotalClaim;
  }

  public void setPrimaryTotalClaim(BigDecimal primaryTotalClaim) {
    this.primaryTotalClaim = primaryTotalClaim;
  }

  @Column(name = "secondary_total_claim", nullable = false, precision = 15)
  public BigDecimal getSecondaryTotalClaim() {
    return this.secondaryTotalClaim;
  }

  public void setSecondaryTotalClaim(BigDecimal secondaryTotalClaim) {
    this.secondaryTotalClaim = secondaryTotalClaim;
  }

  @Column(name = "primary_approval_amount", precision = 15)
  public BigDecimal getPrimaryApprovalAmount() {
    return this.primaryApprovalAmount;
  }

  public void setPrimaryApprovalAmount(BigDecimal primaryApprovalAmount) {
    this.primaryApprovalAmount = primaryApprovalAmount;
  }

  @Column(name = "secondary_approval_amount", precision = 15)
  public BigDecimal getSecondaryApprovalAmount() {
    return this.secondaryApprovalAmount;
  }

  public void setSecondaryApprovalAmount(BigDecimal secondaryApprovalAmount) {
    this.secondaryApprovalAmount = secondaryApprovalAmount;
  }

  @Column(name = "secondary_total_sponsor_receipts", precision = 15)
  public BigDecimal getSecondaryTotalSponsorReceipts() {
    return this.secondaryTotalSponsorReceipts;
  }

  public void setSecondaryTotalSponsorReceipts(BigDecimal secondaryTotalSponsorReceipts) {
    this.secondaryTotalSponsorReceipts = secondaryTotalSponsorReceipts;
  }

  @Column(name = "secondary_no_of_sponsor")
  public Integer getSecondaryNoOfSponsor() {
    return this.secondaryNoOfSponsor;
  }

  public void setSecondaryNoOfSponsor(Integer secondaryNoOfSponsor) {
    this.secondaryNoOfSponsor = secondaryNoOfSponsor;
  }

  @Column(name = "secondary_claim_status", length = 1)
  public Character getSecondaryClaimStatus() {
    return this.secondaryClaimStatus;
  }

  public void setSecondaryClaimStatus(Character secondaryClaimStatus) {
    this.secondaryClaimStatus = secondaryClaimStatus;
  }

  @Column(name = "national_claim_no")
  public Integer getNationalClaimNo() {
    return this.nationalClaimNo;
  }

  public void setNationalClaimNo(Integer nationalClaimNo) {
    this.nationalClaimNo = nationalClaimNo;
  }

  @Column(name = "bill_label_id")
  public Integer getBillLabelId() {
    return this.billLabelId;
  }

  public void setBillLabelId(Integer billLabelId) {
    this.billLabelId = billLabelId;
  }

  @Column(name = "reopen_reason", length = 100)
  public String getReopenReason() {
    return this.reopenReason;
  }

  public void setReopenReason(String reopenReason) {
    this.reopenReason = reopenReason;
  }

  @Column(name = "points_earned", nullable = false)
  public int getPointsEarned() {
    return this.pointsEarned;
  }

  public void setPointsEarned(int pointsEarned) {
    this.pointsEarned = pointsEarned;
  }

  @Column(name = "points_redeemed", nullable = false)
  public int getPointsRedeemed() {
    return this.pointsRedeemed;
  }

  public void setPointsRedeemed(int pointsRedeemed) {
    this.pointsRedeemed = pointsRedeemed;
  }

  @Column(name = "points_redeemed_amt", nullable = false, precision = 15)
  public BigDecimal getPointsRedeemedAmt() {
    return this.pointsRedeemedAmt;
  }

  public void setPointsRedeemedAmt(BigDecimal pointsRedeemedAmt) {
    this.pointsRedeemedAmt = pointsRedeemedAmt;
  }

  @Column(name = "audit_control_number", length = 15)
  public String getAuditControlNumber() {
    return this.auditControlNumber;
  }

  public void setAuditControlNumber(String auditControlNumber) {
    this.auditControlNumber = auditControlNumber;
  }

  @Column(name = "patient_writeoff", nullable = false, length = 1)
  public char getPatientWriteoff() {
    return this.patientWriteoff;
  }

  public void setPatientWriteoff(char patientWriteoff) {
    this.patientWriteoff = patientWriteoff;
  }

  @Column(name = "sponsor_writeoff", nullable = false, length = 1)
  public char getSponsorWriteoff() {
    return this.sponsorWriteoff;
  }

  public void setSponsorWriteoff(char sponsorWriteoff) {
    this.sponsorWriteoff = sponsorWriteoff;
  }

  @Column(name = "writeoff_remarks", length = 200)
  public String getWriteoffRemarks() {
    return this.writeoffRemarks;
  }

  public void setWriteoffRemarks(String writeoffRemarks) {
    this.writeoffRemarks = writeoffRemarks;
  }

  @Column(name = "sponsor_writeoff_remarks", length = 200)
  public String getSponsorWriteoffRemarks() {
    return this.sponsorWriteoffRemarks;
  }

  public void setSponsorWriteoffRemarks(String sponsorWriteoffRemarks) {
    this.sponsorWriteoffRemarks = sponsorWriteoffRemarks;
  }

  @Column(name = "cancellation_approval_status", length = 1)
  public String getCancellationApprovalStatus() {
    return this.cancellationApprovalStatus;
  }

  public void setCancellationApprovalStatus(String cancellationApprovalStatus) {
    this.cancellationApprovalStatus = cancellationApprovalStatus;
  }

  @Column(name = "cancellation_approved_by", length = 100)
  public String getCancellationApprovedBy() {
    return this.cancellationApprovedBy;
  }

  public void setCancellationApprovedBy(String cancellationApprovedBy) {
    this.cancellationApprovedBy = cancellationApprovedBy;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "cancellation_approved_date", length = 29)
  public Date getCancellationApprovedDate() {
    return this.cancellationApprovedDate;
  }

  public void setCancellationApprovedDate(Date cancellationApprovedDate) {
    this.cancellationApprovedDate = cancellationApprovedDate;
  }

  @Column(name = "discount_category_id")
  public Integer getDiscountCategoryId() {
    return this.discountCategoryId;
  }

  public void setDiscountCategoryId(Integer discountCategoryId) {
    this.discountCategoryId = discountCategoryId;
  }

  @Column(name = "cancel_approve_amount", precision = 15)
  public BigDecimal getCancelApproveAmount() {
    return this.cancelApproveAmount;
  }

  public void setCancelApproveAmount(BigDecimal cancelApproveAmount) {
    this.cancelApproveAmount = cancelApproveAmount;
  }

  @Column(name = "ip_deposit_set_off", precision = 15)
  public BigDecimal getIpDepositSetOff() {
    return this.ipDepositSetOff;
  }

  public void setIpDepositSetOff(BigDecimal ipDepositSetOff) {
    this.ipDepositSetOff = ipDepositSetOff;
  }

  @Column(name = "credit_note_reasons", length = 200)
  public String getCreditNoteReasons() {
    return this.creditNoteReasons;
  }

  public void setCreditNoteReasons(String creditNoteReasons) {
    this.creditNoteReasons = creditNoteReasons;
  }

  @Column(name = "total_tax", nullable = false, precision = 15)
  public BigDecimal getTotalTax() {
    return this.totalTax;
  }

  public void setTotalTax(BigDecimal totalTax) {
    this.totalTax = totalTax;
  }

  @Column(name = "total_claim_tax", nullable = false, precision = 15)
  public BigDecimal getTotalClaimTax() {
    return this.totalClaimTax;
  }

  public void setTotalClaimTax(BigDecimal totalClaimTax) {
    this.totalClaimTax = totalClaimTax;
  }

  @Column(name = "total_original_tax_amt", nullable = false, precision = 15)
  public BigDecimal getTotalOriginalTaxAmt() {
    return this.totalOriginalTaxAmt;
  }

  public void setTotalOriginalTaxAmt(BigDecimal totalOriginalTaxAmt) {
    this.totalOriginalTaxAmt = totalOriginalTaxAmt;
  }

  @Column(name = "selfpay_batch_id", nullable = false)
  public int getSelfpayBatchId() {
    return this.selfpayBatchId;
  }

  public void setSelfpayBatchId(int selfpayBatchId) {
    this.selfpayBatchId = selfpayBatchId;
  }

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "bill_claim", joinColumns = {
      @JoinColumn(name = "bill_no") }, inverseJoinColumns = { @JoinColumn(name = "claim_id") })
  public Set<InsuranceClaimModel> getClaims() {
    return this.claims;
  }

  public void setClaims(Set<InsuranceClaimModel> claims) {
    this.claims = claims;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "billNo")
  public Set<BillChargeModel> getBillCharges() {
    return billCharges;
  }

  public void setBillCharges(Set<BillChargeModel> billCharges) {
    this.billCharges = billCharges;
  }

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "bill_receipts", joinColumns = {
      @JoinColumn(name = "bill_no") }, inverseJoinColumns = { @JoinColumn(name = "receipt_no") })
  public List<ReceiptModel> getReceipts() {
    return receipts;
  }

  public void setReceipts(List<ReceiptModel> receipts) {
    this.receipts = receipts;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "visit_id", referencedColumnName = "customer_id", insertable = false, updatable = false)
  public StoreRetailCustomersModel getStoreRetailCustomers() {
    return storeRetailCustomers;
  }

  public void setStoreRetailCustomers(StoreRetailCustomersModel storeRetailCustomers) {
    this.storeRetailCustomers = storeRetailCustomers;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "visit_id", referencedColumnName = "incoming_visit_id", insertable = false, updatable = false)
  public IncomingSampleRegistrationModel getIncomingSampleRegistration() {
    return incomingSampleRegistration;
  }

  public void setIncomingSampleRegistration(IncomingSampleRegistrationModel incomingSampleRegistration) {
    this.incomingSampleRegistration = incomingSampleRegistration;
  }


}
