package com.insta.hms.core.billing;
// Generated 28 Aug, 2018 12:23:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BillClaimId generated by hbm2java
 */
@Embeddable
public class BillClaimIdSequence implements java.io.Serializable {

  private String visitId;
  private String billNo;
  private int planId;
  private String sponsorId;
  private String claimId;
  private Integer priority;
  private Character claimStatus;

  public BillClaimIdSequence() {
  }

  public BillClaimIdSequence(String visitId, String billNo, int planId, String sponsorId,
      String claimId) {
    this.visitId = visitId;
    this.billNo = billNo;
    this.planId = planId;
    this.sponsorId = sponsorId;
    this.claimId = claimId;
  }

  public BillClaimIdSequence(String visitId, String billNo, int planId, String sponsorId,
      String claimId, Integer priority, Character claimStatus) {
    this.visitId = visitId;
    this.billNo = billNo;
    this.planId = planId;
    this.sponsorId = sponsorId;
    this.claimId = claimId;
    this.priority = priority;
    this.claimStatus = claimStatus;
  }

  @Column(name = "visit_id", nullable = false, length = 15)
  public String getVisitId() {
    return this.visitId;
  }

  public void setVisitId(String visitId) {
    this.visitId = visitId;
  }

  @Column(name = "bill_no", nullable = false, length = 15)
  public String getBillNo() {
    return this.billNo;
  }

  public void setBillNo(String billNo) {
    this.billNo = billNo;
  }

  @Column(name = "plan_id", nullable = false)
  public int getPlanId() {
    return this.planId;
  }

  public void setPlanId(int planId) {
    this.planId = planId;
  }

  @Column(name = "sponsor_id", nullable = false, length = 20)
  public String getSponsorId() {
    return this.sponsorId;
  }

  public void setSponsorId(String sponsorId) {
    this.sponsorId = sponsorId;
  }

  @Column(name = "claim_id", nullable = false, length = 15)
  public String getClaimId() {
    return this.claimId;
  }

  public void setClaimId(String claimId) {
    this.claimId = claimId;
  }

  @Column(name = "priority")
  public Integer getPriority() {
    return this.priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  @Column(name = "claim_status", length = 1)
  public Character getClaimStatus() {
    return this.claimStatus;
  }

  public void setClaimStatus(Character claimStatus) {
    this.claimStatus = claimStatus;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof BillClaimIdSequence))
      return false;
    BillClaimIdSequence castOther = (BillClaimIdSequence) other;

    return ((this.getVisitId() == castOther.getVisitId()) || (this.getVisitId() != null
        && castOther.getVisitId() != null && this.getVisitId().equals(castOther.getVisitId())))
        && ((this.getBillNo() == castOther.getBillNo()) || (this.getBillNo() != null
            && castOther.getBillNo() != null && this.getBillNo().equals(castOther.getBillNo())))
        && (this.getPlanId() == castOther.getPlanId())
        && ((this.getSponsorId() == castOther.getSponsorId())
            || (this.getSponsorId() != null && castOther.getSponsorId() != null
                && this.getSponsorId().equals(castOther.getSponsorId())))
        && ((this.getClaimId() == castOther.getClaimId()) || (this.getClaimId() != null
            && castOther.getClaimId() != null && this.getClaimId().equals(castOther.getClaimId())))
        && ((this.getPriority() == castOther.getPriority())
            || (this.getPriority() != null && castOther.getPriority() != null
                && this.getPriority().equals(castOther.getPriority())))
        && ((this.getClaimStatus() == castOther.getClaimStatus())
            || (this.getClaimStatus() != null && castOther.getClaimStatus() != null
                && this.getClaimStatus().equals(castOther.getClaimStatus())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getVisitId() == null ? 0 : this.getVisitId().hashCode());
    result = 37 * result + (getBillNo() == null ? 0 : this.getBillNo().hashCode());
    result = 37 * result + this.getPlanId();
    result = 37 * result + (getSponsorId() == null ? 0 : this.getSponsorId().hashCode());
    result = 37 * result + (getClaimId() == null ? 0 : this.getClaimId().hashCode());
    result = 37 * result + (getPriority() == null ? 0 : this.getPriority().hashCode());
    result = 37 * result + (getClaimStatus() == null ? 0 : this.getClaimStatus().hashCode());
    return result;
  }

}
