package com.insta.hms.core.billing;
// default package

import com.insta.hms.core.insurance.InsuranceClaimModel;
import com.insta.hms.mdm.tpas.TpaMasterModel;

import java.math.BigDecimal;
import java.util.Set;

import com.insta.hms.core.insurance.InsuranceClaimModel;

import java.math.BigDecimal;

import javax.persistence.AssociationOverride;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BillChargeClaimModelModel generated by hbm2java
 */
@Entity
@Table(name = "bill_charge_claim")
public class BillChargeClaimModel implements java.io.Serializable {

  private BillChargeClaimIdSequence id;
  private InsuranceClaimModel claimId;
  private BillChargeModel chargeId;
  private BillModel billNo;
  private TpaMasterModel sponsorId;
  private String approvalId;
  private BigDecimal insuranceClaimAmt;
  private Character claimStatus;
  private BigDecimal claimRecdTotal;
  private String denialCode;
  private String priorAuthId;
  private Integer priorAuthModeId;
  private String denialRemarks;
  private String codeType;
  private Character chargeExcluded;
  private Integer insuranceCategoryId;
  private Boolean firstOfCategory;
  private BigDecimal amountIncluded;
  private BigDecimal returnInsuranceClaimAmt;
  private String chargeHead;
  private String claimActivityId;
  private Character closureType;
  private Integer rejectionReasonCategoryId;
  private BigDecimal copayDedAdj;
  private BigDecimal maxCopayAdj;
  private BigDecimal sponsorLimitAdj;
  private BigDecimal copayPercAdj;
  private Boolean includeInClaimCalc;
  private BigDecimal taxAmount;
  private Set<BillChargeClaimTaxModel> billChargeClaimTaxes;

  public BillChargeClaimModel() {
  }
  
  public BillChargeClaimModel(BillChargeClaimIdSequence id) {
    this.id = id;
  }

  public BillChargeClaimModel(BillChargeClaimIdSequence id, InsuranceClaimModel claimId,
      BillChargeModel chargeId, BillModel billNo, TpaMasterModel sponsorId) {
    this.id = id;
    this.claimId = claimId;
    this.chargeId = chargeId;
    this.billNo = billNo;
    this.sponsorId = sponsorId;
  }

  public BillChargeClaimModel(BillChargeClaimIdSequence id, InsuranceClaimModel claimId,
      BillChargeModel chargeId, BillModel billNo, TpaMasterModel sponsorId, String approvalId,
      BigDecimal insuranceClaimAmt, Character claimStatus, BigDecimal claimRecdTotal,
      String denialCode, String priorAuthId, Integer priorAuthModeId, String denialRemarks,
      String codeType, Character chargeExcluded, Integer insuranceCategoryId,
      Boolean firstOfCategory, BigDecimal amountIncluded, BigDecimal returnInsuranceClaimAmt,
      String chargeHead, String claimActivityId, Character closureType,
      Integer rejectionReasonCategoryId, BigDecimal copayDedAdj, BigDecimal maxCopayAdj,
      BigDecimal sponsorLimitAdj, BigDecimal copayPercAdj, Boolean includeInClaimCalc, BigDecimal taxAmount) {
    this.id = id;
    this.claimId = claimId;
    this.chargeId = chargeId;
    this.billNo = billNo;
    this.sponsorId = sponsorId;
    this.approvalId = approvalId;
    this.insuranceClaimAmt = insuranceClaimAmt;
    this.claimStatus = claimStatus;
    this.claimRecdTotal = claimRecdTotal;
    this.denialCode = denialCode;
    this.priorAuthId = priorAuthId;
    this.priorAuthModeId = priorAuthModeId;
    this.denialRemarks = denialRemarks;
    this.codeType = codeType;
    this.chargeExcluded = chargeExcluded;
    this.insuranceCategoryId = insuranceCategoryId;
    this.firstOfCategory = firstOfCategory;
    this.amountIncluded = amountIncluded;
    this.returnInsuranceClaimAmt = returnInsuranceClaimAmt;
    this.chargeHead = chargeHead;
    this.claimActivityId = claimActivityId;
    this.closureType = closureType;
    this.rejectionReasonCategoryId = rejectionReasonCategoryId;
    this.copayDedAdj = copayDedAdj;
    this.maxCopayAdj = maxCopayAdj;
    this.sponsorLimitAdj = sponsorLimitAdj;
    this.copayPercAdj = copayPercAdj;
    this.includeInClaimCalc = includeInClaimCalc;
    this.taxAmount = taxAmount;
  }

  @EmbeddedId
  @AttributeOverrides({
      @AttributeOverride(name = "chargeId", column = @Column(name = "charge_id", nullable = false, length = 15)),
      @AttributeOverride(name = "claimId", column = @Column(name = "claim_id", nullable = false, length = 15)) })
  public BillChargeClaimIdSequence getId() {
    return this.id;
  }

  public void setId(BillChargeClaimIdSequence id) {
    this.id = id;
  }
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "claim_id", nullable = false, insertable = false, updatable = false)
  public InsuranceClaimModel getClaimId() {
    return this.claimId;
  }

  public void setClaimId(InsuranceClaimModel claimId) {
    this.claimId = claimId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "charge_id", nullable = false, insertable = false, updatable = false)
  public BillChargeModel getChargeId() {
    return this.chargeId;
  }

  public void setChargeId(BillChargeModel chargeId) {
    this.chargeId = chargeId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "bill_no", nullable = false)
  public BillModel getBillNo() {
    return this.billNo;
  }

  public void setBillNo(BillModel billNo) {
    this.billNo = billNo;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "sponsor_id", nullable = false, insertable = false, updatable = false)
  public TpaMasterModel getSponsorId() {
    return this.sponsorId;
  }

  public void setSponsorId(TpaMasterModel sponsorId) {
    this.sponsorId = sponsorId;
  }

  @Column(name = "approval_id", length = 10)
  public String getApprovalId() {
    return this.approvalId;
  }

  public void setApprovalId(String approvalId) {
    this.approvalId = approvalId;
  }

  @Column(name = "insurance_claim_amt", precision = 15)
  public BigDecimal getInsuranceClaimAmt() {
    return this.insuranceClaimAmt;
  }

  public void setInsuranceClaimAmt(BigDecimal insuranceClaimAmt) {
    this.insuranceClaimAmt = insuranceClaimAmt;
  }

  @Column(name = "claim_status", length = 1)
  public Character getClaimStatus() {
    return this.claimStatus;
  }

  public void setClaimStatus(Character claimStatus) {
    this.claimStatus = claimStatus;
  }

  @Column(name = "claim_recd_total", precision = 15)
  public BigDecimal getClaimRecdTotal() {
    return this.claimRecdTotal;
  }

  public void setClaimRecdTotal(BigDecimal claimRecdTotal) {
    this.claimRecdTotal = claimRecdTotal;
  }

  @Column(name = "denial_code", length = 15)
  public String getDenialCode() {
    return this.denialCode;
  }

  public void setDenialCode(String denialCode) {
    this.denialCode = denialCode;
  }

  @Column(name = "prior_auth_id", length = 50)
  public String getPriorAuthId() {
    return this.priorAuthId;
  }

  public void setPriorAuthId(String priorAuthId) {
    this.priorAuthId = priorAuthId;
  }

  @Column(name = "prior_auth_mode_id")
  public Integer getPriorAuthModeId() {
    return this.priorAuthModeId;
  }

  public void setPriorAuthModeId(Integer priorAuthModeId) {
    this.priorAuthModeId = priorAuthModeId;
  }

  @Column(name = "denial_remarks")
  public String getDenialRemarks() {
    return this.denialRemarks;
  }

  public void setDenialRemarks(String denialRemarks) {
    this.denialRemarks = denialRemarks;
  }

  @Column(name = "code_type", length = 50)
  public String getCodeType() {
    return this.codeType;
  }

  public void setCodeType(String codeType) {
    this.codeType = codeType;
  }

  @Column(name = "charge_excluded", length = 1)
  public Character getChargeExcluded() {
    return this.chargeExcluded;
  }

  public void setChargeExcluded(Character chargeExcluded) {
    this.chargeExcluded = chargeExcluded;
  }

  @Column(name = "insurance_category_id")
  public Integer getInsuranceCategoryId() {
    return this.insuranceCategoryId;
  }

  public void setInsuranceCategoryId(Integer insuranceCategoryId) {
    this.insuranceCategoryId = insuranceCategoryId;
  }

  @Column(name = "first_of_category")
  public Boolean getFirstOfCategory() {
    return this.firstOfCategory;
  }

  public void setFirstOfCategory(Boolean firstOfCategory) {
    this.firstOfCategory = firstOfCategory;
  }

  @Column(name = "amount_included", precision = 15)
  public BigDecimal getAmountIncluded() {
    return this.amountIncluded;
  }

  public void setAmountIncluded(BigDecimal amountIncluded) {
    this.amountIncluded = amountIncluded;
  }

  @Column(name = "return_insurance_claim_amt", precision = 15)
  public BigDecimal getReturnInsuranceClaimAmt() {
    return this.returnInsuranceClaimAmt;
  }

  public void setReturnInsuranceClaimAmt(BigDecimal returnInsuranceClaimAmt) {
    this.returnInsuranceClaimAmt = returnInsuranceClaimAmt;
  }

  @Column(name = "charge_head", length = 20)
  public String getChargeHead() {
    return this.chargeHead;
  }

  public void setChargeHead(String chargeHead) {
    this.chargeHead = chargeHead;
  }

  @Column(name = "claim_activity_id", length = 100)
  public String getClaimActivityId() {
    return this.claimActivityId;
  }

  public void setClaimActivityId(String claimActivityId) {
    this.claimActivityId = claimActivityId;
  }

  @Column(name = "closure_type", length = 1)
  public Character getClosureType() {
    return this.closureType;
  }

  public void setClosureType(Character closureType) {
    this.closureType = closureType;
  }

  @Column(name = "rejection_reason_category_id")
  public Integer getRejectionReasonCategoryId() {
    return this.rejectionReasonCategoryId;
  }

  public void setRejectionReasonCategoryId(Integer rejectionReasonCategoryId) {
    this.rejectionReasonCategoryId = rejectionReasonCategoryId;
  }

  @Column(name = "copay_ded_adj", precision = 15)
  public BigDecimal getCopayDedAdj() {
    return this.copayDedAdj;
  }

  public void setCopayDedAdj(BigDecimal copayDedAdj) {
    this.copayDedAdj = copayDedAdj;
  }

  @Column(name = "max_copay_adj", precision = 15)
  public BigDecimal getMaxCopayAdj() {
    return this.maxCopayAdj;
  }

  public void setMaxCopayAdj(BigDecimal maxCopayAdj) {
    this.maxCopayAdj = maxCopayAdj;
  }

  @Column(name = "sponsor_limit_adj", precision = 15)
  public BigDecimal getSponsorLimitAdj() {
    return this.sponsorLimitAdj;
  }

  public void setSponsorLimitAdj(BigDecimal sponsorLimitAdj) {
    this.sponsorLimitAdj = sponsorLimitAdj;
  }

  @Column(name = "copay_perc_adj", precision = 15)
  public BigDecimal getCopayPercAdj() {
    return this.copayPercAdj;
  }

  public void setCopayPercAdj(BigDecimal copayPercAdj) {
    this.copayPercAdj = copayPercAdj;
  }

  @Column(name = "include_in_claim_calc")
  public Boolean getIncludeInClaimCalc() {
    return this.includeInClaimCalc;
  }

  public void setIncludeInClaimCalc(Boolean includeInClaimCalc) {
    this.includeInClaimCalc = includeInClaimCalc;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeId")
  public Set<BillChargeClaimTaxModel> getBillChargeClaimTaxes() {
    return billChargeClaimTaxes;
  }

  public void setBillChargeClaimTaxes(Set<BillChargeClaimTaxModel> billChargeClaimTaxes) {
    this.billChargeClaimTaxes = billChargeClaimTaxes;
  }
  

  @Column(name = "tax_amt", precision = 15)
  public BigDecimal getTaxAmount() {
    return this.taxAmount;
  }

  public void setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
  }

}
