package com.insta.hms.core.billing;
// default package

// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillReceiptsModel generated by hbm2java
 */
@Entity
@Table(name = "bill_receipts")
public class BillReceiptsModel implements java.io.Serializable {

  private long billReceiptId;
  private ReceiptModel receiptNo;
  private BillModel billNo;
  private Date modTime;
  private Character sponsorIndex;
  private BigDecimal allocatedAmount = BigDecimal.ZERO;
  private String username;

  @JsonIgnore
  private Set<BillChargeReceiptAllocationModel> billChargeReceiptAllocations;

  public BillReceiptsModel() {
  }
  
  public BillReceiptsModel(long billReceiptId) {
    this.billReceiptId = billReceiptId;
  }

  public BillReceiptsModel(ReceiptModel receiptNo, BillModel billNo, Date modTime) {
    this.receiptNo = receiptNo;
    this.billNo = billNo;
    this.modTime = modTime;
  }
  
  public BillReceiptsModel(long billReceiptId, ReceiptModel receiptNo, BillModel billNo, Date modTime) {
    this.billReceiptId = billReceiptId;
    this.receiptNo = receiptNo;
    this.billNo = billNo;
    this.modTime = modTime;
  }

  public BillReceiptsModel(long billReceiptId, ReceiptModel receiptNo, BillModel billNo, Date modTime, Character sponsorIndex) {
    this.billReceiptId = billReceiptId;
    this.receiptNo = receiptNo;
    this.billNo = billNo;
    this.modTime = modTime;
    this.sponsorIndex = sponsorIndex;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bill_receipt_id_generator")
  @SequenceGenerator(name = "bill_receipt_id_generator", sequenceName = "bill_receipts_id_sequence", allocationSize = 1, initialValue = 1)
  @Column(name = "bill_receipt_id", unique = true, nullable = false)
  public long getBillReceiptId() {
    return this.billReceiptId;
  }

  public void setBillReceiptId(long billReceiptId) {
    this.billReceiptId = billReceiptId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "receipt_no", nullable = false, referencedColumnName = "receipt_id")
  public ReceiptModel getReceiptNo() {
    return this.receiptNo;
  }

  public void setReceiptNo(ReceiptModel receiptNo) {
    this.receiptNo = receiptNo;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "bill_no", nullable = false)
  public BillModel getBillNo() {
    return this.billNo;
  }

  public void setBillNo(BillModel billNo) {
    this.billNo = billNo;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "mod_time", nullable = false, length = 29)
  public Date getModTime() {
    return this.modTime;
  }

  public void setModTime(Date modTime) {
    this.modTime = modTime;
  }

  @Column(name = "sponsor_index", length = 1)
  public Character getSponsorIndex() {
    return this.sponsorIndex;
  }

  public void setSponsorIndex(Character sponsorIndex) {
    this.sponsorIndex = sponsorIndex;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "billReceipt")
  public Set<BillChargeReceiptAllocationModel> getBillChargeReceiptAllocations() {
    return billChargeReceiptAllocations;
  }

  public void setBillChargeReceiptAllocations(
      Set<BillChargeReceiptAllocationModel> billChargeReceiptAllocations) {
    this.billChargeReceiptAllocations = billChargeReceiptAllocations;
  }

  @Column(name = "allocated_amount", nullable = false, precision = 15)
  public BigDecimal getAllocatedAmount() {
    return allocatedAmount;
  }

  public void setAllocatedAmount(BigDecimal allocatedAmount) {
    this.allocatedAmount = allocatedAmount;
  }

  @Column(name = "username", nullable = false, length = 30)
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

}
