package com.insta.hms.core.billing;

public class InsuranceCategoryHelper {
  
  public final String GET_DIAG_CATEGORY_ID_BASED_ON_PLAN = " SELECT d.test_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM diagnostics d "
      + " LEFT JOIN (SELECT dicm.diagnostic_test_id, dicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY dicm.diagnostic_test_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM diagnostic_test_insurance_category_mapping dicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=dicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE dicm.diagnostic_test_id in (#) order by piic.priority desc) "
      + " AS priCat ON(d.test_id = priCat.diagnostic_test_id)"
      + " LEFT JOIN (SELECT dicm.diagnostic_test_id, dicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY dicm.diagnostic_test_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM diagnostic_test_insurance_category_mapping dicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=dicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE dicm.diagnostic_test_id in (#) order by piic.priority desc)"
      + " AS secCat ON(d.test_id = secCat.diagnostic_test_id) "
      + " WHERE d.test_id in (#) ";
  
  public final String GET_SERVICE_CATEGORY_ID_BASED_ON_PLAN = " SELECT s.service_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM services s "
      + " LEFT JOIN (SELECT sicm.service_id, sicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY sicm.service_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM service_insurance_category_mapping sicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=sicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE sicm.service_id in (#) order by piic.priority desc) "
      + " AS priCat ON(s.service_id = priCat.service_id)"
      + " LEFT JOIN (SELECT sicm.service_id, sicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY sicm.service_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM service_insurance_category_mapping sicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=sicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE sicm.service_id in (#) order by piic.priority desc)"
      + " AS secCat ON(s.service_id = secCat.service_id) "
      + " WHERE s.service_id in (#)";
  
  public final String GET_OPERATION_CATEGORY_ID_BASED_ON_PLAN = " SELECT o.op_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM operation_master o "
      + " LEFT JOIN (SELECT oicm.operation_id, oicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY oicm.operation_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM operation_insurance_category_mapping oicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=oicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE oicm.operation_id in (#) order by piic.priority desc) "
      + " AS priCat ON(o.op_id = priCat.operation_id)"
      + " LEFT JOIN (SELECT oicm.operation_id, oicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY oicm.operation_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM operation_insurance_category_mapping oicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=oicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE oicm.operation_id in (#) order by piic.priority desc)"
      + " AS secCat ON(o.op_id = secCat.operation_id) "
      + " WHERE o.op_id in (#) ";
  
  public final String GET_EQUIPMENT_CATEGORY_ID_BASED_ON_PLAN = " SELECT e.eq_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM equipment_master e "
      + " LEFT JOIN (SELECT eicm.equipment_id, eicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY eicm.equipment_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM equipment_insurance_category_mapping eicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=eicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE eicm.equipment_id in (#) order by piic.priority desc) "
      + " AS priCat ON(e.eq_id = priCat.equipment_id)"
      + " LEFT JOIN (SELECT eicm.equipment_id, eicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY eicm.equipment_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM equipment_insurance_category_mapping eicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=eicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE eicm.equipment_id in (#) order by piic.priority desc)"
      + " AS secCat ON(e.eq_id = secCat.equipment_id) "
      + " WHERE e.eq_id in (#)";
  
  public final String GET_BED_CATEGORY_ID_BASED_ON_PLAN = " SELECT b.bed_type_name AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM bed_types b "
      + " LEFT JOIN (SELECT bicm.bed_type_name, bicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY bicm.bed_type_name "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM bed_types_insurance_category_mapping bicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=bicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       JOIN bed_names bn ON (bn.bed_type = bicm.bed_type_name) "
      + "       WHERE bn.bed_id::text in (#) order by piic.priority desc) "
      + " AS priCat ON(b.bed_type_name = priCat.bed_type_name)"
      + " LEFT JOIN (SELECT bicm.bed_type_name, bicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY bicm.bed_type_name "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM bed_types_insurance_category_mapping bicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=bicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             JOIN bed_names bn ON (bn.bed_type = bicm.bed_type_name) "
      + "             WHERE bn.bed_id::text in (#) order by piic.priority desc)"
      + " AS secCat ON(b.bed_type_name = secCat.bed_type_name) "
      + " JOIN bed_names bn ON (bn.bed_type = b.bed_type_name) "
      + " WHERE bn.bed_id::text in (#)";
  
  public final String GET_BED_NAME_CATEGORY_ID_BASED_ON_PLAN = " SELECT b.bed_type_name AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM bed_types b "
      + " LEFT JOIN (SELECT bicm.bed_type_name, bicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY bicm.bed_type_name "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM bed_types_insurance_category_mapping bicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=bicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE bicm.bed_type_name in (#) order by piic.priority desc) "
      + " AS priCat ON(b.bed_type_name = priCat.bed_type_name)"
      + " LEFT JOIN (SELECT bicm.bed_type_name, bicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY bicm.bed_type_name "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM bed_types_insurance_category_mapping bicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=bicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE bicm.bed_type_name in (#) order by piic.priority desc)"
      + " AS secCat ON(b.bed_type_name = secCat.bed_type_name) "
      + " WHERE b.bed_type_name in (#) ";
  
  public final String GET_MED_CATEGORY_ID_BASED_ON_PLAN = " SELECT s.medicine_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM store_item_details s "
      + " LEFT JOIN (SELECT sicm.medicine_id, sicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY sicm.medicine_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM store_items_insurance_category_mapping sicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=sicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE sicm.medicine_id in (#) order by piic.priority desc) "
      + " AS priCat ON(s.medicine_id = priCat.medicine_id)"
      + " LEFT JOIN (SELECT sicm.medicine_id, sicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY sicm.medicine_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM store_items_insurance_category_mapping sicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=sicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE sicm.medicine_id in (#) order by piic.priority desc)"
      + " AS secCat ON(s.medicine_id = secCat.medicine_id) "
      + " WHERE s.medicine_id in(#) ";
  
  public final String GET_PKG_CATEGORY_ID_BASED_ON_PLAN = " SELECT p.package_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM packages p "
      + " LEFT JOIN (SELECT picm.package_id, picm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY picm.package_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM packages_insurance_category_mapping picm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=picm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE picm.package_id in (#) order by piic.priority desc) "
      + " AS priCat ON(p.package_id = priCat.package_id)"
      + " LEFT JOIN (SELECT picm.package_id, picm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY picm.package_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM packages_insurance_category_mapping picm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=picm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE picm.package_id in (#) order by piic.priority desc)"
      + " AS secCat ON(p.package_id = secCat.package_id) "
      + " WHERE p.package_id in(#) ";
  
  public final String GET_OTHERCHARGE_CATEGORY_ID_BASED_ON_PLAN = " SELECT c.charge_name AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM common_charges_master c "
      + " LEFT JOIN (SELECT cicm.charge_name, cicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY cicm.charge_name "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM common_charges_insurance_category_mapping cicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=cicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE cicm.charge_name in (#) order by piic.priority desc) "
      + " AS priCat ON(c.charge_name = priCat.charge_name)"
      + " LEFT JOIN (SELECT cicm.charge_name, cicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY cicm.charge_name "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM common_charges_insurance_category_mapping cicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=cicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE cicm.charge_name in (#) order by piic.priority desc)"
      + " AS secCat ON(c.charge_name = secCat.charge_name) "
      + " WHERE c.charge_name in(#) ";
  
  public final String GET_DOCTOR_CATEGORY_ID_BASED_ON_PLAN = " SELECT c.consultation_type_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM consultation_types c "
      + " LEFT JOIN (SELECT cicm.consultation_type_id, cicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY cicm.consultation_type_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM consultation_types_insurance_category_mapping cicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=cicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE cicm.consultation_type_id in (#) order by piic.priority desc) "
      + " AS priCat ON(c.consultation_type_id = priCat.consultation_type_id)"
      + " LEFT JOIN (SELECT cicm.consultation_type_id, cicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY cicm.consultation_type_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM consultation_types_insurance_category_mapping cicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=cicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE cicm.consultation_type_id in (#) order by piic.priority desc)"
      + " AS secCat ON(c.consultation_type_id = secCat.consultation_type_id) "
      + " WHERE c.consultation_type_id in(#)";
  
  public final String GET_ANESTHESIA_CATEGORY_ID_BASED_ON_PLAN = " SELECT a.anesthesia_type_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM anesthesia_type_master a "
      + " LEFT JOIN (SELECT aicm.anesthesia_type_id, aicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY aicm.anesthesia_type_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM anesthesia_types_insurance_category_mapping aicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=aicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE aicm.anesthesia_type_id in (#) order by piic.priority desc) "
      + " AS priCat ON(a.anesthesia_type_id = priCat.anesthesia_type_id)"
      + " LEFT JOIN (SELECT aicm.anesthesia_type_id, aicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY aicm.anesthesia_type_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM anesthesia_types_insurance_category_mapping aicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=aicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE aicm.anesthesia_type_id in (#) order by piic.priority desc)"
      + " AS secCat ON(a.anesthesia_type_id = secCat.anesthesia_type_id) "
      + " WHERE a.anesthesia_type_id in (#) ";
  
  public final String GET_DIETARY_CATEGORY_ID_BASED_ON_PLAN = " SELECT d.diet_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM diet_master d "
      + " LEFT JOIN (SELECT dicm.diet_id, dicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY dicm.diet_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM diet_insurance_category_mapping dicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=dicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE dicm.diet_id in (#) order by piic.priority desc) "
      + " AS priCat ON(d.diet_id = priCat.diet_id)"
      + " LEFT JOIN (SELECT dicm.diet_id, dicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY dicm.diet_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM diet_insurance_category_mapping dicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=dicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE dicm.diet_id in (#) order by piic.priority desc)"
      + " AS secCat ON(d.diet_id = secCat.diet_id) "
      + " WHERE d.diet_id in(#) ";
  
  public final String GET_ITE_CATEGORY_ID_BASED_ON_PLAN = " SELECT s.medicine_id AS item_id,"
      + " COALESCE(priCat.insurance_category_id,0) AS primary_insurance_category_id, "
      + " COALESCE(secCat.insurance_category_id,0) AS secondary_insurance_category_id "
      + " FROM store_item_details s "
      + " LEFT JOIN (SELECT sicm.medicine_id, sicm.insurance_category_id, "
      + "             rank() OVER (PARTITION BY sicm.medicine_id "
      + "             ORDER BY piic.priority DESC)  "
      + "       FROM store_items_insurance_category_mapping sicm "
      + "       JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=sicm.insurance_category_id  "
      + "           AND pipd.plan_id = ? and pipd.patient_type = ?) "
      + "       JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id) "
      + "       WHERE sicm.medicine_id in (#) order by piic.priority desc) "
      + " AS priCat ON(s.medicine_id = priCat.medicine_id)"
      + " LEFT JOIN (SELECT sicm.medicine_id, sicm.insurance_category_id, "
      + "                  rank() OVER (PARTITION BY sicm.medicine_id "
      + "                  ORDER BY piic.priority DESC) "
      + "             FROM store_items_insurance_category_mapping sicm "
      + "             JOIN insurance_plan_details pipd ON (pipd.insurance_category_id=sicm.insurance_category_id  "
      + "                 AND pipd.plan_id = ? AND pipd.patient_type = ?) "
      + "             JOIN item_insurance_categories piic ON(piic.insurance_category_id = pipd.insurance_category_id)"
      + "             WHERE sicm.medicine_id in (#) order by piic.priority desc)"
      + " AS secCat ON(s.medicine_id = secCat.medicine_id) "
      + " WHERE s.medicine_id in(#) ";

}
