package com.insta.hms.core.billing;
// Generated 15 Nov, 2018 2:04:47 PM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;
import com.insta.hms.billing.Receipt;
import com.insta.hms.core.patient.PatientDetailsModel;
import com.insta.hms.mdm.cardtypes.CardTypeMasterModel;
import com.insta.hms.mdm.centers.HospitalCenterMasterModel;
import com.insta.hms.mdm.counters.CountersModel;
import com.insta.hms.mdm.paymentmode.PaymentModeMasterModel;
import com.insta.hms.mdm.tpas.TpaMasterModel;
import com.insta.hms.model.ForeignCurrencyModel;
import com.insta.hms.security.usermanager.UUserModel;
import com.insta.hms.util.ViewProfiles;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Receipts generated by hbm2java
 */
@Entity
@Table(name = "receipts")
public class ReceiptModel implements java.io.Serializable {

  @JsonView(ViewProfiles.Public.class)
  private String receiptId;
  @JsonView(ViewProfiles.Public.class)
  private String receiptType;
  @JsonView(ViewProfiles.Public.class)
  @JsonProperty("tpa")
  private TpaMasterModel tpaId;
  @JsonView(ViewProfiles.Public.class)
  private String mrNo;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal amount;
  @JsonView(ViewProfiles.Public.class)
  private Date displayDate = new Date();
  @JsonView(ViewProfiles.Public.class)
  private String counter;
  @JsonView(ViewProfiles.Public.class)
  private String bankName;
  @JsonView(ViewProfiles.Public.class)
  private String referenceNo;
  @JsonView(ViewProfiles.Public.class)
  private UUserModel createdBy;
  @JsonView(ViewProfiles.Public.class)
  private Date createdAt;
  @JsonView(ViewProfiles.Public.class)
  private UUserModel modifiedBy;
  @JsonView(ViewProfiles.Public.class)
  private Date modifiedAt;
  @JsonView(ViewProfiles.Public.class)
  private String remarks;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal tdsAmount = BigDecimal.ZERO;
  @JsonView(ViewProfiles.Public.class)
  private String paidBy;
  @JsonView(ViewProfiles.Public.class)
  @JsonProperty("payment_mode")
  private PaymentModeMasterModel paymentModeId = new PaymentModeMasterModel(-1);
  private Integer cardTypeId;
  @JsonView(ViewProfiles.Public.class)
  private String bankBatchNo;
  @JsonView(ViewProfiles.Public.class)
  private String cardAuthCode;
  @JsonView(ViewProfiles.Public.class)
  private String cardHolderName;
  @JsonView(ViewProfiles.Public.class)
  private Integer currencyId;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal exchangeRate;
  @JsonView(ViewProfiles.Public.class)
  private Date exchangeDate;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal currencyAmt;
  @JsonView(ViewProfiles.Public.class)
  private Date cardExpDate;
  @JsonView(ViewProfiles.Public.class)
  private String cardNumber;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal creditCardCommissionPercentage;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal creditCardCommissionAmount;
  @JsonView(ViewProfiles.Public.class)
  private String totp;
  @JsonView(ViewProfiles.Public.class)
  private String edcImei;
  @JsonView(ViewProfiles.Public.class)
  private Date paymentReceivedDate;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal otherDeductions = BigDecimal.ZERO;
  @JsonView(ViewProfiles.Public.class)
  private Integer centerId;
  @JsonView(ViewProfiles.Public.class)
  private Integer pointsRedeemed;
  @JsonIgnore
  private BigDecimal totalTaxRate = BigDecimal.ZERO;
  @JsonView(ViewProfiles.Public.class)
  private boolean isSettlement;
  @JsonView(ViewProfiles.Public.class)
  private BigDecimal unallocatedAmount;
  @JsonView(ViewProfiles.Public.class)
  private boolean isDeposit;
  @JsonView(ViewProfiles.Public.class)
  private String realized = "Y";
  @JsonView(ViewProfiles.Public.class)
  private String payerName;
  @JsonView(ViewProfiles.Public.class)
  private String payerAddress;
  @JsonView(ViewProfiles.Public.class)
  private String payerMobileNumber;
  @JsonView(ViewProfiles.Public.class)
  private String mobNumber;
  @JsonView(ViewProfiles.Public.class)
  private String storeRetailCustomerId;
  @JsonView(ViewProfiles.Public.class)
  private String incomingVisitId;
  @JsonView(ViewProfiles.Public.class)
  private Set<BillReceiptsModel> billReceipts;
  @JsonIgnore
  private Set<ReceiptRefundReferenceModel> refundReceipts;
  @JsonIgnore
  private Set<ReceiptRefundReferenceModel> deductedReceipts;
  @JsonIgnore
  private Set<ReceiptUsageModel> receiptUsages;
  @JsonIgnore
  private CardTypeMasterModel cardTypeMasterModel;
  @JsonView(ViewProfiles.Public.class)
  private CountersModel countersModel;
  @JsonIgnore
  private ForeignCurrencyModel foreignCurrencyModel;
  @JsonIgnore
  private Set<ReceiptTaxModel> receiptTaxes;
  @JsonIgnore
  private PatientDetailsModel patientDetails;
  @JsonIgnore
  private HospitalCenterMasterModel centerModel;
  @JsonView
  private Boolean isStoreReturn = false;

  public ReceiptModel() {
  }
  
  public ReceiptModel(String receiptId) {
    this.receiptId = receiptId;
  }

  public ReceiptModel(String receiptId, String receiptType, BigDecimal amount, UUserModel createdBy,
      BigDecimal tdsAmount, PaymentModeMasterModel paymentModeId) {
    this.receiptId = receiptId;
    this.receiptType = receiptType;
    this.amount = amount;
    this.createdBy = createdBy;
    this.tdsAmount = tdsAmount;
    this.paymentModeId = paymentModeId;
  }
  
  public ReceiptModel(String receiptId, String receiptType, BigDecimal amount, UUserModel createdBy) {
    this.receiptId = receiptId;
    this.receiptType = receiptType;
    this.amount = amount;
    this.createdBy = createdBy;
  }
  
  public ReceiptModel(Receipt receiptDto) {
    this.receiptId = receiptDto.getReceiptNo();
    this.receiptType = receiptDto.getReceiptType();
    this.amount = receiptDto.getAmount();
    this.tdsAmount = receiptDto.getTdsAmt();
    this.tdsAmount = receiptDto.getTdsAmt();
    this.isSettlement = receiptDto.getisSettlement();
    this.isDeposit = receiptDto.getIsDeposit();
    this.realized = receiptDto.getRealized();
    this.mrNo = receiptDto.getMrno();
    this.payerName = receiptDto.getPayerName();
    this.payerMobileNumber = receiptDto.getPayerMobileNumber();
    this.pointsRedeemed = receiptDto.getPointsRedeemed();
    this.displayDate = receiptDto.getReceiptDate();
    this.counter = receiptDto.getCounter();
    if(receiptDto.getCounter() != null){
      this.countersModel = new CountersModel(receiptDto.getCounter());
    }
    if (receiptDto.getPaymentModeId() != 0) {
      this.paymentModeId = new PaymentModeMasterModel(receiptDto.getPaymentModeId());
    }
    this.cardTypeId = receiptDto.getCardTypeId();
    this.bankName = receiptDto.getBankName();
    this.referenceNo = receiptDto.getReferenceNo();
    this.referenceNo = receiptDto.getReferenceNo();
    this.createdBy = new UUserModel(receiptDto.getUsername());
    this.modifiedBy = new UUserModel(receiptDto.getUsername());
    this.remarks = receiptDto.getRemarks();
    this.paidBy = receiptDto.getPaidBy();
    this.bankBatchNo = receiptDto.getBankBatchNo();
    this.cardAuthCode = receiptDto.getCardAuthCode();
    this.cardHolderName = receiptDto.getCardHolderName();
    this.currencyId = receiptDto.getCurrencyId();
    this.exchangeRate = receiptDto.getExchangeRate();
    this.exchangeDate = receiptDto.getExchangeDateTime();
    this.currencyAmt = receiptDto.getCurrencyAmt();
    this.cardNumber = receiptDto.getCardNumber();
    this.cardExpDate = receiptDto.getCardExpDate();
    this.creditCardCommissionPercentage = receiptDto.getCommissionPercentage();
    this.creditCardCommissionAmount = receiptDto.getCommissionAmount();
    this.mobNumber = receiptDto.getMobNumber();
    this.storeRetailCustomerId = receiptDto.getStoreRetailCustomerId();
    this.incomingVisitId = receiptDto.getIncomingVisitId();
    this.totp = receiptDto.getTotp();
    this.edcImei = receiptDto.getEdcIMEI();
    if (receiptDto.getSponsorId() != null) {
      this.tpaId = new TpaMasterModel(receiptDto.getSponsorId());
    }
    this.unallocatedAmount = receiptDto.getAmount().add(receiptDto.getTdsAmt());
    this.payerAddress = receiptDto.getPayerAddress();
    
  }

  @Id
  @Column(name = "receipt_id", unique = true, nullable = false, length = 15)
  public String getReceiptId() {
    return this.receiptId;
  }

  public void setReceiptId(String receiptId) {
    this.receiptId = receiptId;
  }

  @Column(name = "receipt_type", nullable = false, length = 1)
  public String getReceiptType() {
    return this.receiptType;
  }

  public void setReceiptType(String receiptType) {
    this.receiptType = receiptType;
  }
  
  @Column(name = "realized", nullable = false, length = 1)
  public String getRealized() {
    return this.realized;
  }
  
  public void setRealized(String realized ) {
    this.realized = realized;
  }

  @Column(name = "payer_name", length = 100)
  public String getPayerName() {
    return this.payerName;
  }
  
  public void setPayerName(String payerName ) {
    this.payerName = payerName;
  }

  @Column(name = "payer_address", length = 300)
  public String getPayerAddress() {
    return this.payerAddress;
  }
  
  public void setPayerAddress(String payerAddress ) {
    this.payerAddress = payerAddress;
  }
  
  @Column(name = "payer_mobile_number", length = 15)
  public String getPayerMobileNumber() {
    return this.payerMobileNumber;
  }
  
  public void setPayerMobileNumber(String payerMobileNumber ) {
    this.payerMobileNumber = payerMobileNumber;
  }
  
  @Column(name = "mob_number", length = 15)
  public String getMobNumber() {
    return this.mobNumber;
  }
  
  public void setMobNumber(String mobNumber ) {
    this.mobNumber = mobNumber;
  }

  @Column(name = "store_retail_customer_id", length = 20)
  public String getStoreRetailCustomerId() {
    return this.storeRetailCustomerId;
  }
  
  public void setStoreRetailCustomerId(String storeRetailCustomerId ) {
    this.storeRetailCustomerId = storeRetailCustomerId;
  }

  @Column(name = "incoming_visit_id", length = 20)
  public String getIncomingVisitId() {
    return this.incomingVisitId;
  }
  
  public void setIncomingVisitId(String incomingVisitId ) {
    this.incomingVisitId = incomingVisitId;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "tpa_id")
  public TpaMasterModel getTpaId() {
    return this.tpaId;
  }

  public void setTpaId(TpaMasterModel tpaId) {
    this.tpaId = tpaId;
  }

  @Column(name = "mr_no", length = 15)
  public String getMrNo() {
    return this.mrNo;
  }

  public void setMrNo(String mrNo) {
    this.mrNo = mrNo;
  }

  @Column(name = "points_redeemed", length = 15)
  public Integer getPointsRedeemed() {
    return this.pointsRedeemed;
  }
  
  public void setPointsRedeemed(Integer pointsRedeemed) {
    this.pointsRedeemed = pointsRedeemed;
  }

  @Column(name = "total_tax_rate", nullable = false, precision = 15, scale = 3)
  public BigDecimal getTotalTaxRate() {
    return totalTaxRate;
  }

  public void setTotalTaxRate(BigDecimal totalTaxRate) {
    this.totalTaxRate = totalTaxRate;
  }

  @Column(name = "amount", nullable = false, precision = 16, scale = 3)
  public BigDecimal getAmount() {
    return this.amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "display_date", length = 29, nullable = false)
  public Date getDisplayDate() {
    return this.displayDate;
  }

  public void setDisplayDate(Date displayDate) {
    this.displayDate = displayDate;
  }

  @Column(name = "counter", length = 20)
  public String getCounter() {
    return this.counter;
  }

  public void setCounter(String counter) {
    this.counter = counter;
  }

  @Column(name = "bank_name", length = 50)
  public String getBankName() {
    return this.bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  @Column(name = "reference_no", length = 100)
  public String getReferenceNo() {
    return this.referenceNo;
  }

  public void setReferenceNo(String referenceNo) {
    this.referenceNo = referenceNo;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "created_by", referencedColumnName = "emp_username", nullable = false)
  public UUserModel getCreatedBy() {
    return this.createdBy;
  }

  public void setCreatedBy(UUserModel createdBy) {
    this.createdBy = createdBy;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "created_at", length = 29)
  public Date getCreatedAt() {
    return this.createdAt;
  }

  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "modified_by", referencedColumnName = "emp_username")
  public UUserModel getModifiedBy() {
    return this.modifiedBy;
  }

  public void setModifiedBy(UUserModel modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "modified_at", length = 29)
  public Date getModifiedAt() {
    return this.modifiedAt;
  }

  public void setModifiedAt(Date modifiedAt) {
    this.modifiedAt = modifiedAt;
  }

  @Column(name = "remarks", length = 100)
  public String getRemarks() {
    return this.remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  @Column(name = "tds_amount", nullable = false, precision = 16, scale = 3)
  public BigDecimal getTdsAmount() {
    return this.tdsAmount;
  }

  public void setTdsAmount(BigDecimal tdsAmount) {
    this.tdsAmount = tdsAmount;
  }

  @Column(name = "paid_by", length = 30)
  public String getPaidBy() {
    return this.paidBy;
  }

  public void setPaidBy(String paidBy) {
    this.paidBy = paidBy;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "payment_mode_id", referencedColumnName = "mode_id")
  public PaymentModeMasterModel getPaymentModeId() {
    return this.paymentModeId;
  }

  public void setPaymentModeId(PaymentModeMasterModel paymentModeId) {
    this.paymentModeId = paymentModeId;
  }

  @Column(name = "card_type_id")
  public Integer getCardTypeId() {
    return this.cardTypeId;
  }

  public void setCardTypeId(Integer cardTypeId) {
    this.cardTypeId = cardTypeId;
  }

  @Column(name = "bank_batch_no", length = 100)
  public String getBankBatchNo() {
    return this.bankBatchNo;
  }

  public void setBankBatchNo(String bankBatchNo) {
    this.bankBatchNo = bankBatchNo;
  }

  @Column(name = "card_auth_code", length = 100)
  public String getCardAuthCode() {
    return this.cardAuthCode;
  }

  public void setCardAuthCode(String cardAuthCode) {
    this.cardAuthCode = cardAuthCode;
  }

  @Column(name = "card_holder_name", length = 100)
  public String getCardHolderName() {
    return this.cardHolderName;
  }

  public void setCardHolderName(String cardHolderName) {
    this.cardHolderName = cardHolderName;
  }

  @Column(name = "currency_id")
  public Integer getCurrencyId() {
    return this.currencyId;
  }

  public void setCurrencyId(Integer currencyId) {
    this.currencyId = currencyId;
  }

  @Column(name = "exchange_rate", precision = 16, scale = 3)
  public BigDecimal getExchangeRate() {
    return this.exchangeRate;
  }

  public void setExchangeRate(BigDecimal exchangeRate) {
    this.exchangeRate = exchangeRate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "exchange_date", length = 29)
  public Date getExchangeDate() {
    return this.exchangeDate;
  }

  public void setExchangeDate(Date exchangeDate) {
    this.exchangeDate = exchangeDate;
  }

  @Column(name = "currency_amt", precision = 16, scale = 3)
  public BigDecimal getCurrencyAmt() {
    return this.currencyAmt;
  }

  public void setCurrencyAmt(BigDecimal currencyAmt) {
    this.currencyAmt = currencyAmt;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "card_exp_date", length = 13)
  public Date getCardExpDate() {
    return this.cardExpDate;
  }

  public void setCardExpDate(Date cardExpDate) {
    this.cardExpDate = cardExpDate;
  }

  @Column(name = "card_number", length = 150)
  public String getCardNumber() {
    return this.cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  @Column(name = "credit_card_commission_percentage", precision = 16, scale = 3)
  public BigDecimal getCreditCardCommissionPercentage() {
    return this.creditCardCommissionPercentage;
  }

  public void setCreditCardCommissionPercentage(BigDecimal creditCardComissionPercentage) {
    this.creditCardCommissionPercentage = creditCardComissionPercentage;
  }

  @Column(name = "credit_card_commission_amount", precision = 16, scale = 3)
  public BigDecimal getCreditCardCommissionAmount() {
    return this.creditCardCommissionAmount;
  }

  public void setCreditCardCommissionAmount(BigDecimal creditCardComissionAmount) {
    this.creditCardCommissionAmount = creditCardComissionAmount;
  }

  @Column(name = "totp", length = 10)
  public String getTotp() {
    return this.totp;
  }

  public void setTotp(String totp) {
    this.totp = totp;
  }

  @Column(name = "edc_imei", length = 100)
  public String getEdcImei() {
    return this.edcImei;
  }

  public void setEdcImei(String edcImei) {
    this.edcImei = edcImei;
  }

  @Column(name = "other_deductions", precision = 16, scale = 3)
  public BigDecimal getOtherDeductions() {
    return this.otherDeductions;
  }

  public void setOtherDeductions(BigDecimal otherDeductions) {
    this.otherDeductions = otherDeductions;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "payment_received_date", length = 13)
  public Date getPaymentReceivedDate() {
    return this.paymentReceivedDate;
  }

  public void setPaymentReceivedDate(Date paymentReceivedDate) {
    this.paymentReceivedDate = paymentReceivedDate;
  }

  @Column(name = "center_id")
  public Integer getCenterId() {
    return centerId;
  }

  public void setCenterId(Integer centerId) {
    this.centerId = centerId;
  }

  @Column(name = "is_settlement", nullable = false)
  public boolean getIsSettlement() {
    return isSettlement;
  }

  public void setIsSettlement(boolean isSettlement) {
    this.isSettlement = isSettlement;
  }

  @Column(name = "unallocated_amount", precision = 16, scale = 3)
  public BigDecimal getUnallocatedAmount() {
    return unallocatedAmount;
  }

  public void setUnallocatedAmount(BigDecimal unallocatedAmount) {
    this.unallocatedAmount = unallocatedAmount;
  }
  
  @Column(name = "is_deposit", nullable = false)
  public boolean getIsDeposit() {
    return isDeposit;
  }

  public void setIsDeposit(boolean isDeposit) {
    this.isDeposit = isDeposit;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "receiptNo")
  public Set<BillReceiptsModel> getBillReceipts() {
    return billReceipts;
  }

  public void setBillReceipts(Set<BillReceiptsModel> billReceipts) {
    this.billReceipts = billReceipts;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "refundReceipt")
  public Set<ReceiptRefundReferenceModel> getRefundReceipts() {
    return refundReceipts;
  }

  public void setRefundReceipts(Set<ReceiptRefundReferenceModel> refundReceipts) {
    this.refundReceipts = refundReceipts;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "receipt")
  public Set<ReceiptRefundReferenceModel> getDeductedReceipts() {
    return deductedReceipts;
  }

  public void setDeductedReceipts(Set<ReceiptRefundReferenceModel> deductedReceipts) {
    this.deductedReceipts = deductedReceipts;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "receipt")
  public Set<ReceiptUsageModel> getReceiptUsages() {
    return receiptUsages;
  }

  public void setReceiptUsages(Set<ReceiptUsageModel> receiptUsages) {
    this.receiptUsages = receiptUsages;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "card_type_id", referencedColumnName = "card_type_id", insertable = false, updatable = false)
  public CardTypeMasterModel getCardTypeMasterModel() {
    return cardTypeMasterModel;
  }

  public void setCardTypeMasterModel(CardTypeMasterModel cardTypeMasterModel) {
    this.cardTypeMasterModel = cardTypeMasterModel;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "counter", referencedColumnName = "counter_id", insertable = false, updatable = false)
  public CountersModel getCountersModel() {
    return countersModel;
  }

  public void setCountersModel(CountersModel countersModel) {
    this.countersModel = countersModel;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "currency_id", referencedColumnName = "currency_id", insertable = false, updatable = false)
  public ForeignCurrencyModel getForeignCurrencyModel() {
    return foreignCurrencyModel;
  }

  public void setForeignCurrencyModel(ForeignCurrencyModel foreignCurrencyModel) {
    this.foreignCurrencyModel = foreignCurrencyModel;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "receiptId")
  public Set<ReceiptTaxModel> getReceiptTaxes() {
    return receiptTaxes;
  }

  public void setReceiptTaxes(Set<ReceiptTaxModel> receiptTaxes) {
    this.receiptTaxes = receiptTaxes;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "mr_no", insertable = false, updatable = false)
  public PatientDetailsModel getPatientDetails() {
    return patientDetails;
  }

  public void setPatientDetails(PatientDetailsModel patientDetails) {
    this.patientDetails = patientDetails;
  }

  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "center_id", insertable = false, updatable = false)
  public HospitalCenterMasterModel getCenterModel() {
    return centerModel;
  }

  public void setCenterModel(HospitalCenterMasterModel centerModel) {
    this.centerModel = centerModel;
  }
  
  @Transient
  public boolean getIsStoreReturn() {
    return isStoreReturn;
  }

  public void setIsStoreReturn(boolean isStoreReturn) {
    this.isStoreReturn = isStoreReturn;
  }

}
