package com.insta.hms.mdm.dischargesummarytemplates;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DischargeFormatModel generated by hbm2java
 */
@Entity
@Table(name = "discharge_format")
public class DischargeFormatModel implements java.io.Serializable {

	private DischargeFormatIdSequence id;

	public DischargeFormatModel() {
	}

	public DischargeFormatModel(DischargeFormatIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "formatId", column = @Column(name = "format_id", nullable = false, length = 50)),
			@AttributeOverride(name = "templateCaption", column = @Column(name = "template_caption", length = 100)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 1)),
			@AttributeOverride(name = "templateTitle", column = @Column(name = "template_title", length = 4000)),
			@AttributeOverride(name = "templateType", column = @Column(name = "template_type", length = 50)),
			@AttributeOverride(name = "reportFile", column = @Column(name = "report_file")),
			@AttributeOverride(name = "pheaderTemplateId", column = @Column(name = "pheader_template_id")),
			@AttributeOverride(name = "accessRights", column = @Column(name = "access_rights", length = 1)) })
	public DischargeFormatIdSequence getId() {
		return this.id;
	}

	public void setId(DischargeFormatIdSequence id) {
		this.id = id;
	}

}
