package com.insta.hms.mdm.resourceavailability;
// default package
// Generated Dec 8, 2017 2:32:11 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SchDefaultResAvailabilityDetailsModel generated by hbm2java
 */
@Entity
@Table(name = "sch_default_res_availability_details")
public class SchDefaultResAvailabilityDetailsModel implements java.io.Serializable {

	private SchDefaultResAvailabilityDetailsIdSequence id;

	public SchDefaultResAvailabilityDetailsModel() {
	}

	public SchDefaultResAvailabilityDetailsModel(SchDefaultResAvailabilityDetailsIdSequence id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "resSchId", column = @Column(name = "res_sch_id")),
			@AttributeOverride(name = "dayOfWeek", column = @Column(name = "day_of_week")),
			@AttributeOverride(name = "fromTime", column = @Column(name = "from_time", length = 15)),
			@AttributeOverride(name = "toTime", column = @Column(name = "to_time", length = 15)),
			@AttributeOverride(name = "availabilityStatus", column = @Column(name = "availability_status", length = 1)),
			@AttributeOverride(name = "remarks", column = @Column(name = "remarks", length = 100)),
			@AttributeOverride(name = "centerId", column = @Column(name = "center_id")) })
	public SchDefaultResAvailabilityDetailsIdSequence getId() {
		return this.id;
	}

	public void setId(SchDefaultResAvailabilityDetailsIdSequence id) {
		this.id = id;
	}

}
