package com.insta.hms.emr;

import com.bob.hms.common.RequestContext;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;

/**
 * This interface provides a contract for any medical record document provider
 * which need to expose their documents to EMR.
 *
 * Providers as solely responsible for providing EMR with the list of documents that need to be displayed in EMR.
 *
 *
 */
public interface EMRInterface {

	/**
	 * List all the medical documents associated with the given visit.
	 * All the details of the specified documents need to captured in the EMRDoc
	 *
	 * @param visitId
	 * @return
	 * @throws SQLException
	 * @throws ParseException
	 */
	public List<EMRDoc> listDocumentsByVisit(String visitId) throws Exception;

	/**
	 * List all the visit level documents for the given mr number.
	 *
	 * @param mrNo
	 * @return
	 * @throws Exception
	 */
	public List<EMRDoc> listVisitDocumentsForMrNo(String mrNo) throws Exception;

	/**
	 * List all the medical documents associated with the given mr number.
	 * This method is not mandatory for those providers which have all the documents already associated with a visit.
	 *
	 * @param mrNo
	 * @return
	 * @throws SQLException
	 * @throws ParseException
	 */
	public List<EMRDoc> listDocumentsByMrno(String mrNo) throws Exception;

	/**
	 * Returns the pdf raw bytes for the document requested.  If the document identified by
	 * docid does not support pdf conversion the provider will throw IllegalArgumentException.
	 *
	 * The docid as in EMRDoc uniquely identifies the document to the provider. It is expected that the
	 * docid is unique per provider. So, if one provider returns differnt kinds of documents,
	 * which can possibly have same "id"s, the provider must ensure that there is a prefix/suffix
	 * to distinguish between the types.
	 */
	public byte[] getPDFBytes(String docid, int printId) throws Exception;

	/**
	 *
	 * lists all the provider implementations
	 *
	 */
	public static enum Provider {
		/*
		 * TODO
		 *  ServicesProvider: from IP (now also OP) services: what services were rendered to the patient,
		 *    by the hospital. Could even be something as trivial as cotton wool supplied.
		 *  PrescriptionProvider: from OP (in future, also IP): what we asked the patient to do, whether
		 *   or not we did it within the hospital (see ServicesProvider).
		 *  ConsultationProvider: from OP (in future, also IP): recording of all consultations done
		 *   for the patient.
		 *  Diag Reports: Investigation Reports that we produced for the patient.
		 *    (or uploaded using diag module OutHouse reports, for example.)
		 *  Discharge Summary: Discharge summary: one per IP visit.
		 *  Scanned Docs: Various documents (typically scanned) for the patient.
		 *  Clinical: Treatment related documents for the patient.
		 *  Generic Docs: Misc docs generated by the system in the form of Generic Docs.
		 */
		CaseFormsProvider ("CaseFormsProvider",
				new com.insta.hms.emr.CaseFormsProviderImpl()),
		CaseSheetsProvider ("ConsultationsProvider",
				new com.insta.hms.emr.ConsultationsProviderImpl()),
		DIAGProvider ("DIAGProvider",
				new com.insta.hms.emr.DIAGProviderBOImpl()),
		DischargeSummaryProvider ("DischargeSummaryProvider",
				new com.insta.hms.emr.DischargeSummaryProviderImpl()), //Need to check for pdf
		TriageSummaryProvider ("TriageProvider",
				new com.insta.hms.emr.TriageSummaryProviderImpl()),
		AssessmentProvider ("AssessmentProvider",
				new com.insta.hms.emr.InitialAssessmentProviderImpl()),
		GenericDocumentsProvider ("GenericDocumentsProvider",
				new com.insta.hms.emr.GenericDocumentsProviderBOImpl()),
		VitalParamProvider ("VitalParamProvider",
				new com.insta.hms.emr.VitalParamProviderBOImpl()),
		IntakeOutputParamProvider ("IntakeOutputParamProvider",
				new com.insta.hms.emr.IntakeOutputParamProviderBOImpl()),
		ServiceProvider ("ServiceProvider" ,
				new com.insta.hms.emr.ServiceProviderBOImpl()),
		MealsPrescriptionsProvider ("MealsPrescriptionsProvider",
				new com.insta.hms.emr.MealsPrescriptionsProviderBOImpl()),
		DietChartProvider ("DietChartProvider",
				 new com.insta.hms.emr.DietChartProviderBOImpl()),
		MLCFormProvider("MLCFormProvider",
				new com.insta.hms.emr.MLCFormProviderBOImpl()),// Need to check for user name
		RegistrationFormProvider("RegistrationFormProvider",
				new com.insta.hms.emr.RegistrationFormsProviderBOImpl()),
		OperationProvider("OperationProvider",
				new com.insta.hms.emr.OperationProviderBOImpl()),
		DialysisSessionsProvider("DialysisSessionsProvider",
				new com.insta.hms.emr.DialysisSessionsProviderBOImpl()),
		MRDCodesProvider("MRDCodesProvider",
				new com.insta.hms.emr.MRDCodesDocProviderBOImpl()),
		OphthalmologyProvider("OphthalmologyProvider",
				new com.insta.hms.emr.OphthalmologyProviderBOImpl()),
		PlanCardProvider("PlanCardProvider",
				new com.insta.hms.emr.PlanCardProviderBOImpl()),
		CorporateCardProvider("CorporateCardProvider",
				new com.insta.hms.emr.CorporateCardProviderBOImpl()),
		NationalCardProvider("NationalCardProvider",
				new com.insta.hms.emr.NationalCardProviderBOImpl()),
		ScoreCardProvider("ScoreCardProvider",
				new com.insta.hms.emr.ScoreCardProviderImpl()),
		ClinicalLabResultsProvider("ClinicalLabResultsProvider",
				new com.insta.hms.emr.ClinicalLabResultsProviderImpl()),
		ProgressNotesProvider("ProgressNotesProvider",
				new com.insta.hms.emr.ProgressNotesProviderImpl()),
		DoctorOrderProvider("DoctorOrderProvider",
				new com.insta.hms.emr.DoctorOrderProviderImpl()),
		VisitSummaryRecordsProvider("VisitSummaryRecordsProvider",
				new com.insta.hms.emr.VisitSummaryRecordsProviderImpl()),
		OtRecordsProvider("OtRecordsProvider",
				new com.insta.hms.emr.OtRecordsProviderImpl()),
		GrowthChartsProvider("GrowthChartsProvider",
				new com.insta.hms.emr.GrowthChartsProviderImpl()),
		EandMcalculatorResultsProvider("EandMcalculatorResultsProvider",
				new com.insta.hms.emr.EandMcalculatorResultsProviderImpl()),
	    MedicationChartProvider("MedicationChartProvider",
	    		new com.insta.hms.emr.MedicationChartProviderImpl()
		),
		GenericInstFormProvider("GenericInstaFormProvider",
				new com.insta.hms.GenericForms.GenericFormProviderImpl()),
		VaccinationProvider("VaccinationProvider",
		    new com.insta.hms.emr.VaccinationProviderImpl()),
		;

		private final EMRInterface providerImpl;
		private final String providerName;

		private Provider(String providerName, EMRInterface providerImpl){
			this.providerImpl = providerImpl;
			this.providerName = providerName;
		}

		public EMRInterface getProviderImpl(){return providerImpl;};
		public String getProviderName() { return providerName; }

	}

	public class Helper {
		public static boolean getAuthorized(String username,
				String access_rights) {
			int roleId = RequestContext.getRoleId();
			String loggedInUserId = RequestContext.getUserName();
			boolean authorized = false;

			if (access_rights == null || access_rights.equals(""))
				access_rights = "U";
			if (username == null)
				username = "";

			/*
			 * if authorized check for the rolid and logged in user and
			 * document saved user.
			 */
			if (access_rights.equals("A")) {
				if (roleId == 1 || roleId == 2
						|| loggedInUserId.equals(username) || loggedInUserId.equals("addons_user")) {
					authorized = true;
				}
			} else {
				authorized = true;
			}

			return authorized;
		}
	}
}

